# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/ar.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "الرئيسية",
    "APP_TITLE": "منصة OTMEGA للذكاء الاصطناعي",
    "APP_SUBTITLE": "المستشار الذكي",
    "CHAT_PLACEHOLDER": "اكتب رسالتك...",
    "CHAT_SEND_BUTTON": "إرسال",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 قد يخطئ المستشار، لذا تحقق من المعلومات.",
    "STATUS_ONLINE": "متصل",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "القائمة",
    "ICON_NEW_CHAT": "دردشة جديدة",
    "ICON_HISTORY": "السجل",
    "ICON_TEMPLATES": "القوالب",
    "ICON_SETTINGS": "الإعدادات",
    "ICON_USER_PROFILE": "ملف المستخدم",
    "ICON_QUICK_ACTIONS": "إجراءات سريعة",
    "ICON_PINNED": "مثبت",
    "ICON_GALLERY": "المعرض",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "تثبيت التطبيق",
    "PWA_ANDROID_MSG": "ثبّت هذا التطبيق على جهازك لتجربة أفضل وإمكانية الوصول دون اتصال.",
    "PWA_IOS_MSG": "لتثبيت هذا التطبيق على iPhone/iPad:\n1. اضغط زر المشاركة أدناه\n2. اختر إضافة إلى الشاشة الرئيسية",
    "PWA_BTN_INSTALL": "تثبيت",
    "PWA_BTN_LATER": "ربما لاحقاً",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "تسجيل الدخول إلى شبكة المستشارين",
    "AUTH_HEADER_SIGNUP": "إنشاء حسابك الموحّد",
    "AUTH_HEADER_LOGIN_NETWORK": "تسجيل الدخول إلى شبكة المستشارين",
    "AUTH_HEADER_SIGNUP_UNIFIED": "إنشاء حسابك الموحّد",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "تسجيل الدخول",
    "AUTH_BUTTON_SIGNUP": "إنشاء حساب",
    "AUTH_BUTTON_GOOGLE": "المتابعة باستخدام Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "نسيت كلمة المرور",
    "AUTH_BUTTON_SEND_RESET_LINK": "إرسال رابط إعادة التعيين",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "ليس لديك حساب؟ سجّل الآن",
    "AUTH_PROMPT_LOGIN": "لديك حساب بالفعل؟ سجّل الدخول",
    "AUTH_HELPER_TEXT_SIGNUP": "أنت تنشئ حساباً موحداً يمكنك استخدامه للوصول إلى جميع المستشارين في هذه المنصة.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "أنت تنشئ حساباً موحداً يمكنك استخدامه للوصول إلى جميع المستشارين في هذه المنصة.",
    "AUTH_HELPER_TEXT_LOGIN": "استخدم الحساب نفسه (البريد الإلكتروني/كلمة المرور أو Google) الذي استخدمته مع المستشارين الآخرين في هذه الشبكة.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "استخدم الحساب نفسه (البريد الإلكتروني/كلمة المرور أو Google) الذي استخدمته مع المستشارين الآخرين في هذه الشبكة.",
    "AUTH_FORGOT_PASSWORD_LINK": "هل نسيت كلمة المرور؟",
    "AUTH_FORGOT_PASSWORD_TITLE": "إعادة تعيين كلمة المرور",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "البريد الإلكتروني",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "جارٍ تسجيل دخولك...",
    "AUTH_STATUS_LOADING_SIGNUP": "جارٍ إنشاء حسابك...",
    "AUTH_STATUS_LOADING_RESET": "جارٍ إرسال رابط إعادة التعيين...",
    "AUTH_STATUS_SUCCESS_LOGIN": "تم تسجيل الدخول بنجاح! جارٍ إعادة التحميل...",
    "AUTH_STATUS_SUCCESS_RESET": "تم إرسال رابط إعادة التعيين بنجاح. يرجى التحقق من بريدك الإلكتروني.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "تم إرسال رابط إعادة تعيين كلمة المرور بنجاح. يرجى التحقق من بريدك الإلكتروني.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    "AUTH_ERROR_EMAIL_EXISTS": "يوجد حساب بهذا البريد الإلكتروني بالفعل في شبكة المستشارين.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "يوجد حساب بهذا البريد الإلكتروني بالفعل. يرجى تسجيل الدخول. أنت حالياً عضو في:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "يوجد حساب بهذا البريد الإلكتروني بالفعل في شبكة المستشارين. يرجى إغلاق هذه النافذة واستخدام قسم تسجيل الدخول بالبريد الإلكتروني نفسه وكلمة المرور السابقة.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "أنت حالياً عضو في:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "البريد الإلكتروني وكلمة المرور مطلوبان.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "تم إنشاء الحساب، لكن فشل إعداد العضوية. يرجى التواصل مع الدعم.",
    "AUTH_ERROR_DEFAULT": "حدث خطأ. يرجى المحاولة مرة أخرى.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "حمولة التحكم في لافتة الضيف مطلوبة.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "يمكن للمستخدم صفر فقط تحديث عناصر التحكم في لافتة الضيف.",
    "AUTH_FORGOT_PASSWORD_ERROR": "فشل إرسال رابط إعادة التعيين. يرجى المحاولة مرة أخرى.",
    "INVITE_REPLY_EMAIL_SENT": "تم إرسال بريد دعوة Collabra إلى صديقك على {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "تمت إعادة إرسال بريد دعوة Collabra إلى صديقك على {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "إظهار كلمة المرور",
    "AUTH_PASSWORD_TOGGLE_HIDE": "إخفاء كلمة المرور",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "حسناً",
    "GENERAL_CANCEL": "إلغاء",
    "GENERAL_CLOSE": "إغلاق",
    "GENERAL_SEND": "إرسال",
    "GENERAL_SEARCH": "بحث",
    "GENERAL_RESET": "إعادة تعيين",
    "GENERAL_ENABLE": "تفعيل",
    "GENERAL_LOADING": "جارٍ التحميل...",
    "GENERAL_DELETE": "حذف",
    "GENERAL_DELETING": "جارٍ الحذف...",
    "GENERAL_SAVE_PASSWORD": "حفظ كلمة المرور",
    "AUTH_REMEMBER_EMAIL_LABEL": "تذكّر البريد الإلكتروني",
    "GENERAL_SAVING": "جارٍ الحفظ...",
    "GENERAL_SENDING": "جارٍ الإرسال...",
    "GENERAL_REMOVING": "جارٍ الإزالة...",
    "GENERAL_CONFIRM_REMOVAL": "تأكيد الإزالة",
    "GENERAL_EMPTY": "فارغ",
    "GENERAL_UNAVAILABLE": "غير متاح",
    "GENERAL_ENABLED": "مفعّل",
    "GENERAL_DISABLED": "معطّل",
    "GENERAL_GRANTED": "ممنوح",
    "GENERAL_DENIED": "مرفوض",
    "GENERAL_DEFAULT": "افتراضي",
    "GENERAL_UNSUPPORTED": "غير مدعوم",
    "GENERAL_PUBLIC": "عام",
    "GENERAL_PRIVATE": "خاص",
    "GENERAL_USERNAME": "اسم المستخدم",
    "GENERAL_EMAIL": "البريد الإلكتروني",
    "GENERAL_YOU": "أنت",
    "GENERAL_USER": "المستخدم",
    "GENERAL_UNKNOWN": "غير معروف",
    "GENERAL_VISITOR": "زائر",
    "GENERAL_PROFILE": "الملف الشخصي",
    "GENERAL_BANNER": "البانر",
    "GENERAL_UNKNOWN_BANNER": "بانر غير معروف",
    "GENERAL_ADVISOR_BANNER": "بانر المستشار",
    "GENERAL_NOT_AVAILABLE": "غير متاح",
    "GENERAL_NOT_SELECTED": "غير محدد",
    "GENERAL_NO_EMAIL_FOUND": "لم يتم العثور على بريد إلكتروني",
    "GENERAL_USER_ZERO_ONLY": "User Zero فقط",
    "GENERAL_CONNECTION_STATE": "حالة الاتصال",
    "GENERAL_DISPLAY_ONLY": "للعرض فقط",
    "GENERAL_TEXTAREA": "منطقة نص",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "القائمة (LCAC)",
    "HEADER_CHAT_CCAC": "الدردشة (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "إجراءات سريعة (RCAC)",
    "HEADER_CHANGE_STATUS": "تغيير الحالة",
    "HEADER_OT_COIN_BALANCE": "رصيد OT Coin",
    "HEADER_ALT_USER": "المستخدم",
    "STATUS_BUSY": "مشغول",
    "STATUS_AWAY": "بعيد",
    "STATUS_OFFLINE": "غير متصل",
    "STATUS_INVISIBLE": "مخفي",
    "NETWORK_CHECKING_CONNECTION": "جارٍ فحص الاتصال...",
    "NETWORK_ONLINE_LATENCY": "متصل (زمن الاستجابة: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "الشبكة: جيدة (اضغط لاختبار الاتصال)",
    "CHAT_TARGET_ALT": "هدف الدردشة",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "بحث...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "فتح صورة ملف {name} الشخصي",
    "CHAT_MESSAGE_INPUT_ARIA": "حقل إدخال الرسالة",
    "CHAT_TOGGLE_VIEW_ARIA": "تبديل العرض",
    "CHAT_ADD_USER_ARIA": "إضافة مستخدم",
    "CHAT_ATTACH_ARIA": "إرفاق",
    "CHAT_MIC_ARIA": "الميكروفون",
    "CHAT_SEND_ARIA": "إرسال",
    "CHAT_SEARCH_ARIA": "بحث",
    "CHAT_OPEN_SEARCH_ARIA": "فتح البحث",
    "CHAT_CLOSE_SEARCH_ARIA": "إغلاق البحث",
    "CHAT_ATTACHMENT_ALT": "مرفق",
    "CHAT_PREVIEW_ALT": "معاينة",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "إزالة المرفق",
    "CHAT_REPLYING_TO": "رداً على",
    "CHAT_CANCEL_REPLY_ARIA": "إلغاء الرد",
    "CHAT_UPLOADING": "جارٍ الرفع...",
    "CHAT_LOADING_CHATS": "جارٍ تحميل الدردشات...",
    "CHAT_SEND_FAILED": "فشل الإرسال",
    "CHAT_SEND_FAILED_RETRY": "فشل الإرسال. يرجى إعادة المحاولة.",
    "CHAT_RETRY": "إعادة المحاولة",
    "CHAT_EDITED": "تم التعديل",
    "CHAT_TYPING": "يكتب",
    "CHAT_LOADING": "جارٍ التحميل",
    "CHAT_PENDING_INVITATION": "دعوة معلقة",
    "CHAT_PENDING_INVITATION_MIN": "{count} دقيقة دعوة معلقة",
    "CHAT_PENDING_INVITATION_HR": "{count} ساعة دعوة معلقة",
    "CHAT_PENDING_INVITATION_DAY": "{count} يوم دعوة معلقة",
    "CHAT_WAITING_FOR_YOU": "{label} - بانتظارك",
    "CHAT_PENDING_ACCEPTANCE": "{label} - في انتظار القبول",
    "CHAT_MICROPHONE_ACCESS_DENIED": "تم رفض الوصول إلى الميكروفون.",
    "CHAT_UPLOAD_FAILED": "فشل الرفع: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "يتطلب الرفع اتصالاً بالإنترنت. يرجى المحاولة مرة أخرى عندما تكون متصلاً.",
    "OFFLINE_SHOWING_SAVED_DATA": "",
    "OFFLINE_DATA_MAY_BE_OUTDATED": "",
    "OFFLINE_ACTION_REQUIRES_CONNECTION": "",
    "OFFLINE_MESSAGE_WAITING_CONNECTION": "",
    "OFFLINE_PENDING_MESSAGES_TOOLTIP": "",
    "APP_BACK_EXIT_HINT": "",
    "CHAT_ERROR_AUTH": "خطأ في المصادقة",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "اسم الملف أو content_type مفقود",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id أو target_id مفقود",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id مفقود للرفع غير الخاص بالصورة الرمزية",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path للصورة الرمزية غير صالح",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "عميل خدمة Supabase غير متاح",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "تأكيد قراءة الصورة الرمزية صالح فقط في سياق دردشة المستشار",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "لم يتم العثور على رسالة تدفق الصورة الرمزية أو أنها غير مؤهلة لتأكيد القراءة",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "فشل إتمام رسالة الصورة الرمزية كمقروءة",
    "CHAT_ATTACHMENT_COUNT_ONE": "مرفق واحد",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} مرفقات",
    "CHAT_VOICE_NOTE": "ملاحظة صوتية",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "الدردشة غير متاحة. هذا المستخدم حظرك.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "الدردشة غير متاحة. لقد حظرت هذا المستخدم.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "تم حظر الوصول إلى الحساب بموجب السياسة.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "الدردشة غير متاحة. هذا الحساب محظور نهائياً بواسطة User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "الدردشة غير متاحة. الحظر المتبادل نشط.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "الدردشة غير متاحة بسبب سياسة الحظر.",
    "MESSAGE_PREVIEW_PHOTO": "صورة",
    "MESSAGE_PREVIEW_VOICE": "رسالة صوتية",
    "MESSAGE_PREVIEW_VIDEO": "فيديو",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "ملف",
    "MESSAGE_PREVIEW_MESSAGE": "رسالة",
    "MESSAGE_PREVIEW_SYSTEM": "رسالة نظام",
    "MESSAGE_PREVIEW_NEW": "رسالة جديدة",
    "MESSAGE_UNKNOWN_FILE": "ملف غير معروف",
    "MESSAGE_AUDIO_ATTACHMENT": "مرفق صوتي",
    "MESSAGE_FILE_ATTACHMENT": "مرفق",
    "BANNER_INVITED_BY": "مدعو بواسطة {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "نتائج البحث",
    "SEARCH_QUERY_LABEL": "الاستعلام:",
    "SEARCH_LOADING_VISIBILITY": "جارٍ تحميل قابلية ظهور البحث...",
    "SEARCH_NO_RESULTS": "لم يتم العثور على نتيجة ضمن نطاق البحث الحالي.",
    "SHARE_WITH_COLLABRA": "مشاركة مع Collabra",
    "SHARE_SEND_TO": "إرسال إلى",
    "SHARE_SELECT_ONE_BANNER": "اختر بانراً واحداً",
    "SHARE_BANNER_LIST_ARIA": "قائمة البانرات",
    "SHARE_NO_MATCHING_BANNER": "لا يوجد بانر مطابق",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "أضف تعليقاً...",
    "SHARE_RECENT_CHATS": "الدردشات الأخيرة",
    "SHARE_LEFT_LIST": "القائمة اليسرى",
    "SHARE_RIGHT_LIST": "القائمة اليمنى",
    "SHARE_UNTITLED_BANNER": "بانر بلا عنوان",
    "SHARE_SHARED_CONTENT": "محتوى مشترك",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "تعذر فتح المحتوى المشترك.",
    "SHARE_OPEN_BANNER_FAILED": "تعذر فتح البانر المحدد.",
    "SHARE_ONE_PHOTO_SELECTED": "تم تحديد صورة واحدة",
    "SHARE_MANY_PHOTOS_SELECTED": "تم تحديد {count} صور",
    "SHARE_ONE_FILE_SELECTED": "تم تحديد ملف واحد",
    "SHARE_MANY_FILES_SELECTED": "تم تحديد {count} ملفات",
    "FORWARD_MESSAGE_TITLE": "إعادة توجيه الرسالة",
    "FORWARD_SELECT_RECIPIENTS": "اختر المستلمين",
    "FORWARD_NO_OTHER_BANNER": "لا يوجد بانر آخر متاح.",
    "FORWARD_SEND_TO_COUNT": "إرسال إلى {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "اختر بانراً واحداً على الأقل.",
    "FORWARD_FAILED_DEFAULT": "فشلت إعادة التوجيه. يرجى المحاولة مرة أخرى.",
    "FORWARD_PARTIAL_SENT": "تم إرسال {count}. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "لم يتم العثور على الرسالة المصدر لإعادة التوجيه",
    "FORWARD_NO_FORWARDABLE_CONTENT": "لا تحتوي هذه الرسالة بعد على محتوى قابل لإعادة التوجيه",
    "FORWARD_DESTINATION_MISSING": "وجهة إعادة التوجيه مفقودة",
    "FORWARD_MESSAGE_PREVIEW": "رسالة معاد توجيهها",
    "MENU_PASTE": "لصق",
    "MENU_COPY": "نسخ",
    "MENU_REPLY": "رد",
    "MENU_FORWARD": "إعادة توجيه",
    "MENU_REMOVE_INVITATION": "إزالة الدعوة",
    "MENU_REMOVE_FROM_LIST": "إزالة من القائمة",
    "MENU_GOODBYE_GUEST": "وداعًا أيها الضيف",
    "MENU_ADD_TO_LIST": "إضافة إلى القائمة",
    "MENU_REJECT_INVITATION": "رفض الدعوة",
    "MENU_FRONTEND_VERSION": "إصدار الواجهة الأمامية",
    "MENU_BANNER_HEADER": "بانر - {zone}",
    "MENU_BANNER_INFO": "معلومات البانر: {title}",
    "MENU_MESSAGE_BUBBLE": "فقاعة الرسالة",
    "MENU_CHAT_CANVAS_HEADER": "لوحة الدردشة - {zone}",
    "MENU_CANVAS_INFO": "معلومات اللوحة",
    "MENU_CHAT_CANVAS_SUBLABEL": "منطقة المحادثة / سطح الدردشة الحالي",
    "MENU_INPUT_AREA_HEADER": "منطقة الإدخال - {zone}",
    "MENU_INPUT_AREA_INFO": "معلومات منطقة الإدخال: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "سطح الكتابة وأدوات الإجراءات في الأسفل",
    "MENU_HEADER": "الرأس - {zone}",
    "MENU_HEADER_INFO": "معلومات الرأس: {title}",
    "MENU_HEADER_DESCRIPTION": "التنقل العلوي وعناصر التحكم بالصفحة",
    "MENU_ZONE_HEADER": "المنطقة - {zone}",
    "MENU_ZONE_SPACE_INFO": "معلومات مساحة المنطقة",
    "MENU_EMPTY_LIST_SURFACE": "سطح فارغ/قائمة",
    "MENU_BLOCK": "حظر",
    "MENU_UNBLOCK": "إلغاء الحظر",
    "MENU_HIDE_IN_SEARCH": "إخفاء في البحث",
    "MENU_UNHIDE_IN_SEARCH": "إظهار في البحث",
    "MENU_VISIBLE_IN_SEARCH": "ظاهر في البحث",
    "MENU_HIDDEN_IN_SEARCH": "مخفي في البحث",
    "MENU_VISIBLE_IN_USER_LIST": "ظاهر في قائمة المستخدمين",
    "MENU_HIDDEN_IN_USER_LIST": "مخفي في قائمة المستخدمين",
    "MENU_NOT_BLOCKED": "غير محظور",
    "MENU_BLOCKED": "محظور",
    "MENU_FRONTEND_VERSION_LOADING": "جارٍ التحميل...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "جارٍ تحميل القيمة لكل بانر من الخلفية. لا يتم تحديد أي خيار كنشط حتى تصل استجابة قاعدة البيانات.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "تعذر تحميل قيمة الخلفية. لا يتم عرض أي خيار نشط موثوق.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "قيمة قاعدة البيانات الصريحة لكل بانر هي {overrideVersion}. القيمة الافتراضية العامة هي {globalDefaultVersion}. يجب على المستخدم المستهدف تحديث التطبيق بالكامل أو إعادة فتحه لكي يطبقها تمهيد بدء التشغيل.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "لا توجد قيمة صريحة مخزنة لكل بانر في قاعدة البيانات. FeV2.0.0 نشط افتراضياً. القيمة الافتراضية العامة هي {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "تكون قيمة قاعدة البيانات الصريحة لكل بانر نشطة بعد إعادة تحميل تطبيق المستخدم المستهدف بالكامل",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "لا توجد قيمة صريحة مخزنة لكل بانر؛ هذه هي حالة FeV2.0.0 الفردية الافتراضية",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "هذا الخيار يساوي أيضاً القيمة الافتراضية العامة الحالية",
    "MENU_DELETE_PERMANENT_CONFIRM": "هل تريد حذف {target} نهائياً من قاعدة البيانات؟ يؤدي ذلك إلى إزالة الحساب وسجل الدردشة والاعتماديات ويفرض مسار دعوة جديداً بالكامل لأي عودة مستقبلية.",
    "MENU_DELETE_PERMANENTLY": "حذف نهائياً",
    "MENU_REFRESH_PAGE": "تحديث الصفحة",
    "MENU_LOG_OFF": "تسجيل الخروج",
    "MENU_HARD_RELOAD": "إعادة تحميل قسرية",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "البريد الإلكتروني (مستخدم مسؤول)",
    "AUTH_PASSWORD_PLACEHOLDER": "كلمة المرور",
    "AUTH_CONNECTING": "جارٍ الاتصال...",
    "AUTH_SIGNING_OUT": "جارٍ تسجيل الخروج...",
    "AUTH_BACK_TO_LOGIN": "العودة إلى تسجيل الدخول",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "استجابة الخادم غير صالحة: لم يتم العثور على رمز مميز.",
    "AUTH_LOGIN_FAILED": "فشل تسجيل الدخول",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "كلمتا المرور غير متطابقتين.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "كلمتا المرور غير متطابقتين!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "يجب أن تتطابق كلمتا المرور تماماً.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "كلمة مرور جديدة",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "تأكيد كلمة المرور",
    "AUTH_CHANGE_PASSWORD": "تغيير كلمة المرور",
    "AUTH_SAVING_PASSWORD": "جارٍ الحفظ...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "تم تحديث كلمة المرور بنجاح.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "تعذر تغيير كلمة المرور حالياً.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "يجب تسجيل الدخول لتغيير كلمة المرور.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "تبديل إظهار كلمة المرور الجديدة",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "تبديل إظهار تأكيد كلمة المرور",
    "REGISTER_TITLE": "إكمال التسجيل",
    "REGISTER_SUBTITLE": "يرجى تعيين كلمة المرور يدوياً.",
    "REGISTER_CREATING_ACCOUNT": "جارٍ إنشاء الحساب...",
    "REGISTER_FINISH_SETUP": "إنهاء الإعداد",
    "REGISTER_FAILED_SET_PASSWORD": "فشل تعيين كلمة المرور",
    "INVITE_EMAIL_INSTRUCTION": "يرجى إدخال بريد المدعو الإلكتروني (الصيغة: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "دعوة",
    "INVITE_EMAIL_REQUIRED": "يرجى إدخال بريد المدعو الإلكتروني.",
    "INVITE_EMAIL_INVALID": "صيغة البريد الإلكتروني غير صالحة. يرجى استخدام: user@example.com",
    "PENDING_INVITATION_TITLE": "دعوة معلقة",
    "PENDING_INVITATION_REMOVE_QUESTION": "هل تريد إزالة هذه الدعوة المعلقة من قاعدة البيانات؟",
    "PENDING_INVITATION_KEEP": "الاحتفاظ بالدعوة",
    "PENDING_INVITATION_REMOVAL_FAILED": "فشلت الإزالة.",
    "REMOVE_FROM_LIST_TITLE": "إزالة من القائمة",
    "REMOVE_FROM_LIST_WARNING": "هل تريد إزالة هذا المستخدم من القائمتين الآن؟ سيتم قطع الوصول إلى الدردشة فوراً. طريق العودة الوحيد هو دعوة جديدة.",
    "REMOVE_FROM_LIST_KEEP": "إبقاء المستخدم في القائمة",
    "REMOVE_FROM_LIST_FAILED": "فشلت الإزالة من القائمة.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "الإعداد والحالة المباشرة",
    "PERMISSION_DIALOG_ARIA": "الإعداد والحالة المباشرة",
    "PERMISSION_TRIGGER_ARIA": "مشغل نافذة الإعدادات المنبثقة",
    "PERMISSION_CLOSE_ARIA": "إغلاق نافذة الأذونات المنبثقة",
    "PERMISSION_LIVE_STATUS": "الحالة المباشرة",
    "PERMISSION_SYSTEM_PERMISSION": "إذن النظام",
    "PERMISSION_APP_PUSH": "إشعارات التطبيق الفورية",
    "PERMISSION_LOCATION_PERMISSION": "إذن الموقع",
    "PERMISSION_APP_LOCATION": "موقع التطبيق",
    "PERMISSION_CONTROLS": "عناصر التحكم في الأذونات",
    "PERMISSION_PUSH_NOTIFICATIONS": "الإشعارات الفورية",
    "PERMISSION_LOCATION_ACCESS": "الوصول إلى الموقع",
    "PERMISSION_IN_APP_SETTINGS": "الإعدادات داخل التطبيق",
    "PERMISSION_ALERT_SOUND": "صوت التنبيه",
    "PERMISSION_APP_BADGE": "شارة التطبيق",
    "PERMISSION_PASSWORD_SETTINGS": "إعدادات كلمة المرور",
    "PERMISSION_NAVIGATION_STATUS": "حالة التنقل",
    "PERMISSION_SELECTED_ZONE": "المنطقة المحددة",
    "PERMISSION_STAGED_CHAT_BANNER": "بانر الدردشة المرحلي",
    "PERMISSION_CANVAS_CONTENT": "محتوى اللوحة",
    "PERMISSION_YOUR_DEVICES": "أجهزتك ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "تحديث قائمة الأجهزة",
    "PERMISSION_REFRESH_LIST": "تحديث القائمة",
    "PERMISSION_NO_REGISTERED_DEVICES": "لم يتم العثور على أجهزة مسجلة.",
    "PERMISSION_RESIZE_POPUP_ARIA": "تغيير حجم نافذة الإعدادات المنبثقة",
    "PERMISSION_TOGGLE_PUSH_ARIA": "تبديل الإشعارات الفورية",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "تبديل الوصول إلى الموقع",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "تبديل صوت التنبيه",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "تبديل شارة التطبيق",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "تبديل ظهور الملف الشخصي",
    "PERMISSION_OFF_IN_V1": "متوقف في v1",
    "PERMISSION_CHAT": "الدردشة",
    "PERMISSION_BANNER_LIST": "قائمة البانرات",
    "PERMISSION_PUSH_DISABLED_V1": "الإشعارات الفورية معطلة لإصدار v1 على Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "الإشعارات الفورية مفعلة على هذا الجهاز.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "إشعارات النظام محظورة. اضغط لفتح تعليمات الإعدادات.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "فعّلها لتحسين موثوقية التسليم.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "لتعطيل إشعارات النظام، افتح إعدادات إشعارات المتصفح/الموقع واضبط هذا الموقع على حظر.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "لتغيير إذن إشعارات النظام، افتح إعدادات إشعارات المتصفح/الموقع واضبط هذا الموقع على سماح.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "الوصول إلى الموقع مفعّل لفرز LCAC حسب المسافة وتحديد الموضع على الخريطة.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "واجهة برمجة تطبيقات الموقع غير مدعومة في هذه البيئة.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "الوصول إلى الموقع محظور. اضغط لفتح تعليمات الإعدادات.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "فعّل للسماح بفرز LCAC الدقيق حسب المسافة وتحديد الموضع على الخريطة داخل التطبيق.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "الوصول إلى الموقع غير مدعوم في هذه البيئة.",
    "PERMISSION_LOCATION_DISABLE_HELP": "لتعطيل الوصول إلى الموقع، افتح إعدادات موقع المتصفح/الموقع واضبط هذا الموقع على حظر.",
    "PERMISSION_LOCATION_ALLOW_HELP": "لتفعيل الوصول إلى الموقع من أجل الفرز حسب المسافة وتحديد الموضع على الخريطة داخل التطبيق، افتح إعدادات موقع المتصفح/الموقع واضبط هذا الموقع على سماح.",
    "PERMISSION_DEVICE_LOAD_FAILED": "تعذر تحميل الأجهزة المسجلة حالياً.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "جارٍ تحميل جسر واجهة المستخدم...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "جارٍ تحميل الجسر المحلي...",
    "RUNTIME_LOADING_BACKEND": "جارٍ تحميل الخلفية...",
    "RUNTIME_LOADING": "جارٍ التحميل...",
    "RUNTIME_LOADING_FROM_DATABASE": "جارٍ التحميل من قاعدة البيانات...",
    "RUNTIME_BACKEND_CONNECTED": "الخلفية متصلة",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "الرجوع الاحتياطي المخزن مؤقتاً نشط",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "الرجوع الافتراضي الاحتياطي نشط",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "قيم الرجوع الافتراضية الاحتياطية نشطة",
    "RUNTIME_SAVING_THROUGH_BACKEND": "جارٍ الحفظ عبر الخلفية...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "تم الحفظ في خدمة الخلفية",
    "RUNTIME_SAVE_FAILED": "فشل الحفظ",
    "RUNTIME_LOAD_FAILED": "فشل التحميل",
    "RUNTIME_CONNECTED": "متصل",
    "RUNTIME_LOGIN_REQUIRED": "تسجيل الدخول مطلوب",
    "RUNTIME_SAVED": "تم الحفظ",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "واجهة المستخدم جاهزة - وقت التشغيل قيد الانتظار",
    "RUNTIME_BACKEND_REJECTED_MODEL": "رفضت خدمة محدد الخلفية المحمية خيار النموذج المطلوب أو تعذر عليها حفظه.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "رفضت خدمة محدد الخلفية المحمية تغيير توجيه WF1 المطلوب أو تعذر عليها حفظه.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "يقرأ المحدد الآن الإعداد النشط وتوجيه Qwen والخيارات المسموح بها من خدمة الخلفية المحمية.",
    "RUNTIME_WF1_SELECTOR_CACHED": "خدمة محدد الخلفية غير متاحة حالياً، لذلك يتم استخدام آخر حالة محدد مخزنة مؤقتاً.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "القيم الافتراضية للمحدد نشطة لأنه تعذر تحميل أي حالة من الخلفية أو من الذاكرة المؤقتة.",
    "RUNTIME_WF1_SELECTOR_SAVED": "حدّثت خدمة محدد الخلفية المحمية إعداد توجيه WF1 النشط وأنعشت ذاكرة نطاق وقت التشغيل المؤقتة.",
    "FRONTEND_VERSION_TITLE": "إصدار الواجهة الأمامية",
    "FRONTEND_VERSION_HELPER_ACTIVE": "يتحكم هذا المحدد في إصدار الواجهة الأمامية النشط لجميع المستخدمين. FeV2.0.0 نشط.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "يقرأ هذا المحدد إصدار الواجهة الأمامية النشط من config_domain_registry. يتم حل وقت التشغيل إلى FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "تعذر تحميل إعداد إصدار الواجهة الأمامية من الخلفية، لذلك يبقى الافتراضي المرمّز FeV2.0.0 نشطاً حتى يتمكن تمهيد بدء التشغيل من قراءة الخدمة المحمية مرة أخرى.",
    "FRONTEND_VERSION_HELPER_SAVED": "تم حفظ إصدار الواجهة الأمامية النشط في config_domain_registry. يطبق التحديث الكامل أو التحميل التالي للتطبيق قيمة وقت التشغيل.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "تعذرت على خدمة التحكم بإصدار الواجهة الأمامية في الخلفية حفظ الإصدار العام المطلوب.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "إصدار الواجهة الأمامية النشط.",
    "CHAT_DELETE_WINDOW_TITLE": "نافذة حذف الدردشة",
    "CHAT_DELETE_HELPER": "تتحكم هذه القيمة في نافذة إتاحة الحذف للجميع بالثواني. يتغير حارس الخلفية فوراً بعد الحفظ. تتغير قابلية ظهور الفقاعة بعد تحديث كامل أو عند تحميل التطبيق التالي.",
    "CHAT_DELETE_HELPER_FALLBACK": "تعذر تحميل خدمة التحكم في حذف الدردشة من الخلفية، لذلك تبقى القيمة الافتراضية المرمّزة نشطة حتى يتمكن تمهيد بدء التشغيل من قراءة الخدمة المحمية مرة أخرى.",
    "CHAT_DELETE_HELPER_SAVED": "تم حفظ نافذة إتاحة الحذف للجميع في config_domain_registry. يتغير حارس الخلفية فوراً. تتغير قابلية ظهور الفقاعة بعد تحديث كامل أو عند تحميل التطبيق التالي.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "تعذرت على خدمة التحكم في حذف الدردشة من الخلفية حفظ قيمة النافذة المطلوبة.",
    "CHAT_DELETE_WINDOW_LABEL": "نافذة الحذف للجميع",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} ثانية",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "خزّن القيمة بالثواني الصحيحة. قيمة الإنتاج الحالية هي 86400 ثانية = يوم واحد.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "ثواني النافذة",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "أدخل عدداً صحيحاً أكبر من أو يساوي 0.",
    "CHAT_DELETE_SAVE_BUTTON": "حفظ نافذة الحذف",
    "GUEST_BANNER_CONTROL_TITLE": "لافتة الضيف",
    "GUEST_BANNER_CONTROL_LABEL": "دردشة الضيف عبر رمز QR",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "إظهار لافتة الضيف لجميع المستخدمين",
    "GUEST_BANNER_CONTROL_HELPER": "يتحكم في لافتة الضيف الثابتة ومدة صلاحية رمز QR المعلق.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "البديل المحلي نشط لعناصر التحكم في لافتة الضيف.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "تم حفظ عناصر التحكم في لافتة الضيف.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "تعذر حفظ عناصر التحكم في لافتة الضيف.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "تم إلغاء {count} من جلسات الضيوف.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "مدة صلاحية رمز QR المعلق (بالدقائق)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "مدة صلاحية رمز QR المعلق الحالية: {count} دقيقة.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "أدخل عددًا صحيحًا موجبًا من الدقائق.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "حفظ لافتة الضيف",
    "GUEST_QR_LOADING": "جارٍ تحضير رمز QR للضيف...",
    "GUEST_QR_READY": "امسح لفتح دردشة الضيف المؤقتة.",
    "GUEST_QR_ALT": "رمز QR لدردشة الضيف",
    "GUEST_QR_LOAD_FAILED": "تعذر تحضير رمز QR للضيف.",
    "GUEST_SESSION_ACTIVE": "الضيف متصل.",
    "GUEST_PUBLIC_TITLE": "دردشة الضيف",
    "GUEST_PUBLIC_CONNECTING": "جارٍ الاتصال...",
    "GUEST_PUBLIC_CONNECTED": "متصل",
    "GUEST_PUBLIC_UNAVAILABLE": "رابط الضيف هذا غير متاح.",
    "GUEST_PUBLIC_SEND_FAILED": "تعذر إرسال الرسالة.",
    "UI_TEXTS_RUNTIME_TITLE": "وقت تشغيل لغة واجهة المستخدم",
    "UI_TEXTS_RUNTIME_BACKEND": "يقرأ وقت تشغيل لغة واجهة المستخدم من خدمة الواجهة الخلفية المحمية. تُطبق التغييرات عند التحميل الكامل التالي للتطبيق.",
    "UI_TEXTS_RUNTIME_CACHED": "خدمة وقت تشغيل لغة واجهة المستخدم الخلفية غير متاحة حاليًا، لذا فإن الإعدادات الافتراضية المخزنة مؤقتًا أو المحلية نشطة.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "الإعدادات الافتراضية لوقت تشغيل لغة واجهة المستخدم نشطة لأنه لا يمكن تحميل أي حالة خلفية أو مخزنة مؤقتًا.",
    "UI_TEXTS_RUNTIME_SAVED": "تم حفظ التحكم في وقت تشغيل لغة واجهة المستخدم. يلزم تحديث كامل أو تحميل التطبيق التالي لكي يتلقى المستخدمون بوابة اللغة الجديدة.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "تعذر على خدمة الواجهة الخلفية المحمية حفظ التغيير المطلوب في وقت تشغيل لغة واجهة المستخدم.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "تطبيق لغة الجهاز",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "تمكين لغات واجهة المستخدم وقت التشغيل",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "يمكن للمستخدمين تلقي حمولات نصوص واجهة المستخدم للغتهم المخزنة أو لغة أجهزتهم.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "يُجبر جميع المستخدمين على استخدام نصوص واجهة المستخدم باللغة الإنجليزية، ويتم تجاهل لغة الجهاز.",
    "PROFILE_VISIBILITY_TITLE": "ظهور الملف الشخصي",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "يجب تسجيل الدخول لإدارة ظهور الحساب.",
    "PROFILE_VISIBILITY_HELPER": "يحدّث هذا المفتاح حالة ظهور حسابك فقط. تبقى قابلية الاكتشاف وسلوك قائمة البانرات دون تغيير في هذه المرحلة.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "تعذر تحميل ظهور الملف الشخصي حالياً.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "تعذر تحديث ظهور الملف الشخصي حالياً.",
    "PROFILE_VISIBILITY_SAVED": "أصبحت قابلية ظهور حسابك الآن {visibility}. تبقى مؤشرات قابلية الاكتشاف دون تغيير في هذه المرحلة.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "حساب عام",
    "PROFILE_VISIBILITY_STORED": "الظهور المخزن",
    "WF1_MODEL_CONTROL_TITLE": "التحكم في نموذج WF1",
    "WF1_ENABLE_TRANSLATION": "تفعيل الترجمة / المحور",
    "WF1_TRANSLATION_ACTIVE": "ترجمة الذكاء الاصطناعي نشطة.",
    "WF1_TRANSLATION_INACTIVE": "يستمر WF1 بالعمل، لكن يتم نسخ النص المصدر ويتم تمييز المحور كغير نشط.",
    "WF1_ACTIVE_RUNTIME_SLOT": "خانة وقت التشغيل النشطة",
    "WF1_ALLOW_SAME_LANGUAGE": "السماح بالذكاء الاصطناعي لأزواج اللغة نفسها",
    "WF1_SAME_LANGUAGE_ACTIVE": "تتبع أزواج اللغة نفسها توجيه WF1 العادي.",
    "WF1_SAME_LANGUAGE_INACTIVE": "تتجاوز أزواج اللغة نفسها الذكاء الاصطناعي وتخزن عدم وجود لغة محور نشطة.",
    "WF1_QWEN_ROUTING": "توجيه أزواج Qwen",
    "WF1_QWEN_ROUTING_HELPER": "اللغات المحددة أدناه تستخدم Qwen-Max عندما يكون الزوج إما اللغة المحددة نفسها، أو لغة محددة مع الإنجليزية، أو لغتين غير إنجليزيتين محددتين. وإلا يبقى النموذج الأساسي المحدد نشطاً.",
    "WF1_OPENROUTER_TEST_SLOT": "خانة اختبار OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "خانة اختبار OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "اختبار الجودة فقط",
    "WF1_OPENROUTER_HELPER": "هذه الخانة قابلة للتعديل فقط لاختبارات جودة OpenRouter المؤقتة. لا تغيّر مسار توجيه أزواج Qwen التشغيلي إلا إذا أصبحت هذه الخانة نفسها النموذج النشط.",
    "WF1_LABEL": "التسمية",
    "WF1_PRODUCT": "المنتج",
    "WF1_MODEL": "النموذج",
    "WF1_PROVIDER_OPENROUTER": "المزود: OpenRouter",
    "WF1_SECRET_OPENROUTER": "السر: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "خانة اختبار OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max عبر OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "سعر قائمة Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "سعر قائمة OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "سعر قائمة OpenRouter",
    "LANGUAGE_ENGLISH": "الإنجليزية",
    "LANGUAGE_CHINESE_SIMPLIFIED": "الصينية (المبسطة)",
    "LANGUAGE_CHINESE_TRADITIONAL": "الصينية (التقليدية)",
    "LANGUAGE_JAPANESE": "اليابانية",
    "LANGUAGE_KOREAN": "الكورية",
    "LANGUAGE_PERSIAN": "الفارسية",
    "LANGUAGE_TURKISH_ISTANBUL": "التركية (إسطنبول)",
    "LANGUAGE_ARABIC": "العربية",
    "LANGUAGE_FRENCH": "الفرنسية",
    "LANGUAGE_GERMAN": "الألمانية",
    "LANGUAGE_SPANISH": "الإسبانية",
    "LANGUAGE_PORTUGUESE": "البرتغالية",
    "LANGUAGE_ITALIAN": "الإيطالية",
    "LANGUAGE_RUSSIAN": "الروسية",
    "LANGUAGE_DUTCH": "الهولندية",
    "LANGUAGE_VIETNAMESE": "الفيتنامية",
    "LANGUAGE_INDONESIAN": "الإندونيسية",
    "LANGUAGE_THAI": "التايلاندية",
    "LANGUAGE_MALAY": "الملايوية",
    "WF1_PRICING_CUSTOM": "التسعير: نموذج خانة مخصص - تحقق من تسعير OpenRouter الحالي",
    "WF1_SAVE_OPENROUTER_SLOT": "حفظ خانة OpenRouter",
    "WF1_PRICING_LINE": "الإدخال {input} - الإخراج {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "السر: {secret}",
    "ZONE_VISIBILITY_TITLE": "التحكم في ظهور المنطقة",
    "ZONE_ENABLE": "تفعيل {zone}",
    "ZONE_ENABLED_NOTE": "يمكن أن تظهر {zone} للأدوار المسموح بها بعد تحميل التطبيق التالي.",
    "ZONE_DISABLED_NOTE": "تُعامل {zone} كغير موجودة للمستخدمين غير S_Admin بعد تحميل التطبيق التالي.",
    "ZONE_S_ADMIN_BYPASS": "يتجاوز S_Admin قائمة الأدوار هذه ويحتفظ دائماً بالوصول.",
    "ZONE_ROLE_LOCKED": "يتم قفل اختيارات الأدوار مؤقتاً أثناء تعطيل هذه المنطقة وستعود تماماً كما حُفظت عند تفعيل المنطقة مرة أخرى.",
    "ZONE_LCAC_CONTROL": "التحكم في LCAC",
    "ZONE_RCAC_CONTROL": "التحكم في RCAC",
    "ZONE_LCAC_DESCRIPTION": "يتحكم في وجود المنطقة المحجوزة اليسرى والأدوار التي يمكنها رؤيتها.",
    "ZONE_RCAC_DESCRIPTION": "يتحكم في وجود المنطقة المحجوزة اليمنى والأدوار التي يمكنها رؤيتها.",
    "ZONE_VISIBILITY_BACKEND": "يقرأ تمهيد ظهور المنطقة الآن من خدمة الخلفية المحمية. تُطبق التغييرات عند تحميل التطبيق التالي.",
    "ZONE_VISIBILITY_CACHED": "خدمة ظهور المنطقة في الخلفية غير متاحة حالياً، لذلك تكون القيم المخزنة مؤقتاً أو المحلية نشطة.",
    "ZONE_VISIBILITY_DEFAULTS": "إعدادات ظهور المنطقة الافتراضية نشطة لأنه تعذر تحميل أي حالة من الخلفية أو من الذاكرة المؤقتة.",
    "ZONE_VISIBILITY_SAVED": "تم حفظ تمهيد ظهور المنطقة. يلزم إعادة تحميل قسرية أو تحميل التطبيق التالي لتطبيقه في وقت التشغيل.",
    "ZONE_VISIBILITY_SAVE_FAILED": "تعذرت على خدمة الخلفية المحمية حفظ تغيير ظهور المنطقة المطلوب.",
    "ROLE_MEMBER": "عضو",
    "ROLE_STAFF": "فريق العمل",
    "ROLE_ADMIN": "مسؤول",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "فعّل الإشعارات لتلقي الرسائل الجديدة.",
    "MAIN_LOG_OUT": "تسجيل الخروج",
    "NOTIFICATION_NEW_MESSAGE": "رسالة جديدة",
    "NOTIFICATION_UNREAD_MESSAGE": "لديك رسالة غير مقروءة.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "عرض كامل",
    "MEDIA_AUDIO_ATTACHMENT": "مرفق صوتي",
    "MEDIA_FILE_FALLBACK": "ملف",
    "MEDIA_DOWNLOAD_READY": "المرفق جاهز للتنزيل",
    "MEDIA_TYPE_UNSUPPORTED": "النوع غير مدعوم للعرض الكامل",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "الصورة السابقة",
    "MEDIA_NEXT_IMAGE_ARIA": "الصورة التالية",
    "MEDIA_OPEN_ORIGINAL": "فتح الأصل",
    "MEDIA_DOWNLOAD": "تنزيل",
    "MEDIA_CLOSE_ARIA": "إغلاق",
    "MEDIA_PROFILE_PICTURE_ARIA": "صورة ملف {name} الشخصي",
    "MEDIA_PROFILE_ALT": "ملف {name} الشخصي",
    "MEDIA_UPLOAD_FAILED": "فشل الرفع",
    "MEDIA_BACKEND_TOKEN_ERROR": "خطأ في رمز الخلفية",
    "MEDIA_UPLOAD_URL_MISSING": "حرج: رابط الرفع مفقود في استجابة الخلفية.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "رمز المصادقة مفقود لرفع الدردشة",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "فشل طلب رمز رفع الدردشة",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "استجابة رفع الدردشة غير صالحة",
    "MEDIA_GCS_UPLOAD_FAILED": "فشل رفع GCS",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "اسم الملف أو contentType مفقود",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path مفقود",
    "BLOCK_NOTICE_TITLE": "إشعار حظر دائم",
    "BLOCK_NOTICE_MESSAGE": "تم تعليق حسابك مؤقتاً بسبب انتهاك السياسة.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "إذا كنت تعتقد أن هذا يتطلب متابعة، يرجى التواصل مع",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "عبر البريد الإلكتروني.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "مستخدم غير معروف",
    "GENERAL_GUEST": "ضيف",
    "ADVISOR_FOR_CLIENT": "مستشار لـ {client_display_name}",
    "GUEST_FOR_CLIENT": "ضيف لـ {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "الرمز وكلمة المرور مطلوبان",
    "AUTH_ERROR_REQUEST_BODY_JSON": "يجب أن يكون جسم الطلب بصيغة JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "رمز الدعوة غير صالح أو منتهي الصلاحية",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "فشل تعيين كلمة المرور: الجلسة أو المستخدم مفقود",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "فشل تعيين كلمة المرور أثناء تسجيل الدخول",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "فشل إنشاء رمز المسؤول",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "فشل تسجيل الدخول: الجلسة أو المستخدم مفقود",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "تم التسجيل بنجاح. يرجى التحقق من بريدك الإلكتروني للتأكيد.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "فشل التسجيل لسبب غير معروف",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "معالجة الرمز غير صالحة",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "رمز الوصول مطلوب",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "تتطلب معاينة تجزئة الرمز تلميح البريد الإلكتروني من رابط إعادة التوجيه",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "تعذر حل الهوية لهذا الرمز",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "يمكن لـ User Zero فقط الوصول إلى خدمة محدد LLM الخاصة بـ WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "يمكن لـ User Zero فقط الوصول إلى خدمة التحكم في ظهور المناطق.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "يمكن لـ User Zero فقط الوصول إلى خدمة التحكم في إصدار الواجهة الأمامية.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "يمكن لـ User Zero فقط فحص إصدار الواجهة الأمامية لمستخدم آخر.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "يمكن لـ User Zero فقط الوصول إلى خدمة التحكم في حذف الدردشة.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "يمكن للمستخدم صفر فقط الوصول إلى خدمة التحكم في وقت تشغيل لغة واجهة المستخدم.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "يمكن لـ User Zero فقط حذف حساب مستخدم نهائياً.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "حمولة الطلب غير صالحة.",
    "API_ERROR_INTERNAL_SERVER": "خطأ داخلي في الخادم",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "الدالة مفقودة في الخلفية (إعادة التحميل مطلوبة)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "يُسمح فقط بـ DB RPC لانتقالات delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "يرجى الانتظار قبل إرسال رسالة أخرى.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "تم إرسال الرسالة بنجاح.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "خدمة الاتصال غير متاحة.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "فشل إرسال الرسالة.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "الاسم مطلوب.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "البريد الإلكتروني غير صالح.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "الرسالة مطلوبة.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "حمولة المحدد مطلوبة.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "حمولة ظهور المنطقة مطلوبة.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "حمولة إصدار الواجهة الأمامية مطلوبة.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "حمولة التحكم في حذف الدردشة مطلوبة.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "حمولة التحكم في وقت تشغيل لغة واجهة المستخدم مطلوبة.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "معرّف المستخدم المصادق عليه مطلوب.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "معرّف المستخدم المشاهد المصادق عليه مطلوب.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "معرّف المستخدم الفاعل المصادق عليه مطلوب.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id مطلوب.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id مطلوب.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "قائمة owner_user_ids مطلوبة.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email مطلوب.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by مطلوب.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "وقت تشغيل البحث معطل بواسطة إصدار الواجهة الأمامية العام.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "غير مسموح لك بإلغاء هذه الدعوة المعلقة.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "لم يعد بالإمكان إلغاء هذه الدعوة لأن المستخدم مسجل بالفعل.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "لم يتم العثور على الدعوة المعلقة.",
    "INVITE_REPLY_ALREADY_MEMBER": "تهانينا، صديقك ({invitee_email}) مسجل بالفعل في هذا التطبيق وعضو في مساحة العمل هذه.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "توجد دعوة معلقة لـ {invitee_email}، لكن تعذر تشغيل بريد إعادة المحاولة. يرجى التحقق من سجلات البريد.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "تم إنشاء سجل دعوة لـ {invitee_email}، لكن تعذر تأكيد تسليم البريد الإلكتروني. يرجى المحاولة لاحقاً أو التحقق من سجلات البريد.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "فشل إنشاء سجل الدعوة. يرجى المحاولة لاحقاً.",
    "INVITE_REPLY_SYSTEM_ERROR": "خطأ في النظام أثناء عملية الدعوة: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "خطأ في إعداد الخلفية: بيانات اعتماد Supabase مفقودة",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "خطأ في إعداد الخلفية: رابط Supabase غير صالح",
    "CHAT_ERROR_ACCESS_DENIED": "تم رفض الوصول",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "لا يمكن أن يكون المحتوى فارغاً للرسائل النصية",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "تعذر تحديد معرّف المحادثة",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "سياق مصادقة RPC مفقود",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "أرجع RPC حمولة رسالة غير صالحة",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "فشلت عملية الإدراج، لم يتم إرجاع أي بيانات",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "يجب أن يكون operations قائمة",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "حمولة العملية غير صالحة",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type غير مدعوم",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id مطلوب",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "لم يتم العثور على الرسالة",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "يُسمح بالحذف فقط على رسالتك الخاصة",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "لم يعد الحذف للجميع متاحاً لهذه الرسالة",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "فشل الحذف للجميع",
    "API_ERROR_SERVER_CONFIGURATION": "خطأ في إعداد الخادم",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "ترويسة سر webhook مفقودة",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "مصدر webhook غير مصرح به",
    "API_ERROR_BACKEND_CONFIGURATION": "خطأ في إعداد الخلفية",
    "API_ERROR_MODULE_ATTRIBUTE": "خطأ في خاصية الوحدة: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "فشل قبل حذف الدعوة أثناء إزالة مستخدم المصادقة المنتظر.",
    "CHAT_ERROR_DB": "خطأ DB: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "PERMISSION_MIC_PERMISSION": "",
    "PERMISSION_MIC_ACCESS": "",
    "PERMISSION_TOGGLE_MIC_ARIA": "",
    "PERMISSION_MIC_ON_TOOLTIP": "",
    "PERMISSION_MIC_ENABLE_TOOLTIP": "",
    "PERMISSION_MIC_BLOCKED_TOOLTIP": "",
    "PERMISSION_MIC_DISABLE_HELP": "",
    "PERMISSION_MIC_BLOCKED_HELP": "",
    "LIVE_CONV_MIC_PROMPT_TITLE": "",
    "LIVE_CONV_MIC_PROMPT_BODY": "",
    "LIVE_CONV_MIC_PROMPT_ALLOW": "",
    "LIVE_CONV_MIC_PROMPT_CANCEL": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
