# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/en.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "প্রধান",
    "APP_TITLE": "OTMEGA AI প্ল্যাটফর্ম",
    "APP_SUBTITLE": "AI উপদেষ্টা",
    "CHAT_PLACEHOLDER": "আপনার বার্তা লিখুন...",
    "CHAT_SEND_BUTTON": "পাঠান",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 উপদেষ্টা ভুল করতে পারে, তাই তথ্য যাচাই করুন।",
    "STATUS_ONLINE": "অনলাইন",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "মেনু",
    "ICON_NEW_CHAT": "নতুন চ্যাট",
    "ICON_HISTORY": "ইতিহাস",
    "ICON_TEMPLATES": "টেমপ্লেট",
    "ICON_SETTINGS": "সেটিংস",
    "ICON_USER_PROFILE": "ব্যবহারকারী প্রোফাইল",
    "ICON_QUICK_ACTIONS": "দ্রুত কার্যক্রম",
    "ICON_PINNED": "পিন করা",
    "ICON_GALLERY": "গ্যালারি",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "অ্যাপ ইনস্টল করুন",
    "PWA_ANDROID_MSG": "ভালো অভিজ্ঞতা ও অফলাইন অ্যাক্সেসের জন্য আপনার ডিভাইসে এই অ্যাপটি ইনস্টল করুন।",
    "PWA_IOS_MSG": "আপনার iPhone/iPad-এ এই অ্যাপটি ইনস্টল করতে:\n1. নিচের Share বোতামে ট্যাপ করুন\n2. 'Add to Home Screen' নির্বাচন করুন",
    "PWA_BTN_INSTALL": "ইনস্টল",
    "PWA_BTN_LATER": "পরে হয়তো",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "উপদেষ্টা নেটওয়ার্কে লগ ইন করুন",
    "AUTH_HEADER_SIGNUP": "আপনার একীভূত অ্যাকাউন্ট তৈরি করুন",
    "AUTH_HEADER_LOGIN_NETWORK": "উপদেষ্টা নেটওয়ার্কে লগ ইন করুন",
    "AUTH_HEADER_SIGNUP_UNIFIED": "আপনার একীভূত অ্যাকাউন্ট তৈরি করুন",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "লগইন",
    "AUTH_BUTTON_SIGNUP": "অ্যাকাউন্ট তৈরি করুন",
    "AUTH_BUTTON_GOOGLE": "Google দিয়ে চালিয়ে যান",
    "AUTH_BUTTON_FORGOT_PASSWORD": "পাসওয়ার্ড ভুলে গেছেন",
    "AUTH_BUTTON_SEND_RESET_LINK": "রিসেট লিংক পাঠান",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "অ্যাকাউন্ট নেই? সাইন আপ করুন",
    "AUTH_PROMPT_LOGIN": "ইতিমধ্যে অ্যাকাউন্ট আছে? লগ ইন করুন",
    "AUTH_HELPER_TEXT_SIGNUP": "আপনি একটি একীভূত অ্যাকাউন্ট তৈরি করছেন, যা দিয়ে এই প্ল্যাটফর্মের সব উপদেষ্টায় অ্যাক্সেস করতে পারবেন।",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "আপনি একটি একীভূত অ্যাকাউন্ট তৈরি করছেন, যা দিয়ে এই প্ল্যাটফর্মের সব উপদেষ্টায় অ্যাক্সেস করতে পারবেন।",
    "AUTH_HELPER_TEXT_LOGIN": "এই নেটওয়ার্কের অন্য উপদেষ্টাদের জন্য যে একই অ্যাকাউন্ট (ইমেল/পাসওয়ার্ড বা Google) ব্যবহার করেছিলেন, সেটি ব্যবহার করুন।",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "এই নেটওয়ার্কের অন্য উপদেষ্টাদের জন্য যে একই অ্যাকাউন্ট (ইমেল/পাসওয়ার্ড বা Google) ব্যবহার করেছিলেন, সেটি ব্যবহার করুন।",
    "AUTH_FORGOT_PASSWORD_LINK": "আপনার পাসওয়ার্ড ভুলে গেছেন?",
    "AUTH_FORGOT_PASSWORD_TITLE": "আপনার পাসওয়ার্ড রিসেট করুন",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "আপনার ইমেল ঠিকানা লিখুন; আমরা পাসওয়ার্ড রিসেট করার একটি লিংক পাঠাব।",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "ইমেল",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "আপনাকে লগ ইন করা হচ্ছে...",
    "AUTH_STATUS_LOADING_SIGNUP": "আপনার অ্যাকাউন্ট তৈরি হচ্ছে...",
    "AUTH_STATUS_LOADING_RESET": "রিসেট লিংক পাঠানো হচ্ছে...",
    "AUTH_STATUS_SUCCESS_LOGIN": "লগইন সফল! পুনরায় লোড হচ্ছে...",
    "AUTH_STATUS_SUCCESS_RESET": "রিসেট লিংক সফলভাবে পাঠানো হয়েছে। অনুগ্রহ করে আপনার ইমেল দেখুন।",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "পাসওয়ার্ড রিসেট লিংক সফলভাবে পাঠানো হয়েছে। অনুগ্রহ করে আপনার ইমেল দেখুন।",

    "AUTH_ERROR_INVALID_CREDENTIALS": "ইমেল বা পাসওয়ার্ড সঠিক নয়।",
    "AUTH_ERROR_EMAIL_EXISTS": "এই ইমেল দিয়ে উপদেষ্টা নেটওয়ার্কে ইতিমধ্যে একটি অ্যাকাউন্ট আছে।",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "এই ইমেল দিয়ে ইতিমধ্যে একটি অ্যাকাউন্ট আছে। অনুগ্রহ করে লগ ইন করুন। আপনি বর্তমানে সদস্য:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "এই ইমেল দিয়ে উপদেষ্টা নেটওয়ার্কে ইতিমধ্যে একটি অ্যাকাউন্ট আছে। অনুগ্রহ করে এই উইন্ডোটি বন্ধ করে একই ইমেল এবং আপনার আগের পাসওয়ার্ড দিয়ে 'Login' অংশ ব্যবহার করুন।",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "আপনি বর্তমানে সদস্য:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "ইমেল এবং পাসওয়ার্ড প্রয়োজন।",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "অ্যাকাউন্ট তৈরি হয়েছে, কিন্তু সদস্যপদ সেটআপ ব্যর্থ হয়েছে। অনুগ্রহ করে সাপোর্টের সাথে যোগাযোগ করুন।",
    "AUTH_ERROR_DEFAULT": "একটি ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    "AUTH_FORGOT_PASSWORD_ERROR": "রিসেট লিংক পাঠানো যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।",
    "INVITE_REPLY_EMAIL_SENT": "Collabra আমন্ত্রণ ইমেল আপনার বন্ধুকে {invitee_email} ঠিকানায় পাঠানো হয়েছে।",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra আমন্ত্রণ ইমেল আপনার বন্ধুকে {invitee_email} ঠিকানায় পুনরায় পাঠানো হয়েছে।",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "পাসওয়ার্ড দেখান",
    "AUTH_PASSWORD_TOGGLE_HIDE": "পাসওয়ার্ড লুকান",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "ঠিক আছে",
    "GENERAL_CANCEL": "বাতিল",
    "GENERAL_CLOSE": "বন্ধ",
    "GENERAL_SEND": "পাঠান",
    "GENERAL_SEARCH": "অনুসন্ধান",
    "GENERAL_RESET": "রিসেট",
    "GENERAL_ENABLE": "সক্রিয় করুন",
    "GENERAL_LOADING": "লোড হচ্ছে...",
    "GENERAL_DELETE": "মুছুন",
    "GENERAL_DELETING": "মুছে ফেলা হচ্ছে...",
    "GENERAL_SAVE_PASSWORD": "পাসওয়ার্ড সংরক্ষণ করুন",
    "AUTH_REMEMBER_EMAIL_LABEL": "ইমেল মনে রাখুন",
    "GENERAL_SAVING": "সংরক্ষণ হচ্ছে...",
    "GENERAL_SENDING": "পাঠানো হচ্ছে...",
    "GENERAL_REMOVING": "সরানো হচ্ছে...",
    "GENERAL_CONFIRM_REMOVAL": "সরানো নিশ্চিত করুন",
    "GENERAL_EMPTY": "খালি",
    "GENERAL_UNAVAILABLE": "উপলব্ধ নয়",
    "GENERAL_ENABLED": "সক্রিয়",
    "GENERAL_DISABLED": "নিষ্ক্রিয়",
    "GENERAL_GRANTED": "অনুমোদিত",
    "GENERAL_DENIED": "প্রত্যাখ্যাত",
    "GENERAL_DEFAULT": "ডিফল্ট",
    "GENERAL_UNSUPPORTED": "সমর্থিত নয়",
    "GENERAL_PUBLIC": "সর্বজনীন",
    "GENERAL_PRIVATE": "ব্যক্তিগত",
    "GENERAL_USERNAME": "ব্যবহারকারীর নাম",
    "GENERAL_EMAIL": "ইমেল",
    "GENERAL_YOU": "আপনি",
    "GENERAL_USER": "ব্যবহারকারী",
    "GENERAL_UNKNOWN": "অজানা",
    "GENERAL_VISITOR": "ভিজিটর",
    "GENERAL_PROFILE": "প্রোফাইল",
    "GENERAL_BANNER": "ব্যানার",
    "GENERAL_UNKNOWN_BANNER": "অজানা ব্যানার",
    "GENERAL_ADVISOR_BANNER": "উপদেষ্টা ব্যানার",
    "GENERAL_NOT_AVAILABLE": "প্রযোজ্য নয়",
    "GENERAL_NOT_SELECTED": "নির্বাচিত নয়",
    "GENERAL_NO_EMAIL_FOUND": "কোনো ইমেল পাওয়া যায়নি",
    "GENERAL_USER_ZERO_ONLY": "শুধুমাত্র User Zero",
    "GENERAL_CONNECTION_STATE": "সংযোগের অবস্থা",
    "GENERAL_DISPLAY_ONLY": "শুধু প্রদর্শন",
    "GENERAL_TEXTAREA": "টেক্সটএরিয়া",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "মেনু (LCAC)",
    "HEADER_CHAT_CCAC": "চ্যাট (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "দ্রুত কার্যক্রম (RCAC)",
    "HEADER_CHANGE_STATUS": "স্ট্যাটাস পরিবর্তন করুন",
    "HEADER_OT_COIN_BALANCE": "OT Coin ব্যালেন্স",
    "HEADER_ALT_USER": "ব্যবহারকারী",
    "STATUS_BUSY": "ব্যস্ত",
    "STATUS_AWAY": "দূরে",
    "STATUS_OFFLINE": "অফলাইন",
    "STATUS_INVISIBLE": "অদৃশ্য",
    "NETWORK_CHECKING_CONNECTION": "সংযোগ পরীক্ষা করা হচ্ছে...",
    "NETWORK_ONLINE_LATENCY": "অনলাইন (ল্যাটেন্সি: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "নেটওয়ার্ক: ভালো (ping করতে ট্যাপ করুন)",
    "CHAT_TARGET_ALT": "চ্যাট লক্ষ্য",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "অনুসন্ধান...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "{name}-এর প্রোফাইল ছবি খুলুন",
    "CHAT_MESSAGE_INPUT_ARIA": "বার্তা ইনপুট",
    "CHAT_TOGGLE_VIEW_ARIA": "ভিউ টগল করুন",
    "CHAT_ADD_USER_ARIA": "ব্যবহারকারী যোগ করুন",
    "CHAT_ATTACH_ARIA": "সংযুক্ত করুন",
    "CHAT_MIC_ARIA": "মাইক্রোফোন",
    "CHAT_SEND_ARIA": "পাঠান",
    "CHAT_SEARCH_ARIA": "অনুসন্ধান",
    "CHAT_OPEN_SEARCH_ARIA": "অনুসন্ধান খুলুন",
    "CHAT_CLOSE_SEARCH_ARIA": "অনুসন্ধান বন্ধ করুন",
    "CHAT_ATTACHMENT_ALT": "সংযুক্তি",
    "CHAT_PREVIEW_ALT": "প্রিভিউ",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "সংযুক্তি সরান",
    "CHAT_REPLYING_TO": "উত্তর দেওয়া হচ্ছে",
    "CHAT_CANCEL_REPLY_ARIA": "উত্তর বাতিল করুন",
    "CHAT_UPLOADING": "আপলোড হচ্ছে...",
    "CHAT_LOADING_CHATS": "চ্যাট লোড হচ্ছে...",
    "CHAT_SEND_FAILED": "পাঠানো ব্যর্থ",
    "CHAT_SEND_FAILED_RETRY": "পাঠানো ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    "CHAT_RETRY": "পুনরায় চেষ্টা",
    "CHAT_EDITED": "সম্পাদিত",
    "CHAT_TYPING": "টাইপ করছে",
    "CHAT_LOADING": "লোড হচ্ছে",
    "CHAT_PENDING_INVITATION": "অপেক্ষমাণ আমন্ত্রণ",
    "CHAT_PENDING_INVITATION_MIN": "{count} মিনিট অপেক্ষমাণ আমন্ত্রণ",
    "CHAT_PENDING_INVITATION_HR": "{count} ঘণ্টা অপেক্ষমাণ আমন্ত্রণ",
    "CHAT_PENDING_INVITATION_DAY": "{count} দিন অপেক্ষমাণ আমন্ত্রণ",
    "CHAT_WAITING_FOR_YOU": "{label} - আপনার জন্য অপেক্ষা করছে",
    "CHAT_PENDING_ACCEPTANCE": "{label} - গ্রহণের অপেক্ষায়",
    "CHAT_MICROPHONE_ACCESS_DENIED": "মাইক্রোফোন অ্যাক্সেস অস্বীকার করা হয়েছে।",
    "CHAT_UPLOAD_FAILED": "আপলোড ব্যর্থ: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "আপলোডের জন্য ইন্টারনেট সংযোগ প্রয়োজন। অনলাইনে থাকলে আবার চেষ্টা করুন।",
    "CHAT_ERROR_AUTH": "প্রমাণীকরণ ত্রুটি",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "ফাইলের নাম বা content_type অনুপস্থিত",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id বা target_id অনুপস্থিত",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "নন-অ্যাভাটার আপলোডের জন্য conversation_id অনুপস্থিত",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "অবৈধ avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase সার্ভিস ক্লায়েন্ট উপলব্ধ নয়",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Avatar read ack শুধুমাত্র উপদেষ্টা চ্যাট প্রসঙ্গে বৈধ",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatar flow বার্তা পাওয়া যায়নি বা read ack-এর জন্য যোগ্য নয়",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "অ্যাভাটার বার্তাকে পড়া হিসেবে চূড়ান্ত করতে ব্যর্থ",
    "CHAT_ATTACHMENT_COUNT_ONE": "১টি সংযুক্তি",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count}টি সংযুক্তি",
    "CHAT_VOICE_NOTE": "ভয়েস নোট",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "চ্যাট উপলব্ধ নয়। এই ব্যবহারকারী আপনাকে ব্লক করেছে।",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "চ্যাট উপলব্ধ নয়। আপনি এই ব্যবহারকারীকে ব্লক করেছেন।",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "নীতির কারণে অ্যাকাউন্ট অ্যাক্সেস ব্লক করা হয়েছে।",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "চ্যাট উপলব্ধ নয়। এই অ্যাকাউন্টটি User Zero দ্বারা চূড়ান্তভাবে ব্লক করা হয়েছে।",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "চ্যাট উপলব্ধ নয়। পারস্পরিক ব্লক সক্রিয়।",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "ব্লক নীতির কারণে চ্যাট উপলব্ধ নয়।",
    "MESSAGE_PREVIEW_PHOTO": "ছবি",
    "MESSAGE_PREVIEW_VOICE": "ভয়েস বার্তা",
    "MESSAGE_PREVIEW_VIDEO": "ভিডিও",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "ফাইল",
    "MESSAGE_PREVIEW_MESSAGE": "বার্তা",
    "MESSAGE_PREVIEW_SYSTEM": "সিস্টেম বার্তা",
    "MESSAGE_PREVIEW_NEW": "নতুন বার্তা",
    "MESSAGE_UNKNOWN_FILE": "অজানা ফাইল",
    "MESSAGE_AUDIO_ATTACHMENT": "অডিও সংযুক্তি",
    "MESSAGE_FILE_ATTACHMENT": "সংযুক্তি",
    "BANNER_INVITED_BY": "{label} দ্বারা আমন্ত্রিত",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "অনুসন্ধান ফলাফল",
    "SEARCH_QUERY_LABEL": "কোয়েরি:",
    "SEARCH_LOADING_VISIBILITY": "অনুসন্ধান দৃশ্যমানতা লোড হচ্ছে...",
    "SEARCH_NO_RESULTS": "বর্তমান অনুসন্ধান পরিসরে কোনো ফলাফল পাওয়া যায়নি।",
    "SHARE_WITH_COLLABRA": "Collabra-এর সাথে শেয়ার করুন",
    "SHARE_SEND_TO": "পাঠান",
    "SHARE_SELECT_ONE_BANNER": "একটি ব্যানার নির্বাচন করুন",
    "SHARE_BANNER_LIST_ARIA": "ব্যানার তালিকা",
    "SHARE_NO_MATCHING_BANNER": "মিল থাকা কোনো ব্যানার নেই",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "একটি মন্তব্য যোগ করুন...",
    "SHARE_RECENT_CHATS": "সাম্প্রতিক চ্যাট",
    "SHARE_LEFT_LIST": "বাম তালিকা",
    "SHARE_RIGHT_LIST": "ডান তালিকা",
    "SHARE_UNTITLED_BANNER": "শিরোনামহীন ব্যানার",
    "SHARE_SHARED_CONTENT": "শেয়ার করা কনটেন্ট",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "শেয়ার করা কনটেন্ট খোলা যায়নি।",
    "SHARE_OPEN_BANNER_FAILED": "নির্বাচিত ব্যানার খোলা যায়নি।",
    "SHARE_ONE_PHOTO_SELECTED": "১টি ছবি নির্বাচিত",
    "SHARE_MANY_PHOTOS_SELECTED": "{count}টি ছবি নির্বাচিত",
    "SHARE_ONE_FILE_SELECTED": "১টি ফাইল নির্বাচিত",
    "SHARE_MANY_FILES_SELECTED": "{count}টি ফাইল নির্বাচিত",
    "FORWARD_MESSAGE_TITLE": "বার্তা ফরওয়ার্ড করুন",
    "FORWARD_SELECT_RECIPIENTS": "প্রাপকদের নির্বাচন করুন",
    "FORWARD_NO_OTHER_BANNER": "অন্য কোনো ব্যানার উপলব্ধ নেই।",
    "FORWARD_SEND_TO_COUNT": "{count}-এ পাঠান",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "অন্তত একটি ব্যানার নির্বাচন করুন।",
    "FORWARD_FAILED_DEFAULT": "ফরওয়ার্ড ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    "FORWARD_PARTIAL_SENT": "{count}টি পাঠানো হয়েছে। {error}",
    "FORWARD_SOURCE_NOT_FOUND": "ফরওয়ার্ডের জন্য উৎস বার্তা পাওয়া যায়নি",
    "FORWARD_NO_FORWARDABLE_CONTENT": "এই বার্তায় এখনও ফরওয়ার্ডযোগ্য কনটেন্ট নেই",
    "FORWARD_DESTINATION_MISSING": "ফরওয়ার্ড গন্তব্য অনুপস্থিত",
    "FORWARD_MESSAGE_PREVIEW": "ফরওয়ার্ড করা বার্তা",
    "MENU_PASTE": "পেস্ট",
    "MENU_COPY": "কপি",
    "MENU_REPLY": "উত্তর",
    "MENU_FORWARD": "ফরওয়ার্ড",
    "MENU_REMOVE_INVITATION": "আমন্ত্রণ সরান",
    "MENU_REMOVE_FROM_LIST": "তালিকা থেকে সরান",
    "MENU_ADD_TO_LIST": "তালিকায় যোগ করুন",
    "MENU_REJECT_INVITATION": "আমন্ত্রণ প্রত্যাখ্যান করুন",
    "MENU_FRONTEND_VERSION": "ফ্রন্টএন্ড সংস্করণ",
    "MENU_BANNER_HEADER": "ব্যানার - {zone}",
    "MENU_BANNER_INFO": "ব্যানার তথ্য: {title}",
    "MENU_MESSAGE_BUBBLE": "বার্তা বাবল",
    "MENU_CHAT_CANVAS_HEADER": "চ্যাট ক্যানভাস - {zone}",
    "MENU_CANVAS_INFO": "ক্যানভাস তথ্য",
    "MENU_CHAT_CANVAS_SUBLABEL": "কথোপকথন এলাকা / বর্তমান চ্যাট পৃষ্ঠ",
    "MENU_INPUT_AREA_HEADER": "ইনপুট এলাকা - {zone}",
    "MENU_INPUT_AREA_INFO": "ইনপুট এলাকা তথ্য: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "নিচের টাইপিং ও অ্যাকশন টুলস পৃষ্ঠ",
    "MENU_HEADER": "হেডার - {zone}",
    "MENU_HEADER_INFO": "হেডার তথ্য: {title}",
    "MENU_HEADER_DESCRIPTION": "উপরের নেভিগেশন ও পেজ নিয়ন্ত্রণ",
    "MENU_ZONE_HEADER": "জোন - {zone}",
    "MENU_ZONE_SPACE_INFO": "জোন স্পেস তথ্য",
    "MENU_EMPTY_LIST_SURFACE": "খালি/তালিকা পৃষ্ঠ",
    "MENU_BLOCK": "ব্লক",
    "MENU_UNBLOCK": "আনব্লক",
    "MENU_HIDE_IN_SEARCH": "অনুসন্ধানে লুকান",
    "MENU_UNHIDE_IN_SEARCH": "অনুসন্ধানে দেখান",
    "MENU_VISIBLE_IN_SEARCH": "অনুসন্ধানে দৃশ্যমান",
    "MENU_HIDDEN_IN_SEARCH": "অনুসন্ধানে লুকানো",
    "MENU_VISIBLE_IN_USER_LIST": "ব্যবহারকারী তালিকায় দৃশ্যমান",
    "MENU_HIDDEN_IN_USER_LIST": "ব্যবহারকারী তালিকায় লুকানো",
    "MENU_NOT_BLOCKED": "ব্লক করা নয়",
    "MENU_BLOCKED": "ব্লক করা",
    "MENU_FRONTEND_VERSION_LOADING": "লোড হচ্ছে...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "ব্যাকএন্ড থেকে প্রতি-ব্যানার মান লোড হচ্ছে। ডাটাবেস প্রতিক্রিয়া না আসা পর্যন্ত কোনো অপশন সক্রিয় হিসেবে চিহ্নিত নয়।",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "ব্যাকএন্ড মান লোড করা যায়নি। কোনো বিশ্বস্ত সক্রিয় অপশন দেখানো হচ্ছে না।",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "স্পষ্ট প্রতি-ব্যানার ডাটাবেস মান হলো {overrideVersion}। গ্লোবাল ডিফল্ট হলো {globalDefaultVersion}। স্টার্টআপ bootstrap এটি প্রয়োগ করতে লক্ষ্য ব্যবহারকারীকে অ্যাপটি সম্পূর্ণ রিফ্রেশ বা পুনরায় খুলতে হবে।",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "কোনো স্পষ্ট প্রতি-ব্যানার ডাটাবেস মান সংরক্ষিত নেই। FeV2.0.0 ডিফল্টভাবে সক্রিয়। গ্লোবাল ডিফল্ট হলো {globalDefaultVersion}।",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "লক্ষ্য অ্যাপ সম্পূর্ণ রিলোড হওয়ার পরে স্পষ্ট প্রতি-ব্যানার ডাটাবেস মান সক্রিয় হয়",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "কোনো স্পষ্ট প্রতি-ব্যানার মান সংরক্ষিত নেই; এটি ডিফল্ট ব্যক্তিগত FeV2.0.0 অবস্থা",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "এই অপশনটি বর্তমান গ্লোবাল ডিফল্টের সাথেও সমান",
    "MENU_DELETE_PERMANENT_CONFIRM": "ডাটাবেস থেকে {target} স্থায়ীভাবে মুছে ফেলবেন? এতে অ্যাকাউন্ট, চ্যাট ইতিহাস, নির্ভরতা মুছে যাবে এবং ভবিষ্যৎ পুনঃপ্রবেশের জন্য সম্পূর্ণ নতুন আমন্ত্রণ পথ বাধ্যতামূলক হবে।",
    "MENU_DELETE_PERMANENTLY": "স্থায়ীভাবে মুছুন",
    "MENU_REFRESH_PAGE": "পেজ রিফ্রেশ করুন",
    "MENU_LOG_OFF": "লগ অফ",
    "MENU_HARD_RELOAD": "সর্বশেষ সংস্করণ পান",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "ইমেল (অ্যাডমিন ব্যবহারকারী)",
    "AUTH_PASSWORD_PLACEHOLDER": "পাসওয়ার্ড",
    "AUTH_CONNECTING": "সংযোগ হচ্ছে...",
    "AUTH_SIGNING_OUT": "সাইন আউট হচ্ছে...",
    "AUTH_BACK_TO_LOGIN": "লগইনে ফিরে যান",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "অবৈধ সার্ভার প্রতিক্রিয়া: কোনো টোকেন পাওয়া যায়নি।",
    "AUTH_LOGIN_FAILED": "লগইন ব্যর্থ",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "পাসওয়ার্ড মিলছে না।",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "পাসওয়ার্ড মিলছে না!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "পাসওয়ার্ড অবশ্যই হুবহু মিলতে হবে।",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "নতুন পাসওয়ার্ড",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "পাসওয়ার্ড নিশ্চিত করুন",
    "AUTH_CHANGE_PASSWORD": "পাসওয়ার্ড পরিবর্তন করুন",
    "AUTH_SAVING_PASSWORD": "সংরক্ষণ হচ্ছে...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "পাসওয়ার্ড সফলভাবে আপডেট হয়েছে।",
    "AUTH_CHANGE_PASSWORD_UNABLE": "এই মুহূর্তে পাসওয়ার্ড পরিবর্তন করা যাচ্ছে না।",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "পাসওয়ার্ড পরিবর্তন করতে আপনাকে লগ ইন থাকতে হবে।",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "নতুন পাসওয়ার্ড দৃশ্যমানতা টগল করুন",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "নিশ্চিত পাসওয়ার্ড দৃশ্যমানতা টগল করুন",
    "REGISTER_TITLE": "নিবন্ধন সম্পূর্ণ করুন",
    "REGISTER_SUBTITLE": "অনুগ্রহ করে আপনার পাসওয়ার্ড ম্যানুয়ালি সেট করুন।",
    "REGISTER_CREATING_ACCOUNT": "অ্যাকাউন্ট তৈরি হচ্ছে...",
    "REGISTER_FINISH_SETUP": "সেটআপ শেষ করুন",
    "REGISTER_FAILED_SET_PASSWORD": "পাসওয়ার্ড সেট করতে ব্যর্থ",
    "INVITE_EMAIL_INSTRUCTION": "অনুগ্রহ করে আমন্ত্রিত ব্যক্তির ইমেল লিখুন (ফরম্যাট: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "আমন্ত্রণ",
    "INVITE_EMAIL_REQUIRED": "অনুগ্রহ করে আমন্ত্রিত ব্যক্তির ইমেল লিখুন।",
    "INVITE_EMAIL_INVALID": "ইমেল ফরম্যাট অবৈধ। অনুগ্রহ করে ব্যবহার করুন: user@example.com",
    "PENDING_INVITATION_TITLE": "অপেক্ষমাণ আমন্ত্রণ",
    "PENDING_INVITATION_REMOVE_QUESTION": "ডাটাবেস থেকে এই অপেক্ষমাণ আমন্ত্রণটি সরাবেন?",
    "PENDING_INVITATION_KEEP": "আমন্ত্রণ রাখুন",
    "PENDING_INVITATION_REMOVAL_FAILED": "সরানো ব্যর্থ হয়েছে।",
    "REMOVE_FROM_LIST_TITLE": "তালিকা থেকে সরান",
    "REMOVE_FROM_LIST_WARNING": "এখনই এই ব্যবহারকারীকে দুই তালিকা থেকেই সরাবেন? চ্যাট অ্যাক্সেস সঙ্গে সঙ্গে কেটে যাবে। ফিরে আসার একমাত্র পথ হলো নতুন আমন্ত্রণ।",
    "REMOVE_FROM_LIST_KEEP": "ব্যবহারকারীকে তালিকায় রাখুন",
    "REMOVE_FROM_LIST_FAILED": "তালিকা থেকে সরানো ব্যর্থ হয়েছে।",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "সেটিং ও লাইভ স্ট্যাটাস",
    "PERMISSION_DIALOG_ARIA": "সেটিং এবং লাইভ স্ট্যাটাস",
    "PERMISSION_TRIGGER_ARIA": "সেটিংস পপআপ ট্রিগার",
    "PERMISSION_CLOSE_ARIA": "অনুমতি পপআপ বন্ধ করুন",
    "PERMISSION_LIVE_STATUS": "লাইভ স্ট্যাটাস",
    "PERMISSION_SYSTEM_PERMISSION": "সিস্টেম অনুমতি",
    "PERMISSION_APP_PUSH": "অ্যাপ পুশ",
    "PERMISSION_LOCATION_PERMISSION": "লোকেশন অনুমতি",
    "PERMISSION_APP_LOCATION": "অ্যাপ লোকেশন",
    "PERMISSION_CONTROLS": "অনুমতি নিয়ন্ত্রণ",
    "PERMISSION_PUSH_NOTIFICATIONS": "পুশ নোটিফিকেশন",
    "PERMISSION_LOCATION_ACCESS": "লোকেশন অ্যাক্সেস",
    "PERMISSION_IN_APP_SETTINGS": "ইন-অ্যাপ সেটিংস",
    "PERMISSION_ALERT_SOUND": "সতর্কতা শব্দ",
    "PERMISSION_APP_BADGE": "অ্যাপ ব্যাজ",
    "PERMISSION_PASSWORD_SETTINGS": "পাসওয়ার্ড সেটিংস",
    "PERMISSION_NAVIGATION_STATUS": "নেভিগেশন স্ট্যাটাস",
    "PERMISSION_SELECTED_ZONE": "নির্বাচিত জোন",
    "PERMISSION_STAGED_CHAT_BANNER": "স্টেজ করা চ্যাট ব্যানার",
    "PERMISSION_CANVAS_CONTENT": "ক্যানভাস কনটেন্ট",
    "PERMISSION_YOUR_DEVICES": "আপনার ডিভাইস ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "ডিভাইস তালিকা রিফ্রেশ করুন",
    "PERMISSION_REFRESH_LIST": "তালিকা রিফ্রেশ করুন",
    "PERMISSION_NO_REGISTERED_DEVICES": "কোনো নিবন্ধিত ডিভাইস পাওয়া যায়নি।",
    "PERMISSION_RESIZE_POPUP_ARIA": "সেটিংস পপআপের আকার পরিবর্তন করুন",
    "PERMISSION_TOGGLE_PUSH_ARIA": "পুশ নোটিফিকেশন টগল করুন",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "লোকেশন অ্যাক্সেস টগল করুন",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "সতর্কতা শব্দ টগল করুন",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "অ্যাপ ব্যাজ টগল করুন",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "প্রোফাইল দৃশ্যমানতা টগল করুন",
    "PERMISSION_OFF_IN_V1": "v1-এ বন্ধ",
    "PERMISSION_CHAT": "চ্যাট",
    "PERMISSION_BANNER_LIST": "ব্যানার তালিকা",
    "PERMISSION_PUSH_DISABLED_V1": "v1 Google Play রিলিজের জন্য পুশ নোটিফিকেশন নিষ্ক্রিয়।",
    "PERMISSION_PUSH_ON_TOOLTIP": "এই ডিভাইসে পুশ নোটিফিকেশন চালু আছে।",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "সিস্টেম নোটিফিকেশন ব্লক করা আছে। সেটিংস সহায়তা খুলতে ট্যাপ করুন।",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "ডেলিভারি নির্ভরযোগ্যতা উন্নত করতে চালু করুন।",
    "PERMISSION_SYSTEM_DISABLE_HELP": "সিস্টেম নোটিফিকেশন নিষ্ক্রিয় করতে, আপনার ব্রাউজার/সাইট নোটিফিকেশন সেটিংস খুলে এই সাইটকে Block করুন।",
    "PERMISSION_SYSTEM_ALLOW_HELP": "সিস্টেম নোটিফিকেশন অনুমতি পরিবর্তন করতে, আপনার ব্রাউজার/সাইট নোটিফিকেশন সেটিংস খুলে এই সাইটকে Allow করুন।",
    "PERMISSION_LOCATION_ON_TOOLTIP": "দূরত্বভিত্তিক LCAC sorting এবং map positioning-এর জন্য লোকেশন অ্যাক্সেস চালু আছে।",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "এই পরিবেশে Location API সমর্থিত নয়।",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "লোকেশন অ্যাক্সেস ব্লক করা হয়েছে। সেটিংস সহায়তা খুলতে ট্যাপ করুন।",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "নির্ভুল দূরত্বভিত্তিক LCAC sorting এবং in-app map positioning অনুমোদন করতে চালু করুন।",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "এই পরিবেশে লোকেশন অ্যাক্সেস সমর্থিত নয়।",
    "PERMISSION_LOCATION_DISABLE_HELP": "লোকেশন অ্যাক্সেস নিষ্ক্রিয় করতে, আপনার ব্রাউজার/সাইট লোকেশন সেটিংস খুলে এই সাইটকে Block করুন।",
    "PERMISSION_LOCATION_ALLOW_HELP": "দূরত্ব sorting এবং in-app map positioning-এর জন্য লোকেশন অ্যাক্সেস চালু করতে, আপনার ব্রাউজার/সাইট লোকেশন সেটিংস খুলে এই সাইটকে Allow করুন।",
    "PERMISSION_DEVICE_LOAD_FAILED": "এই মুহূর্তে নিবন্ধিত ডিভাইস লোড করা যাচ্ছে না।",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "UI Bridge লোড হচ্ছে...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Local Bridge লোড হচ্ছে...",
    "RUNTIME_LOADING_BACKEND": "Backend লোড হচ্ছে...",
    "RUNTIME_LOADING": "লোড হচ্ছে...",
    "RUNTIME_LOADING_FROM_DATABASE": "ডাটাবেস থেকে লোড হচ্ছে...",
    "RUNTIME_BACKEND_CONNECTED": "Backend সংযুক্ত",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "ক্যাশড fallback সক্রিয়",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "ডিফল্ট fallback সক্রিয়",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "fallback ডিফল্ট সক্রিয়",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Backend-এর মাধ্যমে সংরক্ষণ হচ্ছে...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Backend সার্ভিসে সংরক্ষিত",
    "RUNTIME_SAVE_FAILED": "সংরক্ষণ ব্যর্থ",
    "RUNTIME_LOAD_FAILED": "লোড ব্যর্থ",
    "RUNTIME_CONNECTED": "সংযুক্ত",
    "RUNTIME_LOGIN_REQUIRED": "লগইন প্রয়োজন",
    "RUNTIME_SAVED": "সংরক্ষিত",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI প্রস্তুত - runtime অপেক্ষমাণ",
    "RUNTIME_BACKEND_REJECTED_MODEL": "সুরক্ষিত backend selector service অনুরোধ করা model option প্রত্যাখ্যান করেছে বা সংরক্ষণ করতে পারেনি।",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "সুরক্ষিত backend selector service অনুরোধ করা WF1 routing পরিবর্তন প্রত্যাখ্যান করেছে বা সংরক্ষণ করতে পারেনি।",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selector এখন সুরক্ষিত backend service থেকে active config, Qwen routing এবং allowed options পড়ছে।",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend selector service এখন উপলব্ধ নয়, তাই সর্বশেষ cached selector state ব্যবহার করা হচ্ছে।",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "কোনো backend বা cached selector state লোড করা যায়নি বলে selector default values সক্রিয়।",
    "RUNTIME_WF1_SELECTOR_SAVED": "সুরক্ষিত backend selector service active WF1 routing config আপডেট করেছে এবং runtime domain cache রিফ্রেশ করেছে।",
    "FRONTEND_VERSION_TITLE": "ফ্রন্টএন্ড সংস্করণ",
    "FRONTEND_VERSION_HELPER_ACTIVE": "এই selector সব ব্যবহারকারীর জন্য active frontend version নিয়ন্ত্রণ করে। FeV2.0.0 সক্রিয়।",
    "FRONTEND_VERSION_HELPER_RUNTIME": "এই selector config_domain_registry থেকে active frontend version পড়ে। Runtime FeV2.0.0-এ resolve করে।",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend frontend-version config লোড করা যায়নি, তাই startup bootstrap আবার protected service পড়তে পারা পর্যন্ত coded FeV2.0.0 default সক্রিয় থাকবে।",
    "FRONTEND_VERSION_HELPER_SAVED": "active frontend version config_domain_registry-তে সংরক্ষিত হয়েছে। সম্পূর্ণ refresh বা পরবর্তী app load runtime value প্রয়োগ করে।",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend frontend-version control service অনুরোধ করা global version সংরক্ষণ করতে পারেনি।",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "সক্রিয় frontend version।",
    "CHAT_DELETE_WINDOW_TITLE": "চ্যাট মুছে ফেলার উইন্ডো",
    "CHAT_DELETE_HELPER": "এই মানটি Delete for everyone availability window সেকেন্ডে নিয়ন্ত্রণ করে। সংরক্ষণের পর backend guard সঙ্গে সঙ্গে পরিবর্তন হয়। Bubble visibility সম্পূর্ণ refresh বা পরবর্তী app load-এর পরে পরিবর্তন হয়।",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend chat delete control service লোড করা যায়নি, তাই startup bootstrap protected service আবার পড়তে পারা পর্যন্ত coded default সক্রিয় থাকবে।",
    "CHAT_DELETE_HELPER_SAVED": "Delete for everyone availability window config_domain_registry-তে সংরক্ষিত হয়েছে। Backend guard সঙ্গে সঙ্গে পরিবর্তন হয়। Bubble visibility সম্পূর্ণ refresh বা পরবর্তী app load-এর পরে পরিবর্তন হয়।",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend chat delete control service অনুরোধ করা window value সংরক্ষণ করতে পারেনি।",
    "CHAT_DELETE_WINDOW_LABEL": "সবার জন্য মুছুন উইন্ডো",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} সেকেন্ড",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "মানটি পূর্ণ সেকেন্ডে সংরক্ষণ করুন। বর্তমান production value হলো 86400 seconds = 1 day।",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "উইন্ডো সেকেন্ড",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "০ বা তার বেশি একটি পূর্ণসংখ্যা লিখুন।",
    "CHAT_DELETE_SAVE_BUTTON": "ডিলিট উইন্ডো সংরক্ষণ করুন",
    "PROFILE_VISIBILITY_TITLE": "প্রোফাইল দৃশ্যমানতা",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "অ্যাকাউন্ট দৃশ্যমানতা পরিচালনা করতে আপনাকে লগ ইন থাকতে হবে।",
    "PROFILE_VISIBILITY_HELPER": "এই switch শুধুমাত্র আপনার account visibility state আপডেট করে। Discoverability এবং banner-list আচরণ এই ধাপে অপরিবর্তিত থাকে।",
    "PROFILE_VISIBILITY_LOAD_FAILED": "এই মুহূর্তে প্রোফাইল দৃশ্যমানতা লোড করা যায়নি।",
    "PROFILE_VISIBILITY_SAVE_FAILED": "এই মুহূর্তে প্রোফাইল দৃশ্যমানতা আপডেট করা যায়নি।",
    "PROFILE_VISIBILITY_SAVED": "আপনার অ্যাকাউন্ট দৃশ্যমানতা এখন {visibility}। Discoverability flags এই ধাপে অপরিবর্তিত থাকে।",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "সর্বজনীন অ্যাকাউন্ট",
    "PROFILE_VISIBILITY_STORED": "সংরক্ষিত দৃশ্যমানতা",
    "WF1_MODEL_CONTROL_TITLE": "WF1 মডেল নিয়ন্ত্রণ",
    "WF1_ENABLE_TRANSLATION": "অনুবাদ / Pivot সক্রিয় করুন",
    "WF1_TRANSLATION_ACTIVE": "AI অনুবাদ সক্রিয়।",
    "WF1_TRANSLATION_INACTIVE": "WF1 চলতে থাকে, কিন্তু উৎস টেক্সট কপি করা হয় এবং pivot নিষ্ক্রিয় হিসেবে চিহ্নিত হয়।",
    "WF1_ACTIVE_RUNTIME_SLOT": "সক্রিয় runtime slot",
    "WF1_ALLOW_SAME_LANGUAGE": "একই ভাষার জোড়ার জন্য AI অনুমোদন করুন",
    "WF1_SAME_LANGUAGE_ACTIVE": "একই ভাষার জোড়াগুলো স্বাভাবিক WF1 routing অনুসরণ করে।",
    "WF1_SAME_LANGUAGE_INACTIVE": "একই ভাষার জোড়াগুলো AI bypass করে এবং No Pivot language active সংরক্ষণ করে।",
    "WF1_QWEN_ROUTING": "Qwen pair routing",
    "WF1_QWEN_ROUTING_HELPER": "নিচে নির্বাচিত ভাষাগুলো Qwen-Max ব্যবহার করে যখন pair হয় একই নির্বাচিত ভাষা, নির্বাচিত ভাষা ও English, অথবা দুটি নির্বাচিত non-English ভাষা। অন্যথায় নির্বাচিত primary model সক্রিয় থাকে।",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter test slot",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter test slot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "শুধু quality test",
    "WF1_OPENROUTER_HELPER": "এই slot শুধুমাত্র অস্থায়ী OpenRouter quality test-এর জন্য editable। এই slot নিজে active model না হলে এটি operational Qwen pair-routing path পরিবর্তন করে না।",
    "WF1_LABEL": "লেবেল",
    "WF1_PRODUCT": "পণ্য",
    "WF1_MODEL": "মডেল",
    "WF1_PROVIDER_OPENROUTER": "প্রদানকারী: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter test slot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "OpenRouter-এর মাধ্যমে Qwen-Max",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google তালিকা মূল্য",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI তালিকা মূল্য",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter তালিকা মূল্য",
    "LANGUAGE_ENGLISH": "ইংরেজি",
    "LANGUAGE_CHINESE_SIMPLIFIED": "চীনা (সরলীকৃত)",
    "LANGUAGE_CHINESE_TRADITIONAL": "চীনা (ঐতিহ্যবাহী)",
    "LANGUAGE_JAPANESE": "জাপানি",
    "LANGUAGE_KOREAN": "কোরিয়ান",
    "LANGUAGE_PERSIAN": "ফারসি",
    "LANGUAGE_TURKISH_ISTANBUL": "তুর্কি (ইস্তানবুল)",
    "LANGUAGE_ARABIC": "আরবি",
    "LANGUAGE_FRENCH": "ফরাসি",
    "LANGUAGE_GERMAN": "জার্মান",
    "LANGUAGE_SPANISH": "স্প্যানিশ",
    "LANGUAGE_PORTUGUESE": "পর্তুগিজ",
    "LANGUAGE_ITALIAN": "ইতালীয়",
    "LANGUAGE_RUSSIAN": "রুশ",
    "LANGUAGE_DUTCH": "ডাচ",
    "LANGUAGE_VIETNAMESE": "ভিয়েতনামি",
    "LANGUAGE_INDONESIAN": "ইন্দোনেশীয়",
    "LANGUAGE_THAI": "থাই",
    "LANGUAGE_MALAY": "মালয়",
    "WF1_PRICING_CUSTOM": "মূল্য: custom slot model - বর্তমান OpenRouter pricing পরীক্ষা করুন",
    "WF1_SAVE_OPENROUTER_SLOT": "OpenRouter slot সংরক্ষণ করুন",
    "WF1_PRICING_LINE": "ইনপুট {input} - আউটপুট {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "জোন দৃশ্যমানতা নিয়ন্ত্রণ",
    "ZONE_ENABLE": "{zone} সক্রিয় করুন",
    "ZONE_ENABLED_NOTE": "পরবর্তী app load-এর পরে {zone} অনুমোদিত roles-এর জন্য দেখা যেতে পারে।",
    "ZONE_DISABLED_NOTE": "পরবর্তী app load-এর পরে non-S_Admin ব্যবহারকারীদের জন্য {zone} অনুপস্থিত হিসেবে গণ্য হবে।",
    "ZONE_S_ADMIN_BYPASS": "S_Admin এই role list bypass করে এবং সবসময় access রাখে।",
    "ZONE_ROLE_LOCKED": "এই zone নিষ্ক্রিয় থাকাকালে role selections সাময়িকভাবে locked থাকে এবং zone আবার সক্রিয় হলে সংরক্ষিত অবস্থার মতোই ফিরে আসবে।",
    "ZONE_LCAC_CONTROL": "LCAC নিয়ন্ত্রণ",
    "ZONE_RCAC_CONTROL": "RCAC নিয়ন্ত্রণ",
    "ZONE_LCAC_DESCRIPTION": "বাম reserved zone-এর অস্তিত্ব এবং কোন roles এটি দেখতে পাবে তা নিয়ন্ত্রণ করে।",
    "ZONE_RCAC_DESCRIPTION": "ডান reserved zone-এর অস্তিত্ব এবং কোন roles এটি দেখতে পাবে তা নিয়ন্ত্রণ করে।",
    "ZONE_VISIBILITY_BACKEND": "Zone visibility bootstrap এখন protected backend service থেকে পড়ছে। পরিবর্তনগুলো পরবর্তী app load-এ প্রয়োগ হবে।",
    "ZONE_VISIBILITY_CACHED": "Backend zone visibility service এখন উপলব্ধ নয়, তাই cached বা local defaults সক্রিয়।",
    "ZONE_VISIBILITY_DEFAULTS": "কোনো backend বা cached state লোড করা যায়নি বলে zone visibility defaults সক্রিয়।",
    "ZONE_VISIBILITY_SAVED": "Zone visibility bootstrap সংরক্ষিত হয়েছে। Runtime application-এর জন্য hard reload বা next app load প্রয়োজন।",
    "ZONE_VISIBILITY_SAVE_FAILED": "Protected backend service অনুরোধ করা zone visibility change সংরক্ষণ করতে পারেনি।",
    "ROLE_MEMBER": "সদস্য",
    "ROLE_STAFF": "স্টাফ",
    "ROLE_ADMIN": "অ্যাডমিন",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "নতুন বার্তা পেতে নোটিফিকেশন সক্রিয় করুন।",
    "MAIN_LOG_OUT": "লগ আউট",
    "NOTIFICATION_NEW_MESSAGE": "নতুন বার্তা",
    "NOTIFICATION_UNREAD_MESSAGE": "আপনার একটি অপঠিত বার্তা আছে।",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "পূর্ণ ভিউ",
    "MEDIA_AUDIO_ATTACHMENT": "অডিও সংযুক্তি",
    "MEDIA_FILE_FALLBACK": "ফাইল",
    "MEDIA_DOWNLOAD_READY": "সংযুক্তি ডাউনলোডের জন্য প্রস্তুত",
    "MEDIA_TYPE_UNSUPPORTED": "পূর্ণ ভিউয়ের জন্য টাইপ সমর্থিত নয়",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "আগের ছবি",
    "MEDIA_NEXT_IMAGE_ARIA": "পরের ছবি",
    "MEDIA_OPEN_ORIGINAL": "মূলটি খুলুন",
    "MEDIA_DOWNLOAD": "ডাউনলোড",
    "MEDIA_CLOSE_ARIA": "বন্ধ",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name}-এর প্রোফাইল ছবি",
    "MEDIA_PROFILE_ALT": "{name}-এর প্রোফাইল",
    "MEDIA_UPLOAD_FAILED": "আপলোড ব্যর্থ",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend token ত্রুটি",
    "MEDIA_UPLOAD_URL_MISSING": "গুরুতর: backend response-এ upload URL অনুপস্থিত।",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "চ্যাট আপলোডের জন্য auth token অনুপস্থিত",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "চ্যাট upload token request ব্যর্থ হয়েছে",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "অবৈধ chat upload response",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS আপলোড ব্যর্থ",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "ফাইলের নাম বা contentType অনুপস্থিত",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path অনুপস্থিত",
    "BLOCK_NOTICE_TITLE": "স্থায়ী ব্লক নোটিশ",
    "BLOCK_NOTICE_MESSAGE": "নীতি লঙ্ঘনের কারণে আপনার অ্যাকাউন্ট সাময়িকভাবে স্থগিত করা হয়েছে।",
    "BLOCK_NOTICE_CONTACT_PREFIX": "আপনি যদি মনে করেন এর follow-up প্রয়োজন, অনুগ্রহ করে যোগাযোগ করুন",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "ইমেলের মাধ্যমে।",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "অজানা ব্যবহারকারী",
    "GENERAL_GUEST": "অতিথি",
    "ADVISOR_FOR_CLIENT": "{client_display_name}-এর জন্য উপদেষ্টা",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "টোকেন এবং পাসওয়ার্ড প্রয়োজন",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Request body অবশ্যই JSON হতে হবে",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "অবৈধ বা মেয়াদোত্তীর্ণ আমন্ত্রণ টোকেন",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "পাসওয়ার্ড সেট ব্যর্থ: session বা user অনুপস্থিত",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "sign-in চলাকালে পাসওয়ার্ড সেট ব্যর্থ হয়েছে",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Admin token generation ব্যর্থ হয়েছে",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "লগইন ব্যর্থ: session বা user অনুপস্থিত",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "নিবন্ধন সফল। যাচাইয়ের জন্য অনুগ্রহ করে ইমেল দেখুন।",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "সাইনআপ অজানা কারণে ব্যর্থ",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "অবৈধ token processing",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Access token প্রয়োজন",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Token hash preview-এর জন্য redirect URL থেকে email hint প্রয়োজন",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "এই token-এর জন্য identity resolve করা যায়নি",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "শুধুমাত্র User Zero WF1 LLM selector service অ্যাক্সেস করতে পারে।",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "শুধুমাত্র User Zero zone visibility control service অ্যাক্সেস করতে পারে।",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "শুধুমাত্র User Zero frontend version control service অ্যাক্সেস করতে পারে।",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "শুধুমাত্র User Zero অন্য ব্যবহারকারীর frontend version inspect করতে পারে।",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "শুধুমাত্র User Zero chat delete control service অ্যাক্সেস করতে পারে।",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "শুধুমাত্র User Zero স্থায়ীভাবে ব্যবহারকারী অ্যাকাউন্ট মুছতে পারে।",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "অবৈধ request payload।",
    "API_ERROR_INTERNAL_SERVER": "Internal Server Error",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Backend-এ function অনুপস্থিত (Reload Required)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "delivered/read transitions-এর জন্য শুধুমাত্র DB RPC অনুমোদিত।",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "আরেকটি বার্তা পাঠানোর আগে অনুগ্রহ করে অপেক্ষা করুন।",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "বার্তা সফলভাবে পাঠানো হয়েছে।",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Contact service উপলব্ধ নয়।",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "বার্তা পাঠানো ব্যর্থ হয়েছে।",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "নাম প্রয়োজন।",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "ইমেল অবৈধ।",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "বার্তা প্রয়োজন।",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Selector payload প্রয়োজন।",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Zone visibility payload প্রয়োজন।",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Frontend version payload প্রয়োজন।",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Chat delete control payload প্রয়োজন।",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Authenticated user id প্রয়োজন।",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Authenticated viewer user id প্রয়োজন।",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Authenticated actor user id প্রয়োজন।",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id প্রয়োজন।",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id প্রয়োজন।",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids list প্রয়োজন।",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email প্রয়োজন।",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by প্রয়োজন।",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Global frontend version দ্বারা search runtime নিষ্ক্রিয়।",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "আপনি এই অপেক্ষমাণ আমন্ত্রণ বাতিল করার অনুমতিপ্রাপ্ত নন।",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "ব্যবহারকারী ইতিমধ্যে নিবন্ধিত হওয়ায় এই আমন্ত্রণ আর বাতিল করা যাবে না।",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "অপেক্ষমাণ আমন্ত্রণ পাওয়া যায়নি।",
    "INVITE_REPLY_ALREADY_MEMBER": "অভিনন্দন, আপনার বন্ধু ({invitee_email}) ইতিমধ্যে এই অ্যাপে নিবন্ধিত এবং এই workspace-এর সদস্য।",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "{invitee_email}-এর জন্য একটি আমন্ত্রণ অপেক্ষমাণ আছে, কিন্তু retry email trigger করা যায়নি। অনুগ্রহ করে mail logs পরীক্ষা করুন।",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "{invitee_email}-এর জন্য invitation record তৈরি হয়েছে, কিন্তু email delivery নিশ্চিত করা যায়নি। অনুগ্রহ করে পরে আবার চেষ্টা করুন বা mail logs পরীক্ষা করুন।",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Invitation record তৈরি করতে ব্যর্থ। অনুগ্রহ করে পরে আবার চেষ্টা করুন।",
    "INVITE_REPLY_SYSTEM_ERROR": "আমন্ত্রণ প্রক্রিয়ার সময় সিস্টেম ত্রুটি: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend configuration error: Supabase credentials অনুপস্থিত",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend configuration error: অবৈধ Supabase URL",
    "CHAT_ERROR_ACCESS_DENIED": "অ্যাক্সেস অস্বীকার",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "টেক্সট বার্তার জন্য content খালি হতে পারে না",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "conversation ID নির্ধারণ করা যায়নি",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC auth context অনুপস্থিত",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC অবৈধ message payload ফিরিয়েছে",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Insert ব্যর্থ, কোনো data ফেরত আসেনি",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations অবশ্যই একটি list হতে হবে",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "অবৈধ operation payload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "সমর্থিত নয় এমন operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id প্রয়োজন",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "বার্তা পাওয়া যায়নি",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "মুছে ফেলা শুধুমাত্র আপনার নিজের বার্তার জন্য অনুমোদিত",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "এই বার্তার জন্য Delete for everyone আর উপলব্ধ নয়",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Delete for everyone ব্যর্থ হয়েছে",
    "API_ERROR_SERVER_CONFIGURATION": "Server configuration error",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Webhook secret header অনুপস্থিত",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "অননুমোদিত webhook source",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend configuration error",
    "API_ERROR_MODULE_ATTRIBUTE": "Module Attribute Error: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "অপেক্ষমাণ auth user সরানোর সময় invitation deletion-এর আগে ব্যর্থ হয়েছে।",
    "CHAT_ERROR_DB": "DB Error: {error}",
}
