# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/en.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Hlavní",
    "APP_TITLE": "AI platforma OTMEGA",
    "APP_SUBTITLE": "AI poradce",
    "CHAT_PLACEHOLDER": "Napište svou zprávu...",
    "CHAT_SEND_BUTTON": "Odeslat",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Poradce se může mýlit, proto si informace ověřte.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Nový chat",
    "ICON_HISTORY": "Historie",
    "ICON_TEMPLATES": "Šablony",
    "ICON_SETTINGS": "Nastavení",
    "ICON_USER_PROFILE": "Profil uživatele",
    "ICON_QUICK_ACTIONS": "Rychlé akce",
    "ICON_PINNED": "Připnuto",
    "ICON_GALLERY": "Galerie",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Instalovat aplikaci",
    "PWA_ANDROID_MSG": "Nainstalujte si tuto aplikaci do zařízení pro lepší zážitek a offline přístup.",
    "PWA_IOS_MSG": "Chcete-li tuto aplikaci nainstalovat na iPhone/iPad:\n1. Klepněte dole na tlačítko Sdílet\n2. Vyberte 'Přidat na plochu'",
    "PWA_BTN_INSTALL": "Instalovat",
    "PWA_BTN_LATER": "Možná později",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Přihlaste se do sítě poradců",
    "AUTH_HEADER_SIGNUP": "Vytvořte si sjednocený účet",
    "AUTH_HEADER_LOGIN_NETWORK": "Přihlaste se do sítě poradců",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Vytvořte si sjednocený účet",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Přihlášení",
    "AUTH_BUTTON_SIGNUP": "Vytvořit účet",
    "AUTH_BUTTON_GOOGLE": "Pokračovat přes Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Zapomenuté heslo",
    "AUTH_BUTTON_SEND_RESET_LINK": "Odeslat odkaz pro reset",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Nemáte účet? Zaregistrujte se",
    "AUTH_PROMPT_LOGIN": "Už máte účet? Přihlaste se",
    "AUTH_HELPER_TEXT_SIGNUP": "Vytváříte sjednocený účet, který můžete používat pro přístup ke všem poradcům na této platformě.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Vytváříte sjednocený účet, který můžete používat pro přístup ke všem poradcům na této platformě.",
    "AUTH_HELPER_TEXT_LOGIN": "Použijte stejný účet (e-mail/heslo nebo Google), který jste používali u jiných poradců v této síti.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Použijte stejný účet (e-mail/heslo nebo Google), který jste používali u jiných poradců v této síti.",
    "AUTH_FORGOT_PASSWORD_LINK": "Zapomněli jste heslo?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Resetovat heslo",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Zadejte svou e-mailovou adresu a pošleme vám odkaz pro resetování hesla.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-mail",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Přihlašování...",
    "AUTH_STATUS_LOADING_SIGNUP": "Vytváření účtu...",
    "AUTH_STATUS_LOADING_RESET": "Odesílání odkazu pro reset...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Přihlášení proběhlo úspěšně! Znovu načítání...",
    "AUTH_STATUS_SUCCESS_RESET": "Odkaz pro reset byl úspěšně odeslán. Zkontrolujte svůj e-mail.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Odkaz pro resetování hesla byl úspěšně odeslán. Zkontrolujte svůj e-mail.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Neplatný e-mail nebo heslo.",
    "AUTH_ERROR_EMAIL_EXISTS": "Účet s tímto e-mailem již v síti poradců existuje.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Účet s tímto e-mailem již existuje. Přihlaste se. Aktuálně jste členem:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Účet s tímto e-mailem již v síti poradců existuje. Zavřete toto okno a použijte sekci 'Login' se stejným e-mailem a svým předchozím heslem.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Aktuálně jste členem:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-mail a heslo jsou povinné.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Účet byl vytvořen, ale nepodařilo se nastavit členství. Kontaktujte podporu.",
    "AUTH_ERROR_DEFAULT": "Došlo k chybě. Zkuste to prosím znovu.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Nepodařilo se odeslat odkaz pro reset. Zkuste to prosím znovu.",
    "INVITE_REPLY_EMAIL_SENT": "E-mail s pozvánkou Collabra byl odeslán vašemu příteli na adresu {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "E-mail s pozvánkou Collabra byl znovu odeslán vašemu příteli na adresu {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Zobrazit heslo",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Skrýt heslo",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Zrušit",
    "GENERAL_CLOSE": "Zavřít",
    "GENERAL_SEND": "Odeslat",
    "GENERAL_SEARCH": "Hledat",
    "GENERAL_RESET": "Resetovat",
    "GENERAL_ENABLE": "Povolit",
    "GENERAL_LOADING": "Načítání...",
    "GENERAL_DELETE": "Smazat",
    "GENERAL_DELETING": "Mazání...",
    "GENERAL_SAVE_PASSWORD": "Uložit heslo",
    "AUTH_REMEMBER_EMAIL_LABEL": "Zapamatovat e-mail",
    "GENERAL_SAVING": "Ukládání...",
    "GENERAL_SENDING": "Odesílání...",
    "GENERAL_REMOVING": "Odebírání...",
    "GENERAL_CONFIRM_REMOVAL": "Potvrdit odebrání",
    "GENERAL_EMPTY": "Prázdné",
    "GENERAL_UNAVAILABLE": "Nedostupné",
    "GENERAL_ENABLED": "Povoleno",
    "GENERAL_DISABLED": "Zakázáno",
    "GENERAL_GRANTED": "Uděleno",
    "GENERAL_DENIED": "Odmítnuto",
    "GENERAL_DEFAULT": "Výchozí",
    "GENERAL_UNSUPPORTED": "Nepodporováno",
    "GENERAL_PUBLIC": "Veřejné",
    "GENERAL_PRIVATE": "Soukromé",
    "GENERAL_USERNAME": "Uživatelské jméno",
    "GENERAL_EMAIL": "E-mail",
    "GENERAL_YOU": "Vy",
    "GENERAL_USER": "Uživatel",
    "GENERAL_UNKNOWN": "Neznámé",
    "GENERAL_VISITOR": "Návštěvník",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Neznámý banner",
    "GENERAL_ADVISOR_BANNER": "Banner poradce",
    "GENERAL_NOT_AVAILABLE": "N/A",
    "GENERAL_NOT_SELECTED": "Nevybráno",
    "GENERAL_NO_EMAIL_FOUND": "Nebyl nalezen žádný e-mail",
    "GENERAL_USER_ZERO_ONLY": "Pouze User Zero",
    "GENERAL_CONNECTION_STATE": "Stav připojení",
    "GENERAL_DISPLAY_ONLY": "Pouze zobrazení",
    "GENERAL_TEXTAREA": "Textové pole",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Rychlé akce (RCAC)",
    "HEADER_CHANGE_STATUS": "Změnit stav",
    "HEADER_OT_COIN_BALANCE": "Zůstatek OT Coin",
    "HEADER_ALT_USER": "Uživatel",
    "STATUS_BUSY": "Zaneprázdněn",
    "STATUS_AWAY": "Pryč",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Neviditelný",
    "NETWORK_CHECKING_CONNECTION": "Kontrola připojení...",
    "NETWORK_ONLINE_LATENCY": "Online (latence: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Síť: dobrá (klepnutím otestovat ping)",
    "CHAT_TARGET_ALT": "Cíl chatu",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Hledat...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Otevřít profilový obrázek {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Pole zprávy",
    "CHAT_TOGGLE_VIEW_ARIA": "Přepnout zobrazení",
    "CHAT_ADD_USER_ARIA": "Přidat uživatele",
    "CHAT_ATTACH_ARIA": "Přiložit",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Odeslat",
    "CHAT_SEARCH_ARIA": "Hledat",
    "CHAT_OPEN_SEARCH_ARIA": "Otevřít hledání",
    "CHAT_CLOSE_SEARCH_ARIA": "Zavřít hledání",
    "CHAT_ATTACHMENT_ALT": "Příloha",
    "CHAT_PREVIEW_ALT": "Náhled",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Odebrat přílohu",
    "CHAT_REPLYING_TO": "Odpověď na",
    "CHAT_CANCEL_REPLY_ARIA": "Zrušit odpověď",
    "CHAT_UPLOADING": "Nahrávání...",
    "CHAT_LOADING_CHATS": "Načítání chatů...",
    "CHAT_SEND_FAILED": "Odeslání se nezdařilo",
    "CHAT_SEND_FAILED_RETRY": "Odeslání se nezdařilo. Zkuste to prosím znovu.",
    "CHAT_RETRY": "Zkusit znovu",
    "CHAT_EDITED": "upraveno",
    "CHAT_TYPING": "Píše",
    "CHAT_LOADING": "Načítání",
    "CHAT_PENDING_INVITATION": "Čekající pozvánka",
    "CHAT_PENDING_INVITATION_MIN": "{count} min čekající pozvánka",
    "CHAT_PENDING_INVITATION_HR": "{count} h čekající pozvánka",
    "CHAT_PENDING_INVITATION_DAY": "{count} d čekající pozvánka",
    "CHAT_WAITING_FOR_YOU": "{label} - Čeká na vás",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Čeká na přijetí",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Přístup k mikrofonu byl odepřen.",
    "CHAT_UPLOAD_FAILED": "Nahrávání se nezdařilo: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Nahrávání vyžaduje připojení k internetu. Zkuste to znovu, až budete online.",
    "CHAT_ERROR_AUTH": "Chyba ověření",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Chybí název souboru nebo content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Chybí conversation_id nebo target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Chybí conversation_id pro nahrávání mimo avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Neplatný file_path avataru",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Klient služby Supabase není dostupný",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Potvrzení přečtení avataru je platné pouze v kontextu chatu poradce",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Zpráva toku avataru nebyla nalezena nebo není způsobilá pro potvrzení přečtení",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Nepodařilo se dokončit zprávu avataru jako přečtenou",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 příloha",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} příloh",
    "CHAT_VOICE_NOTE": "Hlasová poznámka",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat není dostupný. Tento uživatel vás zablokoval.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat není dostupný. Zablokovali jste tohoto uživatele.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Přístup k účtu je zablokován zásadami.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat není dostupný. Tento účet je finálně zablokován uživatelem User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat není dostupný. Vzájemné blokování je aktivní.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat není dostupný kvůli zásadám blokování.",
    "MESSAGE_PREVIEW_PHOTO": "Fotografie",
    "MESSAGE_PREVIEW_VOICE": "Hlasová zpráva",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Soubor",
    "MESSAGE_PREVIEW_MESSAGE": "Zpráva",
    "MESSAGE_PREVIEW_SYSTEM": "Systémová zpráva",
    "MESSAGE_PREVIEW_NEW": "Nová zpráva",
    "MESSAGE_UNKNOWN_FILE": "Neznámý soubor",
    "MESSAGE_AUDIO_ATTACHMENT": "Zvuková příloha",
    "MESSAGE_FILE_ATTACHMENT": "Příloha",
    "BANNER_INVITED_BY": "pozval {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Výsledky hledání",
    "SEARCH_QUERY_LABEL": "Dotaz:",
    "SEARCH_LOADING_VISIBILITY": "Načítání viditelnosti hledání...",
    "SEARCH_NO_RESULTS": "V aktuálním rozsahu hledání nebyl nalezen žádný výsledek.",
    "SHARE_WITH_COLLABRA": "Sdílet s Collabra",
    "SHARE_SEND_TO": "Odeslat komu",
    "SHARE_SELECT_ONE_BANNER": "Vyberte jeden banner",
    "SHARE_BANNER_LIST_ARIA": "Seznam bannerů",
    "SHARE_NO_MATCHING_BANNER": "Žádný odpovídající banner",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Přidat komentář...",
    "SHARE_RECENT_CHATS": "Nedávné chaty",
    "SHARE_LEFT_LIST": "Levý seznam",
    "SHARE_RIGHT_LIST": "Pravý seznam",
    "SHARE_UNTITLED_BANNER": "Banner bez názvu",
    "SHARE_SHARED_CONTENT": "Sdílený obsah",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Sdílený obsah se nepodařilo otevřít.",
    "SHARE_OPEN_BANNER_FAILED": "Vybraný banner se nepodařilo otevřít.",
    "SHARE_ONE_PHOTO_SELECTED": "Vybrána 1 fotografie",
    "SHARE_MANY_PHOTOS_SELECTED": "Vybráno {count} fotografií",
    "SHARE_ONE_FILE_SELECTED": "Vybrán 1 soubor",
    "SHARE_MANY_FILES_SELECTED": "Vybráno {count} souborů",
    "FORWARD_MESSAGE_TITLE": "Přeposlat zprávu",
    "FORWARD_SELECT_RECIPIENTS": "Vyberte příjemce",
    "FORWARD_NO_OTHER_BANNER": "Není dostupný žádný jiný banner.",
    "FORWARD_SEND_TO_COUNT": "Odeslat pro {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Vyberte alespoň jeden banner.",
    "FORWARD_FAILED_DEFAULT": "Přeposlání se nezdařilo. Zkuste to prosím znovu.",
    "FORWARD_PARTIAL_SENT": "Odesláno {count}. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Zdrojová zpráva pro přeposlání nebyla nalezena",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Tato zpráva zatím nemá obsah, který lze přeposlat",
    "FORWARD_DESTINATION_MISSING": "Chybí cíl přeposlání",
    "FORWARD_MESSAGE_PREVIEW": "Přeposlaná zpráva",
    "MENU_PASTE": "Vložit",
    "MENU_COPY": "Kopírovat",
    "MENU_REPLY": "Odpovědět",
    "MENU_FORWARD": "Přeposlat",
    "MENU_REMOVE_INVITATION": "Odebrat pozvánku",
    "MENU_REMOVE_FROM_LIST": "Odebrat ze seznamu",
    "MENU_ADD_TO_LIST": "Přidat do seznamu",
    "MENU_REJECT_INVITATION": "Odmítnout pozvánku",
    "MENU_FRONTEND_VERSION": "Verze frontendu",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Informace o banneru: {title}",
    "MENU_MESSAGE_BUBBLE": "Bublina zprávy",
    "MENU_CHAT_CANVAS_HEADER": "Plátno chatu - {zone}",
    "MENU_CANVAS_INFO": "Informace o plátně",
    "MENU_CHAT_CANVAS_SUBLABEL": "Oblast konverzace / aktuální plocha chatu",
    "MENU_INPUT_AREA_HEADER": "Vstupní oblast - {zone}",
    "MENU_INPUT_AREA_INFO": "Informace o vstupní oblasti: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Spodní plocha pro psaní a akční nástroje",
    "MENU_HEADER": "Záhlaví - {zone}",
    "MENU_HEADER_INFO": "Informace o záhlaví: {title}",
    "MENU_HEADER_DESCRIPTION": "Horní navigace a ovládací prvky stránky",
    "MENU_ZONE_HEADER": "Zóna - {zone}",
    "MENU_ZONE_SPACE_INFO": "Informace o prostoru zóny",
    "MENU_EMPTY_LIST_SURFACE": "Prázdná/seznamová plocha",
    "MENU_BLOCK": "Blokovat",
    "MENU_UNBLOCK": "Odblokovat",
    "MENU_HIDE_IN_SEARCH": "Skrýt ve vyhledávání",
    "MENU_UNHIDE_IN_SEARCH": "Zobrazit ve vyhledávání",
    "MENU_VISIBLE_IN_SEARCH": "Viditelné ve vyhledávání",
    "MENU_HIDDEN_IN_SEARCH": "Skryté ve vyhledávání",
    "MENU_VISIBLE_IN_USER_LIST": "Viditelné v seznamu uživatelů",
    "MENU_HIDDEN_IN_USER_LIST": "Skryté v seznamu uživatelů",
    "MENU_NOT_BLOCKED": "Není blokováno",
    "MENU_BLOCKED": "Blokováno",
    "MENU_FRONTEND_VERSION_LOADING": "Načítání...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Načítá se hodnota pro banner z backendu. Dokud nedorazí odpověď databáze, není žádná možnost označena jako aktivní.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Hodnotu z backendu se nepodařilo načíst. Není zobrazena žádná důvěryhodná aktivní možnost.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Explicitní databázová hodnota pro banner je {overrideVersion}. Globální výchozí hodnota je {globalDefaultVersion}. Cílový uživatel musí aplikaci úplně obnovit nebo znovu otevřít, aby ji startovací bootstrap použil.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Není uložena žádná explicitní databázová hodnota pro banner. FeV2.0.0 je ve výchozím stavu aktivní. Globální výchozí hodnota je {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Explicitní databázová hodnota pro banner se aktivuje po úplném opětovném načtení cílové aplikace",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Není uložena žádná explicitní hodnota pro banner; toto je výchozí individuální stav FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Tato možnost se také rovná aktuální globální výchozí hodnotě",
    "MENU_DELETE_PERMANENT_CONFIRM": "Trvale smazat {target} z databáze? Tím se odstraní účet, historie chatu, závislosti a pro budoucí opětovný vstup bude vynucena úplně nová cesta pozvánky.",
    "MENU_DELETE_PERMANENTLY": "Trvale smazat",
    "MENU_REFRESH_PAGE": "Obnovit stránku",
    "MENU_LOG_OFF": "Odhlásit se",
    "MENU_HARD_RELOAD": "Tvrdé obnovení",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-mail (admin uživatel)",
    "AUTH_PASSWORD_PLACEHOLDER": "Heslo",
    "AUTH_CONNECTING": "Připojování...",
    "AUTH_SIGNING_OUT": "Odhlašování...",
    "AUTH_BACK_TO_LOGIN": "Zpět na přihlášení",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Neplatná odpověď serveru: nebyl nalezen žádný token.",
    "AUTH_LOGIN_FAILED": "Přihlášení se nezdařilo",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Hesla se neshodují.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Hesla se neshodují!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Hesla se musí přesně shodovat.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nové heslo",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Potvrdit heslo",
    "AUTH_CHANGE_PASSWORD": "Změnit heslo",
    "AUTH_SAVING_PASSWORD": "Ukládání...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Heslo bylo úspěšně aktualizováno.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Heslo teď nelze změnit.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Pro změnu hesla musíte být přihlášeni.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Přepnout viditelnost nového hesla",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Přepnout viditelnost potvrzení hesla",
    "REGISTER_TITLE": "Dokončit registraci",
    "REGISTER_SUBTITLE": "Nastavte prosím své heslo ručně.",
    "REGISTER_CREATING_ACCOUNT": "Vytváření účtu...",
    "REGISTER_FINISH_SETUP": "Dokončit nastavení",
    "REGISTER_FAILED_SET_PASSWORD": "Nepodařilo se nastavit heslo",
    "INVITE_EMAIL_INSTRUCTION": "Zadejte e-mail pozvaného (formát: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Pozvat",
    "INVITE_EMAIL_REQUIRED": "Zadejte prosím e-mail pozvaného.",
    "INVITE_EMAIL_INVALID": "Neplatný formát e-mailu. Použijte: user@example.com",
    "PENDING_INVITATION_TITLE": "Čekající pozvánka",
    "PENDING_INVITATION_REMOVE_QUESTION": "Odebrat tuto čekající pozvánku z databáze?",
    "PENDING_INVITATION_KEEP": "Ponechat pozvánku",
    "PENDING_INVITATION_REMOVAL_FAILED": "Odebrání se nezdařilo.",
    "REMOVE_FROM_LIST_TITLE": "Odebrat ze seznamu",
    "REMOVE_FROM_LIST_WARNING": "Odebrat tohoto uživatele nyní z obou seznamů? Přístup k chatu bude okamžitě odříznut. Jedinou cestou zpět je nová pozvánka.",
    "REMOVE_FROM_LIST_KEEP": "Ponechat uživatele v seznamu",
    "REMOVE_FROM_LIST_FAILED": "Odebrání ze seznamu se nezdařilo.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Nastavení a živý stav",
    "PERMISSION_DIALOG_ARIA": "Nastavení a živý stav",
    "PERMISSION_TRIGGER_ARIA": "Spouštěč vyskakovacího okna nastavení",
    "PERMISSION_CLOSE_ARIA": "Zavřít vyskakovací okno oprávnění",
    "PERMISSION_LIVE_STATUS": "Živý stav",
    "PERMISSION_SYSTEM_PERMISSION": "Systémové oprávnění",
    "PERMISSION_APP_PUSH": "Push aplikace",
    "PERMISSION_LOCATION_PERMISSION": "Oprávnění k poloze",
    "PERMISSION_APP_LOCATION": "Poloha aplikace",
    "PERMISSION_CONTROLS": "Ovládání oprávnění",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push oznámení",
    "PERMISSION_LOCATION_ACCESS": "Přístup k poloze",
    "PERMISSION_IN_APP_SETTINGS": "Nastavení v aplikaci",
    "PERMISSION_ALERT_SOUND": "Zvuk upozornění",
    "PERMISSION_APP_BADGE": "Odznak aplikace",
    "PERMISSION_PASSWORD_SETTINGS": "Nastavení hesla",
    "PERMISSION_NAVIGATION_STATUS": "Stav navigace",
    "PERMISSION_SELECTED_ZONE": "Vybraná zóna",
    "PERMISSION_STAGED_CHAT_BANNER": "Připravený banner chatu",
    "PERMISSION_CANVAS_CONTENT": "Obsah plátna",
    "PERMISSION_YOUR_DEVICES": "Vaše zařízení ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Obnovit seznam zařízení",
    "PERMISSION_REFRESH_LIST": "Obnovit seznam",
    "PERMISSION_NO_REGISTERED_DEVICES": "Nebyla nalezena žádná registrovaná zařízení.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Změnit velikost vyskakovacího okna nastavení",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Přepnout push oznámení",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Přepnout přístup k poloze",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Přepnout zvuk upozornění",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Přepnout odznak aplikace",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Přepnout viditelnost profilu",
    "PERMISSION_OFF_IN_V1": "Vypnuto ve v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Seznam bannerů",
    "PERMISSION_PUSH_DISABLED_V1": "Push oznámení jsou pro vydání v1 Google Play zakázána.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Push oznámení jsou pro toto zařízení zapnutá.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Systémová oznámení jsou blokována. Klepnutím otevřete nápovědu k nastavení.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Zapněte pro zlepšení spolehlivosti doručování.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Chcete-li zakázat systémová oznámení, otevřete nastavení oznámení prohlížeče/webu a nastavte tento web na Blokovat.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Chcete-li změnit oprávnění systémových oznámení, otevřete nastavení oznámení prohlížeče/webu a nastavte tento web na Povolit.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Přístup k poloze je zapnutý pro řazení LCAC podle vzdálenosti a umístění na mapě.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API polohy není v tomto prostředí podporováno.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Přístup k poloze je blokován. Klepnutím otevřete nápovědu k nastavení.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Zapněte pro povolení přesného řazení LCAC podle vzdálenosti a umístění na mapě v aplikaci.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Přístup k poloze není v tomto prostředí podporován.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Chcete-li zakázat přístup k poloze, otevřete nastavení polohy prohlížeče/webu a nastavte tento web na Blokovat.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Chcete-li povolit přístup k poloze pro řazení podle vzdálenosti a umístění na mapě v aplikaci, otevřete nastavení polohy prohlížeče/webu a nastavte tento web na Povolit.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Registrovaná zařízení se teď nepodařilo načíst.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Načítání UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Načítání Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Načítání backendu...",
    "RUNTIME_LOADING": "Načítání...",
    "RUNTIME_LOADING_FROM_DATABASE": "Načítání z databáze...",
    "RUNTIME_BACKEND_CONNECTED": "Backend připojen",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Aktivní záložní režim z mezipaměti",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Aktivní výchozí záložní režim",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Aktivní výchozí záložní hodnoty",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Ukládání přes backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Uloženo ve službě backendu",
    "RUNTIME_SAVE_FAILED": "Uložení se nezdařilo",
    "RUNTIME_LOAD_FAILED": "Načtení se nezdařilo",
    "RUNTIME_CONNECTED": "Připojeno",
    "RUNTIME_LOGIN_REQUIRED": "Vyžadováno přihlášení",
    "RUNTIME_SAVED": "Uloženo",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI připraveno - runtime čeká",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Chráněná backendová služba selektoru odmítla nebo nemohla uložit požadovanou možnost modelu.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Chráněná backendová služba selektoru odmítla nebo nemohla uložit požadovanou změnu směrování WF1.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selektor nyní čte aktivní konfiguraci, směrování Qwen a povolené možnosti z chráněné backendové služby.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backendová služba selektoru je právě nedostupná, proto se používá poslední stav selektoru z mezipaměti.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Výchozí hodnoty selektoru jsou aktivní, protože nebylo možné načíst žádný backendový ani uložený stav selektoru.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Chráněná backendová služba selektoru aktualizovala aktivní konfiguraci směrování WF1 a obnovila mezipaměť runtime domény.",
    "FRONTEND_VERSION_TITLE": "Verze frontendu",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Tento selektor řídí aktivní verzi frontendu pro všechny uživatele. FeV2.0.0 je aktivní.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Tento selektor čte aktivní verzi frontendu z config_domain_registry. Runtime se vyhodnotí jako FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Konfiguraci verze frontendu z backendu se nepodařilo načíst, proto zůstává aktivní zakódovaná výchozí hodnota FeV2.0.0, dokud startovací bootstrap znovu nepřečte chráněnou službu.",
    "FRONTEND_VERSION_HELPER_SAVED": "Aktivní verze frontendu byla uložena v config_domain_registry. Úplné obnovení nebo další načtení aplikace použije runtime hodnotu.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backendová služba řízení verze frontendu nemohla uložit požadovanou globální verzi.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktivní verze frontendu.",
    "CHAT_DELETE_WINDOW_TITLE": "Okno mazání chatu",
    "CHAT_DELETE_HELPER": "Tato hodnota řídí okno dostupnosti funkce Smazat pro všechny v sekundách. Backendová kontrola se změní okamžitě po uložení. Viditelnost bubliny se změní po úplném obnovení nebo při dalším načtení aplikace.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backendovou službu řízení mazání chatu se nepodařilo načíst, proto zůstává aktivní zakódovaná výchozí hodnota, dokud startovací bootstrap znovu nepřečte chráněnou službu.",
    "CHAT_DELETE_HELPER_SAVED": "Okno dostupnosti funkce Smazat pro všechny bylo uloženo v config_domain_registry. Backendová kontrola se změní okamžitě. Viditelnost bubliny se změní po úplném obnovení nebo při dalším načtení aplikace.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backendová služba řízení mazání chatu nemohla uložit požadovanou hodnotu okna.",
    "CHAT_DELETE_WINDOW_LABEL": "Okno Smazat pro všechny",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} s",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Uložte hodnotu v celých sekundách. Aktuální produkční hodnota je 86400 sekund = 1 den.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Sekundy okna",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Zadejte celé číslo větší nebo rovné 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Uložit okno mazání",
    "PROFILE_VISIBILITY_TITLE": "Viditelnost profilu",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Pro správu viditelnosti účtu musíte být přihlášeni.",
    "PROFILE_VISIBILITY_HELPER": "Tento přepínač aktualizuje pouze stav viditelnosti vašeho účtu. Dohledatelnost a chování seznamu bannerů zůstávají v této fázi beze změny.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Viditelnost profilu se teď nepodařilo načíst.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Viditelnost profilu se teď nepodařilo aktualizovat.",
    "PROFILE_VISIBILITY_SAVED": "Viditelnost vašeho účtu je nyní {visibility}. Příznaky dohledatelnosti zůstávají v této fázi beze změny.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Veřejný účet",
    "PROFILE_VISIBILITY_STORED": "Uložená viditelnost",
    "WF1_MODEL_CONTROL_TITLE": "Řízení modelu WF1",
    "WF1_ENABLE_TRANSLATION": "Povolit překlad / pivot",
    "WF1_TRANSLATION_ACTIVE": "AI překlad je aktivní.",
    "WF1_TRANSLATION_INACTIVE": "WF1 běží dál, ale zdrojový text se zkopíruje a pivot se označí jako neaktivní.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktivní runtime slot",
    "WF1_ALLOW_SAME_LANGUAGE": "Povolit AI pro páry stejného jazyka",
    "WF1_SAME_LANGUAGE_ACTIVE": "Páry stejného jazyka používají běžné směrování WF1.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Páry stejného jazyka obcházejí AI a ukládají stav Žádný aktivní pivot jazyk.",
    "WF1_QWEN_ROUTING": "Směrování párů Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Níže zaškrtnuté jazyky používají Qwen-Max, když je pár buď stejný zaškrtnutý jazyk, zaškrtnutý jazyk s angličtinou, nebo dva zaškrtnuté neanglické jazyky. Jinak zůstává aktivní vybraný primární model.",
    "WF1_OPENROUTER_TEST_SLOT": "Testovací slot OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Testovací slot OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Pouze test kvality",
    "WF1_OPENROUTER_HELPER": "Tento slot lze upravovat pouze pro dočasné testy kvality OpenRouter. Nemění provozní cestu směrování párů Qwen, pokud se tento slot sám nestane aktivním modelem.",
    "WF1_LABEL": "Štítek",
    "WF1_PRODUCT": "Produkt",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Poskytovatel: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Tajný klíč: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Testovací slot OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max přes OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Ceníková cena Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Ceníková cena OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Ceníková cena OpenRouter",
    "LANGUAGE_ENGLISH": "Angličtina",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Čínština (zjednodušená)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Čínština (tradiční)",
    "LANGUAGE_JAPANESE": "Japonština",
    "LANGUAGE_KOREAN": "Korejština",
    "LANGUAGE_PERSIAN": "Perština",
    "LANGUAGE_TURKISH_ISTANBUL": "Turečtina (Istanbul)",
    "LANGUAGE_ARABIC": "Arabština",
    "LANGUAGE_FRENCH": "Francouzština",
    "LANGUAGE_GERMAN": "Němčina",
    "LANGUAGE_SPANISH": "Španělština",
    "LANGUAGE_PORTUGUESE": "Portugalština",
    "LANGUAGE_ITALIAN": "Italština",
    "LANGUAGE_RUSSIAN": "Ruština",
    "LANGUAGE_DUTCH": "Nizozemština",
    "LANGUAGE_VIETNAMESE": "Vietnamština",
    "LANGUAGE_INDONESIAN": "Indonéština",
    "LANGUAGE_THAI": "Thajština",
    "LANGUAGE_MALAY": "Malajština",
    "WF1_PRICING_CUSTOM": "Ceny: vlastní model slotu - zkontrolujte aktuální ceny OpenRouter",
    "WF1_SAVE_OPENROUTER_SLOT": "Uložit slot OpenRouter",
    "WF1_PRICING_LINE": "Vstup {input} - Výstup {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Tajný klíč: {secret}",
    "ZONE_VISIBILITY_TITLE": "Řízení viditelnosti zón",
    "ZONE_ENABLE": "Povolit {zone}",
    "ZONE_ENABLED_NOTE": "{zone} se může zobrazit povoleným rolím po dalším načtení aplikace.",
    "ZONE_DISABLED_NOTE": "{zone} je po dalším načtení aplikace pro uživatele mimo S_Admin považována za nepřítomnou.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin obchází tento seznam rolí a vždy si zachovává přístup.",
    "ZONE_ROLE_LOCKED": "Výběry rolí jsou dočasně uzamčeny, dokud je tato zóna zakázána, a po opětovném povolení zóny se vrátí přesně tak, jak byly uloženy.",
    "ZONE_LCAC_CONTROL": "Řízení LCAC",
    "ZONE_RCAC_CONTROL": "Řízení RCAC",
    "ZONE_LCAC_DESCRIPTION": "Řídí existenci levé vyhrazené zóny a role, které ji mohou vidět.",
    "ZONE_RCAC_DESCRIPTION": "Řídí existenci pravé vyhrazené zóny a role, které ji mohou vidět.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap viditelnosti zón nyní čte z chráněné backendové služby. Změny se použijí při dalším načtení aplikace.",
    "ZONE_VISIBILITY_CACHED": "Backendová služba viditelnosti zón je právě nedostupná, proto jsou aktivní hodnoty z mezipaměti nebo místní výchozí hodnoty.",
    "ZONE_VISIBILITY_DEFAULTS": "Výchozí hodnoty viditelnosti zón jsou aktivní, protože nebylo možné načíst žádný backendový ani uložený stav.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap viditelnosti zón byl uložen. Pro runtime použití je vyžadováno tvrdé obnovení nebo další načtení aplikace.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Chráněná backendová služba nemohla uložit požadovanou změnu viditelnosti zóny.",
    "ROLE_MEMBER": "Člen",
    "ROLE_STAFF": "Personál",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Povolte oznámení, abyste dostávali nové zprávy.",
    "MAIN_LOG_OUT": "Odhlásit se",
    "NOTIFICATION_NEW_MESSAGE": "Nová zpráva",
    "NOTIFICATION_UNREAD_MESSAGE": "Máte nepřečtenou zprávu.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Plné zobrazení",
    "MEDIA_AUDIO_ATTACHMENT": "Zvuková příloha",
    "MEDIA_FILE_FALLBACK": "Soubor",
    "MEDIA_DOWNLOAD_READY": "Příloha je připravena ke stažení",
    "MEDIA_TYPE_UNSUPPORTED": "Typ není podporován pro plné zobrazení",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Předchozí obrázek",
    "MEDIA_NEXT_IMAGE_ARIA": "Další obrázek",
    "MEDIA_OPEN_ORIGINAL": "Otevřít originál",
    "MEDIA_DOWNLOAD": "Stáhnout",
    "MEDIA_CLOSE_ARIA": "Zavřít",
    "MEDIA_PROFILE_PICTURE_ARIA": "Profilový obrázek {name}",
    "MEDIA_PROFILE_ALT": "Profil {name}",
    "MEDIA_UPLOAD_FAILED": "Nahrávání se nezdařilo",
    "MEDIA_BACKEND_TOKEN_ERROR": "Chyba backendového tokenu",
    "MEDIA_UPLOAD_URL_MISSING": "Kritické: v odpovědi backendu chybí URL pro nahrání.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Chybí ověřovací token pro nahrávání do chatu",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Požadavek na token pro nahrávání do chatu selhal",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Neplatná odpověď nahrávání do chatu",
    "MEDIA_GCS_UPLOAD_FAILED": "Nahrávání GCS se nezdařilo",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Chybí název souboru nebo contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Chybí file_path",
    "BLOCK_NOTICE_TITLE": "Oznámení o trvalém blokování",
    "BLOCK_NOTICE_MESSAGE": "Váš účet byl dočasně pozastaven kvůli porušení zásad.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Pokud se domníváte, že je potřeba další řešení, kontaktujte prosím",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "e-mailem.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Neznámý uživatel",
    "GENERAL_GUEST": "Host",
    "ADVISOR_FOR_CLIENT": "Poradce pro {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token a heslo jsou povinné",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Tělo požadavku musí být JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Neplatný nebo expirovaný token pozvánky",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Nastavení hesla selhalo: chybí relace nebo uživatel",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Nastavení hesla selhalo během přihlašování",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Vygenerování admin tokenu selhalo",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Přihlášení selhalo: chybí relace nebo uživatel",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registrace byla úspěšná. Zkontrolujte e-mail pro ověření.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Neznámé selhání registrace",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Neplatné zpracování tokenu",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Přístupový token je vyžadován",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Náhled hashe tokenu vyžaduje nápovědu e-mailu z URL přesměrování",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Pro tento token se nepodařilo vyřešit identitu",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Ke službě selektoru WF1 LLM má přístup pouze User Zero.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Ke službě řízení viditelnosti zón má přístup pouze User Zero.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Ke službě řízení verze frontendu má přístup pouze User Zero.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Pouze User Zero může kontrolovat verzi frontendu jiného uživatele.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Ke službě řízení mazání chatu má přístup pouze User Zero.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Pouze User Zero může trvale smazat uživatelský účet.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Neplatný payload požadavku.",
    "API_ERROR_INTERNAL_SERVER": "Interní chyba serveru",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funkce chybí v backendu (vyžadováno opětovné načtení)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Pro přechody delivered/read je povoleno pouze DB RPC.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Před odesláním další zprávy prosím počkejte.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Zpráva byla úspěšně odeslána.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Kontaktní služba není dostupná.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Odeslání zprávy selhalo.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Jméno je povinné.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-mail je neplatný.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Zpráva je povinná.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload selektoru je vyžadován.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload viditelnosti zón je vyžadován.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload verze frontendu je vyžadován.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload řízení mazání chatu je vyžadován.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID ověřeného uživatele je vyžadováno.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID ověřeného prohlížejícího uživatele je vyžadováno.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID ověřeného jednajícího uživatele je vyžadováno.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id je vyžadováno.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id je vyžadováno.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Seznam owner_user_ids je vyžadován.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email je vyžadováno.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by je vyžadováno.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime vyhledávání je zakázán globální verzí frontendu.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Nemáte oprávnění zrušit tuto čekající pozvánku.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Tuto pozvánku již nelze zrušit, protože uživatel je již registrován.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Čekající pozvánka nebyla nalezena.",
    "INVITE_REPLY_ALREADY_MEMBER": "Gratulujeme, váš přítel ({invitee_email}) je již v této aplikaci zaregistrován a je členem tohoto pracovního prostoru.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Pro {invitee_email} čeká pozvánka, ale e-mail pro opakované odeslání se nepodařilo spustit. Zkontrolujte prosím poštovní logy.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Záznam pozvánky byl vytvořen pro {invitee_email}, ale doručení e-mailu nebylo možné potvrdit. Zkuste to prosím později nebo zkontrolujte poštovní logy.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Vytvoření záznamu pozvánky selhalo. Zkuste to prosím později.",
    "INVITE_REPLY_SYSTEM_ERROR": "Systémová chyba během procesu pozvání: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Chyba konfigurace backendu: chybí přihlašovací údaje Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Chyba konfigurace backendu: neplatná URL Supabase",
    "CHAT_ERROR_ACCESS_DENIED": "Přístup odepřen",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Obsah textových zpráv nemůže být prázdný",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Nepodařilo se určit ID konverzace",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Chybí kontext ověření RPC",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC vrátilo neplatný payload zprávy",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Vložení selhalo, nebyla vrácena žádná data",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations musí být seznam",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Neplatný payload operace",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Nepodporovaný operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id je vyžadováno",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Zpráva nebyla nalezena",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Smazání je povoleno pouze u vaší vlastní zprávy",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Smazat pro všechny již není pro tuto zprávu dostupné",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Smazání pro všechny selhalo",
    "API_ERROR_SERVER_CONFIGURATION": "Chyba konfigurace serveru",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Chybí hlavička tajného klíče webhooku",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Neautorizovaný zdroj webhooku",
    "API_ERROR_BACKEND_CONFIGURATION": "Chyba konfigurace backendu",
    "API_ERROR_MODULE_ATTRIBUTE": "Chyba atributu modulu: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Selhání před smazáním pozvánky při odebírání čekajícího ověřeného uživatele.",
    "CHAT_ERROR_DB": "Chyba DB: {error}",
}
