# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/da.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Hovedside",
    "APP_TITLE": "OTMEGA AI-platform",
    "APP_SUBTITLE": "AI-rådgiver",
    "CHAT_PLACEHOLDER": "Skriv din besked...",
    "CHAT_SEND_BUTTON": "Send",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Rådgiveren kan lave fejl, så dobbelttjek oplysningerne.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Ny chat",
    "ICON_HISTORY": "Historik",
    "ICON_TEMPLATES": "Skabeloner",
    "ICON_SETTINGS": "Indstillinger",
    "ICON_USER_PROFILE": "Brugerprofil",
    "ICON_QUICK_ACTIONS": "Hurtige handlinger",
    "ICON_PINNED": "Fastgjort",
    "ICON_GALLERY": "Galleri",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Installer app",
    "PWA_ANDROID_MSG": "Installer denne app på din enhed for en bedre oplevelse og offlineadgang.",
    "PWA_IOS_MSG": "For at installere denne app på din iPhone/iPad:\\n1. Tryk på Del-knappen nedenfor\\n2. Vælg 'Føj til hjemmeskærm'",
    "PWA_BTN_INSTALL": "Installer",
    "PWA_BTN_LATER": "Måske senere",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Log ind på rådgivernetværket",
    "AUTH_HEADER_SIGNUP": "Opret din samlede konto",
    "AUTH_HEADER_LOGIN_NETWORK": "Log ind på rådgivernetværket",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Opret din samlede konto",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Log ind",
    "AUTH_BUTTON_SIGNUP": "Opret konto",
    "AUTH_BUTTON_GOOGLE": "Fortsæt med Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Glemt adgangskode",
    "AUTH_BUTTON_SEND_RESET_LINK": "Send nulstillingslink",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Har du ikke en konto? Tilmeld dig",
    "AUTH_PROMPT_LOGIN": "Har du allerede en konto? Log ind",
    "AUTH_HELPER_TEXT_SIGNUP": "Du opretter en samlet konto, som du kan bruge til at få adgang til alle rådgivere på denne platform.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Du opretter en samlet konto, som du kan bruge til at få adgang til alle rådgivere på denne platform.",
    "AUTH_HELPER_TEXT_LOGIN": "Brug den samme konto (e-mail/adgangskode eller Google), som du brugte til andre rådgivere i dette netværk.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Brug den samme konto (e-mail/adgangskode eller Google), som du brugte til andre rådgivere i dette netværk.",
    "AUTH_FORGOT_PASSWORD_LINK": "Glemt din adgangskode?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Nulstil din adgangskode",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Indtast din e-mailadresse, så sender vi dig et link til at nulstille din adgangskode.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-mail",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Logger dig ind...",
    "AUTH_STATUS_LOADING_SIGNUP": "Opretter din konto...",
    "AUTH_STATUS_LOADING_RESET": "Sender nulstillingslink...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Login lykkedes! Genindlæser...",
    "AUTH_STATUS_SUCCESS_RESET": "Nulstillingslink sendt. Tjek venligst din e-mail.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Link til nulstilling af adgangskode er sendt. Tjek venligst din e-mail.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Ugyldig e-mail eller adgangskode.",
    "AUTH_ERROR_EMAIL_EXISTS": "Der findes allerede en konto med denne e-mail i rådgivernetværket.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Der findes allerede en konto med denne e-mail. Log venligst ind. Du er i øjeblikket medlem af:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Der findes allerede en konto med denne e-mail i rådgivernetværket. Luk venligst dette vindue, og brug afsnittet 'Login' med samme e-mail og din tidligere adgangskode.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Du er i øjeblikket medlem af:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-mail og adgangskode er påkrævet.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Kontoen blev oprettet, men medlemskabet kunne ikke konfigureres. Kontakt venligst support.",
    "AUTH_ERROR_DEFAULT": "Der opstod en fejl. Prøv venligst igen.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Nyttedata til gæstebannerkontrol er påkrævet.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Kun Bruger Nul kan opdatere gæstebannerkontroller.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Kunne ikke sende nulstillingslink. Prøv venligst igen.",
    "INVITE_REPLY_EMAIL_SENT": "Collabra-invitationsmailen blev sendt til din ven på {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra-invitationsmailen blev sendt igen til din ven på {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Vis adgangskode",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Skjul adgangskode",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Annuller",
    "GENERAL_CLOSE": "Luk",
    "GENERAL_SEND": "Send",
    "GENERAL_SEARCH": "Søg",
    "GENERAL_RESET": "Nulstil",
    "GENERAL_ENABLE": "Aktivér",
    "GENERAL_LOADING": "Indlæser...",
    "GENERAL_DELETE": "Slet",
    "GENERAL_DELETING": "Sletter...",
    "GENERAL_SAVE_PASSWORD": "Gem adgangskode",
    "AUTH_REMEMBER_EMAIL_LABEL": "Husk e-mail",
    "GENERAL_SAVING": "Gemmer...",
    "GENERAL_SENDING": "Sender...",
    "GENERAL_REMOVING": "Fjerner...",
    "GENERAL_CONFIRM_REMOVAL": "Bekræft fjernelse",
    "GENERAL_EMPTY": "Tom",
    "GENERAL_UNAVAILABLE": "Ikke tilgængelig",
    "GENERAL_ENABLED": "Aktiveret",
    "GENERAL_DISABLED": "Deaktiveret",
    "GENERAL_GRANTED": "Givet",
    "GENERAL_DENIED": "Afvist",
    "GENERAL_DEFAULT": "Standard",
    "GENERAL_UNSUPPORTED": "Ikke understøttet",
    "GENERAL_PUBLIC": "Offentlig",
    "GENERAL_PRIVATE": "Privat",
    "GENERAL_USERNAME": "Brugernavn",
    "GENERAL_EMAIL": "E-mail",
    "GENERAL_YOU": "Dig",
    "GENERAL_USER": "Bruger",
    "GENERAL_UNKNOWN": "Ukendt",
    "GENERAL_VISITOR": "Besøgende",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Ukendt banner",
    "GENERAL_ADVISOR_BANNER": "Rådgiverbanner",
    "GENERAL_NOT_AVAILABLE": "Ikke tilgængelig",
    "GENERAL_NOT_SELECTED": "Ikke valgt",
    "GENERAL_NO_EMAIL_FOUND": "Ingen e-mail fundet",
    "GENERAL_USER_ZERO_ONLY": "Kun User Zero",
    "GENERAL_CONNECTION_STATE": "Forbindelsestilstand",
    "GENERAL_DISPLAY_ONLY": "Kun visning",
    "GENERAL_TEXTAREA": "Tekstområde",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Hurtige handlinger (RCAC)",
    "HEADER_CHANGE_STATUS": "Skift status",
    "HEADER_OT_COIN_BALANCE": "OT Coin-saldo",
    "HEADER_ALT_USER": "Bruger",
    "STATUS_BUSY": "Optaget",
    "STATUS_AWAY": "Væk",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Usynlig",
    "NETWORK_CHECKING_CONNECTION": "Kontrollerer forbindelse...",
    "NETWORK_ONLINE_LATENCY": "Online (latenstid: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Netværk: Godt (tryk for at pinge)",
    "CHAT_TARGET_ALT": "Chatmål",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Søg...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Åbn profilbilledet for {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Beskedfelt",
    "CHAT_TOGGLE_VIEW_ARIA": "Skift visning",
    "CHAT_ADD_USER_ARIA": "Tilføj bruger",
    "CHAT_ATTACH_ARIA": "Vedhæft",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Send",
    "CHAT_SEARCH_ARIA": "Søg",
    "CHAT_OPEN_SEARCH_ARIA": "Åbn søgning",
    "CHAT_CLOSE_SEARCH_ARIA": "Luk søgning",
    "CHAT_ATTACHMENT_ALT": "Vedhæftet fil",
    "CHAT_PREVIEW_ALT": "Forhåndsvisning",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Fjern vedhæftet fil",
    "CHAT_REPLYING_TO": "Svarer på",
    "CHAT_CANCEL_REPLY_ARIA": "Annuller svar",
    "CHAT_UPLOADING": "Uploader...",
    "CHAT_LOADING_CHATS": "Indlæser chats...",
    "CHAT_SEND_FAILED": "Afsendelse mislykkedes",
    "CHAT_SEND_FAILED_RETRY": "Afsendelse mislykkedes. Prøv igen.",
    "CHAT_RETRY": "Prøv igen",
    "CHAT_EDITED": "redigeret",
    "CHAT_TYPING": "Skriver",
    "CHAT_LOADING": "Indlæser",
    "CHAT_PENDING_INVITATION": "Afventende invitation",
    "CHAT_PENDING_INVITATION_MIN": "{count} min Afventende invitation",
    "CHAT_PENDING_INVITATION_HR": "{count} t Afventende invitation",
    "CHAT_PENDING_INVITATION_DAY": "{count} dag Afventende invitation",
    "CHAT_WAITING_FOR_YOU": "{label} - Venter på dig",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Afventer accept",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Adgang til mikrofon nægtet.",
    "CHAT_UPLOAD_FAILED": "Upload mislykkedes: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Upload kræver en internetforbindelse. Prøv igen, når du er online.",
    "OFFLINE_SHOWING_SAVED_DATA": "",
    "OFFLINE_DATA_MAY_BE_OUTDATED": "",
    "OFFLINE_ACTION_REQUIRES_CONNECTION": "",
    "OFFLINE_MESSAGE_WAITING_CONNECTION": "",
    "OFFLINE_PENDING_MESSAGES_TOOLTIP": "",
    "APP_BACK_EXIT_HINT": "",
    "CHAT_ERROR_AUTH": "Godkendelsesfejl",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Manglende filnavn eller content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Manglende conversation_id eller target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Manglende conversation_id for upload uden avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Ugyldig avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase serviceklient er ikke tilgængelig",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Avatar-læsekvittering er kun gyldig i rådgiverchatkontekst",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatar-flowbesked blev ikke fundet eller er ikke berettiget til læsekvittering",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Kunne ikke markere avatarbesked som læst",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 vedhæftet fil",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} vedhæftede filer",
    "CHAT_VOICE_NOTE": "Talebesked",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat er ikke tilgængelig. Denne bruger har blokeret dig.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat er ikke tilgængelig. Du har blokeret denne bruger.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Kontoadgang er blokeret af politik.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat er ikke tilgængelig. Denne konto er permanent blokeret af User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat er ikke tilgængelig. Gensidig blokering er aktiv.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat er ikke tilgængelig på grund af blokeringspolitik.",
    "MESSAGE_PREVIEW_PHOTO": "Foto",
    "MESSAGE_PREVIEW_VOICE": "Talebesked",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Fil",
    "MESSAGE_PREVIEW_MESSAGE": "Besked",
    "MESSAGE_PREVIEW_SYSTEM": "Systembesked",
    "MESSAGE_PREVIEW_NEW": "Ny besked",
    "MESSAGE_UNKNOWN_FILE": "Ukendt fil",
    "MESSAGE_AUDIO_ATTACHMENT": "Lydvedhæftning",
    "MESSAGE_FILE_ATTACHMENT": "Vedhæftet fil",
    "BANNER_INVITED_BY": "inviteret af {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Søgeresultater",
    "SEARCH_QUERY_LABEL": "Forespørgsel:",
    "SEARCH_LOADING_VISIBILITY": "Indlæser søgesynlighed...",
    "SEARCH_NO_RESULTS": "Ingen resultater fundet i det aktuelle søgeområde.",
    "SHARE_WITH_COLLABRA": "Del med Collabra",
    "SHARE_SEND_TO": "Send til",
    "SHARE_SELECT_ONE_BANNER": "Vælg ét banner",
    "SHARE_BANNER_LIST_ARIA": "Bannerliste",
    "SHARE_NO_MATCHING_BANNER": "Intet matchende banner",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Tilføj en kommentar...",
    "SHARE_RECENT_CHATS": "Seneste chats",
    "SHARE_LEFT_LIST": "Venstre liste",
    "SHARE_RIGHT_LIST": "Højre liste",
    "SHARE_UNTITLED_BANNER": "Banner uden titel",
    "SHARE_SHARED_CONTENT": "Delt indhold",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Det delte indhold kunne ikke åbnes.",
    "SHARE_OPEN_BANNER_FAILED": "Kunne ikke åbne det valgte banner.",
    "SHARE_ONE_PHOTO_SELECTED": "1 foto valgt",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} fotos valgt",
    "SHARE_ONE_FILE_SELECTED": "1 fil valgt",
    "SHARE_MANY_FILES_SELECTED": "{count} filer valgt",
    "FORWARD_MESSAGE_TITLE": "Videresend besked",
    "FORWARD_SELECT_RECIPIENTS": "Vælg modtagere",
    "FORWARD_NO_OTHER_BANNER": "Intet andet banner tilgængeligt.",
    "FORWARD_SEND_TO_COUNT": "Send til {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Vælg mindst ét banner.",
    "FORWARD_FAILED_DEFAULT": "Videresendelse mislykkedes. Prøv venligst igen.",
    "FORWARD_PARTIAL_SENT": "{count} sendt. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Kildebesked blev ikke fundet til videresendelse",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Denne besked har endnu intet indhold, der kan videresendes",
    "FORWARD_DESTINATION_MISSING": "Videresendelsesdestination mangler",
    "FORWARD_MESSAGE_PREVIEW": "Videresendt besked",
    "MENU_PASTE": "Indsæt",
    "MENU_COPY": "Kopiér",
    "MENU_REPLY": "Svar",
    "MENU_FORWARD": "Videresend",
    "MENU_REMOVE_INVITATION": "Fjern invitation",
    "MENU_REMOVE_FROM_LIST": "Fjern fra liste",
    "MENU_GOODBYE_GUEST": "Farvel gæst",
    "MENU_ADD_TO_LIST": "Føj til liste",
    "MENU_REJECT_INVITATION": "Afvis invitation",
    "MENU_FRONTEND_VERSION": "Frontend-version",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Bannerinfo: {title}",
    "MENU_MESSAGE_BUBBLE": "Beskedboble",
    "MENU_CHAT_CANVAS_HEADER": "Chatcanvas - {zone}",
    "MENU_CANVAS_INFO": "Canvasinfo",
    "MENU_CHAT_CANVAS_SUBLABEL": "Samtaleområde / aktuel chatoverflade",
    "MENU_INPUT_AREA_HEADER": "Inputområde - {zone}",
    "MENU_INPUT_AREA_INFO": "Inputområdeinfo: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Nederste skrive- og handlingsværktøjsflade",
    "MENU_HEADER": "Header - {zone}",
    "MENU_HEADER_INFO": "Headerinfo: {title}",
    "MENU_HEADER_DESCRIPTION": "Topnavigation og sidekontroller",
    "MENU_ZONE_HEADER": "Zone - {zone}",
    "MENU_ZONE_SPACE_INFO": "Zoneområdeinfo",
    "MENU_EMPTY_LIST_SURFACE": "Tom/listemæssig flade",
    "MENU_BLOCK": "Bloker",
    "MENU_UNBLOCK": "Fjern blokering",
    "MENU_HIDE_IN_SEARCH": "Skjul i søgning",
    "MENU_UNHIDE_IN_SEARCH": "Vis i søgning igen",
    "MENU_VISIBLE_IN_SEARCH": "Synlig i søgning",
    "MENU_HIDDEN_IN_SEARCH": "Skjult i søgning",
    "MENU_VISIBLE_IN_USER_LIST": "Synlig i brugerliste",
    "MENU_HIDDEN_IN_USER_LIST": "Skjult i brugerliste",
    "MENU_NOT_BLOCKED": "Ikke blokeret",
    "MENU_BLOCKED": "Blokeret",
    "MENU_FRONTEND_VERSION_LOADING": "Indlæser...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Indlæser værdi pr. banner fra backend. Ingen mulighed markeres som aktiv, før databaseresponsen ankommer.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend-værdien kunne ikke indlæses. Ingen betroet aktiv mulighed vises.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Eksplicit databaseværdi pr. banner er {overrideVersion}. Global standard er {globalDefaultVersion}. Målbrugeren skal genindlæse fuldt eller genåbne appen, for at opstartsbootstrap kan anvende den.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Ingen eksplicit databaseværdi pr. banner er gemt. FeV2.0.0 er aktiv som standard. Global standard er {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Eksplicit databaseværdi pr. banner bliver aktiv, efter målappen er fuldt genindlæst",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Ingen eksplicit værdi pr. banner er gemt; dette er den individuelle FeV2.0.0-standardtilstand",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Denne mulighed er også lig med den aktuelle globale standard",
    "MENU_DELETE_PERMANENT_CONFIRM": "Slet {target} permanent fra databasen? Dette fjerner kontoen, chathistorik, afhængigheder og tvinger en helt ny invitationsvej for fremtidig genindtræden.",
    "MENU_DELETE_PERMANENTLY": "Slet permanent",
    "MENU_REFRESH_PAGE": "Opdater side",
    "MENU_LOG_OFF": "Log af",
    "MENU_HARD_RELOAD": "Hård genindlæsning",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-mail (administratorbruger)",
    "AUTH_PASSWORD_PLACEHOLDER": "Adgangskode",
    "AUTH_CONNECTING": "Forbinder...",
    "AUTH_SIGNING_OUT": "Logger ud...",
    "AUTH_BACK_TO_LOGIN": "Tilbage til login",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Ugyldigt serversvar: Ingen token fundet.",
    "AUTH_LOGIN_FAILED": "Login mislykkedes",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Adgangskoderne matcher ikke.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Adgangskoderne matcher ikke!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Adgangskoderne skal matche nøjagtigt.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Ny adgangskode",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Bekræft adgangskode",
    "AUTH_CHANGE_PASSWORD": "Skift adgangskode",
    "AUTH_SAVING_PASSWORD": "Gemmer...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Adgangskoden blev opdateret.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Kan ikke ændre adgangskode lige nu.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Du skal være logget ind for at ændre din adgangskode.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Skift synlighed for ny adgangskode",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Skift synlighed for bekræftelse af adgangskode",
    "REGISTER_TITLE": "Fuldfør registrering",
    "REGISTER_SUBTITLE": "Angiv venligst din adgangskode manuelt.",
    "REGISTER_CREATING_ACCOUNT": "Opretter konto...",
    "REGISTER_FINISH_SETUP": "Afslut opsætning",
    "REGISTER_FAILED_SET_PASSWORD": "Kunne ikke angive adgangskode",
    "INVITE_EMAIL_INSTRUCTION": "Indtast venligst inviteredes e-mail (format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Inviter",
    "INVITE_EMAIL_REQUIRED": "Indtast venligst inviteredes e-mail.",
    "INVITE_EMAIL_INVALID": "Ugyldigt e-mailformat. Brug venligst: user@example.com",
    "PENDING_INVITATION_TITLE": "Afventende invitation",
    "PENDING_INVITATION_REMOVE_QUESTION": "Fjern denne afventende invitation fra databasen?",
    "PENDING_INVITATION_KEEP": "Behold invitation",
    "PENDING_INVITATION_REMOVAL_FAILED": "Fjernelse mislykkedes.",
    "REMOVE_FROM_LIST_TITLE": "Fjern fra liste",
    "REMOVE_FROM_LIST_WARNING": "Fjern denne bruger fra begge lister nu? Chatadgang afbrydes straks. Den eneste vej tilbage er en ny invitation.",
    "REMOVE_FROM_LIST_KEEP": "Behold bruger på listen",
    "REMOVE_FROM_LIST_FAILED": "Fjernelse fra liste mislykkedes.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Indstilling og livestatus",
    "PERMISSION_DIALOG_ARIA": "Indstilling og livestatus",
    "PERMISSION_TRIGGER_ARIA": "Udløser for indstillingspopup",
    "PERMISSION_CLOSE_ARIA": "Luk tilladelsespopup",
    "PERMISSION_LIVE_STATUS": "Livestatus",
    "PERMISSION_SYSTEM_PERMISSION": "Systemtilladelse",
    "PERMISSION_APP_PUSH": "App-push",
    "PERMISSION_LOCATION_PERMISSION": "Placeringstilladelse",
    "PERMISSION_APP_LOCATION": "App-placering",
    "PERMISSION_CONTROLS": "Tilladelseskontroller",
    "PERMISSION_PUSH_NOTIFICATIONS": "Pushnotifikationer",
    "PERMISSION_LOCATION_ACCESS": "Adgang til placering",
    "PERMISSION_IN_APP_SETTINGS": "Indstillinger i appen",
    "PERMISSION_ALERT_SOUND": "Advarselslyd",
    "PERMISSION_APP_BADGE": "App-badge",
    "PERMISSION_PASSWORD_SETTINGS": "Adgangskodeindstillinger",
    "PERMISSION_NAVIGATION_STATUS": "Navigationsstatus",
    "PERMISSION_SELECTED_ZONE": "Valgt zone",
    "PERMISSION_STAGED_CHAT_BANNER": "Forberedt chatbanner",
    "PERMISSION_CANVAS_CONTENT": "Canvasindhold",
    "PERMISSION_YOUR_DEVICES": "Dine enheder ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Opdater enhedsliste",
    "PERMISSION_REFRESH_LIST": "Opdater liste",
    "PERMISSION_NO_REGISTERED_DEVICES": "Ingen registrerede enheder fundet.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Tilpas størrelse på indstillingspopup",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Skift pushnotifikationer",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Skift placeringsadgang",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Skift advarselslyd",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Skift app-badge",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Skift profilsynlighed",
    "PERMISSION_OFF_IN_V1": "Fra i v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Bannerliste",
    "PERMISSION_PUSH_DISABLED_V1": "Pushnotifikationer er deaktiveret for v1 Google Play-udgivelsen.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Pushnotifikationer er slået TIL for denne enhed.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Systemnotifikationer er blokeret. Tryk for at åbne hjælp til indstillinger.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Slå TIL for at forbedre leveringssikkerheden.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "For at deaktivere systemnotifikationer skal du åbne browserens/webstedets notifikationsindstillinger og sætte dette websted til Bloker.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "For at ændre systemnotifikationstilladelse skal du åbne browserens/webstedets notifikationsindstillinger og sætte dette websted til Tillad.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Placeringsadgang er slået TIL for afstandsbaseret LCAC-sortering og kortpositionering.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Placerings-API understøttes ikke i dette miljø.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Placeringsadgang er blokeret. Tryk for at åbne hjælp til indstillinger.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Slå TIL for at tillade præcis afstandsbaseret LCAC-sortering og kortpositionering i appen.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Placeringsadgang understøttes ikke i dette miljø.",
    "PERMISSION_LOCATION_DISABLE_HELP": "For at deaktivere placeringsadgang skal du åbne browserens/webstedets placeringsindstillinger og sætte dette websted til Bloker.",
    "PERMISSION_LOCATION_ALLOW_HELP": "For at aktivere placeringsadgang til afstandssortering og kortpositionering i appen skal du åbne browserens/webstedets placeringsindstillinger og sætte dette websted til Tillad.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Kan ikke indlæse registrerede enheder lige nu.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Indlæser UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Indlæser Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Indlæser backend...",
    "RUNTIME_LOADING": "Indlæser...",
    "RUNTIME_LOADING_FROM_DATABASE": "Indlæser fra database...",
    "RUNTIME_BACKEND_CONNECTED": "Backend forbundet",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Cachet fallback aktiv",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Standardfallback aktiv",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallbackstandarder aktive",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Gemmer gennem backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Gemt i backendtjeneste",
    "RUNTIME_SAVE_FAILED": "Gem mislykkedes",
    "RUNTIME_LOAD_FAILED": "Indlæsning mislykkedes",
    "RUNTIME_CONNECTED": "Forbundet",
    "RUNTIME_LOGIN_REQUIRED": "Login påkrævet",
    "RUNTIME_SAVED": "Gemt",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI klar - runtime afventer",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Den beskyttede backend-selektortjeneste afviste eller kunne ikke gemme den ønskede modelindstilling.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Den beskyttede backend-selektortjeneste afviste eller kunne ikke gemme den ønskede WF1-ruteændring.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selektoren læser nu aktiv konfiguration, Qwen-routing og tilladte muligheder fra den beskyttede backendtjeneste.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend-selektortjenesten er ikke tilgængelig lige nu, så den senest cachede selektortilstand bruges.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Selektorens standardværdier er aktive, fordi ingen backend- eller cachet selektortilstand kunne indlæses.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Den beskyttede backend-selektortjeneste opdaterede den aktive WF1-routingkonfiguration og opdaterede runtime-domænecachen.",
    "FRONTEND_VERSION_TITLE": "Frontend-version",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Denne selektor styrer den aktive frontend-version for alle brugere. FeV2.0.0 er aktiv.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Denne selektor læser den aktive frontend-version fra config_domain_registry. Runtime opløses til FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend-konfigurationen for frontend-version kunne ikke indlæses, så den kodede FeV2.0.0-standard er aktiv, indtil opstartsbootstrap kan læse den beskyttede tjeneste igen.",
    "FRONTEND_VERSION_HELPER_SAVED": "Den aktive frontend-version blev gemt i config_domain_registry. En fuld opdatering eller næste appindlæsning anvender runtime-værdien.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend-kontroltjenesten for frontend-version kunne ikke gemme den ønskede globale version.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktiv frontend-version.",
    "CHAT_DELETE_WINDOW_TITLE": "Vindue til chatsletning",
    "CHAT_DELETE_HELPER": "Denne værdi styrer tilgængelighedsvinduet for Slet for alle i sekunder. Backend-vagten ændres straks efter gemning. Boblesynligheden ændres efter en fuld opdatering eller næste appindlæsning.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend-kontroltjenesten for chatsletning kunne ikke indlæses, så den kodede standard forbliver aktiv, indtil opstartsbootstrap kan læse den beskyttede tjeneste igen.",
    "CHAT_DELETE_HELPER_SAVED": "Tilgængelighedsvinduet for Slet for alle blev gemt i config_domain_registry. Backend-vagten ændres straks. Boblesynligheden ændres efter en fuld opdatering eller næste appindlæsning.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend-kontroltjenesten for chatsletning kunne ikke gemme den ønskede vinduesværdi.",
    "CHAT_DELETE_WINDOW_LABEL": "Vindue for Slet for alle",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} sek.",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Gem værdien i hele sekunder. Den aktuelle produktionsværdi er 86400 sekunder = 1 dag.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Vinduessekunder",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Indtast et helt tal større end eller lig med 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Gem slettevindue",
    "GUEST_BANNER_CONTROL_TITLE": "Gæstebanner",
    "GUEST_BANNER_CONTROL_LABEL": "Gæste-QR-chat",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Vis gæstebanner for alle brugere",
    "GUEST_BANNER_CONTROL_HELPER": "Styrer det faste gæstebanner og levetiden for afventende QR-token.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Lokal fallback er aktiv for gæstebannerkontroller.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Gæstebannerkontroller gemt.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Gæstebannerkontroller kunne ikke gemmes.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} gæstesessioner er tilbagekaldt.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "Afventende QR TTL (minutter)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "Nuværende afventende QR TTL: {count} minutter.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Indtast et positivt helt antal minutter.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Gem gæstebanner",
    "GUEST_QR_LOADING": "Forbereder gæste-QR...",
    "GUEST_QR_READY": "Scan for at åbne den midlertidige gæstechat.",
    "GUEST_QR_ALT": "QR-kode til gæstechat",
    "GUEST_QR_LOAD_FAILED": "Gæste-QR kunne ikke forberedes.",
    "GUEST_SESSION_ACTIVE": "Gæst er tilsluttet.",
    "GUEST_PUBLIC_TITLE": "Gæstechat",
    "GUEST_PUBLIC_CONNECTING": "Opretter forbindelse...",
    "GUEST_PUBLIC_CONNECTED": "Forbundet",
    "GUEST_PUBLIC_UNAVAILABLE": "Dette gæstelink er ikke tilgængeligt.",
    "GUEST_PUBLIC_SEND_FAILED": "Beskeden kunne ikke sendes.",
    "UI_TEXTS_RUNTIME_TITLE": "UI-sprog-runtime",
    "UI_TEXTS_RUNTIME_BACKEND": "UI-sprog-runtime læser fra den beskyttede backend-tjeneste. Ændringer træder i kraft ved næste fulde app-indlæsning.",
    "UI_TEXTS_RUNTIME_CACHED": "Backend UI-sprog-runtime-tjenesten er ikke tilgængelig lige nu, så cachelagrede eller lokale standardindstillinger er aktive.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "UI-sprog-runtime-standardindstillinger er aktive, fordi ingen backend- eller cachelagret tilstand kunne indlæses.",
    "UI_TEXTS_RUNTIME_SAVED": "Kontrol af UI-sprog-runtime blev gemt. En fuld genindlæsning eller næste app-indlæsning er påkrævet, for at brugerne kan modtage den nye sprog-gate.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Den beskyttede backend-tjeneste kunne ikke gemme den anmodede ændring af UI-sprog-runtime.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Anvendelse af enhedens sprog",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Aktivér runtime UI-sprog",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Brugere kan modtage UI-tekst-payloads for deres gemte sprog eller enhedens sprog.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Alle brugere tvinges til engelsk UI-tekst, og enhedens sprog ignoreres.",
    "PROFILE_VISIBILITY_TITLE": "Profilsynlighed",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Du skal være logget ind for at administrere kontosynlighed.",
    "PROFILE_VISIBILITY_HELPER": "Denne kontakt opdaterer kun din kontos synlighedstilstand. Synlighed i søgning og bannerlisteadfærd forbliver uændret i denne fase.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Profilsynlighed kunne ikke indlæses lige nu.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Profilsynlighed kunne ikke opdateres lige nu.",
    "PROFILE_VISIBILITY_SAVED": "Din kontosynlighed er nu {visibility}. Synlighedsflag forbliver uændrede i denne fase.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Offentlig konto",
    "PROFILE_VISIBILITY_STORED": "Gemt synlighed",
    "WF1_MODEL_CONTROL_TITLE": "WF1-modelkontrol",
    "WF1_ENABLE_TRANSLATION": "Aktivér oversættelse / pivot",
    "WF1_TRANSLATION_ACTIVE": "AI-oversættelse er aktiv.",
    "WF1_TRANSLATION_INACTIVE": "WF1 fortsætter med at køre, men kildeteksten kopieres, og pivot markeres som inaktiv.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktiv runtime-slot",
    "WF1_ALLOW_SAME_LANGUAGE": "Tillad AI for sprogpar med samme sprog",
    "WF1_SAME_LANGUAGE_ACTIVE": "Sprogpar med samme sprog følger normal WF1-routing.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Sprogpar med samme sprog omgår AI og gemmer Ingen aktivt pivotsprog.",
    "WF1_QWEN_ROUTING": "Qwen-parrouting",
    "WF1_QWEN_ROUTING_HELPER": "Sprog markeret nedenfor bruger Qwen-Max, når parret enten er det samme markerede sprog, et markeret sprog med engelsk eller to markerede ikke-engelske sprog. Ellers forbliver den valgte primære model aktiv.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter-testslot",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter-testslot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Kun kvalitetstest",
    "WF1_OPENROUTER_HELPER": "Denne slot kan kun redigeres til midlertidige OpenRouter-kvalitetstests. Den ændrer ikke den operationelle Qwen-parroutingsti, medmindre denne slot selv bliver den aktive model.",
    "WF1_LABEL": "Etiket",
    "WF1_PRODUCT": "Produkt",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Udbyder: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Hemmelighed: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter-testslot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max via OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google listepris",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI listepris",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter listepris",
    "LANGUAGE_ENGLISH": "Engelsk",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Kinesisk (forenklet)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Kinesisk (traditionel)",
    "LANGUAGE_JAPANESE": "Japansk",
    "LANGUAGE_KOREAN": "Koreansk",
    "LANGUAGE_PERSIAN": "Persisk",
    "LANGUAGE_TURKISH_ISTANBUL": "Tyrkisk (Istanbul)",
    "LANGUAGE_ARABIC": "Arabisk",
    "LANGUAGE_FRENCH": "Fransk",
    "LANGUAGE_GERMAN": "Tysk",
    "LANGUAGE_SPANISH": "Spansk",
    "LANGUAGE_PORTUGUESE": "Portugisisk",
    "LANGUAGE_ITALIAN": "Italiensk",
    "LANGUAGE_RUSSIAN": "Russisk",
    "LANGUAGE_DUTCH": "Nederlandsk",
    "LANGUAGE_VIETNAMESE": "Vietnamesisk",
    "LANGUAGE_INDONESIAN": "Indonesisk",
    "LANGUAGE_THAI": "Thai",
    "LANGUAGE_MALAY": "Malay",
    "WF1_PRICING_CUSTOM": "Prissætning: brugerdefineret slotmodel - tjek aktuel OpenRouter-prissætning",
    "WF1_SAVE_OPENROUTER_SLOT": "Gem OpenRouter-slot",
    "WF1_PRICING_LINE": "Input {input} - Output {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Hemmelighed: {secret}",
    "ZONE_VISIBILITY_TITLE": "Kontrol af zonesynlighed",
    "ZONE_ENABLE": "Aktivér {zone}",
    "ZONE_ENABLED_NOTE": "{zone} kan vises for tilladte roller efter næste appindlæsning.",
    "ZONE_DISABLED_NOTE": "{zone} behandles som fraværende for ikke-S_Admin-brugere efter næste appindlæsning.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin omgår denne rollelisten og beholder altid adgang.",
    "ZONE_ROLE_LOCKED": "Rollevalg er midlertidigt låst, mens denne zone er deaktiveret, og vender tilbage præcis som gemt, når zonen aktiveres igen.",
    "ZONE_LCAC_CONTROL": "LCAC-kontrol",
    "ZONE_RCAC_CONTROL": "RCAC-kontrol",
    "ZONE_LCAC_DESCRIPTION": "Styrer eksistensen af den venstre reserverede zone og de roller, der kan se den.",
    "ZONE_RCAC_DESCRIPTION": "Styrer eksistensen af den højre reserverede zone og de roller, der kan se den.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap for zonesynlighed læser nu fra den beskyttede backendtjeneste. Ændringer anvendes ved næste appindlæsning.",
    "ZONE_VISIBILITY_CACHED": "Backendtjenesten for zonesynlighed er ikke tilgængelig lige nu, så cachede eller lokale standarder er aktive.",
    "ZONE_VISIBILITY_DEFAULTS": "Standarder for zonesynlighed er aktive, fordi ingen backend- eller cachet tilstand kunne indlæses.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap for zonesynlighed blev gemt. Hård genindlæsning eller næste appindlæsning er påkrævet for runtime-anvendelse.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Den beskyttede backendtjeneste kunne ikke gemme den ønskede ændring af zonesynlighed.",
    "ROLE_MEMBER": "Medlem",
    "ROLE_STAFF": "Personale",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Aktivér notifikationer for at modtage nye beskeder.",
    "MAIN_LOG_OUT": "Log ud",
    "NOTIFICATION_NEW_MESSAGE": "Ny besked",
    "NOTIFICATION_UNREAD_MESSAGE": "Du har en ulæst besked.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Fuld visning",
    "MEDIA_AUDIO_ATTACHMENT": "Lydvedhæftning",
    "MEDIA_FILE_FALLBACK": "Fil",
    "MEDIA_DOWNLOAD_READY": "Vedhæftet fil klar til download",
    "MEDIA_TYPE_UNSUPPORTED": "Type understøttes ikke i fuld visning",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Forrige billede",
    "MEDIA_NEXT_IMAGE_ARIA": "Næste billede",
    "MEDIA_OPEN_ORIGINAL": "Åbn original",
    "MEDIA_DOWNLOAD": "Download",
    "MEDIA_CLOSE_ARIA": "Luk",
    "MEDIA_PROFILE_PICTURE_ARIA": "Profilbillede for {name}",
    "MEDIA_PROFILE_ALT": "Profil for {name}",
    "MEDIA_UPLOAD_FAILED": "Upload mislykkedes",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend-tokenfejl",
    "MEDIA_UPLOAD_URL_MISSING": "Kritisk: upload-URL mangler i backend-svaret.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Manglende godkendelsestoken til chatupload",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Anmodning om chatuploadtoken mislykkedes",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Ugyldigt chatuploadsvar",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS-upload mislykkedes",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Manglende filnavn eller contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Manglende file_path",
    "BLOCK_NOTICE_TITLE": "Permanent blokeringsmeddelelse",
    "BLOCK_NOTICE_MESSAGE": "Din konto er midlertidigt suspenderet på grund af politikovertrædelsen.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Hvis du mener, dette kræver opfølgning, bedes du kontakte",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "via e-mail.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Ukendt bruger",
    "GENERAL_GUEST": "Gæst",
    "ADVISOR_FOR_CLIENT": "Rådgiver for {client_display_name}",
    "GUEST_FOR_CLIENT": "Gæst for {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token og adgangskode er påkrævet",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Anmodningens body skal være JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Ugyldig eller udløbet invitationstoken",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Angivelse af adgangskode mislykkedes: manglende session eller bruger",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Angivelse af adgangskode mislykkedes under login",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Generering af admintoken mislykkedes",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Login mislykkedes: manglende session eller bruger",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registrering lykkedes. Tjek venligst e-mail for bekræftelse.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Tilmelding mislykkedes ukendt",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Ugyldig tokenbehandling",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Adgangstoken er påkrævet",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Token-hashforhåndsvisning kræver e-mailhint fra redirect-URL",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Kan ikke løse identitet for denne token",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Kun User Zero kan få adgang til WF1 LLM-selektortjenesten.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Kun User Zero kan få adgang til kontroltjenesten for zonesynlighed.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Kun User Zero kan få adgang til kontroltjenesten for frontend-version.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Kun User Zero kan inspicere en anden brugers frontend-version.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Kun User Zero kan få adgang til kontroltjenesten for chatsletning.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Kun User Zero kan tilgå kontroltjenesten for UI-sprog-runtime.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Kun User Zero kan permanent slette en brugerkonto.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Ugyldig anmodningspayload.",
    "API_ERROR_INTERNAL_SERVER": "Intern serverfejl",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funktion mangler i backend (genindlæsning påkrævet)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Kun DB RPC er tilladt for delivered/read-overgange.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Vent venligst, før du sender en ny besked.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Besked sendt.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Kontakttjenesten er ikke tilgængelig.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Afsendelse af besked mislykkedes.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Navn er påkrævet.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-mail er ugyldig.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Besked er påkrævet.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Selektorpayload er påkrævet.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload for zonesynlighed er påkrævet.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload for frontend-version er påkrævet.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload for chatsletningskontrol er påkrævet.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Payload til kontrol af UI-sprog-runtime er påkrævet.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Godkendt bruger-id er påkrævet.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Godkendt viewer-bruger-id er påkrævet.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Godkendt aktør-bruger-id er påkrævet.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id er påkrævet.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id er påkrævet.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids-liste er påkrævet.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email er påkrævet.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by er påkrævet.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Søgeruntime er deaktiveret af global frontend-version.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Du har ikke tilladelse til at annullere denne afventende invitation.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Denne invitation kan ikke længere annulleres, fordi brugeren allerede er registreret.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Afventende invitation blev ikke fundet.",
    "INVITE_REPLY_ALREADY_MEMBER": "Tillykke, din ven ({invitee_email}) er allerede registreret i denne app og er medlem af dette arbejdsområde.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "En invitation afventer for {invitee_email}, men retry-e-mailen kunne ikke udløses. Tjek venligst mail-loggene.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Invitationsposten blev oprettet for {invitee_email}, men e-maillevering kunne ikke bekræftes. Prøv igen senere eller tjek mail-loggene.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Kunne ikke oprette invitationspost. Prøv venligst igen senere.",
    "INVITE_REPLY_SYSTEM_ERROR": "Systemfejl under invitationsprocessen: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend-konfigurationsfejl: manglende Supabase-legitimationsoplysninger",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend-konfigurationsfejl: ugyldig Supabase-URL",
    "CHAT_ERROR_ACCESS_DENIED": "Adgang nægtet",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Indhold må ikke være tomt for tekstbeskeder",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Kunne ikke bestemme samtale-id",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC-godkendelseskontekst mangler",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC returnerede ugyldig beskedpayload",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Indsættelse mislykkedes, ingen data returneret",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations skal være en liste",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Ugyldig operationspayload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type understøttes ikke",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id er påkrævet",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Besked blev ikke fundet",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Sletning er kun tilladt for din egen besked",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Slet for alle er ikke længere tilgængelig for denne besked",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Slet for alle mislykkedes",
    "API_ERROR_SERVER_CONFIGURATION": "Serverkonfigurationsfejl",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Manglende webhook secret header",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Uautoriseret webhookkilde",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend-konfigurationsfejl",
    "API_ERROR_MODULE_ATTRIBUTE": "Modulattributfejl: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Mislykkedes før invitationssletning under fjernelse af ventende auth-bruger.",
    "CHAT_ERROR_DB": "DB-fejl: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "PERMISSION_MIC_PERMISSION": "",
    "PERMISSION_MIC_ACCESS": "",
    "PERMISSION_TOGGLE_MIC_ARIA": "",
    "PERMISSION_MIC_ON_TOOLTIP": "",
    "PERMISSION_MIC_ENABLE_TOOLTIP": "",
    "PERMISSION_MIC_BLOCKED_TOOLTIP": "",
    "PERMISSION_MIC_DISABLE_HELP": "",
    "PERMISSION_MIC_BLOCKED_HELP": "",
    "LIVE_CONV_MIC_PROMPT_TITLE": "",
    "LIVE_CONV_MIC_PROMPT_BODY": "",
    "LIVE_CONV_MIC_PROMPT_ALLOW": "",
    "LIVE_CONV_MIC_PROMPT_CANCEL": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
