# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/en.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Hauptseite",
    "APP_TITLE": "OTMEGA KI-Plattform",
    "APP_SUBTITLE": "KI-Berater",
    "CHAT_PLACEHOLDER": "Geben Sie Ihre Nachricht ein...",
    "CHAT_SEND_BUTTON": "Senden",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Der Berater kann Fehler machen, daher bitte prüfen Sie die Informationen.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menü",
    "ICON_NEW_CHAT": "Neuer Chat",
    "ICON_HISTORY": "Verlauf",
    "ICON_TEMPLATES": "Vorlagen",
    "ICON_SETTINGS": "Einstellungen",
    "ICON_USER_PROFILE": "Benutzerprofil",
    "ICON_QUICK_ACTIONS": "Schnellaktionen",
    "ICON_PINNED": "Angeheftet",
    "ICON_GALLERY": "Galerie",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "App installieren",
    "PWA_ANDROID_MSG": "Installieren Sie diese App auf Ihrem Gerät für eine bessere Erfahrung und Offline-Zugriff.",
    "PWA_IOS_MSG": "So installieren Sie diese App auf Ihrem iPhone/iPad:\n1. Tippen Sie unten auf die Teilen-Schaltfläche\n2. Wählen Sie „Zum Home-Bildschirm hinzufügen“",
    "PWA_BTN_INSTALL": "Installieren",
    "PWA_BTN_LATER": "Vielleicht später",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Beim Beraternetzwerk anmelden",
    "AUTH_HEADER_SIGNUP": "Ihr einheitliches Konto erstellen",
    "AUTH_HEADER_LOGIN_NETWORK": "Beim Beraternetzwerk anmelden",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Ihr einheitliches Konto erstellen",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Anmelden",
    "AUTH_BUTTON_SIGNUP": "Konto erstellen",
    "AUTH_BUTTON_GOOGLE": "Mit Google fortfahren",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Passwort vergessen",
    "AUTH_BUTTON_SEND_RESET_LINK": "Link zum Zurücksetzen senden",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Noch kein Konto? Registrieren",
    "AUTH_PROMPT_LOGIN": "Bereits ein Konto? Anmelden",
    "AUTH_HELPER_TEXT_SIGNUP": "Sie erstellen ein einheitliches Konto, mit dem Sie auf alle Berater dieser Plattform zugreifen können.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Sie erstellen ein einheitliches Konto, mit dem Sie auf alle Berater dieser Plattform zugreifen können.",
    "AUTH_HELPER_TEXT_LOGIN": "Verwenden Sie dasselbe Konto (E-Mail/Passwort oder Google), das Sie für andere Berater in diesem Netzwerk verwendet haben.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Verwenden Sie dasselbe Konto (E-Mail/Passwort oder Google), das Sie für andere Berater in diesem Netzwerk verwendet haben.",
    "AUTH_FORGOT_PASSWORD_LINK": "Passwort vergessen?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Passwort zurücksetzen",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-Mail",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Sie werden angemeldet...",
    "AUTH_STATUS_LOADING_SIGNUP": "Ihr Konto wird erstellt...",
    "AUTH_STATUS_LOADING_RESET": "Link zum Zurücksetzen wird gesendet...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Anmeldung erfolgreich! Wird neu geladen...",
    "AUTH_STATUS_SUCCESS_RESET": "Link zum Zurücksetzen wurde erfolgreich gesendet. Bitte prüfen Sie Ihre E-Mail.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Link zum Zurücksetzen des Passworts wurde erfolgreich gesendet. Bitte prüfen Sie Ihre E-Mail.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Ungültige E-Mail-Adresse oder ungültiges Passwort.",
    "AUTH_ERROR_EMAIL_EXISTS": "Ein Konto mit dieser E-Mail-Adresse existiert bereits im Beraternetzwerk.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Ein Konto mit dieser E-Mail-Adresse existiert bereits. Bitte melden Sie sich an. Sie sind derzeit Mitglied von:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Ein Konto mit dieser E-Mail-Adresse existiert bereits im Beraternetzwerk. Bitte schließen Sie dieses Fenster und verwenden Sie den Bereich „Anmelden“ mit derselben E-Mail-Adresse und Ihrem bisherigen Passwort.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Sie sind derzeit Mitglied von:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-Mail-Adresse und Passwort sind erforderlich.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Konto wurde erstellt, aber die Mitgliedschaft konnte nicht eingerichtet werden. Bitte kontaktieren Sie den Support.",
    "AUTH_ERROR_DEFAULT": "Es ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Link zum Zurücksetzen konnte nicht gesendet werden. Bitte versuchen Sie es erneut.",
    "INVITE_REPLY_EMAIL_SENT": "Die Collabra-Einladungs-E-Mail wurde an Ihren Freund unter {invitee_email} gesendet.",
    "INVITE_REPLY_EMAIL_RESENT": "Die Collabra-Einladungs-E-Mail wurde erneut an Ihren Freund unter {invitee_email} gesendet.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Passwort anzeigen",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Passwort ausblenden",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Abbrechen",
    "GENERAL_CLOSE": "Schließen",
    "GENERAL_SEND": "Senden",
    "GENERAL_SEARCH": "Suchen",
    "GENERAL_RESET": "Zurücksetzen",
    "GENERAL_ENABLE": "Aktivieren",
    "GENERAL_LOADING": "Wird geladen...",
    "GENERAL_DELETE": "Löschen",
    "GENERAL_DELETING": "Wird gelöscht...",
    "GENERAL_SAVE_PASSWORD": "Passwort speichern",
    "AUTH_REMEMBER_EMAIL_LABEL": "E-Mail merken",
    "GENERAL_SAVING": "Wird gespeichert...",
    "GENERAL_SENDING": "Wird gesendet...",
    "GENERAL_REMOVING": "Wird entfernt...",
    "GENERAL_CONFIRM_REMOVAL": "Entfernung bestätigen",
    "GENERAL_EMPTY": "Leer",
    "GENERAL_UNAVAILABLE": "Nicht verfügbar",
    "GENERAL_ENABLED": "Aktiviert",
    "GENERAL_DISABLED": "Deaktiviert",
    "GENERAL_GRANTED": "Gewährt",
    "GENERAL_DENIED": "Verweigert",
    "GENERAL_DEFAULT": "Standard",
    "GENERAL_UNSUPPORTED": "Nicht unterstützt",
    "GENERAL_PUBLIC": "Öffentlich",
    "GENERAL_PRIVATE": "Privat",
    "GENERAL_USERNAME": "Benutzername",
    "GENERAL_EMAIL": "E-Mail",
    "GENERAL_YOU": "Sie",
    "GENERAL_USER": "Benutzer",
    "GENERAL_UNKNOWN": "Unbekannt",
    "GENERAL_VISITOR": "Besucher",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Unbekanntes Banner",
    "GENERAL_ADVISOR_BANNER": "Berater-Banner",
    "GENERAL_NOT_AVAILABLE": "N/V",
    "GENERAL_NOT_SELECTED": "Nicht ausgewählt",
    "GENERAL_NO_EMAIL_FOUND": "Keine E-Mail gefunden",
    "GENERAL_USER_ZERO_ONLY": "Nur User Zero",
    "GENERAL_CONNECTION_STATE": "Verbindungsstatus",
    "GENERAL_DISPLAY_ONLY": "Nur Anzeige",
    "GENERAL_TEXTAREA": "Textbereich",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menü (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Schnellaktionen (RCAC)",
    "HEADER_CHANGE_STATUS": "Status ändern",
    "HEADER_OT_COIN_BALANCE": "OT-Coin-Guthaben",
    "HEADER_ALT_USER": "Benutzer",
    "STATUS_BUSY": "Beschäftigt",
    "STATUS_AWAY": "Abwesend",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Unsichtbar",
    "NETWORK_CHECKING_CONNECTION": "Verbindung wird geprüft...",
    "NETWORK_ONLINE_LATENCY": "Online (Latenz: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Netzwerk: Gut (zum Pingen tippen)",
    "CHAT_TARGET_ALT": "Chat-Ziel",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Suchen...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Profilbild von {name} öffnen",
    "CHAT_MESSAGE_INPUT_ARIA": "Nachrichteneingabe",
    "CHAT_TOGGLE_VIEW_ARIA": "Ansicht umschalten",
    "CHAT_ADD_USER_ARIA": "Benutzer hinzufügen",
    "CHAT_ATTACH_ARIA": "Anhängen",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Senden",
    "CHAT_SEARCH_ARIA": "Suchen",
    "CHAT_OPEN_SEARCH_ARIA": "Suche öffnen",
    "CHAT_CLOSE_SEARCH_ARIA": "Suche schließen",
    "CHAT_ATTACHMENT_ALT": "Anhang",
    "CHAT_PREVIEW_ALT": "Vorschau",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Anhang entfernen",
    "CHAT_REPLYING_TO": "Antwort auf",
    "CHAT_CANCEL_REPLY_ARIA": "Antwort abbrechen",
    "CHAT_UPLOADING": "Wird hochgeladen...",
    "CHAT_LOADING_CHATS": "Chats werden geladen...",
    "CHAT_SEND_FAILED": "Senden fehlgeschlagen",
    "CHAT_SEND_FAILED_RETRY": "Senden fehlgeschlagen. Bitte erneut versuchen.",
    "CHAT_RETRY": "Erneut versuchen",
    "CHAT_EDITED": "bearbeitet",
    "CHAT_TYPING": "Tippt",
    "CHAT_LOADING": "Wird geladen",
    "CHAT_PENDING_INVITATION": "Ausstehende Einladung",
    "CHAT_PENDING_INVITATION_MIN": "{count} Min. ausstehende Einladung",
    "CHAT_PENDING_INVITATION_HR": "{count} Std. ausstehende Einladung",
    "CHAT_PENDING_INVITATION_DAY": "{count} Tag(e) ausstehende Einladung",
    "CHAT_WAITING_FOR_YOU": "{label} - Wartet auf Sie",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Annahme ausstehend",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Mikrofonzugriff verweigert.",
    "CHAT_UPLOAD_FAILED": "Hochladen fehlgeschlagen: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Zum Hochladen ist eine Internetverbindung erforderlich. Bitte versuchen Sie es erneut, wenn Sie online sind.",
    "CHAT_ERROR_AUTH": "Authentifizierungsfehler",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Dateiname oder content_type fehlt",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id oder target_id fehlt",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id fehlt für Uploads, die kein Avatar sind",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Ungültiger avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase-Service-Client nicht verfügbar",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Avatar-Lesebestätigung ist nur im Berater-Chat-Kontext gültig",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatar-Flow-Nachricht nicht gefunden oder nicht für Lesebestätigung geeignet",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Avatar-Nachricht konnte nicht als gelesen finalisiert werden",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 Anhang",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} Anhänge",
    "CHAT_VOICE_NOTE": "Sprachnotiz",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat nicht verfügbar. Dieser Benutzer hat Sie blockiert.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat nicht verfügbar. Sie haben diesen Benutzer blockiert.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Kontozugriff ist durch Richtlinie blockiert.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat nicht verfügbar. Dieses Konto wurde endgültig von User Zero blockiert.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat nicht verfügbar. Gegenseitige Blockierung ist aktiv.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat aufgrund der Blockierungsrichtlinie nicht verfügbar.",
    "MESSAGE_PREVIEW_PHOTO": "Foto",
    "MESSAGE_PREVIEW_VOICE": "Sprachnachricht",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Datei",
    "MESSAGE_PREVIEW_MESSAGE": "Nachricht",
    "MESSAGE_PREVIEW_SYSTEM": "Systemnachricht",
    "MESSAGE_PREVIEW_NEW": "Neue Nachricht",
    "MESSAGE_UNKNOWN_FILE": "Unbekannte Datei",
    "MESSAGE_AUDIO_ATTACHMENT": "Audioanhang",
    "MESSAGE_FILE_ATTACHMENT": "Anhang",
    "BANNER_INVITED_BY": "eingeladen von {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Suchergebnisse",
    "SEARCH_QUERY_LABEL": "Abfrage:",
    "SEARCH_LOADING_VISIBILITY": "Suchsichtbarkeit wird geladen...",
    "SEARCH_NO_RESULTS": "Im aktuellen Suchbereich wurde kein Ergebnis gefunden.",
    "SHARE_WITH_COLLABRA": "Mit Collabra teilen",
    "SHARE_SEND_TO": "Senden an",
    "SHARE_SELECT_ONE_BANNER": "Ein Banner auswählen",
    "SHARE_BANNER_LIST_ARIA": "Bannerliste",
    "SHARE_NO_MATCHING_BANNER": "Kein passendes Banner",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Kommentar hinzufügen...",
    "SHARE_RECENT_CHATS": "Aktuelle Chats",
    "SHARE_LEFT_LIST": "Linke Liste",
    "SHARE_RIGHT_LIST": "Rechte Liste",
    "SHARE_UNTITLED_BANNER": "Banner ohne Titel",
    "SHARE_SHARED_CONTENT": "Geteilter Inhalt",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Der geteilte Inhalt konnte nicht geöffnet werden.",
    "SHARE_OPEN_BANNER_FAILED": "Das ausgewählte Banner konnte nicht geöffnet werden.",
    "SHARE_ONE_PHOTO_SELECTED": "1 Foto ausgewählt",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} Fotos ausgewählt",
    "SHARE_ONE_FILE_SELECTED": "1 Datei ausgewählt",
    "SHARE_MANY_FILES_SELECTED": "{count} Dateien ausgewählt",
    "FORWARD_MESSAGE_TITLE": "Nachricht weiterleiten",
    "FORWARD_SELECT_RECIPIENTS": "Empfänger auswählen",
    "FORWARD_NO_OTHER_BANNER": "Kein anderes Banner verfügbar.",
    "FORWARD_SEND_TO_COUNT": "An {count} senden",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Wählen Sie mindestens ein Banner aus.",
    "FORWARD_FAILED_DEFAULT": "Weiterleitung fehlgeschlagen. Bitte versuchen Sie es erneut.",
    "FORWARD_PARTIAL_SENT": "{count} gesendet. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Quellnachricht für Weiterleitung nicht gefunden",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Diese Nachricht hat noch keinen weiterleitbaren Inhalt",
    "FORWARD_DESTINATION_MISSING": "Weiterleitungsziel fehlt",
    "FORWARD_MESSAGE_PREVIEW": "Weitergeleitete Nachricht",
    "MENU_PASTE": "Einfügen",
    "MENU_COPY": "Kopieren",
    "MENU_REPLY": "Antworten",
    "MENU_FORWARD": "Weiterleiten",
    "MENU_REMOVE_INVITATION": "Einladung entfernen",
    "MENU_REMOVE_FROM_LIST": "Aus Liste entfernen",
    "MENU_ADD_TO_LIST": "Zur Liste hinzufügen",
    "MENU_REJECT_INVITATION": "Einladung ablehnen",
    "MENU_FRONTEND_VERSION": "Frontend-Version",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Banner-Info: {title}",
    "MENU_MESSAGE_BUBBLE": "Nachrichtenblase",
    "MENU_CHAT_CANVAS_HEADER": "Chat-Canvas - {zone}",
    "MENU_CANVAS_INFO": "Canvas-Info",
    "MENU_CHAT_CANVAS_SUBLABEL": "Konversationsbereich / aktuelle Chat-Fläche",
    "MENU_INPUT_AREA_HEADER": "Eingabebereich - {zone}",
    "MENU_INPUT_AREA_INFO": "Eingabebereich-Info: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Untere Fläche für Texteingabe und Aktionstools",
    "MENU_HEADER": "Header - {zone}",
    "MENU_HEADER_INFO": "Header-Info: {title}",
    "MENU_HEADER_DESCRIPTION": "Obere Navigation und Seitensteuerungen",
    "MENU_ZONE_HEADER": "Zone - {zone}",
    "MENU_ZONE_SPACE_INFO": "Zonenbereich-Info",
    "MENU_EMPTY_LIST_SURFACE": "Leere/Liste-Fläche",
    "MENU_BLOCK": "Blockieren",
    "MENU_UNBLOCK": "Blockierung aufheben",
    "MENU_HIDE_IN_SEARCH": "In der Suche ausblenden",
    "MENU_UNHIDE_IN_SEARCH": "In der Suche einblenden",
    "MENU_VISIBLE_IN_SEARCH": "In der Suche sichtbar",
    "MENU_HIDDEN_IN_SEARCH": "In der Suche ausgeblendet",
    "MENU_VISIBLE_IN_USER_LIST": "In Benutzerliste sichtbar",
    "MENU_HIDDEN_IN_USER_LIST": "In Benutzerliste ausgeblendet",
    "MENU_NOT_BLOCKED": "Nicht blockiert",
    "MENU_BLOCKED": "Blockiert",
    "MENU_FRONTEND_VERSION_LOADING": "Wird geladen...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Bannerbezogener Wert wird vom Backend geladen. Keine Option wird als aktiv markiert, bis die Datenbankantwort eintrifft.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend-Wert konnte nicht geladen werden. Es wird keine vertrauenswürdige aktive Option angezeigt.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Expliziter bannerbezogener Datenbankwert ist {overrideVersion}. Globaler Standard ist {globalDefaultVersion}. Der Zielbenutzer muss die App vollständig aktualisieren oder erneut öffnen, damit der Start-Bootstrap ihn anwendet.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Es ist kein expliziter bannerbezogener Datenbankwert gespeichert. FeV2.0.0 ist standardmäßig aktiv. Globaler Standard ist {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Expliziter bannerbezogener Datenbankwert ist aktiv, nachdem die Ziel-App vollständig neu geladen wurde",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Es ist kein expliziter bannerbezogener Wert gespeichert; dies ist der standardmäßige individuelle FeV2.0.0-Zustand",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Diese Option entspricht auch dem aktuellen globalen Standard",
    "MENU_DELETE_PERMANENT_CONFIRM": "{target} dauerhaft aus der Datenbank löschen? Dadurch werden Konto, Chatverlauf und Abhängigkeiten entfernt und für einen zukünftigen Wiedereintritt ein vollständig neuer Einladungsweg erzwungen.",
    "MENU_DELETE_PERMANENTLY": "Dauerhaft löschen",
    "MENU_REFRESH_PAGE": "Seite aktualisieren",
    "MENU_LOG_OFF": "Abmelden",
    "MENU_HARD_RELOAD": "Neueste Version abrufen",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-Mail (Admin-Benutzer)",
    "AUTH_PASSWORD_PLACEHOLDER": "Passwort",
    "AUTH_CONNECTING": "Verbindung wird hergestellt...",
    "AUTH_SIGNING_OUT": "Abmeldung läuft...",
    "AUTH_BACK_TO_LOGIN": "Zurück zur Anmeldung",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Ungültige Serverantwort: Kein Token gefunden.",
    "AUTH_LOGIN_FAILED": "Anmeldung fehlgeschlagen",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Passwörter stimmen nicht überein.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Passwörter stimmen nicht überein!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Passwörter müssen exakt übereinstimmen.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Neues Passwort",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Passwort bestätigen",
    "AUTH_CHANGE_PASSWORD": "Passwort ändern",
    "AUTH_SAVING_PASSWORD": "Wird gespeichert...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Passwort erfolgreich aktualisiert.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Passwort kann derzeit nicht geändert werden.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Sie müssen angemeldet sein, um Ihr Passwort zu ändern.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Sichtbarkeit des neuen Passworts umschalten",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Sichtbarkeit der Passwortbestätigung umschalten",
    "REGISTER_TITLE": "Registrierung abschließen",
    "REGISTER_SUBTITLE": "Bitte legen Sie Ihr Passwort manuell fest.",
    "REGISTER_CREATING_ACCOUNT": "Konto wird erstellt...",
    "REGISTER_FINISH_SETUP": "Einrichtung abschließen",
    "REGISTER_FAILED_SET_PASSWORD": "Passwort konnte nicht festgelegt werden",
    "INVITE_EMAIL_INSTRUCTION": "Bitte geben Sie die E-Mail-Adresse des Eingeladenen ein (Format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Einladen",
    "INVITE_EMAIL_REQUIRED": "Bitte geben Sie die E-Mail-Adresse des Eingeladenen ein.",
    "INVITE_EMAIL_INVALID": "Ungültiges E-Mail-Format. Bitte verwenden Sie: user@example.com",
    "PENDING_INVITATION_TITLE": "Ausstehende Einladung",
    "PENDING_INVITATION_REMOVE_QUESTION": "Diese ausstehende Einladung aus der Datenbank entfernen?",
    "PENDING_INVITATION_KEEP": "Einladung behalten",
    "PENDING_INVITATION_REMOVAL_FAILED": "Entfernung fehlgeschlagen.",
    "REMOVE_FROM_LIST_TITLE": "Aus Liste entfernen",
    "REMOVE_FROM_LIST_WARNING": "Diesen Benutzer jetzt aus beiden Listen entfernen? Der Chat-Zugriff wird sofort getrennt. Der einzige Rückweg ist eine neue Einladung.",
    "REMOVE_FROM_LIST_KEEP": "Benutzer in Liste behalten",
    "REMOVE_FROM_LIST_FAILED": "Entfernen aus Liste fehlgeschlagen.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Einstellung & Live-Status",
    "PERMISSION_DIALOG_ARIA": "Einstellung und Live-Status",
    "PERMISSION_TRIGGER_ARIA": "Auslöser für Einstellungs-Popup",
    "PERMISSION_CLOSE_ARIA": "Berechtigungs-Popup schließen",
    "PERMISSION_LIVE_STATUS": "Live-Status",
    "PERMISSION_SYSTEM_PERMISSION": "Systemberechtigung",
    "PERMISSION_APP_PUSH": "App-Push",
    "PERMISSION_LOCATION_PERMISSION": "Standortberechtigung",
    "PERMISSION_APP_LOCATION": "App-Standort",
    "PERMISSION_CONTROLS": "Berechtigungssteuerungen",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push-Benachrichtigungen",
    "PERMISSION_LOCATION_ACCESS": "Standortzugriff",
    "PERMISSION_IN_APP_SETTINGS": "In-App-Einstellungen",
    "PERMISSION_ALERT_SOUND": "Warnton",
    "PERMISSION_APP_BADGE": "App-Badge",
    "PERMISSION_PASSWORD_SETTINGS": "Passworteinstellungen",
    "PERMISSION_NAVIGATION_STATUS": "Navigationsstatus",
    "PERMISSION_SELECTED_ZONE": "Ausgewählte Zone",
    "PERMISSION_STAGED_CHAT_BANNER": "Vorbereitetes Chat-Banner",
    "PERMISSION_CANVAS_CONTENT": "Canvas-Inhalt",
    "PERMISSION_YOUR_DEVICES": "Ihre Geräte ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Geräteliste aktualisieren",
    "PERMISSION_REFRESH_LIST": "Liste aktualisieren",
    "PERMISSION_NO_REGISTERED_DEVICES": "Keine registrierten Geräte gefunden.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Einstellungs-Popup skalieren",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Push-Benachrichtigungen umschalten",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Standortzugriff umschalten",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Warnton umschalten",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "App-Badge umschalten",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Profilsichtbarkeit umschalten",
    "PERMISSION_OFF_IN_V1": "Aus in v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Bannerliste",
    "PERMISSION_PUSH_DISABLED_V1": "Push-Benachrichtigungen sind für die v1-Google-Play-Version deaktiviert.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Push-Benachrichtigungen sind für dieses Gerät aktiviert.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Systembenachrichtigungen sind blockiert. Tippen Sie, um die Einstellungshilfe zu öffnen.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Aktivieren, um die Zustellzuverlässigkeit zu verbessern.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Um Systembenachrichtigungen zu deaktivieren, öffnen Sie die Benachrichtigungseinstellungen Ihres Browsers/Ihrer Website und setzen Sie diese Website auf Blockieren.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Um die Systembenachrichtigungsberechtigung zu ändern, öffnen Sie die Benachrichtigungseinstellungen Ihres Browsers/Ihrer Website und setzen Sie diese Website auf Zulassen.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Standortzugriff ist für entfernungsbasierte LCAC-Sortierung und Kartenpositionierung aktiviert.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Die Standort-API wird in dieser Umgebung nicht unterstützt.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Standortzugriff ist blockiert. Tippen Sie, um die Einstellungshilfe zu öffnen.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Aktivieren, um präzise entfernungsbasierte LCAC-Sortierung und In-App-Kartenpositionierung zu erlauben.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Standortzugriff wird in dieser Umgebung nicht unterstützt.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Um Standortzugriff zu deaktivieren, öffnen Sie die Standort-Einstellungen Ihres Browsers/Ihrer Website und setzen Sie diese Website auf Blockieren.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Um Standortzugriff für Entfernungssortierung und In-App-Kartenpositionierung zu aktivieren, öffnen Sie die Standort-Einstellungen Ihres Browsers/Ihrer Website und setzen Sie diese Website auf Zulassen.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Registrierte Geräte können derzeit nicht geladen werden.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "UI-Bridge wird geladen...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Lokale Bridge wird geladen...",
    "RUNTIME_LOADING_BACKEND": "Backend wird geladen...",
    "RUNTIME_LOADING": "Wird geladen...",
    "RUNTIME_LOADING_FROM_DATABASE": "Wird aus der Datenbank geladen...",
    "RUNTIME_BACKEND_CONNECTED": "Backend verbunden",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Zwischengespeicherter Fallback aktiv",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Standard-Fallback aktiv",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallback-Standardwerte aktiv",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Speichern über Backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Im Backend-Service gespeichert",
    "RUNTIME_SAVE_FAILED": "Speichern fehlgeschlagen",
    "RUNTIME_LOAD_FAILED": "Laden fehlgeschlagen",
    "RUNTIME_CONNECTED": "Verbunden",
    "RUNTIME_LOGIN_REQUIRED": "Anmeldung erforderlich",
    "RUNTIME_SAVED": "Gespeichert",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI bereit - Runtime ausstehend",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Der geschützte Backend-Auswahldienst hat die angeforderte Modelloption abgelehnt oder konnte sie nicht speichern.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Der geschützte Backend-Auswahldienst hat die angeforderte WF1-Routing-Änderung abgelehnt oder konnte sie nicht speichern.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Der Selektor liest jetzt aktive Konfiguration, Qwen-Routing und zulässige Optionen aus dem geschützten Backend-Service.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Der Backend-Selektorservice ist derzeit nicht verfügbar, daher wird der zuletzt zwischengespeicherte Selektorzustand verwendet.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Die Standardwerte des Selektors sind aktiv, weil kein Backend- oder zwischengespeicherter Selektorzustand geladen werden konnte.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Der geschützte Backend-Auswahldienst hat die aktive WF1-Routing-Konfiguration aktualisiert und den Runtime-Domain-Cache aktualisiert.",
    "FRONTEND_VERSION_TITLE": "Frontend-Version",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Dieser Selektor steuert die aktive Frontend-Version für alle Benutzer. FeV2.0.0 ist aktiv.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Dieser Selektor liest die aktive Frontend-Version aus config_domain_registry. Runtime löst zu FeV2.0.0 auf.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Die Backend-Konfiguration der Frontend-Version konnte nicht geladen werden, daher bleibt der codierte FeV2.0.0-Standard aktiv, bis der Start-Bootstrap den geschützten Service erneut lesen kann.",
    "FRONTEND_VERSION_HELPER_SAVED": "Die aktive Frontend-Version wurde in config_domain_registry gespeichert. Eine vollständige Aktualisierung oder der nächste App-Start wendet den Runtime-Wert an.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Der Backend-Steuerdienst für die Frontend-Version konnte die angeforderte globale Version nicht speichern.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktive Frontend-Version.",
    "CHAT_DELETE_WINDOW_TITLE": "Chat-Löschfenster",
    "CHAT_DELETE_HELPER": "Dieser Wert steuert das Verfügbarkeitsfenster für „Für alle löschen“ in Sekunden. Der Backend-Guard ändert sich unmittelbar nach dem Speichern. Die Sichtbarkeit der Blase ändert sich nach einer vollständigen Aktualisierung oder beim nächsten App-Start.",
    "CHAT_DELETE_HELPER_FALLBACK": "Der Backend-Steuerdienst für Chat-Löschung konnte nicht geladen werden, daher bleibt der codierte Standard aktiv, bis der Start-Bootstrap den geschützten Service erneut lesen kann.",
    "CHAT_DELETE_HELPER_SAVED": "Das Verfügbarkeitsfenster für „Für alle löschen“ wurde in config_domain_registry gespeichert. Der Backend-Guard ändert sich sofort. Die Sichtbarkeit der Blase ändert sich nach einer vollständigen Aktualisierung oder beim nächsten App-Start.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Der Backend-Steuerdienst für Chat-Löschung konnte den angeforderten Fensterwert nicht speichern.",
    "CHAT_DELETE_WINDOW_LABEL": "Fenster für „Für alle löschen“",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} Sek.",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Speichern Sie den Wert in ganzen Sekunden. Der aktuelle Produktionswert ist 86400 Sekunden = 1 Tag.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Fenstersekunden",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Geben Sie eine ganze Zahl größer oder gleich 0 ein.",
    "CHAT_DELETE_SAVE_BUTTON": "Löschfenster speichern",
    "PROFILE_VISIBILITY_TITLE": "Profilsichtbarkeit",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Sie müssen angemeldet sein, um die Kontosichtbarkeit zu verwalten.",
    "PROFILE_VISIBILITY_HELPER": "Dieser Schalter aktualisiert nur den Sichtbarkeitsstatus Ihres Kontos. Auffindbarkeit und Bannerlisten-Verhalten bleiben in dieser Phase unverändert.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Profilsichtbarkeit konnte derzeit nicht geladen werden.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Profilsichtbarkeit konnte derzeit nicht aktualisiert werden.",
    "PROFILE_VISIBILITY_SAVED": "Ihre Kontosichtbarkeit ist jetzt {visibility}. Auffindbarkeits-Flags bleiben in dieser Phase unverändert.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Öffentliches Konto",
    "PROFILE_VISIBILITY_STORED": "Gespeicherte Sichtbarkeit",
    "WF1_MODEL_CONTROL_TITLE": "WF1-Modellsteuerung",
    "WF1_ENABLE_TRANSLATION": "Übersetzung / Pivot aktivieren",
    "WF1_TRANSLATION_ACTIVE": "KI-Übersetzung ist aktiv.",
    "WF1_TRANSLATION_INACTIVE": "WF1 läuft weiter, aber der Quelltext wird kopiert und der Pivot wird als inaktiv markiert.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktiver Runtime-Slot",
    "WF1_ALLOW_SAME_LANGUAGE": "KI für gleichsprachige Paare erlauben",
    "WF1_SAME_LANGUAGE_ACTIVE": "Gleichsprachige Paare folgen dem normalen WF1-Routing.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Gleichsprachige Paare umgehen KI und speichern „Keine Pivot-Sprache“ als aktiv.",
    "WF1_QWEN_ROUTING": "Qwen-Paar-Routing",
    "WF1_QWEN_ROUTING_HELPER": "Unten markierte Sprachen verwenden Qwen-Max, wenn das Paar entweder dieselbe markierte Sprache, eine markierte Sprache mit Englisch oder zwei markierte nicht-englische Sprachen umfasst. Andernfalls bleibt das ausgewählte Primärmodell aktiv.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter-Test-Slot",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter-Test-Slot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Nur Qualitätstest",
    "WF1_OPENROUTER_HELPER": "Dieser Slot ist nur für temporäre OpenRouter-Qualitätstests bearbeitbar. Er ändert den operativen Qwen-Paar-Routing-Pfad nicht, es sei denn, dieser Slot selbst wird zum aktiven Modell.",
    "WF1_LABEL": "Bezeichnung",
    "WF1_PRODUCT": "Produkt",
    "WF1_MODEL": "Modell",
    "WF1_PROVIDER_OPENROUTER": "Anbieter: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter-Test-Slot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max über OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google-Listenpreis",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI-Listenpreis",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter-Listenpreis",
    "LANGUAGE_ENGLISH": "Englisch",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Chinesisch (vereinfacht)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Chinesisch (traditionell)",
    "LANGUAGE_JAPANESE": "Japanisch",
    "LANGUAGE_KOREAN": "Koreanisch",
    "LANGUAGE_PERSIAN": "Persisch",
    "LANGUAGE_TURKISH_ISTANBUL": "Türkisch (Istanbul)",
    "LANGUAGE_ARABIC": "Arabisch",
    "LANGUAGE_FRENCH": "Französisch",
    "LANGUAGE_GERMAN": "Deutsch",
    "LANGUAGE_SPANISH": "Spanisch",
    "LANGUAGE_PORTUGUESE": "Portugiesisch",
    "LANGUAGE_ITALIAN": "Italienisch",
    "LANGUAGE_RUSSIAN": "Russisch",
    "LANGUAGE_DUTCH": "Niederländisch",
    "LANGUAGE_VIETNAMESE": "Vietnamesisch",
    "LANGUAGE_INDONESIAN": "Indonesisch",
    "LANGUAGE_THAI": "Thailändisch",
    "LANGUAGE_MALAY": "Malaiisch",
    "WF1_PRICING_CUSTOM": "Preisgestaltung: benutzerdefiniertes Slot-Modell - aktuelle OpenRouter-Preise prüfen",
    "WF1_SAVE_OPENROUTER_SLOT": "OpenRouter-Slot speichern",
    "WF1_PRICING_LINE": "Eingabe {input} - Ausgabe {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "Zonensichtbarkeitssteuerung",
    "ZONE_ENABLE": "{zone} aktivieren",
    "ZONE_ENABLED_NOTE": "{zone} kann nach dem nächsten App-Start für zugelassene Rollen erscheinen.",
    "ZONE_DISABLED_NOTE": "{zone} wird nach dem nächsten App-Start für Nicht-S_Admin-Benutzer als nicht vorhanden behandelt.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin umgeht diese Rollenliste und behält immer Zugriff.",
    "ZONE_ROLE_LOCKED": "Rollenauswahlen sind vorübergehend gesperrt, solange diese Zone deaktiviert ist, und werden exakt wie gespeichert wiederhergestellt, wenn die Zone erneut aktiviert wird.",
    "ZONE_LCAC_CONTROL": "LCAC-Steuerung",
    "ZONE_RCAC_CONTROL": "RCAC-Steuerung",
    "ZONE_LCAC_DESCRIPTION": "Steuert die Existenz der linken reservierten Zone und die Rollen, die sie sehen dürfen.",
    "ZONE_RCAC_DESCRIPTION": "Steuert die Existenz der rechten reservierten Zone und die Rollen, die sie sehen dürfen.",
    "ZONE_VISIBILITY_BACKEND": "Der Bootstrap der Zonensichtbarkeit liest jetzt aus dem geschützten Backend-Service. Änderungen gelten beim nächsten App-Start.",
    "ZONE_VISIBILITY_CACHED": "Der Backend-Service für Zonensichtbarkeit ist derzeit nicht verfügbar, daher sind zwischengespeicherte oder lokale Standards aktiv.",
    "ZONE_VISIBILITY_DEFAULTS": "Standardwerte für Zonensichtbarkeit sind aktiv, weil kein Backend- oder zwischengespeicherter Zustand geladen werden konnte.",
    "ZONE_VISIBILITY_SAVED": "Der Bootstrap der Zonensichtbarkeit wurde gespeichert. Ein harter Neustart oder der nächste App-Start ist für die Runtime-Anwendung erforderlich.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Der geschützte Backend-Service konnte die angeforderte Änderung der Zonensichtbarkeit nicht speichern.",
    "ROLE_MEMBER": "Mitglied",
    "ROLE_STAFF": "Mitarbeiter",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Aktivieren Sie Benachrichtigungen, um neue Nachrichten zu erhalten.",
    "MAIN_LOG_OUT": "Abmelden",
    "NOTIFICATION_NEW_MESSAGE": "Neue Nachricht",
    "NOTIFICATION_UNREAD_MESSAGE": "Sie haben eine ungelesene Nachricht.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Vollansicht",
    "MEDIA_AUDIO_ATTACHMENT": "Audioanhang",
    "MEDIA_FILE_FALLBACK": "Datei",
    "MEDIA_DOWNLOAD_READY": "Anhang bereit zum Herunterladen",
    "MEDIA_TYPE_UNSUPPORTED": "Typ für Vollansicht nicht unterstützt",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Vorheriges Bild",
    "MEDIA_NEXT_IMAGE_ARIA": "Nächstes Bild",
    "MEDIA_OPEN_ORIGINAL": "Original öffnen",
    "MEDIA_DOWNLOAD": "Herunterladen",
    "MEDIA_CLOSE_ARIA": "Schließen",
    "MEDIA_PROFILE_PICTURE_ARIA": "Profilbild von {name}",
    "MEDIA_PROFILE_ALT": "Profil von {name}",
    "MEDIA_UPLOAD_FAILED": "Hochladen fehlgeschlagen",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend-Token-Fehler",
    "MEDIA_UPLOAD_URL_MISSING": "Kritisch: Upload-URL fehlt in der Backend-Antwort.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Authentifizierungstoken für Chat-Upload fehlt",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Chat-Upload-Token-Anfrage fehlgeschlagen",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Ungültige Chat-Upload-Antwort",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS-Upload fehlgeschlagen",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Dateiname oder contentType fehlt",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path fehlt",
    "BLOCK_NOTICE_TITLE": "Hinweis auf dauerhafte Blockierung",
    "BLOCK_NOTICE_MESSAGE": "Ihr Konto wurde aufgrund eines Richtlinienverstoßes vorübergehend gesperrt.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Wenn Sie glauben, dass dies eine Nachverfolgung erfordert, kontaktieren Sie bitte",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "per E-Mail.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Unbekannter Benutzer",
    "GENERAL_GUEST": "Gast",
    "ADVISOR_FOR_CLIENT": "Berater für {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token und Passwort sind erforderlich",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Anforderungstext muss JSON sein",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Ungültiger oder abgelaufener Einladungstoken",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Passwortfestlegung fehlgeschlagen: Sitzung oder Benutzer fehlt",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Passwortfestlegung während der Anmeldung fehlgeschlagen",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Admin-Token-Generierung fehlgeschlagen",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Anmeldung fehlgeschlagen: Sitzung oder Benutzer fehlt",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registrierung erfolgreich. Bitte prüfen Sie Ihre E-Mail zur Verifizierung.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Registrierung aus unbekanntem Grund fehlgeschlagen",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Ungültige Token-Verarbeitung",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Zugriffstoken ist erforderlich",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Token-Hash-Vorschau erfordert E-Mail-Hinweis aus der Weiterleitungs-URL",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Identität für diesen Token kann nicht aufgelöst werden",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Nur User Zero kann auf den WF1-LLM-Selektordienst zugreifen.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Nur User Zero kann auf den Steuerdienst für Zonensichtbarkeit zugreifen.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Nur User Zero kann auf den Steuerdienst für Frontend-Version zugreifen.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Nur User Zero kann die Frontend-Version eines anderen Benutzers prüfen.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Nur User Zero kann auf den Steuerdienst für Chat-Löschung zugreifen.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Nur User Zero kann ein Benutzerkonto dauerhaft löschen.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Ungültiger Anfrage-Payload.",
    "API_ERROR_INTERNAL_SERVER": "Interner Serverfehler",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funktion im Backend fehlt (Neuladen erforderlich)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Nur DB-RPC ist für delivered/read-Übergänge erlaubt.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Bitte warten Sie, bevor Sie eine weitere Nachricht senden.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Nachricht erfolgreich gesendet.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Kontaktdienst ist nicht verfügbar.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Nachrichtenversand fehlgeschlagen.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Name ist erforderlich.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-Mail ist ungültig.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Nachricht ist erforderlich.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Selektor-Payload ist erforderlich.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload für Zonensichtbarkeit ist erforderlich.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload für Frontend-Version ist erforderlich.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload für Chat-Löschsteuerung ist erforderlich.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Authentifizierte Benutzer-ID ist erforderlich.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Authentifizierte Viewer-Benutzer-ID ist erforderlich.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Authentifizierte Akteur-Benutzer-ID ist erforderlich.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id ist erforderlich.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id ist erforderlich.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids-Liste ist erforderlich.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email ist erforderlich.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by ist erforderlich.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Such-Runtime ist durch die globale Frontend-Version deaktiviert.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Sie dürfen diese ausstehende Einladung nicht stornieren.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Diese Einladung kann nicht mehr storniert werden, weil der Benutzer bereits registriert ist.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Ausstehende Einladung nicht gefunden.",
    "INVITE_REPLY_ALREADY_MEMBER": "Glückwunsch, Ihr Freund ({invitee_email}) ist bereits in dieser App registriert und Mitglied dieses Arbeitsbereichs.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Für {invitee_email} ist eine Einladung ausstehend, aber die erneute E-Mail konnte nicht ausgelöst werden. Bitte prüfen Sie die Mail-Logs.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Ein Einladungsdatensatz wurde für {invitee_email} erstellt, aber die E-Mail-Zustellung konnte nicht bestätigt werden. Bitte versuchen Sie es später erneut oder prüfen Sie die Mail-Logs.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Einladungsdatensatz konnte nicht erstellt werden. Bitte versuchen Sie es später erneut.",
    "INVITE_REPLY_SYSTEM_ERROR": "Systemfehler während des Einladungsprozesses: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend-Konfigurationsfehler: Supabase-Anmeldedaten fehlen",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend-Konfigurationsfehler: Ungültige Supabase-URL",
    "CHAT_ERROR_ACCESS_DENIED": "Zugriff verweigert",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Inhalt darf bei Textnachrichten nicht leer sein",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Konversations-ID konnte nicht bestimmt werden",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC-Authentifizierungskontext fehlt",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC hat ungültigen Nachrichten-Payload zurückgegeben",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Einfügen fehlgeschlagen, keine Daten zurückgegeben",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations muss eine Liste sein",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Ungültiger Operations-Payload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type wird nicht unterstützt",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id ist erforderlich",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Nachricht nicht gefunden",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Löschen ist nur für Ihre eigene Nachricht erlaubt",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "„Für alle löschen“ ist für diese Nachricht nicht mehr verfügbar",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "„Für alle löschen“ fehlgeschlagen",
    "API_ERROR_SERVER_CONFIGURATION": "Serverkonfigurationsfehler",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Webhook-Secret-Header fehlt",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Nicht autorisierte Webhook-Quelle",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend-Konfigurationsfehler",
    "API_ERROR_MODULE_ATTRIBUTE": "Modulattribut-Fehler: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Fehler vor dem Löschen der Einladung beim Entfernen des wartenden Auth-Benutzers.",
    "CHAT_ERROR_DB": "DB-Fehler: {error}",
}
