# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/el.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Κύρια",
    "APP_TITLE": "Πλατφόρμα AI OTMEGA",
    "APP_SUBTITLE": "Σύμβουλος AI",
    "CHAT_PLACEHOLDER": "Πληκτρολογήστε το μήνυμά σας...",
    "CHAT_SEND_BUTTON": "Αποστολή",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Ο σύμβουλος μπορεί να κάνει λάθη, γι' αυτό ελέγξτε ξανά τις πληροφορίες.",
    "STATUS_ONLINE": "Σε σύνδεση",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Μενού",
    "ICON_NEW_CHAT": "Νέα συνομιλία",
    "ICON_HISTORY": "Ιστορικό",
    "ICON_TEMPLATES": "Πρότυπα",
    "ICON_SETTINGS": "Ρυθμίσεις",
    "ICON_USER_PROFILE": "Προφίλ χρήστη",
    "ICON_QUICK_ACTIONS": "Γρήγορες ενέργειες",
    "ICON_PINNED": "Καρφιτσωμένο",
    "ICON_GALLERY": "Συλλογή",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Εγκατάσταση εφαρμογής",
    "PWA_ANDROID_MSG": "Εγκαταστήστε αυτήν την εφαρμογή στη συσκευή σας για καλύτερη εμπειρία και πρόσβαση εκτός σύνδεσης.",
    "PWA_IOS_MSG": "Για να εγκαταστήσετε αυτήν την εφαρμογή στο iPhone/iPad σας:\n1. Πατήστε το κουμπί Κοινοποίηση παρακάτω\n2. Επιλέξτε 'Προσθήκη στην αρχική οθόνη'",
    "PWA_BTN_INSTALL": "Εγκατάσταση",
    "PWA_BTN_LATER": "Ίσως αργότερα",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Συνδεθείτε στο δίκτυο συμβούλων",
    "AUTH_HEADER_SIGNUP": "Δημιουργήστε τον ενοποιημένο λογαριασμό σας",
    "AUTH_HEADER_LOGIN_NETWORK": "Συνδεθείτε στο δίκτυο συμβούλων",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Δημιουργήστε τον ενοποιημένο λογαριασμό σας",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Σύνδεση",
    "AUTH_BUTTON_SIGNUP": "Δημιουργία λογαριασμού",
    "AUTH_BUTTON_GOOGLE": "Συνέχεια με Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Ξεχάσατε τον κωδικό πρόσβασης",
    "AUTH_BUTTON_SEND_RESET_LINK": "Αποστολή συνδέσμου επαναφοράς",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Δεν έχετε λογαριασμό; Εγγραφείτε",
    "AUTH_PROMPT_LOGIN": "Έχετε ήδη λογαριασμό; Συνδεθείτε",
    "AUTH_HELPER_TEXT_SIGNUP": "Δημιουργείτε έναν ενοποιημένο λογαριασμό που μπορείτε να χρησιμοποιήσετε για πρόσβαση σε όλους τους συμβούλους αυτής της πλατφόρμας.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Δημιουργείτε έναν ενοποιημένο λογαριασμό που μπορείτε να χρησιμοποιήσετε για πρόσβαση σε όλους τους συμβούλους αυτής της πλατφόρμας.",
    "AUTH_HELPER_TEXT_LOGIN": "Χρησιμοποιήστε τον ίδιο λογαριασμό (email/κωδικό πρόσβασης ή Google) που χρησιμοποιήσατε για άλλους συμβούλους σε αυτό το δίκτυο.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Χρησιμοποιήστε τον ίδιο λογαριασμό (email/κωδικό πρόσβασης ή Google) που χρησιμοποιήσατε για άλλους συμβούλους σε αυτό το δίκτυο.",
    "AUTH_FORGOT_PASSWORD_LINK": "Ξεχάσατε τον κωδικό σας;",
    "AUTH_FORGOT_PASSWORD_TITLE": "Επαναφορά του κωδικού πρόσβασής σας",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Εισαγάγετε τη διεύθυνση email σας και θα σας στείλουμε έναν σύνδεσμο για να επαναφέρετε τον κωδικό πρόσβασής σας.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Email",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Σας συνδέουμε...",
    "AUTH_STATUS_LOADING_SIGNUP": "Δημιουργία του λογαριασμού σας...",
    "AUTH_STATUS_LOADING_RESET": "Αποστολή συνδέσμου επαναφοράς...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Η σύνδεση ήταν επιτυχής! Επαναφόρτωση...",
    "AUTH_STATUS_SUCCESS_RESET": "Ο σύνδεσμος επαναφοράς στάλθηκε με επιτυχία. Ελέγξτε το email σας.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Ο σύνδεσμος επαναφοράς κωδικού πρόσβασης στάλθηκε με επιτυχία. Ελέγξτε το email σας.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Μη έγκυρο email ή κωδικός πρόσβασης.",
    "AUTH_ERROR_EMAIL_EXISTS": "Υπάρχει ήδη λογαριασμός με αυτό το email στο δίκτυο συμβούλων.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Υπάρχει ήδη λογαριασμός με αυτό το email. Παρακαλώ συνδεθείτε. Αυτήν τη στιγμή είστε μέλος σε:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Υπάρχει ήδη λογαριασμός με αυτό το email στο δίκτυο συμβούλων. Κλείστε αυτό το παράθυρο και χρησιμοποιήστε την ενότητα 'Login' με το ίδιο email και τον προηγούμενο κωδικό σας.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Αυτήν τη στιγμή είστε μέλος σε:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "Απαιτούνται email και κωδικός πρόσβασης.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Ο λογαριασμός δημιουργήθηκε, αλλά η ρύθμιση της συνδρομής απέτυχε. Επικοινωνήστε με την υποστήριξη.",
    "AUTH_ERROR_DEFAULT": "Παρουσιάστηκε σφάλμα. Παρακαλώ δοκιμάστε ξανά.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Απαιτείται ωφέλιμο φορτίο ελέγχου banner επισκέπτη.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Μόνο ο Χρήστης Μηδέν μπορεί να ενημερώσει τα στοιχεία ελέγχου του banner επισκέπτη.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Αποτυχία αποστολής του συνδέσμου επαναφοράς. Παρακαλώ δοκιμάστε ξανά.",
    "INVITE_REPLY_EMAIL_SENT": "Το email πρόσκλησης Collabra στάλθηκε στον φίλο σας στη διεύθυνση {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Το email πρόσκλησης Collabra στάλθηκε ξανά στον φίλο σας στη διεύθυνση {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Εμφάνιση κωδικού πρόσβασης",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Απόκρυψη κωδικού πρόσβασης",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Ακύρωση",
    "GENERAL_CLOSE": "Κλείσιμο",
    "GENERAL_SEND": "Αποστολή",
    "GENERAL_SEARCH": "Αναζήτηση",
    "GENERAL_RESET": "Επαναφορά",
    "GENERAL_ENABLE": "Ενεργοποίηση",
    "GENERAL_LOADING": "Φόρτωση...",
    "GENERAL_DELETE": "Διαγραφή",
    "GENERAL_DELETING": "Διαγραφή...",
    "GENERAL_SAVE_PASSWORD": "Αποθήκευση κωδικού πρόσβασης",
    "AUTH_REMEMBER_EMAIL_LABEL": "Απομνημόνευση email",
    "GENERAL_SAVING": "Αποθήκευση...",
    "GENERAL_SENDING": "Αποστολή...",
    "GENERAL_REMOVING": "Αφαίρεση...",
    "GENERAL_CONFIRM_REMOVAL": "Επιβεβαίωση αφαίρεσης",
    "GENERAL_EMPTY": "Κενό",
    "GENERAL_UNAVAILABLE": "Μη διαθέσιμο",
    "GENERAL_ENABLED": "Ενεργοποιημένο",
    "GENERAL_DISABLED": "Απενεργοποιημένο",
    "GENERAL_GRANTED": "Εγκρίθηκε",
    "GENERAL_DENIED": "Απορρίφθηκε",
    "GENERAL_DEFAULT": "Προεπιλογή",
    "GENERAL_UNSUPPORTED": "Δεν υποστηρίζεται",
    "GENERAL_PUBLIC": "Δημόσιο",
    "GENERAL_PRIVATE": "Ιδιωτικό",
    "GENERAL_USERNAME": "Όνομα χρήστη",
    "GENERAL_EMAIL": "Email",
    "GENERAL_YOU": "Εσείς",
    "GENERAL_USER": "Χρήστης",
    "GENERAL_UNKNOWN": "Άγνωστο",
    "GENERAL_VISITOR": "Επισκέπτης",
    "GENERAL_PROFILE": "Προφίλ",
    "GENERAL_BANNER": "Μπάνερ",
    "GENERAL_UNKNOWN_BANNER": "Άγνωστο μπάνερ",
    "GENERAL_ADVISOR_BANNER": "Μπάνερ συμβούλου",
    "GENERAL_NOT_AVAILABLE": "Μ/Δ",
    "GENERAL_NOT_SELECTED": "Δεν έχει επιλεγεί",
    "GENERAL_NO_EMAIL_FOUND": "Δεν βρέθηκε email",
    "GENERAL_USER_ZERO_ONLY": "Μόνο User Zero",
    "GENERAL_CONNECTION_STATE": "Κατάσταση σύνδεσης",
    "GENERAL_DISPLAY_ONLY": "Μόνο προβολή",
    "GENERAL_TEXTAREA": "Περιοχή κειμένου",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Μενού (LCAC)",
    "HEADER_CHAT_CCAC": "Συνομιλία (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Γρήγορες ενέργειες (RCAC)",
    "HEADER_CHANGE_STATUS": "Αλλαγή κατάστασης",
    "HEADER_OT_COIN_BALANCE": "Υπόλοιπο OT Coin",
    "HEADER_ALT_USER": "Χρήστης",
    "STATUS_BUSY": "Απασχολημένος",
    "STATUS_AWAY": "Απών",
    "STATUS_OFFLINE": "Εκτός σύνδεσης",
    "STATUS_INVISIBLE": "Αόρατος",
    "NETWORK_CHECKING_CONNECTION": "Έλεγχος σύνδεσης...",
    "NETWORK_ONLINE_LATENCY": "Σε σύνδεση (καθυστέρηση: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Δίκτυο: Καλό (πατήστε για ping)",
    "CHAT_TARGET_ALT": "Στόχος συνομιλίας",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Αναζήτηση...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Άνοιγμα εικόνας προφίλ του/της {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Πεδίο μηνύματος",
    "CHAT_TOGGLE_VIEW_ARIA": "Εναλλαγή προβολής",
    "CHAT_ADD_USER_ARIA": "Προσθήκη χρήστη",
    "CHAT_ATTACH_ARIA": "Επισύναψη",
    "CHAT_MIC_ARIA": "Μικρόφωνο",
    "CHAT_SEND_ARIA": "Αποστολή",
    "CHAT_SEARCH_ARIA": "Αναζήτηση",
    "CHAT_OPEN_SEARCH_ARIA": "Άνοιγμα αναζήτησης",
    "CHAT_CLOSE_SEARCH_ARIA": "Κλείσιμο αναζήτησης",
    "CHAT_ATTACHMENT_ALT": "Συνημμένο",
    "CHAT_PREVIEW_ALT": "Προεπισκόπηση",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Αφαίρεση συνημμένου",
    "CHAT_REPLYING_TO": "Απάντηση σε",
    "CHAT_CANCEL_REPLY_ARIA": "Ακύρωση απάντησης",
    "CHAT_UPLOADING": "Μεταφόρτωση...",
    "CHAT_LOADING_CHATS": "Φόρτωση συνομιλιών...",
    "CHAT_SEND_FAILED": "Η αποστολή απέτυχε",
    "CHAT_SEND_FAILED_RETRY": "Η αποστολή απέτυχε. Παρακαλώ δοκιμάστε ξανά.",
    "CHAT_RETRY": "Επανάληψη",
    "CHAT_EDITED": "επεξεργάστηκε",
    "CHAT_TYPING": "Πληκτρολογεί",
    "CHAT_LOADING": "Φόρτωση",
    "CHAT_PENDING_INVITATION": "Πρόσκληση σε εκκρεμότητα",
    "CHAT_PENDING_INVITATION_MIN": "{count} λεπτά πρόσκληση σε εκκρεμότητα",
    "CHAT_PENDING_INVITATION_HR": "{count} ώρες πρόσκληση σε εκκρεμότητα",
    "CHAT_PENDING_INVITATION_DAY": "{count} ημέρες πρόσκληση σε εκκρεμότητα",
    "CHAT_WAITING_FOR_YOU": "{label} - Σε αναμονή για εσάς",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Εκκρεμεί αποδοχή",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Η πρόσβαση στο μικρόφωνο απορρίφθηκε.",
    "CHAT_UPLOAD_FAILED": "Η μεταφόρτωση απέτυχε: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Η μεταφόρτωση απαιτεί σύνδεση στο διαδίκτυο. Παρακαλώ δοκιμάστε ξανά όταν είστε σε σύνδεση.",
    "CHAT_ERROR_AUTH": "Σφάλμα ελέγχου ταυτότητας",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Λείπει όνομα αρχείου ή content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Λείπει conversation_id ή target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Λείπει conversation_id για μεταφόρτωση εκτός avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Μη έγκυρο avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Ο πελάτης υπηρεσίας Supabase δεν είναι διαθέσιμος",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Η επιβεβαίωση ανάγνωσης avatar ισχύει μόνο στο πλαίσιο συνομιλίας συμβούλου",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Το μήνυμα ροής avatar δεν βρέθηκε ή δεν είναι κατάλληλο για επιβεβαίωση ανάγνωσης",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Αποτυχία οριστικοποίησης του μηνύματος avatar ως αναγνωσμένου",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 συνημμένο",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} συνημμένα",
    "CHAT_VOICE_NOTE": "Φωνητική σημείωση",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Η συνομιλία δεν είναι διαθέσιμη. Αυτός ο χρήστης σας έχει αποκλείσει.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Η συνομιλία δεν είναι διαθέσιμη. Έχετε αποκλείσει αυτόν τον χρήστη.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Η πρόσβαση στον λογαριασμό έχει αποκλειστεί από την πολιτική.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Η συνομιλία δεν είναι διαθέσιμη. Αυτός ο λογαριασμός έχει αποκλειστεί οριστικά από τον User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Η συνομιλία δεν είναι διαθέσιμη. Είναι ενεργός αμοιβαίος αποκλεισμός.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Η συνομιλία δεν είναι διαθέσιμη λόγω πολιτικής αποκλεισμού.",
    "MESSAGE_PREVIEW_PHOTO": "Φωτογραφία",
    "MESSAGE_PREVIEW_VOICE": "Φωνητικό μήνυμα",
    "MESSAGE_PREVIEW_VIDEO": "Βίντεο",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Αρχείο",
    "MESSAGE_PREVIEW_MESSAGE": "Μήνυμα",
    "MESSAGE_PREVIEW_SYSTEM": "Μήνυμα συστήματος",
    "MESSAGE_PREVIEW_NEW": "Νέο μήνυμα",
    "MESSAGE_UNKNOWN_FILE": "Άγνωστο αρχείο",
    "MESSAGE_AUDIO_ATTACHMENT": "Συνημμένο ήχου",
    "MESSAGE_FILE_ATTACHMENT": "Συνημμένο",
    "BANNER_INVITED_BY": "προσκλήθηκε από {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Αποτελέσματα αναζήτησης",
    "SEARCH_QUERY_LABEL": "Ερώτημα:",
    "SEARCH_LOADING_VISIBILITY": "Φόρτωση ορατότητας αναζήτησης...",
    "SEARCH_NO_RESULTS": "Δεν βρέθηκε αποτέλεσμα στο τρέχον εύρος αναζήτησης.",
    "SHARE_WITH_COLLABRA": "Κοινή χρήση με το Collabra",
    "SHARE_SEND_TO": "Αποστολή σε",
    "SHARE_SELECT_ONE_BANNER": "Επιλέξτε ένα μπάνερ",
    "SHARE_BANNER_LIST_ARIA": "Λίστα μπάνερ",
    "SHARE_NO_MATCHING_BANNER": "Δεν υπάρχει αντίστοιχο μπάνερ",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Προσθέστε σχόλιο...",
    "SHARE_RECENT_CHATS": "Πρόσφατες συνομιλίες",
    "SHARE_LEFT_LIST": "Αριστερή λίστα",
    "SHARE_RIGHT_LIST": "Δεξιά λίστα",
    "SHARE_UNTITLED_BANNER": "Μπάνερ χωρίς τίτλο",
    "SHARE_SHARED_CONTENT": "Κοινόχρηστο περιεχόμενο",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Δεν ήταν δυνατό να ανοιχτεί το κοινόχρηστο περιεχόμενο.",
    "SHARE_OPEN_BANNER_FAILED": "Δεν ήταν δυνατό να ανοίξει το επιλεγμένο μπάνερ.",
    "SHARE_ONE_PHOTO_SELECTED": "Επιλέχθηκε 1 φωτογραφία",
    "SHARE_MANY_PHOTOS_SELECTED": "Επιλέχθηκαν {count} φωτογραφίες",
    "SHARE_ONE_FILE_SELECTED": "Επιλέχθηκε 1 αρχείο",
    "SHARE_MANY_FILES_SELECTED": "Επιλέχθηκαν {count} αρχεία",
    "FORWARD_MESSAGE_TITLE": "Προώθηση μηνύματος",
    "FORWARD_SELECT_RECIPIENTS": "Επιλέξτε παραλήπτες",
    "FORWARD_NO_OTHER_BANNER": "Δεν υπάρχει άλλο διαθέσιμο μπάνερ.",
    "FORWARD_SEND_TO_COUNT": "Αποστολή σε {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Επιλέξτε τουλάχιστον ένα μπάνερ.",
    "FORWARD_FAILED_DEFAULT": "Η προώθηση απέτυχε. Παρακαλώ δοκιμάστε ξανά.",
    "FORWARD_PARTIAL_SENT": "Στάλθηκαν {count}. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Το μήνυμα προέλευσης δεν βρέθηκε για προώθηση",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Αυτό το μήνυμα δεν έχει ακόμη περιεχόμενο που μπορεί να προωθηθεί",
    "FORWARD_DESTINATION_MISSING": "Λείπει ο προορισμός προώθησης",
    "FORWARD_MESSAGE_PREVIEW": "Προωθημένο μήνυμα",
    "MENU_PASTE": "Επικόλληση",
    "MENU_COPY": "Αντιγραφή",
    "MENU_REPLY": "Απάντηση",
    "MENU_FORWARD": "Προώθηση",
    "MENU_REMOVE_INVITATION": "Αφαίρεση πρόσκλησης",
    "MENU_REMOVE_FROM_LIST": "Αφαίρεση από τη λίστα",
    "MENU_GOODBYE_GUEST": "Αντίο επισκέπτη",
    "MENU_ADD_TO_LIST": "Προσθήκη στη λίστα",
    "MENU_REJECT_INVITATION": "Απόρριψη πρόσκλησης",
    "MENU_FRONTEND_VERSION": "Έκδοση frontend",
    "MENU_BANNER_HEADER": "Μπάνερ - {zone}",
    "MENU_BANNER_INFO": "Πληροφορίες μπάνερ: {title}",
    "MENU_MESSAGE_BUBBLE": "Φούσκα μηνύματος",
    "MENU_CHAT_CANVAS_HEADER": "Καμβάς συνομιλίας - {zone}",
    "MENU_CANVAS_INFO": "Πληροφορίες καμβά",
    "MENU_CHAT_CANVAS_SUBLABEL": "Περιοχή συνομιλίας / τρέχουσα επιφάνεια συνομιλίας",
    "MENU_INPUT_AREA_HEADER": "Περιοχή εισαγωγής - {zone}",
    "MENU_INPUT_AREA_INFO": "Πληροφορίες περιοχής εισαγωγής: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Κάτω επιφάνεια πληκτρολόγησης και εργαλείων ενεργειών",
    "MENU_HEADER": "Κεφαλίδα - {zone}",
    "MENU_HEADER_INFO": "Πληροφορίες κεφαλίδας: {title}",
    "MENU_HEADER_DESCRIPTION": "Επάνω πλοήγηση και στοιχεία ελέγχου σελίδας",
    "MENU_ZONE_HEADER": "Ζώνη - {zone}",
    "MENU_ZONE_SPACE_INFO": "Πληροφορίες χώρου ζώνης",
    "MENU_EMPTY_LIST_SURFACE": "Κενή επιφάνεια/λίστα",
    "MENU_BLOCK": "Αποκλεισμός",
    "MENU_UNBLOCK": "Κατάργηση αποκλεισμού",
    "MENU_HIDE_IN_SEARCH": "Απόκρυψη στην αναζήτηση",
    "MENU_UNHIDE_IN_SEARCH": "Εμφάνιση στην αναζήτηση",
    "MENU_VISIBLE_IN_SEARCH": "Ορατό στην αναζήτηση",
    "MENU_HIDDEN_IN_SEARCH": "Κρυφό στην αναζήτηση",
    "MENU_VISIBLE_IN_USER_LIST": "Ορατό στη λίστα χρηστών",
    "MENU_HIDDEN_IN_USER_LIST": "Κρυφό στη λίστα χρηστών",
    "MENU_NOT_BLOCKED": "Δεν είναι αποκλεισμένο",
    "MENU_BLOCKED": "Αποκλεισμένο",
    "MENU_FRONTEND_VERSION_LOADING": "Φόρτωση...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Φόρτωση τιμής ανά μπάνερ από το backend. Καμία επιλογή δεν επισημαίνεται ως ενεργή μέχρι να φτάσει η απάντηση της βάσης δεδομένων.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Δεν ήταν δυνατή η φόρτωση της τιμής backend. Δεν εμφανίζεται αξιόπιστη ενεργή επιλογή.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Η ρητή τιμή ανά μπάνερ στη βάση δεδομένων είναι {overrideVersion}. Η καθολική προεπιλεγμένη τιμή είναι {globalDefaultVersion}. Ο χρήστης-στόχος πρέπει να ανανεώσει πλήρως ή να ανοίξει ξανά την εφαρμογή για να εφαρμοστεί το bootstrap εκκίνησης.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Δεν έχει αποθηκευτεί ρητή τιμή ανά μπάνερ στη βάση δεδομένων. Το FeV2.0.0 είναι ενεργό από προεπιλογή. Η καθολική προεπιλεγμένη τιμή είναι {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Η ρητή τιμή ανά μπάνερ γίνεται ενεργή μετά την πλήρη επαναφόρτωση της εφαρμογής-στόχου",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Δεν έχει αποθηκευτεί ρητή τιμή ανά μπάνερ· αυτή είναι η προεπιλεγμένη ατομική κατάσταση FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Αυτή η επιλογή είναι επίσης ίση με την τρέχουσα καθολική προεπιλογή",
    "MENU_DELETE_PERMANENT_CONFIRM": "Να διαγραφεί οριστικά το {target} από τη βάση δεδομένων; Αυτό καταργεί τον λογαριασμό, το ιστορικό συνομιλιών, τις εξαρτήσεις και επιβάλλει νέα διαδρομή πρόσκλησης για μελλοντική επανένταξη.",
    "MENU_DELETE_PERMANENTLY": "Οριστική διαγραφή",
    "MENU_REFRESH_PAGE": "Ανανέωση σελίδας",
    "MENU_LOG_OFF": "Αποσύνδεση",
    "MENU_HARD_RELOAD": "Σκληρή επαναφόρτωση",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Email (διαχειριστής)",
    "AUTH_PASSWORD_PLACEHOLDER": "Κωδικός πρόσβασης",
    "AUTH_CONNECTING": "Σύνδεση...",
    "AUTH_SIGNING_OUT": "Αποσύνδεση...",
    "AUTH_BACK_TO_LOGIN": "Επιστροφή στη σύνδεση",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Μη έγκυρη απόκριση διακομιστή: Δεν βρέθηκε token.",
    "AUTH_LOGIN_FAILED": "Η σύνδεση απέτυχε",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Οι κωδικοί πρόσβασης δεν ταιριάζουν.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Οι κωδικοί πρόσβασης δεν ταιριάζουν!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Οι κωδικοί πρόσβασης πρέπει να ταιριάζουν ακριβώς.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Νέος κωδικός πρόσβασης",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Επιβεβαίωση κωδικού πρόσβασης",
    "AUTH_CHANGE_PASSWORD": "Αλλαγή κωδικού πρόσβασης",
    "AUTH_SAVING_PASSWORD": "Αποθήκευση...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Ο κωδικός πρόσβασης ενημερώθηκε με επιτυχία.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Δεν είναι δυνατή η αλλαγή κωδικού πρόσβασης αυτήν τη στιγμή.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Πρέπει να είστε συνδεδεμένοι για να αλλάξετε τον κωδικό πρόσβασής σας.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Εναλλαγή ορατότητας νέου κωδικού πρόσβασης",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Εναλλαγή ορατότητας επιβεβαίωσης κωδικού πρόσβασης",
    "REGISTER_TITLE": "Ολοκλήρωση εγγραφής",
    "REGISTER_SUBTITLE": "Παρακαλώ ορίστε τον κωδικό πρόσβασής σας χειροκίνητα.",
    "REGISTER_CREATING_ACCOUNT": "Δημιουργία λογαριασμού...",
    "REGISTER_FINISH_SETUP": "Ολοκλήρωση ρύθμισης",
    "REGISTER_FAILED_SET_PASSWORD": "Αποτυχία ορισμού κωδικού πρόσβασης",
    "INVITE_EMAIL_INSTRUCTION": "Παρακαλώ εισαγάγετε το email του προσκεκλημένου (μορφή: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Πρόσκληση",
    "INVITE_EMAIL_REQUIRED": "Παρακαλώ εισαγάγετε το email του προσκεκλημένου.",
    "INVITE_EMAIL_INVALID": "Μη έγκυρη μορφή email. Παρακαλώ χρησιμοποιήστε: user@example.com",
    "PENDING_INVITATION_TITLE": "Πρόσκληση σε εκκρεμότητα",
    "PENDING_INVITATION_REMOVE_QUESTION": "Να αφαιρεθεί αυτή η εκκρεμής πρόσκληση από τη βάση δεδομένων;",
    "PENDING_INVITATION_KEEP": "Διατήρηση πρόσκλησης",
    "PENDING_INVITATION_REMOVAL_FAILED": "Η αφαίρεση απέτυχε.",
    "REMOVE_FROM_LIST_TITLE": "Αφαίρεση από τη λίστα",
    "REMOVE_FROM_LIST_WARNING": "Να αφαιρεθεί τώρα αυτός ο χρήστης και από τις δύο λίστες; Η πρόσβαση στη συνομιλία θα διακοπεί αμέσως. Η μόνη διαδρομή επιστροφής είναι μια νέα πρόσκληση.",
    "REMOVE_FROM_LIST_KEEP": "Διατήρηση χρήστη στη λίστα",
    "REMOVE_FROM_LIST_FAILED": "Η αφαίρεση από τη λίστα απέτυχε.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Ρύθμιση και ζωντανή κατάσταση",
    "PERMISSION_DIALOG_ARIA": "Ρύθμιση και ζωντανή κατάσταση",
    "PERMISSION_TRIGGER_ARIA": "Ενεργοποιητής αναδυόμενου ρυθμίσεων",
    "PERMISSION_CLOSE_ARIA": "Κλείσιμο αναδυόμενου δικαιωμάτων",
    "PERMISSION_LIVE_STATUS": "Ζωντανή κατάσταση",
    "PERMISSION_SYSTEM_PERMISSION": "Δικαίωμα συστήματος",
    "PERMISSION_APP_PUSH": "Push εφαρμογής",
    "PERMISSION_LOCATION_PERMISSION": "Δικαίωμα τοποθεσίας",
    "PERMISSION_APP_LOCATION": "Τοποθεσία εφαρμογής",
    "PERMISSION_CONTROLS": "Στοιχεία ελέγχου δικαιωμάτων",
    "PERMISSION_PUSH_NOTIFICATIONS": "Ειδοποιήσεις push",
    "PERMISSION_LOCATION_ACCESS": "Πρόσβαση τοποθεσίας",
    "PERMISSION_IN_APP_SETTINGS": "Ρυθμίσεις εντός εφαρμογής",
    "PERMISSION_ALERT_SOUND": "Ήχος ειδοποίησης",
    "PERMISSION_APP_BADGE": "Σήμα εφαρμογής",
    "PERMISSION_PASSWORD_SETTINGS": "Ρυθμίσεις κωδικού πρόσβασης",
    "PERMISSION_NAVIGATION_STATUS": "Κατάσταση πλοήγησης",
    "PERMISSION_SELECTED_ZONE": "Επιλεγμένη ζώνη",
    "PERMISSION_STAGED_CHAT_BANNER": "Προετοιμασμένο μπάνερ συνομιλίας",
    "PERMISSION_CANVAS_CONTENT": "Περιεχόμενο καμβά",
    "PERMISSION_YOUR_DEVICES": "Οι συσκευές σας ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Ανανέωση λίστας συσκευών",
    "PERMISSION_REFRESH_LIST": "Ανανέωση λίστας",
    "PERMISSION_NO_REGISTERED_DEVICES": "Δεν βρέθηκαν καταχωρημένες συσκευές.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Αλλαγή μεγέθους αναδυόμενου ρυθμίσεων",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Εναλλαγή ειδοποιήσεων push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Εναλλαγή πρόσβασης τοποθεσίας",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Εναλλαγή ήχου ειδοποίησης",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Εναλλαγή σήματος εφαρμογής",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Εναλλαγή ορατότητας προφίλ",
    "PERMISSION_OFF_IN_V1": "Ανενεργό στην v1",
    "PERMISSION_CHAT": "Συνομιλία",
    "PERMISSION_BANNER_LIST": "Λίστα μπάνερ",
    "PERMISSION_PUSH_DISABLED_V1": "Οι ειδοποιήσεις push είναι απενεργοποιημένες για την έκδοση v1 του Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Οι ειδοποιήσεις push είναι ενεργές για αυτήν τη συσκευή.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Οι ειδοποιήσεις συστήματος είναι αποκλεισμένες. Πατήστε για να ανοίξετε τη βοήθεια ρυθμίσεων.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Ενεργοποιήστε για να βελτιώσετε την αξιοπιστία παράδοσης.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Για να απενεργοποιήσετε τις ειδοποιήσεις συστήματος, ανοίξτε τις ρυθμίσεις ειδοποιήσεων του προγράμματος περιήγησης/ιστότοπου και ορίστε αυτόν τον ιστότοπο σε Αποκλεισμός.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Για να αλλάξετε το δικαίωμα ειδοποιήσεων συστήματος, ανοίξτε τις ρυθμίσεις ειδοποιήσεων του προγράμματος περιήγησης/ιστότοπου και ορίστε αυτόν τον ιστότοπο σε Αποδοχή.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Η πρόσβαση τοποθεσίας είναι ενεργή για ταξινόμηση LCAC βάσει απόστασης και τοποθέτηση στον χάρτη.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Το API τοποθεσίας δεν υποστηρίζεται σε αυτό το περιβάλλον.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Η πρόσβαση τοποθεσίας είναι αποκλεισμένη. Πατήστε για να ανοίξετε τη βοήθεια ρυθμίσεων.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Ενεργοποιήστε για να επιτρέψετε ακριβή ταξινόμηση LCAC βάσει απόστασης και τοποθέτηση στον χάρτη εντός εφαρμογής.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Η πρόσβαση τοποθεσίας δεν υποστηρίζεται σε αυτό το περιβάλλον.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Για να απενεργοποιήσετε την πρόσβαση τοποθεσίας, ανοίξτε τις ρυθμίσεις τοποθεσίας του προγράμματος περιήγησης/ιστότοπου και ορίστε αυτόν τον ιστότοπο σε Αποκλεισμός.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Για να ενεργοποιήσετε την πρόσβαση τοποθεσίας για ταξινόμηση βάσει απόστασης και τοποθέτηση στον χάρτη εντός εφαρμογής, ανοίξτε τις ρυθμίσεις τοποθεσίας του προγράμματος περιήγησης/ιστότοπου και ορίστε αυτόν τον ιστότοπο σε Αποδοχή.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Δεν είναι δυνατή η φόρτωση των καταχωρημένων συσκευών αυτήν τη στιγμή.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Φόρτωση UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Φόρτωση Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Φόρτωση backend...",
    "RUNTIME_LOADING": "Φόρτωση...",
    "RUNTIME_LOADING_FROM_DATABASE": "Φόρτωση από τη βάση δεδομένων...",
    "RUNTIME_BACKEND_CONNECTED": "Το backend συνδέθηκε",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Ενεργό εφεδρικό από cache",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Ενεργή προεπιλεγμένη εφεδρεία",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Ενεργές προεπιλεγμένες εφεδρικές τιμές",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Αποθήκευση μέσω backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Αποθηκεύτηκε στην υπηρεσία backend",
    "RUNTIME_SAVE_FAILED": "Η αποθήκευση απέτυχε",
    "RUNTIME_LOAD_FAILED": "Η φόρτωση απέτυχε",
    "RUNTIME_CONNECTED": "Συνδεδεμένο",
    "RUNTIME_LOGIN_REQUIRED": "Απαιτείται σύνδεση",
    "RUNTIME_SAVED": "Αποθηκεύτηκε",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "Το UI είναι έτοιμο - το runtime εκκρεμεί",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Η προστατευμένη υπηρεσία επιλογέα backend απέρριψε ή δεν μπόρεσε να αποθηκεύσει την ζητούμενη επιλογή μοντέλου.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Η προστατευμένη υπηρεσία επιλογέα backend απέρριψε ή δεν μπόρεσε να αποθηκεύσει την ζητούμενη αλλαγή δρομολόγησης WF1.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Ο επιλογέας διαβάζει πλέον την ενεργή διαμόρφωση, τη δρομολόγηση Qwen και τις επιτρεπόμενες επιλογές από την προστατευμένη υπηρεσία backend.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Η υπηρεσία επιλογέα backend δεν είναι διαθέσιμη αυτήν τη στιγμή, οπότε χρησιμοποιείται η τελευταία κατάσταση επιλογέα από την cache.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Οι προεπιλεγμένες τιμές επιλογέα είναι ενεργές επειδή δεν μπόρεσε να φορτωθεί κατάσταση backend ή cache.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Η προστατευμένη υπηρεσία επιλογέα backend ενημέρωσε την ενεργή διαμόρφωση δρομολόγησης WF1 και ανανέωσε την cache του runtime domain.",
    "FRONTEND_VERSION_TITLE": "Έκδοση frontend",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Αυτός ο επιλογέας ελέγχει την ενεργή έκδοση frontend για όλους τους χρήστες. Το FeV2.0.0 είναι ενεργό.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Αυτός ο επιλογέας διαβάζει την ενεργή έκδοση frontend από το config_domain_registry. Το runtime επιλύεται σε FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Δεν ήταν δυνατή η φόρτωση της διαμόρφωσης έκδοσης frontend από το backend, οπότε η κωδικοποιημένη προεπιλογή FeV2.0.0 παραμένει ενεργή μέχρι το bootstrap εκκίνησης να διαβάσει ξανά την προστατευμένη υπηρεσία.",
    "FRONTEND_VERSION_HELPER_SAVED": "Η ενεργή έκδοση frontend αποθηκεύτηκε στο config_domain_registry. Μια πλήρης ανανέωση ή η επόμενη φόρτωση της εφαρμογής εφαρμόζει την τιμή runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Η υπηρεσία ελέγχου έκδοσης frontend του backend δεν μπόρεσε να αποθηκεύσει την ζητούμενη καθολική έκδοση.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Ενεργή έκδοση frontend.",
    "CHAT_DELETE_WINDOW_TITLE": "Παράθυρο διαγραφής συνομιλίας",
    "CHAT_DELETE_HELPER": "Αυτή η τιμή ελέγχει το παράθυρο διαθεσιμότητας Διαγραφή για όλους σε δευτερόλεπτα. Ο backend guard αλλάζει αμέσως μετά την αποθήκευση. Η ορατότητα της φούσκας αλλάζει μετά από πλήρη ανανέωση ή την επόμενη φόρτωση της εφαρμογής.",
    "CHAT_DELETE_HELPER_FALLBACK": "Δεν ήταν δυνατή η φόρτωση της υπηρεσίας ελέγχου διαγραφής συνομιλίας του backend, οπότε η κωδικοποιημένη προεπιλογή παραμένει ενεργή μέχρι το bootstrap εκκίνησης να διαβάσει ξανά την προστατευμένη υπηρεσία.",
    "CHAT_DELETE_HELPER_SAVED": "Το παράθυρο διαθεσιμότητας Διαγραφή για όλους αποθηκεύτηκε στο config_domain_registry. Ο backend guard αλλάζει αμέσως. Η ορατότητα της φούσκας αλλάζει μετά από πλήρη ανανέωση ή την επόμενη φόρτωση της εφαρμογής.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Η υπηρεσία ελέγχου διαγραφής συνομιλίας του backend δεν μπόρεσε να αποθηκεύσει την ζητούμενη τιμή παραθύρου.",
    "CHAT_DELETE_WINDOW_LABEL": "Παράθυρο Διαγραφή για όλους",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} δευτ.",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Αποθηκεύστε την τιμή σε ακέραια δευτερόλεπτα. Η τρέχουσα τιμή παραγωγής είναι 86400 δευτερόλεπτα = 1 ημέρα.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Δευτερόλεπτα παραθύρου",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Εισαγάγετε ακέραιο αριθμό μεγαλύτερο ή ίσο με 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Αποθήκευση παραθύρου διαγραφής",
    "GUEST_BANNER_CONTROL_TITLE": "Banner επισκέπτη",
    "GUEST_BANNER_CONTROL_LABEL": "Συνομιλία QR επισκέπτη",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Εμφάνιση banner επισκέπτη για όλους τους χρήστες",
    "GUEST_BANNER_CONTROL_HELPER": "Ελέγχει το σταθερό banner επισκέπτη και τη διάρκεια ζωής του διακριτικού QR σε εκκρεμότητα.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Η τοπική εναλλακτική είναι ενεργή για τα στοιχεία ελέγχου του banner επισκέπτη.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Τα στοιχεία ελέγχου του banner επισκέπτη αποθηκεύτηκαν.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Δεν ήταν δυνατή η αποθήκευση των στοιχείων ελέγχου του banner επισκέπτη.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "Ανακλήθηκαν {count} περίοδοι λειτουργίας επισκέπτη.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "TTL QR σε εκκρεμότητα (λεπτά)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "Τρέχον TTL QR σε εκκρεμότητα: {count} λεπτά.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Εισαγάγετε έναν θετικό ακέραιο αριθμό λεπτών.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Αποθήκευση banner επισκέπτη",
    "GUEST_QR_LOADING": "Προετοιμασία QR επισκέπτη...",
    "GUEST_QR_READY": "Σαρώστε για να ανοίξετε την προσωρινή συνομιλία επισκέπτη.",
    "GUEST_QR_ALT": "Κωδικός QR συνομιλίας επισκέπτη",
    "GUEST_QR_LOAD_FAILED": "Δεν ήταν δυνατή η προετοιμασία του QR επισκέπτη.",
    "GUEST_SESSION_ACTIVE": "Ο επισκέπτης είναι συνδεδεμένος.",
    "GUEST_PUBLIC_TITLE": "Συνομιλία επισκέπτη",
    "GUEST_PUBLIC_CONNECTING": "Σύνδεση...",
    "GUEST_PUBLIC_CONNECTED": "Συνδέθηκε",
    "GUEST_PUBLIC_UNAVAILABLE": "Αυτός ο σύνδεσμος επισκέπτη δεν είναι διαθέσιμος.",
    "GUEST_PUBLIC_SEND_FAILED": "Δεν ήταν δυνατή η αποστολή του μηνύματος.",
    "UI_TEXTS_RUNTIME_TITLE": "Χρόνος εκτέλεσης γλώσσας περιβάλλοντος εργασίας χρήστη",
    "UI_TEXTS_RUNTIME_BACKEND": "Ο χρόνος εκτέλεσης γλώσσας περιβάλλοντος εργασίας χρήστη διαβάζει από την προστατευμένη υπηρεσία υποστήριξης. Οι αλλαγές ισχύουν στην επόμενη πλήρη φόρτωση της εφαρμογής.",
    "UI_TEXTS_RUNTIME_CACHED": "Η υπηρεσία χρόνου εκτέλεσης γλώσσας περιβάλλοντος εργασίας χρήστη υποστήριξης δεν είναι διαθέσιμη αυτήν τη στιγμή, επομένως οι προεπιλογές της κρυφής μνήμης ή οι τοπικές προεπιλογές είναι ενεργές.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "Οι προεπιλογές χρόνου εκτέλεσης γλώσσας περιβάλλοντος εργασίας χρήστη είναι ενεργές επειδή δεν ήταν δυνατή η φόρτωση καμίας κατάστασης υποστήριξης ή κρυφής μνήμης.",
    "UI_TEXTS_RUNTIME_SAVED": "Ο έλεγχος χρόνου εκτέλεσης γλώσσας περιβάλλοντος εργασίας χρήστη αποθηκεύτηκε. Απαιτείται πλήρης ανανέωση ή επόμενη φόρτωση της εφαρμογής για να λάβουν οι χρήστες τη νέα πύλη γλώσσας.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Η προστατευμένη υπηρεσία υποστήριξης δεν μπόρεσε να αποθηκεύσει την αιτούμενη αλλαγή χρόνου εκτέλεσης γλώσσας περιβάλλοντος εργασίας χρήστη.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Εφαρμογή γλώσσας συσκευής",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Ενεργοποίηση γλωσσών περιβάλλοντος εργασίας χρήστη χρόνου εκτέλεσης",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Οι χρήστες μπορούν να λαμβάνουν ωφέλιμα φορτία κειμένου περιβάλλοντος εργασίας χρήστη για την αποθηκευμένη γλώσσα ή τη γλώσσα της συσκευής τους.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Όλοι οι χρήστες αναγκάζονται να χρησιμοποιούν αγγλικό κείμενο περιβάλλοντος εργασίας χρήστη και η γλώσσα της συσκευής αγνοείται.",
    "PROFILE_VISIBILITY_TITLE": "Ορατότητα προφίλ",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Πρέπει να είστε συνδεδεμένοι για να διαχειριστείτε την ορατότητα λογαριασμού.",
    "PROFILE_VISIBILITY_HELPER": "Αυτός ο διακόπτης ενημερώνει μόνο την κατάσταση ορατότητας του λογαριασμού σας. Η δυνατότητα ανακάλυψης και η συμπεριφορά λίστας μπάνερ παραμένουν αμετάβλητες σε αυτήν τη φάση.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Δεν ήταν δυνατή η φόρτωση της ορατότητας προφίλ αυτήν τη στιγμή.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Δεν ήταν δυνατή η ενημέρωση της ορατότητας προφίλ αυτήν τη στιγμή.",
    "PROFILE_VISIBILITY_SAVED": "Η ορατότητα του λογαριασμού σας είναι τώρα {visibility}. Οι σημαίες δυνατότητας ανακάλυψης παραμένουν αμετάβλητες σε αυτήν τη φάση.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Δημόσιος λογαριασμός",
    "PROFILE_VISIBILITY_STORED": "Αποθηκευμένη ορατότητα",
    "WF1_MODEL_CONTROL_TITLE": "Έλεγχος μοντέλου WF1",
    "WF1_ENABLE_TRANSLATION": "Ενεργοποίηση μετάφρασης / Pivot",
    "WF1_TRANSLATION_ACTIVE": "Η μετάφραση AI είναι ενεργή.",
    "WF1_TRANSLATION_INACTIVE": "Το WF1 συνεχίζει να λειτουργεί, αλλά το κείμενο προέλευσης αντιγράφεται και το pivot επισημαίνεται ως ανενεργό.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Ενεργή θέση runtime",
    "WF1_ALLOW_SAME_LANGUAGE": "Να επιτρέπεται AI για ζεύγη ίδιας γλώσσας",
    "WF1_SAME_LANGUAGE_ACTIVE": "Τα ζεύγη ίδιας γλώσσας ακολουθούν την κανονική δρομολόγηση WF1.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Τα ζεύγη ίδιας γλώσσας παρακάμπτουν το AI και αποθηκεύουν ενεργή γλώσσα No Pivot.",
    "WF1_QWEN_ROUTING": "Δρομολόγηση ζευγών Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Οι γλώσσες που είναι επιλεγμένες παρακάτω χρησιμοποιούν Qwen-Max όταν το ζεύγος είναι είτε η ίδια επιλεγμένη γλώσσα, είτε μια επιλεγμένη γλώσσα με αγγλικά, είτε δύο επιλεγμένες μη αγγλικές γλώσσες. Διαφορετικά, το επιλεγμένο κύριο μοντέλο παραμένει ενεργό.",
    "WF1_OPENROUTER_TEST_SLOT": "Θέση δοκιμής OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Θέση δοκιμής OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Μόνο δοκιμή ποιότητας",
    "WF1_OPENROUTER_HELPER": "Αυτή η θέση είναι επεξεργάσιμη μόνο για προσωρινές δοκιμές ποιότητας OpenRouter. Δεν αλλάζει την επιχειρησιακή διαδρομή δρομολόγησης ζευγών Qwen, εκτός αν αυτή η ίδια θέση γίνει το ενεργό μοντέλο.",
    "WF1_LABEL": "Ετικέτα",
    "WF1_PRODUCT": "Προϊόν",
    "WF1_MODEL": "Μοντέλο",
    "WF1_PROVIDER_OPENROUTER": "Πάροχος: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Θέση δοκιμής OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max μέσω OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Τιμή καταλόγου Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Τιμή καταλόγου OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Τιμή καταλόγου OpenRouter",
    "LANGUAGE_ENGLISH": "Αγγλικά",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Κινέζικα (απλοποιημένα)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Κινέζικα (παραδοσιακά)",
    "LANGUAGE_JAPANESE": "Ιαπωνικά",
    "LANGUAGE_KOREAN": "Κορεατικά",
    "LANGUAGE_PERSIAN": "Περσικά",
    "LANGUAGE_TURKISH_ISTANBUL": "Τουρκικά (Κωνσταντινούπολη)",
    "LANGUAGE_ARABIC": "Αραβικά",
    "LANGUAGE_FRENCH": "Γαλλικά",
    "LANGUAGE_GERMAN": "Γερμανικά",
    "LANGUAGE_SPANISH": "Ισπανικά",
    "LANGUAGE_PORTUGUESE": "Πορτογαλικά",
    "LANGUAGE_ITALIAN": "Ιταλικά",
    "LANGUAGE_RUSSIAN": "Ρωσικά",
    "LANGUAGE_DUTCH": "Ολλανδικά",
    "LANGUAGE_VIETNAMESE": "Βιετναμικά",
    "LANGUAGE_INDONESIAN": "Ινδονησιακά",
    "LANGUAGE_THAI": "Ταϊλανδικά",
    "LANGUAGE_MALAY": "Μαλαισιανά",
    "WF1_PRICING_CUSTOM": "Τιμολόγηση: προσαρμοσμένο μοντέλο θέσης - ελέγξτε την τρέχουσα τιμολόγηση OpenRouter",
    "WF1_SAVE_OPENROUTER_SLOT": "Αποθήκευση θέσης OpenRouter",
    "WF1_PRICING_LINE": "Είσοδος {input} - Έξοδος {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "Έλεγχος ορατότητας ζώνης",
    "ZONE_ENABLE": "Ενεργοποίηση {zone}",
    "ZONE_ENABLED_NOTE": "Το {zone} μπορεί να εμφανιστεί για επιτρεπόμενους ρόλους μετά την επόμενη φόρτωση της εφαρμογής.",
    "ZONE_DISABLED_NOTE": "Το {zone} αντιμετωπίζεται ως απόν για χρήστες που δεν είναι S_Admin μετά την επόμενη φόρτωση της εφαρμογής.",
    "ZONE_S_ADMIN_BYPASS": "Ο S_Admin παρακάμπτει αυτήν τη λίστα ρόλων και διατηρεί πάντα πρόσβαση.",
    "ZONE_ROLE_LOCKED": "Οι επιλογές ρόλων είναι προσωρινά κλειδωμένες όσο αυτή η ζώνη είναι απενεργοποιημένη και θα επιστρέψουν ακριβώς όπως αποθηκεύτηκαν όταν η ζώνη ενεργοποιηθεί ξανά.",
    "ZONE_LCAC_CONTROL": "Έλεγχος LCAC",
    "ZONE_RCAC_CONTROL": "Έλεγχος RCAC",
    "ZONE_LCAC_DESCRIPTION": "Ελέγχει την ύπαρξη της αριστερής δεσμευμένης ζώνης και τους ρόλους που μπορούν να τη βλέπουν.",
    "ZONE_RCAC_DESCRIPTION": "Ελέγχει την ύπαρξη της δεξιάς δεσμευμένης ζώνης και τους ρόλους που μπορούν να τη βλέπουν.",
    "ZONE_VISIBILITY_BACKEND": "Το bootstrap ορατότητας ζώνης διαβάζει πλέον από την προστατευμένη υπηρεσία backend. Οι αλλαγές εφαρμόζονται στην επόμενη φόρτωση της εφαρμογής.",
    "ZONE_VISIBILITY_CACHED": "Η υπηρεσία ορατότητας ζώνης backend δεν είναι διαθέσιμη αυτήν τη στιγμή, οπότε είναι ενεργές τιμές από cache ή τοπικές προεπιλογές.",
    "ZONE_VISIBILITY_DEFAULTS": "Οι προεπιλογές ορατότητας ζώνης είναι ενεργές επειδή δεν μπόρεσε να φορτωθεί κατάσταση backend ή cache.",
    "ZONE_VISIBILITY_SAVED": "Το bootstrap ορατότητας ζώνης αποθηκεύτηκε. Απαιτείται σκληρή επαναφόρτωση ή επόμενη φόρτωση εφαρμογής για εφαρμογή στο runtime.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Η προστατευμένη υπηρεσία backend δεν μπόρεσε να αποθηκεύσει την ζητούμενη αλλαγή ορατότητας ζώνης.",
    "ROLE_MEMBER": "Μέλος",
    "ROLE_STAFF": "Προσωπικό",
    "ROLE_ADMIN": "Διαχειριστής",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Ενεργοποιήστε τις ειδοποιήσεις για να λαμβάνετε νέα μηνύματα.",
    "MAIN_LOG_OUT": "Αποσύνδεση",
    "NOTIFICATION_NEW_MESSAGE": "Νέο μήνυμα",
    "NOTIFICATION_UNREAD_MESSAGE": "Έχετε ένα μη αναγνωσμένο μήνυμα.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Πλήρης προβολή",
    "MEDIA_AUDIO_ATTACHMENT": "Συνημμένο ήχου",
    "MEDIA_FILE_FALLBACK": "Αρχείο",
    "MEDIA_DOWNLOAD_READY": "Το συνημμένο είναι έτοιμο για λήψη",
    "MEDIA_TYPE_UNSUPPORTED": "Ο τύπος δεν υποστηρίζεται για πλήρη προβολή",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Προηγούμενη εικόνα",
    "MEDIA_NEXT_IMAGE_ARIA": "Επόμενη εικόνα",
    "MEDIA_OPEN_ORIGINAL": "Άνοιγμα πρωτοτύπου",
    "MEDIA_DOWNLOAD": "Λήψη",
    "MEDIA_CLOSE_ARIA": "Κλείσιμο",
    "MEDIA_PROFILE_PICTURE_ARIA": "Εικόνα προφίλ του/της {name}",
    "MEDIA_PROFILE_ALT": "Προφίλ του/της {name}",
    "MEDIA_UPLOAD_FAILED": "Η μεταφόρτωση απέτυχε",
    "MEDIA_BACKEND_TOKEN_ERROR": "Σφάλμα token backend",
    "MEDIA_UPLOAD_URL_MISSING": "Κρίσιμο: λείπει το URL μεταφόρτωσης στην απόκριση backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Λείπει token ελέγχου ταυτότητας για μεταφόρτωση συνομιλίας",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Το αίτημα token μεταφόρτωσης συνομιλίας απέτυχε",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Μη έγκυρη απόκριση μεταφόρτωσης συνομιλίας",
    "MEDIA_GCS_UPLOAD_FAILED": "Η μεταφόρτωση GCS απέτυχε",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Λείπει όνομα αρχείου ή contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Λείπει file_path",
    "BLOCK_NOTICE_TITLE": "Ειδοποίηση μόνιμου αποκλεισμού",
    "BLOCK_NOTICE_MESSAGE": "Ο λογαριασμός σας έχει ανασταλεί προσωρινά λόγω παραβίασης της πολιτικής.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Αν πιστεύετε ότι αυτό απαιτεί περαιτέρω ενέργεια, επικοινωνήστε με",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "μέσω email.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Άγνωστος χρήστης",
    "GENERAL_GUEST": "Επισκέπτης",
    "ADVISOR_FOR_CLIENT": "Σύμβουλος για {client_display_name}",
    "GUEST_FOR_CLIENT": "Επισκέπτης για {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Απαιτούνται token και κωδικός πρόσβασης",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Το σώμα του αιτήματος πρέπει να είναι JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Μη έγκυρο ή ληγμένο token πρόσκλησης",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Ο ορισμός κωδικού πρόσβασης απέτυχε: λείπει συνεδρία ή χρήστης",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Ο ορισμός κωδικού πρόσβασης απέτυχε κατά τη σύνδεση",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Η δημιουργία admin token απέτυχε",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Η σύνδεση απέτυχε: λείπει συνεδρία ή χρήστης",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Η εγγραφή ήταν επιτυχής. Ελέγξτε το email σας για επαλήθευση.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Άγνωστη αποτυχία εγγραφής",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Μη έγκυρη επεξεργασία token",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Απαιτείται access token",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Η προεπισκόπηση hash token απαιτεί υπόδειξη email από το URL ανακατεύθυνσης",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Δεν είναι δυνατή η επίλυση ταυτότητας για αυτό το token",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Μόνο ο User Zero μπορεί να έχει πρόσβαση στην υπηρεσία επιλογέα LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Μόνο ο User Zero μπορεί να έχει πρόσβαση στην υπηρεσία ελέγχου ορατότητας ζώνης.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Μόνο ο User Zero μπορεί να έχει πρόσβαση στην υπηρεσία ελέγχου έκδοσης frontend.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Μόνο ο User Zero μπορεί να ελέγξει την έκδοση frontend άλλου χρήστη.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Μόνο ο User Zero μπορεί να έχει πρόσβαση στην υπηρεσία ελέγχου διαγραφής συνομιλίας.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Μόνο ο Χρήστης Μηδέν μπορεί να έχει πρόσβαση στην υπηρεσία ελέγχου χρόνου εκτέλεσης γλώσσας περιβάλλοντος εργασίας χρήστη.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Μόνο ο User Zero μπορεί να διαγράψει οριστικά έναν λογαριασμό χρήστη.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Μη έγκυρο payload αιτήματος.",
    "API_ERROR_INTERNAL_SERVER": "Εσωτερικό σφάλμα διακομιστή",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Λείπει λειτουργία στο backend (απαιτείται επαναφόρτωση)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Μόνο DB RPC επιτρέπεται για μεταβάσεις delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Παρακαλώ περιμένετε πριν στείλετε άλλο μήνυμα.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Το μήνυμα στάλθηκε με επιτυχία.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Η υπηρεσία επικοινωνίας δεν είναι διαθέσιμη.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Η αποστολή μηνύματος απέτυχε.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Απαιτείται όνομα.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Το email δεν είναι έγκυρο.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Απαιτείται μήνυμα.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Απαιτείται payload επιλογέα.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Απαιτείται payload ορατότητας ζώνης.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Απαιτείται payload έκδοσης frontend.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Απαιτείται payload ελέγχου διαγραφής συνομιλίας.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Απαιτείται ωφέλιμο φορτίο ελέγχου χρόνου εκτέλεσης γλώσσας περιβάλλοντος εργασίας χρήστη.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Απαιτείται αναγνωριστικό πιστοποιημένου χρήστη.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Απαιτείται αναγνωριστικό πιστοποιημένου χρήστη-θεατή.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Απαιτείται αναγνωριστικό πιστοποιημένου χρήστη-ενεργούντα.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id απαιτείται.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id απαιτείται.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Απαιτείται λίστα owner_user_ids.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email απαιτείται.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by απαιτείται.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Το runtime αναζήτησης είναι απενεργοποιημένο από την καθολική έκδοση frontend.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Δεν επιτρέπεται να ακυρώσετε αυτήν την εκκρεμή πρόσκληση.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Αυτή η πρόσκληση δεν μπορεί πλέον να ακυρωθεί επειδή ο χρήστης είναι ήδη εγγεγραμμένος.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Η εκκρεμής πρόσκληση δεν βρέθηκε.",
    "INVITE_REPLY_ALREADY_MEMBER": "Συγχαρητήρια, ο φίλος σας ({invitee_email}) είναι ήδη εγγεγραμμένος σε αυτήν την εφαρμογή και είναι μέλος αυτού του χώρου εργασίας.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Υπάρχει εκκρεμής πρόσκληση για {invitee_email}, αλλά δεν ήταν δυνατή η ενεργοποίηση του email επανάληψης. Ελέγξτε τα αρχεία καταγραφής email.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Η εγγραφή πρόσκλησης δημιουργήθηκε για {invitee_email}, αλλά η παράδοση του email δεν μπόρεσε να επιβεβαιωθεί. Παρακαλώ δοκιμάστε ξανά αργότερα ή ελέγξτε τα αρχεία καταγραφής email.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Αποτυχία δημιουργίας εγγραφής πρόσκλησης. Παρακαλώ δοκιμάστε ξανά αργότερα.",
    "INVITE_REPLY_SYSTEM_ERROR": "Σφάλμα συστήματος κατά τη διαδικασία πρόσκλησης: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Σφάλμα διαμόρφωσης backend: λείπουν διαπιστευτήρια Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Σφάλμα διαμόρφωσης backend: μη έγκυρο URL Supabase",
    "CHAT_ERROR_ACCESS_DENIED": "Δεν επιτρέπεται η πρόσβαση",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Το περιεχόμενο δεν μπορεί να είναι κενό για μηνύματα κειμένου",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Δεν ήταν δυνατός ο προσδιορισμός του ID συνομιλίας",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Λείπει το πλαίσιο ελέγχου ταυτότητας RPC",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "Το RPC επέστρεψε μη έγκυρο payload μηνύματος",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Η εισαγωγή απέτυχε, δεν επιστράφηκαν δεδομένα",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "Το operations πρέπει να είναι λίστα",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Μη έγκυρο payload λειτουργίας",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Το operation_type δεν υποστηρίζεται",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id απαιτείται",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Το μήνυμα δεν βρέθηκε",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Η διαγραφή επιτρέπεται μόνο στο δικό σας μήνυμα",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Η Διαγραφή για όλους δεν είναι πλέον διαθέσιμη για αυτό το μήνυμα",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Η Διαγραφή για όλους απέτυχε",
    "API_ERROR_SERVER_CONFIGURATION": "Σφάλμα διαμόρφωσης διακομιστή",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Λείπει κεφαλίδα webhook secret",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Μη εξουσιοδοτημένη πηγή webhook",
    "API_ERROR_BACKEND_CONFIGURATION": "Σφάλμα διαμόρφωσης backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Σφάλμα χαρακτηριστικού module: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Αποτυχία πριν από τη διαγραφή της πρόσκλησης κατά την αφαίρεση του χρήστη auth σε αναμονή.",
    "CHAT_ERROR_DB": "Σφάλμα DB: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
