# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/en.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Main",
    "APP_TITLE": "OTMEGA AI Platform",
    "APP_SUBTITLE": "AI Advisor",
    "CHAT_PLACEHOLDER": "Type Your Message...",
    "CHAT_SEND_BUTTON": "Send",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Advisor can make mistakes, so double-check it.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "New Chat",
    "ICON_HISTORY": "History",
    "ICON_TEMPLATES": "Templates",
    "ICON_SETTINGS": "Settings",
    "ICON_USER_PROFILE": "User Profile",
    "ICON_QUICK_ACTIONS": "Quick Actions",
    "ICON_PINNED": "Pinned",
    "ICON_GALLERY": "Gallery",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Install App",
    "PWA_ANDROID_MSG": "Install this app on your device for a better experience and offline access.",
    "PWA_IOS_MSG": "To install this app on your iPhone/iPad:\n1. Tap the Share button below\n2. Select 'Add to Home Screen'",
    "PWA_BTN_INSTALL": "Install",
    "PWA_BTN_LATER": "Maybe Later",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Log in to the Advisor Network",
    "AUTH_HEADER_SIGNUP": "Create your Unified Account",
    "AUTH_HEADER_LOGIN_NETWORK": "Log in to the Advisor Network",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Create your Unified Account",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Login",
    "AUTH_BUTTON_SIGNUP": "Create Account",
    "AUTH_BUTTON_GOOGLE": "Continue with Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Forgot Password",
    "AUTH_BUTTON_SEND_RESET_LINK": "Send Reset Link",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Don't have an account? Sign up",
    "AUTH_PROMPT_LOGIN": "Already have an account? Log in",
    "AUTH_HELPER_TEXT_SIGNUP": "You are creating a unified account that you can use to access all advisors in this platform.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "You are creating a unified account that you can use to access all advisors in this platform.",
    "AUTH_HELPER_TEXT_LOGIN": "Use the same account (email/password or Google) that you used for other advisors in this network.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Use the same account (email/password or Google) that you used for other advisors in this network.",
    "AUTH_FORGOT_PASSWORD_LINK": "Forgot your password?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Reset Your Password",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Enter your email address and we'll send you a link to reset your password.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Email",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Logging you in...",
    "AUTH_STATUS_LOADING_SIGNUP": "Creating your account...",
    "AUTH_STATUS_LOADING_RESET": "Sending reset link...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Login successful! Reloading...",
    "AUTH_STATUS_SUCCESS_RESET": "Reset link sent successfully. Please check your email.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Password reset link sent successfully. Please check your email.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Invalid email or password.",
    "AUTH_ERROR_EMAIL_EXISTS": "An account with this email already exists in the advisor network.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "An account with this email already exists. Please log in. You are currently a member of:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "An account with this email already exists in the advisor network. Please close this window and use the 'Login' section with the same email and your previous password.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "You are currently a member of:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "Email and password are required.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Account created but failed to set up membership. Please contact support.",
    "AUTH_ERROR_DEFAULT": "An error occurred. Please try again.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Guest banner control payload is required.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Only User Zero can update Guest banner controls.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Failed to send reset link. Please try again.",
    "INVITE_REPLY_EMAIL_SENT": "The Collabra invitation email was sent to your friend at {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "The Collabra invitation email was resent to your friend at {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Show password",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Hide password",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Cancel",
    "GENERAL_CLOSE": "Close",
    "GENERAL_SEND": "Send",
    "GENERAL_SEARCH": "Search",
    "GENERAL_RESET": "Reset",
    "GENERAL_ENABLE": "Enable",
    "GENERAL_LOADING": "Loading...",
    "GENERAL_DELETE": "Delete",
    "GENERAL_DELETING": "Deleting...",
    "GENERAL_SAVE_PASSWORD": "Save Password",
    "AUTH_REMEMBER_EMAIL_LABEL": "Remember email",
    "GENERAL_SAVING": "Saving...",
    "GENERAL_SENDING": "Sending...",
    "GENERAL_REMOVING": "Removing...",
    "GENERAL_CONFIRM_REMOVAL": "Confirm Removal",
    "GENERAL_EMPTY": "Empty",
    "GENERAL_UNAVAILABLE": "Unavailable",
    "GENERAL_ENABLED": "Enabled",
    "GENERAL_DISABLED": "Disabled",
    "GENERAL_GRANTED": "Granted",
    "GENERAL_DENIED": "Denied",
    "GENERAL_DEFAULT": "Default",
    "GENERAL_UNSUPPORTED": "Unsupported",
    "GENERAL_PUBLIC": "Public",
    "GENERAL_PRIVATE": "Private",
    "GENERAL_USERNAME": "Username",
    "GENERAL_EMAIL": "Email",
    "GENERAL_YOU": "You",
    "GENERAL_USER": "User",
    "GENERAL_UNKNOWN": "Unknown",
    "GENERAL_VISITOR": "Visitor",
    "GENERAL_PROFILE": "Profile",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Unknown Banner",
    "GENERAL_ADVISOR_BANNER": "Advisor Banner",
    "GENERAL_NOT_AVAILABLE": "N/A",
    "GENERAL_NOT_SELECTED": "Not Selected",
    "GENERAL_NO_EMAIL_FOUND": "No email found",
    "GENERAL_USER_ZERO_ONLY": "User Zero Only",
    "GENERAL_CONNECTION_STATE": "Connection State",
    "GENERAL_DISPLAY_ONLY": "Display only",
    "GENERAL_TEXTAREA": "Textarea",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Quick Actions (RCAC)",
    "HEADER_CHANGE_STATUS": "Change Status",
    "HEADER_OT_COIN_BALANCE": "OT Coin Balance",
    "HEADER_ALT_USER": "User",
    "STATUS_BUSY": "Busy",
    "STATUS_AWAY": "Away",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Invisible",
    "NETWORK_CHECKING_CONNECTION": "Checking connection...",
    "NETWORK_ONLINE_LATENCY": "Online (Latency: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Network: Good (Tap to ping)",
    "CHAT_TARGET_ALT": "Chat target",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Search...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Open {name} profile picture",
    "CHAT_MESSAGE_INPUT_ARIA": "Message input",
    "CHAT_TOGGLE_VIEW_ARIA": "Toggle view",
    "CHAT_ADD_USER_ARIA": "Add user",
    "CHAT_ATTACH_ARIA": "Attach",
    "CHAT_MIC_ARIA": "Microphone",
    "CHAT_SEND_ARIA": "Send",
    "CHAT_SEARCH_ARIA": "Search",
    "CHAT_OPEN_SEARCH_ARIA": "Open search",
    "CHAT_CLOSE_SEARCH_ARIA": "Close search",
    "CHAT_ATTACHMENT_ALT": "Attachment",
    "CHAT_PREVIEW_ALT": "Preview",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Remove attachment",
    "CHAT_REPLYING_TO": "Replying to",
    "CHAT_CANCEL_REPLY_ARIA": "Cancel reply",
    "CHAT_UPLOADING": "Uploading...",
    "CHAT_LOADING_CHATS": "Loading Chats...",
    "CHAT_SEND_FAILED": "Send Failed",
    "CHAT_SEND_FAILED_RETRY": "Send failed. Please retry.",
    "CHAT_RETRY": "Retry",
    "CHAT_EDITED": "edited",
    "CHAT_TYPING": "Typing",
    "CHAT_LOADING": "Loading",
    "CHAT_PENDING_INVITATION": "Pending invitation",
    "CHAT_PENDING_INVITATION_MIN": "{count} min Pending invitation",
    "CHAT_PENDING_INVITATION_HR": "{count} hr Pending invitation",
    "CHAT_PENDING_INVITATION_DAY": "{count} day Pending invitation",
    "CHAT_WAITING_FOR_YOU": "{label} - Waiting for you",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Pending acceptance",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Microphone access denied.",
    "CHAT_UPLOAD_FAILED": "Upload Failed: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Upload requires an internet connection. Please try again when you are online.",
    "CHAT_ERROR_AUTH": "Auth Error",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Missing filename or content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Missing conversation_id or target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Missing conversation_id for non-avatar upload",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Invalid avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase service client unavailable",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Avatar read ack is only valid in advisor chat context",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatar flow message not found or not eligible for read ack",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Failed to finalize avatar message as read",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 attachment",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} attachments",
    "CHAT_VOICE_NOTE": "Voice Note",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat unavailable. This user blocked you.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat unavailable. You blocked this user.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Account access is blocked by policy.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat unavailable. This account is final-blocked by User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat unavailable. Mutual block is active.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat unavailable due to block policy.",
    "MESSAGE_PREVIEW_PHOTO": "Photo",
    "MESSAGE_PREVIEW_VOICE": "Voice message",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "File",
    "MESSAGE_PREVIEW_MESSAGE": "Message",
    "MESSAGE_PREVIEW_SYSTEM": "System message",
    "MESSAGE_PREVIEW_NEW": "New message",
    "MESSAGE_UNKNOWN_FILE": "Unknown File",
    "MESSAGE_AUDIO_ATTACHMENT": "Audio attachment",
    "MESSAGE_FILE_ATTACHMENT": "Attachment",
    "BANNER_INVITED_BY": "invited by {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Search Results",
    "SEARCH_QUERY_LABEL": "Query:",
    "SEARCH_LOADING_VISIBILITY": "Loading search visibility...",
    "SEARCH_NO_RESULTS": "No result found in current search scope.",
    "SHARE_WITH_COLLABRA": "Share with Collabra",
    "SHARE_SEND_TO": "Send to",
    "SHARE_SELECT_ONE_BANNER": "Select one banner",
    "SHARE_BANNER_LIST_ARIA": "Banner list",
    "SHARE_NO_MATCHING_BANNER": "No matching banner",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Add a comment...",
    "SHARE_RECENT_CHATS": "Recent chats",
    "SHARE_LEFT_LIST": "Left list",
    "SHARE_RIGHT_LIST": "Right list",
    "SHARE_UNTITLED_BANNER": "Untitled banner",
    "SHARE_SHARED_CONTENT": "Shared content",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Shared content could not be opened.",
    "SHARE_OPEN_BANNER_FAILED": "Could not open the selected banner.",
    "SHARE_ONE_PHOTO_SELECTED": "1 photo selected",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} photos selected",
    "SHARE_ONE_FILE_SELECTED": "1 file selected",
    "SHARE_MANY_FILES_SELECTED": "{count} files selected",
    "FORWARD_MESSAGE_TITLE": "Forward Message",
    "FORWARD_SELECT_RECIPIENTS": "Select recipients",
    "FORWARD_NO_OTHER_BANNER": "No other banner available.",
    "FORWARD_SEND_TO_COUNT": "Send to {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Select at least one banner.",
    "FORWARD_FAILED_DEFAULT": "Forward failed. Please try again.",
    "FORWARD_PARTIAL_SENT": "{count} sent. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Source message not found for forwarding",
    "FORWARD_NO_FORWARDABLE_CONTENT": "This message has no forwardable content yet",
    "FORWARD_DESTINATION_MISSING": "Forward destination is missing",
    "FORWARD_MESSAGE_PREVIEW": "Forwarded message",
    "MENU_PASTE": "Paste",
    "MENU_COPY": "Copy",
    "MENU_REPLY": "Reply",
    "MENU_FORWARD": "Forward",
    "MENU_REMOVE_INVITATION": "Remove Invitation",
    "MENU_REMOVE_FROM_LIST": "Remove From List",
    "MENU_GOODBYE_GUEST": "Goodbye Guest",
    "MENU_ADD_TO_LIST": "Add To List",
    "MENU_REJECT_INVITATION": "Reject Invitation",
    "MENU_FRONTEND_VERSION": "Frontend Version",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Banner Info: {title}",
    "MENU_MESSAGE_BUBBLE": "Message Bubble",
    "MENU_CHAT_CANVAS_HEADER": "Chat Canvas - {zone}",
    "MENU_CANVAS_INFO": "Canvas Info",
    "MENU_CHAT_CANVAS_SUBLABEL": "Conversation area / current chat surface",
    "MENU_INPUT_AREA_HEADER": "Input Area - {zone}",
    "MENU_INPUT_AREA_INFO": "Input Area Info: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Bottom typing and action tools surface",
    "MENU_HEADER": "Header - {zone}",
    "MENU_HEADER_INFO": "Header Info: {title}",
    "MENU_HEADER_DESCRIPTION": "Top navigation and page controls",
    "MENU_ZONE_HEADER": "Zone - {zone}",
    "MENU_ZONE_SPACE_INFO": "Zone Space Info",
    "MENU_EMPTY_LIST_SURFACE": "Empty/list surface",
    "MENU_BLOCK": "Block",
    "MENU_UNBLOCK": "Unblock",
    "MENU_HIDE_IN_SEARCH": "Hide In Search",
    "MENU_UNHIDE_IN_SEARCH": "Unhide In Search",
    "MENU_VISIBLE_IN_SEARCH": "Visible In Search",
    "MENU_HIDDEN_IN_SEARCH": "Hidden In Search",
    "MENU_VISIBLE_IN_USER_LIST": "Visible In User List",
    "MENU_HIDDEN_IN_USER_LIST": "Hidden In User List",
    "MENU_NOT_BLOCKED": "Not Blocked",
    "MENU_BLOCKED": "Blocked",
    "MENU_FRONTEND_VERSION_LOADING": "Loading...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Loading per-banner value from backend. No option is marked active until the database response arrives.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend value could not be loaded. No trusted active option is shown.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Explicit per-banner database value is {overrideVersion}. Global default is {globalDefaultVersion}. The target user must fully refresh or reopen the app for startup bootstrap to apply it.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "No explicit per-banner database value is stored. FeV2.0.0 is active by default. Global default is {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Explicit per-banner database value is active after the target app fully reloads",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "No explicit per-banner value is stored; this is the default individual FeV2.0.0 state",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "This option is also equal to the current global default",
    "MENU_DELETE_PERMANENT_CONFIRM": "Delete {target} permanently from the database? This removes the account, chat history, dependencies, and forces a full new invite path for future re-entry.",
    "MENU_DELETE_PERMANENTLY": "Delete Permanently",
    "MENU_REFRESH_PAGE": "Refresh Page",
    "MENU_LOG_OFF": "Log Off",
    "MENU_HARD_RELOAD": "Get Latest Version",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Email (Admin User)",
    "AUTH_PASSWORD_PLACEHOLDER": "Password",
    "AUTH_CONNECTING": "Connecting...",
    "AUTH_SIGNING_OUT": "Signing Out...",
    "AUTH_BACK_TO_LOGIN": "Back to Login",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Invalid server response: No token found.",
    "AUTH_LOGIN_FAILED": "Login Failed",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Passwords do not match.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Passwords do not match!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Passwords must match exactly.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "New Password",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Confirm Password",
    "AUTH_CHANGE_PASSWORD": "Change Password",
    "AUTH_SAVING_PASSWORD": "Saving...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Password updated successfully.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Unable to change password right now.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "You must be logged in to change your password.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Toggle new password visibility",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Toggle confirm password visibility",
    "REGISTER_TITLE": "Complete Registration",
    "REGISTER_SUBTITLE": "Please set your password manually.",
    "REGISTER_CREATING_ACCOUNT": "Creating Account...",
    "REGISTER_FINISH_SETUP": "Finish Setup",
    "REGISTER_FAILED_SET_PASSWORD": "Failed to set password",
    "INVITE_EMAIL_INSTRUCTION": "Please enter invitee email (Format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Invite",
    "INVITE_EMAIL_REQUIRED": "Please enter invitee email.",
    "INVITE_EMAIL_INVALID": "Invalid email format. Please use: user@example.com",
    "PENDING_INVITATION_TITLE": "Pending Invitation",
    "PENDING_INVITATION_REMOVE_QUESTION": "Remove this pending invitation from the database?",
    "PENDING_INVITATION_KEEP": "Keep Invitation",
    "PENDING_INVITATION_REMOVAL_FAILED": "Removal failed.",
    "REMOVE_FROM_LIST_TITLE": "Remove From List",
    "REMOVE_FROM_LIST_WARNING": "Remove this user from both lists now? Chat access will be cut immediately. The only return path is a new invite.",
    "REMOVE_FROM_LIST_KEEP": "Keep User In List",
    "REMOVE_FROM_LIST_FAILED": "Remove from list failed.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Setting & Live Status",
    "PERMISSION_DIALOG_ARIA": "Setting and Live Status",
    "PERMISSION_TRIGGER_ARIA": "Settings popup trigger",
    "PERMISSION_CLOSE_ARIA": "Close permission popup",
    "PERMISSION_LIVE_STATUS": "Live Status",
    "PERMISSION_SYSTEM_PERMISSION": "System Permission",
    "PERMISSION_APP_PUSH": "App Push",
    "PERMISSION_LOCATION_PERMISSION": "Location Permission",
    "PERMISSION_APP_LOCATION": "App Location",
    "PERMISSION_CONTROLS": "Permission Controls",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push Notifications",
    "PERMISSION_LOCATION_ACCESS": "Location Access",
    "PERMISSION_IN_APP_SETTINGS": "In-App Settings",
    "PERMISSION_ALERT_SOUND": "Alert Sound",
    "PERMISSION_APP_BADGE": "App Badge",
    "PERMISSION_PASSWORD_SETTINGS": "Password Settings",
    "PERMISSION_NAVIGATION_STATUS": "Navigation Status",
    "PERMISSION_SELECTED_ZONE": "Selected Zone",
    "PERMISSION_STAGED_CHAT_BANNER": "Staged Chat Banner",
    "PERMISSION_CANVAS_CONTENT": "Canvas Content",
    "PERMISSION_YOUR_DEVICES": "Your Devices ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Refresh device list",
    "PERMISSION_REFRESH_LIST": "Refresh List",
    "PERMISSION_NO_REGISTERED_DEVICES": "No registered devices found.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Resize settings popup",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Toggle push notifications",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Toggle location access",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Toggle alert sound",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Toggle app badge",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Toggle profile visibility",
    "PERMISSION_OFF_IN_V1": "Off in v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Banner List",
    "PERMISSION_PUSH_DISABLED_V1": "Push notifications are disabled for the v1 Google Play release.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Push notifications are ON for this device.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "System notifications are blocked. Tap to open settings help.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Turn ON to improve delivery reliability.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "To disable system notifications, open your browser/site notification settings and set this site to Block.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "To change system notification permission, open your browser/site notification settings and set this site to Allow.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Location access is ON for distance-based LCAC sorting and map positioning.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Location API is not supported in this environment.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Location access is blocked. Tap to open settings help.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Turn ON to allow precise distance-based LCAC sorting and in-app map positioning.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Location access is not supported in this environment.",
    "PERMISSION_LOCATION_DISABLE_HELP": "To disable location access, open your browser/site location settings and set this site to Block.",
    "PERMISSION_LOCATION_ALLOW_HELP": "To enable location access for distance sorting and in-app map positioning, open your browser/site location settings and set this site to Allow.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Unable to load registered devices right now.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Loading UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Loading Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Loading Backend...",
    "RUNTIME_LOADING": "Loading...",
    "RUNTIME_LOADING_FROM_DATABASE": "Loading From Database...",
    "RUNTIME_BACKEND_CONNECTED": "Backend Connected",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Cached Fallback Active",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback Default Active",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallback Defaults Active",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Saving Through Backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Saved In Backend Service",
    "RUNTIME_SAVE_FAILED": "Save Failed",
    "RUNTIME_LOAD_FAILED": "Load Failed",
    "RUNTIME_CONNECTED": "Connected",
    "RUNTIME_LOGIN_REQUIRED": "Login Required",
    "RUNTIME_SAVED": "Saved",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI Ready - Runtime Pending",
    "RUNTIME_BACKEND_REJECTED_MODEL": "The protected backend selector service rejected or could not save the requested model option.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "The protected backend selector service rejected or could not save the requested WF1 routing change.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selector is now reading active config, Qwen routing, and allowed options from the protected backend service.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend selector service is unavailable right now, so the last cached selector state is being used.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Selector default values are active because no backend or cached selector state could be loaded.",
    "RUNTIME_WF1_SELECTOR_SAVED": "The protected backend selector service updated the active WF1 routing config and refreshed the runtime domain cache.",
    "FRONTEND_VERSION_TITLE": "Frontend Version",
    "FRONTEND_VERSION_HELPER_ACTIVE": "This selector controls the active frontend version for all users. FeV2.0.0 is active.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "This selector reads the active frontend version from config_domain_registry. Runtime resolves to FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "The backend frontend-version config could not be loaded, so the coded FeV2.0.0 default is active until startup bootstrap can read the protected service again.",
    "FRONTEND_VERSION_HELPER_SAVED": "The active frontend version was saved in config_domain_registry. A full refresh or next app load applies the runtime value.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "The backend frontend-version control service could not save the requested global version.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Active frontend version.",
    "CHAT_DELETE_WINDOW_TITLE": "Chat Delete Window",
    "CHAT_DELETE_HELPER": "This value controls the Delete for everyone availability window in seconds. Backend guard changes immediately after save. Bubble visibility changes after a full refresh or the next app load.",
    "CHAT_DELETE_HELPER_FALLBACK": "The backend chat delete control service could not be loaded, so the coded default remains active until startup bootstrap can read the protected service again.",
    "CHAT_DELETE_HELPER_SAVED": "The Delete for everyone availability window was saved in config_domain_registry. Backend guard changes immediately. Bubble visibility changes after a full refresh or the next app load.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "The backend chat delete control service could not save the requested window value.",
    "CHAT_DELETE_WINDOW_LABEL": "Delete for everyone window",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} sec",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Store the value in whole seconds. Current production value is 86400 seconds = 1 day.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Window Seconds",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Enter a whole number greater than or equal to 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Save Delete Window",
    "GUEST_BANNER_CONTROL_TITLE": "Guest Banner",
    "GUEST_BANNER_CONTROL_LABEL": "Guest QR Chat",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Show Guest banner for all users",
    "GUEST_BANNER_CONTROL_HELPER": "Controls the fixed Guest banner and pending QR token lifetime.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Local fallback is active for Guest banner controls.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Guest banner controls saved.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Guest banner controls could not be saved.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} Guest sessions revoked.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "Pending QR TTL (minutes)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "Current pending QR TTL: {count} minutes.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Enter a positive whole number of minutes.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Save Guest Banner",
    "GUEST_QR_LOADING": "Preparing Guest QR...",
    "GUEST_QR_READY": "Scan to open the temporary Guest chat.",
    "GUEST_QR_ALT": "Guest chat QR code",
    "GUEST_QR_LOAD_FAILED": "Guest QR could not be prepared.",
    "GUEST_SESSION_ACTIVE": "Guest is connected.",
    "GUEST_PUBLIC_TITLE": "Guest Chat",
    "GUEST_PUBLIC_CONNECTING": "Connecting...",
    "GUEST_PUBLIC_CONNECTED": "Connected",
    "GUEST_PUBLIC_UNAVAILABLE": "This Guest link is unavailable.",
    "GUEST_PUBLIC_SEND_FAILED": "Message could not be sent.",
    "UI_TEXTS_RUNTIME_TITLE": "UI Language Runtime",
    "UI_TEXTS_RUNTIME_BACKEND": "UI language runtime is reading from the protected backend service. Changes apply on the next full app load.",
    "UI_TEXTS_RUNTIME_CACHED": "Backend UI language runtime service is unavailable right now, so cached or local defaults are active.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "UI language runtime defaults are active because no backend or cached state could be loaded.",
    "UI_TEXTS_RUNTIME_SAVED": "UI language runtime control was saved. A full refresh or next app load is required for users to receive the new language gate.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "The protected backend service could not save the requested UI language runtime change.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Device language application",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Enable runtime UI languages",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Users can receive UI text payloads for their stored or device language.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "All users are forced to English UI text, and device language is ignored.",
    "PROFILE_VISIBILITY_TITLE": "Profile Visibility",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "You must be logged in to manage account visibility.",
    "PROFILE_VISIBILITY_HELPER": "This switch updates only your account visibility state. Discoverability and banner-list behavior stay unchanged in this phase.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Profile visibility could not be loaded right now.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Profile visibility could not be updated right now.",
    "PROFILE_VISIBILITY_SAVED": "Your account visibility is now {visibility}. Discoverability flags remain unchanged in this phase.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Public Account",
    "PROFILE_VISIBILITY_STORED": "Stored Visibility",
    "WF1_MODEL_CONTROL_TITLE": "WF1 Model Control",
    "WF1_ENABLE_TRANSLATION": "Enable Translation / Pivot",
    "WF1_TRANSLATION_ACTIVE": "AI translation is active.",
    "WF1_TRANSLATION_INACTIVE": "WF1 keeps running but source text is copied and pivot is marked as inactive.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Active Runtime Slot",
    "WF1_ALLOW_SAME_LANGUAGE": "Allow AI For Same-Language Pairs",
    "WF1_SAME_LANGUAGE_ACTIVE": "Same-language pairs follow normal WF1 routing.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Same-language pairs bypass AI and store No Pivot language active.",
    "WF1_QWEN_ROUTING": "Qwen Pair Routing",
    "WF1_QWEN_ROUTING_HELPER": "Languages checked below use Qwen-Max when the pair is either the same checked language, a checked language with English, or two checked non-English languages. Otherwise the selected primary model stays active.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter Test Slot",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter Test Slot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Quality Test Only",
    "WF1_OPENROUTER_HELPER": "This slot is editable only for temporary OpenRouter quality tests. It does not change the operational Qwen pair-routing path unless this slot itself becomes the active model.",
    "WF1_LABEL": "Label",
    "WF1_PRODUCT": "Product",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Provider: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter Test Slot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max via OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google list price",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI list price",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter list price",
    "LANGUAGE_ENGLISH": "English",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Chinese (Simplified)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Chinese (Traditional)",
    "LANGUAGE_JAPANESE": "Japanese",
    "LANGUAGE_KOREAN": "Korean",
    "LANGUAGE_PERSIAN": "Persian",
    "LANGUAGE_TURKISH_ISTANBUL": "Turkish (Istanbul)",
    "LANGUAGE_ARABIC": "Arabic",
    "LANGUAGE_FRENCH": "French",
    "LANGUAGE_GERMAN": "German",
    "LANGUAGE_SPANISH": "Spanish",
    "LANGUAGE_PORTUGUESE": "Portuguese",
    "LANGUAGE_ITALIAN": "Italian",
    "LANGUAGE_RUSSIAN": "Russian",
    "LANGUAGE_DUTCH": "Dutch",
    "LANGUAGE_VIETNAMESE": "Vietnamese",
    "LANGUAGE_INDONESIAN": "Indonesian",
    "LANGUAGE_THAI": "Thai",
    "LANGUAGE_MALAY": "Malay",
    "WF1_PRICING_CUSTOM": "Pricing: custom slot model - check current OpenRouter pricing",
    "WF1_SAVE_OPENROUTER_SLOT": "Save OpenRouter Slot",
    "WF1_PRICING_LINE": "Input {input} - Output {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "Zone Visibility Control",
    "ZONE_ENABLE": "Enable {zone}",
    "ZONE_ENABLED_NOTE": "{zone} can appear for allowed roles after the next app load.",
    "ZONE_DISABLED_NOTE": "{zone} is treated as absent for non-S_Admin users after the next app load.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin bypasses this role list and always keeps access.",
    "ZONE_ROLE_LOCKED": "Role selections are temporarily locked while this zone is disabled and will return exactly as saved when the zone is enabled again.",
    "ZONE_LCAC_CONTROL": "LCAC Control",
    "ZONE_RCAC_CONTROL": "RCAC Control",
    "ZONE_LCAC_DESCRIPTION": "Controls the existence of the left reserved zone and the roles that may see it.",
    "ZONE_RCAC_DESCRIPTION": "Controls the existence of the right reserved zone and the roles that may see it.",
    "ZONE_VISIBILITY_BACKEND": "Zone visibility bootstrap is now reading from the protected backend service. Changes apply on the next app load.",
    "ZONE_VISIBILITY_CACHED": "Backend zone visibility service is unavailable right now, so cached or local defaults are active.",
    "ZONE_VISIBILITY_DEFAULTS": "Zone visibility defaults are active because no backend or cached state could be loaded.",
    "ZONE_VISIBILITY_SAVED": "Zone visibility bootstrap was saved. Hard reload or next app load is required for runtime application.",
    "ZONE_VISIBILITY_SAVE_FAILED": "The protected backend service could not save the requested zone visibility change.",
    "ROLE_MEMBER": "Member",
    "ROLE_STAFF": "Staff",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Enable notifications to receive new messages.",
    "MAIN_LOG_OUT": "Log Out",
    "NOTIFICATION_NEW_MESSAGE": "New message",
    "NOTIFICATION_UNREAD_MESSAGE": "You have an unread message.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Full View",
    "MEDIA_AUDIO_ATTACHMENT": "Audio attachment",
    "MEDIA_FILE_FALLBACK": "File",
    "MEDIA_DOWNLOAD_READY": "Attachment ready for download",
    "MEDIA_TYPE_UNSUPPORTED": "Type not supported for full view",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Previous image",
    "MEDIA_NEXT_IMAGE_ARIA": "Next image",
    "MEDIA_OPEN_ORIGINAL": "Open Original",
    "MEDIA_DOWNLOAD": "Download",
    "MEDIA_CLOSE_ARIA": "Close",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name} profile picture",
    "MEDIA_PROFILE_ALT": "{name} profile",
    "MEDIA_UPLOAD_FAILED": "Upload failed",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend Token Error",
    "MEDIA_UPLOAD_URL_MISSING": "Critical: upload URL is missing in backend response.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Missing auth token for chat upload",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Chat upload token request failed",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Invalid chat upload response",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS Upload Failed",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Missing filename or contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Missing file_path",
    "BLOCK_NOTICE_TITLE": "Permanent Block Notice",
    "BLOCK_NOTICE_MESSAGE": "Your account has been temporarily suspended due to the policy violation.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "If you believe this requires follow-up, please contact",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "by email.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Unknown User",
    "GENERAL_GUEST": "Guest",
    "ADVISOR_FOR_CLIENT": "Advisor for {client_display_name}",
    "GUEST_FOR_CLIENT": "Guest for {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token and password are required",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Request body must be JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Invalid or expired invitation token",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Password set failed: missing session or user",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Password set failed during sign-in",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Admin token generation failed",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Login failed: missing session or user",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registration successful. Please check email for verification.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Signup failed unknown",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Invalid token processing",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Access token is required",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Token hash preview requires email hint from redirect URL",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Unable to resolve identity for this token",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Only User Zero can access the WF1 LLM selector service.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Only User Zero can access the zone visibility control service.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Only User Zero can access the frontend version control service.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Only User Zero can inspect another user's frontend version.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Only User Zero can access the chat delete control service.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Only User Zero can access the UI language runtime control service.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Only User Zero can permanently delete a user account.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Invalid request payload.",
    "API_ERROR_INTERNAL_SERVER": "Internal Server Error",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Function missing in backend (Reload Required)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Only DB RPC is allowed for delivered/read transitions.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Please wait before sending another message.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Message sent successfully.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Contact service is unavailable.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Message sending failed.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Name is required.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Email is invalid.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Message is required.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Selector payload is required.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Zone visibility payload is required.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Frontend version payload is required.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Chat delete control payload is required.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "UI language runtime control payload is required.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Authenticated user id is required.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Authenticated viewer user id is required.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Authenticated actor user id is required.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id is required.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id is required.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids list is required.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email is required.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by is required.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Search runtime is disabled by global frontend version.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "You are not allowed to cancel this pending invitation.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "This invitation can no longer be canceled because the user is already registered.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Pending invitation not found.",
    "INVITE_REPLY_ALREADY_MEMBER": "Congratulations, your friend ({invitee_email}) is already registered in this app and is a member of this workspace.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "An invitation is pending for {invitee_email}, but the retry email could not be triggered. Please check the mail logs.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Invitation record was created for {invitee_email}, but email delivery could not be confirmed. Please try again later or check the mail logs.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Failed to create invitation record. Please try again later.",
    "INVITE_REPLY_SYSTEM_ERROR": "System Error during invitation process: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend Configuration Error: Missing Supabase credentials",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend Configuration Error: Invalid Supabase URL",
    "CHAT_ERROR_ACCESS_DENIED": "Access Denied",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Content cannot be empty for text messages",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Could not determine conversation ID",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC auth context is missing",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC returned invalid message payload",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Insert failed, no data returned",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations must be a list",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Invalid operation payload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Unsupported operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id is required",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Message not found",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Delete is only allowed on your own message",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Delete for everyone is no longer available for this message",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Delete for everyone failed",
    "API_ERROR_SERVER_CONFIGURATION": "Server configuration error",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Missing webhook secret header",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Unauthorized webhook source",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend configuration error",
    "API_ERROR_MODULE_ATTRIBUTE": "Module Attribute Error: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Failed before invitation deletion while removing waiting auth user.",
    "CHAT_ERROR_DB": "DB Error: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "Live Conversation",
    "CHAT_LIVE_CONVERSATION_ARIA": "Live conversation",
    "LIVE_CONV_START": "Start",
    "LIVE_CONV_STOP": "Stop",
    "LIVE_CONV_CLOSE": "Close",
    "LIVE_CONV_STATUS_READY": "Ready to start",
    "LIVE_CONV_STATUS_CONNECTING": "Connecting...",
    "LIVE_CONV_STATUS_LISTENING": "Listening...",
    "LIVE_CONV_STATUS_TRANSLATING": "Translating...",
    "LIVE_CONV_STATUS_FINISHING": "Finishing...",
    "LIVE_CONV_STATUS_STOPPED": "Stopped",
    "LIVE_CONV_TURN_SENDING": "Sending...",
    "LIVE_CONV_TURN_SENT": "Sent",
    "LIVE_CONV_TURN_FAILED": "Send failed",
    "LIVE_CONV_EMPTY_HINT": "Press Start and speak. Each pause sends a translated voice message.",
    "LIVE_CONV_DISCLAIMER": "Translated voice is a model voice, not a clone of the speaker.",
    "LIVE_CONV_ERROR_DISABLED": "Live Conversation is currently disabled.",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "Daily Live Conversation limit reached.",
    "LIVE_CONV_ERROR_MIC": "Microphone access is required.",
    "LIVE_CONV_ERROR_CONNECTION": "Connection failed. Please try again.",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "Turn audio file is required.",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "conversation_id is required.",
}
