# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/es.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Principal",
    "APP_TITLE": "Plataforma de IA OTMEGA",
    "APP_SUBTITLE": "Asesor de IA",
    "CHAT_PLACEHOLDER": "Escribe tu mensaje...",
    "CHAT_SEND_BUTTON": "Enviar",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 El asesor puede cometer errores, asi que verifica la informacion.",
    "STATUS_ONLINE": "En linea",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Nuevo chat",
    "ICON_HISTORY": "Historial",
    "ICON_TEMPLATES": "Plantillas",
    "ICON_SETTINGS": "Configuracion",
    "ICON_USER_PROFILE": "Perfil de usuario",
    "ICON_QUICK_ACTIONS": "Acciones rapidas",
    "ICON_PINNED": "Fijado",
    "ICON_GALLERY": "Galeria",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Instalar app",
    "PWA_ANDROID_MSG": "Instala esta app en tu dispositivo para una mejor experiencia y acceso sin conexion.",
    "PWA_IOS_MSG": "Para instalar esta app en tu iPhone/iPad:\n1. Toca el boton Compartir de abajo\n2. Selecciona Agregar a la pantalla de inicio",
    "PWA_BTN_INSTALL": "Instalar",
    "PWA_BTN_LATER": "Tal vez mas tarde",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Inicia sesion en la red de asesores",
    "AUTH_HEADER_SIGNUP": "Crea tu cuenta unificada",
    "AUTH_HEADER_LOGIN_NETWORK": "Inicia sesion en la red de asesores",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Crea tu cuenta unificada",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Iniciar sesion",
    "AUTH_BUTTON_SIGNUP": "Crear cuenta",
    "AUTH_BUTTON_GOOGLE": "Continuar con Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Olvide mi contrasena",
    "AUTH_BUTTON_SEND_RESET_LINK": "Enviar enlace de restablecimiento",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "No tienes cuenta? Registrate",
    "AUTH_PROMPT_LOGIN": "Ya tienes cuenta? Inicia sesion",
    "AUTH_HELPER_TEXT_SIGNUP": "Estas creando una cuenta unificada que puedes usar para acceder a todos los asesores de esta plataforma.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Estas creando una cuenta unificada que puedes usar para acceder a todos los asesores de esta plataforma.",
    "AUTH_HELPER_TEXT_LOGIN": "Usa la misma cuenta (email/contrasena o Google) que usaste para otros asesores de esta red.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Usa la misma cuenta (email/contrasena o Google) que usaste para otros asesores de esta red.",
    "AUTH_FORGOT_PASSWORD_LINK": "Olvidaste tu contrasena?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Restablecer tu contrasena",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Ingresa tu direccion de email y te enviaremos un enlace para restablecer tu contrasena.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Email",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Iniciando sesion...",
    "AUTH_STATUS_LOADING_SIGNUP": "Creando tu cuenta...",
    "AUTH_STATUS_LOADING_RESET": "Enviando enlace de restablecimiento...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Inicio de sesion correcto! Recargando...",
    "AUTH_STATUS_SUCCESS_RESET": "Enlace de restablecimiento enviado correctamente. Revisa tu email.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Enlace para restablecer la contrasena enviado correctamente. Revisa tu email.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Email o contrasena invalidos.",
    "AUTH_ERROR_EMAIL_EXISTS": "Ya existe una cuenta con este email en la red de asesores.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Ya existe una cuenta con este email. Inicia sesion. Actualmente eres miembro de:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Ya existe una cuenta con este email en la red de asesores. Cierra esta ventana y usa la seccion Iniciar sesion con el mismo email y tu contrasena anterior.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Actualmente eres miembro de:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "El email y la contrasena son obligatorios.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "La cuenta se creo, pero no se pudo configurar la membresia. Contacta con soporte.",
    "AUTH_ERROR_DEFAULT": "Ocurrio un error. Intentalo de nuevo.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Se requiere la carga útil de control del banner de invitado.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Solo el Usuario Cero puede actualizar los controles del banner de invitado.",
    "AUTH_FORGOT_PASSWORD_ERROR": "No se pudo enviar el enlace de restablecimiento. Intentalo de nuevo.",
    "INVITE_REPLY_EMAIL_SENT": "El email de invitacion de Collabra se envio a tu amigo en {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "El email de invitacion de Collabra se reenvio a tu amigo en {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Mostrar contrasena",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Ocultar contrasena",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Cancelar",
    "GENERAL_CLOSE": "Cerrar",
    "GENERAL_SEND": "Enviar",
    "GENERAL_SEARCH": "Buscar",
    "GENERAL_RESET": "Restablecer",
    "GENERAL_ENABLE": "Activar",
    "GENERAL_LOADING": "Cargando...",
    "GENERAL_DELETE": "Eliminar",
    "GENERAL_DELETING": "Eliminando...",
    "GENERAL_SAVE_PASSWORD": "Guardar contrasena",
    "AUTH_REMEMBER_EMAIL_LABEL": "Recordar email",
    "GENERAL_SAVING": "Guardando...",
    "GENERAL_SENDING": "Enviando...",
    "GENERAL_REMOVING": "Quitando...",
    "GENERAL_CONFIRM_REMOVAL": "Confirmar eliminacion",
    "GENERAL_EMPTY": "Vacio",
    "GENERAL_UNAVAILABLE": "No disponible",
    "GENERAL_ENABLED": "Activado",
    "GENERAL_DISABLED": "Desactivado",
    "GENERAL_GRANTED": "Concedido",
    "GENERAL_DENIED": "Denegado",
    "GENERAL_DEFAULT": "Predeterminado",
    "GENERAL_UNSUPPORTED": "No compatible",
    "GENERAL_PUBLIC": "Publico",
    "GENERAL_PRIVATE": "Privado",
    "GENERAL_USERNAME": "Nombre de usuario",
    "GENERAL_EMAIL": "Email",
    "GENERAL_YOU": "Tu",
    "GENERAL_USER": "Usuario",
    "GENERAL_UNKNOWN": "Desconocido",
    "GENERAL_VISITOR": "Visitante",
    "GENERAL_PROFILE": "Perfil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Banner desconocido",
    "GENERAL_ADVISOR_BANNER": "Banner del asesor",
    "GENERAL_NOT_AVAILABLE": "N/D",
    "GENERAL_NOT_SELECTED": "No seleccionado",
    "GENERAL_NO_EMAIL_FOUND": "No se encontro email",
    "GENERAL_USER_ZERO_ONLY": "Solo Usuario Cero",
    "GENERAL_CONNECTION_STATE": "Estado de conexion",
    "GENERAL_DISPLAY_ONLY": "Solo visualizacion",
    "GENERAL_TEXTAREA": "Area de texto",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Acciones rapidas (RCAC)",
    "HEADER_CHANGE_STATUS": "Cambiar estado",
    "HEADER_OT_COIN_BALANCE": "Saldo de OT Coin",
    "HEADER_ALT_USER": "Usuario",
    "STATUS_BUSY": "Ocupado",
    "STATUS_AWAY": "Ausente",
    "STATUS_OFFLINE": "Sin conexion",
    "STATUS_INVISIBLE": "Invisible",
    "NETWORK_CHECKING_CONNECTION": "Comprobando conexion...",
    "NETWORK_ONLINE_LATENCY": "En linea (latencia: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Red: buena (toca para hacer ping)",
    "CHAT_TARGET_ALT": "Destino del chat",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Buscar...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Abrir foto de perfil de {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Entrada de mensaje",
    "CHAT_TOGGLE_VIEW_ARIA": "Alternar vista",
    "CHAT_ADD_USER_ARIA": "Agregar usuario",
    "CHAT_ATTACH_ARIA": "Adjuntar",
    "CHAT_MIC_ARIA": "Microfono",
    "CHAT_SEND_ARIA": "Enviar",
    "CHAT_SEARCH_ARIA": "Buscar",
    "CHAT_OPEN_SEARCH_ARIA": "Abrir busqueda",
    "CHAT_CLOSE_SEARCH_ARIA": "Cerrar busqueda",
    "CHAT_ATTACHMENT_ALT": "Adjunto",
    "CHAT_PREVIEW_ALT": "Vista previa",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Quitar adjunto",
    "CHAT_REPLYING_TO": "Respondiendo a",
    "CHAT_CANCEL_REPLY_ARIA": "Cancelar respuesta",
    "CHAT_UPLOADING": "Subiendo...",
    "CHAT_LOADING_CHATS": "Cargando chats...",
    "CHAT_SEND_FAILED": "Envio fallido",
    "CHAT_SEND_FAILED_RETRY": "No se pudo enviar. Intentalo de nuevo.",
    "CHAT_RETRY": "Reintentar",
    "CHAT_EDITED": "editado",
    "CHAT_TYPING": "Escribiendo",
    "CHAT_LOADING": "Cargando",
    "CHAT_PENDING_INVITATION": "Invitacion pendiente",
    "CHAT_PENDING_INVITATION_MIN": "{count} min Invitacion pendiente",
    "CHAT_PENDING_INVITATION_HR": "{count} h Invitacion pendiente",
    "CHAT_PENDING_INVITATION_DAY": "{count} dia Invitacion pendiente",
    "CHAT_WAITING_FOR_YOU": "{label} - Esperando por ti",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Aceptacion pendiente",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Acceso al microfono denegado.",
    "CHAT_UPLOAD_FAILED": "Subida fallida: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "La subida requiere conexion a Internet. Intentalo de nuevo cuando estes en linea.",
    "OFFLINE_SHOWING_SAVED_DATA": "",
    "OFFLINE_DATA_MAY_BE_OUTDATED": "",
    "OFFLINE_ACTION_REQUIRES_CONNECTION": "",
    "OFFLINE_MESSAGE_WAITING_CONNECTION": "",
    "OFFLINE_PENDING_MESSAGES_TOOLTIP": "",
    "APP_BACK_EXIT_HINT": "",
    "CHAT_ERROR_AUTH": "Error de autenticacion",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Falta nombre de archivo o content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Falta conversation_id o target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Falta conversation_id para una subida que no es avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path de avatar invalido",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Cliente de servicio Supabase no disponible",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "El acuse de lectura de avatar solo es valido en el contexto de chat con asesor",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Mensaje de flujo de avatar no encontrado o no apto para acuse de lectura",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "No se pudo finalizar el mensaje de avatar como leido",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 adjunto",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} adjuntos",
    "CHAT_VOICE_NOTE": "Nota de voz",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat no disponible. Este usuario te bloqueo.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat no disponible. Has bloqueado a este usuario.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "El acceso a la cuenta esta bloqueado por la politica.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat no disponible. Esta cuenta esta bloqueada definitivamente por Usuario Cero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat no disponible. El bloqueo mutuo esta activo.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat no disponible debido a la politica de bloqueo.",
    "MESSAGE_PREVIEW_PHOTO": "Foto",
    "MESSAGE_PREVIEW_VOICE": "Mensaje de voz",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Archivo",
    "MESSAGE_PREVIEW_MESSAGE": "Mensaje",
    "MESSAGE_PREVIEW_SYSTEM": "Mensaje del sistema",
    "MESSAGE_PREVIEW_NEW": "Nuevo mensaje",
    "MESSAGE_UNKNOWN_FILE": "Archivo desconocido",
    "MESSAGE_AUDIO_ATTACHMENT": "Adjunto de audio",
    "MESSAGE_FILE_ATTACHMENT": "Adjunto",
    "BANNER_INVITED_BY": "invitado por {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Resultados de busqueda",
    "SEARCH_QUERY_LABEL": "Consulta:",
    "SEARCH_LOADING_VISIBILITY": "Cargando visibilidad de busqueda...",
    "SEARCH_NO_RESULTS": "No se encontro ningun resultado en el ambito de busqueda actual.",
    "SHARE_WITH_COLLABRA": "Compartir con Collabra",
    "SHARE_SEND_TO": "Enviar a",
    "SHARE_SELECT_ONE_BANNER": "Selecciona un banner",
    "SHARE_BANNER_LIST_ARIA": "Lista de banners",
    "SHARE_NO_MATCHING_BANNER": "No hay banner coincidente",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Agregar un comentario...",
    "SHARE_RECENT_CHATS": "Chats recientes",
    "SHARE_LEFT_LIST": "Lista izquierda",
    "SHARE_RIGHT_LIST": "Lista derecha",
    "SHARE_UNTITLED_BANNER": "Banner sin titulo",
    "SHARE_SHARED_CONTENT": "Contenido compartido",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "No se pudo abrir el contenido compartido.",
    "SHARE_OPEN_BANNER_FAILED": "No se pudo abrir el banner seleccionado.",
    "SHARE_ONE_PHOTO_SELECTED": "1 foto seleccionada",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} fotos seleccionadas",
    "SHARE_ONE_FILE_SELECTED": "1 archivo seleccionado",
    "SHARE_MANY_FILES_SELECTED": "{count} archivos seleccionados",
    "FORWARD_MESSAGE_TITLE": "Reenviar mensaje",
    "FORWARD_SELECT_RECIPIENTS": "Seleccionar destinatarios",
    "FORWARD_NO_OTHER_BANNER": "No hay otro banner disponible.",
    "FORWARD_SEND_TO_COUNT": "Enviar a {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Selecciona al menos un banner.",
    "FORWARD_FAILED_DEFAULT": "El reenvio fallo. Intentalo de nuevo.",
    "FORWARD_PARTIAL_SENT": "{count} enviado(s). {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Mensaje de origen no encontrado para reenviar",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Este mensaje aun no tiene contenido reenviable",
    "FORWARD_DESTINATION_MISSING": "Falta el destino del reenvio",
    "FORWARD_MESSAGE_PREVIEW": "Mensaje reenviado",
    "MENU_PASTE": "Pegar",
    "MENU_COPY": "Copiar",
    "MENU_REPLY": "Responder",
    "MENU_FORWARD": "Reenviar",
    "MENU_REMOVE_INVITATION": "Eliminar invitacion",
    "MENU_REMOVE_FROM_LIST": "Quitar de la lista",
    "MENU_GOODBYE_GUEST": "Adiós, invitado",
    "MENU_ADD_TO_LIST": "Agregar a la lista",
    "MENU_REJECT_INVITATION": "Rechazar invitacion",
    "MENU_FRONTEND_VERSION": "Version frontend",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Info del banner: {title}",
    "MENU_MESSAGE_BUBBLE": "Burbuja de mensaje",
    "MENU_CHAT_CANVAS_HEADER": "Canvas de chat - {zone}",
    "MENU_CANVAS_INFO": "Info del canvas",
    "MENU_CHAT_CANVAS_SUBLABEL": "Area de conversacion / superficie del chat actual",
    "MENU_INPUT_AREA_HEADER": "Area de entrada - {zone}",
    "MENU_INPUT_AREA_INFO": "Info del area de entrada: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Superficie inferior de escritura y herramientas de accion",
    "MENU_HEADER": "Encabezado - {zone}",
    "MENU_HEADER_INFO": "Info del encabezado: {title}",
    "MENU_HEADER_DESCRIPTION": "Navegacion superior y controles de pagina",
    "MENU_ZONE_HEADER": "Zona - {zone}",
    "MENU_ZONE_SPACE_INFO": "Info del espacio de zona",
    "MENU_EMPTY_LIST_SURFACE": "Superficie vacia/lista",
    "MENU_BLOCK": "Bloquear",
    "MENU_UNBLOCK": "Desbloquear",
    "MENU_HIDE_IN_SEARCH": "Ocultar en busqueda",
    "MENU_UNHIDE_IN_SEARCH": "Mostrar en busqueda",
    "MENU_VISIBLE_IN_SEARCH": "Visible en busqueda",
    "MENU_HIDDEN_IN_SEARCH": "Oculto en busqueda",
    "MENU_VISIBLE_IN_USER_LIST": "Visible en lista de usuarios",
    "MENU_HIDDEN_IN_USER_LIST": "Oculto en lista de usuarios",
    "MENU_NOT_BLOCKED": "No bloqueado",
    "MENU_BLOCKED": "Bloqueado",
    "MENU_FRONTEND_VERSION_LOADING": "Cargando...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Cargando valor por banner desde el backend. Ninguna opcion se marca como activa hasta que llegue la respuesta de la base de datos.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "No se pudo cargar el valor del backend. No se muestra ninguna opcion activa confiable.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "El valor explicito por banner en la base de datos es {overrideVersion}. El valor global predeterminado es {globalDefaultVersion}. El usuario destino debe actualizar completamente o reabrir la app para que el bootstrap de inicio lo aplique.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "No hay valor explicito por banner almacenado. FeV2.0.0 esta activo de forma predeterminada. El valor global predeterminado es {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "El valor explicito por banner se activa despues de que la app destino se recargue por completo",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "No hay valor explicito por banner almacenado; este es el estado individual predeterminado de FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Esta opcion tambien es igual al valor global predeterminado actual",
    "MENU_DELETE_PERMANENT_CONFIRM": "Eliminar {target} permanentemente de la base de datos? Esto elimina la cuenta, el historial de chat, las dependencias y fuerza una nueva ruta de invitacion para cualquier reingreso futuro.",
    "MENU_DELETE_PERMANENTLY": "Eliminar permanentemente",
    "MENU_REFRESH_PAGE": "Actualizar pagina",
    "MENU_LOG_OFF": "Cerrar sesion",
    "MENU_HARD_RELOAD": "Recarga forzada",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Email (usuario admin)",
    "AUTH_PASSWORD_PLACEHOLDER": "Contrasena",
    "AUTH_CONNECTING": "Conectando...",
    "AUTH_SIGNING_OUT": "Cerrando sesion...",
    "AUTH_BACK_TO_LOGIN": "Volver al inicio de sesion",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Respuesta del servidor invalida: no se encontro ningun token.",
    "AUTH_LOGIN_FAILED": "Inicio de sesion fallido",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Las contrasenas no coinciden.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Las contrasenas no coinciden!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Las contrasenas deben coincidir exactamente.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nueva contrasena",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Confirmar contrasena",
    "AUTH_CHANGE_PASSWORD": "Cambiar contrasena",
    "AUTH_SAVING_PASSWORD": "Guardando...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Contrasena actualizada correctamente.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "No se puede cambiar la contrasena ahora mismo.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Debes iniciar sesion para cambiar tu contrasena.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Alternar visibilidad de la nueva contrasena",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Alternar visibilidad de confirmacion de contrasena",
    "REGISTER_TITLE": "Completar registro",
    "REGISTER_SUBTITLE": "Configura tu contrasena manualmente.",
    "REGISTER_CREATING_ACCOUNT": "Creando cuenta...",
    "REGISTER_FINISH_SETUP": "Finalizar configuracion",
    "REGISTER_FAILED_SET_PASSWORD": "No se pudo establecer la contrasena",
    "INVITE_EMAIL_INSTRUCTION": "Ingresa el email del invitado (formato: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Invitar",
    "INVITE_EMAIL_REQUIRED": "Ingresa el email del invitado.",
    "INVITE_EMAIL_INVALID": "Formato de email invalido. Usa: user@example.com",
    "PENDING_INVITATION_TITLE": "Invitacion pendiente",
    "PENDING_INVITATION_REMOVE_QUESTION": "Eliminar esta invitacion pendiente de la base de datos?",
    "PENDING_INVITATION_KEEP": "Conservar invitacion",
    "PENDING_INVITATION_REMOVAL_FAILED": "La eliminacion fallo.",
    "REMOVE_FROM_LIST_TITLE": "Quitar de la lista",
    "REMOVE_FROM_LIST_WARNING": "Quitar ahora este usuario de ambas listas? El acceso al chat se cortara inmediatamente. La unica ruta de retorno es una nueva invitacion.",
    "REMOVE_FROM_LIST_KEEP": "Mantener usuario en la lista",
    "REMOVE_FROM_LIST_FAILED": "No se pudo quitar de la lista.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Configuracion y estado en vivo",
    "PERMISSION_DIALOG_ARIA": "Configuracion y estado en vivo",
    "PERMISSION_TRIGGER_ARIA": "Disparador de popup de configuracion",
    "PERMISSION_CLOSE_ARIA": "Cerrar popup de permisos",
    "PERMISSION_LIVE_STATUS": "Estado en vivo",
    "PERMISSION_SYSTEM_PERMISSION": "Permiso del sistema",
    "PERMISSION_APP_PUSH": "Push de la app",
    "PERMISSION_LOCATION_PERMISSION": "Permiso de ubicacion",
    "PERMISSION_APP_LOCATION": "Ubicacion de la app",
    "PERMISSION_CONTROLS": "Controles de permisos",
    "PERMISSION_PUSH_NOTIFICATIONS": "Notificaciones push",
    "PERMISSION_LOCATION_ACCESS": "Acceso a ubicacion",
    "PERMISSION_IN_APP_SETTINGS": "Configuracion dentro de la app",
    "PERMISSION_ALERT_SOUND": "Sonido de alerta",
    "PERMISSION_APP_BADGE": "Insignia de la app",
    "PERMISSION_PASSWORD_SETTINGS": "Configuracion de contrasena",
    "PERMISSION_NAVIGATION_STATUS": "Estado de navegacion",
    "PERMISSION_SELECTED_ZONE": "Zona seleccionada",
    "PERMISSION_STAGED_CHAT_BANNER": "Banner de chat preparado",
    "PERMISSION_CANVAS_CONTENT": "Contenido del canvas",
    "PERMISSION_YOUR_DEVICES": "Tus dispositivos ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Actualizar lista de dispositivos",
    "PERMISSION_REFRESH_LIST": "Actualizar lista",
    "PERMISSION_NO_REGISTERED_DEVICES": "No se encontraron dispositivos registrados.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Redimensionar popup de configuracion",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Alternar notificaciones push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Alternar acceso a ubicacion",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Alternar sonido de alerta",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Alternar insignia de la app",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Alternar visibilidad del perfil",
    "PERMISSION_OFF_IN_V1": "Desactivado en v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Lista de banners",
    "PERMISSION_PUSH_DISABLED_V1": "Las notificaciones push estan desactivadas para la version v1 de Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Las notificaciones push estan activadas para este dispositivo.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Las notificaciones del sistema estan bloqueadas. Toca para abrir la ayuda de configuracion.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Activa para mejorar la fiabilidad de entrega.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Para desactivar las notificaciones del sistema, abre la configuracion de notificaciones de tu navegador/sitio y establece este sitio en Bloquear.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Para cambiar el permiso de notificaciones del sistema, abre la configuracion de notificaciones de tu navegador/sitio y establece este sitio en Permitir.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "El acceso a ubicacion esta activado para la ordenacion LCAC basada en distancia y el posicionamiento en el mapa.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "La API de ubicacion no es compatible con este entorno.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "El acceso a ubicacion esta bloqueado. Toca para abrir la ayuda de configuracion.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Activa para permitir la ordenacion LCAC precisa basada en distancia y el posicionamiento en el mapa dentro de la app.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "El acceso a ubicacion no es compatible con este entorno.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Para desactivar el acceso a ubicacion, abre la configuracion de ubicacion de tu navegador/sitio y establece este sitio en Bloquear.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Para activar el acceso a ubicacion para ordenacion por distancia y posicionamiento en el mapa dentro de la app, abre la configuracion de ubicacion de tu navegador/sitio y establece este sitio en Permitir.",
    "PERMISSION_DEVICE_LOAD_FAILED": "No se pueden cargar los dispositivos registrados ahora mismo.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Cargando puente UI...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Cargando puente local...",
    "RUNTIME_LOADING_BACKEND": "Cargando backend...",
    "RUNTIME_LOADING": "Cargando...",
    "RUNTIME_LOADING_FROM_DATABASE": "Cargando desde la base de datos...",
    "RUNTIME_BACKEND_CONNECTED": "Backend conectado",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Fallback en cache activo",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback predeterminado activo",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Valores predeterminados de fallback activos",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Guardando a traves del backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Guardado en el servicio backend",
    "RUNTIME_SAVE_FAILED": "Guardado fallido",
    "RUNTIME_LOAD_FAILED": "Carga fallida",
    "RUNTIME_CONNECTED": "Conectado",
    "RUNTIME_LOGIN_REQUIRED": "Inicio de sesion requerido",
    "RUNTIME_SAVED": "Guardado",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI lista - runtime pendiente",
    "RUNTIME_BACKEND_REJECTED_MODEL": "El servicio selector backend protegido rechazo o no pudo guardar la opcion de modelo solicitada.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "El servicio selector backend protegido rechazo o no pudo guardar el cambio de enrutamiento WF1 solicitado.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "El selector ahora lee la configuracion activa, el enrutamiento Qwen y las opciones permitidas desde el servicio backend protegido.",
    "RUNTIME_WF1_SELECTOR_CACHED": "El servicio backend del selector no esta disponible ahora mismo, asi que se usa el ultimo estado del selector en cache.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Los valores predeterminados del selector estan activos porque no se pudo cargar ningun estado backend o en cache.",
    "RUNTIME_WF1_SELECTOR_SAVED": "El servicio selector backend protegido actualizo la configuracion de enrutamiento WF1 activa y actualizo la cache del dominio runtime.",
    "FRONTEND_VERSION_TITLE": "Version frontend",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Este selector controla la version frontend activa para todos los usuarios. FeV2.0.0 esta activo.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Este selector lee la version frontend activa desde config_domain_registry. El runtime se resuelve en FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "No se pudo cargar la configuracion backend de version frontend, asi que el valor predeterminado codificado FeV2.0.0 permanece activo hasta que el bootstrap de inicio pueda volver a leer el servicio protegido.",
    "FRONTEND_VERSION_HELPER_SAVED": "La version frontend activa se guardo en config_domain_registry. Una actualizacion completa o la proxima carga de la app aplica el valor runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "El servicio backend de control de version frontend no pudo guardar la version global solicitada.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Version frontend activa.",
    "CHAT_DELETE_WINDOW_TITLE": "Ventana de eliminacion de chat",
    "CHAT_DELETE_HELPER": "Este valor controla la ventana de disponibilidad de Eliminar para todos en segundos. La guarda backend cambia inmediatamente despues de guardar. La visibilidad de la burbuja cambia despues de una actualizacion completa o la proxima carga de la app.",
    "CHAT_DELETE_HELPER_FALLBACK": "No se pudo cargar el servicio backend de control de eliminacion de chat, asi que el valor predeterminado codificado permanece activo hasta que el bootstrap de inicio pueda volver a leer el servicio protegido.",
    "CHAT_DELETE_HELPER_SAVED": "La ventana de disponibilidad de Eliminar para todos se guardo en config_domain_registry. La guarda backend cambia inmediatamente. La visibilidad de la burbuja cambia despues de una actualizacion completa o la proxima carga de la app.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "El servicio backend de control de eliminacion de chat no pudo guardar el valor de ventana solicitado.",
    "CHAT_DELETE_WINDOW_LABEL": "Ventana de Eliminar para todos",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} s",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Guarda el valor en segundos enteros. El valor actual de produccion es 86400 segundos = 1 dia.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Segundos de la ventana",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Ingresa un numero entero mayor o igual a 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Guardar ventana de eliminacion",
    "GUEST_BANNER_CONTROL_TITLE": "Banner de invitado",
    "GUEST_BANNER_CONTROL_LABEL": "Chat QR de invitado",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Mostrar banner de invitado para todos los usuarios",
    "GUEST_BANNER_CONTROL_HELPER": "Controla el banner de invitado fijo y la duración del token QR pendiente.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "La alternativa local está activa para los controles del banner de invitado.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Controles del banner de invitado guardados.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "No se pudieron guardar los controles del banner de invitado.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} sesiones de invitado revocadas.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "TTL de QR pendiente (minutos)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "TTL de QR pendiente actual: {count} minutos.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Introduce un número entero positivo de minutos.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Guardar banner de invitado",
    "GUEST_QR_LOADING": "Preparando QR de invitado...",
    "GUEST_QR_READY": "Escanea para abrir el chat de invitado temporal.",
    "GUEST_QR_ALT": "Código QR del chat de invitado",
    "GUEST_QR_LOAD_FAILED": "No se pudo preparar el QR de invitado.",
    "GUEST_SESSION_ACTIVE": "El invitado está conectado.",
    "GUEST_PUBLIC_TITLE": "Chat de invitado",
    "GUEST_PUBLIC_CONNECTING": "Conectando...",
    "GUEST_PUBLIC_CONNECTED": "Conectado",
    "GUEST_PUBLIC_UNAVAILABLE": "Este enlace de invitado no está disponible.",
    "GUEST_PUBLIC_SEND_FAILED": "No se pudo enviar el mensaje.",
    "UI_TEXTS_RUNTIME_TITLE": "Entorno de ejecución de idioma de la IU",
    "UI_TEXTS_RUNTIME_BACKEND": "El entorno de ejecución de idioma de la IU está leyendo desde el servicio de backend protegido. Los cambios se aplicarán la próxima vez que se cargue la aplicación por completo.",
    "UI_TEXTS_RUNTIME_CACHED": "El servicio de entorno de ejecución de idioma de la IU del backend no está disponible en este momento, por lo que los valores predeterminados locales o en caché están activos.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "Los valores predeterminados del entorno de ejecución de idioma de la IU están activos porque no se pudo cargar ningún estado de backend o en caché.",
    "UI_TEXTS_RUNTIME_SAVED": "Se guardó el control del entorno de ejecución de idioma de la IU. Se requiere una actualización completa o la próxima carga de la aplicación para que los usuarios reciban la nueva puerta de idioma.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "El servicio de backend protegido no pudo guardar el cambio solicitado en el entorno de ejecución de idioma de la IU.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Aplicación del idioma del dispositivo",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Habilitar idiomas de la IU en tiempo de ejecución",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Los usuarios pueden recibir cargas útiles de texto de la IU para su idioma almacenado o del dispositivo.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Todos los usuarios están obligados a usar el texto de la IU en inglés y se ignora el idioma del dispositivo.",
    "PROFILE_VISIBILITY_TITLE": "Visibilidad del perfil",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Debes iniciar sesion para gestionar la visibilidad de la cuenta.",
    "PROFILE_VISIBILITY_HELPER": "Este interruptor actualiza solo el estado de visibilidad de tu cuenta. La detectabilidad y el comportamiento de lista de banners permanecen sin cambios en esta fase.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "No se pudo cargar la visibilidad del perfil ahora mismo.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "No se pudo actualizar la visibilidad del perfil ahora mismo.",
    "PROFILE_VISIBILITY_SAVED": "La visibilidad de tu cuenta ahora es {visibility}. Las marcas de detectabilidad permanecen sin cambios en esta fase.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Cuenta publica",
    "PROFILE_VISIBILITY_STORED": "Visibilidad almacenada",
    "WF1_MODEL_CONTROL_TITLE": "Control de modelo WF1",
    "WF1_ENABLE_TRANSLATION": "Activar traduccion / pivote",
    "WF1_TRANSLATION_ACTIVE": "La traduccion por IA esta activa.",
    "WF1_TRANSLATION_INACTIVE": "WF1 sigue ejecutandose, pero el texto fuente se copia y el pivote se marca como inactivo.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Slot runtime activo",
    "WF1_ALLOW_SAME_LANGUAGE": "Permitir IA para pares del mismo idioma",
    "WF1_SAME_LANGUAGE_ACTIVE": "Los pares del mismo idioma siguen el enrutamiento WF1 normal.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Los pares del mismo idioma omiten la IA y almacenan Sin idioma pivote activo.",
    "WF1_QWEN_ROUTING": "Enrutamiento de pares Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Los idiomas marcados abajo usan Qwen-Max cuando el par es el mismo idioma marcado, un idioma marcado con ingles, o dos idiomas no ingleses marcados. De lo contrario, el modelo principal seleccionado permanece activo.",
    "WF1_OPENROUTER_TEST_SLOT": "Slot de prueba OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Slot de prueba OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Solo prueba de calidad",
    "WF1_OPENROUTER_HELPER": "Este slot solo es editable para pruebas temporales de calidad de OpenRouter. No cambia la ruta operativa de enrutamiento de pares Qwen a menos que este slot se convierta en el modelo activo.",
    "WF1_LABEL": "Etiqueta",
    "WF1_PRODUCT": "Producto",
    "WF1_MODEL": "Modelo",
    "WF1_PROVIDER_OPENROUTER": "Proveedor: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secreto: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Slot de prueba OpenRouter - Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max via OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Precio de lista de Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Precio de lista de OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Precio de lista de OpenRouter",
    "LANGUAGE_ENGLISH": "Ingles",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Chino (simplificado)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Chino (tradicional)",
    "LANGUAGE_JAPANESE": "Japones",
    "LANGUAGE_KOREAN": "Coreano",
    "LANGUAGE_PERSIAN": "Persa",
    "LANGUAGE_TURKISH_ISTANBUL": "Turco (Estambul)",
    "LANGUAGE_ARABIC": "Arabe",
    "LANGUAGE_FRENCH": "Frances",
    "LANGUAGE_GERMAN": "Aleman",
    "LANGUAGE_SPANISH": "Espanol",
    "LANGUAGE_PORTUGUESE": "Portugues",
    "LANGUAGE_ITALIAN": "Italiano",
    "LANGUAGE_RUSSIAN": "Ruso",
    "LANGUAGE_DUTCH": "Neerlandes",
    "LANGUAGE_VIETNAMESE": "Vietnamita",
    "LANGUAGE_INDONESIAN": "Indonesio",
    "LANGUAGE_THAI": "Tailandes",
    "LANGUAGE_MALAY": "Malayo",
    "WF1_PRICING_CUSTOM": "Precios: modelo de slot personalizado - revisa el precio actual de OpenRouter",
    "WF1_SAVE_OPENROUTER_SLOT": "Guardar slot OpenRouter",
    "WF1_PRICING_LINE": "Entrada {input} - Salida {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secreto: {secret}",
    "ZONE_VISIBILITY_TITLE": "Control de visibilidad de zona",
    "ZONE_ENABLE": "Activar {zone}",
    "ZONE_ENABLED_NOTE": "{zone} puede aparecer para roles permitidos despues de la proxima carga de la app.",
    "ZONE_DISABLED_NOTE": "{zone} se trata como ausente para usuarios que no son S_Admin despues de la proxima carga de la app.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin omite esta lista de roles y siempre mantiene el acceso.",
    "ZONE_ROLE_LOCKED": "Las selecciones de roles estan temporalmente bloqueadas mientras esta zona esta desactivada y volveran exactamente como se guardaron cuando la zona se active de nuevo.",
    "ZONE_LCAC_CONTROL": "Control LCAC",
    "ZONE_RCAC_CONTROL": "Control RCAC",
    "ZONE_LCAC_DESCRIPTION": "Controla la existencia de la zona reservada izquierda y los roles que pueden verla.",
    "ZONE_RCAC_DESCRIPTION": "Controla la existencia de la zona reservada derecha y los roles que pueden verla.",
    "ZONE_VISIBILITY_BACKEND": "El bootstrap de visibilidad de zona ahora lee desde el servicio backend protegido. Los cambios se aplican en la proxima carga de la app.",
    "ZONE_VISIBILITY_CACHED": "El servicio backend de visibilidad de zona no esta disponible ahora mismo, asi que estan activos los valores en cache o locales.",
    "ZONE_VISIBILITY_DEFAULTS": "Los valores predeterminados de visibilidad de zona estan activos porque no se pudo cargar ningun estado backend o en cache.",
    "ZONE_VISIBILITY_SAVED": "El bootstrap de visibilidad de zona se guardo. Se requiere una recarga forzada o la proxima carga de la app para aplicar el runtime.",
    "ZONE_VISIBILITY_SAVE_FAILED": "El servicio backend protegido no pudo guardar el cambio de visibilidad de zona solicitado.",
    "ROLE_MEMBER": "Miembro",
    "ROLE_STAFF": "Personal",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Activa las notificaciones para recibir nuevos mensajes.",
    "MAIN_LOG_OUT": "Cerrar sesion",
    "NOTIFICATION_NEW_MESSAGE": "Nuevo mensaje",
    "NOTIFICATION_UNREAD_MESSAGE": "Tienes un mensaje no leido.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Vista completa",
    "MEDIA_AUDIO_ATTACHMENT": "Adjunto de audio",
    "MEDIA_FILE_FALLBACK": "Archivo",
    "MEDIA_DOWNLOAD_READY": "Adjunto listo para descargar",
    "MEDIA_TYPE_UNSUPPORTED": "Tipo no compatible para vista completa",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Imagen anterior",
    "MEDIA_NEXT_IMAGE_ARIA": "Imagen siguiente",
    "MEDIA_OPEN_ORIGINAL": "Abrir original",
    "MEDIA_DOWNLOAD": "Descargar",
    "MEDIA_CLOSE_ARIA": "Cerrar",
    "MEDIA_PROFILE_PICTURE_ARIA": "Foto de perfil de {name}",
    "MEDIA_PROFILE_ALT": "Perfil de {name}",
    "MEDIA_UPLOAD_FAILED": "Subida fallida",
    "MEDIA_BACKEND_TOKEN_ERROR": "Error de token backend",
    "MEDIA_UPLOAD_URL_MISSING": "Critico: falta la URL de subida en la respuesta backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Falta token de autenticacion para subida de chat",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "La solicitud de token de subida de chat fallo",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Respuesta de subida de chat invalida",
    "MEDIA_GCS_UPLOAD_FAILED": "Subida GCS fallida",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Falta nombre de archivo o contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Falta file_path",
    "BLOCK_NOTICE_TITLE": "Aviso de bloqueo permanente",
    "BLOCK_NOTICE_MESSAGE": "Tu cuenta ha sido suspendida temporalmente debido a una infraccion de la politica.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Si crees que esto requiere seguimiento, contacta con",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "por email.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Usuario desconocido",
    "GENERAL_GUEST": "Invitado",
    "ADVISOR_FOR_CLIENT": "Asesor para {client_display_name}",
    "GUEST_FOR_CLIENT": "Invitado para {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "El token y la contrasena son obligatorios",
    "AUTH_ERROR_REQUEST_BODY_JSON": "El cuerpo de la solicitud debe ser JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Token de invitacion invalido o caducado",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Error al establecer la contrasena: falta sesion o usuario",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Error al establecer la contrasena durante el inicio de sesion",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Error al generar token admin",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Inicio de sesion fallido: falta sesion o usuario",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registro correcto. Revisa tu email para la verificacion.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Error desconocido en el registro",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Procesamiento de token invalido",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "El token de acceso es obligatorio",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "La vista previa del hash de token requiere pista de email desde la URL de redireccion",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "No se puede resolver la identidad para este token",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Solo Usuario Cero puede acceder al servicio selector LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Solo Usuario Cero puede acceder al servicio de control de visibilidad de zona.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Solo Usuario Cero puede acceder al servicio de control de version frontend.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Solo Usuario Cero puede inspeccionar la version frontend de otro usuario.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Solo Usuario Cero puede acceder al servicio de control de eliminacion de chat.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Solo el Usuario Cero puede acceder al servicio de control del entorno de ejecución de idioma de la IU.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Solo Usuario Cero puede eliminar permanentemente una cuenta de usuario.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Payload de solicitud invalido.",
    "API_ERROR_INTERNAL_SERVER": "Error interno del servidor",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funcion faltante en backend (recarga requerida)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Solo se permite DB RPC para transiciones delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Espera antes de enviar otro mensaje.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Mensaje enviado correctamente.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "El servicio de contacto no esta disponible.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "El envio del mensaje fallo.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "El nombre es obligatorio.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "El email es invalido.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "El mensaje es obligatorio.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "El payload del selector es obligatorio.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "El payload de visibilidad de zona es obligatorio.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "El payload de version frontend es obligatorio.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "El payload de control de eliminacion de chat es obligatorio.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Se requiere la carga útil de control del entorno de ejecución de idioma de la IU.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "El id de usuario autenticado es obligatorio.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "El id de usuario visor autenticado es obligatorio.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "El id de usuario actor autenticado es obligatorio.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id es obligatorio.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id es obligatorio.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "La lista owner_user_ids es obligatoria.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email es obligatorio.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by es obligatorio.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "El runtime de busqueda esta desactivado por la version frontend global.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "No tienes permiso para cancelar esta invitacion pendiente.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Esta invitacion ya no se puede cancelar porque el usuario ya esta registrado.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Invitacion pendiente no encontrada.",
    "INVITE_REPLY_ALREADY_MEMBER": "Felicidades, tu amigo ({invitee_email}) ya esta registrado en esta app y es miembro de este espacio de trabajo.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Hay una invitacion pendiente para {invitee_email}, pero no se pudo activar el email de reintento. Revisa los registros de correo.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Se creo el registro de invitacion para {invitee_email}, pero no se pudo confirmar la entrega del email. Intentalo mas tarde o revisa los registros de correo.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "No se pudo crear el registro de invitacion. Intentalo mas tarde.",
    "INVITE_REPLY_SYSTEM_ERROR": "Error del sistema durante el proceso de invitacion: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Error de configuracion backend: faltan credenciales de Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Error de configuracion backend: URL de Supabase invalida",
    "CHAT_ERROR_ACCESS_DENIED": "Acceso denegado",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "El contenido no puede estar vacio para mensajes de texto",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "No se pudo determinar el ID de conversacion",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Falta el contexto de autenticacion RPC",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC devolvio un payload de mensaje invalido",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Insercion fallida, no se devolvieron datos",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations debe ser una lista",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Payload de operacion invalido",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type no compatible",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id es obligatorio",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Mensaje no encontrado",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "La eliminacion solo esta permitida en tu propio mensaje",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Eliminar para todos ya no esta disponible para este mensaje",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Eliminar para todos fallo",
    "API_ERROR_SERVER_CONFIGURATION": "Error de configuracion del servidor",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Falta encabezado secreto de webhook",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Fuente de webhook no autorizada",
    "API_ERROR_BACKEND_CONFIGURATION": "Error de configuracion backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Error de atributo de modulo: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Error antes de eliminar la invitacion al quitar el usuario auth en espera.",
    "CHAT_ERROR_DB": "Error DB: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "PERMISSION_MIC_PERMISSION": "",
    "PERMISSION_MIC_ACCESS": "",
    "PERMISSION_TOGGLE_MIC_ARIA": "",
    "PERMISSION_MIC_ON_TOOLTIP": "",
    "PERMISSION_MIC_ENABLE_TOOLTIP": "",
    "PERMISSION_MIC_BLOCKED_TOOLTIP": "",
    "PERMISSION_MIC_DISABLE_HELP": "",
    "PERMISSION_MIC_BLOCKED_HELP": "",
    "LIVE_CONV_MIC_PROMPT_TITLE": "",
    "LIVE_CONV_MIC_PROMPT_BODY": "",
    "LIVE_CONV_MIC_PROMPT_ALLOW": "",
    "LIVE_CONV_MIC_PROMPT_CANCEL": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
