# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/fa.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "اصلی",
    "APP_TITLE": "پلتفرم هوش مصنوعی OTMEGA",
    "APP_SUBTITLE": "ادوایزر هوش مصنوعی",
    "CHAT_PLACEHOLDER": "پیام خود را بنویسید...",
    "CHAT_SEND_BUTTON": "ارسال",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 ادوایزر ممکن است اشتباه کند؛ بنابراین پاسخ را دوباره بررسی کنید.",
    "STATUS_ONLINE": "آنلاین",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "منو",
    "ICON_NEW_CHAT": "چت جدید",
    "ICON_HISTORY": "تاریخچه",
    "ICON_TEMPLATES": "قالب‌ها",
    "ICON_SETTINGS": "تنظیمات",
    "ICON_USER_PROFILE": "پروفایل کاربر",
    "ICON_QUICK_ACTIONS": "اقدام‌های سریع",
    "ICON_PINNED": "سنجاق‌شده",
    "ICON_GALLERY": "گالری",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "نصب برنامه",
    "PWA_ANDROID_MSG": "برای تجربه بهتر و دسترسی آفلاین، این برنامه را روی دستگاه خود نصب کنید.",
    "PWA_IOS_MSG": "برای نصب این برنامه روی iPhone/iPad:\n1. روی دکمه اشتراک‌گذاری پایین بزنید\n2. گزینه «افزودن به صفحه اصلی» را انتخاب کنید",
    "PWA_BTN_INSTALL": "نصب",
    "PWA_BTN_LATER": "شاید بعداً",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "ورود به شبکه ادوایزر",
    "AUTH_HEADER_SIGNUP": "ایجاد حساب یکپارچه",
    "AUTH_HEADER_LOGIN_NETWORK": "ورود به شبکه ادوایزر",
    "AUTH_HEADER_SIGNUP_UNIFIED": "ایجاد حساب یکپارچه",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "ورود",
    "AUTH_BUTTON_SIGNUP": "ایجاد حساب",
    "AUTH_BUTTON_GOOGLE": "ادامه با Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "فراموشی رمز عبور",
    "AUTH_BUTTON_SEND_RESET_LINK": "ارسال لینک بازیابی",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "حساب کاربری ندارید؟ ثبت‌نام کنید",
    "AUTH_PROMPT_LOGIN": "حساب کاربری دارید؟ وارد شوید",
    "AUTH_HELPER_TEXT_SIGNUP": "شما در حال ایجاد یک حساب یکپارچه هستید که با آن می‌توانید به همه ادوایزرهای این پلتفرم دسترسی داشته باشید.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "شما در حال ایجاد یک حساب یکپارچه هستید که با آن می‌توانید به همه ادوایزرهای این پلتفرم دسترسی داشته باشید.",
    "AUTH_HELPER_TEXT_LOGIN": "از همان حسابی استفاده کنید (ایمیل/رمز عبور یا Google) که برای ادوایزرهای دیگر در این شبکه استفاده کرده‌اید.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "از همان حسابی استفاده کنید (ایمیل/رمز عبور یا Google) که برای ادوایزرهای دیگر در این شبکه استفاده کرده‌اید.",
    "AUTH_FORGOT_PASSWORD_LINK": "رمز عبور خود را فراموش کرده‌اید؟",
    "AUTH_FORGOT_PASSWORD_TITLE": "بازیابی رمز عبور",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "آدرس ایمیل خود را وارد کنید تا لینک بازیابی رمز عبور برای شما ارسال شود.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "ایمیل",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "در حال ورود...",
    "AUTH_STATUS_LOADING_SIGNUP": "در حال ایجاد حساب شما...",
    "AUTH_STATUS_LOADING_RESET": "در حال ارسال لینک بازیابی...",
    "AUTH_STATUS_SUCCESS_LOGIN": "ورود موفق بود! در حال بارگذاری مجدد...",
    "AUTH_STATUS_SUCCESS_RESET": "لینک بازیابی با موفقیت ارسال شد. لطفاً ایمیل خود را بررسی کنید.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "لینک بازیابی رمز عبور با موفقیت ارسال شد. لطفاً ایمیل خود را بررسی کنید.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "ایمیل یا رمز عبور نامعتبر است.",
    "AUTH_ERROR_EMAIL_EXISTS": "حسابی با این ایمیل از قبل در شبکه ادوایزر وجود دارد.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "حسابی با این ایمیل از قبل وجود دارد. لطفاً وارد شوید. شما اکنون عضو این موارد هستید:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "حسابی با این ایمیل از قبل در شبکه ادوایزر وجود دارد. لطفاً این پنجره را ببندید و با همان ایمیل و رمز عبور قبلی خود از بخش «ورود» استفاده کنید.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "شما اکنون عضو این موارد هستید:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "ایمیل و رمز عبور الزامی است.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "حساب ایجاد شد اما راه‌اندازی عضویت ناموفق بود. لطفاً با پشتیبانی تماس بگیرید.",
    "AUTH_ERROR_DEFAULT": "خطایی رخ داد. لطفاً دوباره تلاش کنید.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "بار کنترلی بنر مهمان الزامی است.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "فقط کاربر صفر می‌تواند کنترل‌های بنر مهمان را به‌روزرسانی کند.",
    "AUTH_FORGOT_PASSWORD_ERROR": "ارسال لینک بازیابی ناموفق بود. لطفاً دوباره تلاش کنید.",
    "INVITE_REPLY_EMAIL_SENT": "ایمیل دعوت Collabra به دوست شما در {invitee_email} ارسال شد.",
    "INVITE_REPLY_EMAIL_RESENT": "ایمیل دعوت Collabra دوباره به دوست شما در {invitee_email} ارسال شد.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "نمایش رمز عبور",
    "AUTH_PASSWORD_TOGGLE_HIDE": "پنهان کردن رمز عبور",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "تأیید",
    "GENERAL_CANCEL": "لغو",
    "GENERAL_CLOSE": "بستن",
    "GENERAL_SEND": "ارسال",
    "GENERAL_SEARCH": "جستجو",
    "GENERAL_RESET": "بازنشانی",
    "GENERAL_ENABLE": "فعال‌سازی",
    "GENERAL_LOADING": "در حال بارگذاری...",
    "GENERAL_DELETE": "حذف",
    "GENERAL_DELETING": "در حال حذف...",
    "GENERAL_SAVE_PASSWORD": "ذخیره رمز عبور",
    "AUTH_REMEMBER_EMAIL_LABEL": "به خاطر سپردن ایمیل",
    "GENERAL_SAVING": "در حال ذخیره...",
    "GENERAL_SENDING": "در حال ارسال...",
    "GENERAL_REMOVING": "در حال حذف...",
    "GENERAL_CONFIRM_REMOVAL": "تأیید حذف",
    "GENERAL_EMPTY": "خالی",
    "GENERAL_UNAVAILABLE": "در دسترس نیست",
    "GENERAL_ENABLED": "فعال",
    "GENERAL_DISABLED": "غیرفعال",
    "GENERAL_GRANTED": "اعطا شده",
    "GENERAL_DENIED": "رد شده",
    "GENERAL_DEFAULT": "پیش‌فرض",
    "GENERAL_UNSUPPORTED": "پشتیبانی‌نشده",
    "GENERAL_PUBLIC": "عمومی",
    "GENERAL_PRIVATE": "خصوصی",
    "GENERAL_USERNAME": "نام کاربری",
    "GENERAL_EMAIL": "ایمیل",
    "GENERAL_YOU": "شما",
    "GENERAL_USER": "کاربر",
    "GENERAL_UNKNOWN": "نامشخص",
    "GENERAL_VISITOR": "بازدیدکننده",
    "GENERAL_PROFILE": "پروفایل",
    "GENERAL_BANNER": "بنر",
    "GENERAL_UNKNOWN_BANNER": "بنر نامشخص",
    "GENERAL_ADVISOR_BANNER": "بنر ادوایزر",
    "GENERAL_NOT_AVAILABLE": "ناموجود",
    "GENERAL_NOT_SELECTED": "انتخاب نشده",
    "GENERAL_NO_EMAIL_FOUND": "ایمیلی یافت نشد",
    "GENERAL_USER_ZERO_ONLY": "فقط User Zero",
    "GENERAL_CONNECTION_STATE": "وضعیت اتصال",
    "GENERAL_DISPLAY_ONLY": "فقط نمایش",
    "GENERAL_TEXTAREA": "کادر متن",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "منو (LCAC)",
    "HEADER_CHAT_CCAC": "چت (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "اقدام‌های سریع (RCAC)",
    "HEADER_CHANGE_STATUS": "تغییر وضعیت",
    "HEADER_OT_COIN_BALANCE": "موجودی OT Coin",
    "HEADER_ALT_USER": "کاربر",
    "STATUS_BUSY": "مشغول",
    "STATUS_AWAY": "دور از دسترس",
    "STATUS_OFFLINE": "آفلاین",
    "STATUS_INVISIBLE": "نامرئی",
    "NETWORK_CHECKING_CONNECTION": "در حال بررسی اتصال...",
    "NETWORK_ONLINE_LATENCY": "آنلاین (تأخیر: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "شبکه: خوب (برای ping بزنید)",
    "CHAT_TARGET_ALT": "هدف چت",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "جستجو...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "باز کردن تصویر پروفایل {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "ورودی پیام",
    "CHAT_TOGGLE_VIEW_ARIA": "تغییر نما",
    "CHAT_ADD_USER_ARIA": "افزودن کاربر",
    "CHAT_ATTACH_ARIA": "پیوست",
    "CHAT_MIC_ARIA": "میکروفون",
    "CHAT_SEND_ARIA": "ارسال",
    "CHAT_SEARCH_ARIA": "جستجو",
    "CHAT_OPEN_SEARCH_ARIA": "باز کردن جستجو",
    "CHAT_CLOSE_SEARCH_ARIA": "بستن جستجو",
    "CHAT_ATTACHMENT_ALT": "پیوست",
    "CHAT_PREVIEW_ALT": "پیش‌نمایش",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "حذف پیوست",
    "CHAT_REPLYING_TO": "در پاسخ به",
    "CHAT_CANCEL_REPLY_ARIA": "لغو پاسخ",
    "CHAT_UPLOADING": "در حال آپلود...",
    "CHAT_LOADING_CHATS": "در حال بارگذاری چت‌ها...",
    "CHAT_SEND_FAILED": "ارسال ناموفق بود",
    "CHAT_SEND_FAILED_RETRY": "ارسال ناموفق بود. لطفاً دوباره تلاش کنید.",
    "CHAT_RETRY": "تلاش مجدد",
    "CHAT_EDITED": "ویرایش‌شده",
    "CHAT_TYPING": "در حال نوشتن",
    "CHAT_LOADING": "در حال بارگذاری",
    "CHAT_PENDING_INVITATION": "دعوت در انتظار",
    "CHAT_PENDING_INVITATION_MIN": "{count} دقیقه دعوت در انتظار",
    "CHAT_PENDING_INVITATION_HR": "{count} ساعت دعوت در انتظار",
    "CHAT_PENDING_INVITATION_DAY": "{count} روز دعوت در انتظار",
    "CHAT_WAITING_FOR_YOU": "{label} - در انتظار شما",
    "CHAT_PENDING_ACCEPTANCE": "{label} - در انتظار پذیرش",
    "CHAT_MICROPHONE_ACCESS_DENIED": "دسترسی به میکروفون رد شد.",
    "CHAT_UPLOAD_FAILED": "آپلود ناموفق بود: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "آپلود به اتصال اینترنت نیاز دارد. لطفاً وقتی آنلاین هستید دوباره تلاش کنید.",
    "CHAT_ERROR_AUTH": "خطای احراز هویت",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "نام فایل یا content_type موجود نیست",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id یا target_id موجود نیست",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id برای آپلود غیرآواتار موجود نیست",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path آواتار نامعتبر است",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "کلاینت سرویس Supabase در دسترس نیست",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "تأیید خواندن آواتار فقط در زمینه چت ادوایزر معتبر است",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "پیام جریان آواتار یافت نشد یا واجد شرایط تأیید خواندن نیست",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "نهایی‌سازی پیام آواتار به‌عنوان خوانده‌شده ناموفق بود",
    "CHAT_ATTACHMENT_COUNT_ONE": "۱ پیوست",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} پیوست",
    "CHAT_VOICE_NOTE": "یادداشت صوتی",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "چت در دسترس نیست. این کاربر شما را مسدود کرده است.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "چت در دسترس نیست. شما این کاربر را مسدود کرده‌اید.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "دسترسی حساب طبق سیاست مسدود شده است.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "چت در دسترس نیست. این حساب توسط User Zero به‌صورت نهایی مسدود شده است.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "چت در دسترس نیست. مسدودی متقابل فعال است.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "چت به‌دلیل سیاست مسدودی در دسترس نیست.",
    "MESSAGE_PREVIEW_PHOTO": "عکس",
    "MESSAGE_PREVIEW_VOICE": "پیام صوتی",
    "MESSAGE_PREVIEW_VIDEO": "ویدئو",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "فایل",
    "MESSAGE_PREVIEW_MESSAGE": "پیام",
    "MESSAGE_PREVIEW_SYSTEM": "پیام سیستمی",
    "MESSAGE_PREVIEW_NEW": "پیام جدید",
    "MESSAGE_UNKNOWN_FILE": "فایل نامشخص",
    "MESSAGE_AUDIO_ATTACHMENT": "پیوست صوتی",
    "MESSAGE_FILE_ATTACHMENT": "پیوست",
    "BANNER_INVITED_BY": "دعوت‌شده توسط {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "نتایج جستجو",
    "SEARCH_QUERY_LABEL": "عبارت جستجو:",
    "SEARCH_LOADING_VISIBILITY": "در حال بارگذاری وضعیت نمایش جستجو...",
    "SEARCH_NO_RESULTS": "در محدوده جستجوی فعلی نتیجه‌ای یافت نشد.",
    "SHARE_WITH_COLLABRA": "اشتراک‌گذاری با Collabra",
    "SHARE_SEND_TO": "ارسال به",
    "SHARE_SELECT_ONE_BANNER": "یک بنر را انتخاب کنید",
    "SHARE_BANNER_LIST_ARIA": "فهرست بنرها",
    "SHARE_NO_MATCHING_BANNER": "بنر مطابقی وجود ندارد",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "افزودن نظر...",
    "SHARE_RECENT_CHATS": "چت‌های اخیر",
    "SHARE_LEFT_LIST": "فهرست چپ",
    "SHARE_RIGHT_LIST": "فهرست راست",
    "SHARE_UNTITLED_BANNER": "بنر بدون عنوان",
    "SHARE_SHARED_CONTENT": "محتوای اشتراک‌گذاری‌شده",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "محتوای اشتراک‌گذاری‌شده باز نشد.",
    "SHARE_OPEN_BANNER_FAILED": "باز کردن بنر انتخاب‌شده ممکن نبود.",
    "SHARE_ONE_PHOTO_SELECTED": "۱ عکس انتخاب شد",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} عکس انتخاب شد",
    "SHARE_ONE_FILE_SELECTED": "۱ فایل انتخاب شد",
    "SHARE_MANY_FILES_SELECTED": "{count} فایل انتخاب شد",
    "FORWARD_MESSAGE_TITLE": "بازارسال پیام",
    "FORWARD_SELECT_RECIPIENTS": "گیرندگان را انتخاب کنید",
    "FORWARD_NO_OTHER_BANNER": "بنر دیگری در دسترس نیست.",
    "FORWARD_SEND_TO_COUNT": "ارسال به {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "حداقل یک بنر را انتخاب کنید.",
    "FORWARD_FAILED_DEFAULT": "بازارسال ناموفق بود. لطفاً دوباره تلاش کنید.",
    "FORWARD_PARTIAL_SENT": "{count} مورد ارسال شد. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "پیام منبع برای بازارسال یافت نشد",
    "FORWARD_NO_FORWARDABLE_CONTENT": "این پیام هنوز محتوای قابل بازارسال ندارد",
    "FORWARD_DESTINATION_MISSING": "مقصد بازارسال موجود نیست",
    "FORWARD_MESSAGE_PREVIEW": "پیام بازارسال‌شده",
    "MENU_PASTE": "جای‌گذاری",
    "MENU_COPY": "کپی",
    "MENU_REPLY": "پاسخ",
    "MENU_FORWARD": "بازارسال",
    "MENU_REMOVE_INVITATION": "حذف دعوت",
    "MENU_REMOVE_FROM_LIST": "حذف از فهرست",
    "MENU_GOODBYE_GUEST": "خداحافظ مهمان",
    "MENU_ADD_TO_LIST": "افزودن به فهرست",
    "MENU_REJECT_INVITATION": "رد دعوت",
    "MENU_FRONTEND_VERSION": "نسخه فرانت‌اند",
    "MENU_BANNER_HEADER": "بنر - {zone}",
    "MENU_BANNER_INFO": "اطلاعات بنر: {title}",
    "MENU_MESSAGE_BUBBLE": "حباب پیام",
    "MENU_CHAT_CANVAS_HEADER": "بوم چت - {zone}",
    "MENU_CANVAS_INFO": "اطلاعات بوم",
    "MENU_CHAT_CANVAS_SUBLABEL": "ناحیه گفت‌وگو / سطح چت فعلی",
    "MENU_INPUT_AREA_HEADER": "ناحیه ورودی - {zone}",
    "MENU_INPUT_AREA_INFO": "اطلاعات ناحیه ورودی: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "سطح پایینی تایپ و ابزارهای اقدام",
    "MENU_HEADER": "هدر - {zone}",
    "MENU_HEADER_INFO": "اطلاعات هدر: {title}",
    "MENU_HEADER_DESCRIPTION": "ناوبری بالایی و کنترل‌های صفحه",
    "MENU_ZONE_HEADER": "زون - {zone}",
    "MENU_ZONE_SPACE_INFO": "اطلاعات فضای زون",
    "MENU_EMPTY_LIST_SURFACE": "سطح خالی/فهرست",
    "MENU_BLOCK": "مسدود کردن",
    "MENU_UNBLOCK": "رفع مسدودی",
    "MENU_HIDE_IN_SEARCH": "پنهان کردن در جستجو",
    "MENU_UNHIDE_IN_SEARCH": "نمایش دوباره در جستجو",
    "MENU_VISIBLE_IN_SEARCH": "قابل مشاهده در جستجو",
    "MENU_HIDDEN_IN_SEARCH": "پنهان در جستجو",
    "MENU_VISIBLE_IN_USER_LIST": "قابل مشاهده در فهرست کاربران",
    "MENU_HIDDEN_IN_USER_LIST": "پنهان در فهرست کاربران",
    "MENU_NOT_BLOCKED": "مسدود نیست",
    "MENU_BLOCKED": "مسدود شده",
    "MENU_FRONTEND_VERSION_LOADING": "در حال بارگذاری...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "در حال بارگذاری مقدار هر بنر از بک‌اند. تا زمانی که پاسخ پایگاه داده برسد، هیچ گزینه‌ای فعال علامت‌گذاری نمی‌شود.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "مقدار بک‌اند بارگذاری نشد. هیچ گزینه فعال قابل اعتمادی نمایش داده نمی‌شود.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "مقدار صریح پایگاه داده برای هر بنر {overrideVersion} است. مقدار پیش‌فرض سراسری {globalDefaultVersion} است. کاربر هدف باید برنامه را کامل refresh کند یا دوباره باز کند تا startup bootstrap آن را اعمال کند.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "هیچ مقدار صریحی برای هر بنر در پایگاه داده ذخیره نشده است. FeV2.0.0 به‌صورت پیش‌فرض فعال است. مقدار پیش‌فرض سراسری {globalDefaultVersion} است.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "مقدار صریح پایگاه داده برای هر بنر پس از بارگذاری مجدد کامل برنامه هدف فعال می‌شود",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "هیچ مقدار صریحی برای هر بنر ذخیره نشده است؛ این وضعیت پیش‌فرض فردی FeV2.0.0 است",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "این گزینه با مقدار پیش‌فرض سراسری فعلی نیز برابر است",
    "MENU_DELETE_PERMANENT_CONFIRM": "آیا {target} برای همیشه از پایگاه داده حذف شود؟ این کار حساب، تاریخچه چت، وابستگی‌ها را حذف می‌کند و برای ورود مجدد آینده، مسیر دعوت کاملاً جدیدی را الزامی می‌کند.",
    "MENU_DELETE_PERMANENTLY": "حذف دائمی",
    "MENU_REFRESH_PAGE": "بازآوری صفحه",
    "MENU_LOG_OFF": "خروج",
    "MENU_HARD_RELOAD": "بارگذاری مجدد کامل",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "ایمیل (کاربر ادمین)",
    "AUTH_PASSWORD_PLACEHOLDER": "رمز عبور",
    "AUTH_CONNECTING": "در حال اتصال...",
    "AUTH_SIGNING_OUT": "در حال خروج...",
    "AUTH_BACK_TO_LOGIN": "بازگشت به ورود",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "پاسخ سرور نامعتبر است: توکنی یافت نشد.",
    "AUTH_LOGIN_FAILED": "ورود ناموفق بود",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "رمزهای عبور یکسان نیستند.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "رمزهای عبور یکسان نیستند!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "رمزهای عبور باید دقیقاً یکسان باشند.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "رمز عبور جدید",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "تأیید رمز عبور",
    "AUTH_CHANGE_PASSWORD": "تغییر رمز عبور",
    "AUTH_SAVING_PASSWORD": "در حال ذخیره...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "رمز عبور با موفقیت به‌روزرسانی شد.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "در حال حاضر امکان تغییر رمز عبور وجود ندارد.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "برای تغییر رمز عبور باید وارد شده باشید.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "تغییر نمایش رمز عبور جدید",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "تغییر نمایش تأیید رمز عبور",
    "REGISTER_TITLE": "تکمیل ثبت‌نام",
    "REGISTER_SUBTITLE": "لطفاً رمز عبور خود را به‌صورت دستی تنظیم کنید.",
    "REGISTER_CREATING_ACCOUNT": "در حال ایجاد حساب...",
    "REGISTER_FINISH_SETUP": "پایان راه‌اندازی",
    "REGISTER_FAILED_SET_PASSWORD": "تنظیم رمز عبور ناموفق بود",
    "INVITE_EMAIL_INSTRUCTION": "لطفاً ایمیل دعوت‌شونده را وارد کنید (قالب: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "دعوت",
    "INVITE_EMAIL_REQUIRED": "لطفاً ایمیل دعوت‌شونده را وارد کنید.",
    "INVITE_EMAIL_INVALID": "قالب ایمیل نامعتبر است. لطفاً از این قالب استفاده کنید: user@example.com",
    "PENDING_INVITATION_TITLE": "دعوت در انتظار",
    "PENDING_INVITATION_REMOVE_QUESTION": "این دعوت در انتظار از پایگاه داده حذف شود؟",
    "PENDING_INVITATION_KEEP": "نگه داشتن دعوت",
    "PENDING_INVITATION_REMOVAL_FAILED": "حذف ناموفق بود.",
    "REMOVE_FROM_LIST_TITLE": "حذف از فهرست",
    "REMOVE_FROM_LIST_WARNING": "آیا این کاربر اکنون از هر دو فهرست حذف شود؟ دسترسی چت فوراً قطع می‌شود. تنها مسیر بازگشت، دعوت جدید است.",
    "REMOVE_FROM_LIST_KEEP": "نگه داشتن کاربر در فهرست",
    "REMOVE_FROM_LIST_FAILED": "حذف از فهرست ناموفق بود.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "تنظیمات و وضعیت زنده",
    "PERMISSION_DIALOG_ARIA": "تنظیمات و وضعیت زنده",
    "PERMISSION_TRIGGER_ARIA": "ماشه پاپ‌آپ تنظیمات",
    "PERMISSION_CLOSE_ARIA": "بستن پاپ‌آپ مجوز",
    "PERMISSION_LIVE_STATUS": "وضعیت زنده",
    "PERMISSION_SYSTEM_PERMISSION": "مجوز سیستم",
    "PERMISSION_APP_PUSH": "Push برنامه",
    "PERMISSION_LOCATION_PERMISSION": "مجوز موقعیت مکانی",
    "PERMISSION_APP_LOCATION": "موقعیت برنامه",
    "PERMISSION_CONTROLS": "کنترل‌های مجوز",
    "PERMISSION_PUSH_NOTIFICATIONS": "اعلان‌های Push",
    "PERMISSION_LOCATION_ACCESS": "دسترسی به موقعیت مکانی",
    "PERMISSION_IN_APP_SETTINGS": "تنظیمات درون‌برنامه‌ای",
    "PERMISSION_ALERT_SOUND": "صدای هشدار",
    "PERMISSION_APP_BADGE": "نشان برنامه",
    "PERMISSION_PASSWORD_SETTINGS": "تنظیمات رمز عبور",
    "PERMISSION_NAVIGATION_STATUS": "وضعیت ناوبری",
    "PERMISSION_SELECTED_ZONE": "زون انتخاب‌شده",
    "PERMISSION_STAGED_CHAT_BANNER": "بنر چت مرحله‌بندی‌شده",
    "PERMISSION_CANVAS_CONTENT": "محتوای بوم",
    "PERMISSION_YOUR_DEVICES": "دستگاه‌های شما ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "بازآوری فهرست دستگاه‌ها",
    "PERMISSION_REFRESH_LIST": "بازآوری فهرست",
    "PERMISSION_NO_REGISTERED_DEVICES": "هیچ دستگاه ثبت‌شده‌ای یافت نشد.",
    "PERMISSION_RESIZE_POPUP_ARIA": "تغییر اندازه پاپ‌آپ تنظیمات",
    "PERMISSION_TOGGLE_PUSH_ARIA": "تغییر وضعیت اعلان‌های push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "تغییر وضعیت دسترسی به موقعیت مکانی",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "تغییر وضعیت صدای هشدار",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "تغییر وضعیت نشان برنامه",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "تغییر وضعیت نمایش پروفایل",
    "PERMISSION_OFF_IN_V1": "خاموش در v1",
    "PERMISSION_CHAT": "چت",
    "PERMISSION_BANNER_LIST": "فهرست بنرها",
    "PERMISSION_PUSH_DISABLED_V1": "اعلان‌های push برای نسخه v1 Google Play غیرفعال هستند.",
    "PERMISSION_PUSH_ON_TOOLTIP": "اعلان‌های push برای این دستگاه روشن است.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "اعلان‌های سیستم مسدود شده‌اند. برای باز کردن راهنمای تنظیمات بزنید.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "برای بهبود قابلیت اطمینان تحویل، روشن کنید.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "برای غیرفعال کردن اعلان‌های سیستم، تنظیمات اعلان مرورگر/سایت را باز کنید و این سایت را روی Block قرار دهید.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "برای تغییر مجوز اعلان سیستم، تنظیمات اعلان مرورگر/سایت را باز کنید و این سایت را روی Allow قرار دهید.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "دسترسی موقعیت مکانی برای مرتب‌سازی LCAC بر اساس فاصله و موقعیت‌یابی نقشه روشن است.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Location API در این محیط پشتیبانی نمی‌شود.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "دسترسی به موقعیت مکانی مسدود شده است. برای باز کردن راهنمای تنظیمات بزنید.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "برای فعال‌سازی مرتب‌سازی دقیق LCAC بر اساس فاصله و موقعیت‌یابی نقشه درون‌برنامه‌ای، روشن کنید.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "دسترسی به موقعیت مکانی در این محیط پشتیبانی نمی‌شود.",
    "PERMISSION_LOCATION_DISABLE_HELP": "برای غیرفعال کردن دسترسی موقعیت مکانی، تنظیمات موقعیت مرورگر/سایت را باز کنید و این سایت را روی Block قرار دهید.",
    "PERMISSION_LOCATION_ALLOW_HELP": "برای فعال کردن دسترسی موقعیت مکانی برای مرتب‌سازی فاصله و موقعیت‌یابی نقشه درون‌برنامه‌ای، تنظیمات موقعیت مرورگر/سایت را باز کنید و این سایت را روی Allow قرار دهید.",
    "PERMISSION_DEVICE_LOAD_FAILED": "در حال حاضر بارگذاری دستگاه‌های ثبت‌شده ممکن نیست.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "در حال بارگذاری UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "در حال بارگذاری Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "در حال بارگذاری بک‌اند...",
    "RUNTIME_LOADING": "در حال بارگذاری...",
    "RUNTIME_LOADING_FROM_DATABASE": "در حال بارگذاری از پایگاه داده...",
    "RUNTIME_BACKEND_CONNECTED": "بک‌اند متصل شد",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Fallback کش‌شده فعال است",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback پیش‌فرض فعال است",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallbackهای پیش‌فرض فعال هستند",
    "RUNTIME_SAVING_THROUGH_BACKEND": "در حال ذخیره از طریق بک‌اند...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "در سرویس بک‌اند ذخیره شد",
    "RUNTIME_SAVE_FAILED": "ذخیره ناموفق بود",
    "RUNTIME_LOAD_FAILED": "بارگذاری ناموفق بود",
    "RUNTIME_CONNECTED": "متصل",
    "RUNTIME_LOGIN_REQUIRED": "ورود الزامی است",
    "RUNTIME_SAVED": "ذخیره شد",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI آماده است - Runtime در انتظار است",
    "RUNTIME_BACKEND_REJECTED_MODEL": "سرویس محافظت‌شده انتخابگر بک‌اند گزینه مدل درخواستی را رد کرد یا نتوانست ذخیره کند.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "سرویس محافظت‌شده انتخابگر بک‌اند تغییر routing مربوط به WF1 را رد کرد یا نتوانست ذخیره کند.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "انتخابگر اکنون تنظیمات فعال، routing مربوط به Qwen و گزینه‌های مجاز را از سرویس محافظت‌شده بک‌اند می‌خواند.",
    "RUNTIME_WF1_SELECTOR_CACHED": "سرویس انتخابگر بک‌اند اکنون در دسترس نیست، بنابراین آخرین وضعیت کش‌شده انتخابگر استفاده می‌شود.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "مقادیر پیش‌فرض انتخابگر فعال هستند، چون هیچ وضعیت بک‌اند یا کش‌شده‌ای بارگذاری نشد.",
    "RUNTIME_WF1_SELECTOR_SAVED": "سرویس محافظت‌شده انتخابگر بک‌اند تنظیمات routing فعال WF1 را به‌روزرسانی کرد و کش دامنه runtime را تازه‌سازی کرد.",
    "FRONTEND_VERSION_TITLE": "نسخه فرانت‌اند",
    "FRONTEND_VERSION_HELPER_ACTIVE": "این انتخابگر نسخه فعال فرانت‌اند را برای همه کاربران کنترل می‌کند. FeV2.0.0 فعال است.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "این انتخابگر نسخه فعال فرانت‌اند را از config_domain_registry می‌خواند. Runtime به FeV2.0.0 resolve می‌شود.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "تنظیمات نسخه فرانت‌اند بک‌اند بارگذاری نشد؛ بنابراین پیش‌فرض کدنویسی‌شده FeV2.0.0 تا زمانی که startup bootstrap دوباره سرویس محافظت‌شده را بخواند، فعال می‌ماند.",
    "FRONTEND_VERSION_HELPER_SAVED": "نسخه فعال فرانت‌اند در config_domain_registry ذخیره شد. refresh کامل یا بارگذاری بعدی برنامه مقدار runtime را اعمال می‌کند.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "سرویس کنترل نسخه فرانت‌اند بک‌اند نتوانست نسخه سراسری درخواستی را ذخیره کند.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "نسخه فعال فرانت‌اند.",
    "CHAT_DELETE_WINDOW_TITLE": "پنجره حذف چت",
    "CHAT_DELETE_HELPER": "این مقدار پنجره زمانی امکان Delete for everyone را بر حسب ثانیه کنترل می‌کند. گارد بک‌اند بلافاصله پس از ذخیره تغییر می‌کند. نمایش حباب پس از refresh کامل یا بارگذاری بعدی برنامه تغییر می‌کند.",
    "CHAT_DELETE_HELPER_FALLBACK": "سرویس کنترل حذف چت بک‌اند بارگذاری نشد؛ بنابراین پیش‌فرض کدنویسی‌شده تا زمانی که startup bootstrap دوباره سرویس محافظت‌شده را بخواند، فعال می‌ماند.",
    "CHAT_DELETE_HELPER_SAVED": "پنجره زمانی Delete for everyone در config_domain_registry ذخیره شد. گارد بک‌اند بلافاصله تغییر می‌کند. نمایش حباب پس از refresh کامل یا بارگذاری بعدی برنامه تغییر می‌کند.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "سرویس کنترل حذف چت بک‌اند نتوانست مقدار پنجره درخواستی را ذخیره کند.",
    "CHAT_DELETE_WINDOW_LABEL": "پنجره Delete for everyone",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} ثانیه",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "مقدار را به ثانیه کامل ذخیره کنید. مقدار production فعلی 86400 ثانیه = ۱ روز است.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "ثانیه‌های پنجره",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "یک عدد صحیح بزرگ‌تر یا مساوی ۰ وارد کنید.",
    "CHAT_DELETE_SAVE_BUTTON": "ذخیره پنجره حذف",
    "GUEST_BANNER_CONTROL_TITLE": "بنر مهمان",
    "GUEST_BANNER_CONTROL_LABEL": "چت QR مهمان",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "نمایش بنر مهمان برای همه کاربران",
    "GUEST_BANNER_CONTROL_HELPER": "بنر ثابت مهمان و طول عمر توکن QR در حال انتظار را کنترل می‌کند.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "جایگزین محلی برای کنترل‌های بنر مهمان فعال است.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "کنترل‌های بنر مهمان ذخیره شد.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "کنترل‌های بنر مهمان ذخیره نشد.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} جلسه مهمان لغو شد.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "TTL کد QR در حال انتظار (دقیقه)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "TTL کد QR در حال انتظار فعلی: {count} دقیقه.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "یک عدد صحیح مثبت برای دقیقه وارد کنید.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "ذخیره بنر مهمان",
    "GUEST_QR_LOADING": "در حال آماده‌سازی QR مهمان...",
    "GUEST_QR_READY": "برای باز کردن چت موقت مهمان اسکن کنید.",
    "GUEST_QR_ALT": "کد QR چت مهمان",
    "GUEST_QR_LOAD_FAILED": "QR مهمان آماده نشد.",
    "GUEST_SESSION_ACTIVE": "مهمان متصل است.",
    "GUEST_PUBLIC_TITLE": "چت مهمان",
    "GUEST_PUBLIC_CONNECTING": "در حال اتصال...",
    "GUEST_PUBLIC_CONNECTED": "متصل شد",
    "GUEST_PUBLIC_UNAVAILABLE": "این لینک مهمان در دسترس نیست.",
    "GUEST_PUBLIC_SEND_FAILED": "پیام ارسال نشد.",
    "UI_TEXTS_RUNTIME_TITLE": "زمان اجرای زبان رابط کاربری",
    "UI_TEXTS_RUNTIME_BACKEND": "زمان اجرای زبان رابط کاربری در حال خواندن از سرویس بک‌اند محافظت‌شده است. تغییرات در بارگذاری کامل بعدی برنامه اعمال می‌شوند.",
    "UI_TEXTS_RUNTIME_CACHED": "سرویس زمان اجرای زبان رابط کاربری بک‌اند در حال حاضر در دسترس نیست، بنابراین پیش‌فرض‌های کش‌شده یا محلی فعال هستند.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "پیش‌فرض‌های زمان اجرای زبان رابط کاربری فعال هستند زیرا هیچ وضعیت بک‌اند یا کش‌شده‌ای بارگیری نشد.",
    "UI_TEXTS_RUNTIME_SAVED": "کنترل زمان اجرای زبان رابط کاربری ذخیره شد. برای اینکه کاربران گیت زبان جدید را دریافت کنند، یک بازخوانی کامل یا بارگذاری بعدی برنامه لازم است.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "سرویس بک‌اند محافظت‌شده نتوانست تغییر درخواستی زمان اجرای زبان رابط کاربری را ذخیره کند.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "برنامه زبان دستگاه",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "فعال کردن زبان‌های رابط کاربری زمان اجرا",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "کاربران می‌توانند محموله‌های متنی رابط کاربری را برای زبان ذخیره‌شده یا زبان دستگاه خود دریافت کنند.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "همه کاربران مجبور به استفاده از متن رابط کاربری انگلیسی هستند و زبان دستگاه نادیده گرفته می‌شود.",
    "PROFILE_VISIBILITY_TITLE": "نمایش پروفایل",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "برای مدیریت وضعیت نمایش حساب باید وارد شده باشید.",
    "PROFILE_VISIBILITY_HELPER": "این سوئیچ فقط وضعیت نمایش حساب شما را به‌روزرسانی می‌کند. قابلیت کشف و رفتار فهرست بنر در این فاز بدون تغییر می‌مانند.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "در حال حاضر وضعیت نمایش پروفایل بارگذاری نشد.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "در حال حاضر وضعیت نمایش پروفایل به‌روزرسانی نشد.",
    "PROFILE_VISIBILITY_SAVED": "وضعیت نمایش حساب شما اکنون {visibility} است. پرچم‌های قابلیت کشف در این فاز بدون تغییر می‌مانند.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "حساب عمومی",
    "PROFILE_VISIBILITY_STORED": "وضعیت نمایش ذخیره‌شده",
    "WF1_MODEL_CONTROL_TITLE": "کنترل مدل WF1",
    "WF1_ENABLE_TRANSLATION": "فعال‌سازی ترجمه / Pivot",
    "WF1_TRANSLATION_ACTIVE": "ترجمه هوش مصنوعی فعال است.",
    "WF1_TRANSLATION_INACTIVE": "WF1 همچنان اجرا می‌شود، اما متن منبع کپی می‌شود و pivot به‌عنوان غیرفعال علامت‌گذاری می‌شود.",
    "WF1_ACTIVE_RUNTIME_SLOT": "اسلات Runtime فعال",
    "WF1_ALLOW_SAME_LANGUAGE": "اجازه استفاده از هوش مصنوعی برای جفت‌های هم‌زبان",
    "WF1_SAME_LANGUAGE_ACTIVE": "جفت‌های هم‌زبان از routing عادی WF1 پیروی می‌کنند.",
    "WF1_SAME_LANGUAGE_INACTIVE": "جفت‌های هم‌زبان هوش مصنوعی را دور می‌زنند و زبان No Pivot را به‌عنوان فعال ذخیره می‌کنند.",
    "WF1_QWEN_ROUTING": "Routing جفت‌های Qwen",
    "WF1_QWEN_ROUTING_HELPER": "زبان‌های انتخاب‌شده زیر زمانی از Qwen-Max استفاده می‌کنند که جفت زبان یا همان زبان انتخاب‌شده باشد، یا یک زبان انتخاب‌شده با انگلیسی باشد، یا دو زبان غیرانگلیسی انتخاب‌شده باشند. در غیر این صورت، مدل اصلی انتخاب‌شده فعال می‌ماند.",
    "WF1_OPENROUTER_TEST_SLOT": "اسلات تست OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "اسلات تست OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "فقط تست کیفیت",
    "WF1_OPENROUTER_HELPER": "این اسلات فقط برای تست‌های موقت کیفیت OpenRouter قابل ویرایش است. مسیر عملیاتی routing جفت‌های Qwen را تغییر نمی‌دهد، مگر اینکه خود این اسلات به مدل فعال تبدیل شود.",
    "WF1_LABEL": "برچسب",
    "WF1_PRODUCT": "محصول",
    "WF1_MODEL": "مدل",
    "WF1_PROVIDER_OPENROUTER": "ارائه‌دهنده: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "اسلات تست OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max از طریق OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "قیمت لیست Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "قیمت لیست OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "قیمت لیست OpenRouter",
    "LANGUAGE_ENGLISH": "انگلیسی",
    "LANGUAGE_CHINESE_SIMPLIFIED": "چینی (ساده‌شده)",
    "LANGUAGE_CHINESE_TRADITIONAL": "چینی (سنتی)",
    "LANGUAGE_JAPANESE": "ژاپنی",
    "LANGUAGE_KOREAN": "کره‌ای",
    "LANGUAGE_PERSIAN": "فارسی",
    "LANGUAGE_TURKISH_ISTANBUL": "ترکی استانبولی",
    "LANGUAGE_ARABIC": "عربی",
    "LANGUAGE_FRENCH": "فرانسوی",
    "LANGUAGE_GERMAN": "آلمانی",
    "LANGUAGE_SPANISH": "اسپانیایی",
    "LANGUAGE_PORTUGUESE": "پرتغالی",
    "LANGUAGE_ITALIAN": "ایتالیایی",
    "LANGUAGE_RUSSIAN": "روسی",
    "LANGUAGE_DUTCH": "هلندی",
    "LANGUAGE_VIETNAMESE": "ویتنامی",
    "LANGUAGE_INDONESIAN": "اندونزیایی",
    "LANGUAGE_THAI": "تایلندی",
    "LANGUAGE_MALAY": "مالایی",
    "WF1_PRICING_CUSTOM": "قیمت‌گذاری: مدل اسلات سفارشی - قیمت‌گذاری فعلی OpenRouter را بررسی کنید",
    "WF1_SAVE_OPENROUTER_SLOT": "ذخیره اسلات OpenRouter",
    "WF1_PRICING_LINE": "ورودی {input} - خروجی {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "کنترل نمایش زون",
    "ZONE_ENABLE": "فعال‌سازی {zone}",
    "ZONE_ENABLED_NOTE": "{zone} پس از بارگذاری بعدی برنامه می‌تواند برای نقش‌های مجاز نمایش داده شود.",
    "ZONE_DISABLED_NOTE": "{zone} پس از بارگذاری بعدی برنامه برای کاربران غیر S_Admin غایب در نظر گرفته می‌شود.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin این فهرست نقش‌ها را دور می‌زند و همیشه دسترسی را حفظ می‌کند.",
    "ZONE_ROLE_LOCKED": "انتخاب نقش‌ها تا زمانی که این زون غیرفعال است موقتاً قفل می‌شود و وقتی زون دوباره فعال شود دقیقاً مطابق ذخیره‌شده برمی‌گردد.",
    "ZONE_LCAC_CONTROL": "کنترل LCAC",
    "ZONE_RCAC_CONTROL": "کنترل RCAC",
    "ZONE_LCAC_DESCRIPTION": "وجود زون رزروشده سمت چپ و نقش‌هایی را که ممکن است آن را ببینند کنترل می‌کند.",
    "ZONE_RCAC_DESCRIPTION": "وجود زون رزروشده سمت راست و نقش‌هایی را که ممکن است آن را ببینند کنترل می‌کند.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap نمایش زون اکنون از سرویس محافظت‌شده بک‌اند می‌خواند. تغییرات در بارگذاری بعدی برنامه اعمال می‌شوند.",
    "ZONE_VISIBILITY_CACHED": "سرویس نمایش زون بک‌اند اکنون در دسترس نیست، بنابراین مقادیر کش‌شده یا پیش‌فرض‌های محلی فعال هستند.",
    "ZONE_VISIBILITY_DEFAULTS": "پیش‌فرض‌های نمایش زون فعال هستند، چون هیچ وضعیت بک‌اند یا کش‌شده‌ای بارگذاری نشد.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap نمایش زون ذخیره شد. برای اعمال runtime، hard reload یا بارگذاری بعدی برنامه لازم است.",
    "ZONE_VISIBILITY_SAVE_FAILED": "سرویس محافظت‌شده بک‌اند نتوانست تغییر نمایش زون درخواستی را ذخیره کند.",
    "ROLE_MEMBER": "عضو",
    "ROLE_STAFF": "کارمند",
    "ROLE_ADMIN": "ادمین",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "برای دریافت پیام‌های جدید، اعلان‌ها را فعال کنید.",
    "MAIN_LOG_OUT": "خروج",
    "NOTIFICATION_NEW_MESSAGE": "پیام جدید",
    "NOTIFICATION_UNREAD_MESSAGE": "شما یک پیام خوانده‌نشده دارید.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "نمای کامل",
    "MEDIA_AUDIO_ATTACHMENT": "پیوست صوتی",
    "MEDIA_FILE_FALLBACK": "فایل",
    "MEDIA_DOWNLOAD_READY": "پیوست آماده دانلود است",
    "MEDIA_TYPE_UNSUPPORTED": "این نوع برای نمای کامل پشتیبانی نمی‌شود",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "تصویر قبلی",
    "MEDIA_NEXT_IMAGE_ARIA": "تصویر بعدی",
    "MEDIA_OPEN_ORIGINAL": "باز کردن نسخه اصلی",
    "MEDIA_DOWNLOAD": "دانلود",
    "MEDIA_CLOSE_ARIA": "بستن",
    "MEDIA_PROFILE_PICTURE_ARIA": "تصویر پروفایل {name}",
    "MEDIA_PROFILE_ALT": "پروفایل {name}",
    "MEDIA_UPLOAD_FAILED": "آپلود ناموفق بود",
    "MEDIA_BACKEND_TOKEN_ERROR": "خطای توکن بک‌اند",
    "MEDIA_UPLOAD_URL_MISSING": "بحرانی: آدرس آپلود در پاسخ بک‌اند موجود نیست.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "توکن احراز هویت برای آپلود چت موجود نیست",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "درخواست توکن آپلود چت ناموفق بود",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "پاسخ آپلود چت نامعتبر است",
    "MEDIA_GCS_UPLOAD_FAILED": "آپلود GCS ناموفق بود",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "نام فایل یا contentType موجود نیست",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path موجود نیست",
    "BLOCK_NOTICE_TITLE": "اعلان مسدودی دائمی",
    "BLOCK_NOTICE_MESSAGE": "حساب شما به‌دلیل نقض سیاست به‌صورت موقت تعلیق شده است.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "اگر فکر می‌کنید این موضوع نیاز به پیگیری دارد، لطفاً با",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "از طریق ایمیل تماس بگیرید.",
    "USER_BANNER_SAMPLE_NAME": "نصرت ابوحمزه",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "کاربر نامشخص",
    "GENERAL_GUEST": "مهمان",
    "ADVISOR_FOR_CLIENT": "ادوایزر برای {client_display_name}",
    "GUEST_FOR_CLIENT": "مهمان برای {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "توکن و رمز عبور الزامی است",
    "AUTH_ERROR_REQUEST_BODY_JSON": "بدنه درخواست باید JSON باشد",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "توکن دعوت نامعتبر است یا منقضی شده است",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "تنظیم رمز عبور ناموفق بود: session یا user موجود نیست",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "تنظیم رمز عبور هنگام ورود ناموفق بود",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "تولید توکن ادمین ناموفق بود",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "ورود ناموفق بود: session یا user موجود نیست",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "ثبت‌نام موفق بود. لطفاً ایمیل را برای تأیید بررسی کنید.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "ثبت‌نام به‌دلیل نامشخص ناموفق بود",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "پردازش توکن نامعتبر",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "access token الزامی است",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "پیش‌نمایش token hash به email hint از redirect URL نیاز دارد",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "امکان resolve کردن هویت برای این توکن وجود ندارد",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "فقط User Zero می‌تواند به سرویس انتخابگر LLM مربوط به WF1 دسترسی داشته باشد.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "فقط User Zero می‌تواند به سرویس کنترل نمایش زون دسترسی داشته باشد.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "فقط User Zero می‌تواند به سرویس کنترل نسخه فرانت‌اند دسترسی داشته باشد.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "فقط User Zero می‌تواند نسخه فرانت‌اند کاربر دیگر را بررسی کند.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "فقط User Zero می‌تواند به سرویس کنترل حذف چت دسترسی داشته باشد.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "فقط کاربر صفر می‌تواند به سرویس کنترل زمان اجرای زبان رابط کاربری دسترسی داشته باشد.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "فقط User Zero می‌تواند حساب کاربری را برای همیشه حذف کند.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "payload درخواست نامعتبر است.",
    "API_ERROR_INTERNAL_SERVER": "خطای داخلی سرور",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "تابع در بک‌اند موجود نیست (بارگذاری مجدد لازم است)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "برای transitionهای delivered/read فقط DB RPC مجاز است.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "لطفاً پیش از ارسال پیام دیگر کمی صبر کنید.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "پیام با موفقیت ارسال شد.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "سرویس تماس در دسترس نیست.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "ارسال پیام ناموفق بود.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "نام الزامی است.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "ایمیل نامعتبر است.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "پیام الزامی است.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "payload انتخابگر الزامی است.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "payload نمایش زون الزامی است.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "payload نسخه فرانت‌اند الزامی است.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "payload کنترل حذف چت الزامی است.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "محموله کنترل زمان اجرای زبان رابط کاربری الزامی است.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "شناسه کاربر احراز هویت‌شده الزامی است.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "شناسه viewer احراز هویت‌شده الزامی است.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "شناسه actor احراز هویت‌شده الزامی است.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id الزامی است.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id الزامی است.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "فهرست owner_user_ids الزامی است.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email الزامی است.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by الزامی است.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Search runtime توسط نسخه سراسری فرانت‌اند غیرفعال شده است.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "شما اجازه لغو این دعوت در انتظار را ندارید.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "این دعوت دیگر قابل لغو نیست، چون کاربر قبلاً ثبت‌نام کرده است.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "دعوت در انتظار یافت نشد.",
    "INVITE_REPLY_ALREADY_MEMBER": "تبریک، دوست شما ({invitee_email}) از قبل در این برنامه ثبت‌نام کرده و عضو این workspace است.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "دعوتی برای {invitee_email} در انتظار است، اما ایمیل تلاش مجدد فعال نشد. لطفاً mail logs را بررسی کنید.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "رکورد دعوت برای {invitee_email} ایجاد شد، اما تحویل ایمیل تأیید نشد. لطفاً بعداً دوباره تلاش کنید یا mail logs را بررسی کنید.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "ایجاد رکورد دعوت ناموفق بود. لطفاً بعداً دوباره تلاش کنید.",
    "INVITE_REPLY_SYSTEM_ERROR": "خطای سیستمی در فرایند دعوت: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "خطای پیکربندی بک‌اند: credentials مربوط به Supabase موجود نیست",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "خطای پیکربندی بک‌اند: URL مربوط به Supabase نامعتبر است",
    "CHAT_ERROR_ACCESS_DENIED": "دسترسی رد شد",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "محتوا برای پیام‌های متنی نمی‌تواند خالی باشد",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "شناسه گفت‌وگو تعیین نشد",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "زمینه احراز هویت RPC موجود نیست",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC payload پیام نامعتبر برگرداند",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "درج ناموفق بود، داده‌ای برگردانده نشد",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations باید یک فهرست باشد",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "payload عملیات نامعتبر است",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type پشتیبانی نمی‌شود",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id الزامی است",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "پیام یافت نشد",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "حذف فقط برای پیام خودتان مجاز است",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Delete for everyone دیگر برای این پیام در دسترس نیست",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Delete for everyone ناموفق بود",
    "API_ERROR_SERVER_CONFIGURATION": "خطای پیکربندی سرور",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "هدر webhook secret موجود نیست",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "منبع webhook غیرمجاز است",
    "API_ERROR_BACKEND_CONFIGURATION": "خطای پیکربندی بک‌اند",
    "API_ERROR_MODULE_ATTRIBUTE": "خطای ویژگی ماژول: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "پیش از حذف دعوت هنگام حذف کاربر auth در انتظار، عملیات ناموفق بود.",
    "CHAT_ERROR_DB": "خطای DB: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
