# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/fi.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Pääsivu",
    "APP_TITLE": "OTMEGA AI -alusta",
    "APP_SUBTITLE": "AI-neuvoja",
    "CHAT_PLACEHOLDER": "Kirjoita viestisi...",
    "CHAT_SEND_BUTTON": "Lähetä",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Neuvoja voi tehdä virheitä, joten tarkista tiedot.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Valikko",
    "ICON_NEW_CHAT": "Uusi keskustelu",
    "ICON_HISTORY": "Historia",
    "ICON_TEMPLATES": "Mallit",
    "ICON_SETTINGS": "Asetukset",
    "ICON_USER_PROFILE": "Käyttäjäprofiili",
    "ICON_QUICK_ACTIONS": "Pikatoiminnot",
    "ICON_PINNED": "Kiinnitetty",
    "ICON_GALLERY": "Galleria",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Asenna sovellus",
    "PWA_ANDROID_MSG": "Asenna tämä sovellus laitteellesi paremman käyttökokemuksen ja offline-käytön vuoksi.",
    "PWA_IOS_MSG": "Asenna tämä sovellus iPhoneen/iPadiin näin:\\n1. Napauta alla olevaa Jaa-painiketta\\n2. Valitse 'Lisää Koti-valikkoon'",
    "PWA_BTN_INSTALL": "Asenna",
    "PWA_BTN_LATER": "Ehkä myöhemmin",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Kirjaudu Advisor-verkostoon",
    "AUTH_HEADER_SIGNUP": "Luo yhtenäinen tilisi",
    "AUTH_HEADER_LOGIN_NETWORK": "Kirjaudu Advisor-verkostoon",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Luo yhtenäinen tilisi",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Kirjaudu",
    "AUTH_BUTTON_SIGNUP": "Luo tili",
    "AUTH_BUTTON_GOOGLE": "Jatka Googlella",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Unohtunut salasana",
    "AUTH_BUTTON_SEND_RESET_LINK": "Lähetä palautuslinkki",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Eikö sinulla ole tiliä? Rekisteröidy",
    "AUTH_PROMPT_LOGIN": "Onko sinulla jo tili? Kirjaudu sisään",
    "AUTH_HELPER_TEXT_SIGNUP": "Olet luomassa yhtenäistä tiliä, jolla voit käyttää kaikkia tämän alustan neuvojia.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Olet luomassa yhtenäistä tiliä, jolla voit käyttää kaikkia tämän alustan neuvojia.",
    "AUTH_HELPER_TEXT_LOGIN": "Käytä samaa tiliä (sähköposti/salasana tai Google), jota käytit muihin tämän verkoston neuvojiin.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Käytä samaa tiliä (sähköposti/salasana tai Google), jota käytit muihin tämän verkoston neuvojiin.",
    "AUTH_FORGOT_PASSWORD_LINK": "Unohditko salasanasi?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Palauta salasanasi",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Anna sähköpostiosoitteesi, niin lähetämme sinulle linkin salasanan palauttamiseksi.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Sähköposti",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Kirjataan sinua sisään...",
    "AUTH_STATUS_LOADING_SIGNUP": "Luodaan tiliäsi...",
    "AUTH_STATUS_LOADING_RESET": "Lähetetään palautuslinkkiä...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Kirjautuminen onnistui! Ladataan uudelleen...",
    "AUTH_STATUS_SUCCESS_RESET": "Palautuslinkki lähetettiin onnistuneesti. Tarkista sähköpostisi.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Salasanan palautuslinkki lähetettiin onnistuneesti. Tarkista sähköpostisi.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Virheellinen sähköposti tai salasana.",
    "AUTH_ERROR_EMAIL_EXISTS": "Tällä sähköpostilla on jo tili Advisor-verkostossa.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Tällä sähköpostilla on jo tili. Kirjaudu sisään. Olet tällä hetkellä jäsen kohteessa:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Tällä sähköpostilla on jo tili Advisor-verkostossa. Sulje tämä ikkuna ja käytä Kirjaudu-osaa samalla sähköpostilla ja aiemmalla salasanallasi.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Olet tällä hetkellä jäsen kohteessa:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "Sähköposti ja salasana vaaditaan.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Tili luotiin, mutta jäsenyyden määrittäminen epäonnistui. Ota yhteyttä tukeen.",
    "AUTH_ERROR_DEFAULT": "Tapahtui virhe. Yritä uudelleen.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Vierasbannerin ohjausobjektin hyötykuorma vaaditaan.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Vain Käyttäjä Nolla voi päivittää vierasbannerin ohjausobjekteja.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Palautuslinkin lähettäminen epäonnistui. Yritä uudelleen.",
    "INVITE_REPLY_EMAIL_SENT": "Collabra-kutsusähköposti lähetettiin ystävällesi osoitteeseen {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra-kutsusähköposti lähetettiin uudelleen ystävällesi osoitteeseen {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Näytä salasana",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Piilota salasana",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Peruuta",
    "GENERAL_CLOSE": "Sulje",
    "GENERAL_SEND": "Lähetä",
    "GENERAL_SEARCH": "Hae",
    "GENERAL_RESET": "Palauta",
    "GENERAL_ENABLE": "Ota käyttöön",
    "GENERAL_LOADING": "Ladataan...",
    "GENERAL_DELETE": "Poista",
    "GENERAL_DELETING": "Poistetaan...",
    "GENERAL_SAVE_PASSWORD": "Tallenna salasana",
    "AUTH_REMEMBER_EMAIL_LABEL": "Muista sähköposti",
    "GENERAL_SAVING": "Tallennetaan...",
    "GENERAL_SENDING": "Lähetetään...",
    "GENERAL_REMOVING": "Poistetaan...",
    "GENERAL_CONFIRM_REMOVAL": "Vahvista poisto",
    "GENERAL_EMPTY": "Tyhjä",
    "GENERAL_UNAVAILABLE": "Ei saatavilla",
    "GENERAL_ENABLED": "Käytössä",
    "GENERAL_DISABLED": "Poistettu käytöstä",
    "GENERAL_GRANTED": "Myönnetty",
    "GENERAL_DENIED": "Evätty",
    "GENERAL_DEFAULT": "Oletus",
    "GENERAL_UNSUPPORTED": "Ei tuettu",
    "GENERAL_PUBLIC": "Julkinen",
    "GENERAL_PRIVATE": "Yksityinen",
    "GENERAL_USERNAME": "Käyttäjänimi",
    "GENERAL_EMAIL": "Sähköposti",
    "GENERAL_YOU": "Sinä",
    "GENERAL_USER": "Käyttäjä",
    "GENERAL_UNKNOWN": "Tuntematon",
    "GENERAL_VISITOR": "Vierailija",
    "GENERAL_PROFILE": "Profiili",
    "GENERAL_BANNER": "Banneri",
    "GENERAL_UNKNOWN_BANNER": "Tuntematon banneri",
    "GENERAL_ADVISOR_BANNER": "Neuvojan banneri",
    "GENERAL_NOT_AVAILABLE": "Ei saatavilla",
    "GENERAL_NOT_SELECTED": "Ei valittu",
    "GENERAL_NO_EMAIL_FOUND": "Sähköpostia ei löytynyt",
    "GENERAL_USER_ZERO_ONLY": "Vain User Zero",
    "GENERAL_CONNECTION_STATE": "Yhteyden tila",
    "GENERAL_DISPLAY_ONLY": "Vain näyttö",
    "GENERAL_TEXTAREA": "Tekstialue",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Valikko (LCAC)",
    "HEADER_CHAT_CCAC": "Keskustelu (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Pikatoiminnot (RCAC)",
    "HEADER_CHANGE_STATUS": "Vaihda tila",
    "HEADER_OT_COIN_BALANCE": "OT Coin -saldo",
    "HEADER_ALT_USER": "Käyttäjä",
    "STATUS_BUSY": "Varattu",
    "STATUS_AWAY": "Poissa",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Näkymätön",
    "NETWORK_CHECKING_CONNECTION": "Tarkistetaan yhteyttä...",
    "NETWORK_ONLINE_LATENCY": "Online (viive: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Verkko: hyvä (napauta pingataksesi)",
    "CHAT_TARGET_ALT": "Keskustelun kohde",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Hae...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Avaa käyttäjän {name} profiilikuva",
    "CHAT_MESSAGE_INPUT_ARIA": "Viestikenttä",
    "CHAT_TOGGLE_VIEW_ARIA": "Vaihda näkymää",
    "CHAT_ADD_USER_ARIA": "Lisää käyttäjä",
    "CHAT_ATTACH_ARIA": "Liitä",
    "CHAT_MIC_ARIA": "Mikrofoni",
    "CHAT_SEND_ARIA": "Lähetä",
    "CHAT_SEARCH_ARIA": "Hae",
    "CHAT_OPEN_SEARCH_ARIA": "Avaa haku",
    "CHAT_CLOSE_SEARCH_ARIA": "Sulje haku",
    "CHAT_ATTACHMENT_ALT": "Liite",
    "CHAT_PREVIEW_ALT": "Esikatselu",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Poista liite",
    "CHAT_REPLYING_TO": "Vastataan kohteeseen",
    "CHAT_CANCEL_REPLY_ARIA": "Peruuta vastaus",
    "CHAT_UPLOADING": "Ladataan palvelimeen...",
    "CHAT_LOADING_CHATS": "Ladataan keskusteluja...",
    "CHAT_SEND_FAILED": "Lähetys epäonnistui",
    "CHAT_SEND_FAILED_RETRY": "Lähetys epäonnistui. Yritä uudelleen.",
    "CHAT_RETRY": "Yritä uudelleen",
    "CHAT_EDITED": "muokattu",
    "CHAT_TYPING": "Kirjoittaa",
    "CHAT_LOADING": "Ladataan",
    "CHAT_PENDING_INVITATION": "Odottava kutsu",
    "CHAT_PENDING_INVITATION_MIN": "{count} min Odottava kutsu",
    "CHAT_PENDING_INVITATION_HR": "{count} h Odottava kutsu",
    "CHAT_PENDING_INVITATION_DAY": "{count} pv Odottava kutsu",
    "CHAT_WAITING_FOR_YOU": "{label} - Odottaa sinua",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Hyväksyntää odotetaan",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Mikrofonin käyttö estetty.",
    "CHAT_UPLOAD_FAILED": "Lataus epäonnistui: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Lataus vaatii internet-yhteyden. Yritä uudelleen, kun olet online.",
    "CHAT_ERROR_AUTH": "Todennusvirhe",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Tiedostonimi tai content_type puuttuu",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id tai target_id puuttuu",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id puuttuu muulle kuin avatar-lataukselle",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Virheellinen avatarin file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase-palveluasiakas ei ole saatavilla",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Avatarin lukukuittaus on kelvollinen vain neuvojan keskustelukontekstissa",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatar-virran viestiä ei löytynyt tai se ei kelpaa lukukuittaukseen",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Avatar-viestin merkitseminen luetuksi epäonnistui",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 liite",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} liitettä",
    "CHAT_VOICE_NOTE": "Ääniviesti",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Keskustelu ei ole saatavilla. Tämä käyttäjä esti sinut.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Keskustelu ei ole saatavilla. Estit tämän käyttäjän.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Tilin käyttö on estetty käytännön vuoksi.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Keskustelu ei ole saatavilla. User Zero on estänyt tämän tilin lopullisesti.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Keskustelu ei ole saatavilla. Molemminpuolinen esto on aktiivinen.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Keskustelu ei ole saatavilla estokäytännön vuoksi.",
    "MESSAGE_PREVIEW_PHOTO": "Kuva",
    "MESSAGE_PREVIEW_VOICE": "Ääniviesti",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Tiedosto",
    "MESSAGE_PREVIEW_MESSAGE": "Viesti",
    "MESSAGE_PREVIEW_SYSTEM": "Järjestelmäviesti",
    "MESSAGE_PREVIEW_NEW": "Uusi viesti",
    "MESSAGE_UNKNOWN_FILE": "Tuntematon tiedosto",
    "MESSAGE_AUDIO_ATTACHMENT": "Ääniliite",
    "MESSAGE_FILE_ATTACHMENT": "Liite",
    "BANNER_INVITED_BY": "kutsuja {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Hakutulokset",
    "SEARCH_QUERY_LABEL": "Kysely:",
    "SEARCH_LOADING_VISIBILITY": "Ladataan haun näkyvyyttä...",
    "SEARCH_NO_RESULTS": "Nykyisestä hakualueesta ei löytynyt tuloksia.",
    "SHARE_WITH_COLLABRA": "Jaa Collabralla",
    "SHARE_SEND_TO": "Lähetä vastaanottajalle",
    "SHARE_SELECT_ONE_BANNER": "Valitse yksi banneri",
    "SHARE_BANNER_LIST_ARIA": "Banneriluettelo",
    "SHARE_NO_MATCHING_BANNER": "Vastaavaa banneria ei ole",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Lisää kommentti...",
    "SHARE_RECENT_CHATS": "Viimeaikaiset keskustelut",
    "SHARE_LEFT_LIST": "Vasen luettelo",
    "SHARE_RIGHT_LIST": "Oikea luettelo",
    "SHARE_UNTITLED_BANNER": "Nimetön banneri",
    "SHARE_SHARED_CONTENT": "Jaettu sisältö",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Jaettua sisältöä ei voitu avata.",
    "SHARE_OPEN_BANNER_FAILED": "Valittua banneria ei voitu avata.",
    "SHARE_ONE_PHOTO_SELECTED": "1 kuva valittu",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} kuvaa valittu",
    "SHARE_ONE_FILE_SELECTED": "1 tiedosto valittu",
    "SHARE_MANY_FILES_SELECTED": "{count} tiedostoa valittu",
    "FORWARD_MESSAGE_TITLE": "Välitä viesti",
    "FORWARD_SELECT_RECIPIENTS": "Valitse vastaanottajat",
    "FORWARD_NO_OTHER_BANNER": "Muita bannereita ei ole saatavilla.",
    "FORWARD_SEND_TO_COUNT": "Lähetä kohteelle {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Valitse vähintään yksi banneri.",
    "FORWARD_FAILED_DEFAULT": "Välitys epäonnistui. Yritä uudelleen.",
    "FORWARD_PARTIAL_SENT": "{count} lähetetty. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Lähdeviestiä ei löytynyt välitystä varten",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Tässä viestissä ei vielä ole välitettävää sisältöä",
    "FORWARD_DESTINATION_MISSING": "Välityksen kohde puuttuu",
    "FORWARD_MESSAGE_PREVIEW": "Välitetty viesti",
    "MENU_PASTE": "Liitä",
    "MENU_COPY": "Kopioi",
    "MENU_REPLY": "Vastaa",
    "MENU_FORWARD": "Välitä",
    "MENU_REMOVE_INVITATION": "Poista kutsu",
    "MENU_REMOVE_FROM_LIST": "Poista luettelosta",
    "MENU_GOODBYE_GUEST": "Näkemiin, vieras",
    "MENU_ADD_TO_LIST": "Lisää luetteloon",
    "MENU_REJECT_INVITATION": "Hylkää kutsu",
    "MENU_FRONTEND_VERSION": "Frontend-versio",
    "MENU_BANNER_HEADER": "Banneri - {zone}",
    "MENU_BANNER_INFO": "Bannerin tiedot: {title}",
    "MENU_MESSAGE_BUBBLE": "Viestikupla",
    "MENU_CHAT_CANVAS_HEADER": "Keskustelupohja - {zone}",
    "MENU_CANVAS_INFO": "Pohjan tiedot",
    "MENU_CHAT_CANVAS_SUBLABEL": "Keskustelualue / nykyinen keskustelupinta",
    "MENU_INPUT_AREA_HEADER": "Syöttöalue - {zone}",
    "MENU_INPUT_AREA_INFO": "Syöttöalueen tiedot: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Alareunan kirjoitus- ja toimintotyökalujen pinta",
    "MENU_HEADER": "Otsake - {zone}",
    "MENU_HEADER_INFO": "Otsakkeen tiedot: {title}",
    "MENU_HEADER_DESCRIPTION": "Yläosan navigointi ja sivun hallintatoiminnot",
    "MENU_ZONE_HEADER": "Alue - {zone}",
    "MENU_ZONE_SPACE_INFO": "Aluetilan tiedot",
    "MENU_EMPTY_LIST_SURFACE": "Tyhjä/luettelopinta",
    "MENU_BLOCK": "Estä",
    "MENU_UNBLOCK": "Poista esto",
    "MENU_HIDE_IN_SEARCH": "Piilota haussa",
    "MENU_UNHIDE_IN_SEARCH": "Näytä haussa",
    "MENU_VISIBLE_IN_SEARCH": "Näkyy haussa",
    "MENU_HIDDEN_IN_SEARCH": "Piilotettu haussa",
    "MENU_VISIBLE_IN_USER_LIST": "Näkyy käyttäjäluettelossa",
    "MENU_HIDDEN_IN_USER_LIST": "Piilotettu käyttäjäluettelossa",
    "MENU_NOT_BLOCKED": "Ei estetty",
    "MENU_BLOCKED": "Estetty",
    "MENU_FRONTEND_VERSION_LOADING": "Ladataan...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Ladataan bannerikohtaista arvoa backendistä. Mikään vaihtoehto ei ole merkitty aktiiviseksi ennen tietokantavastauksen saapumista.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend-arvoa ei voitu ladata. Luotettua aktiivista vaihtoehtoa ei näytetä.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Nimenomainen bannerikohtainen tietokanta-arvo on {overrideVersion}. Globaali oletusarvo on {globalDefaultVersion}. Kohdekäyttäjän on päivitettävä kokonaan tai avattava sovellus uudelleen, jotta käynnistyksen bootstrap ottaa sen käyttöön.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Nimenomaista bannerikohtaista tietokanta-arvoa ei ole tallennettu. FeV2.0.0 on oletuksena aktiivinen. Globaali oletusarvo on {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Nimenomainen bannerikohtainen tietokanta-arvo tulee aktiiviseksi, kun kohdesovellus latautuu kokonaan uudelleen",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Nimenomaista bannerikohtaista arvoa ei ole tallennettu; tämä on yksilöllinen FeV2.0.0-oletustila",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Tämä vaihtoehto vastaa myös nykyistä globaalia oletusarvoa",
    "MENU_DELETE_PERMANENT_CONFIRM": "Poistetaanko {target} pysyvästi tietokannasta? Tämä poistaa tilin, keskusteluhistorian ja riippuvuudet sekä pakottaa uuden kutsupolun tulevaa paluuta varten.",
    "MENU_DELETE_PERMANENTLY": "Poista pysyvästi",
    "MENU_REFRESH_PAGE": "Päivitä sivu",
    "MENU_LOG_OFF": "Kirjaudu ulos",
    "MENU_HARD_RELOAD": "Pakotettu uudelleenlataus",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Sähköposti (ylläpitäjäkäyttäjä)",
    "AUTH_PASSWORD_PLACEHOLDER": "Salasana",
    "AUTH_CONNECTING": "Yhdistetään...",
    "AUTH_SIGNING_OUT": "Kirjaudutaan ulos...",
    "AUTH_BACK_TO_LOGIN": "Takaisin kirjautumiseen",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Virheellinen palvelinvastaus: tunnusta ei löytynyt.",
    "AUTH_LOGIN_FAILED": "Kirjautuminen epäonnistui",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Salasanat eivät täsmää.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Salasanat eivät täsmää!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Salasanojen on täsmättävä täsmälleen.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Uusi salasana",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Vahvista salasana",
    "AUTH_CHANGE_PASSWORD": "Vaihda salasana",
    "AUTH_SAVING_PASSWORD": "Tallennetaan...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Salasana päivitettiin onnistuneesti.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Salasanaa ei voi vaihtaa juuri nyt.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Sinun on oltava kirjautuneena sisään vaihtaaksesi salasanasi.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Vaihda uuden salasanan näkyvyyttä",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Vaihda vahvistussalasanan näkyvyyttä",
    "REGISTER_TITLE": "Viimeistele rekisteröinti",
    "REGISTER_SUBTITLE": "Aseta salasanasi manuaalisesti.",
    "REGISTER_CREATING_ACCOUNT": "Luodaan tiliä...",
    "REGISTER_FINISH_SETUP": "Viimeistele määritys",
    "REGISTER_FAILED_SET_PASSWORD": "Salasanan asettaminen epäonnistui",
    "INVITE_EMAIL_INSTRUCTION": "Anna kutsuttavan sähköposti (muoto: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Kutsu",
    "INVITE_EMAIL_REQUIRED": "Anna kutsuttavan sähköposti.",
    "INVITE_EMAIL_INVALID": "Virheellinen sähköpostimuoto. Käytä: user@example.com",
    "PENDING_INVITATION_TITLE": "Odottava kutsu",
    "PENDING_INVITATION_REMOVE_QUESTION": "Poistetaanko tämä odottava kutsu tietokannasta?",
    "PENDING_INVITATION_KEEP": "Säilytä kutsu",
    "PENDING_INVITATION_REMOVAL_FAILED": "Poisto epäonnistui.",
    "REMOVE_FROM_LIST_TITLE": "Poista luettelosta",
    "REMOVE_FROM_LIST_WARNING": "Poistetaanko tämä käyttäjä nyt molemmista luetteloista? Keskusteluyhteys katkaistaan heti. Ainoa paluureitti on uusi kutsu.",
    "REMOVE_FROM_LIST_KEEP": "Pidä käyttäjä luettelossa",
    "REMOVE_FROM_LIST_FAILED": "Luettelosta poistaminen epäonnistui.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Asetukset ja live-tila",
    "PERMISSION_DIALOG_ARIA": "Asetukset ja live-tila",
    "PERMISSION_TRIGGER_ARIA": "Asetusponnahdusikkunan laukaisin",
    "PERMISSION_CLOSE_ARIA": "Sulje käyttöoikeusponnahdusikkuna",
    "PERMISSION_LIVE_STATUS": "Live-tila",
    "PERMISSION_SYSTEM_PERMISSION": "Järjestelmän käyttöoikeus",
    "PERMISSION_APP_PUSH": "Sovelluksen push",
    "PERMISSION_LOCATION_PERMISSION": "Sijaintioikeus",
    "PERMISSION_APP_LOCATION": "Sovelluksen sijainti",
    "PERMISSION_CONTROLS": "Käyttöoikeuksien hallinta",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push-ilmoitukset",
    "PERMISSION_LOCATION_ACCESS": "Sijainnin käyttö",
    "PERMISSION_IN_APP_SETTINGS": "Sovelluksen sisäiset asetukset",
    "PERMISSION_ALERT_SOUND": "Hälytysääni",
    "PERMISSION_APP_BADGE": "Sovellusmerkki",
    "PERMISSION_PASSWORD_SETTINGS": "Salasana-asetukset",
    "PERMISSION_NAVIGATION_STATUS": "Navigoinnin tila",
    "PERMISSION_SELECTED_ZONE": "Valittu alue",
    "PERMISSION_STAGED_CHAT_BANNER": "Valmisteltu keskustelubanneri",
    "PERMISSION_CANVAS_CONTENT": "Pohjan sisältö",
    "PERMISSION_YOUR_DEVICES": "Laitteesi ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Päivitä laiteluettelo",
    "PERMISSION_REFRESH_LIST": "Päivitä luettelo",
    "PERMISSION_NO_REGISTERED_DEVICES": "Rekisteröityjä laitteita ei löytynyt.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Muuta asetusponnahdusikkunan kokoa",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Vaihda push-ilmoitukset",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Vaihda sijainnin käyttö",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Vaihda hälytysääni",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Vaihda sovellusmerkki",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Vaihda profiilin näkyvyys",
    "PERMISSION_OFF_IN_V1": "Pois käytöstä v1:ssä",
    "PERMISSION_CHAT": "Keskustelu",
    "PERMISSION_BANNER_LIST": "Banneriluettelo",
    "PERMISSION_PUSH_DISABLED_V1": "Push-ilmoitukset on poistettu käytöstä v1 Google Play -julkaisussa.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Push-ilmoitukset ovat käytössä tällä laitteella.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Järjestelmäilmoitukset on estetty. Napauta avataksesi asetusten ohjeen.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Ota käyttöön toimitusvarmuuden parantamiseksi.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Poista järjestelmäilmoitukset käytöstä avaamalla selaimen/sivuston ilmoitusasetukset ja estämällä tämä sivusto.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Muuta järjestelmäilmoitusten käyttöoikeutta avaamalla selaimen/sivuston ilmoitusasetukset ja sallimalla tämä sivusto.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Sijainnin käyttö on päällä etäisyyspohjaista LCAC-lajittelua ja karttasijoittelua varten.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Sijaintirajapintaa ei tueta tässä ympäristössä.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Sijainnin käyttö on estetty. Napauta avataksesi asetusten ohjeen.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Ota käyttöön tarkan etäisyyspohjaisen LCAC-lajittelun ja sovelluksen sisäisen karttasijoittelun sallimiseksi.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Sijainnin käyttöä ei tueta tässä ympäristössä.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Poista sijainnin käyttö käytöstä avaamalla selaimen/sivuston sijaintiasetukset ja estämällä tämä sivusto.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Ota sijainnin käyttö käyttöön etäisyyslajittelua ja sovelluksen sisäistä karttasijoittelua varten avaamalla selaimen/sivuston sijaintiasetukset ja sallimalla tämä sivusto.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Rekisteröityjä laitteita ei voi ladata juuri nyt.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Ladataan UI Bridgeä...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Ladataan Local Bridgeä...",
    "RUNTIME_LOADING_BACKEND": "Ladataan backendiä...",
    "RUNTIME_LOADING": "Ladataan...",
    "RUNTIME_LOADING_FROM_DATABASE": "Ladataan tietokannasta...",
    "RUNTIME_BACKEND_CONNECTED": "Backend yhdistetty",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Välimuistivaraus aktiivinen",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Oletusvaraus aktiivinen",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Varausoletukset aktiivisia",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Tallennetaan backendin kautta...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Tallennettu backend-palveluun",
    "RUNTIME_SAVE_FAILED": "Tallennus epäonnistui",
    "RUNTIME_LOAD_FAILED": "Lataus epäonnistui",
    "RUNTIME_CONNECTED": "Yhdistetty",
    "RUNTIME_LOGIN_REQUIRED": "Kirjautuminen vaaditaan",
    "RUNTIME_SAVED": "Tallennettu",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI valmis - runtime odottaa",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Suojattu backend-valitsin hylkäsi pyydetyn mallivaihtoehdon tai ei voinut tallentaa sitä.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Suojattu backend-valitsin hylkäsi pyydetyn WF1-reititysmuutoksen tai ei voinut tallentaa sitä.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Valitsin lukee nyt aktiivisen määrityksen, Qwen-reitityksen ja sallitut vaihtoehdot suojatusta backend-palvelusta.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend-valitsinpalvelu ei ole juuri nyt saatavilla, joten viimeisintä välimuistissa olevaa valitsintilaa käytetään.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Valitsimen oletusarvot ovat aktiivisia, koska backend- tai välimuistitilaa ei voitu ladata.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Suojattu backend-valitsinpalvelu päivitti aktiivisen WF1-reititysmäärityksen ja päivitti runtime-verkkotunnuksen välimuistin.",
    "FRONTEND_VERSION_TITLE": "Frontend-versio",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Tämä valitsin ohjaa kaikkien käyttäjien aktiivista frontend-versiota. FeV2.0.0 on aktiivinen.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Tämä valitsin lukee aktiivisen frontend-version kohteesta config_domain_registry. Runtime ratkeaa arvoon FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backendin frontend-version määritystä ei voitu ladata, joten koodattu FeV2.0.0-oletus on aktiivinen, kunnes käynnistyksen bootstrap voi lukea suojatun palvelun uudelleen.",
    "FRONTEND_VERSION_HELPER_SAVED": "Aktiivinen frontend-versio tallennettiin config_domain_registryyn. Täysi päivitys tai seuraava sovelluksen lataus ottaa runtime-arvon käyttöön.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backendin frontend-version hallintapalvelu ei voinut tallentaa pyydettyä globaalia versiota.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktiivinen frontend-versio.",
    "CHAT_DELETE_WINDOW_TITLE": "Keskustelun poistoikkuna",
    "CHAT_DELETE_HELPER": "Tämä arvo hallitsee Poista kaikilta -toiminnon saatavuusikkunaa sekunteina. Backend-suoja muuttuu heti tallennuksen jälkeen. Kuplan näkyvyys muuttuu täyden päivityksen tai seuraavan sovelluksen latauksen jälkeen.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backendin keskustelun poiston hallintapalvelua ei voitu ladata, joten koodattu oletus pysyy aktiivisena, kunnes käynnistyksen bootstrap voi lukea suojatun palvelun uudelleen.",
    "CHAT_DELETE_HELPER_SAVED": "Poista kaikilta -saatavuusikkuna tallennettiin config_domain_registryyn. Backend-suoja muuttuu heti. Kuplan näkyvyys muuttuu täyden päivityksen tai seuraavan sovelluksen latauksen jälkeen.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backendin keskustelun poiston hallintapalvelu ei voinut tallentaa pyydettyä ikkunan arvoa.",
    "CHAT_DELETE_WINDOW_LABEL": "Poista kaikilta -ikkuna",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} s",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Tallenna arvo kokonaisina sekunteina. Nykyinen tuotantoarvo on 86400 sekuntia = 1 päivä.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Ikkunan sekunnit",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Anna kokonaisluku, joka on vähintään 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Tallenna poistoikkuna",
    "GUEST_BANNER_CONTROL_TITLE": "Vieras-banneri",
    "GUEST_BANNER_CONTROL_LABEL": "Vieras-QR-chat",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Näytä vieras-banneri kaikille käyttäjille",
    "GUEST_BANNER_CONTROL_HELPER": "Hallitsee kiinteää vieras-banneria ja odottavan QR-tunnisteen elinikää.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Paikallinen varajärjestelmä on aktiivinen vieras-bannerin hallinnalle.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Vieras-bannerin hallinta-asetukset tallennettu.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Vieras-bannerin hallinta-asetuksia ei voitu tallentaa.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} vierasistuntoa peruutettu.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "Odottavan QR-koodin elinikä (minuuttia)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "Nykyinen odottavan QR-koodin elinikä: {count} minuuttia.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Anna positiivinen kokonaisluku minuutteina.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Tallenna vieras-banneri",
    "GUEST_QR_LOADING": "Valmistellaan vieras-QR-koodia...",
    "GUEST_QR_READY": "Skannaa avataksesi väliaikaisen vieras-chatin.",
    "GUEST_QR_ALT": "Vieras-chatin QR-koodi",
    "GUEST_QR_LOAD_FAILED": "Vieras-QR-koodia ei voitu valmistaa.",
    "GUEST_SESSION_ACTIVE": "Vieras on yhdistetty.",
    "GUEST_PUBLIC_TITLE": "Vieras-chat",
    "GUEST_PUBLIC_CONNECTING": "Yhdistetään...",
    "GUEST_PUBLIC_CONNECTED": "Yhdistetty",
    "GUEST_PUBLIC_UNAVAILABLE": "Tämä vieraslinkki ei ole käytettävissä.",
    "GUEST_PUBLIC_SEND_FAILED": "Viestiä ei voitu lähettää.",
    "UI_TEXTS_RUNTIME_TITLE": "Käyttöliittymän kielen ajonaikainen hallinta",
    "UI_TEXTS_RUNTIME_BACKEND": "Käyttöliittymän kielen ajonaikainen hallinta lukee suojatusta taustapalvelusta. Muutokset tulevat voimaan sovelluksen seuraavan täyden latauksen yhteydessä.",
    "UI_TEXTS_RUNTIME_CACHED": "Taustapalvelun käyttöliittymän kielen ajonaikainen hallintapalvelu ei ole tällä hetkellä käytettävissä, joten välimuistissa olevat tai paikalliset oletusasetukset ovat käytössä.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "Käyttöliittymän kielen ajonaikaiset oletusasetukset ovat käytössä, koska taustapalvelua tai välimuistissa olevaa tilaa ei voitu ladata.",
    "UI_TEXTS_RUNTIME_SAVED": "Käyttöliittymän kielen ajonaikainen hallinta tallennettiin. Käyttäjät saavat uuden kieliasetuksen käyttöönsä täyden päivityksen tai sovelluksen seuraavan latauksen jälkeen.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Suojattu taustapalvelu ei voinut tallentaa pyydettyä käyttöliittymän kielen ajonaikaista muutosta.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Laitteen kielen sovellus",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Ota käyttöön ajonaikaiset käyttöliittymäkielet",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Käyttäjät voivat vastaanottaa käyttöliittymän tekstejä tallennetulla kielellään tai laitteen kielellä.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Kaikkien käyttäjien on käytettävä englanninkielistä käyttöliittymää, ja laitteen kieli ohitetaan.",
    "PROFILE_VISIBILITY_TITLE": "Profiilin näkyvyys",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Sinun on oltava kirjautuneena hallitaksesi tilin näkyvyyttä.",
    "PROFILE_VISIBILITY_HELPER": "Tämä kytkin päivittää vain tilisi näkyvyystilan. Löydettävyys ja banneriluettelon toiminta pysyvät tässä vaiheessa ennallaan.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Profiilin näkyvyyttä ei voitu ladata juuri nyt.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Profiilin näkyvyyttä ei voitu päivittää juuri nyt.",
    "PROFILE_VISIBILITY_SAVED": "Tilisi näkyvyys on nyt {visibility}. Löydettävyysliput pysyvät tässä vaiheessa ennallaan.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Julkinen tili",
    "PROFILE_VISIBILITY_STORED": "Tallennettu näkyvyys",
    "WF1_MODEL_CONTROL_TITLE": "WF1-mallin hallinta",
    "WF1_ENABLE_TRANSLATION": "Ota käännös / pivot käyttöön",
    "WF1_TRANSLATION_ACTIVE": "AI-käännös on aktiivinen.",
    "WF1_TRANSLATION_INACTIVE": "WF1 jatkaa toimintaansa, mutta lähdeteksti kopioidaan ja pivot merkitään ei-aktiiviseksi.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktiivinen runtime-paikka",
    "WF1_ALLOW_SAME_LANGUAGE": "Salli AI saman kielen pareille",
    "WF1_SAME_LANGUAGE_ACTIVE": "Saman kielen parit noudattavat normaalia WF1-reititystä.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Saman kielen parit ohittavat AI:n ja tallentavat tilan Ei aktiivista pivot-kieltä.",
    "WF1_QWEN_ROUTING": "Qwen-parireititys",
    "WF1_QWEN_ROUTING_HELPER": "Alla valitut kielet käyttävät Qwen-Maxia, kun pari on joko sama valittu kieli, valittu kieli englannin kanssa tai kaksi valittua ei-englanninkielistä kieltä. Muuten valittu ensisijainen malli pysyy aktiivisena.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter-testipaikka",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter-testipaikka - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Vain laatutesti",
    "WF1_OPENROUTER_HELPER": "Tämä paikka on muokattavissa vain väliaikaisia OpenRouter-laatutestejä varten. Se ei muuta operatiivista Qwen-parireitityspolkua, ellei tästä paikasta itsestään tule aktiivista mallia.",
    "WF1_LABEL": "Tunniste",
    "WF1_PRODUCT": "Tuote",
    "WF1_MODEL": "Malli",
    "WF1_PROVIDER_OPENROUTER": "Palveluntarjoaja: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Salaisuus: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter-testipaikka · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max OpenRouterin kautta",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Googlen listahinta",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI:n listahinta",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouterin listahinta",
    "LANGUAGE_ENGLISH": "Englanti",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Kiina (yksinkertaistettu)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Kiina (perinteinen)",
    "LANGUAGE_JAPANESE": "Japani",
    "LANGUAGE_KOREAN": "Korea",
    "LANGUAGE_PERSIAN": "Persia",
    "LANGUAGE_TURKISH_ISTANBUL": "Turkki (Istanbul)",
    "LANGUAGE_ARABIC": "Arabia",
    "LANGUAGE_FRENCH": "Ranska",
    "LANGUAGE_GERMAN": "Saksa",
    "LANGUAGE_SPANISH": "Espanja",
    "LANGUAGE_PORTUGUESE": "Portugali",
    "LANGUAGE_ITALIAN": "Italia",
    "LANGUAGE_RUSSIAN": "Venäjä",
    "LANGUAGE_DUTCH": "Hollanti",
    "LANGUAGE_VIETNAMESE": "Vietnam",
    "LANGUAGE_INDONESIAN": "Indonesia",
    "LANGUAGE_THAI": "Thai",
    "LANGUAGE_MALAY": "Malaiji",
    "WF1_PRICING_CUSTOM": "Hinnoittelu: mukautetun paikan malli - tarkista nykyinen OpenRouter-hinnoittelu",
    "WF1_SAVE_OPENROUTER_SLOT": "Tallenna OpenRouter-paikka",
    "WF1_PRICING_LINE": "Syöte {input} - Tuloste {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Salaisuus: {secret}",
    "ZONE_VISIBILITY_TITLE": "Alueen näkyvyyden hallinta",
    "ZONE_ENABLE": "Ota {zone} käyttöön",
    "ZONE_ENABLED_NOTE": "{zone} voi näkyä sallituille rooleille seuraavan sovelluksen latauksen jälkeen.",
    "ZONE_DISABLED_NOTE": "{zone} käsitellään poissaolevana muille kuin S_Admin-käyttäjille seuraavan sovelluksen latauksen jälkeen.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin ohittaa tämän rooliluettelon ja säilyttää aina pääsyn.",
    "ZONE_ROLE_LOCKED": "Roolivalinnat ovat väliaikaisesti lukittuina, kun tämä alue on poistettu käytöstä, ja ne palaavat täsmälleen tallennettuina, kun alue otetaan uudelleen käyttöön.",
    "ZONE_LCAC_CONTROL": "LCAC-hallinta",
    "ZONE_RCAC_CONTROL": "RCAC-hallinta",
    "ZONE_LCAC_DESCRIPTION": "Hallitsee vasemman varatun alueen olemassaoloa ja rooleja, jotka voivat nähdä sen.",
    "ZONE_RCAC_DESCRIPTION": "Hallitsee oikean varatun alueen olemassaoloa ja rooleja, jotka voivat nähdä sen.",
    "ZONE_VISIBILITY_BACKEND": "Alueen näkyvyyden bootstrap lukee nyt suojatusta backend-palvelusta. Muutokset otetaan käyttöön seuraavassa sovelluksen latauksessa.",
    "ZONE_VISIBILITY_CACHED": "Backendin alueen näkyvyyspalvelu ei ole juuri nyt saatavilla, joten välimuistissa olevat tai paikalliset oletukset ovat aktiivisia.",
    "ZONE_VISIBILITY_DEFAULTS": "Alueen näkyvyyden oletukset ovat aktiivisia, koska backend- tai välimuistitilaa ei voitu ladata.",
    "ZONE_VISIBILITY_SAVED": "Alueen näkyvyyden bootstrap tallennettiin. Runtime-käyttöönotto vaatii pakotetun uudelleenlatauksen tai seuraavan sovelluksen latauksen.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Suojattu backend-palvelu ei voinut tallentaa pyydettyä alueen näkyvyysmuutosta.",
    "ROLE_MEMBER": "Jäsen",
    "ROLE_STAFF": "Henkilöstö",
    "ROLE_ADMIN": "Ylläpitäjä",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Ota ilmoitukset käyttöön saadaksesi uusia viestejä.",
    "MAIN_LOG_OUT": "Kirjaudu ulos",
    "NOTIFICATION_NEW_MESSAGE": "Uusi viesti",
    "NOTIFICATION_UNREAD_MESSAGE": "Sinulla on lukematon viesti.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Koko näkymä",
    "MEDIA_AUDIO_ATTACHMENT": "Ääniliite",
    "MEDIA_FILE_FALLBACK": "Tiedosto",
    "MEDIA_DOWNLOAD_READY": "Liite valmis ladattavaksi",
    "MEDIA_TYPE_UNSUPPORTED": "Tyyppiä ei tueta koko näkymässä",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Edellinen kuva",
    "MEDIA_NEXT_IMAGE_ARIA": "Seuraava kuva",
    "MEDIA_OPEN_ORIGINAL": "Avaa alkuperäinen",
    "MEDIA_DOWNLOAD": "Lataa",
    "MEDIA_CLOSE_ARIA": "Sulje",
    "MEDIA_PROFILE_PICTURE_ARIA": "Käyttäjän {name} profiilikuva",
    "MEDIA_PROFILE_ALT": "Käyttäjän {name} profiili",
    "MEDIA_UPLOAD_FAILED": "Lataus epäonnistui",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend-tunnusvirhe",
    "MEDIA_UPLOAD_URL_MISSING": "Kriittinen: lataus-URL puuttuu backend-vastauksesta.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Todennustunnus puuttuu keskustelulatausta varten",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Keskustelulatauksen tunnuspyyntö epäonnistui",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Virheellinen keskustelulatauksen vastaus",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS-lataus epäonnistui",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Tiedostonimi tai contentType puuttuu",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path puuttuu",
    "BLOCK_NOTICE_TITLE": "Pysyvän eston ilmoitus",
    "BLOCK_NOTICE_MESSAGE": "Tilisi on väliaikaisesti keskeytetty käytäntörikkomuksen vuoksi.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Jos uskot, että tämä vaatii jatkotoimia, ota yhteyttä",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "sähköpostitse.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Tuntematon käyttäjä",
    "GENERAL_GUEST": "Vieras",
    "ADVISOR_FOR_CLIENT": "Neuvoja asiakkaalle {client_display_name}",
    "GUEST_FOR_CLIENT": "Vieras käyttäjälle {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Tunnus ja salasana vaaditaan",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Pyynnön rungon on oltava JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Virheellinen tai vanhentunut kutsutunnus",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Salasanan asetus epäonnistui: istunto tai käyttäjä puuttuu",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Salasanan asetus epäonnistui sisäänkirjautumisen aikana",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Ylläpitotunnuksen luonti epäonnistui",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Kirjautuminen epäonnistui: istunto tai käyttäjä puuttuu",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Rekisteröinti onnistui. Tarkista sähköpostisi vahvistusta varten.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Rekisteröityminen epäonnistui tuntemattomasta syystä",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Virheellinen tunnuksen käsittely",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Käyttötunnus vaaditaan",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Tunnisteen hash-esikatselu vaatii sähköpostivihjeen uudelleenohjaus-URL:stä",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Henkilöllisyyttä ei voitu ratkaista tälle tunnukselle",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Vain User Zero voi käyttää WF1 LLM -valitsinpalvelua.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Vain User Zero voi käyttää alueen näkyvyyden hallintapalvelua.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Vain User Zero voi käyttää frontend-version hallintapalvelua.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Vain User Zero voi tarkastaa toisen käyttäjän frontend-version.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Vain User Zero voi käyttää keskustelun poiston hallintapalvelua.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Vain User Zero voi käyttää käyttöliittymän kielen ajonaikaista hallintapalvelua.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Vain User Zero voi poistaa käyttäjätilin pysyvästi.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Virheellinen pyynnön payload.",
    "API_ERROR_INTERNAL_SERVER": "Sisäinen palvelinvirhe",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funktio puuttuu backendistä (uudelleenlataus vaaditaan)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Vain tietokannan RPC on sallittu delivered/read-siirtymille.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Odota ennen uuden viestin lähettämistä.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Viesti lähetettiin onnistuneesti.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Yhteydenottopalvelu ei ole saatavilla.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Viestin lähettäminen epäonnistui.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Nimi vaaditaan.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Sähköposti on virheellinen.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Viesti vaaditaan.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Valitsimen payload vaaditaan.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Alueen näkyvyyden payload vaaditaan.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Frontend-version payload vaaditaan.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Keskustelun poiston hallinnan payload vaaditaan.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Käyttöliittymän kielen ajonaikaisen hallinnan data on pakollinen.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Todennetun käyttäjän id vaaditaan.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Todennetun katsojakäyttäjän id vaaditaan.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Todennetun toimijakäyttäjän id vaaditaan.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id vaaditaan.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id vaaditaan.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids-luettelo vaaditaan.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email vaaditaan.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by vaaditaan.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Globaali frontend-versio on poistanut hakuruntimen käytöstä.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Et saa peruuttaa tätä odottavaa kutsua.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Tätä kutsua ei voi enää peruuttaa, koska käyttäjä on jo rekisteröitynyt.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Odottavaa kutsua ei löytynyt.",
    "INVITE_REPLY_ALREADY_MEMBER": "Onnittelut, ystäväsi ({invitee_email}) on jo rekisteröitynyt tähän sovellukseen ja on tämän työtilan jäsen.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Kutsu odottaa osoitteelle {invitee_email}, mutta uudelleenlähetyssähköpostia ei voitu käynnistää. Tarkista sähköpostilokit.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Kutsutietue luotiin osoitteelle {invitee_email}, mutta sähköpostin toimitusta ei voitu vahvistaa. Yritä myöhemmin uudelleen tai tarkista sähköpostilokit.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Kutsutietueen luonti epäonnistui. Yritä myöhemmin uudelleen.",
    "INVITE_REPLY_SYSTEM_ERROR": "Järjestelmävirhe kutsuprosessin aikana: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend-määritysvirhe: Supabase-tunnistetiedot puuttuvat",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend-määritysvirhe: virheellinen Supabase-URL",
    "CHAT_ERROR_ACCESS_DENIED": "Pääsy estetty",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Sisältö ei voi olla tyhjä tekstiviesteissä",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Keskustelun ID:tä ei voitu määrittää",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC-todennuskonteksti puuttuu",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC palautti virheellisen viestin payloadin",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Lisäys epäonnistui, tietoja ei palautettu",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations-arvon on oltava luettelo",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Virheellinen toiminnon payload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type ei ole tuettu",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id vaaditaan",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Viestiä ei löytynyt",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Poisto on sallittu vain omalle viestillesi",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Poista kaikilta ei ole enää saatavilla tälle viestille",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Poista kaikilta epäonnistui",
    "API_ERROR_SERVER_CONFIGURATION": "Palvelimen määritysvirhe",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Webhookin salainen otsake puuttuu",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Luvaton webhook-lähde",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend-määritysvirhe",
    "API_ERROR_MODULE_ATTRIBUTE": "Moduulin attribuuttivirhe: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Epäonnistui ennen kutsun poistamista odottavan auth-käyttäjän poistamisen aikana.",
    "CHAT_ERROR_DB": "DB-virhe: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
