# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/fr.py
# Mission: depot canonique des textes francais de l'interface utilisateur pour i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Principal",
    "APP_TITLE": "Plateforme IA OTMEGA",
    "APP_SUBTITLE": "Conseiller IA",
    "CHAT_PLACEHOLDER": "Tapez votre message...",
    "CHAT_SEND_BUTTON": "Envoyer",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Le conseiller peut faire des erreurs, verifiez donc les informations.",
    "STATUS_ONLINE": "En ligne",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Nouvelle discussion",
    "ICON_HISTORY": "Historique",
    "ICON_TEMPLATES": "Modeles",
    "ICON_SETTINGS": "Parametres",
    "ICON_USER_PROFILE": "Profil utilisateur",
    "ICON_QUICK_ACTIONS": "Actions rapides",
    "ICON_PINNED": "Epingle",
    "ICON_GALLERY": "Galerie",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Installer l'application",
    "PWA_ANDROID_MSG": "Installez cette application sur votre appareil pour une meilleure experience et un acces hors ligne.",
    "PWA_IOS_MSG": "Pour installer cette application sur votre iPhone/iPad :\n1. Touchez le bouton Partager ci-dessous\n2. Selectionnez Ajouter a l'ecran d'accueil",
    "PWA_BTN_INSTALL": "Installer",
    "PWA_BTN_LATER": "Peut-etre plus tard",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================
    "AUTH_HEADER_LOGIN": "Connectez-vous au reseau des conseillers",
    "AUTH_HEADER_SIGNUP": "Creez votre compte unifie",
    "AUTH_HEADER_LOGIN_NETWORK": "Connectez-vous au reseau des conseillers",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Creez votre compte unifie",
    "AUTH_BUTTON_LOGIN": "Connexion",
    "AUTH_BUTTON_SIGNUP": "Creer un compte",
    "AUTH_BUTTON_GOOGLE": "Continuer avec Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Mot de passe oublie",
    "AUTH_BUTTON_SEND_RESET_LINK": "Envoyer le lien de reinitialisation",
    "AUTH_PROMPT_SIGNUP": "Vous n'avez pas de compte ? Inscrivez-vous",
    "AUTH_PROMPT_LOGIN": "Vous avez deja un compte ? Connectez-vous",
    "AUTH_HELPER_TEXT_SIGNUP": "Vous creez un compte unifie que vous pouvez utiliser pour acceder a tous les conseillers de cette plateforme.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Vous creez un compte unifie que vous pouvez utiliser pour acceder a tous les conseillers de cette plateforme.",
    "AUTH_HELPER_TEXT_LOGIN": "Utilisez le meme compte (e-mail/mot de passe ou Google) que vous avez utilise pour d'autres conseillers de ce reseau.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Utilisez le meme compte (e-mail/mot de passe ou Google) que vous avez utilise pour d'autres conseillers de ce reseau.",
    "AUTH_FORGOT_PASSWORD_LINK": "Mot de passe oublie ?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Reinitialiser votre mot de passe",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Saisissez votre adresse e-mail et nous vous enverrons un lien pour reinitialiser votre mot de passe.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-mail",
    "AUTH_STATUS_LOADING_LOGIN": "Connexion en cours...",
    "AUTH_STATUS_LOADING_SIGNUP": "Creation de votre compte...",
    "AUTH_STATUS_LOADING_RESET": "Envoi du lien de reinitialisation...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Connexion reussie ! Rechargement...",
    "AUTH_STATUS_SUCCESS_RESET": "Lien de reinitialisation envoye avec succes. Veuillez verifier votre e-mail.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Lien de reinitialisation du mot de passe envoye avec succes. Veuillez verifier votre e-mail.",
    "AUTH_ERROR_INVALID_CREDENTIALS": "E-mail ou mot de passe invalide.",
    "AUTH_ERROR_EMAIL_EXISTS": "Un compte avec cet e-mail existe deja dans le reseau des conseillers.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Un compte avec cet e-mail existe deja. Veuillez vous connecter. Vous etes actuellement membre de :",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Un compte avec cet e-mail existe deja dans le reseau des conseillers. Veuillez fermer cette fenetre et utiliser la section Connexion avec le meme e-mail et votre ancien mot de passe.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Vous etes actuellement membre de :",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "L'e-mail et le mot de passe sont requis.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Compte cree, mais la configuration de l'adhesion a echoue. Veuillez contacter le support.",
    "AUTH_ERROR_DEFAULT": "Une erreur s'est produite. Veuillez reessayer.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Echec de l'envoi du lien de reinitialisation. Veuillez reessayer.",
    "INVITE_REPLY_EMAIL_SENT": "L'e-mail d'invitation Collabra a ete envoye a votre ami a l'adresse {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "L'e-mail d'invitation Collabra a ete renvoye a votre ami a l'adresse {invitee_email}.",
    "AUTH_PASSWORD_TOGGLE_SHOW": "Afficher le mot de passe",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Masquer le mot de passe",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Annuler",
    "GENERAL_CLOSE": "Fermer",
    "GENERAL_SEND": "Envoyer",
    "GENERAL_SEARCH": "Rechercher",
    "GENERAL_RESET": "Reinitialiser",
    "GENERAL_ENABLE": "Activer",
    "GENERAL_LOADING": "Chargement...",
    "GENERAL_DELETE": "Supprimer",
    "GENERAL_DELETING": "Suppression...",
    "GENERAL_SAVE_PASSWORD": "Enregistrer le mot de passe",
    "AUTH_REMEMBER_EMAIL_LABEL": "Memoriser l'e-mail",
    "GENERAL_SAVING": "Enregistrement...",
    "GENERAL_SENDING": "Envoi...",
    "GENERAL_REMOVING": "Suppression...",
    "GENERAL_CONFIRM_REMOVAL": "Confirmer la suppression",
    "GENERAL_EMPTY": "Vide",
    "GENERAL_UNAVAILABLE": "Indisponible",
    "GENERAL_ENABLED": "Active",
    "GENERAL_DISABLED": "Desactive",
    "GENERAL_GRANTED": "Accorde",
    "GENERAL_DENIED": "Refuse",
    "GENERAL_DEFAULT": "Par defaut",
    "GENERAL_UNSUPPORTED": "Non pris en charge",
    "GENERAL_PUBLIC": "Public",
    "GENERAL_PRIVATE": "Prive",
    "GENERAL_USERNAME": "Nom d'utilisateur",
    "GENERAL_EMAIL": "E-mail",
    "GENERAL_YOU": "Vous",
    "GENERAL_USER": "Utilisateur",
    "GENERAL_UNKNOWN": "Inconnu",
    "GENERAL_VISITOR": "Visiteur",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banniere",
    "GENERAL_UNKNOWN_BANNER": "Banniere inconnue",
    "GENERAL_ADVISOR_BANNER": "Banniere du conseiller",
    "GENERAL_NOT_AVAILABLE": "N/D",
    "GENERAL_NOT_SELECTED": "Non selectionne",
    "GENERAL_NO_EMAIL_FOUND": "Aucun e-mail trouve",
    "GENERAL_USER_ZERO_ONLY": "Utilisateur Zero uniquement",
    "GENERAL_CONNECTION_STATE": "Etat de connexion",
    "GENERAL_DISPLAY_ONLY": "Affichage uniquement",
    "GENERAL_TEXTAREA": "Zone de texte",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Discussion (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Actions rapides (RCAC)",
    "HEADER_CHANGE_STATUS": "Changer le statut",
    "HEADER_OT_COIN_BALANCE": "Solde OT Coin",
    "HEADER_ALT_USER": "Utilisateur",
    "STATUS_BUSY": "Occupe",
    "STATUS_AWAY": "Absent",
    "STATUS_OFFLINE": "Hors ligne",
    "STATUS_INVISIBLE": "Invisible",
    "NETWORK_CHECKING_CONNECTION": "Verification de la connexion...",
    "NETWORK_ONLINE_LATENCY": "En ligne (latence : {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Reseau : bon (touchez pour tester)",
    "CHAT_TARGET_ALT": "Cible de discussion",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Rechercher...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Ouvrir la photo de profil de {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Champ de message",
    "CHAT_TOGGLE_VIEW_ARIA": "Basculer l'affichage",
    "CHAT_ADD_USER_ARIA": "Ajouter un utilisateur",
    "CHAT_ATTACH_ARIA": "Joindre",
    "CHAT_MIC_ARIA": "Microphone",
    "CHAT_SEND_ARIA": "Envoyer",
    "CHAT_SEARCH_ARIA": "Rechercher",
    "CHAT_OPEN_SEARCH_ARIA": "Ouvrir la recherche",
    "CHAT_CLOSE_SEARCH_ARIA": "Fermer la recherche",
    "CHAT_ATTACHMENT_ALT": "Piece jointe",
    "CHAT_PREVIEW_ALT": "Apercu",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Supprimer la piece jointe",
    "CHAT_REPLYING_TO": "Reponse a",
    "CHAT_CANCEL_REPLY_ARIA": "Annuler la reponse",
    "CHAT_UPLOADING": "Televersement...",
    "CHAT_LOADING_CHATS": "Chargement des discussions...",
    "CHAT_SEND_FAILED": "Echec de l'envoi",
    "CHAT_SEND_FAILED_RETRY": "Echec de l'envoi. Veuillez reessayer.",
    "CHAT_RETRY": "Reessayer",
    "CHAT_EDITED": "modifie",
    "CHAT_TYPING": "Saisie",
    "CHAT_LOADING": "Chargement",
    "CHAT_PENDING_INVITATION": "Invitation en attente",
    "CHAT_PENDING_INVITATION_MIN": "{count} min Invitation en attente",
    "CHAT_PENDING_INVITATION_HR": "{count} h Invitation en attente",
    "CHAT_PENDING_INVITATION_DAY": "{count} j Invitation en attente",
    "CHAT_WAITING_FOR_YOU": "{label} - En attente de vous",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Acceptation en attente",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Acces au microphone refuse.",
    "CHAT_UPLOAD_FAILED": "Echec du televersement : {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Le televersement necessite une connexion Internet. Veuillez reessayer lorsque vous serez en ligne.",
    "CHAT_ERROR_AUTH": "Erreur d'authentification",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nom de fichier ou content_type manquant",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id ou target_id manquant",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id manquant pour un televersement hors avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path de l'avatar invalide",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Client de service Supabase indisponible",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "L'accuse de lecture d'avatar n'est valide que dans le contexte de discussion avec le conseiller",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Message de flux avatar introuvable ou non eligible a l'accuse de lecture",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Echec de la finalisation du message avatar comme lu",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 piece jointe",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} pieces jointes",
    "CHAT_VOICE_NOTE": "Note vocale",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Discussion indisponible. Cet utilisateur vous a bloque.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Discussion indisponible. Vous avez bloque cet utilisateur.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "L'acces au compte est bloque par la politique.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Discussion indisponible. Ce compte est definitivement bloque par l'Utilisateur Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Discussion indisponible. Le blocage mutuel est actif.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Discussion indisponible en raison de la politique de blocage.",
    "MESSAGE_PREVIEW_PHOTO": "Photo",
    "MESSAGE_PREVIEW_VOICE": "Message vocal",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Fichier",
    "MESSAGE_PREVIEW_MESSAGE": "Message",
    "MESSAGE_PREVIEW_SYSTEM": "Message systeme",
    "MESSAGE_PREVIEW_NEW": "Nouveau message",
    "MESSAGE_UNKNOWN_FILE": "Fichier inconnu",
    "MESSAGE_AUDIO_ATTACHMENT": "Piece jointe audio",
    "MESSAGE_FILE_ATTACHMENT": "Piece jointe",
    "BANNER_INVITED_BY": "invite par {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Resultats de recherche",
    "SEARCH_QUERY_LABEL": "Requete :",
    "SEARCH_LOADING_VISIBILITY": "Chargement de la visibilite de recherche...",
    "SEARCH_NO_RESULTS": "Aucun resultat trouve dans le perimetre de recherche actuel.",
    "SHARE_WITH_COLLABRA": "Partager avec Collabra",
    "SHARE_SEND_TO": "Envoyer a",
    "SHARE_SELECT_ONE_BANNER": "Selectionnez une banniere",
    "SHARE_BANNER_LIST_ARIA": "Liste des bannieres",
    "SHARE_NO_MATCHING_BANNER": "Aucune banniere correspondante",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Ajouter un commentaire...",
    "SHARE_RECENT_CHATS": "Discussions recentes",
    "SHARE_LEFT_LIST": "Liste gauche",
    "SHARE_RIGHT_LIST": "Liste droite",
    "SHARE_UNTITLED_BANNER": "Banniere sans titre",
    "SHARE_SHARED_CONTENT": "Contenu partage",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Le contenu partage n'a pas pu etre ouvert.",
    "SHARE_OPEN_BANNER_FAILED": "Impossible d'ouvrir la banniere selectionnee.",
    "SHARE_ONE_PHOTO_SELECTED": "1 photo selectionnee",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} photos selectionnees",
    "SHARE_ONE_FILE_SELECTED": "1 fichier selectionne",
    "SHARE_MANY_FILES_SELECTED": "{count} fichiers selectionnes",
    "FORWARD_MESSAGE_TITLE": "Transferer le message",
    "FORWARD_SELECT_RECIPIENTS": "Selectionner les destinataires",
    "FORWARD_NO_OTHER_BANNER": "Aucune autre banniere disponible.",
    "FORWARD_SEND_TO_COUNT": "Envoyer a {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Selectionnez au moins une banniere.",
    "FORWARD_FAILED_DEFAULT": "Le transfert a echoue. Veuillez reessayer.",
    "FORWARD_PARTIAL_SENT": "{count} envoye(s). {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Message source introuvable pour le transfert",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Ce message n'a pas encore de contenu transferable",
    "FORWARD_DESTINATION_MISSING": "La destination du transfert est manquante",
    "FORWARD_MESSAGE_PREVIEW": "Message transfere",
    "MENU_PASTE": "Coller",
    "MENU_COPY": "Copier",
    "MENU_REPLY": "Repondre",
    "MENU_FORWARD": "Transferer",
    "MENU_REMOVE_INVITATION": "Supprimer l'invitation",
    "MENU_REMOVE_FROM_LIST": "Retirer de la liste",
    "MENU_ADD_TO_LIST": "Ajouter a la liste",
    "MENU_REJECT_INVITATION": "Rejeter l'invitation",
    "MENU_FRONTEND_VERSION": "Version frontend",
    "MENU_BANNER_HEADER": "Banniere - {zone}",
    "MENU_BANNER_INFO": "Infos banniere : {title}",
    "MENU_MESSAGE_BUBBLE": "Bulle de message",
    "MENU_CHAT_CANVAS_HEADER": "Canvas de discussion - {zone}",
    "MENU_CANVAS_INFO": "Infos canvas",
    "MENU_CHAT_CANVAS_SUBLABEL": "Zone de conversation / surface de discussion actuelle",
    "MENU_INPUT_AREA_HEADER": "Zone de saisie - {zone}",
    "MENU_INPUT_AREA_INFO": "Infos zone de saisie : {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Surface inferieure de saisie et d'outils d'action",
    "MENU_HEADER": "En-tete - {zone}",
    "MENU_HEADER_INFO": "Infos en-tete : {title}",
    "MENU_HEADER_DESCRIPTION": "Navigation superieure et controles de page",
    "MENU_ZONE_HEADER": "Zone - {zone}",
    "MENU_ZONE_SPACE_INFO": "Infos espace de zone",
    "MENU_EMPTY_LIST_SURFACE": "Surface vide/liste",
    "MENU_BLOCK": "Bloquer",
    "MENU_UNBLOCK": "Debloquer",
    "MENU_HIDE_IN_SEARCH": "Masquer dans la recherche",
    "MENU_UNHIDE_IN_SEARCH": "Afficher dans la recherche",
    "MENU_VISIBLE_IN_SEARCH": "Visible dans la recherche",
    "MENU_HIDDEN_IN_SEARCH": "Masque dans la recherche",
    "MENU_VISIBLE_IN_USER_LIST": "Visible dans la liste utilisateurs",
    "MENU_HIDDEN_IN_USER_LIST": "Masque dans la liste utilisateurs",
    "MENU_NOT_BLOCKED": "Non bloque",
    "MENU_BLOCKED": "Bloque",
    "MENU_FRONTEND_VERSION_LOADING": "Chargement...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Chargement de la valeur par banniere depuis le backend. Aucune option n'est marquee active tant que la reponse de la base de donnees n'est pas arrivee.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "La valeur backend n'a pas pu etre chargee. Aucune option active fiable n'est affichee.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "La valeur explicite par banniere en base est {overrideVersion}. La valeur globale par defaut est {globalDefaultVersion}. L'utilisateur cible doit actualiser completement ou rouvrir l'application pour que le bootstrap de demarrage l'applique.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Aucune valeur explicite par banniere n'est stockee. FeV2.0.0 est active par defaut. La valeur globale par defaut est {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "La valeur explicite par banniere devient active apres le rechargement complet de l'application cible",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Aucune valeur explicite par banniere n'est stockee ; c'est l'etat individuel FeV2.0.0 par defaut",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Cette option est egalement egale a la valeur globale par defaut actuelle",
    "MENU_DELETE_PERMANENT_CONFIRM": "Supprimer definitivement {target} de la base de donnees ? Cela supprime le compte, l'historique de discussion, les dependances et force un nouveau parcours d'invitation pour toute future reintegration.",
    "MENU_DELETE_PERMANENTLY": "Supprimer definitivement",
    "MENU_REFRESH_PAGE": "Actualiser la page",
    "MENU_LOG_OFF": "Se deconnecter",
    "MENU_HARD_RELOAD": "Obtenir la dernière version",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-mail (utilisateur admin)",
    "AUTH_PASSWORD_PLACEHOLDER": "Mot de passe",
    "AUTH_CONNECTING": "Connexion...",
    "AUTH_SIGNING_OUT": "Deconnexion...",
    "AUTH_BACK_TO_LOGIN": "Retour a la connexion",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Reponse serveur invalide : aucun jeton trouve.",
    "AUTH_LOGIN_FAILED": "Echec de la connexion",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Les mots de passe ne correspondent pas.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Les mots de passe ne correspondent pas !",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Les mots de passe doivent correspondre exactement.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nouveau mot de passe",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Confirmer le mot de passe",
    "AUTH_CHANGE_PASSWORD": "Changer le mot de passe",
    "AUTH_SAVING_PASSWORD": "Enregistrement...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Mot de passe mis a jour avec succes.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Impossible de changer le mot de passe pour le moment.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Vous devez etre connecte pour changer votre mot de passe.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Basculer la visibilite du nouveau mot de passe",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Basculer la visibilite de la confirmation du mot de passe",
    "REGISTER_TITLE": "Terminer l'inscription",
    "REGISTER_SUBTITLE": "Veuillez definir votre mot de passe manuellement.",
    "REGISTER_CREATING_ACCOUNT": "Creation du compte...",
    "REGISTER_FINISH_SETUP": "Terminer la configuration",
    "REGISTER_FAILED_SET_PASSWORD": "Echec de la definition du mot de passe",
    "INVITE_EMAIL_INSTRUCTION": "Veuillez saisir l'e-mail de l'invite (format : user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Inviter",
    "INVITE_EMAIL_REQUIRED": "Veuillez saisir l'e-mail de l'invite.",
    "INVITE_EMAIL_INVALID": "Format d'e-mail invalide. Veuillez utiliser : user@example.com",
    "PENDING_INVITATION_TITLE": "Invitation en attente",
    "PENDING_INVITATION_REMOVE_QUESTION": "Supprimer cette invitation en attente de la base de donnees ?",
    "PENDING_INVITATION_KEEP": "Conserver l'invitation",
    "PENDING_INVITATION_REMOVAL_FAILED": "La suppression a echoue.",
    "REMOVE_FROM_LIST_TITLE": "Retirer de la liste",
    "REMOVE_FROM_LIST_WARNING": "Retirer maintenant cet utilisateur des deux listes ? L'acces a la discussion sera coupe immediatement. Le seul chemin de retour est une nouvelle invitation.",
    "REMOVE_FROM_LIST_KEEP": "Garder l'utilisateur dans la liste",
    "REMOVE_FROM_LIST_FAILED": "Echec du retrait de la liste.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Parametres et statut en direct",
    "PERMISSION_DIALOG_ARIA": "Parametres et statut en direct",
    "PERMISSION_TRIGGER_ARIA": "Declencheur de popup des parametres",
    "PERMISSION_CLOSE_ARIA": "Fermer la popup des autorisations",
    "PERMISSION_LIVE_STATUS": "Statut en direct",
    "PERMISSION_SYSTEM_PERMISSION": "Autorisation systeme",
    "PERMISSION_APP_PUSH": "Push de l'app",
    "PERMISSION_LOCATION_PERMISSION": "Autorisation de localisation",
    "PERMISSION_APP_LOCATION": "Localisation de l'app",
    "PERMISSION_CONTROLS": "Controles des autorisations",
    "PERMISSION_PUSH_NOTIFICATIONS": "Notifications push",
    "PERMISSION_LOCATION_ACCESS": "Acces a la localisation",
    "PERMISSION_IN_APP_SETTINGS": "Parametres integres",
    "PERMISSION_ALERT_SOUND": "Son d'alerte",
    "PERMISSION_APP_BADGE": "Badge de l'app",
    "PERMISSION_PASSWORD_SETTINGS": "Parametres du mot de passe",
    "PERMISSION_NAVIGATION_STATUS": "Statut de navigation",
    "PERMISSION_SELECTED_ZONE": "Zone selectionnee",
    "PERMISSION_STAGED_CHAT_BANNER": "Banniere de discussion preparee",
    "PERMISSION_CANVAS_CONTENT": "Contenu du canvas",
    "PERMISSION_YOUR_DEVICES": "Vos appareils ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Actualiser la liste des appareils",
    "PERMISSION_REFRESH_LIST": "Actualiser la liste",
    "PERMISSION_NO_REGISTERED_DEVICES": "Aucun appareil enregistre trouve.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Redimensionner la popup des parametres",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Basculer les notifications push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Basculer l'acces a la localisation",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Basculer le son d'alerte",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Basculer le badge de l'app",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Basculer la visibilite du profil",
    "PERMISSION_OFF_IN_V1": "Desactive en v1",
    "PERMISSION_CHAT": "Discussion",
    "PERMISSION_BANNER_LIST": "Liste de bannieres",
    "PERMISSION_PUSH_DISABLED_V1": "Les notifications push sont desactivees pour la version v1 Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Les notifications push sont activees pour cet appareil.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Les notifications systeme sont bloquees. Touchez pour ouvrir l'aide des parametres.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Activez pour ameliorer la fiabilite de livraison.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Pour desactiver les notifications systeme, ouvrez les parametres de notification de votre navigateur/site et bloquez ce site.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Pour modifier l'autorisation des notifications systeme, ouvrez les parametres de notification de votre navigateur/site et autorisez ce site.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "L'acces a la localisation est active pour le tri LCAC par distance et le positionnement sur la carte.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "L'API de localisation n'est pas prise en charge dans cet environnement.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "L'acces a la localisation est bloque. Touchez pour ouvrir l'aide des parametres.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Activez pour autoriser le tri precis par distance LCAC et le positionnement sur la carte integree.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "L'acces a la localisation n'est pas pris en charge dans cet environnement.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Pour desactiver l'acces a la localisation, ouvrez les parametres de localisation de votre navigateur/site et bloquez ce site.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Pour activer l'acces a la localisation pour le tri par distance et le positionnement sur la carte integree, ouvrez les parametres de localisation de votre navigateur/site et autorisez ce site.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Impossible de charger les appareils enregistres pour le moment.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Chargement du pont UI...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Chargement du pont local...",
    "RUNTIME_LOADING_BACKEND": "Chargement du backend...",
    "RUNTIME_LOADING": "Chargement...",
    "RUNTIME_LOADING_FROM_DATABASE": "Chargement depuis la base de donnees...",
    "RUNTIME_BACKEND_CONNECTED": "Backend connecte",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Fallback en cache actif",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback par defaut actif",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Valeurs par defaut de fallback actives",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Enregistrement via le backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Enregistre dans le service backend",
    "RUNTIME_SAVE_FAILED": "Echec de l'enregistrement",
    "RUNTIME_LOAD_FAILED": "Echec du chargement",
    "RUNTIME_CONNECTED": "Connecte",
    "RUNTIME_LOGIN_REQUIRED": "Connexion requise",
    "RUNTIME_SAVED": "Enregistre",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI prete - runtime en attente",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Le service backend protege du selecteur a rejete ou n'a pas pu enregistrer l'option de modele demandee.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Le service backend protege du selecteur a rejete ou n'a pas pu enregistrer le changement de routage WF1 demande.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Le selecteur lit maintenant la configuration active, le routage Qwen et les options autorisees depuis le service backend protege.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Le service backend du selecteur est indisponible pour le moment ; le dernier etat du selecteur en cache est donc utilise.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Les valeurs par defaut du selecteur sont actives car aucun etat backend ou en cache n'a pu etre charge.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Le service backend protege du selecteur a mis a jour la configuration de routage WF1 active et rafraichi le cache du domaine runtime.",
    "FRONTEND_VERSION_TITLE": "Version frontend",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Ce selecteur controle la version frontend active pour tous les utilisateurs. FeV2.0.0 est active.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Ce selecteur lit la version frontend active depuis config_domain_registry. Le runtime se resout en FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "La configuration backend de version frontend n'a pas pu etre chargee ; la valeur par defaut codee FeV2.0.0 reste donc active jusqu'a ce que le bootstrap puisse relire le service protege.",
    "FRONTEND_VERSION_HELPER_SAVED": "La version frontend active a ete enregistree dans config_domain_registry. Un rafraichissement complet ou le prochain chargement de l'app applique la valeur runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Le service backend de controle de version frontend n'a pas pu enregistrer la version globale demandee.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Version frontend active.",
    "CHAT_DELETE_WINDOW_TITLE": "Fenetre de suppression de discussion",
    "CHAT_DELETE_HELPER": "Cette valeur controle la fenetre de disponibilite de Supprimer pour tous en secondes. La garde backend change immediatement apres enregistrement. La visibilite de la bulle change apres un rafraichissement complet ou le prochain chargement de l'app.",
    "CHAT_DELETE_HELPER_FALLBACK": "Le service backend de controle de suppression de discussion n'a pas pu etre charge ; la valeur par defaut codee reste donc active jusqu'a ce que le bootstrap puisse relire le service protege.",
    "CHAT_DELETE_HELPER_SAVED": "La fenetre de disponibilite de Supprimer pour tous a ete enregistree dans config_domain_registry. La garde backend change immediatement. La visibilite de la bulle change apres un rafraichissement complet ou le prochain chargement de l'app.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Le service backend de controle de suppression de discussion n'a pas pu enregistrer la fenetre demandee.",
    "CHAT_DELETE_WINDOW_LABEL": "Fenetre Supprimer pour tous",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} s",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Stockez la valeur en secondes entieres. La valeur de production actuelle est 86400 secondes = 1 jour.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Secondes de la fenetre",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Saisissez un nombre entier superieur ou egal a 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Enregistrer la fenetre de suppression",
    "PROFILE_VISIBILITY_TITLE": "Visibilite du profil",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Vous devez etre connecte pour gerer la visibilite du compte.",
    "PROFILE_VISIBILITY_HELPER": "Ce commutateur met a jour uniquement l'etat de visibilite de votre compte. La decouvrabilite et le comportement des listes de bannieres restent inchanges dans cette phase.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "La visibilite du profil n'a pas pu etre chargee pour le moment.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "La visibilite du profil n'a pas pu etre mise a jour pour le moment.",
    "PROFILE_VISIBILITY_SAVED": "La visibilite de votre compte est maintenant {visibility}. Les indicateurs de decouvrabilite restent inchanges dans cette phase.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Compte public",
    "PROFILE_VISIBILITY_STORED": "Visibilite stockee",
    "WF1_MODEL_CONTROL_TITLE": "Controle du modele WF1",
    "WF1_ENABLE_TRANSLATION": "Activer traduction / pivot",
    "WF1_TRANSLATION_ACTIVE": "La traduction IA est active.",
    "WF1_TRANSLATION_INACTIVE": "WF1 continue de fonctionner, mais le texte source est copie et le pivot est marque comme inactif.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Emplacement runtime actif",
    "WF1_ALLOW_SAME_LANGUAGE": "Autoriser l'IA pour les paires de meme langue",
    "WF1_SAME_LANGUAGE_ACTIVE": "Les paires de meme langue suivent le routage WF1 normal.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Les paires de meme langue contournent l'IA et stockent Aucune langue pivot active.",
    "WF1_QWEN_ROUTING": "Routage des paires Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Les langues cochees ci-dessous utilisent Qwen-Max lorsque la paire est soit la meme langue cochee, soit une langue cochee avec l'anglais, soit deux langues non anglaises cochees. Sinon, le modele principal selectionne reste actif.",
    "WF1_OPENROUTER_TEST_SLOT": "Emplacement de test OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Emplacement de test OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Test qualite uniquement",
    "WF1_OPENROUTER_HELPER": "Cet emplacement est modifiable uniquement pour des tests qualite OpenRouter temporaires. Il ne change pas le chemin operationnel de routage des paires Qwen sauf si cet emplacement devient lui-meme le modele actif.",
    "WF1_LABEL": "Libelle",
    "WF1_PRODUCT": "Produit",
    "WF1_MODEL": "Modele",
    "WF1_PROVIDER_OPENROUTER": "Fournisseur : OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret : OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Emplacement de test OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max via OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Prix catalogue Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Prix catalogue OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Prix catalogue OpenRouter",
    "LANGUAGE_ENGLISH": "Anglais",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Chinois (simplifie)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Chinois (traditionnel)",
    "LANGUAGE_JAPANESE": "Japonais",
    "LANGUAGE_KOREAN": "Coreen",
    "LANGUAGE_PERSIAN": "Persan",
    "LANGUAGE_TURKISH_ISTANBUL": "Turc (Istanbul)",
    "LANGUAGE_ARABIC": "Arabe",
    "LANGUAGE_FRENCH": "Francais",
    "LANGUAGE_GERMAN": "Allemand",
    "LANGUAGE_SPANISH": "Espagnol",
    "LANGUAGE_PORTUGUESE": "Portugais",
    "LANGUAGE_ITALIAN": "Italien",
    "LANGUAGE_RUSSIAN": "Russe",
    "LANGUAGE_DUTCH": "Neerlandais",
    "LANGUAGE_VIETNAMESE": "Vietnamien",
    "LANGUAGE_INDONESIAN": "Indonesien",
    "LANGUAGE_THAI": "Thai",
    "LANGUAGE_MALAY": "Malais",
    "WF1_PRICING_CUSTOM": "Tarification : modele d'emplacement personnalise - verifiez le tarif OpenRouter actuel",
    "WF1_SAVE_OPENROUTER_SLOT": "Enregistrer l'emplacement OpenRouter",
    "WF1_PRICING_LINE": "Entree {input} - Sortie {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret : {secret}",
    "ZONE_VISIBILITY_TITLE": "Controle de visibilite des zones",
    "ZONE_ENABLE": "Activer {zone}",
    "ZONE_ENABLED_NOTE": "{zone} peut apparaitre pour les roles autorises apres le prochain chargement de l'app.",
    "ZONE_DISABLED_NOTE": "{zone} est traitee comme absente pour les utilisateurs non S_Admin apres le prochain chargement de l'app.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin contourne cette liste de roles et conserve toujours l'acces.",
    "ZONE_ROLE_LOCKED": "Les selections de roles sont temporairement verrouillees pendant que cette zone est desactivee et reviendront exactement comme enregistrees lorsque la zone sera reactivee.",
    "ZONE_LCAC_CONTROL": "Controle LCAC",
    "ZONE_RCAC_CONTROL": "Controle RCAC",
    "ZONE_LCAC_DESCRIPTION": "Controle l'existence de la zone reservee gauche et les roles qui peuvent la voir.",
    "ZONE_RCAC_DESCRIPTION": "Controle l'existence de la zone reservee droite et les roles qui peuvent la voir.",
    "ZONE_VISIBILITY_BACKEND": "Le bootstrap de visibilite des zones lit maintenant depuis le service backend protege. Les changements s'appliquent au prochain chargement de l'app.",
    "ZONE_VISIBILITY_CACHED": "Le service backend de visibilite des zones est indisponible pour le moment ; les valeurs en cache ou locales sont donc actives.",
    "ZONE_VISIBILITY_DEFAULTS": "Les valeurs par defaut de visibilite des zones sont actives car aucun etat backend ou en cache n'a pu etre charge.",
    "ZONE_VISIBILITY_SAVED": "Le bootstrap de visibilite des zones a ete enregistre. Un rechargement force ou le prochain chargement de l'app est requis pour l'application runtime.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Le service backend protege n'a pas pu enregistrer le changement de visibilite de zone demande.",
    "ROLE_MEMBER": "Membre",
    "ROLE_STAFF": "Personnel",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Activez les notifications pour recevoir les nouveaux messages.",
    "MAIN_LOG_OUT": "Deconnexion",
    "NOTIFICATION_NEW_MESSAGE": "Nouveau message",
    "NOTIFICATION_UNREAD_MESSAGE": "Vous avez un message non lu.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Vue complete",
    "MEDIA_AUDIO_ATTACHMENT": "Piece jointe audio",
    "MEDIA_FILE_FALLBACK": "Fichier",
    "MEDIA_DOWNLOAD_READY": "Piece jointe prete au telechargement",
    "MEDIA_TYPE_UNSUPPORTED": "Type non pris en charge en vue complete",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Image precedente",
    "MEDIA_NEXT_IMAGE_ARIA": "Image suivante",
    "MEDIA_OPEN_ORIGINAL": "Ouvrir l'original",
    "MEDIA_DOWNLOAD": "Telecharger",
    "MEDIA_CLOSE_ARIA": "Fermer",
    "MEDIA_PROFILE_PICTURE_ARIA": "Photo de profil de {name}",
    "MEDIA_PROFILE_ALT": "Profil de {name}",
    "MEDIA_UPLOAD_FAILED": "Echec du televersement",
    "MEDIA_BACKEND_TOKEN_ERROR": "Erreur de jeton backend",
    "MEDIA_UPLOAD_URL_MISSING": "Critique : l'URL de televersement est manquante dans la reponse backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Jeton d'authentification manquant pour le televersement de discussion",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "La demande de jeton de televersement de discussion a echoue",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Reponse de televersement de discussion invalide",
    "MEDIA_GCS_UPLOAD_FAILED": "Echec du televersement GCS",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nom de fichier ou contentType manquant",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path manquant",
    "BLOCK_NOTICE_TITLE": "Avis de blocage permanent",
    "BLOCK_NOTICE_MESSAGE": "Votre compte a ete temporairement suspendu en raison d'une violation de la politique.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Si vous pensez que cela necessite un suivi, veuillez contacter",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "par e-mail.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Utilisateur inconnu",
    "GENERAL_GUEST": "Invite",
    "ADVISOR_FOR_CLIENT": "Conseiller pour {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Le jeton et le mot de passe sont requis",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Le corps de la requete doit etre au format JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Jeton d'invitation invalide ou expire",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "La definition du mot de passe a echoue : session ou utilisateur manquant",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "La definition du mot de passe a echoue pendant la connexion",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "La generation du jeton admin a echoue",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "La connexion a echoue : session ou utilisateur manquant",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Inscription reussie. Veuillez verifier votre e-mail pour la verification.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Echec inconnu de l'inscription",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Traitement du jeton invalide",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Le jeton d'acces est requis",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "L'apercu du hash de jeton necessite l'indice e-mail depuis l'URL de redirection",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Impossible de resoudre l'identite pour ce jeton",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Seul l'Utilisateur Zero peut acceder au service de selection LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Seul l'Utilisateur Zero peut acceder au service de controle de visibilite des zones.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Seul l'Utilisateur Zero peut acceder au service de controle de version frontend.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Seul l'Utilisateur Zero peut inspecter la version frontend d'un autre utilisateur.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Seul l'Utilisateur Zero peut acceder au service de controle de suppression de discussion.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Seul l'Utilisateur Zero peut supprimer definitivement un compte utilisateur.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Payload de requete invalide.",
    "API_ERROR_INTERNAL_SERVER": "Erreur interne du serveur",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Fonction manquante dans le backend (rechargement requis)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Seule la RPC de base de donnees est autorisee pour les transitions delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Veuillez attendre avant d'envoyer un autre message.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Message envoye avec succes.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Le service de contact est indisponible.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "L'envoi du message a echoue.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Le nom est requis.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "L'e-mail est invalide.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Le message est requis.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Le payload du selecteur est requis.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Le payload de visibilite des zones est requis.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Le payload de version frontend est requis.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Le payload de controle de suppression de discussion est requis.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "L'identifiant utilisateur authentifie est requis.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "L'identifiant utilisateur spectateur authentifie est requis.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "L'identifiant utilisateur acteur authentifie est requis.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id est requis.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id est requis.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "La liste owner_user_ids est requise.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email est requis.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by est requis.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Le runtime de recherche est desactive par la version frontend globale.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Vous n'etes pas autorise a annuler cette invitation en attente.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Cette invitation ne peut plus etre annulee car l'utilisateur est deja inscrit.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Invitation en attente introuvable.",
    "INVITE_REPLY_ALREADY_MEMBER": "Felicitations, votre ami ({invitee_email}) est deja inscrit dans cette app et est membre de cet espace de travail.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Une invitation est en attente pour {invitee_email}, mais l'e-mail de relance n'a pas pu etre declenche. Veuillez verifier les journaux de messagerie.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "L'enregistrement d'invitation a ete cree pour {invitee_email}, mais la livraison de l'e-mail n'a pas pu etre confirmee. Veuillez reessayer plus tard ou verifier les journaux de messagerie.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Echec de la creation de l'enregistrement d'invitation. Veuillez reessayer plus tard.",
    "INVITE_REPLY_SYSTEM_ERROR": "Erreur systeme pendant le processus d'invitation : {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Erreur de configuration backend : identifiants Supabase manquants",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Erreur de configuration backend : URL Supabase invalide",
    "CHAT_ERROR_ACCESS_DENIED": "Acces refuse",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Le contenu ne peut pas etre vide pour les messages texte",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Impossible de determiner l'ID de conversation",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Le contexte d'authentification RPC est manquant",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "La RPC a renvoye un payload de message invalide",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Insertion echouee, aucune donnee renvoyee",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations doit etre une liste",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Payload d'operation invalide",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type non pris en charge",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id est requis",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Message introuvable",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "La suppression est autorisee uniquement sur votre propre message",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Supprimer pour tous n'est plus disponible pour ce message",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Supprimer pour tous a echoue",
    "API_ERROR_SERVER_CONFIGURATION": "Erreur de configuration du serveur",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "En-tete secret webhook manquant",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Source webhook non autorisee",
    "API_ERROR_BACKEND_CONFIGURATION": "Erreur de configuration backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Erreur d'attribut de module : {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Echec avant la suppression de l'invitation lors de la suppression de l'utilisateur auth en attente.",
    "CHAT_ERROR_DB": "Erreur DB : {error}",
}
