# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/hi.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "मुख्य",
    "APP_TITLE": "OTMEGA AI प्लेटफ़ॉर्म",
    "APP_SUBTITLE": "AI सलाहकार",
    "CHAT_PLACEHOLDER": "अपना संदेश लिखें...",
    "CHAT_SEND_BUTTON": "भेजें",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 सलाहकार गलती कर सकता है, इसलिए कृपया जाँच लें।",
    "STATUS_ONLINE": "ऑनलाइन",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "मेनू",
    "ICON_NEW_CHAT": "नई चैट",
    "ICON_HISTORY": "इतिहास",
    "ICON_TEMPLATES": "टेम्पलेट्स",
    "ICON_SETTINGS": "सेटिंग्स",
    "ICON_USER_PROFILE": "उपयोगकर्ता प्रोफ़ाइल",
    "ICON_QUICK_ACTIONS": "त्वरित कार्रवाइयाँ",
    "ICON_PINNED": "पिन किया गया",
    "ICON_GALLERY": "गैलरी",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "ऐप इंस्टॉल करें",
    "PWA_ANDROID_MSG": "बेहतर अनुभव और ऑफ़लाइन पहुँच के लिए इस ऐप को अपने डिवाइस पर इंस्टॉल करें।",
    "PWA_IOS_MSG": "इस ऐप को अपने iPhone/iPad पर इंस्टॉल करने के लिए:\n1. नीचे दिए गए शेयर बटन पर टैप करें\n2. 'होम स्क्रीन में जोड़ें' चुनें",
    "PWA_BTN_INSTALL": "इंस्टॉल करें",
    "PWA_BTN_LATER": "शायद बाद में",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "सलाहकार नेटवर्क में लॉग इन करें",
    "AUTH_HEADER_SIGNUP": "अपना एकीकृत खाता बनाएँ",
    "AUTH_HEADER_LOGIN_NETWORK": "सलाहकार नेटवर्क में लॉग इन करें",
    "AUTH_HEADER_SIGNUP_UNIFIED": "अपना एकीकृत खाता बनाएँ",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "लॉगिन",
    "AUTH_BUTTON_SIGNUP": "खाता बनाएँ",
    "AUTH_BUTTON_GOOGLE": "Google के साथ जारी रखें",
    "AUTH_BUTTON_FORGOT_PASSWORD": "पासवर्ड भूल गए",
    "AUTH_BUTTON_SEND_RESET_LINK": "रीसेट लिंक भेजें",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "खाता नहीं है? साइन अप करें",
    "AUTH_PROMPT_LOGIN": "पहले से खाता है? लॉग इन करें",
    "AUTH_HELPER_TEXT_SIGNUP": "आप एक एकीकृत खाता बना रहे हैं जिसका उपयोग आप इस प्लेटफ़ॉर्म के सभी सलाहकारों तक पहुँचने के लिए कर सकते हैं।",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "आप एक एकीकृत खाता बना रहे हैं जिसका उपयोग आप इस प्लेटफ़ॉर्म के सभी सलाहकारों तक पहुँचने के लिए कर सकते हैं।",
    "AUTH_HELPER_TEXT_LOGIN": "वही खाता (ईमेल/पासवर्ड या Google) उपयोग करें जो आपने इस नेटवर्क के अन्य सलाहकारों के लिए उपयोग किया था।",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "वही खाता (ईमेल/पासवर्ड या Google) उपयोग करें जो आपने इस नेटवर्क के अन्य सलाहकारों के लिए उपयोग किया था।",
    "AUTH_FORGOT_PASSWORD_LINK": "अपना पासवर्ड भूल गए?",
    "AUTH_FORGOT_PASSWORD_TITLE": "अपना पासवर्ड रीसेट करें",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "अपना ईमेल पता दर्ज करें और हम आपको पासवर्ड रीसेट करने के लिए एक लिंक भेजेंगे।",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "ईमेल",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "आपको लॉग इन किया जा रहा है...",
    "AUTH_STATUS_LOADING_SIGNUP": "आपका खाता बनाया जा रहा है...",
    "AUTH_STATUS_LOADING_RESET": "रीसेट लिंक भेजा जा रहा है...",
    "AUTH_STATUS_SUCCESS_LOGIN": "लॉगिन सफल! फिर से लोड हो रहा है...",
    "AUTH_STATUS_SUCCESS_RESET": "रीसेट लिंक सफलतापूर्वक भेजा गया। कृपया अपना ईमेल देखें।",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "पासवर्ड रीसेट लिंक सफलतापूर्वक भेजा गया। कृपया अपना ईमेल देखें।",

    "AUTH_ERROR_INVALID_CREDENTIALS": "अमान्य ईमेल या पासवर्ड।",
    "AUTH_ERROR_EMAIL_EXISTS": "इस ईमेल वाला खाता सलाहकार नेटवर्क में पहले से मौजूद है।",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "इस ईमेल वाला खाता पहले से मौजूद है। कृपया लॉग इन करें। आप वर्तमान में इनके सदस्य हैं:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "इस ईमेल वाला खाता सलाहकार नेटवर्क में पहले से मौजूद है। कृपया यह विंडो बंद करें और उसी ईमेल तथा अपने पिछले पासवर्ड के साथ 'Login' अनुभाग का उपयोग करें।",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "आप वर्तमान में इनके सदस्य हैं:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "ईमेल और पासवर्ड आवश्यक हैं।",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "खाता बन गया, लेकिन सदस्यता सेट अप नहीं हो सकी। कृपया सहायता से संपर्क करें।",
    "AUTH_ERROR_DEFAULT": "एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "अतिथि बैनर नियंत्रण पेलोड आवश्यक है।",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "केवल User Zero ही अतिथि बैनर नियंत्रणों को अपडेट कर सकता है।",
    "AUTH_FORGOT_PASSWORD_ERROR": "रीसेट लिंक भेजने में विफल। कृपया पुनः प्रयास करें।",
    "INVITE_REPLY_EMAIL_SENT": "Collabra आमंत्रण ईमेल आपके मित्र को {invitee_email} पर भेज दिया गया।",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra आमंत्रण ईमेल आपके मित्र को {invitee_email} पर फिर से भेज दिया गया।",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "पासवर्ड दिखाएँ",
    "AUTH_PASSWORD_TOGGLE_HIDE": "पासवर्ड छिपाएँ",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "ठीक है",
    "GENERAL_CANCEL": "रद्द करें",
    "GENERAL_CLOSE": "बंद करें",
    "GENERAL_SEND": "भेजें",
    "GENERAL_SEARCH": "खोजें",
    "GENERAL_RESET": "रीसेट करें",
    "GENERAL_ENABLE": "सक्षम करें",
    "GENERAL_LOADING": "लोड हो रहा है...",
    "GENERAL_DELETE": "हटाएँ",
    "GENERAL_DELETING": "हटाया जा रहा है...",
    "GENERAL_SAVE_PASSWORD": "पासवर्ड सहेजें",
    "AUTH_REMEMBER_EMAIL_LABEL": "ईमेल याद रखें",
    "GENERAL_SAVING": "सहेजा जा रहा है...",
    "GENERAL_SENDING": "भेजा जा रहा है...",
    "GENERAL_REMOVING": "हटाया जा रहा है...",
    "GENERAL_CONFIRM_REMOVAL": "हटाने की पुष्टि करें",
    "GENERAL_EMPTY": "खाली",
    "GENERAL_UNAVAILABLE": "अनुपलब्ध",
    "GENERAL_ENABLED": "सक्षम",
    "GENERAL_DISABLED": "अक्षम",
    "GENERAL_GRANTED": "अनुमति मिली",
    "GENERAL_DENIED": "अस्वीकृत",
    "GENERAL_DEFAULT": "डिफ़ॉल्ट",
    "GENERAL_UNSUPPORTED": "समर्थित नहीं",
    "GENERAL_PUBLIC": "सार्वजनिक",
    "GENERAL_PRIVATE": "निजी",
    "GENERAL_USERNAME": "उपयोगकर्ता नाम",
    "GENERAL_EMAIL": "ईमेल",
    "GENERAL_YOU": "आप",
    "GENERAL_USER": "उपयोगकर्ता",
    "GENERAL_UNKNOWN": "अज्ञात",
    "GENERAL_VISITOR": "आगंतुक",
    "GENERAL_PROFILE": "प्रोफ़ाइल",
    "GENERAL_BANNER": "बैनर",
    "GENERAL_UNKNOWN_BANNER": "अज्ञात बैनर",
    "GENERAL_ADVISOR_BANNER": "सलाहकार बैनर",
    "GENERAL_NOT_AVAILABLE": "उपलब्ध नहीं",
    "GENERAL_NOT_SELECTED": "चयनित नहीं",
    "GENERAL_NO_EMAIL_FOUND": "कोई ईमेल नहीं मिला",
    "GENERAL_USER_ZERO_ONLY": "केवल User Zero",
    "GENERAL_CONNECTION_STATE": "कनेक्शन स्थिति",
    "GENERAL_DISPLAY_ONLY": "केवल प्रदर्शन",
    "GENERAL_TEXTAREA": "टेक्स्ट क्षेत्र",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "मेनू (LCAC)",
    "HEADER_CHAT_CCAC": "चैट (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "त्वरित कार्रवाइयाँ (RCAC)",
    "HEADER_CHANGE_STATUS": "स्थिति बदलें",
    "HEADER_OT_COIN_BALANCE": "OT Coin शेष",
    "HEADER_ALT_USER": "उपयोगकर्ता",
    "STATUS_BUSY": "व्यस्त",
    "STATUS_AWAY": "दूर",
    "STATUS_OFFLINE": "ऑफ़लाइन",
    "STATUS_INVISIBLE": "अदृश्य",
    "NETWORK_CHECKING_CONNECTION": "कनेक्शन जाँचा जा रहा है...",
    "NETWORK_ONLINE_LATENCY": "ऑनलाइन (विलंबता: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "नेटवर्क: अच्छा (पिंग करने के लिए टैप करें)",
    "CHAT_TARGET_ALT": "चैट लक्ष्य",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "खोजें...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "{name} की प्रोफ़ाइल तस्वीर खोलें",
    "CHAT_MESSAGE_INPUT_ARIA": "संदेश इनपुट",
    "CHAT_TOGGLE_VIEW_ARIA": "दृश्य बदलें",
    "CHAT_ADD_USER_ARIA": "उपयोगकर्ता जोड़ें",
    "CHAT_ATTACH_ARIA": "संलग्न करें",
    "CHAT_MIC_ARIA": "माइक्रोफ़ोन",
    "CHAT_SEND_ARIA": "भेजें",
    "CHAT_SEARCH_ARIA": "खोजें",
    "CHAT_OPEN_SEARCH_ARIA": "खोज खोलें",
    "CHAT_CLOSE_SEARCH_ARIA": "खोज बंद करें",
    "CHAT_ATTACHMENT_ALT": "संलग्नक",
    "CHAT_PREVIEW_ALT": "पूर्वावलोकन",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "संलग्नक हटाएँ",
    "CHAT_REPLYING_TO": "जवाब दे रहे हैं",
    "CHAT_CANCEL_REPLY_ARIA": "जवाब रद्द करें",
    "CHAT_UPLOADING": "अपलोड हो रहा है...",
    "CHAT_LOADING_CHATS": "चैट लोड हो रही हैं...",
    "CHAT_SEND_FAILED": "भेजना विफल",
    "CHAT_SEND_FAILED_RETRY": "भेजना विफल। कृपया पुनः प्रयास करें।",
    "CHAT_RETRY": "पुनः प्रयास करें",
    "CHAT_EDITED": "संपादित",
    "CHAT_TYPING": "टाइप कर रहे हैं",
    "CHAT_LOADING": "लोड हो रहा है",
    "CHAT_PENDING_INVITATION": "लंबित आमंत्रण",
    "CHAT_PENDING_INVITATION_MIN": "{count} मिनट लंबित आमंत्रण",
    "CHAT_PENDING_INVITATION_HR": "{count} घंटा लंबित आमंत्रण",
    "CHAT_PENDING_INVITATION_DAY": "{count} दिन लंबित आमंत्रण",
    "CHAT_WAITING_FOR_YOU": "{label} - आपकी प्रतीक्षा में",
    "CHAT_PENDING_ACCEPTANCE": "{label} - स्वीकृति लंबित",
    "CHAT_MICROPHONE_ACCESS_DENIED": "माइक्रोफ़ोन पहुँच अस्वीकृत।",
    "CHAT_UPLOAD_FAILED": "अपलोड विफल: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "अपलोड के लिए इंटरनेट कनेक्शन आवश्यक है। ऑनलाइन होने पर कृपया पुनः प्रयास करें।",
    "CHAT_ERROR_AUTH": "प्रमाणीकरण त्रुटि",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "फ़ाइल नाम या content_type अनुपलब्ध",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id या target_id अनुपलब्ध",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "गैर-अवतार अपलोड के लिए conversation_id अनुपलब्ध",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "अमान्य avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase सेवा क्लाइंट अनुपलब्ध",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Avatar read ack केवल सलाहकार चैट संदर्भ में मान्य है",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatar flow संदेश नहीं मिला या read ack के लिए पात्र नहीं है",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Avatar संदेश को पढ़ा हुआ अंतिम रूप देने में विफल",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 संलग्नक",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} संलग्नक",
    "CHAT_VOICE_NOTE": "वॉइस नोट",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "चैट अनुपलब्ध है। इस उपयोगकर्ता ने आपको ब्लॉक किया है।",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "चैट अनुपलब्ध है। आपने इस उपयोगकर्ता को ब्लॉक किया है।",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "खाते की पहुँच नीति द्वारा अवरुद्ध है।",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "चैट अनुपलब्ध है। यह खाता User Zero द्वारा अंतिम रूप से ब्लॉक है।",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "चैट अनुपलब्ध है। पारस्परिक ब्लॉक सक्रिय है।",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "ब्लॉक नीति के कारण चैट अनुपलब्ध है।",
    "MESSAGE_PREVIEW_PHOTO": "फ़ोटो",
    "MESSAGE_PREVIEW_VOICE": "वॉइस संदेश",
    "MESSAGE_PREVIEW_VIDEO": "वीडियो",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "फ़ाइल",
    "MESSAGE_PREVIEW_MESSAGE": "संदेश",
    "MESSAGE_PREVIEW_SYSTEM": "सिस्टम संदेश",
    "MESSAGE_PREVIEW_NEW": "नया संदेश",
    "MESSAGE_UNKNOWN_FILE": "अज्ञात फ़ाइल",
    "MESSAGE_AUDIO_ATTACHMENT": "ऑडियो संलग्नक",
    "MESSAGE_FILE_ATTACHMENT": "संलग्नक",
    "BANNER_INVITED_BY": "{label} द्वारा आमंत्रित",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "खोज परिणाम",
    "SEARCH_QUERY_LABEL": "क्वेरी:",
    "SEARCH_LOADING_VISIBILITY": "खोज दृश्यता लोड हो रही है...",
    "SEARCH_NO_RESULTS": "वर्तमान खोज दायरे में कोई परिणाम नहीं मिला।",
    "SHARE_WITH_COLLABRA": "Collabra के साथ साझा करें",
    "SHARE_SEND_TO": "भेजें",
    "SHARE_SELECT_ONE_BANNER": "एक बैनर चुनें",
    "SHARE_BANNER_LIST_ARIA": "बैनर सूची",
    "SHARE_NO_MATCHING_BANNER": "कोई मेल खाता बैनर नहीं",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "एक टिप्पणी जोड़ें...",
    "SHARE_RECENT_CHATS": "हाल की चैट",
    "SHARE_LEFT_LIST": "बाईं सूची",
    "SHARE_RIGHT_LIST": "दाईं सूची",
    "SHARE_UNTITLED_BANNER": "शीर्षकरहित बैनर",
    "SHARE_SHARED_CONTENT": "साझा सामग्री",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "साझा सामग्री खोली नहीं जा सकी।",
    "SHARE_OPEN_BANNER_FAILED": "चयनित बैनर खोला नहीं जा सका।",
    "SHARE_ONE_PHOTO_SELECTED": "1 फ़ोटो चयनित",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} फ़ोटो चयनित",
    "SHARE_ONE_FILE_SELECTED": "1 फ़ाइल चयनित",
    "SHARE_MANY_FILES_SELECTED": "{count} फ़ाइलें चयनित",
    "FORWARD_MESSAGE_TITLE": "संदेश अग्रेषित करें",
    "FORWARD_SELECT_RECIPIENTS": "प्राप्तकर्ता चुनें",
    "FORWARD_NO_OTHER_BANNER": "कोई अन्य बैनर उपलब्ध नहीं।",
    "FORWARD_SEND_TO_COUNT": "{count} को भेजें",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "कम से कम एक बैनर चुनें।",
    "FORWARD_FAILED_DEFAULT": "अग्रेषण विफल। कृपया पुनः प्रयास करें।",
    "FORWARD_PARTIAL_SENT": "{count} भेजे गए। {error}",
    "FORWARD_SOURCE_NOT_FOUND": "अग्रेषण के लिए स्रोत संदेश नहीं मिला",
    "FORWARD_NO_FORWARDABLE_CONTENT": "इस संदेश में अभी कोई अग्रेषण योग्य सामग्री नहीं है",
    "FORWARD_DESTINATION_MISSING": "अग्रेषण गंतव्य अनुपलब्ध है",
    "FORWARD_MESSAGE_PREVIEW": "अग्रेषित संदेश",
    "MENU_PASTE": "चिपकाएँ",
    "MENU_COPY": "कॉपी करें",
    "MENU_REPLY": "जवाब दें",
    "MENU_FORWARD": "अग्रेषित करें",
    "MENU_REMOVE_INVITATION": "आमंत्रण हटाएँ",
    "MENU_REMOVE_FROM_LIST": "सूची से हटाएँ",
    "MENU_GOODBYE_GUEST": "अलविदा अतिथि",
    "MENU_ADD_TO_LIST": "सूची में जोड़ें",
    "MENU_REJECT_INVITATION": "आमंत्रण अस्वीकार करें",
    "MENU_FRONTEND_VERSION": "Frontend संस्करण",
    "MENU_BANNER_HEADER": "बैनर - {zone}",
    "MENU_BANNER_INFO": "बैनर जानकारी: {title}",
    "MENU_MESSAGE_BUBBLE": "संदेश बबल",
    "MENU_CHAT_CANVAS_HEADER": "चैट कैनवास - {zone}",
    "MENU_CANVAS_INFO": "कैनवास जानकारी",
    "MENU_CHAT_CANVAS_SUBLABEL": "बातचीत क्षेत्र / वर्तमान चैट सतह",
    "MENU_INPUT_AREA_HEADER": "इनपुट क्षेत्र - {zone}",
    "MENU_INPUT_AREA_INFO": "इनपुट क्षेत्र जानकारी: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "नीचे का टाइपिंग और कार्रवाई उपकरण क्षेत्र",
    "MENU_HEADER": "हेडर - {zone}",
    "MENU_HEADER_INFO": "हेडर जानकारी: {title}",
    "MENU_HEADER_DESCRIPTION": "शीर्ष नेविगेशन और पेज नियंत्रण",
    "MENU_ZONE_HEADER": "ज़ोन - {zone}",
    "MENU_ZONE_SPACE_INFO": "ज़ोन स्पेस जानकारी",
    "MENU_EMPTY_LIST_SURFACE": "खाली/सूची सतह",
    "MENU_BLOCK": "ब्लॉक करें",
    "MENU_UNBLOCK": "अनब्लॉक करें",
    "MENU_HIDE_IN_SEARCH": "खोज में छिपाएँ",
    "MENU_UNHIDE_IN_SEARCH": "खोज में दिखाएँ",
    "MENU_VISIBLE_IN_SEARCH": "खोज में दृश्यमान",
    "MENU_HIDDEN_IN_SEARCH": "खोज में छिपा हुआ",
    "MENU_VISIBLE_IN_USER_LIST": "उपयोगकर्ता सूची में दृश्यमान",
    "MENU_HIDDEN_IN_USER_LIST": "उपयोगकर्ता सूची में छिपा हुआ",
    "MENU_NOT_BLOCKED": "ब्लॉक नहीं",
    "MENU_BLOCKED": "ब्लॉक किया गया",
    "MENU_FRONTEND_VERSION_LOADING": "लोड हो रहा है...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Backend से प्रति-बैनर मान लोड हो रहा है। डेटाबेस प्रतिक्रिया आने तक कोई विकल्प सक्रिय चिह्नित नहीं होगा।",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend मान लोड नहीं किया जा सका। कोई विश्वसनीय सक्रिय विकल्प नहीं दिखाया गया।",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "डेटाबेस में स्पष्ट प्रति-बैनर मान {overrideVersion} है। वैश्विक डिफ़ॉल्ट {globalDefaultVersion} है। स्टार्टअप bootstrap लागू करने के लिए लक्षित उपयोगकर्ता को ऐप पूरी तरह refresh या फिर से खोलना होगा।",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "कोई स्पष्ट प्रति-बैनर डेटाबेस मान संग्रहीत नहीं है। FeV2.0.0 डिफ़ॉल्ट रूप से सक्रिय है। वैश्विक डिफ़ॉल्ट {globalDefaultVersion} है।",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "लक्षित ऐप के पूर्ण reload के बाद स्पष्ट प्रति-बैनर डेटाबेस मान सक्रिय होता है",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "कोई स्पष्ट प्रति-बैनर मान संग्रहीत नहीं है; यह डिफ़ॉल्ट व्यक्तिगत FeV2.0.0 स्थिति है",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "यह विकल्प वर्तमान वैश्विक डिफ़ॉल्ट के बराबर भी है",
    "MENU_DELETE_PERMANENT_CONFIRM": "क्या डेटाबेस से {target} को स्थायी रूप से हटाएँ? इससे खाता, चैट इतिहास, निर्भरताएँ हट जाएँगी और भविष्य में फिर प्रवेश के लिए पूरा नया invite path आवश्यक होगा।",
    "MENU_DELETE_PERMANENTLY": "स्थायी रूप से हटाएँ",
    "MENU_REFRESH_PAGE": "पेज refresh करें",
    "MENU_LOG_OFF": "लॉग ऑफ़",
    "MENU_HARD_RELOAD": "Hard Reload",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "ईमेल (Admin User)",
    "AUTH_PASSWORD_PLACEHOLDER": "पासवर्ड",
    "AUTH_CONNECTING": "कनेक्ट हो रहा है...",
    "AUTH_SIGNING_OUT": "साइन आउट हो रहा है...",
    "AUTH_BACK_TO_LOGIN": "लॉगिन पर वापस जाएँ",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "अमान्य सर्वर प्रतिक्रिया: कोई टोकन नहीं मिला।",
    "AUTH_LOGIN_FAILED": "लॉगिन विफल",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "पासवर्ड मेल नहीं खाते।",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "पासवर्ड मेल नहीं खाते!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "पासवर्ड बिल्कुल समान होने चाहिए।",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "नया पासवर्ड",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "पासवर्ड की पुष्टि करें",
    "AUTH_CHANGE_PASSWORD": "पासवर्ड बदलें",
    "AUTH_SAVING_PASSWORD": "सहेजा जा रहा है...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "पासवर्ड सफलतापूर्वक अपडेट हुआ।",
    "AUTH_CHANGE_PASSWORD_UNABLE": "अभी पासवर्ड बदलना संभव नहीं है।",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "पासवर्ड बदलने के लिए आपको लॉग इन होना होगा।",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "नए पासवर्ड की दृश्यता बदलें",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "पासवर्ड पुष्टि की दृश्यता बदलें",
    "REGISTER_TITLE": "पंजीकरण पूरा करें",
    "REGISTER_SUBTITLE": "कृपया अपना पासवर्ड मैन्युअल रूप से सेट करें।",
    "REGISTER_CREATING_ACCOUNT": "खाता बनाया जा रहा है...",
    "REGISTER_FINISH_SETUP": "सेटअप पूरा करें",
    "REGISTER_FAILED_SET_PASSWORD": "पासवर्ड सेट करने में विफल",
    "INVITE_EMAIL_INSTRUCTION": "कृपया आमंत्रित व्यक्ति का ईमेल दर्ज करें (प्रारूप: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "आमंत्रित करें",
    "INVITE_EMAIL_REQUIRED": "कृपया आमंत्रित व्यक्ति का ईमेल दर्ज करें।",
    "INVITE_EMAIL_INVALID": "अमान्य ईमेल प्रारूप। कृपया उपयोग करें: user@example.com",
    "PENDING_INVITATION_TITLE": "लंबित आमंत्रण",
    "PENDING_INVITATION_REMOVE_QUESTION": "क्या इस लंबित आमंत्रण को डेटाबेस से हटाएँ?",
    "PENDING_INVITATION_KEEP": "आमंत्रण रखें",
    "PENDING_INVITATION_REMOVAL_FAILED": "हटाना विफल।",
    "REMOVE_FROM_LIST_TITLE": "सूची से हटाएँ",
    "REMOVE_FROM_LIST_WARNING": "क्या इस उपयोगकर्ता को अभी दोनों सूचियों से हटाएँ? चैट पहुँच तुरंत कट जाएगी। वापसी का एकमात्र रास्ता नया आमंत्रण है।",
    "REMOVE_FROM_LIST_KEEP": "उपयोगकर्ता को सूची में रखें",
    "REMOVE_FROM_LIST_FAILED": "सूची से हटाना विफल।",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "सेटिंग और लाइव स्थिति",
    "PERMISSION_DIALOG_ARIA": "सेटिंग और लाइव स्थिति",
    "PERMISSION_TRIGGER_ARIA": "सेटिंग्स पॉपअप ट्रिगर",
    "PERMISSION_CLOSE_ARIA": "अनुमति पॉपअप बंद करें",
    "PERMISSION_LIVE_STATUS": "लाइव स्थिति",
    "PERMISSION_SYSTEM_PERMISSION": "सिस्टम अनुमति",
    "PERMISSION_APP_PUSH": "ऐप Push",
    "PERMISSION_LOCATION_PERMISSION": "स्थान अनुमति",
    "PERMISSION_APP_LOCATION": "ऐप स्थान",
    "PERMISSION_CONTROLS": "अनुमति नियंत्रण",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push सूचनाएँ",
    "PERMISSION_LOCATION_ACCESS": "स्थान पहुँच",
    "PERMISSION_IN_APP_SETTINGS": "इन-ऐप सेटिंग्स",
    "PERMISSION_ALERT_SOUND": "अलर्ट ध्वनि",
    "PERMISSION_APP_BADGE": "ऐप बैज",
    "PERMISSION_PASSWORD_SETTINGS": "पासवर्ड सेटिंग्स",
    "PERMISSION_NAVIGATION_STATUS": "नेविगेशन स्थिति",
    "PERMISSION_SELECTED_ZONE": "चयनित ज़ोन",
    "PERMISSION_STAGED_CHAT_BANNER": "स्टेज्ड चैट बैनर",
    "PERMISSION_CANVAS_CONTENT": "कैनवास सामग्री",
    "PERMISSION_YOUR_DEVICES": "आपके डिवाइस ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "डिवाइस सूची refresh करें",
    "PERMISSION_REFRESH_LIST": "सूची refresh करें",
    "PERMISSION_NO_REGISTERED_DEVICES": "कोई पंजीकृत डिवाइस नहीं मिला।",
    "PERMISSION_RESIZE_POPUP_ARIA": "सेटिंग्स पॉपअप का आकार बदलें",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Push सूचनाएँ चालू/बंद करें",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "स्थान पहुँच चालू/बंद करें",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "अलर्ट ध्वनि चालू/बंद करें",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "ऐप बैज चालू/बंद करें",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "प्रोफ़ाइल दृश्यता चालू/बंद करें",
    "PERMISSION_OFF_IN_V1": "v1 में बंद",
    "PERMISSION_CHAT": "चैट",
    "PERMISSION_BANNER_LIST": "बैनर सूची",
    "PERMISSION_PUSH_DISABLED_V1": "v1 Google Play रिलीज़ के लिए push सूचनाएँ अक्षम हैं।",
    "PERMISSION_PUSH_ON_TOOLTIP": "इस डिवाइस के लिए push सूचनाएँ चालू हैं।",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "सिस्टम सूचनाएँ ब्लॉक हैं। सेटिंग्स सहायता खोलने के लिए टैप करें।",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "डिलीवरी विश्वसनीयता सुधारने के लिए चालू करें।",
    "PERMISSION_SYSTEM_DISABLE_HELP": "सिस्टम सूचनाएँ अक्षम करने के लिए, अपने ब्राउज़र/साइट notification settings खोलें और इस साइट को Block पर सेट करें।",
    "PERMISSION_SYSTEM_ALLOW_HELP": "सिस्टम notification permission बदलने के लिए, अपने ब्राउज़र/साइट notification settings खोलें और इस साइट को Allow पर सेट करें।",
    "PERMISSION_LOCATION_ON_TOOLTIP": "दूरी-आधारित LCAC sorting और map positioning के लिए स्थान पहुँच चालू है।",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "इस वातावरण में Location API समर्थित नहीं है।",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "स्थान पहुँच ब्लॉक है। सेटिंग्स सहायता खोलने के लिए टैप करें।",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "सटीक दूरी-आधारित LCAC sorting और इन-ऐप map positioning की अनुमति देने के लिए चालू करें।",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "इस वातावरण में स्थान पहुँच समर्थित नहीं है।",
    "PERMISSION_LOCATION_DISABLE_HELP": "स्थान पहुँच अक्षम करने के लिए, अपने ब्राउज़र/साइट location settings खोलें और इस साइट को Block पर सेट करें।",
    "PERMISSION_LOCATION_ALLOW_HELP": "दूरी sorting और इन-ऐप map positioning के लिए स्थान पहुँच सक्षम करने हेतु, अपने ब्राउज़र/साइट location settings खोलें और इस साइट को Allow पर सेट करें।",
    "PERMISSION_DEVICE_LOAD_FAILED": "अभी पंजीकृत डिवाइस लोड नहीं किए जा सकते।",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "UI Bridge लोड हो रहा है...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Local Bridge लोड हो रहा है...",
    "RUNTIME_LOADING_BACKEND": "Backend लोड हो रहा है...",
    "RUNTIME_LOADING": "लोड हो रहा है...",
    "RUNTIME_LOADING_FROM_DATABASE": "डेटाबेस से लोड हो रहा है...",
    "RUNTIME_BACKEND_CONNECTED": "Backend कनेक्टेड",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Cached Fallback सक्रिय",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback Default सक्रिय",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallback Defaults सक्रिय",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Backend के माध्यम से सहेजा जा रहा है...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Backend Service में सहेजा गया",
    "RUNTIME_SAVE_FAILED": "सहेजना विफल",
    "RUNTIME_LOAD_FAILED": "लोड करना विफल",
    "RUNTIME_CONNECTED": "कनेक्टेड",
    "RUNTIME_LOGIN_REQUIRED": "लॉगिन आवश्यक",
    "RUNTIME_SAVED": "सहेजा गया",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI तैयार - Runtime लंबित",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Protected backend selector service ने अनुरोधित model option को अस्वीकार कर दिया या सहेज नहीं सका।",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Protected backend selector service ने अनुरोधित WF1 routing change को अस्वीकार कर दिया या सहेज नहीं सका।",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selector अब protected backend service से active config, Qwen routing और allowed options पढ़ रहा है।",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend selector service अभी अनुपलब्ध है, इसलिए अंतिम cached selector state का उपयोग किया जा रहा है।",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Selector default values सक्रिय हैं क्योंकि कोई backend या cached selector state लोड नहीं हो सका।",
    "RUNTIME_WF1_SELECTOR_SAVED": "Protected backend selector service ने active WF1 routing config अपडेट किया और runtime domain cache refresh किया।",
    "FRONTEND_VERSION_TITLE": "Frontend संस्करण",
    "FRONTEND_VERSION_HELPER_ACTIVE": "यह selector सभी उपयोगकर्ताओं के लिए active frontend version नियंत्रित करता है। FeV2.0.0 सक्रिय है।",
    "FRONTEND_VERSION_HELPER_RUNTIME": "यह selector config_domain_registry से active frontend version पढ़ता है। Runtime FeV2.0.0 पर resolve होता है।",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend frontend-version config लोड नहीं हो सका, इसलिए coded FeV2.0.0 default तब तक सक्रिय है जब तक startup bootstrap protected service को फिर से पढ़ सके।",
    "FRONTEND_VERSION_HELPER_SAVED": "Active frontend version config_domain_registry में सहेजा गया। Full refresh या अगला app load runtime value लागू करता है।",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend frontend-version control service अनुरोधित global version सहेज नहीं सका।",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Active frontend version।",
    "CHAT_DELETE_WINDOW_TITLE": "Chat Delete Window",
    "CHAT_DELETE_HELPER": "यह मान Delete for everyone availability window को सेकंड में नियंत्रित करता है। Save के तुरंत बाद backend guard बदल जाता है। Bubble visibility full refresh या अगले app load के बाद बदलती है।",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend chat delete control service लोड नहीं हो सका, इसलिए coded default तब तक सक्रिय रहेगा जब तक startup bootstrap protected service को फिर से पढ़ सके।",
    "CHAT_DELETE_HELPER_SAVED": "Delete for everyone availability window config_domain_registry में सहेजी गई। Backend guard तुरंत बदलता है। Bubble visibility full refresh या अगले app load के बाद बदलती है।",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend chat delete control service अनुरोधित window value सहेज नहीं सका।",
    "CHAT_DELETE_WINDOW_LABEL": "Delete for everyone window",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} सेकंड",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "मान को पूर्ण सेकंड में संग्रहीत करें। वर्तमान production value 86400 seconds = 1 day है।",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Window Seconds",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "0 या उससे अधिक पूर्ण संख्या दर्ज करें।",
    "CHAT_DELETE_SAVE_BUTTON": "Delete Window सहेजें",
    "GUEST_BANNER_CONTROL_TITLE": "अतिथि बैनर",
    "GUEST_BANNER_CONTROL_LABEL": "गेस्ट QR चैट",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "सभी यूज़र्स के लिए गेस्ट बैनर दिखाएँ",
    "GUEST_BANNER_CONTROL_HELPER": "फ़िक्स्ड गेस्ट बैनर और पेंडिंग QR टोकन की लाइफ़टाइम को कंट्रोल करता है.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "गेस्ट बैनर कंट्रोल के लिए लोकल फ़ॉलबैक सक्रिय है.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "गेस्ट बैनर कंट्रोल सेव किए गए.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "गेस्ट बैनर कंट्रोल सेव नहीं किए जा सके.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} गेस्ट सेशन रद्द किए गए.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "पेंडिंग QR TTL (मिनट)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "मौजूदा पेंडिंग QR TTL: {count} मिनट.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "मिनटों की एक पॉज़िटिव पूरी संख्या डालें.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "गेस्ट बैनर सेव करें",
    "GUEST_QR_LOADING": "गेस्ट QR तैयार किया जा रहा है...",
    "GUEST_QR_READY": "अस्थायी गेस्ट चैट खोलने के लिए स्कैन करें.",
    "GUEST_QR_ALT": "गेस्ट चैट QR कोड",
    "GUEST_QR_LOAD_FAILED": "गेस्ट QR तैयार नहीं किया जा सका.",
    "GUEST_SESSION_ACTIVE": "गेस्ट कनेक्टेड है.",
    "GUEST_PUBLIC_TITLE": "गेस्ट चैट",
    "GUEST_PUBLIC_CONNECTING": "कनेक्ट हो रहा है...",
    "GUEST_PUBLIC_CONNECTED": "कनेक्ट हो गया",
    "GUEST_PUBLIC_UNAVAILABLE": "यह गेस्ट लिंक उपलब्ध नहीं है.",
    "GUEST_PUBLIC_SEND_FAILED": "संदेश नहीं भेजा जा सका।",
    "UI_TEXTS_RUNTIME_TITLE": "UI भाषा रनटाइम",
    "UI_TEXTS_RUNTIME_BACKEND": "UI भाषा रनटाइम सुरक्षित बैकएंड सेवा से पढ़ रहा है। बदलाव अगले पूर्ण ऐप लोड पर लागू होंगे।",
    "UI_TEXTS_RUNTIME_CACHED": "बैकएंड UI भाषा रनटाइम सेवा अभी अनुपलब्ध है, इसलिए कैश्ड या स्थानीय डिफ़ॉल्ट सक्रिय हैं।",
    "UI_TEXTS_RUNTIME_DEFAULTS": "UI भाषा रनटाइम डिफ़ॉल्ट सक्रिय हैं क्योंकि कोई बैकएंड या कैश्ड स्थिति लोड नहीं की जा सकी।",
    "UI_TEXTS_RUNTIME_SAVED": "UI भाषा रनटाइम नियंत्रण सहेजा गया था। उपयोगकर्ताओं को नया भाषा गेट प्राप्त करने के लिए एक पूर्ण रीफ़्रेश या अगले ऐप लोड की आवश्यकता है।",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "सुरक्षित बैकएंड सेवा अनुरोधित UI भाषा रनटाइम परिवर्तन को सहेज नहीं सकी।",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "डिवाइस भाषा एप्लिकेशन",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "रनटाइम UI भाषाएँ सक्षम करें",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "उपयोगकर्ता अपनी संग्रहीत या डिवाइस भाषा के लिए UI टेक्स्ट पेलोड प्राप्त कर सकते हैं।",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "सभी उपयोगकर्ताओं को अंग्रेज़ी UI टेक्स्ट के लिए बाध्य किया जाता है, और डिवाइस भाषा को अनदेखा कर दिया जाता है।",
    "PROFILE_VISIBILITY_TITLE": "प्रोफ़ाइल दृश्यता",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "खाता दृश्यता प्रबंधित करने के लिए आपको लॉग इन होना होगा।",
    "PROFILE_VISIBILITY_HELPER": "यह switch केवल आपके account visibility state को अपडेट करता है। Discoverability और banner-list behavior इस चरण में अपरिवर्तित रहते हैं।",
    "PROFILE_VISIBILITY_LOAD_FAILED": "प्रोफ़ाइल दृश्यता अभी लोड नहीं की जा सकी।",
    "PROFILE_VISIBILITY_SAVE_FAILED": "प्रोफ़ाइल दृश्यता अभी अपडेट नहीं की जा सकी।",
    "PROFILE_VISIBILITY_SAVED": "आपके खाते की दृश्यता अब {visibility} है। Discoverability flags इस चरण में अपरिवर्तित रहते हैं।",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "सार्वजनिक खाता",
    "PROFILE_VISIBILITY_STORED": "संग्रहीत दृश्यता",
    "WF1_MODEL_CONTROL_TITLE": "WF1 Model Control",
    "WF1_ENABLE_TRANSLATION": "अनुवाद / Pivot सक्षम करें",
    "WF1_TRANSLATION_ACTIVE": "AI अनुवाद सक्रिय है।",
    "WF1_TRANSLATION_INACTIVE": "WF1 चलता रहता है लेकिन source text कॉपी किया जाता है और pivot को inactive चिह्नित किया जाता है।",
    "WF1_ACTIVE_RUNTIME_SLOT": "Active Runtime Slot",
    "WF1_ALLOW_SAME_LANGUAGE": "समान-भाषा जोड़ों के लिए AI की अनुमति दें",
    "WF1_SAME_LANGUAGE_ACTIVE": "समान-भाषा जोड़े सामान्य WF1 routing का पालन करते हैं।",
    "WF1_SAME_LANGUAGE_INACTIVE": "समान-भाषा जोड़े AI को bypass करते हैं और No Pivot language active संग्रहीत करते हैं।",
    "WF1_QWEN_ROUTING": "Qwen Pair Routing",
    "WF1_QWEN_ROUTING_HELPER": "नीचे चेक की गई भाषाएँ Qwen-Max का उपयोग करती हैं जब pair या तो वही चेक की गई भाषा हो, कोई चेक की गई भाषा English के साथ हो, या दो चेक की गई non-English भाषाएँ हों। अन्यथा चयनित primary model सक्रिय रहता है।",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter Test Slot",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter Test Slot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "केवल गुणवत्ता परीक्षण",
    "WF1_OPENROUTER_HELPER": "यह slot केवल अस्थायी OpenRouter quality tests के लिए editable है। यह operational Qwen pair-routing path को नहीं बदलता जब तक यह slot स्वयं active model न बन जाए।",
    "WF1_LABEL": "लेबल",
    "WF1_PRODUCT": "उत्पाद",
    "WF1_MODEL": "मॉडल",
    "WF1_PROVIDER_OPENROUTER": "प्रदाता: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter Test Slot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "OpenRouter के माध्यम से Qwen-Max",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google list price",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI list price",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter list price",
    "LANGUAGE_ENGLISH": "अंग्रेज़ी",
    "LANGUAGE_CHINESE_SIMPLIFIED": "चीनी (सरलीकृत)",
    "LANGUAGE_CHINESE_TRADITIONAL": "चीनी (पारंपरिक)",
    "LANGUAGE_JAPANESE": "जापानी",
    "LANGUAGE_KOREAN": "कोरियाई",
    "LANGUAGE_PERSIAN": "फ़ारसी",
    "LANGUAGE_TURKISH_ISTANBUL": "तुर्की (इस्तांबुल)",
    "LANGUAGE_ARABIC": "अरबी",
    "LANGUAGE_FRENCH": "फ़्रेंच",
    "LANGUAGE_GERMAN": "जर्मन",
    "LANGUAGE_SPANISH": "स्पेनिश",
    "LANGUAGE_PORTUGUESE": "पुर्तगाली",
    "LANGUAGE_ITALIAN": "इतालवी",
    "LANGUAGE_RUSSIAN": "रूसी",
    "LANGUAGE_DUTCH": "डच",
    "LANGUAGE_VIETNAMESE": "वियतनामी",
    "LANGUAGE_INDONESIAN": "इंडोनेशियाई",
    "LANGUAGE_THAI": "थाई",
    "LANGUAGE_MALAY": "मलय",
    "WF1_PRICING_CUSTOM": "Pricing: custom slot model - current OpenRouter pricing जाँचें",
    "WF1_SAVE_OPENROUTER_SLOT": "OpenRouter Slot सहेजें",
    "WF1_PRICING_LINE": "Input {input} - Output {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "Zone Visibility Control",
    "ZONE_ENABLE": "{zone} सक्षम करें",
    "ZONE_ENABLED_NOTE": "अगले app load के बाद {zone} allowed roles के लिए दिखाई दे सकता है।",
    "ZONE_DISABLED_NOTE": "अगले app load के बाद {zone} को non-S_Admin users के लिए अनुपस्थित माना जाता है।",
    "ZONE_S_ADMIN_BYPASS": "S_Admin इस role list को bypass करता है और हमेशा access रखता है।",
    "ZONE_ROLE_LOCKED": "इस zone के disabled रहने के दौरान role selections अस्थायी रूप से locked हैं और zone enabled होने पर ठीक वैसे ही लौटेंगे जैसे save किए गए थे।",
    "ZONE_LCAC_CONTROL": "LCAC Control",
    "ZONE_RCAC_CONTROL": "RCAC Control",
    "ZONE_LCAC_DESCRIPTION": "बाएँ reserved zone के अस्तित्व और उसे देखने वाले roles को नियंत्रित करता है।",
    "ZONE_RCAC_DESCRIPTION": "दाएँ reserved zone के अस्तित्व और उसे देखने वाले roles को नियंत्रित करता है।",
    "ZONE_VISIBILITY_BACKEND": "Zone visibility bootstrap अब protected backend service से पढ़ रहा है। Changes अगले app load पर लागू होते हैं।",
    "ZONE_VISIBILITY_CACHED": "Backend zone visibility service अभी अनुपलब्ध है, इसलिए cached या local defaults सक्रिय हैं।",
    "ZONE_VISIBILITY_DEFAULTS": "Zone visibility defaults सक्रिय हैं क्योंकि कोई backend या cached state लोड नहीं हो सका।",
    "ZONE_VISIBILITY_SAVED": "Zone visibility bootstrap सहेज दिया गया। Runtime application के लिए hard reload या अगला app load आवश्यक है।",
    "ZONE_VISIBILITY_SAVE_FAILED": "Protected backend service अनुरोधित zone visibility change सहेज नहीं सका।",
    "ROLE_MEMBER": "सदस्य",
    "ROLE_STAFF": "स्टाफ़",
    "ROLE_ADMIN": "एडमिन",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "नए संदेश प्राप्त करने के लिए सूचनाएँ सक्षम करें।",
    "MAIN_LOG_OUT": "लॉग आउट",
    "NOTIFICATION_NEW_MESSAGE": "नया संदेश",
    "NOTIFICATION_UNREAD_MESSAGE": "आपके पास एक अपठित संदेश है।",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "पूर्ण दृश्य",
    "MEDIA_AUDIO_ATTACHMENT": "ऑडियो संलग्नक",
    "MEDIA_FILE_FALLBACK": "फ़ाइल",
    "MEDIA_DOWNLOAD_READY": "संलग्नक डाउनलोड के लिए तैयार",
    "MEDIA_TYPE_UNSUPPORTED": "पूर्ण दृश्य के लिए प्रकार समर्थित नहीं",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "पिछली छवि",
    "MEDIA_NEXT_IMAGE_ARIA": "अगली छवि",
    "MEDIA_OPEN_ORIGINAL": "मूल खोलें",
    "MEDIA_DOWNLOAD": "डाउनलोड",
    "MEDIA_CLOSE_ARIA": "बंद करें",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name} की प्रोफ़ाइल तस्वीर",
    "MEDIA_PROFILE_ALT": "{name} प्रोफ़ाइल",
    "MEDIA_UPLOAD_FAILED": "अपलोड विफल",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend Token Error",
    "MEDIA_UPLOAD_URL_MISSING": "महत्वपूर्ण: backend response में upload URL अनुपलब्ध है।",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "chat upload के लिए auth token अनुपलब्ध",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "chat upload token request विफल",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "अमान्य chat upload response",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS Upload Failed",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "फ़ाइल नाम या contentType अनुपलब्ध",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path अनुपलब्ध",
    "BLOCK_NOTICE_TITLE": "स्थायी ब्लॉक सूचना",
    "BLOCK_NOTICE_MESSAGE": "नीति उल्लंघन के कारण आपका खाता अस्थायी रूप से निलंबित कर दिया गया है।",
    "BLOCK_NOTICE_CONTACT_PREFIX": "यदि आपको लगता है कि इस पर follow-up आवश्यक है, तो कृपया संपर्क करें",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "ईमेल द्वारा।",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "अज्ञात उपयोगकर्ता",
    "GENERAL_GUEST": "अतिथि",
    "ADVISOR_FOR_CLIENT": "{client_display_name} के लिए सलाहकार",
    "GUEST_FOR_CLIENT": "{client_display_name} के लिए अतिथि",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "टोकन और पासवर्ड आवश्यक हैं",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Request body JSON होना चाहिए",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "अमान्य या समाप्त invitation token",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Password set विफल: session या user अनुपलब्ध",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Sign-in के दौरान password set विफल",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Admin token generation विफल",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Login विफल: session या user अनुपलब्ध",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registration सफल। Verification के लिए कृपया ईमेल देखें।",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Signup failed unknown",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Invalid token processing",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Access token आवश्यक है",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Token hash preview को redirect URL से email hint चाहिए",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "इस token के लिए identity resolve नहीं की जा सकी",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "केवल User Zero WF1 LLM selector service तक पहुँच सकता है।",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "केवल User Zero zone visibility control service तक पहुँच सकता है।",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "केवल User Zero frontend version control service तक पहुँच सकता है।",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "केवल User Zero किसी अन्य user का frontend version inspect कर सकता है।",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "केवल User Zero chat delete control service तक पहुँच सकता है।",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "केवल उपयोगकर्ता शून्य ही UI भाषा रनटाइम नियंत्रण सेवा तक पहुँच सकता है।",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "केवल User Zero किसी user account को स्थायी रूप से delete कर सकता है।",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "अमान्य request payload।",
    "API_ERROR_INTERNAL_SERVER": "Internal Server Error",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Backend में function missing है (Reload Required)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "delivered/read transitions के लिए केवल DB RPC की अनुमति है।",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "दूसरा संदेश भेजने से पहले कृपया प्रतीक्षा करें।",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "संदेश सफलतापूर्वक भेजा गया।",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Contact service अनुपलब्ध है।",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "संदेश भेजना विफल।",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "नाम आवश्यक है।",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "ईमेल अमान्य है।",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "संदेश आवश्यक है।",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Selector payload आवश्यक है।",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Zone visibility payload आवश्यक है।",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Frontend version payload आवश्यक है।",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Chat delete control payload आवश्यक है।",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "UI भाषा रनटाइम नियंत्रण पेलोड आवश्यक है।",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Authenticated user id आवश्यक है।",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Authenticated viewer user id आवश्यक है।",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Authenticated actor user id आवश्यक है।",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id आवश्यक है।",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id आवश्यक है।",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids list आवश्यक है।",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email आवश्यक है।",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by आवश्यक है।",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Search runtime global frontend version द्वारा disabled है।",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "आपको यह pending invitation cancel करने की अनुमति नहीं है।",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "यह invitation अब cancel नहीं किया जा सकता क्योंकि user पहले से registered है।",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Pending invitation नहीं मिला।",
    "INVITE_REPLY_ALREADY_MEMBER": "बधाई हो, आपका मित्र ({invitee_email}) इस app में पहले से registered है और इस workspace का member है।",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "{invitee_email} के लिए invitation pending है, लेकिन retry email trigger नहीं किया जा सका। कृपया mail logs जाँचें।",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "{invitee_email} के लिए invitation record बनाया गया, लेकिन email delivery confirm नहीं हो सकी। कृपया बाद में पुनः प्रयास करें या mail logs जाँचें।",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Invitation record बनाने में विफल। कृपया बाद में पुनः प्रयास करें।",
    "INVITE_REPLY_SYSTEM_ERROR": "Invitation process के दौरान System Error: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend Configuration Error: Supabase credentials अनुपलब्ध",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend Configuration Error: अमान्य Supabase URL",
    "CHAT_ERROR_ACCESS_DENIED": "Access Denied",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Text messages के लिए content empty नहीं हो सकता",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Conversation ID निर्धारित नहीं किया जा सका",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC auth context अनुपलब्ध है",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC ने अमान्य message payload लौटाया",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Insert विफल, कोई data returned नहीं",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations एक list होनी चाहिए",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "अमान्य operation payload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Unsupported operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id आवश्यक है",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "संदेश नहीं मिला",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Delete केवल आपके अपने message पर allowed है",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "इस message के लिए Delete for everyone अब उपलब्ध नहीं है",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Delete for everyone विफल",
    "API_ERROR_SERVER_CONFIGURATION": "Server configuration error",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Webhook secret header अनुपलब्ध",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Unauthorized webhook source",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend configuration error",
    "API_ERROR_MODULE_ATTRIBUTE": "Module Attribute Error: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Waiting auth user को हटाते समय invitation deletion से पहले विफल।",
    "CHAT_ERROR_DB": "DB Error: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
