# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/hr.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Glavno",
    "APP_TITLE": "OTMEGA AI platforma",
    "APP_SUBTITLE": "AI savjetnik",
    "CHAT_PLACEHOLDER": "Upišite svoju poruku...",
    "CHAT_SEND_BUTTON": "Pošalji",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Savjetnik može pogriješiti, zato provjerite informacije.",
    "STATUS_ONLINE": "Na mreži",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Izbornik",
    "ICON_NEW_CHAT": "Novi razgovor",
    "ICON_HISTORY": "Povijest",
    "ICON_TEMPLATES": "Predlošci",
    "ICON_SETTINGS": "Postavke",
    "ICON_USER_PROFILE": "Korisnički profil",
    "ICON_QUICK_ACTIONS": "Brze radnje",
    "ICON_PINNED": "Prikvačeno",
    "ICON_GALLERY": "Galerija",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Instaliraj aplikaciju",
    "PWA_ANDROID_MSG": "Instalirajte ovu aplikaciju na svoj uređaj za bolje iskustvo i izvanmrežni pristup.",
    "PWA_IOS_MSG": "Za instalaciju ove aplikacije na iPhone/iPad:\n1. Dodirnite gumb Dijeli u nastavku\n2. Odaberite Dodaj na početni zaslon",
    "PWA_BTN_INSTALL": "Instaliraj",
    "PWA_BTN_LATER": "Možda kasnije",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Prijavite se u mrežu savjetnika",
    "AUTH_HEADER_SIGNUP": "Izradite svoj objedinjeni račun",
    "AUTH_HEADER_LOGIN_NETWORK": "Prijavite se u mrežu savjetnika",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Izradite svoj objedinjeni račun",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Prijava",
    "AUTH_BUTTON_SIGNUP": "Izradi račun",
    "AUTH_BUTTON_GOOGLE": "Nastavi s Googleom",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Zaboravljena lozinka",
    "AUTH_BUTTON_SEND_RESET_LINK": "Pošalji poveznicu za resetiranje",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Nemate račun? Registrirajte se",
    "AUTH_PROMPT_LOGIN": "Već imate račun? Prijavite se",
    "AUTH_HELPER_TEXT_SIGNUP": "Izrađujete objedinjeni račun koji možete koristiti za pristup svim savjetnicima na ovoj platformi.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Izrađujete objedinjeni račun koji možete koristiti za pristup svim savjetnicima na ovoj platformi.",
    "AUTH_HELPER_TEXT_LOGIN": "Koristite isti račun (e-pošta/lozinka ili Google) koji ste koristili za druge savjetnike u ovoj mreži.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Koristite isti račun (e-pošta/lozinka ili Google) koji ste koristili za druge savjetnike u ovoj mreži.",
    "AUTH_FORGOT_PASSWORD_LINK": "Zaboravili ste lozinku?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Resetirajte svoju lozinku",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Unesite svoju adresu e-pošte i poslat ćemo vam poveznicu za resetiranje lozinke.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-pošta",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Prijava je u tijeku...",
    "AUTH_STATUS_LOADING_SIGNUP": "Izrada računa...",
    "AUTH_STATUS_LOADING_RESET": "Slanje poveznice za resetiranje...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Prijava uspješna! Ponovno učitavanje...",
    "AUTH_STATUS_SUCCESS_RESET": "Poveznica za resetiranje uspješno je poslana. Provjerite svoju e-poštu.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Poveznica za resetiranje lozinke uspješno je poslana. Provjerite svoju e-poštu.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Nevažeća e-pošta ili lozinka.",
    "AUTH_ERROR_EMAIL_EXISTS": "Račun s ovom e-poštom već postoji u mreži savjetnika.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Račun s ovom e-poštom već postoji. Prijavite se. Trenutačno ste član:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Račun s ovom e-poštom već postoji u mreži savjetnika. Zatvorite ovaj prozor i upotrijebite odjeljak Prijava s istom e-poštom i prethodnom lozinkom.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Trenutačno ste član:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-pošta i lozinka su obavezne.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Račun je izrađen, ali postavljanje članstva nije uspjelo. Obratite se podršci.",
    "AUTH_ERROR_DEFAULT": "Došlo je do pogreške. Pokušajte ponovno.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Potrebni su podaci za kontrolu natpisa za goste.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Samo korisnik nula može ažurirati kontrole natpisa za goste.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Slanje poveznice za resetiranje nije uspjelo. Pokušajte ponovno.",
    "INVITE_REPLY_EMAIL_SENT": "Collabra pozivnica e-poštom poslana je vašem prijatelju na {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra pozivnica e-poštom ponovno je poslana vašem prijatelju na {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Prikaži lozinku",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Sakrij lozinku",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "U redu",
    "GENERAL_CANCEL": "Odustani",
    "GENERAL_CLOSE": "Zatvori",
    "GENERAL_SEND": "Pošalji",
    "GENERAL_SEARCH": "Pretraži",
    "GENERAL_RESET": "Resetiraj",
    "GENERAL_ENABLE": "Omogući",
    "GENERAL_LOADING": "Učitavanje...",
    "GENERAL_DELETE": "Izbriši",
    "GENERAL_DELETING": "Brisanje...",
    "GENERAL_SAVE_PASSWORD": "Spremi lozinku",
    "AUTH_REMEMBER_EMAIL_LABEL": "Zapamti e-poštu",
    "GENERAL_SAVING": "Spremanje...",
    "GENERAL_SENDING": "Slanje...",
    "GENERAL_REMOVING": "Uklanjanje...",
    "GENERAL_CONFIRM_REMOVAL": "Potvrdi uklanjanje",
    "GENERAL_EMPTY": "Prazno",
    "GENERAL_UNAVAILABLE": "Nedostupno",
    "GENERAL_ENABLED": "Omogućeno",
    "GENERAL_DISABLED": "Onemogućeno",
    "GENERAL_GRANTED": "Odobreno",
    "GENERAL_DENIED": "Odbijeno",
    "GENERAL_DEFAULT": "Zadano",
    "GENERAL_UNSUPPORTED": "Nije podržano",
    "GENERAL_PUBLIC": "Javno",
    "GENERAL_PRIVATE": "Privatno",
    "GENERAL_USERNAME": "Korisničko ime",
    "GENERAL_EMAIL": "E-pošta",
    "GENERAL_YOU": "Vi",
    "GENERAL_USER": "Korisnik",
    "GENERAL_UNKNOWN": "Nepoznato",
    "GENERAL_VISITOR": "Posjetitelj",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Nepoznati banner",
    "GENERAL_ADVISOR_BANNER": "Banner savjetnika",
    "GENERAL_NOT_AVAILABLE": "N/D",
    "GENERAL_NOT_SELECTED": "Nije odabrano",
    "GENERAL_NO_EMAIL_FOUND": "E-pošta nije pronađena",
    "GENERAL_USER_ZERO_ONLY": "Samo User Zero",
    "GENERAL_CONNECTION_STATE": "Stanje veze",
    "GENERAL_DISPLAY_ONLY": "Samo prikaz",
    "GENERAL_TEXTAREA": "Tekstno područje",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Izbornik (LCAC)",
    "HEADER_CHAT_CCAC": "Razgovor (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Brze radnje (RCAC)",
    "HEADER_CHANGE_STATUS": "Promijeni status",
    "HEADER_OT_COIN_BALANCE": "Stanje OT Coina",
    "HEADER_ALT_USER": "Korisnik",
    "STATUS_BUSY": "Zauzet",
    "STATUS_AWAY": "Odsutan",
    "STATUS_OFFLINE": "Izvan mreže",
    "STATUS_INVISIBLE": "Nevidljiv",
    "NETWORK_CHECKING_CONNECTION": "Provjera veze...",
    "NETWORK_ONLINE_LATENCY": "Na mreži (latencija: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Mreža: dobra (dodirnite za ping)",
    "CHAT_TARGET_ALT": "Cilj razgovora",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Pretraži...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Otvori profilnu sliku korisnika {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Unos poruke",
    "CHAT_TOGGLE_VIEW_ARIA": "Prebaci prikaz",
    "CHAT_ADD_USER_ARIA": "Dodaj korisnika",
    "CHAT_ATTACH_ARIA": "Priloži",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Pošalji",
    "CHAT_SEARCH_ARIA": "Pretraži",
    "CHAT_OPEN_SEARCH_ARIA": "Otvori pretraživanje",
    "CHAT_CLOSE_SEARCH_ARIA": "Zatvori pretraživanje",
    "CHAT_ATTACHMENT_ALT": "Privitak",
    "CHAT_PREVIEW_ALT": "Pregled",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Ukloni privitak",
    "CHAT_REPLYING_TO": "Odgovor na",
    "CHAT_CANCEL_REPLY_ARIA": "Odustani od odgovora",
    "CHAT_UPLOADING": "Prijenos...",
    "CHAT_LOADING_CHATS": "Učitavanje razgovora...",
    "CHAT_SEND_FAILED": "Slanje nije uspjelo",
    "CHAT_SEND_FAILED_RETRY": "Slanje nije uspjelo. Pokušajte ponovno.",
    "CHAT_RETRY": "Pokušaj ponovno",
    "CHAT_EDITED": "uređeno",
    "CHAT_TYPING": "Tipkanje",
    "CHAT_LOADING": "Učitavanje",
    "CHAT_PENDING_INVITATION": "Pozivnica na čekanju",
    "CHAT_PENDING_INVITATION_MIN": "{count} min Pozivnica na čekanju",
    "CHAT_PENDING_INVITATION_HR": "{count} h Pozivnica na čekanju",
    "CHAT_PENDING_INVITATION_DAY": "{count} dan Pozivnica na čekanju",
    "CHAT_WAITING_FOR_YOU": "{label} - Čeka na vas",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Prihvaćanje na čekanju",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Pristup mikrofonu odbijen.",
    "CHAT_UPLOAD_FAILED": "Prijenos nije uspio: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Prijenos zahtijeva internetsku vezu. Pokušajte ponovno kada budete na mreži.",
    "OFFLINE_SHOWING_SAVED_DATA": "",
    "OFFLINE_DATA_MAY_BE_OUTDATED": "",
    "OFFLINE_ACTION_REQUIRES_CONNECTION": "",
    "OFFLINE_MESSAGE_WAITING_CONNECTION": "",
    "OFFLINE_PENDING_MESSAGES_TOOLTIP": "",
    "APP_BACK_EXIT_HINT": "",
    "CHAT_ERROR_AUTH": "Pogreška autentifikacije",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nedostaje naziv datoteke ili content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Nedostaje conversation_id ili target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Nedostaje conversation_id za prijenos koji nije avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Nevažeći file_path avatara",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Klijent usluge Supabase nije dostupan",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Potvrda čitanja avatara vrijedi samo u kontekstu razgovora sa savjetnikom",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Poruka toka avatara nije pronađena ili nije podobna za potvrdu čitanja",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Dovršavanje poruke avatara kao pročitane nije uspjelo",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 privitak",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} privitaka",
    "CHAT_VOICE_NOTE": "Glasovna bilješka",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Razgovor nije dostupan. Ovaj vas je korisnik blokirao.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Razgovor nije dostupan. Blokirali ste ovog korisnika.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Pristup računu blokiran je pravilima.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Razgovor nije dostupan. Ovaj je račun trajno blokirao User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Razgovor nije dostupan. Aktivna je međusobna blokada.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Razgovor nije dostupan zbog pravila blokiranja.",
    "MESSAGE_PREVIEW_PHOTO": "Fotografija",
    "MESSAGE_PREVIEW_VOICE": "Glasovna poruka",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Datoteka",
    "MESSAGE_PREVIEW_MESSAGE": "Poruka",
    "MESSAGE_PREVIEW_SYSTEM": "Sistemska poruka",
    "MESSAGE_PREVIEW_NEW": "Nova poruka",
    "MESSAGE_UNKNOWN_FILE": "Nepoznata datoteka",
    "MESSAGE_AUDIO_ATTACHMENT": "Audio privitak",
    "MESSAGE_FILE_ATTACHMENT": "Privitak",
    "BANNER_INVITED_BY": "pozvao/la {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Rezultati pretraživanja",
    "SEARCH_QUERY_LABEL": "Upit:",
    "SEARCH_LOADING_VISIBILITY": "Učitavanje vidljivosti pretraživanja...",
    "SEARCH_NO_RESULTS": "Nije pronađen nijedan rezultat u trenutačnom opsegu pretraživanja.",
    "SHARE_WITH_COLLABRA": "Podijeli s Collabrom",
    "SHARE_SEND_TO": "Pošalji na",
    "SHARE_SELECT_ONE_BANNER": "Odaberite jedan banner",
    "SHARE_BANNER_LIST_ARIA": "Popis bannera",
    "SHARE_NO_MATCHING_BANNER": "Nema odgovarajućeg bannera",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Dodaj komentar...",
    "SHARE_RECENT_CHATS": "Nedavni razgovori",
    "SHARE_LEFT_LIST": "Lijevi popis",
    "SHARE_RIGHT_LIST": "Desni popis",
    "SHARE_UNTITLED_BANNER": "Banner bez naslova",
    "SHARE_SHARED_CONTENT": "Podijeljeni sadržaj",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Podijeljeni sadržaj nije se mogao otvoriti.",
    "SHARE_OPEN_BANNER_FAILED": "Nije moguće otvoriti odabrani banner.",
    "SHARE_ONE_PHOTO_SELECTED": "Odabrana je 1 fotografija",
    "SHARE_MANY_PHOTOS_SELECTED": "Odabrano fotografija: {count}",
    "SHARE_ONE_FILE_SELECTED": "Odabrana je 1 datoteka",
    "SHARE_MANY_FILES_SELECTED": "Odabrano datoteka: {count}",
    "FORWARD_MESSAGE_TITLE": "Proslijedi poruku",
    "FORWARD_SELECT_RECIPIENTS": "Odaberite primatelje",
    "FORWARD_NO_OTHER_BANNER": "Nema dostupnog drugog bannera.",
    "FORWARD_SEND_TO_COUNT": "Pošalji na {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Odaberite barem jedan banner.",
    "FORWARD_FAILED_DEFAULT": "Prosljeđivanje nije uspjelo. Pokušajte ponovno.",
    "FORWARD_PARTIAL_SENT": "{count} poslano. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Izvorna poruka za prosljeđivanje nije pronađena",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Ova poruka još nema sadržaj koji se može proslijediti",
    "FORWARD_DESTINATION_MISSING": "Nedostaje odredište prosljeđivanja",
    "FORWARD_MESSAGE_PREVIEW": "Proslijeđena poruka",
    "MENU_PASTE": "Zalijepi",
    "MENU_COPY": "Kopiraj",
    "MENU_REPLY": "Odgovori",
    "MENU_FORWARD": "Proslijedi",
    "MENU_REMOVE_INVITATION": "Ukloni pozivnicu",
    "MENU_REMOVE_FROM_LIST": "Ukloni s popisa",
    "MENU_GOODBYE_GUEST": "Doviđenja, gostu",
    "MENU_ADD_TO_LIST": "Dodaj na popis",
    "MENU_REJECT_INVITATION": "Odbij pozivnicu",
    "MENU_FRONTEND_VERSION": "Frontend verzija",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Informacije o banneru: {title}",
    "MENU_MESSAGE_BUBBLE": "Oblačić poruke",
    "MENU_CHAT_CANVAS_HEADER": "Platno razgovora - {zone}",
    "MENU_CANVAS_INFO": "Informacije o platnu",
    "MENU_CHAT_CANVAS_SUBLABEL": "Područje razgovora / trenutačna površina razgovora",
    "MENU_INPUT_AREA_HEADER": "Područje unosa - {zone}",
    "MENU_INPUT_AREA_INFO": "Informacije o području unosa: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Donja površina za tipkanje i alate radnji",
    "MENU_HEADER": "Zaglavlje - {zone}",
    "MENU_HEADER_INFO": "Informacije o zaglavlju: {title}",
    "MENU_HEADER_DESCRIPTION": "Gornja navigacija i kontrole stranice",
    "MENU_ZONE_HEADER": "Zona - {zone}",
    "MENU_ZONE_SPACE_INFO": "Informacije o prostoru zone",
    "MENU_EMPTY_LIST_SURFACE": "Prazna/popisna površina",
    "MENU_BLOCK": "Blokiraj",
    "MENU_UNBLOCK": "Odblokiraj",
    "MENU_HIDE_IN_SEARCH": "Sakrij u pretraživanju",
    "MENU_UNHIDE_IN_SEARCH": "Prikaži u pretraživanju",
    "MENU_VISIBLE_IN_SEARCH": "Vidljivo u pretraživanju",
    "MENU_HIDDEN_IN_SEARCH": "Skriveno u pretraživanju",
    "MENU_VISIBLE_IN_USER_LIST": "Vidljivo na popisu korisnika",
    "MENU_HIDDEN_IN_USER_LIST": "Skriveno na popisu korisnika",
    "MENU_NOT_BLOCKED": "Nije blokirano",
    "MENU_BLOCKED": "Blokirano",
    "MENU_FRONTEND_VERSION_LOADING": "Učitavanje...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Učitavanje vrijednosti po banneru iz backend-a. Nijedna opcija nije označena kao aktivna dok ne stigne odgovor baze podataka.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend vrijednost nije se mogla učitati. Ne prikazuje se nijedna pouzdana aktivna opcija.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Izričita vrijednost po banneru u bazi podataka je {overrideVersion}. Globalna zadana vrijednost je {globalDefaultVersion}. Ciljni korisnik mora potpuno osvježiti ili ponovno otvoriti aplikaciju kako bi je početni bootstrap primijenio.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Nije pohranjena izričita vrijednost po banneru. FeV2.0.0 je zadano aktivan. Globalna zadana vrijednost je {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Izričita vrijednost po banneru postaje aktivna nakon potpunog ponovnog učitavanja ciljne aplikacije",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Nije pohranjena izričita vrijednost po banneru; ovo je zadano pojedinačno stanje FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Ova je opcija također jednaka trenutačnoj globalnoj zadanoj vrijednosti",
    "MENU_DELETE_PERMANENT_CONFIRM": "Trajno izbrisati {target} iz baze podataka? Time se uklanja račun, povijest razgovora, ovisnosti i nameće potpuno novi put pozivanja za budući ponovni ulazak.",
    "MENU_DELETE_PERMANENTLY": "Trajno izbriši",
    "MENU_REFRESH_PAGE": "Osvježi stranicu",
    "MENU_LOG_OFF": "Odjavi se",
    "MENU_HARD_RELOAD": "Tvrdo ponovno učitavanje",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-pošta (admin korisnik)",
    "AUTH_PASSWORD_PLACEHOLDER": "Lozinka",
    "AUTH_CONNECTING": "Povezivanje...",
    "AUTH_SIGNING_OUT": "Odjava...",
    "AUTH_BACK_TO_LOGIN": "Natrag na prijavu",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Nevažeći odgovor poslužitelja: token nije pronađen.",
    "AUTH_LOGIN_FAILED": "Prijava nije uspjela",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Lozinke se ne podudaraju.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Lozinke se ne podudaraju!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Lozinke se moraju točno podudarati.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nova lozinka",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Potvrdite lozinku",
    "AUTH_CHANGE_PASSWORD": "Promijeni lozinku",
    "AUTH_SAVING_PASSWORD": "Spremanje...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Lozinka je uspješno ažurirana.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Trenutačno nije moguće promijeniti lozinku.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Morate biti prijavljeni da biste promijenili lozinku.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Prebaci vidljivost nove lozinke",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Prebaci vidljivost potvrde lozinke",
    "REGISTER_TITLE": "Dovršite registraciju",
    "REGISTER_SUBTITLE": "Ručno postavite svoju lozinku.",
    "REGISTER_CREATING_ACCOUNT": "Izrada računa...",
    "REGISTER_FINISH_SETUP": "Dovrši postavljanje",
    "REGISTER_FAILED_SET_PASSWORD": "Postavljanje lozinke nije uspjelo",
    "INVITE_EMAIL_INSTRUCTION": "Unesite e-poštu pozvane osobe (format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Pozovi",
    "INVITE_EMAIL_REQUIRED": "Unesite e-poštu pozvane osobe.",
    "INVITE_EMAIL_INVALID": "Nevažeći format e-pošte. Upotrijebite: user@example.com",
    "PENDING_INVITATION_TITLE": "Pozivnica na čekanju",
    "PENDING_INVITATION_REMOVE_QUESTION": "Ukloniti ovu pozivnicu na čekanju iz baze podataka?",
    "PENDING_INVITATION_KEEP": "Zadrži pozivnicu",
    "PENDING_INVITATION_REMOVAL_FAILED": "Uklanjanje nije uspjelo.",
    "REMOVE_FROM_LIST_TITLE": "Ukloni s popisa",
    "REMOVE_FROM_LIST_WARNING": "Ukloniti ovog korisnika s oba popisa sada? Pristup razgovoru bit će odmah prekinut. Jedini put povratka je nova pozivnica.",
    "REMOVE_FROM_LIST_KEEP": "Zadrži korisnika na popisu",
    "REMOVE_FROM_LIST_FAILED": "Uklanjanje s popisa nije uspjelo.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Postavke i status uživo",
    "PERMISSION_DIALOG_ARIA": "Postavke i status uživo",
    "PERMISSION_TRIGGER_ARIA": "Okidač skočnog prozora postavki",
    "PERMISSION_CLOSE_ARIA": "Zatvori skočni prozor dopuštenja",
    "PERMISSION_LIVE_STATUS": "Status uživo",
    "PERMISSION_SYSTEM_PERMISSION": "Sistemsko dopuštenje",
    "PERMISSION_APP_PUSH": "Push aplikacije",
    "PERMISSION_LOCATION_PERMISSION": "Dopuštenje lokacije",
    "PERMISSION_APP_LOCATION": "Lokacija aplikacije",
    "PERMISSION_CONTROLS": "Kontrole dopuštenja",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push obavijesti",
    "PERMISSION_LOCATION_ACCESS": "Pristup lokaciji",
    "PERMISSION_IN_APP_SETTINGS": "Postavke u aplikaciji",
    "PERMISSION_ALERT_SOUND": "Zvuk upozorenja",
    "PERMISSION_APP_BADGE": "Značka aplikacije",
    "PERMISSION_PASSWORD_SETTINGS": "Postavke lozinke",
    "PERMISSION_NAVIGATION_STATUS": "Status navigacije",
    "PERMISSION_SELECTED_ZONE": "Odabrana zona",
    "PERMISSION_STAGED_CHAT_BANNER": "Pripremljeni banner razgovora",
    "PERMISSION_CANVAS_CONTENT": "Sadržaj platna",
    "PERMISSION_YOUR_DEVICES": "Vaši uređaji ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Osvježi popis uređaja",
    "PERMISSION_REFRESH_LIST": "Osvježi popis",
    "PERMISSION_NO_REGISTERED_DEVICES": "Nema pronađenih registriranih uređaja.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Promijeni veličinu skočnog prozora postavki",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Prebaci push obavijesti",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Prebaci pristup lokaciji",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Prebaci zvuk upozorenja",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Prebaci značku aplikacije",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Prebaci vidljivost profila",
    "PERMISSION_OFF_IN_V1": "Isključeno u v1",
    "PERMISSION_CHAT": "Razgovor",
    "PERMISSION_BANNER_LIST": "Popis bannera",
    "PERMISSION_PUSH_DISABLED_V1": "Push obavijesti onemogućene su za v1 izdanje Google Playa.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Push obavijesti su uključene za ovaj uređaj.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Sistemske obavijesti su blokirane. Dodirnite za otvaranje pomoći za postavke.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Uključite za poboljšanje pouzdanosti isporuke.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Da biste onemogućili sistemske obavijesti, otvorite postavke obavijesti preglednika/web-mjesta i postavite ovo web-mjesto na Blokiraj.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Da biste promijenili dopuštenje sistemskih obavijesti, otvorite postavke obavijesti preglednika/web-mjesta i postavite ovo web-mjesto na Dopusti.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Pristup lokaciji uključen je za LCAC sortiranje po udaljenosti i pozicioniranje na karti.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API za lokaciju nije podržan u ovom okruženju.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Pristup lokaciji je blokiran. Dodirnite za otvaranje pomoći za postavke.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Uključite za omogućavanje preciznog LCAC sortiranja po udaljenosti i pozicioniranja na karti u aplikaciji.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Pristup lokaciji nije podržan u ovom okruženju.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Da biste onemogućili pristup lokaciji, otvorite postavke lokacije preglednika/web-mjesta i postavite ovo web-mjesto na Blokiraj.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Da biste omogućili pristup lokaciji za sortiranje po udaljenosti i pozicioniranje na karti u aplikaciji, otvorite postavke lokacije preglednika/web-mjesta i postavite ovo web-mjesto na Dopusti.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Trenutačno nije moguće učitati registrirane uređaje.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Učitavanje UI Bridgea...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Učitavanje lokalnog Bridgea...",
    "RUNTIME_LOADING_BACKEND": "Učitavanje backend-a...",
    "RUNTIME_LOADING": "Učitavanje...",
    "RUNTIME_LOADING_FROM_DATABASE": "Učitavanje iz baze podataka...",
    "RUNTIME_BACKEND_CONNECTED": "Backend povezan",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Aktivan predmemorirani fallback",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Aktivan zadani fallback",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Aktivne zadane fallback vrijednosti",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Spremanje preko backend-a...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Spremljeno u backend usluzi",
    "RUNTIME_SAVE_FAILED": "Spremanje nije uspjelo",
    "RUNTIME_LOAD_FAILED": "Učitavanje nije uspjelo",
    "RUNTIME_CONNECTED": "Povezano",
    "RUNTIME_LOGIN_REQUIRED": "Potrebna je prijava",
    "RUNTIME_SAVED": "Spremljeno",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI spreman - runtime na čekanju",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Zaštićena backend usluga selektora odbila je ili nije mogla spremiti zatraženu opciju modela.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Zaštićena backend usluga selektora odbila je ili nije mogla spremiti zatraženu promjenu WF1 usmjeravanja.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selektor sada čita aktivnu konfiguraciju, Qwen usmjeravanje i dopuštene opcije iz zaštićene backend usluge.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend usluga selektora trenutačno nije dostupna, pa se koristi zadnje predmemorirano stanje selektora.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Zadane vrijednosti selektora aktivne su jer se nije moglo učitati nijedno backend ili predmemorirano stanje selektora.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Zaštićena backend usluga selektora ažurirala je aktivnu konfiguraciju WF1 usmjeravanja i osvježila cache runtime domene.",
    "FRONTEND_VERSION_TITLE": "Frontend verzija",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Ovaj selektor kontrolira aktivnu frontend verziju za sve korisnike. FeV2.0.0 je aktivan.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Ovaj selektor čita aktivnu frontend verziju iz config_domain_registry. Runtime se razrješava u FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend konfiguracija frontend verzije nije se mogla učitati, pa kodirana zadana vrijednost FeV2.0.0 ostaje aktivna dok početni bootstrap ponovno ne pročita zaštićenu uslugu.",
    "FRONTEND_VERSION_HELPER_SAVED": "Aktivna frontend verzija spremljena je u config_domain_registry. Potpuno osvježavanje ili sljedeće učitavanje aplikacije primjenjuje runtime vrijednost.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend usluga kontrole frontend verzije nije mogla spremiti zatraženu globalnu verziju.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktivna frontend verzija.",
    "CHAT_DELETE_WINDOW_TITLE": "Prozor brisanja razgovora",
    "CHAT_DELETE_HELPER": "Ova vrijednost kontrolira vremenski prozor dostupnosti opcije Izbriši za sve u sekundama. Backend zaštita mijenja se odmah nakon spremanja. Vidljivost oblačića mijenja se nakon potpunog osvježavanja ili sljedećeg učitavanja aplikacije.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend usluga kontrole brisanja razgovora nije se mogla učitati, pa kodirana zadana vrijednost ostaje aktivna dok početni bootstrap ponovno ne pročita zaštićenu uslugu.",
    "CHAT_DELETE_HELPER_SAVED": "Vremenski prozor dostupnosti opcije Izbriši za sve spremljen je u config_domain_registry. Backend zaštita mijenja se odmah. Vidljivost oblačića mijenja se nakon potpunog osvježavanja ili sljedećeg učitavanja aplikacije.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend usluga kontrole brisanja razgovora nije mogla spremiti zatraženu vrijednost prozora.",
    "CHAT_DELETE_WINDOW_LABEL": "Prozor za Izbriši za sve",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} s",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Spremite vrijednost u cijelim sekundama. Trenutačna produkcijska vrijednost je 86400 sekundi = 1 dan.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Sekunde prozora",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Unesite cijeli broj veći ili jednak 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Spremi prozor brisanja",
    "GUEST_BANNER_CONTROL_TITLE": "Natpis za goste",
    "GUEST_BANNER_CONTROL_LABEL": "QR chat za goste",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Prikaži natpis za goste svim korisnicima",
    "GUEST_BANNER_CONTROL_HELPER": "Upravlja fiksnim natpisom za goste i vijekom trajanja QR tokena na čekanju.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Lokalna zamjena aktivna je za kontrole natpisa za goste.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Kontrole natpisa za goste spremljene.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Kontrole natpisa za goste nije bilo moguće spremiti.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} sesija gostiju opozvano.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "TTL QR-a na čekanju (minute)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "Trenutačni TTL QR-a na čekanju: {count} minuta.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Unesite pozitivan cijeli broj minuta.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Spremi natpis za goste",
    "GUEST_QR_LOADING": "Priprema se QR za goste...",
    "GUEST_QR_READY": "Skenirajte za otvaranje privremenog chata za goste.",
    "GUEST_QR_ALT": "QR kôd za chat za goste",
    "GUEST_QR_LOAD_FAILED": "QR za goste nije se mogao pripremiti.",
    "GUEST_SESSION_ACTIVE": "Gost je povezan.",
    "GUEST_PUBLIC_TITLE": "Razgovor s gostom",
    "GUEST_PUBLIC_CONNECTING": "Povezivanje...",
    "GUEST_PUBLIC_CONNECTED": "Povezano",
    "GUEST_PUBLIC_UNAVAILABLE": "Ova poveznica za gosta nije dostupna.",
    "GUEST_PUBLIC_SEND_FAILED": "Poruka se ne može poslati.",
    "UI_TEXTS_RUNTIME_TITLE": "Izvođenje jezika korisničkog sučelja",
    "UI_TEXTS_RUNTIME_BACKEND": "Izvođenje jezika korisničkog sučelja čita iz zaštićene pozadinske usluge. Promjene se primjenjuju pri sljedećem potpunom učitavanju aplikacije.",
    "UI_TEXTS_RUNTIME_CACHED": "Pozadinska usluga izvođenja jezika korisničkog sučelja trenutačno nije dostupna, stoga su aktivne predmemorirane ili lokalne zadane postavke.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "Zadane postavke izvođenja jezika korisničkog sučelja aktivne su jer se nije moglo učitati pozadinsko ili predmemorirano stanje.",
    "UI_TEXTS_RUNTIME_SAVED": "Kontrola izvođenja jezika korisničkog sučelja je spremljena. Potrebno je potpuno osvježavanje ili sljedeće učitavanje aplikacije kako bi korisnici primili novi jezični pristupnik.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Zaštićena pozadinska usluga nije mogla spremiti zatraženu promjenu izvođenja jezika korisničkog sučelja.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Aplikacija jezika uređaja",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Omogući jezike korisničkog sučelja za izvođenje",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Korisnici mogu primati tekstualne podatke korisničkog sučelja za svoj pohranjeni jezik ili jezik uređaja.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Svi korisnici moraju koristiti tekst korisničkog sučelja na engleskom jeziku, a jezik uređaja se zanemaruje.",
    "PROFILE_VISIBILITY_TITLE": "Vidljivost profila",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Morate biti prijavljeni za upravljanje vidljivošću računa.",
    "PROFILE_VISIBILITY_HELPER": "Ovaj prekidač ažurira samo stanje vidljivosti vašeg računa. Mogućnost otkrivanja i ponašanje popisa bannera ostaju nepromijenjeni u ovoj fazi.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Vidljivost profila trenutačno se nije mogla učitati.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Vidljivost profila trenutačno se nije mogla ažurirati.",
    "PROFILE_VISIBILITY_SAVED": "Vidljivost vašeg računa sada je {visibility}. Oznake mogućnosti otkrivanja ostaju nepromijenjene u ovoj fazi.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Javni račun",
    "PROFILE_VISIBILITY_STORED": "Pohranjena vidljivost",
    "WF1_MODEL_CONTROL_TITLE": "Kontrola WF1 modela",
    "WF1_ENABLE_TRANSLATION": "Omogući prijevod / pivot",
    "WF1_TRANSLATION_ACTIVE": "AI prijevod je aktivan.",
    "WF1_TRANSLATION_INACTIVE": "WF1 nastavlja raditi, ali se izvorni tekst kopira, a pivot označava kao neaktivan.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktivni runtime slot",
    "WF1_ALLOW_SAME_LANGUAGE": "Dopusti AI za parove istog jezika",
    "WF1_SAME_LANGUAGE_ACTIVE": "Parovi istog jezika slijede uobičajeno WF1 usmjeravanje.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Parovi istog jezika zaobilaze AI i spremaju stanje Bez aktivnog pivot jezika.",
    "WF1_QWEN_ROUTING": "Qwen usmjeravanje parova",
    "WF1_QWEN_ROUTING_HELPER": "Jezici označeni u nastavku koriste Qwen-Max kada je par ili isti označeni jezik, označeni jezik s engleskim ili dva označena neengleska jezika. U suprotnom odabrani primarni model ostaje aktivan.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter testni slot",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter testni slot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Samo test kvalitete",
    "WF1_OPENROUTER_HELPER": "Ovaj slot moguće je uređivati samo za privremene OpenRouter testove kvalitete. Ne mijenja operativni put Qwen usmjeravanja parova osim ako sam ovaj slot postane aktivni model.",
    "WF1_LABEL": "Oznaka",
    "WF1_PRODUCT": "Proizvod",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Pružatelj: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Tajna: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter testni slot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max putem OpenRoutera",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google kataloška cijena",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI kataloška cijena",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter kataloška cijena",
    "LANGUAGE_ENGLISH": "Engleski",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Kineski (pojednostavljeni)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Kineski (tradicionalni)",
    "LANGUAGE_JAPANESE": "Japanski",
    "LANGUAGE_KOREAN": "Korejski",
    "LANGUAGE_PERSIAN": "Perzijski",
    "LANGUAGE_TURKISH_ISTANBUL": "Turski (Istanbul)",
    "LANGUAGE_ARABIC": "Arapski",
    "LANGUAGE_FRENCH": "Francuski",
    "LANGUAGE_GERMAN": "Njemački",
    "LANGUAGE_SPANISH": "Španjolski",
    "LANGUAGE_PORTUGUESE": "Portugalski",
    "LANGUAGE_ITALIAN": "Talijanski",
    "LANGUAGE_RUSSIAN": "Ruski",
    "LANGUAGE_DUTCH": "Nizozemski",
    "LANGUAGE_VIETNAMESE": "Vijetnamski",
    "LANGUAGE_INDONESIAN": "Indonezijski",
    "LANGUAGE_THAI": "Tajlandski",
    "LANGUAGE_MALAY": "Malajski",
    "WF1_PRICING_CUSTOM": "Cijena: prilagođeni model slota - provjerite trenutačne OpenRouter cijene",
    "WF1_SAVE_OPENROUTER_SLOT": "Spremi OpenRouter slot",
    "WF1_PRICING_LINE": "Ulaz {input} - Izlaz {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Tajna: {secret}",
    "ZONE_VISIBILITY_TITLE": "Kontrola vidljivosti zona",
    "ZONE_ENABLE": "Omogući {zone}",
    "ZONE_ENABLED_NOTE": "{zone} se može prikazati dopuštenim ulogama nakon sljedećeg učitavanja aplikacije.",
    "ZONE_DISABLED_NOTE": "{zone} se tretira kao odsutna za korisnike koji nisu S_Admin nakon sljedećeg učitavanja aplikacije.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin zaobilazi ovaj popis uloga i uvijek zadržava pristup.",
    "ZONE_ROLE_LOCKED": "Odabiri uloga privremeno su zaključani dok je ova zona onemogućena i vratit će se točno onako kako su spremljeni kada se zona ponovno omogući.",
    "ZONE_LCAC_CONTROL": "LCAC kontrola",
    "ZONE_RCAC_CONTROL": "RCAC kontrola",
    "ZONE_LCAC_DESCRIPTION": "Kontrolira postojanje lijeve rezervirane zone i uloge koje je mogu vidjeti.",
    "ZONE_RCAC_DESCRIPTION": "Kontrolira postojanje desne rezervirane zone i uloge koje je mogu vidjeti.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap vidljivosti zona sada čita iz zaštićene backend usluge. Promjene se primjenjuju pri sljedećem učitavanju aplikacije.",
    "ZONE_VISIBILITY_CACHED": "Backend usluga vidljivosti zona trenutačno nije dostupna, pa su aktivne predmemorirane ili lokalne zadane vrijednosti.",
    "ZONE_VISIBILITY_DEFAULTS": "Zadane vrijednosti vidljivosti zona aktivne su jer se nije moglo učitati nijedno backend ili predmemorirano stanje.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap vidljivosti zona je spremljen. Za primjenu u runtimeu potrebno je tvrdo ponovno učitavanje ili sljedeće učitavanje aplikacije.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Zaštićena backend usluga nije mogla spremiti zatraženu promjenu vidljivosti zone.",
    "ROLE_MEMBER": "Član",
    "ROLE_STAFF": "Osoblje",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Omogućite obavijesti za primanje novih poruka.",
    "MAIN_LOG_OUT": "Odjava",
    "NOTIFICATION_NEW_MESSAGE": "Nova poruka",
    "NOTIFICATION_UNREAD_MESSAGE": "Imate nepročitanu poruku.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Puni prikaz",
    "MEDIA_AUDIO_ATTACHMENT": "Audio privitak",
    "MEDIA_FILE_FALLBACK": "Datoteka",
    "MEDIA_DOWNLOAD_READY": "Privitak spreman za preuzimanje",
    "MEDIA_TYPE_UNSUPPORTED": "Vrsta nije podržana za puni prikaz",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Prethodna slika",
    "MEDIA_NEXT_IMAGE_ARIA": "Sljedeća slika",
    "MEDIA_OPEN_ORIGINAL": "Otvori izvornik",
    "MEDIA_DOWNLOAD": "Preuzmi",
    "MEDIA_CLOSE_ARIA": "Zatvori",
    "MEDIA_PROFILE_PICTURE_ARIA": "Profilna slika korisnika {name}",
    "MEDIA_PROFILE_ALT": "Profil korisnika {name}",
    "MEDIA_UPLOAD_FAILED": "Prijenos nije uspio",
    "MEDIA_BACKEND_TOKEN_ERROR": "Pogreška backend tokena",
    "MEDIA_UPLOAD_URL_MISSING": "Kritično: URL za prijenos nedostaje u backend odgovoru.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Nedostaje auth token za prijenos razgovora",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Zahtjev za token prijenosa razgovora nije uspio",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Nevažeći odgovor prijenosa razgovora",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS prijenos nije uspio",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nedostaje naziv datoteke ili contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Nedostaje file_path",
    "BLOCK_NOTICE_TITLE": "Obavijest o trajnoj blokadi",
    "BLOCK_NOTICE_MESSAGE": "Vaš je račun privremeno suspendiran zbog kršenja pravila.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Ako smatrate da je potrebno daljnje postupanje, obratite se",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "e-poštom.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Nepoznati korisnik",
    "GENERAL_GUEST": "Gost",
    "ADVISOR_FOR_CLIENT": "Savjetnik za {client_display_name}",
    "GUEST_FOR_CLIENT": "Gost za {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token i lozinka su obavezni",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Tijelo zahtjeva mora biti JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Nevažeći ili istekao token pozivnice",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Postavljanje lozinke nije uspjelo: nedostaje sesija ili korisnik",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Postavljanje lozinke nije uspjelo tijekom prijave",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Generiranje admin tokena nije uspjelo",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Prijava nije uspjela: nedostaje sesija ili korisnik",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registracija uspješna. Provjerite e-poštu radi potvrde.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Registracija nije uspjela iz nepoznatog razloga",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Nevažeća obrada tokena",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Potreban je pristupni token",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Pregled hash tokena zahtijeva naznaku e-pošte iz URL-a preusmjeravanja",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Nije moguće razriješiti identitet za ovaj token",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Samo User Zero može pristupiti usluzi WF1 LLM selektora.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Samo User Zero može pristupiti usluzi kontrole vidljivosti zona.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Samo User Zero može pristupiti usluzi kontrole frontend verzije.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Samo User Zero može pregledati frontend verziju drugog korisnika.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Samo User Zero može pristupiti usluzi kontrole brisanja razgovora.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Samo Korisnik Nula može pristupiti usluzi kontrole izvođenja jezika korisničkog sučelja.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Samo User Zero može trajno izbrisati korisnički račun.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Nevažeći payload zahtjeva.",
    "API_ERROR_INTERNAL_SERVER": "Interna pogreška poslužitelja",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funkcija nedostaje u backend-u (potrebno ponovno učitavanje)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Samo DB RPC dopušten je za delivered/read prijelaze.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Pričekajte prije slanja nove poruke.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Poruka je uspješno poslana.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Usluga kontakta nije dostupna.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Slanje poruke nije uspjelo.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Ime je obavezno.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-pošta nije važeća.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Poruka je obavezna.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload selektora je obavezan.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload vidljivosti zona je obavezan.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload frontend verzije je obavezan.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload kontrole brisanja razgovora je obavezan.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Potrebni su podaci za kontrolu izvođenja jezika korisničkog sučelja.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID autentificiranog korisnika je obavezan.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID autentificiranog korisnika gledatelja je obavezan.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID autentificiranog korisnika aktera je obavezan.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id je obavezan.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id je obavezan.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Popis owner_user_ids je obavezan.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email je obavezan.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by je obavezan.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime pretraživanja onemogućen je globalnom frontend verzijom.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Nije vam dopušteno otkazati ovu pozivnicu na čekanju.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Ovu pozivnicu više nije moguće otkazati jer je korisnik već registriran.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Pozivnica na čekanju nije pronađena.",
    "INVITE_REPLY_ALREADY_MEMBER": "Čestitamo, vaš prijatelj ({invitee_email}) već je registriran u ovoj aplikaciji i član je ovog radnog prostora.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Pozivnica je na čekanju za {invitee_email}, ali e-pošta za ponovni pokušaj nije se mogla pokrenuti. Provjerite mail logove.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Zapis pozivnice izrađen je za {invitee_email}, ali isporuka e-pošte nije se mogla potvrditi. Pokušajte ponovno kasnije ili provjerite mail logove.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Izrada zapisa pozivnice nije uspjela. Pokušajte ponovno kasnije.",
    "INVITE_REPLY_SYSTEM_ERROR": "Sistemska pogreška tijekom procesa pozivanja: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Pogreška backend konfiguracije: nedostaju Supabase vjerodajnice",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Pogreška backend konfiguracije: nevažeći Supabase URL",
    "CHAT_ERROR_ACCESS_DENIED": "Pristup odbijen",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Sadržaj ne može biti prazan za tekstualne poruke",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Nije moguće odrediti ID razgovora",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC auth kontekst nedostaje",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC je vratio nevažeći payload poruke",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Umetanje nije uspjelo, nisu vraćeni podaci",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations mora biti popis",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Nevažeći payload operacije",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Nepodržan operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id je obavezan",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Poruka nije pronađena",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Brisanje je dopušteno samo za vlastitu poruku",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Izbriši za sve više nije dostupno za ovu poruku",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Izbriši za sve nije uspjelo",
    "API_ERROR_SERVER_CONFIGURATION": "Pogreška konfiguracije poslužitelja",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Nedostaje tajno zaglavlje webhooka",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Neovlašten izvor webhooka",
    "API_ERROR_BACKEND_CONFIGURATION": "Pogreška backend konfiguracije",
    "API_ERROR_MODULE_ATTRIBUTE": "Pogreška atributa modula: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Neuspjeh prije brisanja pozivnice tijekom uklanjanja auth korisnika na čekanju.",
    "CHAT_ERROR_DB": "DB pogreška: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "PERMISSION_MIC_PERMISSION": "",
    "PERMISSION_MIC_ACCESS": "",
    "PERMISSION_TOGGLE_MIC_ARIA": "",
    "PERMISSION_MIC_ON_TOOLTIP": "",
    "PERMISSION_MIC_ENABLE_TOOLTIP": "",
    "PERMISSION_MIC_BLOCKED_TOOLTIP": "",
    "PERMISSION_MIC_DISABLE_HELP": "",
    "PERMISSION_MIC_BLOCKED_HELP": "",
    "LIVE_CONV_MIC_PROMPT_TITLE": "",
    "LIVE_CONV_MIC_PROMPT_BODY": "",
    "LIVE_CONV_MIC_PROMPT_ALLOW": "",
    "LIVE_CONV_MIC_PROMPT_CANCEL": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
