# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/en.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Főoldal",
    "APP_TITLE": "OTMEGA AI platform",
    "APP_SUBTITLE": "AI tanácsadó",
    "CHAT_PLACEHOLDER": "Írja be az üzenetét...",
    "CHAT_SEND_BUTTON": "Küldés",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 A tanácsadó hibázhat, ezért ellenőrizze az információkat.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menü",
    "ICON_NEW_CHAT": "Új csevegés",
    "ICON_HISTORY": "Előzmények",
    "ICON_TEMPLATES": "Sablonok",
    "ICON_SETTINGS": "Beállítások",
    "ICON_USER_PROFILE": "Felhasználói profil",
    "ICON_QUICK_ACTIONS": "Gyors műveletek",
    "ICON_PINNED": "Rögzítve",
    "ICON_GALLERY": "Galéria",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Alkalmazás telepítése",
    "PWA_ANDROID_MSG": "Telepítse ezt az alkalmazást az eszközére a jobb élmény és az offline hozzáférés érdekében.",
    "PWA_IOS_MSG": "Az alkalmazás telepítése iPhone/iPad készülékre:\\n1. Koppintson az alábbi Megosztás gombra\\n2. Válassza a 'Hozzáadás a Főképernyőhöz' lehetőséget",
    "PWA_BTN_INSTALL": "Telepítés",
    "PWA_BTN_LATER": "Talán később",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Jelentkezzen be az Advisor hálózatba",
    "AUTH_HEADER_SIGNUP": "Hozza létre egységes fiókját",
    "AUTH_HEADER_LOGIN_NETWORK": "Jelentkezzen be az Advisor hálózatba",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Hozza létre egységes fiókját",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Bejelentkezés",
    "AUTH_BUTTON_SIGNUP": "Fiók létrehozása",
    "AUTH_BUTTON_GOOGLE": "Folytatás Google-lal",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Elfelejtett jelszó",
    "AUTH_BUTTON_SEND_RESET_LINK": "Visszaállító link küldése",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Nincs fiókja? Regisztráljon",
    "AUTH_PROMPT_LOGIN": "Már van fiókja? Jelentkezzen be",
    "AUTH_HELPER_TEXT_SIGNUP": "Olyan egységes fiókot hoz létre, amellyel elérheti a platform összes tanácsadóját.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Olyan egységes fiókot hoz létre, amellyel elérheti a platform összes tanácsadóját.",
    "AUTH_HELPER_TEXT_LOGIN": "Használja ugyanazt a fiókot (e-mail/jelszó vagy Google), amelyet a hálózat más tanácsadóinál használt.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Használja ugyanazt a fiókot (e-mail/jelszó vagy Google), amelyet a hálózat más tanácsadóinál használt.",
    "AUTH_FORGOT_PASSWORD_LINK": "Elfelejtette a jelszavát?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Jelszó visszaállítása",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Adja meg az e-mail-címét, és elküldünk egy linket a jelszó visszaállításához.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-mail",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Bejelentkeztetés folyamatban...",
    "AUTH_STATUS_LOADING_SIGNUP": "Fiók létrehozása folyamatban...",
    "AUTH_STATUS_LOADING_RESET": "Visszaállító link küldése...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Sikeres bejelentkezés! Újratöltés...",
    "AUTH_STATUS_SUCCESS_RESET": "A visszaállító link sikeresen elküldve. Kérjük, ellenőrizze e-mailjét.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "A jelszó-visszaállító link sikeresen elküldve. Kérjük, ellenőrizze e-mailjét.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Érvénytelen e-mail vagy jelszó.",
    "AUTH_ERROR_EMAIL_EXISTS": "Ezzel az e-mail-címmel már létezik fiók az Advisor hálózatban.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Ezzel az e-mail-címmel már létezik fiók. Kérjük, jelentkezzen be. Jelenleg a következőnek a tagja:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Ezzel az e-mail-címmel már létezik fiók az Advisor hálózatban. Kérjük, zárja be ezt az ablakot, és használja a Bejelentkezés részt ugyanazzal az e-mail-címmel és korábbi jelszavával.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Jelenleg a következőnek a tagja:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-mail és jelszó megadása kötelező.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "A fiók létrejött, de a tagság beállítása sikertelen volt. Kérjük, forduljon az ügyfélszolgálathoz.",
    "AUTH_ERROR_DEFAULT": "Hiba történt. Kérjük, próbálja újra.",
    "AUTH_FORGOT_PASSWORD_ERROR": "A visszaállító link elküldése sikertelen. Kérjük, próbálja újra.",
    "INVITE_REPLY_EMAIL_SENT": "A Collabra meghívó e-mailt elküldtük a barátjának erre a címre: {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "A Collabra meghívó e-mailt újraküldtük a barátjának erre a címre: {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Jelszó megjelenítése",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Jelszó elrejtése",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Mégse",
    "GENERAL_CLOSE": "Bezárás",
    "GENERAL_SEND": "Küldés",
    "GENERAL_SEARCH": "Keresés",
    "GENERAL_RESET": "Visszaállítás",
    "GENERAL_ENABLE": "Engedélyezés",
    "GENERAL_LOADING": "Betöltés...",
    "GENERAL_DELETE": "Törlés",
    "GENERAL_DELETING": "Törlés...",
    "GENERAL_SAVE_PASSWORD": "Jelszó mentése",
    "AUTH_REMEMBER_EMAIL_LABEL": "E-mail megjegyzése",
    "GENERAL_SAVING": "Mentés...",
    "GENERAL_SENDING": "Küldés...",
    "GENERAL_REMOVING": "Eltávolítás...",
    "GENERAL_CONFIRM_REMOVAL": "Eltávolítás megerősítése",
    "GENERAL_EMPTY": "Üres",
    "GENERAL_UNAVAILABLE": "Nem elérhető",
    "GENERAL_ENABLED": "Engedélyezve",
    "GENERAL_DISABLED": "Letiltva",
    "GENERAL_GRANTED": "Megadva",
    "GENERAL_DENIED": "Megtagadva",
    "GENERAL_DEFAULT": "Alapértelmezett",
    "GENERAL_UNSUPPORTED": "Nem támogatott",
    "GENERAL_PUBLIC": "Nyilvános",
    "GENERAL_PRIVATE": "Privát",
    "GENERAL_USERNAME": "Felhasználónév",
    "GENERAL_EMAIL": "E-mail",
    "GENERAL_YOU": "Ön",
    "GENERAL_USER": "Felhasználó",
    "GENERAL_UNKNOWN": "Ismeretlen",
    "GENERAL_VISITOR": "Látogató",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Ismeretlen banner",
    "GENERAL_ADVISOR_BANNER": "Tanácsadói banner",
    "GENERAL_NOT_AVAILABLE": "N/A",
    "GENERAL_NOT_SELECTED": "Nincs kiválasztva",
    "GENERAL_NO_EMAIL_FOUND": "Nem található e-mail",
    "GENERAL_USER_ZERO_ONLY": "Csak User Zero",
    "GENERAL_CONNECTION_STATE": "Kapcsolat állapota",
    "GENERAL_DISPLAY_ONLY": "Csak megjelenítés",
    "GENERAL_TEXTAREA": "Szövegmező",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menü (LCAC)",
    "HEADER_CHAT_CCAC": "Csevegés (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Gyors műveletek (RCAC)",
    "HEADER_CHANGE_STATUS": "Állapot módosítása",
    "HEADER_OT_COIN_BALANCE": "OT Coin egyenleg",
    "HEADER_ALT_USER": "Felhasználó",
    "STATUS_BUSY": "Elfoglalt",
    "STATUS_AWAY": "Távol",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Láthatatlan",
    "NETWORK_CHECKING_CONNECTION": "Kapcsolat ellenőrzése...",
    "NETWORK_ONLINE_LATENCY": "Online (késleltetés: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Hálózat: jó (koppintson a pingeléshez)",
    "CHAT_TARGET_ALT": "Csevegés célpontja",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Keresés...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "{name} profilképének megnyitása",
    "CHAT_MESSAGE_INPUT_ARIA": "Üzenetbevitel",
    "CHAT_TOGGLE_VIEW_ARIA": "Nézet váltása",
    "CHAT_ADD_USER_ARIA": "Felhasználó hozzáadása",
    "CHAT_ATTACH_ARIA": "Csatolás",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Küldés",
    "CHAT_SEARCH_ARIA": "Keresés",
    "CHAT_OPEN_SEARCH_ARIA": "Keresés megnyitása",
    "CHAT_CLOSE_SEARCH_ARIA": "Keresés bezárása",
    "CHAT_ATTACHMENT_ALT": "Csatolmány",
    "CHAT_PREVIEW_ALT": "Előnézet",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Csatolmány eltávolítása",
    "CHAT_REPLYING_TO": "Válasz erre",
    "CHAT_CANCEL_REPLY_ARIA": "Válasz megszakítása",
    "CHAT_UPLOADING": "Feltöltés...",
    "CHAT_LOADING_CHATS": "Csevegések betöltése...",
    "CHAT_SEND_FAILED": "Küldés sikertelen",
    "CHAT_SEND_FAILED_RETRY": "A küldés sikertelen. Kérjük, próbálja újra.",
    "CHAT_RETRY": "Újrapróbálkozás",
    "CHAT_EDITED": "szerkesztve",
    "CHAT_TYPING": "Ír",
    "CHAT_LOADING": "Betöltés",
    "CHAT_PENDING_INVITATION": "Függőben lévő meghívás",
    "CHAT_PENDING_INVITATION_MIN": "{count} perc Függőben lévő meghívás",
    "CHAT_PENDING_INVITATION_HR": "{count} óra Függőben lévő meghívás",
    "CHAT_PENDING_INVITATION_DAY": "{count} nap Függőben lévő meghívás",
    "CHAT_WAITING_FOR_YOU": "{label} - Önre vár",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Elfogadásra vár",
    "CHAT_MICROPHONE_ACCESS_DENIED": "A mikrofonhoz való hozzáférés megtagadva.",
    "CHAT_UPLOAD_FAILED": "Feltöltés sikertelen: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "A feltöltéshez internetkapcsolat szükséges. Kérjük, próbálja újra, amikor online van.",
    "CHAT_ERROR_AUTH": "Hitelesítési hiba",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Hiányzó fájlnév vagy content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Hiányzó conversation_id vagy target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Hiányzó conversation_id nem avatar feltöltéshez",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Érvénytelen avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "A Supabase szolgáltatáskliens nem elérhető",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Az avatar olvasási visszaigazolása csak tanácsadói csevegési környezetben érvényes",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Az avatar-folyamat üzenete nem található, vagy nem jogosult olvasási visszaigazolásra",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Az avatarüzenet olvasottként való véglegesítése sikertelen",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 csatolmány",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} csatolmány",
    "CHAT_VOICE_NOTE": "Hangjegyzet",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "A csevegés nem elérhető. Ez a felhasználó letiltotta Önt.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "A csevegés nem elérhető. Ön letiltotta ezt a felhasználót.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "A fiókhoz való hozzáférést irányelv blokkolja.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "A csevegés nem elérhető. Ezt a fiókot a User Zero véglegesen letiltotta.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "A csevegés nem elérhető. Kölcsönös tiltás van érvényben.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "A csevegés tiltási irányelv miatt nem elérhető.",
    "MESSAGE_PREVIEW_PHOTO": "Fotó",
    "MESSAGE_PREVIEW_VOICE": "Hangüzenet",
    "MESSAGE_PREVIEW_VIDEO": "Videó",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Fájl",
    "MESSAGE_PREVIEW_MESSAGE": "Üzenet",
    "MESSAGE_PREVIEW_SYSTEM": "Rendszerüzenet",
    "MESSAGE_PREVIEW_NEW": "Új üzenet",
    "MESSAGE_UNKNOWN_FILE": "Ismeretlen fájl",
    "MESSAGE_AUDIO_ATTACHMENT": "Hangcsatolmány",
    "MESSAGE_FILE_ATTACHMENT": "Csatolmány",
    "BANNER_INVITED_BY": "meghívta: {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Keresési eredmények",
    "SEARCH_QUERY_LABEL": "Lekérdezés:",
    "SEARCH_LOADING_VISIBILITY": "Keresési láthatóság betöltése...",
    "SEARCH_NO_RESULTS": "A jelenlegi keresési hatókörben nem található eredmény.",
    "SHARE_WITH_COLLABRA": "Megosztás a Collabrával",
    "SHARE_SEND_TO": "Küldés ide",
    "SHARE_SELECT_ONE_BANNER": "Válasszon egy bannert",
    "SHARE_BANNER_LIST_ARIA": "Bannerlista",
    "SHARE_NO_MATCHING_BANNER": "Nincs megfelelő banner",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Megjegyzés hozzáadása...",
    "SHARE_RECENT_CHATS": "Legutóbbi csevegések",
    "SHARE_LEFT_LIST": "Bal oldali lista",
    "SHARE_RIGHT_LIST": "Jobb oldali lista",
    "SHARE_UNTITLED_BANNER": "Névtelen banner",
    "SHARE_SHARED_CONTENT": "Megosztott tartalom",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "A megosztott tartalom nem nyitható meg.",
    "SHARE_OPEN_BANNER_FAILED": "A kiválasztott banner nem nyitható meg.",
    "SHARE_ONE_PHOTO_SELECTED": "1 fotó kiválasztva",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} fotó kiválasztva",
    "SHARE_ONE_FILE_SELECTED": "1 fájl kiválasztva",
    "SHARE_MANY_FILES_SELECTED": "{count} fájl kiválasztva",
    "FORWARD_MESSAGE_TITLE": "Üzenet továbbítása",
    "FORWARD_SELECT_RECIPIENTS": "Címzettek kiválasztása",
    "FORWARD_NO_OTHER_BANNER": "Nincs más elérhető banner.",
    "FORWARD_SEND_TO_COUNT": "Küldés {count} címzettnek",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Válasszon legalább egy bannert.",
    "FORWARD_FAILED_DEFAULT": "A továbbítás sikertelen. Kérjük, próbálja újra.",
    "FORWARD_PARTIAL_SENT": "{count} elküldve. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "A továbbítandó forrásüzenet nem található",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Ennek az üzenetnek még nincs továbbítható tartalma",
    "FORWARD_DESTINATION_MISSING": "A továbbítás célja hiányzik",
    "FORWARD_MESSAGE_PREVIEW": "Továbbított üzenet",
    "MENU_PASTE": "Beillesztés",
    "MENU_COPY": "Másolás",
    "MENU_REPLY": "Válasz",
    "MENU_FORWARD": "Továbbítás",
    "MENU_REMOVE_INVITATION": "Meghívás eltávolítása",
    "MENU_REMOVE_FROM_LIST": "Eltávolítás a listáról",
    "MENU_ADD_TO_LIST": "Hozzáadás a listához",
    "MENU_REJECT_INVITATION": "Meghívás elutasítása",
    "MENU_FRONTEND_VERSION": "Frontend verzió",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Banner információ: {title}",
    "MENU_MESSAGE_BUBBLE": "Üzenetbuborék",
    "MENU_CHAT_CANVAS_HEADER": "Csevegővászon - {zone}",
    "MENU_CANVAS_INFO": "Vászon információ",
    "MENU_CHAT_CANVAS_SUBLABEL": "Beszélgetési terület / aktuális csevegési felület",
    "MENU_INPUT_AREA_HEADER": "Beviteli terület - {zone}",
    "MENU_INPUT_AREA_INFO": "Beviteli terület információ: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Alsó gépelési és műveleti eszközfelület",
    "MENU_HEADER": "Fejléc - {zone}",
    "MENU_HEADER_INFO": "Fejléc információ: {title}",
    "MENU_HEADER_DESCRIPTION": "Felső navigáció és oldalvezérlők",
    "MENU_ZONE_HEADER": "Zóna - {zone}",
    "MENU_ZONE_SPACE_INFO": "Zónaterület információ",
    "MENU_EMPTY_LIST_SURFACE": "Üres/lista felület",
    "MENU_BLOCK": "Letiltás",
    "MENU_UNBLOCK": "Tiltás feloldása",
    "MENU_HIDE_IN_SEARCH": "Elrejtés a keresésben",
    "MENU_UNHIDE_IN_SEARCH": "Megjelenítés a keresésben",
    "MENU_VISIBLE_IN_SEARCH": "Látható a keresésben",
    "MENU_HIDDEN_IN_SEARCH": "Rejtett a keresésben",
    "MENU_VISIBLE_IN_USER_LIST": "Látható a felhasználói listában",
    "MENU_HIDDEN_IN_USER_LIST": "Rejtett a felhasználói listában",
    "MENU_NOT_BLOCKED": "Nincs letiltva",
    "MENU_BLOCKED": "Letiltva",
    "MENU_FRONTEND_VERSION_LOADING": "Betöltés...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Bannerenkénti érték betöltése a backendből. Egyetlen opció sincs aktívként megjelölve, amíg az adatbázis válasza meg nem érkezik.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "A backend érték nem tölthető be. Nem jelenik meg megbízható aktív opció.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Az explicit bannerenkénti adatbázisérték {overrideVersion}. A globális alapértelmezett érték {globalDefaultVersion}. A célfelhasználónak teljesen frissítenie vagy újra meg kell nyitnia az alkalmazást, hogy az indítási bootstrap alkalmazza.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Nincs explicit bannerenkénti adatbázisérték tárolva. A FeV2.0.0 alapértelmezetten aktív. A globális alapértelmezett érték {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Az explicit bannerenkénti adatbázisérték a célalkalmazás teljes újratöltése után válik aktívvá",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Nincs explicit bannerenkénti érték tárolva; ez az alapértelmezett egyéni FeV2.0.0 állapot",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Ez az opció megegyezik a jelenlegi globális alapértelmezett értékkel is",
    "MENU_DELETE_PERMANENT_CONFIRM": "Véglegesen törli {target} elemet az adatbázisból? Ez eltávolítja a fiókot, a csevegési előzményeket, a függőségeket, és a jövőbeli visszatéréshez teljesen új meghívási utat kényszerít ki.",
    "MENU_DELETE_PERMANENTLY": "Végleges törlés",
    "MENU_REFRESH_PAGE": "Oldal frissítése",
    "MENU_LOG_OFF": "Kijelentkezés",
    "MENU_HARD_RELOAD": "Kényszerített újratöltés",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-mail (admin felhasználó)",
    "AUTH_PASSWORD_PLACEHOLDER": "Jelszó",
    "AUTH_CONNECTING": "Kapcsolódás...",
    "AUTH_SIGNING_OUT": "Kijelentkezés...",
    "AUTH_BACK_TO_LOGIN": "Vissza a bejelentkezéshez",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Érvénytelen szerverválasz: nem található token.",
    "AUTH_LOGIN_FAILED": "Bejelentkezés sikertelen",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "A jelszavak nem egyeznek.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "A jelszavak nem egyeznek!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "A jelszavaknak pontosan egyezniük kell.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Új jelszó",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Jelszó megerősítése",
    "AUTH_CHANGE_PASSWORD": "Jelszó módosítása",
    "AUTH_SAVING_PASSWORD": "Mentés...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "A jelszó sikeresen frissítve.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Jelenleg nem lehet módosítani a jelszót.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "A jelszó módosításához be kell jelentkeznie.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Új jelszó láthatóságának váltása",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Megerősítő jelszó láthatóságának váltása",
    "REGISTER_TITLE": "Regisztráció befejezése",
    "REGISTER_SUBTITLE": "Kérjük, állítsa be manuálisan a jelszavát.",
    "REGISTER_CREATING_ACCOUNT": "Fiók létrehozása...",
    "REGISTER_FINISH_SETUP": "Beállítás befejezése",
    "REGISTER_FAILED_SET_PASSWORD": "A jelszó beállítása sikertelen",
    "INVITE_EMAIL_INSTRUCTION": "Kérjük, adja meg a meghívott e-mail-címét (formátum: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Meghívás",
    "INVITE_EMAIL_REQUIRED": "Kérjük, adja meg a meghívott e-mail-címét.",
    "INVITE_EMAIL_INVALID": "Érvénytelen e-mail-formátum. Kérjük, használja ezt: user@example.com",
    "PENDING_INVITATION_TITLE": "Függőben lévő meghívás",
    "PENDING_INVITATION_REMOVE_QUESTION": "Eltávolítja ezt a függőben lévő meghívást az adatbázisból?",
    "PENDING_INVITATION_KEEP": "Meghívás megtartása",
    "PENDING_INVITATION_REMOVAL_FAILED": "Az eltávolítás sikertelen.",
    "REMOVE_FROM_LIST_TITLE": "Eltávolítás a listáról",
    "REMOVE_FROM_LIST_WARNING": "Eltávolítja most ezt a felhasználót mindkét listáról? A csevegési hozzáférés azonnal megszűnik. Az egyetlen visszatérési út egy új meghívás.",
    "REMOVE_FROM_LIST_KEEP": "Felhasználó megtartása a listában",
    "REMOVE_FROM_LIST_FAILED": "A listáról való eltávolítás sikertelen.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Beállítás és élő állapot",
    "PERMISSION_DIALOG_ARIA": "Beállítás és élő állapot",
    "PERMISSION_TRIGGER_ARIA": "Beállítási felugró ablak indítója",
    "PERMISSION_CLOSE_ARIA": "Jogosultsági felugró ablak bezárása",
    "PERMISSION_LIVE_STATUS": "Élő állapot",
    "PERMISSION_SYSTEM_PERMISSION": "Rendszerjogosultság",
    "PERMISSION_APP_PUSH": "Alkalmazás push",
    "PERMISSION_LOCATION_PERMISSION": "Helymeghatározási jogosultság",
    "PERMISSION_APP_LOCATION": "Alkalmazás helye",
    "PERMISSION_CONTROLS": "Jogosultsági vezérlők",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push értesítések",
    "PERMISSION_LOCATION_ACCESS": "Helyhozzáférés",
    "PERMISSION_IN_APP_SETTINGS": "Alkalmazáson belüli beállítások",
    "PERMISSION_ALERT_SOUND": "Riasztási hang",
    "PERMISSION_APP_BADGE": "Alkalmazásjelvény",
    "PERMISSION_PASSWORD_SETTINGS": "Jelszóbeállítások",
    "PERMISSION_NAVIGATION_STATUS": "Navigációs állapot",
    "PERMISSION_SELECTED_ZONE": "Kiválasztott zóna",
    "PERMISSION_STAGED_CHAT_BANNER": "Előkészített csevegési banner",
    "PERMISSION_CANVAS_CONTENT": "Vászontartalom",
    "PERMISSION_YOUR_DEVICES": "Az Ön eszközei ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Eszközlista frissítése",
    "PERMISSION_REFRESH_LIST": "Lista frissítése",
    "PERMISSION_NO_REGISTERED_DEVICES": "Nem találhatók regisztrált eszközök.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Beállítási felugró ablak átméretezése",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Push értesítések váltása",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Helyhozzáférés váltása",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Riasztási hang váltása",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Alkalmazásjelvény váltása",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Profil láthatóságának váltása",
    "PERMISSION_OFF_IN_V1": "Kikapcsolva v1-ben",
    "PERMISSION_CHAT": "Csevegés",
    "PERMISSION_BANNER_LIST": "Bannerlista",
    "PERMISSION_PUSH_DISABLED_V1": "A push értesítések le vannak tiltva a v1 Google Play kiadásban.",
    "PERMISSION_PUSH_ON_TOOLTIP": "A push értesítések be vannak kapcsolva ezen az eszközön.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "A rendszerértesítések le vannak tiltva. Koppintson a beállítási segítség megnyitásához.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Kapcsolja BE a kézbesítés megbízhatóságának javításához.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "A rendszerértesítések letiltásához nyissa meg a böngésző/webhely értesítési beállításait, és állítsa ezt a webhelyet Letiltásra.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "A rendszerértesítési jogosultság módosításához nyissa meg a böngésző/webhely értesítési beállításait, és állítsa ezt a webhelyet Engedélyezésre.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "A helyhozzáférés BE van kapcsolva a távolságalapú LCAC-rendezéshez és a térképes pozicionáláshoz.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "A Location API ebben a környezetben nem támogatott.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "A helyhozzáférés le van tiltva. Koppintson a beállítási segítség megnyitásához.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Kapcsolja BE a pontos távolságalapú LCAC-rendezés és az alkalmazáson belüli térképes pozicionálás engedélyezéséhez.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "A helyhozzáférés ebben a környezetben nem támogatott.",
    "PERMISSION_LOCATION_DISABLE_HELP": "A helyhozzáférés letiltásához nyissa meg a böngésző/webhely helybeállításait, és állítsa ezt a webhelyet Letiltásra.",
    "PERMISSION_LOCATION_ALLOW_HELP": "A helyhozzáférés engedélyezéséhez a távolságrendezéshez és az alkalmazáson belüli térképes pozicionáláshoz nyissa meg a böngésző/webhely helybeállításait, és állítsa ezt a webhelyet Engedélyezésre.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Jelenleg nem lehet betölteni a regisztrált eszközöket.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "UI Bridge betöltése...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Local Bridge betöltése...",
    "RUNTIME_LOADING_BACKEND": "Backend betöltése...",
    "RUNTIME_LOADING": "Betöltés...",
    "RUNTIME_LOADING_FROM_DATABASE": "Betöltés az adatbázisból...",
    "RUNTIME_BACKEND_CONNECTED": "Backend csatlakoztatva",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Gyorsítótárazott fallback aktív",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Alapértelmezett fallback aktív",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallback alapértékek aktívak",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Mentés backend-en keresztül...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Elmentve a backend szolgáltatásban",
    "RUNTIME_SAVE_FAILED": "Mentés sikertelen",
    "RUNTIME_LOAD_FAILED": "Betöltés sikertelen",
    "RUNTIME_CONNECTED": "Csatlakoztatva",
    "RUNTIME_LOGIN_REQUIRED": "Bejelentkezés szükséges",
    "RUNTIME_SAVED": "Elmentve",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI kész - runtime függőben",
    "RUNTIME_BACKEND_REJECTED_MODEL": "A védett backend választószolgáltatás elutasította, vagy nem tudta menteni a kért modellopciót.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "A védett backend választószolgáltatás elutasította, vagy nem tudta menteni a kért WF1 útvonal-módosítást.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "A választó most az aktív konfigurációt, a Qwen útválasztást és az engedélyezett opciókat a védett backend szolgáltatásból olvassa.",
    "RUNTIME_WF1_SELECTOR_CACHED": "A backend választószolgáltatás jelenleg nem elérhető, ezért a legutóbbi gyorsítótárazott választóállapot kerül használatra.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "A választó alapértelmezett értékei aktívak, mert nem lehetett backend vagy gyorsítótárazott választóállapotot betölteni.",
    "RUNTIME_WF1_SELECTOR_SAVED": "A védett backend választószolgáltatás frissítette az aktív WF1 útválasztási konfigurációt, és frissítette a runtime domain gyorsítótárát.",
    "FRONTEND_VERSION_TITLE": "Frontend verzió",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Ez a választó szabályozza az aktív frontend verziót minden felhasználó számára. A FeV2.0.0 aktív.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Ez a választó az aktív frontend verziót a config_domain_registry-ből olvassa. A runtime FeV2.0.0-ra oldódik fel.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "A backend frontend-verzió konfigurációja nem tölthető be, ezért a kódolt FeV2.0.0 alapérték aktív marad, amíg az indítási bootstrap újra nem tudja olvasni a védett szolgáltatást.",
    "FRONTEND_VERSION_HELPER_SAVED": "Az aktív frontend verzió el lett mentve a config_domain_registry-be. A runtime érték teljes frissítéskor vagy a következő alkalmazásbetöltéskor lép érvénybe.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "A backend frontend-verzió vezérlőszolgáltatás nem tudta menteni a kért globális verziót.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktív frontend verzió.",
    "CHAT_DELETE_WINDOW_TITLE": "Csevegés törlési ablak",
    "CHAT_DELETE_HELPER": "Ez az érték a Mindenkinél törlés elérhetőségi ablakát szabályozza másodpercben. A backend védelem mentés után azonnal változik. A buborék láthatósága teljes frissítés vagy a következő alkalmazásbetöltés után változik.",
    "CHAT_DELETE_HELPER_FALLBACK": "A backend csevegéstörlési vezérlőszolgáltatás nem tölthető be, ezért a kódolt alapérték aktív marad, amíg az indítási bootstrap újra nem tudja olvasni a védett szolgáltatást.",
    "CHAT_DELETE_HELPER_SAVED": "A Mindenkinél törlés elérhetőségi ablaka el lett mentve a config_domain_registry-be. A backend védelem azonnal változik. A buborék láthatósága teljes frissítés vagy a következő alkalmazásbetöltés után változik.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "A backend csevegéstörlési vezérlőszolgáltatás nem tudta menteni a kért ablakértéket.",
    "CHAT_DELETE_WINDOW_LABEL": "Mindenkinél törlés ablaka",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} mp",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Az értéket egész másodpercekben tárolja. A jelenlegi éles érték 86400 másodperc = 1 nap.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Ablak másodpercei",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Adjon meg 0-nál nagyobb vagy azzal egyenlő egész számot.",
    "CHAT_DELETE_SAVE_BUTTON": "Törlési ablak mentése",
    "PROFILE_VISIBILITY_TITLE": "Profil láthatósága",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "A fiók láthatóságának kezeléséhez be kell jelentkeznie.",
    "PROFILE_VISIBILITY_HELPER": "Ez a kapcsoló csak a fiók láthatósági állapotát frissíti. A felfedezhetőség és a bannerlista viselkedése ebben a fázisban változatlan marad.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "A profil láthatósága jelenleg nem tölthető be.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "A profil láthatósága jelenleg nem frissíthető.",
    "PROFILE_VISIBILITY_SAVED": "A fiók láthatósága most {visibility}. A felfedezhetőségi jelzők ebben a fázisban változatlanok maradnak.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Nyilvános fiók",
    "PROFILE_VISIBILITY_STORED": "Tárolt láthatóság",
    "WF1_MODEL_CONTROL_TITLE": "WF1 modellvezérlés",
    "WF1_ENABLE_TRANSLATION": "Fordítás / pivot engedélyezése",
    "WF1_TRANSLATION_ACTIVE": "Az AI-fordítás aktív.",
    "WF1_TRANSLATION_INACTIVE": "A WF1 tovább fut, de a forrásszöveg másolásra kerül, és a pivot inaktívként lesz megjelölve.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktív runtime slot",
    "WF1_ALLOW_SAME_LANGUAGE": "AI engedélyezése azonos nyelvpárokhoz",
    "WF1_SAME_LANGUAGE_ACTIVE": "Az azonos nyelvpárok a normál WF1 útválasztást követik.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Az azonos nyelvpárok megkerülik az AI-t, és a No Pivot nyelvet aktívként tárolják.",
    "WF1_QWEN_ROUTING": "Qwen párútválasztás",
    "WF1_QWEN_ROUTING_HELPER": "Az alább bejelölt nyelvek Qwen-Max-ot használnak, ha a pár vagy ugyanaz a bejelölt nyelv, vagy egy bejelölt nyelv angollal, vagy két bejelölt nem angol nyelv. Egyébként a kiválasztott elsődleges modell marad aktív.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter teszt slot",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter teszt slot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Csak minőségi teszt",
    "WF1_OPENROUTER_HELPER": "Ez a slot csak ideiglenes OpenRouter minőségi tesztekhez szerkeszthető. Nem módosítja az üzemi Qwen párútválasztási útvonalat, kivéve, ha maga ez a slot lesz az aktív modell.",
    "WF1_LABEL": "Címke",
    "WF1_PRODUCT": "Termék",
    "WF1_MODEL": "Modell",
    "WF1_PROVIDER_OPENROUTER": "Szolgáltató: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Titok: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter teszt slot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max OpenRouteren keresztül",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google listaár",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI listaár",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter listaár",
    "LANGUAGE_ENGLISH": "Angol",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Kínai (egyszerűsített)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Kínai (hagyományos)",
    "LANGUAGE_JAPANESE": "Japán",
    "LANGUAGE_KOREAN": "Koreai",
    "LANGUAGE_PERSIAN": "Perzsa",
    "LANGUAGE_TURKISH_ISTANBUL": "Török (Isztambul)",
    "LANGUAGE_ARABIC": "Arab",
    "LANGUAGE_FRENCH": "Francia",
    "LANGUAGE_GERMAN": "Német",
    "LANGUAGE_SPANISH": "Spanyol",
    "LANGUAGE_PORTUGUESE": "Portugál",
    "LANGUAGE_ITALIAN": "Olasz",
    "LANGUAGE_RUSSIAN": "Orosz",
    "LANGUAGE_DUTCH": "Holland",
    "LANGUAGE_VIETNAMESE": "Vietnámi",
    "LANGUAGE_INDONESIAN": "Indonéz",
    "LANGUAGE_THAI": "Thai",
    "LANGUAGE_MALAY": "Maláj",
    "WF1_PRICING_CUSTOM": "Árazás: egyedi slot modell - ellenőrizze az aktuális OpenRouter árazást",
    "WF1_SAVE_OPENROUTER_SLOT": "OpenRouter slot mentése",
    "WF1_PRICING_LINE": "Bemenet {input} - Kimenet {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Titok: {secret}",
    "ZONE_VISIBILITY_TITLE": "Zónaláthatóság vezérlése",
    "ZONE_ENABLE": "{zone} engedélyezése",
    "ZONE_ENABLED_NOTE": "A(z) {zone} megjelenhet az engedélyezett szerepkörök számára a következő alkalmazásbetöltés után.",
    "ZONE_DISABLED_NOTE": "A(z) {zone} hiányzóként lesz kezelve a nem S_Admin felhasználók számára a következő alkalmazásbetöltés után.",
    "ZONE_S_ADMIN_BYPASS": "Az S_Admin megkerüli ezt a szerepkörlistát, és mindig megtartja a hozzáférést.",
    "ZONE_ROLE_LOCKED": "A szerepkör-kiválasztások ideiglenesen zárolva vannak, amíg ez a zóna le van tiltva, és pontosan a mentett állapotukban térnek vissza, amikor a zóna újra engedélyezve lesz.",
    "ZONE_LCAC_CONTROL": "LCAC vezérlés",
    "ZONE_RCAC_CONTROL": "RCAC vezérlés",
    "ZONE_LCAC_DESCRIPTION": "A bal oldali fenntartott zóna létezését és az azt látható szerepköröket szabályozza.",
    "ZONE_RCAC_DESCRIPTION": "A jobb oldali fenntartott zóna létezését és az azt látható szerepköröket szabályozza.",
    "ZONE_VISIBILITY_BACKEND": "A zónaláthatósági bootstrap most a védett backend szolgáltatásból olvas. A módosítások a következő alkalmazásbetöltéskor lépnek érvénybe.",
    "ZONE_VISIBILITY_CACHED": "A backend zónaláthatósági szolgáltatás jelenleg nem elérhető, ezért a gyorsítótárazott vagy helyi alapértékek aktívak.",
    "ZONE_VISIBILITY_DEFAULTS": "A zónaláthatósági alapértékek aktívak, mert nem lehetett backend vagy gyorsítótárazott állapotot betölteni.",
    "ZONE_VISIBILITY_SAVED": "A zónaláthatósági bootstrap mentve lett. A runtime alkalmazáshoz kényszerített újratöltés vagy a következő alkalmazásbetöltés szükséges.",
    "ZONE_VISIBILITY_SAVE_FAILED": "A védett backend szolgáltatás nem tudta menteni a kért zónaláthatósági módosítást.",
    "ROLE_MEMBER": "Tag",
    "ROLE_STAFF": "Munkatárs",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Engedélyezze az értesítéseket az új üzenetek fogadásához.",
    "MAIN_LOG_OUT": "Kijelentkezés",
    "NOTIFICATION_NEW_MESSAGE": "Új üzenet",
    "NOTIFICATION_UNREAD_MESSAGE": "Olvasatlan üzenete van.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Teljes nézet",
    "MEDIA_AUDIO_ATTACHMENT": "Hangcsatolmány",
    "MEDIA_FILE_FALLBACK": "Fájl",
    "MEDIA_DOWNLOAD_READY": "A csatolmány készen áll a letöltésre",
    "MEDIA_TYPE_UNSUPPORTED": "A típus nem támogatott teljes nézetben",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Előző kép",
    "MEDIA_NEXT_IMAGE_ARIA": "Következő kép",
    "MEDIA_OPEN_ORIGINAL": "Eredeti megnyitása",
    "MEDIA_DOWNLOAD": "Letöltés",
    "MEDIA_CLOSE_ARIA": "Bezárás",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name} profilképe",
    "MEDIA_PROFILE_ALT": "{name} profilja",
    "MEDIA_UPLOAD_FAILED": "Feltöltés sikertelen",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend token hiba",
    "MEDIA_UPLOAD_URL_MISSING": "Kritikus: a feltöltési URL hiányzik a backend válaszából.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Hiányzó hitelesítési token a csevegési feltöltéshez",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "A csevegési feltöltési token kérése sikertelen",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Érvénytelen csevegési feltöltési válasz",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS feltöltés sikertelen",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Hiányzó fájlnév vagy contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Hiányzó file_path",
    "BLOCK_NOTICE_TITLE": "Végleges tiltási értesítés",
    "BLOCK_NOTICE_MESSAGE": "Fiókja ideiglenesen felfüggesztésre került az irányelvsértés miatt.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Ha úgy gondolja, hogy ez további egyeztetést igényel, kérjük, vegye fel a kapcsolatot",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "e-mailben.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Ismeretlen felhasználó",
    "GENERAL_GUEST": "Vendég",
    "ADVISOR_FOR_CLIENT": "Tanácsadó ehhez: {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token és jelszó megadása kötelező",
    "AUTH_ERROR_REQUEST_BODY_JSON": "A kérés törzsének JSON formátumúnak kell lennie",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Érvénytelen vagy lejárt meghívási token",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "A jelszó beállítása sikertelen: hiányzó munkamenet vagy felhasználó",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "A jelszó beállítása bejelentkezés közben sikertelen volt",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Az admin token generálása sikertelen",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "A bejelentkezés sikertelen: hiányzó munkamenet vagy felhasználó",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "A regisztráció sikeres. Kérjük, ellenőrizze e-mailjét a hitelesítéshez.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Ismeretlen regisztrációs hiba",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Érvénytelen tokenfeldolgozás",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Hozzáférési token szükséges",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "A token hash előnézetéhez e-mail utalás szükséges az átirányítási URL-ből",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Nem sikerült feloldani az identitást ehhez a tokenhez",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Csak a User Zero férhet hozzá a WF1 LLM választószolgáltatáshoz.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Csak a User Zero férhet hozzá a zónaláthatóság-vezérlő szolgáltatáshoz.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Csak a User Zero férhet hozzá a frontend verzióvezérlő szolgáltatáshoz.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Csak a User Zero tekintheti meg más felhasználó frontend verzióját.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Csak a User Zero férhet hozzá a csevegéstörlés-vezérlő szolgáltatáshoz.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Csak a User Zero törölhet véglegesen felhasználói fiókot.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Érvénytelen kérési payload.",
    "API_ERROR_INTERNAL_SERVER": "Belső szerverhiba",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Hiányzó függvény a backendben (újratöltés szükséges)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "A delivered/read átmenetekhez csak DB RPC engedélyezett.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Kérjük, várjon, mielőtt újabb üzenetet küldene.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Az üzenet sikeresen elküldve.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "A kapcsolati szolgáltatás nem elérhető.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Az üzenet küldése sikertelen.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "A név megadása kötelező.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Az e-mail érvénytelen.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Az üzenet megadása kötelező.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "A választó payload megadása kötelező.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "A zónaláthatósági payload megadása kötelező.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "A frontend verzió payload megadása kötelező.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "A csevegéstörlési vezérlő payload megadása kötelező.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Hitelesített felhasználói azonosító szükséges.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Hitelesített néző felhasználói azonosító szükséges.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Hitelesített műveletvégző felhasználói azonosító szükséges.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id megadása kötelező.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id megadása kötelező.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Az owner_user_ids lista megadása kötelező.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email megadása kötelező.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by megadása kötelező.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "A keresési runtime le van tiltva a globális frontend verzió által.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Nem jogosult ennek a függőben lévő meghívásnak a visszavonására.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Ez a meghívás már nem vonható vissza, mert a felhasználó már regisztrált.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Függőben lévő meghívás nem található.",
    "INVITE_REPLY_ALREADY_MEMBER": "Gratulálunk, a barátja ({invitee_email}) már regisztrált ebben az alkalmazásban, és tagja ennek a munkaterületnek.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Egy meghívás függőben van {invitee_email} számára, de az újraküldő e-mailt nem lehetett elindítani. Kérjük, ellenőrizze a levelezési naplókat.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "A meghívási rekord létrejött {invitee_email} számára, de az e-mail kézbesítése nem volt megerősíthető. Kérjük, próbálja újra később, vagy ellenőrizze a levelezési naplókat.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "A meghívási rekord létrehozása sikertelen. Kérjük, próbálja újra később.",
    "INVITE_REPLY_SYSTEM_ERROR": "Rendszerhiba a meghívási folyamat során: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend konfigurációs hiba: hiányzó Supabase hitelesítő adatok",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend konfigurációs hiba: érvénytelen Supabase URL",
    "CHAT_ERROR_ACCESS_DENIED": "Hozzáférés megtagadva",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "A szöveges üzenetek tartalma nem lehet üres",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Nem sikerült meghatározni a beszélgetés azonosítóját",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Az RPC hitelesítési környezete hiányzik",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "Az RPC érvénytelen üzenet payloadot adott vissza",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "A beszúrás sikertelen, nem érkezett vissza adat",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "Az operations listának kell lennie",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Érvénytelen műveleti payload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Nem támogatott operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id megadása kötelező",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Üzenet nem található",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Törlés csak a saját üzenetén engedélyezett",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "A Mindenkinél törlés már nem elérhető ehhez az üzenethez",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "A Mindenkinél törlés sikertelen",
    "API_ERROR_SERVER_CONFIGURATION": "Szerverkonfigurációs hiba",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Hiányzó webhook titkos fejléc",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Jogosulatlan webhook-forrás",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend konfigurációs hiba",
    "API_ERROR_MODULE_ATTRIBUTE": "Modulattribútum-hiba: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Hiba történt a meghívás törlése előtt, a várakozó auth felhasználó eltávolítása közben.",
    "CHAT_ERROR_DB": "DB hiba: {error}",
}
