# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/hy.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Գլխավոր",
    "APP_TITLE": "OTMEGA AI հարթակ",
    "APP_SUBTITLE": "AI խորհրդատու",
    "CHAT_PLACEHOLDER": "Մուտքագրեք ձեր հաղորդագրությունը...",
    "CHAT_SEND_BUTTON": "Ուղարկել",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Խորհրդատուն կարող է սխալվել, ուստի կրկնակի ստուգեք։",
    "STATUS_ONLINE": "Առցանց",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Մենյու",
    "ICON_NEW_CHAT": "Նոր զրույց",
    "ICON_HISTORY": "Պատմություն",
    "ICON_TEMPLATES": "Կաղապարներ",
    "ICON_SETTINGS": "Կարգավորումներ",
    "ICON_USER_PROFILE": "Օգտատիրոջ պրոֆիլ",
    "ICON_QUICK_ACTIONS": "Արագ գործողություններ",
    "ICON_PINNED": "Ամրացված",
    "ICON_GALLERY": "Պատկերասրահ",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Տեղադրել հավելվածը",
    "PWA_ANDROID_MSG": "Տեղադրեք այս հավելվածը ձեր սարքում՝ ավելի լավ փորձառության և անցանց հասանելիության համար։",
    "PWA_IOS_MSG": "Այս հավելվածը ձեր iPhone/iPad-ում տեղադրելու համար:\n1. Հպեք ներքևի Share կոճակին\n2. Ընտրեք 'Add to Home Screen'",
    "PWA_BTN_INSTALL": "Տեղադրել",
    "PWA_BTN_LATER": "Գուցե ավելի ուշ",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Մուտք գործեք խորհրդատուների ցանց",
    "AUTH_HEADER_SIGNUP": "Ստեղծեք ձեր միասնական հաշիվը",
    "AUTH_HEADER_LOGIN_NETWORK": "Մուտք գործեք խորհրդատուների ցանց",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Ստեղծեք ձեր միասնական հաշիվը",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Մուտք",
    "AUTH_BUTTON_SIGNUP": "Ստեղծել հաշիվ",
    "AUTH_BUTTON_GOOGLE": "Շարունակել Google-ով",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Մոռացել եք գաղտնաբառը",
    "AUTH_BUTTON_SEND_RESET_LINK": "Ուղարկել վերակայման հղումը",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Հաշիվ չունե՞ք։ Գրանցվեք",
    "AUTH_PROMPT_LOGIN": "Արդեն ունե՞ք հաշիվ։ Մուտք գործեք",
    "AUTH_HELPER_TEXT_SIGNUP": "Դուք ստեղծում եք միասնական հաշիվ, որը կարող եք օգտագործել այս հարթակի բոլոր խորհրդատուներին հասանելիություն ստանալու համար։",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Դուք ստեղծում եք միասնական հաշիվ, որը կարող եք օգտագործել այս հարթակի բոլոր խորհրդատուներին հասանելիություն ստանալու համար։",
    "AUTH_HELPER_TEXT_LOGIN": "Օգտագործեք նույն հաշիվը (էլ. փոստ/գաղտնաբառ կամ Google), որը օգտագործել եք այս ցանցի այլ խորհրդատուների համար։",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Օգտագործեք նույն հաշիվը (էլ. փոստ/գաղտնաբառ կամ Google), որը օգտագործել եք այս ցանցի այլ խորհրդատուների համար։",
    "AUTH_FORGOT_PASSWORD_LINK": "Մոռացե՞լ եք ձեր գաղտնաբառը։",
    "AUTH_FORGOT_PASSWORD_TITLE": "Վերակայել ձեր գաղտնաբառը",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Մուտքագրեք ձեր էլ. փոստի հասցեն, և մենք ձեզ կուղարկենք հղում՝ գաղտնաբառը վերակայելու համար։",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Էլ. փոստ",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Մուտքագրում ենք ձեզ...",
    "AUTH_STATUS_LOADING_SIGNUP": "Ստեղծվում է ձեր հաշիվը...",
    "AUTH_STATUS_LOADING_RESET": "Ուղարկվում է վերակայման հղումը...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Մուտքը հաջողվեց։ Վերաբեռնվում է...",
    "AUTH_STATUS_SUCCESS_RESET": "Վերակայման հղումը հաջողությամբ ուղարկվեց։ Խնդրում ենք ստուգել ձեր էլ. փոստը։",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Գաղտնաբառի վերակայման հղումը հաջողությամբ ուղարկվեց։ Խնդրում ենք ստուգել ձեր էլ. փոստը։",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Անվավեր էլ. փոստ կամ գաղտնաբառ։",
    "AUTH_ERROR_EMAIL_EXISTS": "Այս էլ. փոստով հաշիվ արդեն գոյություն ունի խորհրդատուների ցանցում։",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Այս էլ. փոստով հաշիվ արդեն գոյություն ունի։ Խնդրում ենք մուտք գործել։ Դուք այժմ անդամ եք՝",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Այս էլ. փոստով հաշիվ արդեն գոյություն ունի խորհրդատուների ցանցում։ Խնդրում ենք փակել այս պատուհանը և օգտագործել 'Login' բաժինը՝ նույն էլ. փոստով և ձեր նախկին գաղտնաբառով։",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Դուք այժմ անդամ եք՝",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "Էլ. փոստը և գաղտնաբառը պարտադիր են։",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Հաշիվը ստեղծվեց, բայց անդամակցության կարգավորումը չհաջողվեց։ Խնդրում ենք կապվել աջակցման ծառայության հետ։",
    "AUTH_ERROR_DEFAULT": "Սխալ տեղի ունեցավ։ Խնդրում ենք կրկին փորձել։",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Հյուրի բանների կառավարման payload-ը պարտադիր է:",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Միայն User Zero-ն կարող է թարմացնել Հյուրի բանների կառավարման վահանակները:",
    "AUTH_FORGOT_PASSWORD_ERROR": "Վերակայման հղումը ուղարկել չհաջողվեց։ Խնդրում ենք կրկին փորձել։",
    "INVITE_REPLY_EMAIL_SENT": "Collabra-ի հրավերի էլ. նամակը ուղարկվեց ձեր ընկերոջը՝ {invitee_email} հասցեով։",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra-ի հրավերի էլ. նամակը կրկին ուղարկվեց ձեր ընկերոջը՝ {invitee_email} հասցեով։",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Ցույց տալ գաղտնաբառը",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Թաքցնել գաղտնաբառը",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "Լավ",
    "GENERAL_CANCEL": "Չեղարկել",
    "GENERAL_CLOSE": "Փակել",
    "GENERAL_SEND": "Ուղարկել",
    "GENERAL_SEARCH": "Որոնել",
    "GENERAL_RESET": "Վերակայել",
    "GENERAL_ENABLE": "Միացնել",
    "GENERAL_LOADING": "Բեռնվում է...",
    "GENERAL_DELETE": "Ջնջել",
    "GENERAL_DELETING": "Ջնջվում է...",
    "GENERAL_SAVE_PASSWORD": "Պահպանել գաղտնաբառը",
    "AUTH_REMEMBER_EMAIL_LABEL": "Հիշել էլ. փոստը",
    "GENERAL_SAVING": "Պահպանվում է...",
    "GENERAL_SENDING": "Ուղարկվում է...",
    "GENERAL_REMOVING": "Հեռացվում է...",
    "GENERAL_CONFIRM_REMOVAL": "Հաստատել հեռացումը",
    "GENERAL_EMPTY": "Դատարկ",
    "GENERAL_UNAVAILABLE": "Անհասանելի",
    "GENERAL_ENABLED": "Միացված",
    "GENERAL_DISABLED": "Անջատված",
    "GENERAL_GRANTED": "Թույլատրված",
    "GENERAL_DENIED": "Մերժված",
    "GENERAL_DEFAULT": "Լռելյայն",
    "GENERAL_UNSUPPORTED": "Չի աջակցվում",
    "GENERAL_PUBLIC": "Հանրային",
    "GENERAL_PRIVATE": "Մասնավոր",
    "GENERAL_USERNAME": "Օգտանուն",
    "GENERAL_EMAIL": "Էլ. փոստ",
    "GENERAL_YOU": "Դուք",
    "GENERAL_USER": "Օգտատեր",
    "GENERAL_UNKNOWN": "Անհայտ",
    "GENERAL_VISITOR": "Այցելու",
    "GENERAL_PROFILE": "Պրոֆիլ",
    "GENERAL_BANNER": "Բաններ",
    "GENERAL_UNKNOWN_BANNER": "Անհայտ բաններ",
    "GENERAL_ADVISOR_BANNER": "Խորհրդատուի բաններ",
    "GENERAL_NOT_AVAILABLE": "Հասանելի չէ",
    "GENERAL_NOT_SELECTED": "Ընտրված չէ",
    "GENERAL_NO_EMAIL_FOUND": "Էլ. փոստ չի գտնվել",
    "GENERAL_USER_ZERO_ONLY": "Միայն User Zero",
    "GENERAL_CONNECTION_STATE": "Միացման վիճակ",
    "GENERAL_DISPLAY_ONLY": "Միայն ցուցադրում",
    "GENERAL_TEXTAREA": "Տեքստային դաշտ",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Մենյու (LCAC)",
    "HEADER_CHAT_CCAC": "Զրույց (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Արագ գործողություններ (RCAC)",
    "HEADER_CHANGE_STATUS": "Փոխել կարգավիճակը",
    "HEADER_OT_COIN_BALANCE": "OT Coin մնացորդ",
    "HEADER_ALT_USER": "Օգտատեր",
    "STATUS_BUSY": "Զբաղված",
    "STATUS_AWAY": "Բացակա",
    "STATUS_OFFLINE": "Անցանց",
    "STATUS_INVISIBLE": "Անտեսանելի",
    "NETWORK_CHECKING_CONNECTION": "Ստուգվում է կապը...",
    "NETWORK_ONLINE_LATENCY": "Առցանց (ուշացում՝ {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Ցանց՝ լավ (հպեք ping անելու համար)",
    "CHAT_TARGET_ALT": "Զրույցի թիրախ",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Որոնել...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Բացել {name}-ի պրոֆիլի նկարը",
    "CHAT_MESSAGE_INPUT_ARIA": "Հաղորդագրության մուտքագրում",
    "CHAT_TOGGLE_VIEW_ARIA": "Փոխել դիտումը",
    "CHAT_ADD_USER_ARIA": "Ավելացնել օգտատեր",
    "CHAT_ATTACH_ARIA": "Կցել",
    "CHAT_MIC_ARIA": "Միկրոֆոն",
    "CHAT_SEND_ARIA": "Ուղարկել",
    "CHAT_SEARCH_ARIA": "Որոնել",
    "CHAT_OPEN_SEARCH_ARIA": "Բացել որոնումը",
    "CHAT_CLOSE_SEARCH_ARIA": "Փակել որոնումը",
    "CHAT_ATTACHMENT_ALT": "Կցորդ",
    "CHAT_PREVIEW_ALT": "Նախադիտում",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Հեռացնել կցորդը",
    "CHAT_REPLYING_TO": "Պատասխան՝",
    "CHAT_CANCEL_REPLY_ARIA": "Չեղարկել պատասխանը",
    "CHAT_UPLOADING": "Վերբեռնվում է...",
    "CHAT_LOADING_CHATS": "Զրույցները բեռնվում են...",
    "CHAT_SEND_FAILED": "Ուղարկումը ձախողվեց",
    "CHAT_SEND_FAILED_RETRY": "Ուղարկումը ձախողվեց։ Խնդրում ենք կրկին փորձել։",
    "CHAT_RETRY": "Կրկին փորձել",
    "CHAT_EDITED": "խմբագրված",
    "CHAT_TYPING": "Մուտքագրում է",
    "CHAT_LOADING": "Բեռնվում է",
    "CHAT_PENDING_INVITATION": "Սպասող հրավեր",
    "CHAT_PENDING_INVITATION_MIN": "{count} րոպե սպասող հրավեր",
    "CHAT_PENDING_INVITATION_HR": "{count} ժամ սպասող հրավեր",
    "CHAT_PENDING_INVITATION_DAY": "{count} օր սպասող հրավեր",
    "CHAT_WAITING_FOR_YOU": "{label} - Սպասում է ձեզ",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Ընդունումը սպասվում է",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Միկրոֆոնի հասանելիությունը մերժված է։",
    "CHAT_UPLOAD_FAILED": "Վերբեռնումը ձախողվեց՝ {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Վերբեռնման համար անհրաժեշտ է ինտերնետ կապ։ Խնդրում ենք կրկին փորձել, երբ առցանց լինեք։",
    "OFFLINE_SHOWING_SAVED_DATA": "",
    "OFFLINE_DATA_MAY_BE_OUTDATED": "",
    "OFFLINE_ACTION_REQUIRES_CONNECTION": "",
    "OFFLINE_MESSAGE_WAITING_CONNECTION": "",
    "OFFLINE_PENDING_MESSAGES_TOOLTIP": "",
    "APP_BACK_EXIT_HINT": "",
    "CHAT_ERROR_AUTH": "Նույնականացման սխալ",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Ֆայլի անունը կամ content_type-ը բացակայում է",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id-ը կամ target_id-ը բացակայում է",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Ոչ ավատար վերբեռնման համար conversation_id-ը բացակայում է",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Անվավեր avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase ծառայության հաճախորդը անհասանելի է",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Ավատարի ընթերցման հաստատումը վավեր է միայն խորհրդատուի զրույցի համատեքստում",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Ավատարի հոսքի հաղորդագրությունը չի գտնվել կամ իրավասու չէ ընթերցման հաստատման համար",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Ավատարի հաղորդագրությունը որպես կարդացված վերջնականացնել չհաջողվեց",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 կցորդ",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} կցորդ",
    "CHAT_VOICE_NOTE": "Ձայնային նշում",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Զրույցը անհասանելի է։ Այս օգտատերը արգելափակել է ձեզ։",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Զրույցը անհասանելի է։ Դուք արգելափակել եք այս օգտատիրոջը։",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Հաշվի հասանելիությունը արգելափակված է քաղաքականությամբ։",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Զրույցը անհասանելի է։ Այս հաշիվը վերջնական արգելափակված է User Zero-ի կողմից։",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Զրույցը անհասանելի է։ Փոխադարձ արգելափակումը ակտիվ է։",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Զրույցը անհասանելի է արգելափակման քաղաքականության պատճառով։",
    "MESSAGE_PREVIEW_PHOTO": "Լուսանկար",
    "MESSAGE_PREVIEW_VOICE": "Ձայնային հաղորդագրություն",
    "MESSAGE_PREVIEW_VIDEO": "Տեսանյութ",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Ֆայլ",
    "MESSAGE_PREVIEW_MESSAGE": "Հաղորդագրություն",
    "MESSAGE_PREVIEW_SYSTEM": "Համակարգային հաղորդագրություն",
    "MESSAGE_PREVIEW_NEW": "Նոր հաղորդագրություն",
    "MESSAGE_UNKNOWN_FILE": "Անհայտ ֆայլ",
    "MESSAGE_AUDIO_ATTACHMENT": "Աուդիո կցորդ",
    "MESSAGE_FILE_ATTACHMENT": "Կցորդ",
    "BANNER_INVITED_BY": "հրավիրված է {label}-ի կողմից",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Որոնման արդյունքներ",
    "SEARCH_QUERY_LABEL": "Հարցում՝",
    "SEARCH_LOADING_VISIBILITY": "Բեռնվում է որոնման տեսանելիությունը...",
    "SEARCH_NO_RESULTS": "Ընթացիկ որոնման տիրույթում արդյունք չի գտնվել։",
    "SHARE_WITH_COLLABRA": "Կիսվել Collabra-ի հետ",
    "SHARE_SEND_TO": "Ուղարկել՝",
    "SHARE_SELECT_ONE_BANNER": "Ընտրեք մեկ բաններ",
    "SHARE_BANNER_LIST_ARIA": "Բաններների ցանկ",
    "SHARE_NO_MATCHING_BANNER": "Համապատասխան բաններ չկա",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Ավելացնել մեկնաբանություն...",
    "SHARE_RECENT_CHATS": "Վերջին զրույցներ",
    "SHARE_LEFT_LIST": "Ձախ ցանկ",
    "SHARE_RIGHT_LIST": "Աջ ցանկ",
    "SHARE_UNTITLED_BANNER": "Անվերնագիր բաններ",
    "SHARE_SHARED_CONTENT": "Կիսված բովանդակություն",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Կիսված բովանդակությունը չհաջողվեց բացել։",
    "SHARE_OPEN_BANNER_FAILED": "Ընտրված բանները չհաջողվեց բացել։",
    "SHARE_ONE_PHOTO_SELECTED": "Ընտրվել է 1 լուսանկար",
    "SHARE_MANY_PHOTOS_SELECTED": "Ընտրվել է {count} լուսանկար",
    "SHARE_ONE_FILE_SELECTED": "Ընտրվել է 1 ֆայլ",
    "SHARE_MANY_FILES_SELECTED": "Ընտրվել է {count} ֆայլ",
    "FORWARD_MESSAGE_TITLE": "Փոխանցել հաղորդագրությունը",
    "FORWARD_SELECT_RECIPIENTS": "Ընտրել ստացողներին",
    "FORWARD_NO_OTHER_BANNER": "Այլ բաններ հասանելի չէ։",
    "FORWARD_SEND_TO_COUNT": "Ուղարկել {count}-ին",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Ընտրեք առնվազն մեկ բաններ։",
    "FORWARD_FAILED_DEFAULT": "Փոխանցումը ձախողվեց։ Խնդրում ենք կրկին փորձել։",
    "FORWARD_PARTIAL_SENT": "{count} ուղարկվեց։ {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Փոխանցման աղբյուր հաղորդագրությունը չի գտնվել",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Այս հաղորդագրությունը դեռ փոխանցելի բովանդակություն չունի",
    "FORWARD_DESTINATION_MISSING": "Փոխանցման նպատակակետը բացակայում է",
    "FORWARD_MESSAGE_PREVIEW": "Փոխանցված հաղորդագրություն",
    "MENU_PASTE": "Տեղադրել",
    "MENU_COPY": "Պատճենել",
    "MENU_REPLY": "Պատասխանել",
    "MENU_FORWARD": "Փոխանցել",
    "MENU_REMOVE_INVITATION": "Հեռացնել հրավերը",
    "MENU_REMOVE_FROM_LIST": "Հեռացնել ցանկից",
    "MENU_GOODBYE_GUEST": "Ցտեսություն, հյուր",
    "MENU_ADD_TO_LIST": "Ավելացնել ցանկին",
    "MENU_REJECT_INVITATION": "Մերժել հրավերը",
    "MENU_FRONTEND_VERSION": "Frontend տարբերակ",
    "MENU_BANNER_HEADER": "Բաններ - {zone}",
    "MENU_BANNER_INFO": "Բանների տվյալներ՝ {title}",
    "MENU_MESSAGE_BUBBLE": "Հաղորդագրության փուչիկ",
    "MENU_CHAT_CANVAS_HEADER": "Զրույցի Canvas - {zone}",
    "MENU_CANVAS_INFO": "Canvas-ի տվյալներ",
    "MENU_CHAT_CANVAS_SUBLABEL": "Զրույցի տարածք / ընթացիկ զրույցի մակերես",
    "MENU_INPUT_AREA_HEADER": "Մուտքագրման տարածք - {zone}",
    "MENU_INPUT_AREA_INFO": "Մուտքագրման տարածքի տվյալներ՝ {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Ստորին մուտքագրման և գործողության գործիքների մակերես",
    "MENU_HEADER": "Վերնագիր - {zone}",
    "MENU_HEADER_INFO": "Վերնագրի տվյալներ՝ {title}",
    "MENU_HEADER_DESCRIPTION": "Վերին նավիգացիա և էջի կառավարիչներ",
    "MENU_ZONE_HEADER": "Գոտի - {zone}",
    "MENU_ZONE_SPACE_INFO": "Գոտու տարածքի տվյալներ",
    "MENU_EMPTY_LIST_SURFACE": "Դատարկ/ցանկի մակերես",
    "MENU_BLOCK": "Արգելափակել",
    "MENU_UNBLOCK": "Հանել արգելափակումը",
    "MENU_HIDE_IN_SEARCH": "Թաքցնել որոնման մեջ",
    "MENU_UNHIDE_IN_SEARCH": "Ցույց տալ որոնման մեջ",
    "MENU_VISIBLE_IN_SEARCH": "Տեսանելի որոնման մեջ",
    "MENU_HIDDEN_IN_SEARCH": "Թաքնված որոնման մեջ",
    "MENU_VISIBLE_IN_USER_LIST": "Տեսանելի օգտատերերի ցանկում",
    "MENU_HIDDEN_IN_USER_LIST": "Թաքնված օգտատերերի ցանկում",
    "MENU_NOT_BLOCKED": "Արգելափակված չէ",
    "MENU_BLOCKED": "Արգելափակված",
    "MENU_FRONTEND_VERSION_LOADING": "Բեռնվում է...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Բեռնվում է յուրաքանչյուր բանների արժեքը backend-ից։ Ոչ մի տարբերակ ակտիվ չի նշվում, մինչև տվյալների բազայի պատասխանը չգա։",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend-ի արժեքը չհաջողվեց բեռնել։ Վստահելի ակտիվ տարբերակ չի ցուցադրվում։",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Տվյալների բազայում յուրաքանչյուր բանների հստակ արժեքը {overrideVersion} է։ Գլոբալ լռելյայնը {globalDefaultVersion} է։ Թիրախ օգտատերը պետք է ամբողջությամբ թարմացնի կամ նորից բացի հավելվածը, որպեսզի մեկնարկային bootstrap-ը կիրառի այն։",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Յուրաքանչյուր բանների հստակ արժեք պահված չէ։ FeV2.0.0-ը ակտիվ է լռելյայն։ Գլոբալ լռելյայնը {globalDefaultVersion} է։",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Յուրաքանչյուր բանների հստակ տվյալների բազայի արժեքը ակտիվ է դառնում թիրախ հավելվածի ամբողջական վերաբեռնումից հետո",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Յուրաքանչյուր բանների հստակ արժեք պահված չէ. սա լռելյայն անհատական FeV2.0.0 վիճակն է",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Այս տարբերակը նաև հավասար է ընթացիկ գլոբալ լռելյայն արժեքին",
    "MENU_DELETE_PERMANENT_CONFIRM": "Ջնջե՞լ {target}-ը տվյալների բազայից ընդմիշտ։ Սա հեռացնում է հաշիվը, զրույցի պատմությունը, կախվածությունները և ապագա վերադարձի համար պարտադրում է լիովին նոր հրավերի ուղի։",
    "MENU_DELETE_PERMANENTLY": "Ջնջել ընդմիշտ",
    "MENU_REFRESH_PAGE": "Թարմացնել էջը",
    "MENU_LOG_OFF": "Դուրս գալ",
    "MENU_HARD_RELOAD": "Կոշտ վերաբեռնում",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Էլ. փոստ (Admin օգտատեր)",
    "AUTH_PASSWORD_PLACEHOLDER": "Գաղտնաբառ",
    "AUTH_CONNECTING": "Միանում է...",
    "AUTH_SIGNING_OUT": "Դուրս է գալիս...",
    "AUTH_BACK_TO_LOGIN": "Վերադառնալ մուտքին",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Անվավեր սերվերի պատասխան՝ token չի գտնվել։",
    "AUTH_LOGIN_FAILED": "Մուտքը ձախողվեց",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Գաղտնաբառերը չեն համընկնում։",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Գաղտնաբառերը չեն համընկնում։",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Գաղտնաբառերը պետք է ճշգրիտ համընկնեն։",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Նոր գաղտնաբառ",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Հաստատել գաղտնաբառը",
    "AUTH_CHANGE_PASSWORD": "Փոխել գաղտնաբառը",
    "AUTH_SAVING_PASSWORD": "Պահպանվում է...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Գաղտնաբառը հաջողությամբ թարմացվեց։",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Այս պահին գաղտնաբառը հնարավոր չէ փոխել։",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Գաղտնաբառը փոխելու համար պետք է մուտք գործած լինեք։",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Փոխել նոր գաղտնաբառի տեսանելիությունը",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Փոխել հաստատման գաղտնաբառի տեսանելիությունը",
    "REGISTER_TITLE": "Ավարտել գրանցումը",
    "REGISTER_SUBTITLE": "Խնդրում ենք ձեռքով սահմանել ձեր գաղտնաբառը։",
    "REGISTER_CREATING_ACCOUNT": "Հաշիվը ստեղծվում է...",
    "REGISTER_FINISH_SETUP": "Ավարտել կարգավորումը",
    "REGISTER_FAILED_SET_PASSWORD": "Գաղտնաբառը սահմանել չհաջողվեց",
    "INVITE_EMAIL_INSTRUCTION": "Խնդրում ենք մուտքագրել հրավիրվողի էլ. փոստը (ձևաչափ՝ user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Հրավիրել",
    "INVITE_EMAIL_REQUIRED": "Խնդրում ենք մուտքագրել հրավիրվողի էլ. փոստը։",
    "INVITE_EMAIL_INVALID": "Էլ. փոստի անվավեր ձևաչափ։ Խնդրում ենք օգտագործել՝ user@example.com",
    "PENDING_INVITATION_TITLE": "Սպասող հրավեր",
    "PENDING_INVITATION_REMOVE_QUESTION": "Հեռացնե՞լ այս սպասող հրավերը տվյալների բազայից։",
    "PENDING_INVITATION_KEEP": "Պահել հրավերը",
    "PENDING_INVITATION_REMOVAL_FAILED": "Հեռացումը ձախողվեց։",
    "REMOVE_FROM_LIST_TITLE": "Հեռացնել ցանկից",
    "REMOVE_FROM_LIST_WARNING": "Հիմա հեռացնե՞լ այս օգտատիրոջը երկու ցանկերից։ Զրույցի հասանելիությունը անմիջապես կկտրվի։ Վերադարձի միակ ուղին նոր հրավերն է։",
    "REMOVE_FROM_LIST_KEEP": "Պահել օգտատիրոջը ցանկում",
    "REMOVE_FROM_LIST_FAILED": "Ցանկից հեռացումը ձախողվեց։",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Կարգավորում և կենդանի կարգավիճակ",
    "PERMISSION_DIALOG_ARIA": "Կարգավորում և կենդանի կարգավիճակ",
    "PERMISSION_TRIGGER_ARIA": "Կարգավորումների popup-ի գործարկիչ",
    "PERMISSION_CLOSE_ARIA": "Փակել թույլտվությունների popup-ը",
    "PERMISSION_LIVE_STATUS": "Կենդանի կարգավիճակ",
    "PERMISSION_SYSTEM_PERMISSION": "Համակարգային թույլտվություն",
    "PERMISSION_APP_PUSH": "Հավելվածի Push",
    "PERMISSION_LOCATION_PERMISSION": "Տեղադրության թույլտվություն",
    "PERMISSION_APP_LOCATION": "Հավելվածի տեղադրություն",
    "PERMISSION_CONTROLS": "Թույլտվությունների կառավարիչներ",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push ծանուցումներ",
    "PERMISSION_LOCATION_ACCESS": "Տեղադրության հասանելիություն",
    "PERMISSION_IN_APP_SETTINGS": "Ներհավելվածային կարգավորումներ",
    "PERMISSION_ALERT_SOUND": "Զգուշացման ձայն",
    "PERMISSION_APP_BADGE": "Հավելվածի նշան",
    "PERMISSION_PASSWORD_SETTINGS": "Գաղտնաբառի կարգավորումներ",
    "PERMISSION_NAVIGATION_STATUS": "Նավիգացիայի կարգավիճակ",
    "PERMISSION_SELECTED_ZONE": "Ընտրված գոտի",
    "PERMISSION_STAGED_CHAT_BANNER": "Պատրաստված զրույցի բաններ",
    "PERMISSION_CANVAS_CONTENT": "Canvas բովանդակություն",
    "PERMISSION_YOUR_DEVICES": "Ձեր սարքերը ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Թարմացնել սարքերի ցանկը",
    "PERMISSION_REFRESH_LIST": "Թարմացնել ցանկը",
    "PERMISSION_NO_REGISTERED_DEVICES": "Գրանցված սարքեր չեն գտնվել։",
    "PERMISSION_RESIZE_POPUP_ARIA": "Փոխել կարգավորումների popup-ի չափը",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Միացնել/անջատել push ծանուցումները",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Միացնել/անջատել տեղադրության հասանելիությունը",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Միացնել/անջատել զգուշացման ձայնը",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Միացնել/անջատել հավելվածի նշանը",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Միացնել/անջատել պրոֆիլի տեսանելիությունը",
    "PERMISSION_OFF_IN_V1": "Անջատված v1-ում",
    "PERMISSION_CHAT": "Զրույց",
    "PERMISSION_BANNER_LIST": "Բաններների ցանկ",
    "PERMISSION_PUSH_DISABLED_V1": "Push ծանուցումները անջատված են v1 Google Play թողարկման համար։",
    "PERMISSION_PUSH_ON_TOOLTIP": "Push ծանուցումները միացված են այս սարքի համար։",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Համակարգային ծանուցումները արգելափակված են։ Հպեք՝ կարգավորումների օգնությունը բացելու համար։",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Միացրեք՝ առաքման հուսալիությունը բարելավելու համար։",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Համակարգային ծանուցումները անջատելու համար բացեք ձեր դիտարկչի/կայքի ծանուցումների կարգավորումները և այս կայքը սահմանեք որպես Block։",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Համակարգային ծանուցումների թույլտվությունը փոխելու համար բացեք ձեր դիտարկչի/կայքի ծանուցումների կարգավորումները և այս կայքը սահմանեք որպես Allow։",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Տեղադրության հասանելիությունը միացված է հեռավորության վրա հիմնված LCAC տեսակավորման և քարտեզի դիրքավորման համար։",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Տեղադրության API-ն այս միջավայրում չի աջակցվում։",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Տեղադրության հասանելիությունը արգելափակված է։ Հպեք՝ կարգավորումների օգնությունը բացելու համար։",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Միացրեք՝ թույլ տալու ճշգրիտ հեռավորության վրա հիմնված LCAC տեսակավորում և ներհավելվածային քարտեզի դիրքավորում։",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Տեղադրության հասանելիությունը այս միջավայրում չի աջակցվում։",
    "PERMISSION_LOCATION_DISABLE_HELP": "Տեղադրության հասանելիությունը անջատելու համար բացեք ձեր դիտարկչի/կայքի տեղադրության կարգավորումները և այս կայքը սահմանեք որպես Block։",
    "PERMISSION_LOCATION_ALLOW_HELP": "Տեղադրության հասանելիությունը միացնելու համար հեռավորության տեսակավորման և ներհավելվածային քարտեզի դիրքավորման համար բացեք ձեր դիտարկչի/կայքի տեղադրության կարգավորումները և այս կայքը սահմանեք որպես Allow։",
    "PERMISSION_DEVICE_LOAD_FAILED": "Գրանցված սարքերը հիմա բեռնել հնարավոր չէ։",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Բեռնվում է UI Bridge-ը...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Բեռնվում է Local Bridge-ը...",
    "RUNTIME_LOADING_BACKEND": "Բեռնվում է Backend-ը...",
    "RUNTIME_LOADING": "Բեռնվում է...",
    "RUNTIME_LOADING_FROM_DATABASE": "Բեռնվում է տվյալների բազայից...",
    "RUNTIME_BACKEND_CONNECTED": "Backend-ը միացված է",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Քեշավորված fallback-ը ակտիվ է",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Լռելյայն fallback-ը ակտիվ է",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallback լռելյայնները ակտիվ են",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Պահպանվում է backend-ի միջոցով...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Պահպանվել է backend ծառայությունում",
    "RUNTIME_SAVE_FAILED": "Պահպանումը ձախողվեց",
    "RUNTIME_LOAD_FAILED": "Բեռնումը ձախողվեց",
    "RUNTIME_CONNECTED": "Միացված է",
    "RUNTIME_LOGIN_REQUIRED": "Մուտքը պարտադիր է",
    "RUNTIME_SAVED": "Պահպանված է",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI-ն պատրաստ է - runtime-ը սպասում է",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Պաշտպանված backend selector ծառայությունը մերժեց կամ չկարողացավ պահպանել պահանջված մոդելի տարբերակը։",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Պաշտպանված backend selector ծառայությունը մերժեց կամ չկարողացավ պահպանել պահանջված WF1 routing փոփոխությունը։",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selector-ը հիմա կարդում է ակտիվ config-ը, Qwen routing-ը և թույլատրված տարբերակները պաշտպանված backend ծառայությունից։",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend selector ծառայությունը հիմա անհասանելի է, ուստի օգտագործվում է selector-ի վերջին քեշավորված վիճակը։",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Selector-ի լռելյայն արժեքները ակտիվ են, քանի որ backend կամ քեշավորված վիճակ չհաջողվեց բեռնել։",
    "RUNTIME_WF1_SELECTOR_SAVED": "Պաշտպանված backend selector ծառայությունը թարմացրեց ակտիվ WF1 routing config-ը և թարմացրեց runtime domain cache-ը։",
    "FRONTEND_VERSION_TITLE": "Frontend տարբերակ",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Այս selector-ը կառավարում է ակտիվ frontend տարբերակը բոլոր օգտատերերի համար։ FeV2.0.0-ը ակտիվ է։",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Այս selector-ը կարդում է ակտիվ frontend տարբերակը config_domain_registry-ից։ Runtime-ը լուծվում է որպես FeV2.0.0։",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend frontend-version config-ը չհաջողվեց բեռնել, ուստի կոդավորված FeV2.0.0 լռելյայնը ակտիվ է, մինչև startup bootstrap-ը կրկին կարողանա կարդալ պաշտպանված ծառայությունը։",
    "FRONTEND_VERSION_HELPER_SAVED": "Ակտիվ frontend տարբերակը պահպանվեց config_domain_registry-ում։ Ամբողջական թարմացումը կամ հավելվածի հաջորդ բեռնումը կիրառում է runtime արժեքը։",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend frontend-version control ծառայությունը չկարողացավ պահպանել պահանջված գլոբալ տարբերակը։",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Ակտիվ frontend տարբերակ։",
    "CHAT_DELETE_WINDOW_TITLE": "Զրույցի ջնջման պատուհան",
    "CHAT_DELETE_HELPER": "Այս արժեքը կառավարում է Delete for everyone հասանելիության պատուհանը վայրկյաններով։ Backend guard-ը փոխվում է անմիջապես պահպանումից հետո։ Փուչիկի տեսանելիությունը փոխվում է ամբողջական թարմացումից կամ հավելվածի հաջորդ բեռնումից հետո։",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend chat delete control ծառայությունը չհաջողվեց բեռնել, ուստի կոդավորված լռելյայնը մնում է ակտիվ, մինչև startup bootstrap-ը կրկին կարողանա կարդալ պաշտպանված ծառայությունը։",
    "CHAT_DELETE_HELPER_SAVED": "Delete for everyone հասանելիության պատուհանը պահպանվեց config_domain_registry-ում։ Backend guard-ը փոխվում է անմիջապես։ Փուչիկի տեսանելիությունը փոխվում է ամբողջական թարմացումից կամ հավելվածի հաջորդ բեռնումից հետո։",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend chat delete control ծառայությունը չկարողացավ պահպանել պահանջված պատուհանի արժեքը։",
    "CHAT_DELETE_WINDOW_LABEL": "Delete for everyone պատուհան",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} վրկ",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Պահպանեք արժեքը ամբողջ վայրկյաններով։ Ընթացիկ production արժեքը 86400 վայրկյան է = 1 օր։",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Պատուհանի վայրկյաններ",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Մուտքագրեք 0-ից մեծ կամ հավասար ամբողջ թիվ։",
    "CHAT_DELETE_SAVE_BUTTON": "Պահպանել ջնջման պատուհանը",
    "GUEST_BANNER_CONTROL_TITLE": "Հյուրի բաններ",
    "GUEST_BANNER_CONTROL_LABEL": "Հյուրի QR զրույց",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Ցուցադրել Հյուրի բանները բոլոր օգտատերերի համար",
    "GUEST_BANNER_CONTROL_HELPER": "Կառավարում է Հյուրի ֆիքսված բանները և սպասվող QR նշանի գործողության ժամկետը։",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Հյուրի բանների կառավարման համար ակտիվ է տեղական պահուստային տարբերակը։",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Հյուրի բանների կառավարման կարգավորումները պահպանվել են։",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Հյուրի բանների կառավարման կարգավորումները չհաջողվեց պահպանել։",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} հյուրի սեանս չեղարկվեց։",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "Սպասվող QR-ի TTL (րոպե)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "Ընթացիկ սպասվող QR-ի TTL՝ {count} րոպե։",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Մուտքագրեք րոպեների դրական ամբողջ թիվ։",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Պահպանել Հյուրի բանները",
    "GUEST_QR_LOADING": "Հյուրի QR-ը պատրաստվում է...",
    "GUEST_QR_READY": "Սկանավորեք՝ ժամանակավոր Հյուրի զրույցը բացելու համար։",
    "GUEST_QR_ALT": "Հյուրի զրույցի QR կոդ",
    "GUEST_QR_LOAD_FAILED": "Հյուրի QR-ը չհաջողվեց պատրաստել։",
    "GUEST_SESSION_ACTIVE": "Հյուրը միացված է։",
    "GUEST_PUBLIC_TITLE": "Հյուրի զրույց",
    "GUEST_PUBLIC_CONNECTING": "Միանում է...",
    "GUEST_PUBLIC_CONNECTED": "Միացված է",
    "GUEST_PUBLIC_UNAVAILABLE": "Հյուրի այս հղումը հասանելի չէ։",
    "GUEST_PUBLIC_SEND_FAILED": "Հաղորդագրությունը չհաջողվեց ուղարկել:",
    "UI_TEXTS_RUNTIME_TITLE": "UI լեզվի գործարկման ժամանակ",
    "UI_TEXTS_RUNTIME_BACKEND": "UI լեզվի գործարկման ժամանակը կարդում է պաշտպանված բեքենդ ծառայությունից: Փոփոխությունները կկիրառվեն հավելվածի հաջորդ ամբողջական բեռնման ժամանակ:",
    "UI_TEXTS_RUNTIME_CACHED": "Բեքենդի UI լեզվի գործարկման ծառայությունն այս պահին անհասանելի է, ուստի ակտիվ են քեշավորված կամ տեղական լռելյայնները:",
    "UI_TEXTS_RUNTIME_DEFAULTS": "UI լեզվի գործարկման լռելյայնները ակտիվ են, քանի որ բեքենդ կամ քեշավորված վիճակ չի հաջողվել բեռնել:",
    "UI_TEXTS_RUNTIME_SAVED": "UI լեզվի գործարկման կառավարումը պահպանվեց: Օգտատերերի կողմից նոր լեզվական դարպասը ստանալու համար պահանջվում է ամբողջական թարմացում կամ հավելվածի հաջորդ բեռնում:",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Պաշտպանված բեքենդ ծառայությունը չկարողացավ պահպանել պահանջված UI լեզվի գործարկման ժամանակի փոփոխությունը:",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Սարքի լեզվի հավելված",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Միացնել գործարկման ժամանակի UI լեզուները",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Օգտատերերը կարող են ստանալ UI տեքստի բեռնվածքներ իրենց պահպանված կամ սարքի լեզվի համար:",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Բոլոր օգտատերերը ստիպված են օգտագործել անգլերեն UI տեքստը, և սարքի լեզուն անտեսվում է:",
    "PROFILE_VISIBILITY_TITLE": "Պրոֆիլի տեսանելիություն",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Հաշվի տեսանելիությունը կառավարելու համար պետք է մուտք գործած լինեք։",
    "PROFILE_VISIBILITY_HELPER": "Այս անջատիչը թարմացնում է միայն ձեր հաշվի տեսանելիության վիճակը։ Հայտնաբերելիությունը և բանների ցանկի վարքը այս փուլում մնում են անփոփոխ։",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Պրոֆիլի տեսանելիությունը հիմա չհաջողվեց բեռնել։",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Պրոֆիլի տեսանելիությունը հիմա չհաջողվեց թարմացնել։",
    "PROFILE_VISIBILITY_SAVED": "Ձեր հաշվի տեսանելիությունն այժմ {visibility} է։ Հայտնաբերելիության դրոշակները այս փուլում մնում են անփոփոխ։",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Հանրային հաշիվ",
    "PROFILE_VISIBILITY_STORED": "Պահված տեսանելիություն",
    "WF1_MODEL_CONTROL_TITLE": "WF1 մոդելի կառավարում",
    "WF1_ENABLE_TRANSLATION": "Միացնել թարգմանություն / Pivot",
    "WF1_TRANSLATION_ACTIVE": "AI թարգմանությունը ակտիվ է։",
    "WF1_TRANSLATION_INACTIVE": "WF1-ը շարունակում է աշխատել, բայց սկզբնաղբյուր տեքստը պատճենվում է, և pivot-ը նշվում է որպես ոչ ակտիվ։",
    "WF1_ACTIVE_RUNTIME_SLOT": "Ակտիվ runtime slot",
    "WF1_ALLOW_SAME_LANGUAGE": "Թույլատրել AI նույն լեզվական զույգերի համար",
    "WF1_SAME_LANGUAGE_ACTIVE": "Նույն լեզվական զույգերը հետևում են սովորական WF1 routing-ին։",
    "WF1_SAME_LANGUAGE_INACTIVE": "Նույն լեզվական զույգերը շրջանցում են AI-ն և պահում No Pivot language active։",
    "WF1_QWEN_ROUTING": "Qwen զույգերի routing",
    "WF1_QWEN_ROUTING_HELPER": "Ստորև նշված լեզուները օգտագործում են Qwen-Max, երբ զույգը կամ նույն նշված լեզուն է, կամ նշված լեզու անգլերենի հետ, կամ երկու նշված ոչ անգլերեն լեզու։ Հակառակ դեպքում ընտրված հիմնական մոդելը մնում է ակտիվ։",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter թեստային slot",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter թեստային slot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Միայն որակի թեստ",
    "WF1_OPENROUTER_HELPER": "Այս slot-ը խմբագրելի է միայն ժամանակավոր OpenRouter որակի թեստերի համար։ Այն չի փոխում Qwen զույգերի գործառնական routing ուղին, եթե այս slot-ը ինքնին չի դառնում ակտիվ մոդել։",
    "WF1_LABEL": "Պիտակ",
    "WF1_PRODUCT": "Ապրանք",
    "WF1_MODEL": "Մոդել",
    "WF1_PROVIDER_OPENROUTER": "Մատակարար՝ OpenRouter",
    "WF1_SECRET_OPENROUTER": "Գաղտնիք՝ OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter թեստային slot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max OpenRouter-ի միջոցով",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google ցուցակային գին",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI ցուցակային գին",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter ցուցակային գին",
    "LANGUAGE_ENGLISH": "Անգլերեն",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Չինարեն (պարզեցված)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Չինարեն (ավանդական)",
    "LANGUAGE_JAPANESE": "Ճապոներեն",
    "LANGUAGE_KOREAN": "Կորեերեն",
    "LANGUAGE_PERSIAN": "Պարսկերեն",
    "LANGUAGE_TURKISH_ISTANBUL": "Թուրքերեն (Ստամբուլ)",
    "LANGUAGE_ARABIC": "Արաբերեն",
    "LANGUAGE_FRENCH": "Ֆրանսերեն",
    "LANGUAGE_GERMAN": "Գերմաներեն",
    "LANGUAGE_SPANISH": "Իսպաներեն",
    "LANGUAGE_PORTUGUESE": "Պորտուգալերեն",
    "LANGUAGE_ITALIAN": "Իտալերեն",
    "LANGUAGE_RUSSIAN": "Ռուսերեն",
    "LANGUAGE_DUTCH": "Հոլանդերեն",
    "LANGUAGE_VIETNAMESE": "Վիետնամերեն",
    "LANGUAGE_INDONESIAN": "Ինդոնեզերեն",
    "LANGUAGE_THAI": "Թայերեն",
    "LANGUAGE_MALAY": "Մալայերեն",
    "WF1_PRICING_CUSTOM": "Գնագոյացում՝ custom slot մոդել - ստուգեք OpenRouter-ի ընթացիկ գինը",
    "WF1_SAVE_OPENROUTER_SLOT": "Պահպանել OpenRouter slot-ը",
    "WF1_PRICING_LINE": "Մուտք {input} - Ելք {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Գաղտնիք՝ {secret}",
    "ZONE_VISIBILITY_TITLE": "Գոտու տեսանելիության կառավարում",
    "ZONE_ENABLE": "Միացնել {zone}",
    "ZONE_ENABLED_NOTE": "{zone}-ը կարող է երևալ թույլատրված դերերի համար հավելվածի հաջորդ բեռնումից հետո։",
    "ZONE_DISABLED_NOTE": "{zone}-ը ոչ S_Admin օգտատերերի համար դիտվում է որպես բացակայող հավելվածի հաջորդ բեռնումից հետո։",
    "ZONE_S_ADMIN_BYPASS": "S_Admin-ը շրջանցում է այս դերերի ցանկը և միշտ պահպանում է հասանելիությունը։",
    "ZONE_ROLE_LOCKED": "Դերերի ընտրությունները ժամանակավորապես կողպված են, քանի դեռ այս գոտին անջատված է, և կվերադառնան ճիշտ այնպես, ինչպես պահպանվել են, երբ գոտին կրկին միացվի։",
    "ZONE_LCAC_CONTROL": "LCAC կառավարում",
    "ZONE_RCAC_CONTROL": "RCAC կառավարում",
    "ZONE_LCAC_DESCRIPTION": "Կառավարում է ձախ պահված գոտու գոյությունը և այն դերերը, որոնք կարող են տեսնել այն։",
    "ZONE_RCAC_DESCRIPTION": "Կառավարում է աջ պահված գոտու գոյությունը և այն դերերը, որոնք կարող են տեսնել այն։",
    "ZONE_VISIBILITY_BACKEND": "Գոտու տեսանելիության bootstrap-ը հիմա կարդում է պաշտպանված backend ծառայությունից։ Փոփոխությունները կիրառվում են հավելվածի հաջորդ բեռնումից հետո։",
    "ZONE_VISIBILITY_CACHED": "Backend zone visibility ծառայությունը հիմա անհասանելի է, ուստի ակտիվ են քեշավորված կամ տեղային լռելյայնները։",
    "ZONE_VISIBILITY_DEFAULTS": "Գոտու տեսանելիության լռելյայնները ակտիվ են, քանի որ backend կամ քեշավորված վիճակ չհաջողվեց բեռնել։",
    "ZONE_VISIBILITY_SAVED": "Գոտու տեսանելիության bootstrap-ը պահպանվեց։ Runtime կիրառման համար պահանջվում է կոշտ վերաբեռնում կամ հավելվածի հաջորդ բեռնում։",
    "ZONE_VISIBILITY_SAVE_FAILED": "Պաշտպանված backend ծառայությունը չկարողացավ պահպանել պահանջված գոտու տեսանելիության փոփոխությունը։",
    "ROLE_MEMBER": "Անդամ",
    "ROLE_STAFF": "Աշխատակազմ",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Միացրեք ծանուցումները՝ նոր հաղորդագրություններ ստանալու համար։",
    "MAIN_LOG_OUT": "Դուրս գալ",
    "NOTIFICATION_NEW_MESSAGE": "Նոր հաղորդագրություն",
    "NOTIFICATION_UNREAD_MESSAGE": "Դուք ունեք չկարդացված հաղորդագրություն։",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Ամբողջական դիտում",
    "MEDIA_AUDIO_ATTACHMENT": "Աուդիո կցորդ",
    "MEDIA_FILE_FALLBACK": "Ֆայլ",
    "MEDIA_DOWNLOAD_READY": "Կցորդը պատրաստ է ներբեռնման",
    "MEDIA_TYPE_UNSUPPORTED": "Տեսակը չի աջակցվում ամբողջական դիտման համար",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Նախորդ պատկեր",
    "MEDIA_NEXT_IMAGE_ARIA": "Հաջորդ պատկեր",
    "MEDIA_OPEN_ORIGINAL": "Բացել բնօրինակը",
    "MEDIA_DOWNLOAD": "Ներբեռնել",
    "MEDIA_CLOSE_ARIA": "Փակել",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name}-ի պրոֆիլի նկար",
    "MEDIA_PROFILE_ALT": "{name}-ի պրոֆիլ",
    "MEDIA_UPLOAD_FAILED": "Վերբեռնումը ձախողվեց",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend token-ի սխալ",
    "MEDIA_UPLOAD_URL_MISSING": "Կրիտիկական՝ վերբեռնման URL-ը բացակայում է backend-ի պատասխանում։",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Զրույցի վերբեռնման համար auth token-ը բացակայում է",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Զրույցի վերբեռնման token-ի հարցումը ձախողվեց",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Զրույցի վերբեռնման անվավեր պատասխան",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS վերբեռնումը ձախողվեց",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Ֆայլի անունը կամ contentType-ը բացակայում է",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path-ը բացակայում է",
    "BLOCK_NOTICE_TITLE": "Մշտական արգելափակման ծանուցում",
    "BLOCK_NOTICE_MESSAGE": "Ձեր հաշիվը ժամանակավորապես կասեցվել է քաղաքականության խախտման պատճառով։",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Եթե կարծում եք, որ սա պահանջում է հետագա կապ, խնդրում ենք կապվել",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "էլ. փոստով։",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Անհայտ օգտատեր",
    "GENERAL_GUEST": "Հյուր",
    "ADVISOR_FOR_CLIENT": "Խորհրդատու {client_display_name}-ի համար",
    "GUEST_FOR_CLIENT": "Հյուր {client_display_name}-ի համար",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token-ը և գաղտնաբառը պարտադիր են",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Հարցման մարմինը պետք է լինի JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Հրավերի token-ը անվավեր է կամ ժամկետանց",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Գաղտնաբառի սահմանումը ձախողվեց՝ session-ը կամ օգտատերը բացակայում է",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Գաղտնաբառի սահմանումը ձախողվեց մուտք գործելու ընթացքում",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Admin token-ի ստեղծումը ձախողվեց",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Մուտքը ձախողվեց՝ session-ը կամ օգտատերը բացակայում է",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Գրանցումը հաջողվեց։ Խնդրում ենք ստուգել էլ. փոստը հաստատման համար։",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Գրանցման անհայտ ձախողում",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Token-ի անվավեր մշակում",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Access token-ը պարտադիր է",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Token hash preview-ի համար անհրաժեշտ է email hint redirect URL-ից",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Այս token-ի համար ինքնությունը որոշել հնարավոր չէ",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Միայն User Zero-ն կարող է մուտք գործել WF1 LLM selector ծառայություն։",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Միայն User Zero-ն կարող է մուտք գործել գոտու տեսանելիության կառավարման ծառայություն։",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Միայն User Zero-ն կարող է մուտք գործել frontend տարբերակի կառավարման ծառայություն։",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Միայն User Zero-ն կարող է ստուգել այլ օգտատիրոջ frontend տարբերակը։",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Միայն User Zero-ն կարող է մուտք գործել զրույցի ջնջման կառավարման ծառայություն։",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Միայն User Zero-ն կարող է մուտք գործել UI լեզվի գործարկման կառավարման ծառայություն:",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Միայն User Zero-ն կարող է ընդմիշտ ջնջել օգտատիրոջ հաշիվը։",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Հարցման անվավեր payload։",
    "API_ERROR_INTERNAL_SERVER": "Սերվերի ներքին սխալ",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Ֆունկցիան բացակայում է backend-ում (վերաբեռնումը պարտադիր է)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "delivered/read անցումների համար թույլատրված է միայն DB RPC։",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Խնդրում ենք սպասել նախքան մեկ այլ հաղորդագրություն ուղարկելը։",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Հաղորդագրությունը հաջողությամբ ուղարկվեց։",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Կապի ծառայությունը անհասանելի է։",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Հաղորդագրության ուղարկումը ձախողվեց։",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Անունը պարտադիր է։",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Էլ. փոստը անվավեր է։",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Հաղորդագրությունը պարտադիր է։",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Selector payload-ը պարտադիր է։",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Գոտու տեսանելիության payload-ը պարտադիր է։",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Frontend տարբերակի payload-ը պարտադիր է։",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Զրույցի ջնջման կառավարման payload-ը պարտադիր է։",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Պահանջվում է UI լեզվի գործարկման կառավարման բեռնվածք:",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Նույնականացված օգտատիրոջ id-ն պարտադիր է։",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Նույնականացված դիտողի օգտատիրոջ id-ն պարտադիր է։",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Նույնականացված գործող օգտատիրոջ id-ն պարտադիր է։",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id-ը պարտադիր է։",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id-ը պարտադիր է։",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids ցանկը պարտադիր է։",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email-ը պարտադիր է։",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by-ը պարտադիր է։",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Search runtime-ը անջատված է գլոբալ frontend տարբերակով։",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Ձեզ չի թույլատրվում չեղարկել այս սպասող հրավերը։",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Այս հրավերն այլևս չի կարող չեղարկվել, քանի որ օգտատերը արդեն գրանցված է։",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Սպասող հրավերը չի գտնվել։",
    "INVITE_REPLY_ALREADY_MEMBER": "Շնորհավորում ենք, ձեր ընկերը ({invitee_email}) արդեն գրանցված է այս հավելվածում և այս workspace-ի անդամ է։",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "{invitee_email}-ի համար հրավեր է սպասվում, բայց retry email-ը չհաջողվեց գործարկել։ Խնդրում ենք ստուգել mail logs-ը։",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Հրավերի գրառումը ստեղծվեց {invitee_email}-ի համար, բայց email delivery-ը չհաջողվեց հաստատել։ Խնդրում ենք ավելի ուշ կրկին փորձել կամ ստուգել mail logs-ը։",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Հրավերի գրառումը ստեղծել չհաջողվեց։ Խնդրում ենք ավելի ուշ կրկին փորձել։",
    "INVITE_REPLY_SYSTEM_ERROR": "Հրավերի գործընթացի ընթացքում համակարգային սխալ՝ {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend Configuration Error՝ Supabase credentials-ը բացակայում է",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend Configuration Error՝ անվավեր Supabase URL",
    "CHAT_ERROR_ACCESS_DENIED": "Հասանելիությունը մերժված է",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Տեքստային հաղորդագրությունների համար բովանդակությունը չի կարող դատարկ լինել",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Conversation ID-ն որոշել չհաջողվեց",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC auth context-ը բացակայում է",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC-ն վերադարձրել է անվավեր message payload",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Insert-ը ձախողվեց, տվյալներ չեն վերադարձվել",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations-ը պետք է լինի list",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Անվավեր operation payload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Չաջակցվող operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id-ը պարտադիր է",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Հաղորդագրությունը չի գտնվել",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Ջնջումը թույլատրված է միայն ձեր սեփական հաղորդագրության վրա",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Delete for everyone-ն այլևս հասանելի չէ այս հաղորդագրության համար",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Delete for everyone-ը ձախողվեց",
    "API_ERROR_SERVER_CONFIGURATION": "Սերվերի կարգավորման սխալ",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Webhook secret header-ը բացակայում է",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Չարտոնված webhook source",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend-ի կարգավորման սխալ",
    "API_ERROR_MODULE_ATTRIBUTE": "Module Attribute Error՝ {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Սպասող auth օգտատիրոջը հեռացնելիս ձախողվեց նախքան հրավերի ջնջումը։",
    "CHAT_ERROR_DB": "DB Error՝ {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "PERMISSION_MIC_PERMISSION": "",
    "PERMISSION_MIC_ACCESS": "",
    "PERMISSION_TOGGLE_MIC_ARIA": "",
    "PERMISSION_MIC_ON_TOOLTIP": "",
    "PERMISSION_MIC_ENABLE_TOOLTIP": "",
    "PERMISSION_MIC_BLOCKED_TOOLTIP": "",
    "PERMISSION_MIC_DISABLE_HELP": "",
    "PERMISSION_MIC_BLOCKED_HELP": "",
    "LIVE_CONV_MIC_PROMPT_TITLE": "",
    "LIVE_CONV_MIC_PROMPT_BODY": "",
    "LIVE_CONV_MIC_PROMPT_ALLOW": "",
    "LIVE_CONV_MIC_PROMPT_CANCEL": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
