# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/id.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Utama",
    "APP_TITLE": "Platform AI OTMEGA",
    "APP_SUBTITLE": "Penasihat AI",
    "CHAT_PLACEHOLDER": "Ketik pesan Anda...",
    "CHAT_SEND_BUTTON": "Kirim",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Penasihat dapat membuat kesalahan, jadi periksa kembali.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Obrolan Baru",
    "ICON_HISTORY": "Riwayat",
    "ICON_TEMPLATES": "Template",
    "ICON_SETTINGS": "Pengaturan",
    "ICON_USER_PROFILE": "Profil Pengguna",
    "ICON_QUICK_ACTIONS": "Tindakan Cepat",
    "ICON_PINNED": "Disematkan",
    "ICON_GALLERY": "Galeri",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Instal Aplikasi",
    "PWA_ANDROID_MSG": "Instal aplikasi ini di perangkat Anda untuk pengalaman yang lebih baik dan akses offline.",
    "PWA_IOS_MSG": "Untuk menginstal aplikasi ini di iPhone/iPad Anda:\n1. Ketuk tombol Bagikan di bawah\n2. Pilih 'Tambahkan ke Layar Utama'",
    "PWA_BTN_INSTALL": "Instal",
    "PWA_BTN_LATER": "Mungkin Nanti",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Masuk ke Jaringan Penasihat",
    "AUTH_HEADER_SIGNUP": "Buat Akun Terpadu Anda",
    "AUTH_HEADER_LOGIN_NETWORK": "Masuk ke Jaringan Penasihat",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Buat Akun Terpadu Anda",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Masuk",
    "AUTH_BUTTON_SIGNUP": "Buat Akun",
    "AUTH_BUTTON_GOOGLE": "Lanjutkan dengan Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Lupa Kata Sandi",
    "AUTH_BUTTON_SEND_RESET_LINK": "Kirim Tautan Reset",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Belum punya akun? Daftar",
    "AUTH_PROMPT_LOGIN": "Sudah punya akun? Masuk",
    "AUTH_HELPER_TEXT_SIGNUP": "Anda sedang membuat akun terpadu yang dapat digunakan untuk mengakses semua penasihat di platform ini.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Anda sedang membuat akun terpadu yang dapat digunakan untuk mengakses semua penasihat di platform ini.",
    "AUTH_HELPER_TEXT_LOGIN": "Gunakan akun yang sama (email/kata sandi atau Google) yang Anda gunakan untuk penasihat lain di jaringan ini.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Gunakan akun yang sama (email/kata sandi atau Google) yang Anda gunakan untuk penasihat lain di jaringan ini.",
    "AUTH_FORGOT_PASSWORD_LINK": "Lupa kata sandi Anda?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Reset Kata Sandi Anda",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Masukkan alamat email Anda dan kami akan mengirimkan tautan untuk mereset kata sandi Anda.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Email",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Sedang memasukkan Anda...",
    "AUTH_STATUS_LOADING_SIGNUP": "Sedang membuat akun Anda...",
    "AUTH_STATUS_LOADING_RESET": "Mengirim tautan reset...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Login berhasil! Memuat ulang...",
    "AUTH_STATUS_SUCCESS_RESET": "Tautan reset berhasil dikirim. Silakan periksa email Anda.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Tautan reset kata sandi berhasil dikirim. Silakan periksa email Anda.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Email atau kata sandi tidak valid.",
    "AUTH_ERROR_EMAIL_EXISTS": "Akun dengan email ini sudah ada di jaringan penasihat.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Akun dengan email ini sudah ada. Silakan masuk. Anda saat ini adalah anggota dari:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Akun dengan email ini sudah ada di jaringan penasihat. Silakan tutup jendela ini dan gunakan bagian 'Login' dengan email yang sama dan kata sandi sebelumnya.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Anda saat ini adalah anggota dari:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "Email dan kata sandi wajib diisi.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Akun dibuat tetapi gagal menyiapkan keanggotaan. Silakan hubungi dukungan.",
    "AUTH_ERROR_DEFAULT": "Terjadi kesalahan. Silakan coba lagi.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Payload kontrol banner tamu diperlukan.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Hanya User Zero yang dapat memperbarui kontrol banner tamu.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Gagal mengirim tautan reset. Silakan coba lagi.",
    "INVITE_REPLY_EMAIL_SENT": "Email undangan Collabra telah dikirim ke teman Anda di {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Email undangan Collabra telah dikirim ulang ke teman Anda di {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Tampilkan kata sandi",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Sembunyikan kata sandi",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Batal",
    "GENERAL_CLOSE": "Tutup",
    "GENERAL_SEND": "Kirim",
    "GENERAL_SEARCH": "Cari",
    "GENERAL_RESET": "Reset",
    "GENERAL_ENABLE": "Aktifkan",
    "GENERAL_LOADING": "Memuat...",
    "GENERAL_DELETE": "Hapus",
    "GENERAL_DELETING": "Menghapus...",
    "GENERAL_SAVE_PASSWORD": "Simpan Kata Sandi",
    "AUTH_REMEMBER_EMAIL_LABEL": "Ingat email",
    "GENERAL_SAVING": "Menyimpan...",
    "GENERAL_SENDING": "Mengirim...",
    "GENERAL_REMOVING": "Menghapus...",
    "GENERAL_CONFIRM_REMOVAL": "Konfirmasi Penghapusan",
    "GENERAL_EMPTY": "Kosong",
    "GENERAL_UNAVAILABLE": "Tidak tersedia",
    "GENERAL_ENABLED": "Diaktifkan",
    "GENERAL_DISABLED": "Dinonaktifkan",
    "GENERAL_GRANTED": "Diberikan",
    "GENERAL_DENIED": "Ditolak",
    "GENERAL_DEFAULT": "Default",
    "GENERAL_UNSUPPORTED": "Tidak didukung",
    "GENERAL_PUBLIC": "Publik",
    "GENERAL_PRIVATE": "Pribadi",
    "GENERAL_USERNAME": "Nama pengguna",
    "GENERAL_EMAIL": "Email",
    "GENERAL_YOU": "Anda",
    "GENERAL_USER": "Pengguna",
    "GENERAL_UNKNOWN": "Tidak diketahui",
    "GENERAL_VISITOR": "Pengunjung",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Banner Tidak Dikenal",
    "GENERAL_ADVISOR_BANNER": "Banner Penasihat",
    "GENERAL_NOT_AVAILABLE": "N/A",
    "GENERAL_NOT_SELECTED": "Belum Dipilih",
    "GENERAL_NO_EMAIL_FOUND": "Tidak ada email ditemukan",
    "GENERAL_USER_ZERO_ONLY": "Hanya User Zero",
    "GENERAL_CONNECTION_STATE": "Status Koneksi",
    "GENERAL_DISPLAY_ONLY": "Hanya tampilan",
    "GENERAL_TEXTAREA": "Area teks",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Obrolan (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Tindakan Cepat (RCAC)",
    "HEADER_CHANGE_STATUS": "Ubah Status",
    "HEADER_OT_COIN_BALANCE": "Saldo OT Coin",
    "HEADER_ALT_USER": "Pengguna",
    "STATUS_BUSY": "Sibuk",
    "STATUS_AWAY": "Tidak di tempat",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Tidak terlihat",
    "NETWORK_CHECKING_CONNECTION": "Memeriksa koneksi...",
    "NETWORK_ONLINE_LATENCY": "Online (Latensi: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Jaringan: Baik (ketuk untuk ping)",
    "CHAT_TARGET_ALT": "Target obrolan",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Cari...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Buka foto profil {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Input pesan",
    "CHAT_TOGGLE_VIEW_ARIA": "Alihkan tampilan",
    "CHAT_ADD_USER_ARIA": "Tambahkan pengguna",
    "CHAT_ATTACH_ARIA": "Lampirkan",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Kirim",
    "CHAT_SEARCH_ARIA": "Cari",
    "CHAT_OPEN_SEARCH_ARIA": "Buka pencarian",
    "CHAT_CLOSE_SEARCH_ARIA": "Tutup pencarian",
    "CHAT_ATTACHMENT_ALT": "Lampiran",
    "CHAT_PREVIEW_ALT": "Pratinjau",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Hapus lampiran",
    "CHAT_REPLYING_TO": "Membalas kepada",
    "CHAT_CANCEL_REPLY_ARIA": "Batalkan balasan",
    "CHAT_UPLOADING": "Mengunggah...",
    "CHAT_LOADING_CHATS": "Memuat Obrolan...",
    "CHAT_SEND_FAILED": "Pengiriman Gagal",
    "CHAT_SEND_FAILED_RETRY": "Pengiriman gagal. Silakan coba lagi.",
    "CHAT_RETRY": "Coba lagi",
    "CHAT_EDITED": "diedit",
    "CHAT_TYPING": "Mengetik",
    "CHAT_LOADING": "Memuat",
    "CHAT_PENDING_INVITATION": "Undangan tertunda",
    "CHAT_PENDING_INVITATION_MIN": "{count} mnt Undangan tertunda",
    "CHAT_PENDING_INVITATION_HR": "{count} jam Undangan tertunda",
    "CHAT_PENDING_INVITATION_DAY": "{count} hari Undangan tertunda",
    "CHAT_WAITING_FOR_YOU": "{label} - Menunggu Anda",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Menunggu penerimaan",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Akses mikrofon ditolak.",
    "CHAT_UPLOAD_FAILED": "Unggahan Gagal: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Unggahan memerlukan koneksi internet. Silakan coba lagi saat Anda online.",
    "CHAT_ERROR_AUTH": "Kesalahan Autentikasi",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nama file atau content_type tidak ada",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id atau target_id tidak ada",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id tidak ada untuk unggahan non-avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path avatar tidak valid",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Klien layanan Supabase tidak tersedia",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Ack baca avatar hanya valid dalam konteks obrolan penasihat",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Pesan alur avatar tidak ditemukan atau tidak memenuhi syarat untuk ack baca",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Gagal menyelesaikan pesan avatar sebagai telah dibaca",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 lampiran",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} lampiran",
    "CHAT_VOICE_NOTE": "Catatan Suara",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Obrolan tidak tersedia. Pengguna ini memblokir Anda.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Obrolan tidak tersedia. Anda memblokir pengguna ini.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Akses akun diblokir oleh kebijakan.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Obrolan tidak tersedia. Akun ini diblokir final oleh User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Obrolan tidak tersedia. Blokir timbal balik aktif.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Obrolan tidak tersedia karena kebijakan blokir.",
    "MESSAGE_PREVIEW_PHOTO": "Foto",
    "MESSAGE_PREVIEW_VOICE": "Pesan suara",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "File",
    "MESSAGE_PREVIEW_MESSAGE": "Pesan",
    "MESSAGE_PREVIEW_SYSTEM": "Pesan sistem",
    "MESSAGE_PREVIEW_NEW": "Pesan baru",
    "MESSAGE_UNKNOWN_FILE": "File Tidak Dikenal",
    "MESSAGE_AUDIO_ATTACHMENT": "Lampiran audio",
    "MESSAGE_FILE_ATTACHMENT": "Lampiran",
    "BANNER_INVITED_BY": "diundang oleh {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Hasil Pencarian",
    "SEARCH_QUERY_LABEL": "Kueri:",
    "SEARCH_LOADING_VISIBILITY": "Memuat visibilitas pencarian...",
    "SEARCH_NO_RESULTS": "Tidak ada hasil ditemukan dalam cakupan pencarian saat ini.",
    "SHARE_WITH_COLLABRA": "Bagikan dengan Collabra",
    "SHARE_SEND_TO": "Kirim ke",
    "SHARE_SELECT_ONE_BANNER": "Pilih satu banner",
    "SHARE_BANNER_LIST_ARIA": "Daftar banner",
    "SHARE_NO_MATCHING_BANNER": "Tidak ada banner yang cocok",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Tambahkan komentar...",
    "SHARE_RECENT_CHATS": "Obrolan terbaru",
    "SHARE_LEFT_LIST": "Daftar kiri",
    "SHARE_RIGHT_LIST": "Daftar kanan",
    "SHARE_UNTITLED_BANNER": "Banner tanpa judul",
    "SHARE_SHARED_CONTENT": "Konten yang dibagikan",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Konten yang dibagikan tidak dapat dibuka.",
    "SHARE_OPEN_BANNER_FAILED": "Tidak dapat membuka banner yang dipilih.",
    "SHARE_ONE_PHOTO_SELECTED": "1 foto dipilih",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} foto dipilih",
    "SHARE_ONE_FILE_SELECTED": "1 file dipilih",
    "SHARE_MANY_FILES_SELECTED": "{count} file dipilih",
    "FORWARD_MESSAGE_TITLE": "Teruskan Pesan",
    "FORWARD_SELECT_RECIPIENTS": "Pilih penerima",
    "FORWARD_NO_OTHER_BANNER": "Tidak ada banner lain tersedia.",
    "FORWARD_SEND_TO_COUNT": "Kirim ke {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Pilih setidaknya satu banner.",
    "FORWARD_FAILED_DEFAULT": "Penerusan gagal. Silakan coba lagi.",
    "FORWARD_PARTIAL_SENT": "{count} terkirim. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Pesan sumber untuk diteruskan tidak ditemukan",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Pesan ini belum memiliki konten yang dapat diteruskan",
    "FORWARD_DESTINATION_MISSING": "Tujuan penerusan tidak ada",
    "FORWARD_MESSAGE_PREVIEW": "Pesan yang diteruskan",
    "MENU_PASTE": "Tempel",
    "MENU_COPY": "Salin",
    "MENU_REPLY": "Balas",
    "MENU_FORWARD": "Teruskan",
    "MENU_REMOVE_INVITATION": "Hapus Undangan",
    "MENU_REMOVE_FROM_LIST": "Hapus Dari Daftar",
    "MENU_GOODBYE_GUEST": "Selamat Tinggal Tamu",
    "MENU_ADD_TO_LIST": "Tambahkan Ke Daftar",
    "MENU_REJECT_INVITATION": "Tolak Undangan",
    "MENU_FRONTEND_VERSION": "Versi Frontend",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Info Banner: {title}",
    "MENU_MESSAGE_BUBBLE": "Gelembung Pesan",
    "MENU_CHAT_CANVAS_HEADER": "Kanvas Obrolan - {zone}",
    "MENU_CANVAS_INFO": "Info Kanvas",
    "MENU_CHAT_CANVAS_SUBLABEL": "Area percakapan / permukaan obrolan saat ini",
    "MENU_INPUT_AREA_HEADER": "Area Input - {zone}",
    "MENU_INPUT_AREA_INFO": "Info Area Input: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Permukaan bawah untuk mengetik dan alat tindakan",
    "MENU_HEADER": "Header - {zone}",
    "MENU_HEADER_INFO": "Info Header: {title}",
    "MENU_HEADER_DESCRIPTION": "Navigasi atas dan kontrol halaman",
    "MENU_ZONE_HEADER": "Zona - {zone}",
    "MENU_ZONE_SPACE_INFO": "Info Ruang Zona",
    "MENU_EMPTY_LIST_SURFACE": "Permukaan kosong/daftar",
    "MENU_BLOCK": "Blokir",
    "MENU_UNBLOCK": "Buka blokir",
    "MENU_HIDE_IN_SEARCH": "Sembunyikan Dalam Pencarian",
    "MENU_UNHIDE_IN_SEARCH": "Tampilkan Dalam Pencarian",
    "MENU_VISIBLE_IN_SEARCH": "Terlihat Dalam Pencarian",
    "MENU_HIDDEN_IN_SEARCH": "Tersembunyi Dalam Pencarian",
    "MENU_VISIBLE_IN_USER_LIST": "Terlihat Dalam Daftar Pengguna",
    "MENU_HIDDEN_IN_USER_LIST": "Tersembunyi Dalam Daftar Pengguna",
    "MENU_NOT_BLOCKED": "Tidak Diblokir",
    "MENU_BLOCKED": "Diblokir",
    "MENU_FRONTEND_VERSION_LOADING": "Memuat...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Memuat nilai per-banner dari backend. Tidak ada opsi yang ditandai aktif sampai respons database tiba.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Nilai backend tidak dapat dimuat. Tidak ada opsi aktif tepercaya yang ditampilkan.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Nilai database per-banner eksplisit adalah {overrideVersion}. Default global adalah {globalDefaultVersion}. Pengguna target harus menyegarkan penuh atau membuka ulang aplikasi agar bootstrap startup menerapkannya.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Tidak ada nilai database per-banner eksplisit yang disimpan. FeV2.0.0 aktif secara default. Default global adalah {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Nilai database per-banner eksplisit aktif setelah aplikasi target dimuat ulang penuh",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Tidak ada nilai per-banner eksplisit yang disimpan; ini adalah status individual default FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Opsi ini juga sama dengan default global saat ini",
    "MENU_DELETE_PERMANENT_CONFIRM": "Hapus {target} secara permanen dari database? Ini menghapus akun, riwayat obrolan, dependensi, dan memaksa jalur undangan baru penuh untuk masuk kembali di masa mendatang.",
    "MENU_DELETE_PERMANENTLY": "Hapus Permanen",
    "MENU_REFRESH_PAGE": "Segarkan Halaman",
    "MENU_LOG_OFF": "Keluar",
    "MENU_HARD_RELOAD": "Muat Ulang Paksa",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Email (Pengguna Admin)",
    "AUTH_PASSWORD_PLACEHOLDER": "Kata Sandi",
    "AUTH_CONNECTING": "Menghubungkan...",
    "AUTH_SIGNING_OUT": "Keluar...",
    "AUTH_BACK_TO_LOGIN": "Kembali ke Login",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Respons server tidak valid: Token tidak ditemukan.",
    "AUTH_LOGIN_FAILED": "Login Gagal",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Kata sandi tidak cocok.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Kata sandi tidak cocok!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Kata sandi harus sama persis.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Kata Sandi Baru",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Konfirmasi Kata Sandi",
    "AUTH_CHANGE_PASSWORD": "Ubah Kata Sandi",
    "AUTH_SAVING_PASSWORD": "Menyimpan...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Kata sandi berhasil diperbarui.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Tidak dapat mengubah kata sandi saat ini.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Anda harus masuk untuk mengubah kata sandi Anda.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Alihkan visibilitas kata sandi baru",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Alihkan visibilitas konfirmasi kata sandi",
    "REGISTER_TITLE": "Selesaikan Pendaftaran",
    "REGISTER_SUBTITLE": "Silakan atur kata sandi Anda secara manual.",
    "REGISTER_CREATING_ACCOUNT": "Membuat Akun...",
    "REGISTER_FINISH_SETUP": "Selesaikan Penyiapan",
    "REGISTER_FAILED_SET_PASSWORD": "Gagal mengatur kata sandi",
    "INVITE_EMAIL_INSTRUCTION": "Silakan masukkan email undangan (Format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Undang",
    "INVITE_EMAIL_REQUIRED": "Silakan masukkan email undangan.",
    "INVITE_EMAIL_INVALID": "Format email tidak valid. Silakan gunakan: user@example.com",
    "PENDING_INVITATION_TITLE": "Undangan Tertunda",
    "PENDING_INVITATION_REMOVE_QUESTION": "Hapus undangan tertunda ini dari database?",
    "PENDING_INVITATION_KEEP": "Pertahankan Undangan",
    "PENDING_INVITATION_REMOVAL_FAILED": "Penghapusan gagal.",
    "REMOVE_FROM_LIST_TITLE": "Hapus Dari Daftar",
    "REMOVE_FROM_LIST_WARNING": "Hapus pengguna ini dari kedua daftar sekarang? Akses obrolan akan segera diputus. Satu-satunya jalur kembali adalah undangan baru.",
    "REMOVE_FROM_LIST_KEEP": "Pertahankan Pengguna Dalam Daftar",
    "REMOVE_FROM_LIST_FAILED": "Gagal menghapus dari daftar.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Pengaturan & Status Langsung",
    "PERMISSION_DIALOG_ARIA": "Pengaturan dan Status Langsung",
    "PERMISSION_TRIGGER_ARIA": "Pemicu popup pengaturan",
    "PERMISSION_CLOSE_ARIA": "Tutup popup izin",
    "PERMISSION_LIVE_STATUS": "Status Langsung",
    "PERMISSION_SYSTEM_PERMISSION": "Izin Sistem",
    "PERMISSION_APP_PUSH": "Push Aplikasi",
    "PERMISSION_LOCATION_PERMISSION": "Izin Lokasi",
    "PERMISSION_APP_LOCATION": "Lokasi Aplikasi",
    "PERMISSION_CONTROLS": "Kontrol Izin",
    "PERMISSION_PUSH_NOTIFICATIONS": "Notifikasi Push",
    "PERMISSION_LOCATION_ACCESS": "Akses Lokasi",
    "PERMISSION_IN_APP_SETTINGS": "Pengaturan Dalam Aplikasi",
    "PERMISSION_ALERT_SOUND": "Suara Peringatan",
    "PERMISSION_APP_BADGE": "Badge Aplikasi",
    "PERMISSION_PASSWORD_SETTINGS": "Pengaturan Kata Sandi",
    "PERMISSION_NAVIGATION_STATUS": "Status Navigasi",
    "PERMISSION_SELECTED_ZONE": "Zona Terpilih",
    "PERMISSION_STAGED_CHAT_BANNER": "Banner Obrolan Bertahap",
    "PERMISSION_CANVAS_CONTENT": "Konten Kanvas",
    "PERMISSION_YOUR_DEVICES": "Perangkat Anda ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Segarkan daftar perangkat",
    "PERMISSION_REFRESH_LIST": "Segarkan Daftar",
    "PERMISSION_NO_REGISTERED_DEVICES": "Tidak ada perangkat terdaftar ditemukan.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Ubah ukuran popup pengaturan",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Alihkan notifikasi push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Alihkan akses lokasi",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Alihkan suara peringatan",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Alihkan badge aplikasi",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Alihkan visibilitas profil",
    "PERMISSION_OFF_IN_V1": "Mati di v1",
    "PERMISSION_CHAT": "Obrolan",
    "PERMISSION_BANNER_LIST": "Daftar Banner",
    "PERMISSION_PUSH_DISABLED_V1": "Notifikasi push dinonaktifkan untuk rilis v1 Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Notifikasi push AKTIF untuk perangkat ini.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Notifikasi sistem diblokir. Ketuk untuk membuka bantuan pengaturan.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Aktifkan untuk meningkatkan keandalan pengiriman.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Untuk menonaktifkan notifikasi sistem, buka pengaturan notifikasi browser/situs Anda dan atur situs ini ke Blokir.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Untuk mengubah izin notifikasi sistem, buka pengaturan notifikasi browser/situs Anda dan atur situs ini ke Izinkan.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Akses lokasi AKTIF untuk pengurutan LCAC berbasis jarak dan penentuan posisi peta.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API Lokasi tidak didukung di lingkungan ini.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Akses lokasi diblokir. Ketuk untuk membuka bantuan pengaturan.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Aktifkan untuk mengizinkan pengurutan LCAC berbasis jarak yang presisi dan penentuan posisi peta dalam aplikasi.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Akses lokasi tidak didukung di lingkungan ini.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Untuk menonaktifkan akses lokasi, buka pengaturan lokasi browser/situs Anda dan atur situs ini ke Blokir.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Untuk mengaktifkan akses lokasi untuk pengurutan jarak dan penentuan posisi peta dalam aplikasi, buka pengaturan lokasi browser/situs Anda dan atur situs ini ke Izinkan.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Tidak dapat memuat perangkat terdaftar saat ini.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Memuat UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Memuat Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Memuat Backend...",
    "RUNTIME_LOADING": "Memuat...",
    "RUNTIME_LOADING_FROM_DATABASE": "Memuat Dari Database...",
    "RUNTIME_BACKEND_CONNECTED": "Backend Terhubung",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Fallback Cache Aktif",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback Default Aktif",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Default Fallback Aktif",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Menyimpan Melalui Backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Tersimpan Di Layanan Backend",
    "RUNTIME_SAVE_FAILED": "Penyimpanan Gagal",
    "RUNTIME_LOAD_FAILED": "Pemuatan Gagal",
    "RUNTIME_CONNECTED": "Terhubung",
    "RUNTIME_LOGIN_REQUIRED": "Login Diperlukan",
    "RUNTIME_SAVED": "Tersimpan",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI Siap - Runtime Tertunda",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Layanan selector backend terlindungi menolak atau tidak dapat menyimpan opsi model yang diminta.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Layanan selector backend terlindungi menolak atau tidak dapat menyimpan perubahan routing WF1 yang diminta.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selector sekarang membaca konfigurasi aktif, routing Qwen, dan opsi yang diizinkan dari layanan backend terlindungi.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Layanan selector backend tidak tersedia saat ini, jadi status selector cache terakhir digunakan.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Nilai default selector aktif karena tidak ada status backend atau cache yang dapat dimuat.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Layanan selector backend terlindungi memperbarui konfigurasi routing WF1 aktif dan menyegarkan cache domain runtime.",
    "FRONTEND_VERSION_TITLE": "Versi Frontend",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Selector ini mengontrol versi frontend aktif untuk semua pengguna. FeV2.0.0 aktif.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Selector ini membaca versi frontend aktif dari config_domain_registry. Runtime terselesaikan ke FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Konfigurasi frontend-version backend tidak dapat dimuat, jadi default kode FeV2.0.0 tetap aktif sampai bootstrap startup dapat membaca layanan terlindungi lagi.",
    "FRONTEND_VERSION_HELPER_SAVED": "Versi frontend aktif disimpan di config_domain_registry. Refresh penuh atau pemuatan aplikasi berikutnya menerapkan nilai runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Layanan kontrol frontend-version backend tidak dapat menyimpan versi global yang diminta.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Versi frontend aktif.",
    "CHAT_DELETE_WINDOW_TITLE": "Jendela Hapus Obrolan",
    "CHAT_DELETE_HELPER": "Nilai ini mengontrol jendela ketersediaan Hapus untuk semua orang dalam detik. Guard backend berubah segera setelah disimpan. Visibilitas gelembung berubah setelah refresh penuh atau pemuatan aplikasi berikutnya.",
    "CHAT_DELETE_HELPER_FALLBACK": "Layanan kontrol hapus obrolan backend tidak dapat dimuat, jadi default kode tetap aktif sampai bootstrap startup dapat membaca layanan terlindungi lagi.",
    "CHAT_DELETE_HELPER_SAVED": "Jendela ketersediaan Hapus untuk semua orang disimpan di config_domain_registry. Guard backend berubah segera. Visibilitas gelembung berubah setelah refresh penuh atau pemuatan aplikasi berikutnya.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Layanan kontrol hapus obrolan backend tidak dapat menyimpan nilai jendela yang diminta.",
    "CHAT_DELETE_WINDOW_LABEL": "Jendela Hapus untuk semua orang",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} dtk",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Simpan nilai dalam detik penuh. Nilai produksi saat ini adalah 86400 detik = 1 hari.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Detik Jendela",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Masukkan bilangan bulat lebih besar dari atau sama dengan 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Simpan Jendela Hapus",
    "GUEST_BANNER_CONTROL_TITLE": "Banner Tamu",
    "GUEST_BANNER_CONTROL_LABEL": "Obrolan QR Tamu",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Tampilkan banner tamu untuk semua pengguna",
    "GUEST_BANNER_CONTROL_HELPER": "Mengontrol banner tamu tetap dan masa aktif token QR yang tertunda.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Fallback lokal aktif untuk kontrol banner tamu.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Kontrol banner tamu disimpan.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Kontrol banner tamu tidak dapat disimpan.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} sesi tamu dicabut.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "TTL QR Tertunda (menit)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "TTL QR tertunda saat ini: {count} menit.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Masukkan bilangan bulat positif dalam menit.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Simpan Banner Tamu",
    "GUEST_QR_LOADING": "Menyiapkan QR Tamu...",
    "GUEST_QR_READY": "Pindai untuk membuka obrolan tamu sementara.",
    "GUEST_QR_ALT": "Kode QR obrolan tamu",
    "GUEST_QR_LOAD_FAILED": "QR Tamu tidak dapat disiapkan.",
    "GUEST_SESSION_ACTIVE": "Tamu terhubung.",
    "GUEST_PUBLIC_TITLE": "Obrolan Tamu",
    "GUEST_PUBLIC_CONNECTING": "Menyambungkan...",
    "GUEST_PUBLIC_CONNECTED": "Tersambung",
    "GUEST_PUBLIC_UNAVAILABLE": "Tautan Tamu ini tidak tersedia.",
    "GUEST_PUBLIC_SEND_FAILED": "Pesan tidak dapat dikirim.",
    "UI_TEXTS_RUNTIME_TITLE": "Runtime Bahasa UI",
    "UI_TEXTS_RUNTIME_BACKEND": "Runtime bahasa UI sedang membaca dari layanan backend yang dilindungi. Perubahan berlaku pada pemuatan aplikasi penuh berikutnya.",
    "UI_TEXTS_RUNTIME_CACHED": "Layanan runtime bahasa UI backend tidak tersedia saat ini, jadi cache atau default lokal aktif.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "Default runtime bahasa UI aktif karena tidak ada status backend atau cache yang dapat dimuat.",
    "UI_TEXTS_RUNTIME_SAVED": "Kontrol runtime bahasa UI telah disimpan. Penyegaran penuh atau pemuatan aplikasi berikutnya diperlukan agar pengguna dapat menerima gerbang bahasa baru.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Layanan backend yang dilindungi tidak dapat menyimpan perubahan runtime bahasa UI yang diminta.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Aplikasi bahasa perangkat",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Aktifkan bahasa UI runtime",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Pengguna dapat menerima muatan teks UI untuk bahasa yang tersimpan atau bahasa perangkat mereka.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Semua pengguna dipaksa menggunakan teks UI bahasa Inggris, dan bahasa perangkat diabaikan.",
    "PROFILE_VISIBILITY_TITLE": "Visibilitas Profil",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Anda harus masuk untuk mengelola visibilitas akun.",
    "PROFILE_VISIBILITY_HELPER": "Switch ini hanya memperbarui status visibilitas akun Anda. Kemampuan ditemukan dan perilaku daftar banner tetap tidak berubah pada fase ini.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Visibilitas profil tidak dapat dimuat saat ini.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Visibilitas profil tidak dapat diperbarui saat ini.",
    "PROFILE_VISIBILITY_SAVED": "Visibilitas akun Anda sekarang {visibility}. Flag kemampuan ditemukan tetap tidak berubah pada fase ini.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Akun Publik",
    "PROFILE_VISIBILITY_STORED": "Visibilitas Tersimpan",
    "WF1_MODEL_CONTROL_TITLE": "Kontrol Model WF1",
    "WF1_ENABLE_TRANSLATION": "Aktifkan Terjemahan / Pivot",
    "WF1_TRANSLATION_ACTIVE": "Terjemahan AI aktif.",
    "WF1_TRANSLATION_INACTIVE": "WF1 tetap berjalan tetapi teks sumber disalin dan pivot ditandai tidak aktif.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Slot Runtime Aktif",
    "WF1_ALLOW_SAME_LANGUAGE": "Izinkan AI Untuk Pasangan Bahasa Yang Sama",
    "WF1_SAME_LANGUAGE_ACTIVE": "Pasangan bahasa yang sama mengikuti routing WF1 normal.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Pasangan bahasa yang sama melewati AI dan menyimpan bahasa No Pivot aktif.",
    "WF1_QWEN_ROUTING": "Routing Pasangan Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Bahasa yang dicentang di bawah menggunakan Qwen-Max ketika pasangan adalah bahasa yang sama yang dicentang, bahasa yang dicentang dengan bahasa Inggris, atau dua bahasa non-Inggris yang dicentang. Jika tidak, model primer yang dipilih tetap aktif.",
    "WF1_OPENROUTER_TEST_SLOT": "Slot Uji OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Slot Uji OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Hanya Uji Kualitas",
    "WF1_OPENROUTER_HELPER": "Slot ini hanya dapat diedit untuk uji kualitas OpenRouter sementara. Slot ini tidak mengubah jalur operasional routing pasangan Qwen kecuali slot ini sendiri menjadi model aktif.",
    "WF1_LABEL": "Label",
    "WF1_PRODUCT": "Produk",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Penyedia: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Rahasia: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Slot Uji OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max via OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Harga daftar Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Harga daftar OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Harga daftar OpenRouter",
    "LANGUAGE_ENGLISH": "Inggris",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Tionghoa (Sederhana)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Tionghoa (Tradisional)",
    "LANGUAGE_JAPANESE": "Jepang",
    "LANGUAGE_KOREAN": "Korea",
    "LANGUAGE_PERSIAN": "Persia",
    "LANGUAGE_TURKISH_ISTANBUL": "Turki (Istanbul)",
    "LANGUAGE_ARABIC": "Arab",
    "LANGUAGE_FRENCH": "Prancis",
    "LANGUAGE_GERMAN": "Jerman",
    "LANGUAGE_SPANISH": "Spanyol",
    "LANGUAGE_PORTUGUESE": "Portugis",
    "LANGUAGE_ITALIAN": "Italia",
    "LANGUAGE_RUSSIAN": "Rusia",
    "LANGUAGE_DUTCH": "Belanda",
    "LANGUAGE_VIETNAMESE": "Vietnam",
    "LANGUAGE_INDONESIAN": "Indonesia",
    "LANGUAGE_THAI": "Thai",
    "LANGUAGE_MALAY": "Melayu",
    "WF1_PRICING_CUSTOM": "Harga: model slot khusus - periksa harga OpenRouter saat ini",
    "WF1_SAVE_OPENROUTER_SLOT": "Simpan Slot OpenRouter",
    "WF1_PRICING_LINE": "Input {input} - Output {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Rahasia: {secret}",
    "ZONE_VISIBILITY_TITLE": "Kontrol Visibilitas Zona",
    "ZONE_ENABLE": "Aktifkan {zone}",
    "ZONE_ENABLED_NOTE": "{zone} dapat muncul untuk peran yang diizinkan setelah pemuatan aplikasi berikutnya.",
    "ZONE_DISABLED_NOTE": "{zone} diperlakukan sebagai tidak ada untuk pengguna non-S_Admin setelah pemuatan aplikasi berikutnya.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin melewati daftar peran ini dan selalu mempertahankan akses.",
    "ZONE_ROLE_LOCKED": "Pilihan peran dikunci sementara saat zona ini dinonaktifkan dan akan kembali persis seperti yang disimpan ketika zona diaktifkan kembali.",
    "ZONE_LCAC_CONTROL": "Kontrol LCAC",
    "ZONE_RCAC_CONTROL": "Kontrol RCAC",
    "ZONE_LCAC_DESCRIPTION": "Mengontrol keberadaan zona cadangan kiri dan peran yang dapat melihatnya.",
    "ZONE_RCAC_DESCRIPTION": "Mengontrol keberadaan zona cadangan kanan dan peran yang dapat melihatnya.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap visibilitas zona sekarang membaca dari layanan backend terlindungi. Perubahan berlaku pada pemuatan aplikasi berikutnya.",
    "ZONE_VISIBILITY_CACHED": "Layanan visibilitas zona backend tidak tersedia saat ini, jadi default cache atau lokal aktif.",
    "ZONE_VISIBILITY_DEFAULTS": "Default visibilitas zona aktif karena tidak ada status backend atau cache yang dapat dimuat.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap visibilitas zona telah disimpan. Muat ulang paksa atau pemuatan aplikasi berikutnya diperlukan untuk penerapan runtime.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Layanan backend terlindungi tidak dapat menyimpan perubahan visibilitas zona yang diminta.",
    "ROLE_MEMBER": "Anggota",
    "ROLE_STAFF": "Staf",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Aktifkan notifikasi untuk menerima pesan baru.",
    "MAIN_LOG_OUT": "Keluar",
    "NOTIFICATION_NEW_MESSAGE": "Pesan baru",
    "NOTIFICATION_UNREAD_MESSAGE": "Anda memiliki pesan yang belum dibaca.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Tampilan Penuh",
    "MEDIA_AUDIO_ATTACHMENT": "Lampiran audio",
    "MEDIA_FILE_FALLBACK": "File",
    "MEDIA_DOWNLOAD_READY": "Lampiran siap diunduh",
    "MEDIA_TYPE_UNSUPPORTED": "Tipe tidak didukung untuk tampilan penuh",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Gambar sebelumnya",
    "MEDIA_NEXT_IMAGE_ARIA": "Gambar berikutnya",
    "MEDIA_OPEN_ORIGINAL": "Buka Asli",
    "MEDIA_DOWNLOAD": "Unduh",
    "MEDIA_CLOSE_ARIA": "Tutup",
    "MEDIA_PROFILE_PICTURE_ARIA": "Foto profil {name}",
    "MEDIA_PROFILE_ALT": "Profil {name}",
    "MEDIA_UPLOAD_FAILED": "Unggahan gagal",
    "MEDIA_BACKEND_TOKEN_ERROR": "Kesalahan Token Backend",
    "MEDIA_UPLOAD_URL_MISSING": "Kritis: URL unggahan tidak ada dalam respons backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Token autentikasi tidak ada untuk unggahan obrolan",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Permintaan token unggahan obrolan gagal",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Respons unggahan obrolan tidak valid",
    "MEDIA_GCS_UPLOAD_FAILED": "Unggahan GCS Gagal",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nama file atau contentType tidak ada",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path tidak ada",
    "BLOCK_NOTICE_TITLE": "Pemberitahuan Blokir Permanen",
    "BLOCK_NOTICE_MESSAGE": "Akun Anda telah ditangguhkan sementara karena pelanggaran kebijakan.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Jika Anda yakin hal ini memerlukan tindak lanjut, silakan hubungi",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "melalui email.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Pengguna Tidak Dikenal",
    "GENERAL_GUEST": "Tamu",
    "ADVISOR_FOR_CLIENT": "Penasihat untuk {client_display_name}",
    "GUEST_FOR_CLIENT": "Tamu untuk {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token dan kata sandi wajib diisi",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Body permintaan harus JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Token undangan tidak valid atau kedaluwarsa",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Pengaturan kata sandi gagal: sesi atau pengguna tidak ada",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Pengaturan kata sandi gagal saat sign-in",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Pembuatan token admin gagal",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Login gagal: sesi atau pengguna tidak ada",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Pendaftaran berhasil. Silakan periksa email untuk verifikasi.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Pendaftaran gagal tidak diketahui",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Pemrosesan token tidak valid",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Token akses wajib ada",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Pratinjau hash token memerlukan petunjuk email dari URL pengalihan",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Tidak dapat menyelesaikan identitas untuk token ini",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Hanya User Zero yang dapat mengakses layanan selector LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Hanya User Zero yang dapat mengakses layanan kontrol visibilitas zona.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Hanya User Zero yang dapat mengakses layanan kontrol versi frontend.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Hanya User Zero yang dapat memeriksa versi frontend pengguna lain.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Hanya User Zero yang dapat mengakses layanan kontrol hapus obrolan.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Hanya User Zero yang dapat mengakses layanan kontrol runtime bahasa UI.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Hanya User Zero yang dapat menghapus akun pengguna secara permanen.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Payload permintaan tidak valid.",
    "API_ERROR_INTERNAL_SERVER": "Kesalahan Server Internal",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Fungsi tidak ada di backend (Muat Ulang Diperlukan)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Hanya DB RPC yang diizinkan untuk transisi delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Silakan tunggu sebelum mengirim pesan lain.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Pesan berhasil dikirim.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Layanan kontak tidak tersedia.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Pengiriman pesan gagal.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Nama wajib diisi.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Email tidak valid.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Pesan wajib diisi.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload selector wajib ada.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload visibilitas zona wajib ada.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload versi frontend wajib ada.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload kontrol hapus obrolan wajib ada.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Muatan kontrol runtime bahasa UI diperlukan.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID pengguna terautentikasi wajib ada.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID pengguna viewer terautentikasi wajib ada.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID pengguna aktor terautentikasi wajib ada.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id wajib ada.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id wajib ada.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Daftar owner_user_ids wajib ada.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email wajib ada.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by wajib ada.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime pencarian dinonaktifkan oleh versi frontend global.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Anda tidak diizinkan membatalkan undangan tertunda ini.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Undangan ini tidak dapat lagi dibatalkan karena pengguna sudah terdaftar.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Undangan tertunda tidak ditemukan.",
    "INVITE_REPLY_ALREADY_MEMBER": "Selamat, teman Anda ({invitee_email}) sudah terdaftar di aplikasi ini dan menjadi anggota ruang kerja ini.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Undangan tertunda untuk {invitee_email}, tetapi email percobaan ulang tidak dapat dipicu. Silakan periksa log email.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Catatan undangan telah dibuat untuk {invitee_email}, tetapi pengiriman email tidak dapat dikonfirmasi. Silakan coba lagi nanti atau periksa log email.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Gagal membuat catatan undangan. Silakan coba lagi nanti.",
    "INVITE_REPLY_SYSTEM_ERROR": "Kesalahan Sistem selama proses undangan: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Kesalahan Konfigurasi Backend: Kredensial Supabase tidak ada",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Kesalahan Konfigurasi Backend: URL Supabase tidak valid",
    "CHAT_ERROR_ACCESS_DENIED": "Akses Ditolak",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Konten tidak boleh kosong untuk pesan teks",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Tidak dapat menentukan ID percakapan",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Konteks autentikasi RPC tidak ada",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC mengembalikan payload pesan yang tidak valid",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Insert gagal, tidak ada data yang dikembalikan",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations harus berupa daftar",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Payload operasi tidak valid",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type tidak didukung",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id wajib ada",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Pesan tidak ditemukan",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Hapus hanya diizinkan pada pesan Anda sendiri",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Hapus untuk semua orang tidak lagi tersedia untuk pesan ini",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Hapus untuk semua orang gagal",
    "API_ERROR_SERVER_CONFIGURATION": "Kesalahan konfigurasi server",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Header rahasia webhook tidak ada",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Sumber webhook tidak sah",
    "API_ERROR_BACKEND_CONFIGURATION": "Kesalahan konfigurasi backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Kesalahan Atribut Modul: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Gagal sebelum penghapusan undangan saat menghapus pengguna auth yang menunggu.",
    "CHAT_ERROR_DB": "Kesalahan DB: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
