# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/it.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Principale",
    "APP_TITLE": "Piattaforma IA OTMEGA",
    "APP_SUBTITLE": "Consulente IA",
    "CHAT_PLACEHOLDER": "Scrivi il tuo messaggio...",
    "CHAT_SEND_BUTTON": "Invia",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Il consulente può commettere errori, quindi verifica le informazioni.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Nuova chat",
    "ICON_HISTORY": "Cronologia",
    "ICON_TEMPLATES": "Modelli",
    "ICON_SETTINGS": "Impostazioni",
    "ICON_USER_PROFILE": "Profilo utente",
    "ICON_QUICK_ACTIONS": "Azioni rapide",
    "ICON_PINNED": "Fissato",
    "ICON_GALLERY": "Galleria",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Installa app",
    "PWA_ANDROID_MSG": "Installa questa app sul tuo dispositivo per un'esperienza migliore e accesso offline.",
    "PWA_IOS_MSG": "Per installare questa app sul tuo iPhone/iPad:\n1. Tocca il pulsante Condividi qui sotto\n2. Seleziona Aggiungi alla schermata Home",
    "PWA_BTN_INSTALL": "Installa",
    "PWA_BTN_LATER": "Forse più tardi",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Accedi alla rete dei consulenti",
    "AUTH_HEADER_SIGNUP": "Crea il tuo account unificato",
    "AUTH_HEADER_LOGIN_NETWORK": "Accedi alla rete dei consulenti",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Crea il tuo account unificato",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Accedi",
    "AUTH_BUTTON_SIGNUP": "Crea account",
    "AUTH_BUTTON_GOOGLE": "Continua con Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Password dimenticata",
    "AUTH_BUTTON_SEND_RESET_LINK": "Invia link di reimpostazione",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Non hai un account? Registrati",
    "AUTH_PROMPT_LOGIN": "Hai già un account? Accedi",
    "AUTH_HELPER_TEXT_SIGNUP": "Stai creando un account unificato che puoi usare per accedere a tutti i consulenti di questa piattaforma.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Stai creando un account unificato che puoi usare per accedere a tutti i consulenti di questa piattaforma.",
    "AUTH_HELPER_TEXT_LOGIN": "Usa lo stesso account (email/password o Google) che hai usato per altri consulenti in questa rete.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Usa lo stesso account (email/password o Google) che hai usato per altri consulenti in questa rete.",
    "AUTH_FORGOT_PASSWORD_LINK": "Hai dimenticato la password?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Reimposta la password",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Inserisci il tuo indirizzo email e ti invieremo un link per reimpostare la password.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Email",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Accesso in corso...",
    "AUTH_STATUS_LOADING_SIGNUP": "Creazione del tuo account...",
    "AUTH_STATUS_LOADING_RESET": "Invio del link di reimpostazione...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Accesso riuscito! Ricaricamento...",
    "AUTH_STATUS_SUCCESS_RESET": "Link di reimpostazione inviato correttamente. Controlla la tua email.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Link per reimpostare la password inviato correttamente. Controlla la tua email.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Email o password non validi.",
    "AUTH_ERROR_EMAIL_EXISTS": "Esiste già un account con questa email nella rete dei consulenti.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Esiste già un account con questa email. Accedi. Attualmente sei membro di:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Esiste già un account con questa email nella rete dei consulenti. Chiudi questa finestra e usa la sezione Accedi con la stessa email e la tua password precedente.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Attualmente sei membro di:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "Email e password sono obbligatorie.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Account creato, ma configurazione dell'iscrizione non riuscita. Contatta il supporto.",
    "AUTH_ERROR_DEFAULT": "Si è verificato un errore. Riprova.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Il payload di controllo del banner ospite è obbligatorio.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Solo l'Utente Zero può aggiornare i controlli del banner ospite.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Invio del link di reimpostazione non riuscito. Riprova.",
    "INVITE_REPLY_EMAIL_SENT": "L'email di invito Collabra è stata inviata al tuo amico all'indirizzo {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "L'email di invito Collabra è stata reinviata al tuo amico all'indirizzo {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Mostra password",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Nascondi password",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Annulla",
    "GENERAL_CLOSE": "Chiudi",
    "GENERAL_SEND": "Invia",
    "GENERAL_SEARCH": "Cerca",
    "GENERAL_RESET": "Reimposta",
    "GENERAL_ENABLE": "Abilita",
    "GENERAL_LOADING": "Caricamento...",
    "GENERAL_DELETE": "Elimina",
    "GENERAL_DELETING": "Eliminazione...",
    "GENERAL_SAVE_PASSWORD": "Salva password",
    "AUTH_REMEMBER_EMAIL_LABEL": "Ricorda email",
    "GENERAL_SAVING": "Salvataggio...",
    "GENERAL_SENDING": "Invio...",
    "GENERAL_REMOVING": "Rimozione...",
    "GENERAL_CONFIRM_REMOVAL": "Conferma rimozione",
    "GENERAL_EMPTY": "Vuoto",
    "GENERAL_UNAVAILABLE": "Non disponibile",
    "GENERAL_ENABLED": "Abilitato",
    "GENERAL_DISABLED": "Disabilitato",
    "GENERAL_GRANTED": "Concesso",
    "GENERAL_DENIED": "Negato",
    "GENERAL_DEFAULT": "Predefinito",
    "GENERAL_UNSUPPORTED": "Non supportato",
    "GENERAL_PUBLIC": "Pubblico",
    "GENERAL_PRIVATE": "Privato",
    "GENERAL_USERNAME": "Nome utente",
    "GENERAL_EMAIL": "Email",
    "GENERAL_YOU": "Tu",
    "GENERAL_USER": "Utente",
    "GENERAL_UNKNOWN": "Sconosciuto",
    "GENERAL_VISITOR": "Visitatore",
    "GENERAL_PROFILE": "Profilo",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Banner sconosciuto",
    "GENERAL_ADVISOR_BANNER": "Banner del consulente",
    "GENERAL_NOT_AVAILABLE": "N/D",
    "GENERAL_NOT_SELECTED": "Non selezionato",
    "GENERAL_NO_EMAIL_FOUND": "Nessuna email trovata",
    "GENERAL_USER_ZERO_ONLY": "Solo User Zero",
    "GENERAL_CONNECTION_STATE": "Stato connessione",
    "GENERAL_DISPLAY_ONLY": "Solo visualizzazione",
    "GENERAL_TEXTAREA": "Area di testo",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Azioni rapide (RCAC)",
    "HEADER_CHANGE_STATUS": "Cambia stato",
    "HEADER_OT_COIN_BALANCE": "Saldo OT Coin",
    "HEADER_ALT_USER": "Utente",
    "STATUS_BUSY": "Occupato",
    "STATUS_AWAY": "Assente",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Invisibile",
    "NETWORK_CHECKING_CONNECTION": "Verifica connessione...",
    "NETWORK_ONLINE_LATENCY": "Online (latenza: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Rete: buona (tocca per ping)",
    "CHAT_TARGET_ALT": "Destinatario chat",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Cerca...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Apri la foto profilo di {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Campo messaggio",
    "CHAT_TOGGLE_VIEW_ARIA": "Cambia vista",
    "CHAT_ADD_USER_ARIA": "Aggiungi utente",
    "CHAT_ATTACH_ARIA": "Allega",
    "CHAT_MIC_ARIA": "Microfono",
    "CHAT_SEND_ARIA": "Invia",
    "CHAT_SEARCH_ARIA": "Cerca",
    "CHAT_OPEN_SEARCH_ARIA": "Apri ricerca",
    "CHAT_CLOSE_SEARCH_ARIA": "Chiudi ricerca",
    "CHAT_ATTACHMENT_ALT": "Allegato",
    "CHAT_PREVIEW_ALT": "Anteprima",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Rimuovi allegato",
    "CHAT_REPLYING_TO": "Risposta a",
    "CHAT_CANCEL_REPLY_ARIA": "Annulla risposta",
    "CHAT_UPLOADING": "Caricamento...",
    "CHAT_LOADING_CHATS": "Caricamento chat...",
    "CHAT_SEND_FAILED": "Invio non riuscito",
    "CHAT_SEND_FAILED_RETRY": "Invio non riuscito. Riprova.",
    "CHAT_RETRY": "Riprova",
    "CHAT_EDITED": "modificato",
    "CHAT_TYPING": "Sta scrivendo",
    "CHAT_LOADING": "Caricamento",
    "CHAT_PENDING_INVITATION": "Invito in sospeso",
    "CHAT_PENDING_INVITATION_MIN": "{count} min Invito in sospeso",
    "CHAT_PENDING_INVITATION_HR": "{count} h Invito in sospeso",
    "CHAT_PENDING_INVITATION_DAY": "{count} g Invito in sospeso",
    "CHAT_WAITING_FOR_YOU": "{label} - In attesa di te",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Accettazione in sospeso",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Accesso al microfono negato.",
    "CHAT_UPLOAD_FAILED": "Caricamento non riuscito: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Il caricamento richiede una connessione Internet. Riprova quando sei online.",
    "CHAT_ERROR_AUTH": "Errore di autenticazione",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nome file o content_type mancante",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id o target_id mancante",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id mancante per caricamento non avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path avatar non valido",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Client del servizio Supabase non disponibile",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "L'ack di lettura avatar è valido solo nel contesto chat consulente",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Messaggio del flusso avatar non trovato o non idoneo per ack di lettura",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Finalizzazione del messaggio avatar come letto non riuscita",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 allegato",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} allegati",
    "CHAT_VOICE_NOTE": "Nota vocale",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat non disponibile. Questo utente ti ha bloccato.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat non disponibile. Hai bloccato questo utente.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "L'accesso all'account è bloccato dalla policy.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat non disponibile. Questo account è bloccato definitivamente da User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat non disponibile. Il blocco reciproco è attivo.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat non disponibile a causa della policy di blocco.",
    "MESSAGE_PREVIEW_PHOTO": "Foto",
    "MESSAGE_PREVIEW_VOICE": "Messaggio vocale",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "File",
    "MESSAGE_PREVIEW_MESSAGE": "Messaggio",
    "MESSAGE_PREVIEW_SYSTEM": "Messaggio di sistema",
    "MESSAGE_PREVIEW_NEW": "Nuovo messaggio",
    "MESSAGE_UNKNOWN_FILE": "File sconosciuto",
    "MESSAGE_AUDIO_ATTACHMENT": "Allegato audio",
    "MESSAGE_FILE_ATTACHMENT": "Allegato",
    "BANNER_INVITED_BY": "invitato da {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Risultati di ricerca",
    "SEARCH_QUERY_LABEL": "Query:",
    "SEARCH_LOADING_VISIBILITY": "Caricamento visibilità ricerca...",
    "SEARCH_NO_RESULTS": "Nessun risultato trovato nell'ambito di ricerca corrente.",
    "SHARE_WITH_COLLABRA": "Condividi con Collabra",
    "SHARE_SEND_TO": "Invia a",
    "SHARE_SELECT_ONE_BANNER": "Seleziona un banner",
    "SHARE_BANNER_LIST_ARIA": "Elenco banner",
    "SHARE_NO_MATCHING_BANNER": "Nessun banner corrispondente",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Aggiungi un commento...",
    "SHARE_RECENT_CHATS": "Chat recenti",
    "SHARE_LEFT_LIST": "Elenco sinistro",
    "SHARE_RIGHT_LIST": "Elenco destro",
    "SHARE_UNTITLED_BANNER": "Banner senza titolo",
    "SHARE_SHARED_CONTENT": "Contenuto condiviso",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Impossibile aprire il contenuto condiviso.",
    "SHARE_OPEN_BANNER_FAILED": "Impossibile aprire il banner selezionato.",
    "SHARE_ONE_PHOTO_SELECTED": "1 foto selezionata",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} foto selezionate",
    "SHARE_ONE_FILE_SELECTED": "1 file selezionato",
    "SHARE_MANY_FILES_SELECTED": "{count} file selezionati",
    "FORWARD_MESSAGE_TITLE": "Inoltra messaggio",
    "FORWARD_SELECT_RECIPIENTS": "Seleziona destinatari",
    "FORWARD_NO_OTHER_BANNER": "Nessun altro banner disponibile.",
    "FORWARD_SEND_TO_COUNT": "Invia a {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Seleziona almeno un banner.",
    "FORWARD_FAILED_DEFAULT": "Inoltro non riuscito. Riprova.",
    "FORWARD_PARTIAL_SENT": "{count} inviati. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Messaggio sorgente non trovato per l'inoltro",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Questo messaggio non ha ancora contenuti inoltrabili",
    "FORWARD_DESTINATION_MISSING": "Destinazione dell'inoltro mancante",
    "FORWARD_MESSAGE_PREVIEW": "Messaggio inoltrato",
    "MENU_PASTE": "Incolla",
    "MENU_COPY": "Copia",
    "MENU_REPLY": "Rispondi",
    "MENU_FORWARD": "Inoltra",
    "MENU_REMOVE_INVITATION": "Rimuovi invito",
    "MENU_REMOVE_FROM_LIST": "Rimuovi dalla lista",
    "MENU_GOODBYE_GUEST": "Arrivederci ospite",
    "MENU_ADD_TO_LIST": "Aggiungi alla lista",
    "MENU_REJECT_INVITATION": "Rifiuta invito",
    "MENU_FRONTEND_VERSION": "Versione frontend",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Info banner: {title}",
    "MENU_MESSAGE_BUBBLE": "Bolla messaggio",
    "MENU_CHAT_CANVAS_HEADER": "Canvas chat - {zone}",
    "MENU_CANVAS_INFO": "Info canvas",
    "MENU_CHAT_CANVAS_SUBLABEL": "Area conversazione / superficie chat corrente",
    "MENU_INPUT_AREA_HEADER": "Area input - {zone}",
    "MENU_INPUT_AREA_INFO": "Info area input: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Superficie inferiore di digitazione e strumenti di azione",
    "MENU_HEADER": "Intestazione - {zone}",
    "MENU_HEADER_INFO": "Info intestazione: {title}",
    "MENU_HEADER_DESCRIPTION": "Navigazione superiore e controlli pagina",
    "MENU_ZONE_HEADER": "Zona - {zone}",
    "MENU_ZONE_SPACE_INFO": "Info spazio zona",
    "MENU_EMPTY_LIST_SURFACE": "Superficie vuota/lista",
    "MENU_BLOCK": "Blocca",
    "MENU_UNBLOCK": "Sblocca",
    "MENU_HIDE_IN_SEARCH": "Nascondi nella ricerca",
    "MENU_UNHIDE_IN_SEARCH": "Mostra nella ricerca",
    "MENU_VISIBLE_IN_SEARCH": "Visibile nella ricerca",
    "MENU_HIDDEN_IN_SEARCH": "Nascosto nella ricerca",
    "MENU_VISIBLE_IN_USER_LIST": "Visibile nella lista utenti",
    "MENU_HIDDEN_IN_USER_LIST": "Nascosto nella lista utenti",
    "MENU_NOT_BLOCKED": "Non bloccato",
    "MENU_BLOCKED": "Bloccato",
    "MENU_FRONTEND_VERSION_LOADING": "Caricamento...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Caricamento del valore per banner dal backend. Nessuna opzione viene marcata come attiva finché non arriva la risposta del database.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Impossibile caricare il valore backend. Nessuna opzione attiva attendibile viene mostrata.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Il valore esplicito per banner nel database è {overrideVersion}. Il valore globale predefinito è {globalDefaultVersion}. L'utente di destinazione deve aggiornare completamente o riaprire l'app perché il bootstrap di avvio lo applichi.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Nessun valore esplicito per banner è memorizzato. FeV2.0.0 è attivo per impostazione predefinita. Il valore globale predefinito è {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Il valore esplicito per banner diventa attivo dopo il ricaricamento completo dell'app di destinazione",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Nessun valore esplicito per banner è memorizzato; questo è lo stato individuale predefinito FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Questa opzione è anche uguale al valore globale predefinito corrente",
    "MENU_DELETE_PERMANENT_CONFIRM": "Eliminare definitivamente {target} dal database? Questo rimuove l'account, la cronologia chat, le dipendenze e impone un nuovo percorso di invito per rientri futuri.",
    "MENU_DELETE_PERMANENTLY": "Elimina definitivamente",
    "MENU_REFRESH_PAGE": "Aggiorna pagina",
    "MENU_LOG_OFF": "Disconnetti",
    "MENU_HARD_RELOAD": "Ricaricamento forzato",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Email (utente admin)",
    "AUTH_PASSWORD_PLACEHOLDER": "Password",
    "AUTH_CONNECTING": "Connessione...",
    "AUTH_SIGNING_OUT": "Disconnessione...",
    "AUTH_BACK_TO_LOGIN": "Torna all'accesso",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Risposta server non valida: nessun token trovato.",
    "AUTH_LOGIN_FAILED": "Accesso non riuscito",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Le password non corrispondono.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Le password non corrispondono!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Le password devono corrispondere esattamente.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nuova password",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Conferma password",
    "AUTH_CHANGE_PASSWORD": "Cambia password",
    "AUTH_SAVING_PASSWORD": "Salvataggio...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Password aggiornata correttamente.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Impossibile cambiare la password in questo momento.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Devi essere connesso per cambiare la password.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Attiva/disattiva visibilità nuova password",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Attiva/disattiva visibilità conferma password",
    "REGISTER_TITLE": "Completa registrazione",
    "REGISTER_SUBTITLE": "Imposta manualmente la tua password.",
    "REGISTER_CREATING_ACCOUNT": "Creazione account...",
    "REGISTER_FINISH_SETUP": "Completa configurazione",
    "REGISTER_FAILED_SET_PASSWORD": "Impostazione password non riuscita",
    "INVITE_EMAIL_INSTRUCTION": "Inserisci l'email dell'invitato (formato: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Invita",
    "INVITE_EMAIL_REQUIRED": "Inserisci l'email dell'invitato.",
    "INVITE_EMAIL_INVALID": "Formato email non valido. Usa: user@example.com",
    "PENDING_INVITATION_TITLE": "Invito in sospeso",
    "PENDING_INVITATION_REMOVE_QUESTION": "Rimuovere questo invito in sospeso dal database?",
    "PENDING_INVITATION_KEEP": "Mantieni invito",
    "PENDING_INVITATION_REMOVAL_FAILED": "Rimozione non riuscita.",
    "REMOVE_FROM_LIST_TITLE": "Rimuovi dalla lista",
    "REMOVE_FROM_LIST_WARNING": "Rimuovere ora questo utente da entrambe le liste? L'accesso alla chat verrà interrotto immediatamente. L'unico percorso di rientro è un nuovo invito.",
    "REMOVE_FROM_LIST_KEEP": "Mantieni utente nella lista",
    "REMOVE_FROM_LIST_FAILED": "Rimozione dalla lista non riuscita.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Impostazioni e stato live",
    "PERMISSION_DIALOG_ARIA": "Impostazioni e stato live",
    "PERMISSION_TRIGGER_ARIA": "Trigger popup impostazioni",
    "PERMISSION_CLOSE_ARIA": "Chiudi popup permessi",
    "PERMISSION_LIVE_STATUS": "Stato live",
    "PERMISSION_SYSTEM_PERMISSION": "Permesso di sistema",
    "PERMISSION_APP_PUSH": "Push app",
    "PERMISSION_LOCATION_PERMISSION": "Permesso posizione",
    "PERMISSION_APP_LOCATION": "Posizione app",
    "PERMISSION_CONTROLS": "Controlli permessi",
    "PERMISSION_PUSH_NOTIFICATIONS": "Notifiche push",
    "PERMISSION_LOCATION_ACCESS": "Accesso alla posizione",
    "PERMISSION_IN_APP_SETTINGS": "Impostazioni in-app",
    "PERMISSION_ALERT_SOUND": "Suono avviso",
    "PERMISSION_APP_BADGE": "Badge app",
    "PERMISSION_PASSWORD_SETTINGS": "Impostazioni password",
    "PERMISSION_NAVIGATION_STATUS": "Stato navigazione",
    "PERMISSION_SELECTED_ZONE": "Zona selezionata",
    "PERMISSION_STAGED_CHAT_BANNER": "Banner chat preparato",
    "PERMISSION_CANVAS_CONTENT": "Contenuto canvas",
    "PERMISSION_YOUR_DEVICES": "I tuoi dispositivi ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Aggiorna elenco dispositivi",
    "PERMISSION_REFRESH_LIST": "Aggiorna elenco",
    "PERMISSION_NO_REGISTERED_DEVICES": "Nessun dispositivo registrato trovato.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Ridimensiona popup impostazioni",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Attiva/disattiva notifiche push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Attiva/disattiva accesso alla posizione",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Attiva/disattiva suono avviso",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Attiva/disattiva badge app",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Attiva/disattiva visibilità profilo",
    "PERMISSION_OFF_IN_V1": "Disattivato in v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Lista banner",
    "PERMISSION_PUSH_DISABLED_V1": "Le notifiche push sono disattivate per la release v1 Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Le notifiche push sono attive per questo dispositivo.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Le notifiche di sistema sono bloccate. Tocca per aprire la guida impostazioni.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Attiva per migliorare l'affidabilità della consegna.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Per disattivare le notifiche di sistema, apri le impostazioni di notifica del browser/sito e imposta questo sito su Blocca.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Per modificare il permesso delle notifiche di sistema, apri le impostazioni di notifica del browser/sito e imposta questo sito su Consenti.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "L'accesso alla posizione è attivo per l'ordinamento LCAC basato sulla distanza e il posizionamento sulla mappa.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "L'API di localizzazione non è supportata in questo ambiente.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "L'accesso alla posizione è bloccato. Tocca per aprire la guida impostazioni.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Attiva per consentire ordinamento LCAC preciso basato sulla distanza e posizionamento sulla mappa in-app.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "L'accesso alla posizione non è supportato in questo ambiente.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Per disattivare l'accesso alla posizione, apri le impostazioni di posizione del browser/sito e imposta questo sito su Blocca.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Per attivare l'accesso alla posizione per l'ordinamento per distanza e il posizionamento sulla mappa in-app, apri le impostazioni di posizione del browser/sito e imposta questo sito su Consenti.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Impossibile caricare i dispositivi registrati in questo momento.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Caricamento UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Caricamento Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Caricamento backend...",
    "RUNTIME_LOADING": "Caricamento...",
    "RUNTIME_LOADING_FROM_DATABASE": "Caricamento dal database...",
    "RUNTIME_BACKEND_CONNECTED": "Backend connesso",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Fallback cache attivo",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback predefinito attivo",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Valori predefiniti di fallback attivi",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Salvataggio tramite backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Salvato nel servizio backend",
    "RUNTIME_SAVE_FAILED": "Salvataggio non riuscito",
    "RUNTIME_LOAD_FAILED": "Caricamento non riuscito",
    "RUNTIME_CONNECTED": "Connesso",
    "RUNTIME_LOGIN_REQUIRED": "Accesso richiesto",
    "RUNTIME_SAVED": "Salvato",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI pronta - runtime in sospeso",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Il servizio selector backend protetto ha rifiutato o non ha potuto salvare l'opzione modello richiesta.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Il servizio selector backend protetto ha rifiutato o non ha potuto salvare la modifica di routing WF1 richiesta.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Il selector ora legge configurazione attiva, routing Qwen e opzioni consentite dal servizio backend protetto.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Il servizio backend del selector non è disponibile al momento, quindi viene usato l'ultimo stato del selector in cache.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "I valori predefiniti del selector sono attivi perché non è stato possibile caricare alcuno stato backend o in cache.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Il servizio selector backend protetto ha aggiornato la configurazione di routing WF1 attiva e aggiornato la cache del dominio runtime.",
    "FRONTEND_VERSION_TITLE": "Versione frontend",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Questo selector controlla la versione frontend attiva per tutti gli utenti. FeV2.0.0 è attivo.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Questo selector legge la versione frontend attiva da config_domain_registry. Il runtime si risolve in FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "La configurazione backend della versione frontend non è stata caricata, quindi il valore predefinito codificato FeV2.0.0 resta attivo finché il bootstrap di avvio non potrà rileggere il servizio protetto.",
    "FRONTEND_VERSION_HELPER_SAVED": "La versione frontend attiva è stata salvata in config_domain_registry. Un aggiornamento completo o il prossimo caricamento dell'app applica il valore runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Il servizio backend di controllo versione frontend non ha potuto salvare la versione globale richiesta.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Versione frontend attiva.",
    "CHAT_DELETE_WINDOW_TITLE": "Finestra eliminazione chat",
    "CHAT_DELETE_HELPER": "Questo valore controlla la finestra di disponibilità di Elimina per tutti in secondi. La guardia backend cambia immediatamente dopo il salvataggio. La visibilità della bolla cambia dopo un aggiornamento completo o al prossimo caricamento dell'app.",
    "CHAT_DELETE_HELPER_FALLBACK": "Il servizio backend di controllo eliminazione chat non è stato caricato, quindi il valore predefinito codificato resta attivo finché il bootstrap di avvio non potrà rileggere il servizio protetto.",
    "CHAT_DELETE_HELPER_SAVED": "La finestra di disponibilità di Elimina per tutti è stata salvata in config_domain_registry. La guardia backend cambia immediatamente. La visibilità della bolla cambia dopo un aggiornamento completo o al prossimo caricamento dell'app.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Il servizio backend di controllo eliminazione chat non ha potuto salvare il valore finestra richiesto.",
    "CHAT_DELETE_WINDOW_LABEL": "Finestra Elimina per tutti",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} sec",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Memorizza il valore in secondi interi. Il valore di produzione corrente è 86400 secondi = 1 giorno.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Secondi finestra",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Inserisci un numero intero maggiore o uguale a 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Salva finestra eliminazione",
    "GUEST_BANNER_CONTROL_TITLE": "Banner ospite",
    "GUEST_BANNER_CONTROL_LABEL": "Chat QR ospite",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Mostra banner ospite per tutti gli utenti",
    "GUEST_BANNER_CONTROL_HELPER": "Controlla il banner Ospite fisso e la durata del token QR in sospeso.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Il fallback locale è attivo per i controlli del banner Ospite.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Controlli del banner Ospite salvati.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Impossibile salvare i controlli del banner Ospite.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} sessioni Ospite revocate.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "TTL QR in sospeso (minuti)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "TTL QR in attesa attuale: {count} minuti.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Inserisci un numero intero positivo di minuti.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Salva banner ospite",
    "GUEST_QR_LOADING": "Preparazione QR ospite...",
    "GUEST_QR_READY": "Scansiona per aprire la chat ospite temporanea.",
    "GUEST_QR_ALT": "Codice QR della chat ospite",
    "GUEST_QR_LOAD_FAILED": "Impossibile preparare il QR ospite.",
    "GUEST_SESSION_ACTIVE": "L'ospite è connesso.",
    "GUEST_PUBLIC_TITLE": "Chat ospite",
    "GUEST_PUBLIC_CONNECTING": "Connessione in corso...",
    "GUEST_PUBLIC_CONNECTED": "Connesso",
    "GUEST_PUBLIC_UNAVAILABLE": "Questo link ospite non è disponibile.",
    "GUEST_PUBLIC_SEND_FAILED": "Impossibile inviare il messaggio.",
    "UI_TEXTS_RUNTIME_TITLE": "Runtime lingua interfaccia utente",
    "UI_TEXTS_RUNTIME_BACKEND": "Il runtime della lingua dell'interfaccia utente sta leggendo dal servizio di backend protetto. Le modifiche verranno applicate al successivo caricamento completo dell'app.",
    "UI_TEXTS_RUNTIME_CACHED": "Il servizio di runtime della lingua dell'interfaccia utente del backend non è al momento disponibile, pertanto sono attive le impostazioni predefinite locali o memorizzate nella cache.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "Le impostazioni predefinite del runtime della lingua dell'interfaccia utente sono attive perché non è stato possibile caricare alcuno stato di backend o memorizzato nella cache.",
    "UI_TEXTS_RUNTIME_SAVED": "Il controllo del runtime della lingua dell'interfaccia utente è stato salvato. È necessario un aggiornamento completo o il successivo caricamento dell'app affinché gli utenti ricevano il nuovo gate della lingua.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Il servizio di backend protetto non è riuscito a salvare la modifica del runtime della lingua dell'interfaccia utente richiesta.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Applicazione della lingua del dispositivo",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Abilita le lingue dell'interfaccia utente in fase di esecuzione",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Gli utenti possono ricevere i payload di testo dell'interfaccia utente per la lingua memorizzata o per quella del dispositivo.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Tutti gli utenti sono obbligati a utilizzare il testo dell'interfaccia utente in inglese e la lingua del dispositivo viene ignorata.",
    "PROFILE_VISIBILITY_TITLE": "Visibilità profilo",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Devi essere connesso per gestire la visibilità dell'account.",
    "PROFILE_VISIBILITY_HELPER": "Questo interruttore aggiorna solo lo stato di visibilità del tuo account. Rilevabilità e comportamento della lista banner restano invariati in questa fase.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Impossibile caricare la visibilità del profilo in questo momento.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Impossibile aggiornare la visibilità del profilo in questo momento.",
    "PROFILE_VISIBILITY_SAVED": "La visibilità del tuo account ora è {visibility}. Gli indicatori di rilevabilità restano invariati in questa fase.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Account pubblico",
    "PROFILE_VISIBILITY_STORED": "Visibilità memorizzata",
    "WF1_MODEL_CONTROL_TITLE": "Controllo modello WF1",
    "WF1_ENABLE_TRANSLATION": "Abilita traduzione / pivot",
    "WF1_TRANSLATION_ACTIVE": "La traduzione IA è attiva.",
    "WF1_TRANSLATION_INACTIVE": "WF1 continua a funzionare, ma il testo sorgente viene copiato e il pivot è marcato come inattivo.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Slot runtime attivo",
    "WF1_ALLOW_SAME_LANGUAGE": "Consenti IA per coppie della stessa lingua",
    "WF1_SAME_LANGUAGE_ACTIVE": "Le coppie della stessa lingua seguono il normale routing WF1.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Le coppie della stessa lingua bypassano l'IA e memorizzano Nessuna lingua pivot attiva.",
    "WF1_QWEN_ROUTING": "Routing coppie Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Le lingue selezionate sotto usano Qwen-Max quando la coppia è la stessa lingua selezionata, una lingua selezionata con l'inglese o due lingue non inglesi selezionate. In caso contrario resta attivo il modello primario selezionato.",
    "WF1_OPENROUTER_TEST_SLOT": "Slot test OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Slot test OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Solo test qualità",
    "WF1_OPENROUTER_HELPER": "Questo slot è modificabile solo per test temporanei di qualità OpenRouter. Non modifica il percorso operativo di routing coppie Qwen a meno che questo slot stesso diventi il modello attivo.",
    "WF1_LABEL": "Etichetta",
    "WF1_PRODUCT": "Prodotto",
    "WF1_MODEL": "Modello",
    "WF1_PROVIDER_OPENROUTER": "Provider: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Segreto: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Slot test OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max via OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Prezzo di listino Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Prezzo di listino OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Prezzo di listino OpenRouter",
    "LANGUAGE_ENGLISH": "Inglese",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Cinese (semplificato)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Cinese (tradizionale)",
    "LANGUAGE_JAPANESE": "Giapponese",
    "LANGUAGE_KOREAN": "Coreano",
    "LANGUAGE_PERSIAN": "Persiano",
    "LANGUAGE_TURKISH_ISTANBUL": "Turco (Istanbul)",
    "LANGUAGE_ARABIC": "Arabo",
    "LANGUAGE_FRENCH": "Francese",
    "LANGUAGE_GERMAN": "Tedesco",
    "LANGUAGE_SPANISH": "Spagnolo",
    "LANGUAGE_PORTUGUESE": "Portoghese",
    "LANGUAGE_ITALIAN": "Italiano",
    "LANGUAGE_RUSSIAN": "Russo",
    "LANGUAGE_DUTCH": "Olandese",
    "LANGUAGE_VIETNAMESE": "Vietnamita",
    "LANGUAGE_INDONESIAN": "Indonesiano",
    "LANGUAGE_THAI": "Thai",
    "LANGUAGE_MALAY": "Malese",
    "WF1_PRICING_CUSTOM": "Prezzi: modello slot personalizzato - verifica i prezzi OpenRouter correnti",
    "WF1_SAVE_OPENROUTER_SLOT": "Salva slot OpenRouter",
    "WF1_PRICING_LINE": "Input {input} - Output {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Segreto: {secret}",
    "ZONE_VISIBILITY_TITLE": "Controllo visibilità zone",
    "ZONE_ENABLE": "Abilita {zone}",
    "ZONE_ENABLED_NOTE": "{zone} può apparire per i ruoli consentiti dopo il prossimo caricamento dell'app.",
    "ZONE_DISABLED_NOTE": "{zone} viene trattata come assente per utenti non S_Admin dopo il prossimo caricamento dell'app.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin bypassa questa lista di ruoli e mantiene sempre l'accesso.",
    "ZONE_ROLE_LOCKED": "Le selezioni dei ruoli sono temporaneamente bloccate mentre questa zona è disabilitata e torneranno esattamente come salvate quando la zona verrà riabilitata.",
    "ZONE_LCAC_CONTROL": "Controllo LCAC",
    "ZONE_RCAC_CONTROL": "Controllo RCAC",
    "ZONE_LCAC_DESCRIPTION": "Controlla l'esistenza della zona riservata sinistra e i ruoli che possono vederla.",
    "ZONE_RCAC_DESCRIPTION": "Controlla l'esistenza della zona riservata destra e i ruoli che possono vederla.",
    "ZONE_VISIBILITY_BACKEND": "Il bootstrap della visibilità zone ora legge dal servizio backend protetto. Le modifiche si applicano al prossimo caricamento dell'app.",
    "ZONE_VISIBILITY_CACHED": "Il servizio backend di visibilità zone non è disponibile al momento, quindi sono attivi valori in cache o predefiniti locali.",
    "ZONE_VISIBILITY_DEFAULTS": "I valori predefiniti di visibilità zone sono attivi perché non è stato possibile caricare alcuno stato backend o in cache.",
    "ZONE_VISIBILITY_SAVED": "Il bootstrap della visibilità zone è stato salvato. È richiesto un ricaricamento forzato o il prossimo caricamento dell'app per l'applicazione runtime.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Il servizio backend protetto non ha potuto salvare la modifica di visibilità zona richiesta.",
    "ROLE_MEMBER": "Membro",
    "ROLE_STAFF": "Staff",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Abilita le notifiche per ricevere nuovi messaggi.",
    "MAIN_LOG_OUT": "Esci",
    "NOTIFICATION_NEW_MESSAGE": "Nuovo messaggio",
    "NOTIFICATION_UNREAD_MESSAGE": "Hai un messaggio non letto.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Vista completa",
    "MEDIA_AUDIO_ATTACHMENT": "Allegato audio",
    "MEDIA_FILE_FALLBACK": "File",
    "MEDIA_DOWNLOAD_READY": "Allegato pronto per il download",
    "MEDIA_TYPE_UNSUPPORTED": "Tipo non supportato per la vista completa",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Immagine precedente",
    "MEDIA_NEXT_IMAGE_ARIA": "Immagine successiva",
    "MEDIA_OPEN_ORIGINAL": "Apri originale",
    "MEDIA_DOWNLOAD": "Scarica",
    "MEDIA_CLOSE_ARIA": "Chiudi",
    "MEDIA_PROFILE_PICTURE_ARIA": "Foto profilo di {name}",
    "MEDIA_PROFILE_ALT": "Profilo di {name}",
    "MEDIA_UPLOAD_FAILED": "Caricamento non riuscito",
    "MEDIA_BACKEND_TOKEN_ERROR": "Errore token backend",
    "MEDIA_UPLOAD_URL_MISSING": "Critico: URL di caricamento mancante nella risposta backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Token di autenticazione mancante per caricamento chat",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Richiesta token caricamento chat non riuscita",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Risposta caricamento chat non valida",
    "MEDIA_GCS_UPLOAD_FAILED": "Caricamento GCS non riuscito",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nome file o contentType mancante",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path mancante",
    "BLOCK_NOTICE_TITLE": "Avviso di blocco permanente",
    "BLOCK_NOTICE_MESSAGE": "Il tuo account è stato temporaneamente sospeso a causa di una violazione della policy.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Se ritieni che sia necessario un follow-up, contatta",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "via email.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Utente sconosciuto",
    "GENERAL_GUEST": "Ospite",
    "ADVISOR_FOR_CLIENT": "Consulente per {client_display_name}",
    "GUEST_FOR_CLIENT": "Ospite per {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token e password sono obbligatori",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Il corpo della richiesta deve essere JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Token di invito non valido o scaduto",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Impostazione password non riuscita: sessione o utente mancante",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Impostazione password non riuscita durante l'accesso",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Generazione token admin non riuscita",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Accesso non riuscito: sessione o utente mancante",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registrazione riuscita. Controlla l'email per la verifica.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Registrazione non riuscita: errore sconosciuto",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Elaborazione token non valida",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Token di accesso obbligatorio",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "L'anteprima hash token richiede suggerimento email dall'URL di reindirizzamento",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Impossibile risolvere l'identità per questo token",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Solo User Zero può accedere al servizio selector LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Solo User Zero può accedere al servizio di controllo visibilità zone.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Solo User Zero può accedere al servizio di controllo versione frontend.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Solo User Zero può ispezionare la versione frontend di un altro utente.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Solo User Zero può accedere al servizio di controllo eliminazione chat.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Solo l'Utente Zero può accedere al servizio di controllo runtime della lingua dell'interfaccia utente.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Solo User Zero può eliminare definitivamente un account utente.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Payload richiesta non valido.",
    "API_ERROR_INTERNAL_SERVER": "Errore interno del server",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funzione mancante nel backend (ricaricamento richiesto)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Solo DB RPC è consentito per le transizioni delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Attendi prima di inviare un altro messaggio.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Messaggio inviato correttamente.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Servizio di contatto non disponibile.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Invio messaggio non riuscito.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Il nome è obbligatorio.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "L'email non è valida.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Il messaggio è obbligatorio.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload selector obbligatorio.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload visibilità zone obbligatorio.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload versione frontend obbligatorio.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload controllo eliminazione chat obbligatorio.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "È richiesto il payload di controllo runtime della lingua dell'interfaccia utente.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID utente autenticato obbligatorio.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID utente visualizzatore autenticato obbligatorio.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID utente attore autenticato obbligatorio.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id è obbligatorio.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id è obbligatorio.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "La lista owner_user_ids è obbligatoria.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email è obbligatoria.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by è obbligatorio.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Il runtime di ricerca è disabilitato dalla versione frontend globale.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Non sei autorizzato ad annullare questo invito in sospeso.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Questo invito non può più essere annullato perché l'utente è già registrato.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Invito in sospeso non trovato.",
    "INVITE_REPLY_ALREADY_MEMBER": "Congratulazioni, il tuo amico ({invitee_email}) è già registrato in questa app ed è membro di questo workspace.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Un invito è in sospeso per {invitee_email}, ma non è stato possibile attivare l'email di nuovo invio. Controlla i log email.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Il record di invito è stato creato per {invitee_email}, ma non è stato possibile confermare la consegna dell'email. Riprova più tardi o controlla i log email.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Creazione del record di invito non riuscita. Riprova più tardi.",
    "INVITE_REPLY_SYSTEM_ERROR": "Errore di sistema durante il processo di invito: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Errore configurazione backend: credenziali Supabase mancanti",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Errore configurazione backend: URL Supabase non valido",
    "CHAT_ERROR_ACCESS_DENIED": "Accesso negato",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Il contenuto non può essere vuoto per i messaggi di testo",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Impossibile determinare l'ID conversazione",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Contesto autenticazione RPC mancante",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC ha restituito un payload messaggio non valido",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Inserimento non riuscito, nessun dato restituito",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations deve essere una lista",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Payload operazione non valido",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type non supportato",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id è obbligatorio",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Messaggio non trovato",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "L'eliminazione è consentita solo sul tuo messaggio",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Elimina per tutti non è più disponibile per questo messaggio",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Elimina per tutti non riuscito",
    "API_ERROR_SERVER_CONFIGURATION": "Errore configurazione server",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Header segreto webhook mancante",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Sorgente webhook non autorizzata",
    "API_ERROR_BACKEND_CONFIGURATION": "Errore configurazione backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Errore attributo modulo: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Errore prima dell'eliminazione dell'invito durante la rimozione dell'utente auth in attesa.",
    "CHAT_ERROR_DB": "Errore DB: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
