# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/ja.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "メイン",
    "APP_TITLE": "OTMEGA AIプラットフォーム",
    "APP_SUBTITLE": "AIアドバイザー",
    "CHAT_PLACEHOLDER": "メッセージを入力...",
    "CHAT_SEND_BUTTON": "送信",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 アドバイザーは間違えることがあります。内容を確認してください。",
    "STATUS_ONLINE": "オンライン",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "メニュー",
    "ICON_NEW_CHAT": "新しいチャット",
    "ICON_HISTORY": "履歴",
    "ICON_TEMPLATES": "テンプレート",
    "ICON_SETTINGS": "設定",
    "ICON_USER_PROFILE": "ユーザープロフィール",
    "ICON_QUICK_ACTIONS": "クイックアクション",
    "ICON_PINNED": "ピン留め",
    "ICON_GALLERY": "ギャラリー",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "アプリをインストール",
    "PWA_ANDROID_MSG": "より快適な体験とオフラインアクセスのため、このアプリをデバイスにインストールしてください。",
    "PWA_IOS_MSG": "iPhone/iPadにこのアプリをインストールするには：\n1. 下の共有ボタンをタップします\n2. 「ホーム画面に追加」を選択します",
    "PWA_BTN_INSTALL": "インストール",
    "PWA_BTN_LATER": "後で",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "アドバイザーネットワークにログイン",
    "AUTH_HEADER_SIGNUP": "統合アカウントを作成",
    "AUTH_HEADER_LOGIN_NETWORK": "アドバイザーネットワークにログイン",
    "AUTH_HEADER_SIGNUP_UNIFIED": "統合アカウントを作成",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "ログイン",
    "AUTH_BUTTON_SIGNUP": "アカウント作成",
    "AUTH_BUTTON_GOOGLE": "Googleで続行",
    "AUTH_BUTTON_FORGOT_PASSWORD": "パスワードを忘れた場合",
    "AUTH_BUTTON_SEND_RESET_LINK": "リセットリンクを送信",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "アカウントをお持ちでないですか？登録",
    "AUTH_PROMPT_LOGIN": "すでにアカウントをお持ちですか？ログイン",
    "AUTH_HELPER_TEXT_SIGNUP": "このプラットフォーム内のすべてのアドバイザーにアクセスできる統合アカウントを作成します。",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "このプラットフォーム内のすべてのアドバイザーにアクセスできる統合アカウントを作成します。",
    "AUTH_HELPER_TEXT_LOGIN": "このネットワーク内の他のアドバイザーで使用した同じアカウント（メール/パスワードまたはGoogle）を使用してください。",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "このネットワーク内の他のアドバイザーで使用した同じアカウント（メール/パスワードまたはGoogle）を使用してください。",
    "AUTH_FORGOT_PASSWORD_LINK": "パスワードをお忘れですか？",
    "AUTH_FORGOT_PASSWORD_TITLE": "パスワードをリセット",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "メールアドレスを入力してください。パスワードをリセットするリンクを送信します。",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "メール",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "ログイン中...",
    "AUTH_STATUS_LOADING_SIGNUP": "アカウントを作成中...",
    "AUTH_STATUS_LOADING_RESET": "リセットリンクを送信中...",
    "AUTH_STATUS_SUCCESS_LOGIN": "ログインに成功しました！再読み込み中...",
    "AUTH_STATUS_SUCCESS_RESET": "リセットリンクを送信しました。メールを確認してください。",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "パスワードリセットリンクを送信しました。メールを確認してください。",

    "AUTH_ERROR_INVALID_CREDENTIALS": "メールアドレスまたはパスワードが無効です。",
    "AUTH_ERROR_EMAIL_EXISTS": "このメールアドレスのアカウントはすでにアドバイザーネットワークに存在します。",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "このメールアドレスのアカウントはすでに存在します。ログインしてください。現在、次のメンバーです：",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "このメールアドレスのアカウントはすでにアドバイザーネットワークに存在します。このウィンドウを閉じ、同じメールアドレスと以前のパスワードで「ログイン」セクションを使用してください。",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "現在、次のメンバーです：",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "メールアドレスとパスワードは必須です。",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "アカウントは作成されましたが、メンバーシップの設定に失敗しました。サポートにお問い合わせください。",
    "AUTH_ERROR_DEFAULT": "エラーが発生しました。もう一度お試しください。",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "ゲストバナー制御ペイロードが必要です。",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "User Zero のみがゲストバナーコントロールを更新できます。",
    "AUTH_FORGOT_PASSWORD_ERROR": "リセットリンクの送信に失敗しました。もう一度お試しください。",
    "INVITE_REPLY_EMAIL_SENT": "Collabraの招待メールを{invitee_email}の友人に送信しました。",
    "INVITE_REPLY_EMAIL_RESENT": "Collabraの招待メールを{invitee_email}の友人に再送信しました。",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "パスワードを表示",
    "AUTH_PASSWORD_TOGGLE_HIDE": "パスワードを非表示",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "キャンセル",
    "GENERAL_CLOSE": "閉じる",
    "GENERAL_SEND": "送信",
    "GENERAL_SEARCH": "検索",
    "GENERAL_RESET": "リセット",
    "GENERAL_ENABLE": "有効化",
    "GENERAL_LOADING": "読み込み中...",
    "GENERAL_DELETE": "削除",
    "GENERAL_DELETING": "削除中...",
    "GENERAL_SAVE_PASSWORD": "パスワードを保存",
    "AUTH_REMEMBER_EMAIL_LABEL": "メールアドレスを記憶",
    "GENERAL_SAVING": "保存中...",
    "GENERAL_SENDING": "送信中...",
    "GENERAL_REMOVING": "削除中...",
    "GENERAL_CONFIRM_REMOVAL": "削除の確認",
    "GENERAL_EMPTY": "空",
    "GENERAL_UNAVAILABLE": "利用不可",
    "GENERAL_ENABLED": "有効",
    "GENERAL_DISABLED": "無効",
    "GENERAL_GRANTED": "許可済み",
    "GENERAL_DENIED": "拒否",
    "GENERAL_DEFAULT": "デフォルト",
    "GENERAL_UNSUPPORTED": "未対応",
    "GENERAL_PUBLIC": "公開",
    "GENERAL_PRIVATE": "非公開",
    "GENERAL_USERNAME": "ユーザー名",
    "GENERAL_EMAIL": "メール",
    "GENERAL_YOU": "あなた",
    "GENERAL_USER": "ユーザー",
    "GENERAL_UNKNOWN": "不明",
    "GENERAL_VISITOR": "訪問者",
    "GENERAL_PROFILE": "プロフィール",
    "GENERAL_BANNER": "バナー",
    "GENERAL_UNKNOWN_BANNER": "不明なバナー",
    "GENERAL_ADVISOR_BANNER": "アドバイザーバナー",
    "GENERAL_NOT_AVAILABLE": "N/A",
    "GENERAL_NOT_SELECTED": "未選択",
    "GENERAL_NO_EMAIL_FOUND": "メールが見つかりません",
    "GENERAL_USER_ZERO_ONLY": "User Zeroのみ",
    "GENERAL_CONNECTION_STATE": "接続状態",
    "GENERAL_DISPLAY_ONLY": "表示のみ",
    "GENERAL_TEXTAREA": "テキストエリア",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "メニュー（LCAC）",
    "HEADER_CHAT_CCAC": "チャット（CCAC）",
    "HEADER_QUICK_ACTIONS_RCAC": "クイックアクション（RCAC）",
    "HEADER_CHANGE_STATUS": "ステータスを変更",
    "HEADER_OT_COIN_BALANCE": "OT Coin残高",
    "HEADER_ALT_USER": "ユーザー",
    "STATUS_BUSY": "取り込み中",
    "STATUS_AWAY": "離席中",
    "STATUS_OFFLINE": "オフライン",
    "STATUS_INVISIBLE": "非表示",
    "NETWORK_CHECKING_CONNECTION": "接続を確認中...",
    "NETWORK_ONLINE_LATENCY": "オンライン（レイテンシ: {latency}ms）",
    "NETWORK_GOOD_TAP_TO_PING": "ネットワーク: 良好（タップしてping）",
    "CHAT_TARGET_ALT": "チャット対象",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "検索...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "{name}のプロフィール画像を開く",
    "CHAT_MESSAGE_INPUT_ARIA": "メッセージ入力",
    "CHAT_TOGGLE_VIEW_ARIA": "表示を切り替え",
    "CHAT_ADD_USER_ARIA": "ユーザーを追加",
    "CHAT_ATTACH_ARIA": "添付",
    "CHAT_MIC_ARIA": "マイク",
    "CHAT_SEND_ARIA": "送信",
    "CHAT_SEARCH_ARIA": "検索",
    "CHAT_OPEN_SEARCH_ARIA": "検索を開く",
    "CHAT_CLOSE_SEARCH_ARIA": "検索を閉じる",
    "CHAT_ATTACHMENT_ALT": "添付ファイル",
    "CHAT_PREVIEW_ALT": "プレビュー",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "添付ファイルを削除",
    "CHAT_REPLYING_TO": "返信先",
    "CHAT_CANCEL_REPLY_ARIA": "返信をキャンセル",
    "CHAT_UPLOADING": "アップロード中...",
    "CHAT_LOADING_CHATS": "チャットを読み込み中...",
    "CHAT_SEND_FAILED": "送信失敗",
    "CHAT_SEND_FAILED_RETRY": "送信に失敗しました。もう一度お試しください。",
    "CHAT_RETRY": "再試行",
    "CHAT_EDITED": "編集済み",
    "CHAT_TYPING": "入力中",
    "CHAT_LOADING": "読み込み中",
    "CHAT_PENDING_INVITATION": "招待待ち",
    "CHAT_PENDING_INVITATION_MIN": "{count}分 招待待ち",
    "CHAT_PENDING_INVITATION_HR": "{count}時間 招待待ち",
    "CHAT_PENDING_INVITATION_DAY": "{count}日 招待待ち",
    "CHAT_WAITING_FOR_YOU": "{label} - あなたの対応待ち",
    "CHAT_PENDING_ACCEPTANCE": "{label} - 承認待ち",
    "CHAT_MICROPHONE_ACCESS_DENIED": "マイクへのアクセスが拒否されました。",
    "CHAT_UPLOAD_FAILED": "アップロード失敗: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "アップロードにはインターネット接続が必要です。オンラインになってからもう一度お試しください。",
    "OFFLINE_SHOWING_SAVED_DATA": "",
    "OFFLINE_DATA_MAY_BE_OUTDATED": "",
    "OFFLINE_ACTION_REQUIRES_CONNECTION": "",
    "OFFLINE_MESSAGE_WAITING_CONNECTION": "",
    "OFFLINE_PENDING_MESSAGES_TOOLTIP": "",
    "APP_BACK_EXIT_HINT": "",
    "CHAT_ERROR_AUTH": "認証エラー",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "ファイル名またはcontent_typeがありません",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_idまたはtarget_idがありません",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "アバター以外のアップロードにはconversation_idが必要です",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "アバターのfile_pathが無効です",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabaseサービスクライアントを利用できません",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "アバターの既読ACKはアドバイザーチャットのコンテキストでのみ有効です",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "アバターフローのメッセージが見つからないか、既読ACKの対象ではありません",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "アバターメッセージを既読として確定できませんでした",
    "CHAT_ATTACHMENT_COUNT_ONE": "添付ファイル1件",
    "CHAT_ATTACHMENT_COUNT_MANY": "添付ファイル{count}件",
    "CHAT_VOICE_NOTE": "ボイスノート",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "チャットを利用できません。このユーザーはあなたをブロックしています。",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "チャットを利用できません。あなたはこのユーザーをブロックしています。",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "ポリシーによりアカウントアクセスがブロックされています。",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "チャットを利用できません。このアカウントはUser Zeroにより最終ブロックされています。",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "チャットを利用できません。相互ブロックが有効です。",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "ブロックポリシーによりチャットを利用できません。",
    "MESSAGE_PREVIEW_PHOTO": "写真",
    "MESSAGE_PREVIEW_VOICE": "ボイスメッセージ",
    "MESSAGE_PREVIEW_VIDEO": "動画",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "ファイル",
    "MESSAGE_PREVIEW_MESSAGE": "メッセージ",
    "MESSAGE_PREVIEW_SYSTEM": "システムメッセージ",
    "MESSAGE_PREVIEW_NEW": "新着メッセージ",
    "MESSAGE_UNKNOWN_FILE": "不明なファイル",
    "MESSAGE_AUDIO_ATTACHMENT": "音声添付ファイル",
    "MESSAGE_FILE_ATTACHMENT": "添付ファイル",
    "BANNER_INVITED_BY": "{label}から招待",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "検索結果",
    "SEARCH_QUERY_LABEL": "クエリ:",
    "SEARCH_LOADING_VISIBILITY": "検索表示設定を読み込み中...",
    "SEARCH_NO_RESULTS": "現在の検索範囲に結果が見つかりません。",
    "SHARE_WITH_COLLABRA": "Collabraで共有",
    "SHARE_SEND_TO": "送信先",
    "SHARE_SELECT_ONE_BANNER": "バナーを1つ選択",
    "SHARE_BANNER_LIST_ARIA": "バナー一覧",
    "SHARE_NO_MATCHING_BANNER": "一致するバナーがありません",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "コメントを追加...",
    "SHARE_RECENT_CHATS": "最近のチャット",
    "SHARE_LEFT_LIST": "左リスト",
    "SHARE_RIGHT_LIST": "右リスト",
    "SHARE_UNTITLED_BANNER": "無題のバナー",
    "SHARE_SHARED_CONTENT": "共有コンテンツ",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "共有コンテンツを開けませんでした。",
    "SHARE_OPEN_BANNER_FAILED": "選択したバナーを開けませんでした。",
    "SHARE_ONE_PHOTO_SELECTED": "写真1枚を選択",
    "SHARE_MANY_PHOTOS_SELECTED": "写真{count}枚を選択",
    "SHARE_ONE_FILE_SELECTED": "ファイル1件を選択",
    "SHARE_MANY_FILES_SELECTED": "ファイル{count}件を選択",
    "FORWARD_MESSAGE_TITLE": "メッセージを転送",
    "FORWARD_SELECT_RECIPIENTS": "宛先を選択",
    "FORWARD_NO_OTHER_BANNER": "他のバナーは利用できません。",
    "FORWARD_SEND_TO_COUNT": "{count}件に送信",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "少なくとも1つのバナーを選択してください。",
    "FORWARD_FAILED_DEFAULT": "転送に失敗しました。もう一度お試しください。",
    "FORWARD_PARTIAL_SENT": "{count}件送信済み。{error}",
    "FORWARD_SOURCE_NOT_FOUND": "転送元メッセージが見つかりません",
    "FORWARD_NO_FORWARDABLE_CONTENT": "このメッセージにはまだ転送可能なコンテンツがありません",
    "FORWARD_DESTINATION_MISSING": "転送先がありません",
    "FORWARD_MESSAGE_PREVIEW": "転送メッセージ",
    "MENU_PASTE": "貼り付け",
    "MENU_COPY": "コピー",
    "MENU_REPLY": "返信",
    "MENU_FORWARD": "転送",
    "MENU_REMOVE_INVITATION": "招待を削除",
    "MENU_REMOVE_FROM_LIST": "リストから削除",
    "MENU_GOODBYE_GUEST": "さようなら、ゲスト",
    "MENU_ADD_TO_LIST": "リストに追加",
    "MENU_REJECT_INVITATION": "招待を拒否",
    "MENU_FRONTEND_VERSION": "フロントエンドバージョン",
    "MENU_BANNER_HEADER": "バナー - {zone}",
    "MENU_BANNER_INFO": "バナー情報: {title}",
    "MENU_MESSAGE_BUBBLE": "メッセージバブル",
    "MENU_CHAT_CANVAS_HEADER": "チャットキャンバス - {zone}",
    "MENU_CANVAS_INFO": "キャンバス情報",
    "MENU_CHAT_CANVAS_SUBLABEL": "会話エリア / 現在のチャット面",
    "MENU_INPUT_AREA_HEADER": "入力エリア - {zone}",
    "MENU_INPUT_AREA_INFO": "入力エリア情報: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "下部の入力およびアクションツール面",
    "MENU_HEADER": "ヘッダー - {zone}",
    "MENU_HEADER_INFO": "ヘッダー情報: {title}",
    "MENU_HEADER_DESCRIPTION": "上部ナビゲーションとページ制御",
    "MENU_ZONE_HEADER": "ゾーン - {zone}",
    "MENU_ZONE_SPACE_INFO": "ゾーンスペース情報",
    "MENU_EMPTY_LIST_SURFACE": "空/リスト面",
    "MENU_BLOCK": "ブロック",
    "MENU_UNBLOCK": "ブロック解除",
    "MENU_HIDE_IN_SEARCH": "検索で非表示",
    "MENU_UNHIDE_IN_SEARCH": "検索で表示",
    "MENU_VISIBLE_IN_SEARCH": "検索で表示",
    "MENU_HIDDEN_IN_SEARCH": "検索で非表示",
    "MENU_VISIBLE_IN_USER_LIST": "ユーザーリストで表示",
    "MENU_HIDDEN_IN_USER_LIST": "ユーザーリストで非表示",
    "MENU_NOT_BLOCKED": "未ブロック",
    "MENU_BLOCKED": "ブロック済み",
    "MENU_FRONTEND_VERSION_LOADING": "読み込み中...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "バックエンドからバナーごとの値を読み込み中です。データベースの応答が届くまで、アクティブとして表示されるオプションはありません。",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "バックエンド値を読み込めませんでした。信頼できるアクティブオプションは表示されません。",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "バナーごとの明示的なデータベース値は{overrideVersion}です。グローバルデフォルトは{globalDefaultVersion}です。起動時ブートストラップを適用するには、対象ユーザーがアプリを完全に更新または再度開く必要があります。",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "バナーごとの明示的なデータベース値は保存されていません。FeV2.0.0がデフォルトで有効です。グローバルデフォルトは{globalDefaultVersion}です。",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "対象アプリが完全に再読み込みされた後、バナーごとの明示的なデータベース値が有効になります",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "バナーごとの明示的な値は保存されていません。これは個別のFeV2.0.0デフォルト状態です",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "このオプションは現在のグローバルデフォルト値とも一致しています",
    "MENU_DELETE_PERMANENT_CONFIRM": "データベースから{target}を完全に削除しますか？これによりアカウント、チャット履歴、依存関係が削除され、今後の再参加には新しい招待パスが必要になります。",
    "MENU_DELETE_PERMANENTLY": "完全に削除",
    "MENU_REFRESH_PAGE": "ページを更新",
    "MENU_LOG_OFF": "ログオフ",
    "MENU_HARD_RELOAD": "強制再読み込み",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "メール（管理者ユーザー）",
    "AUTH_PASSWORD_PLACEHOLDER": "パスワード",
    "AUTH_CONNECTING": "接続中...",
    "AUTH_SIGNING_OUT": "サインアウト中...",
    "AUTH_BACK_TO_LOGIN": "ログインに戻る",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "サーバー応答が無効です: トークンが見つかりません。",
    "AUTH_LOGIN_FAILED": "ログイン失敗",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "パスワードが一致しません。",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "パスワードが一致しません！",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "パスワードは完全に一致する必要があります。",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "新しいパスワード",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "パスワードを確認",
    "AUTH_CHANGE_PASSWORD": "パスワードを変更",
    "AUTH_SAVING_PASSWORD": "保存中...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "パスワードが正常に更新されました。",
    "AUTH_CHANGE_PASSWORD_UNABLE": "現在パスワードを変更できません。",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "パスワードを変更するにはログインが必要です。",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "新しいパスワードの表示を切り替え",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "確認用パスワードの表示を切り替え",
    "REGISTER_TITLE": "登録を完了",
    "REGISTER_SUBTITLE": "パスワードを手動で設定してください。",
    "REGISTER_CREATING_ACCOUNT": "アカウントを作成中...",
    "REGISTER_FINISH_SETUP": "セットアップを完了",
    "REGISTER_FAILED_SET_PASSWORD": "パスワードの設定に失敗しました",
    "INVITE_EMAIL_INSTRUCTION": "招待相手のメールアドレスを入力してください（形式: user@example.com）",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "招待",
    "INVITE_EMAIL_REQUIRED": "招待相手のメールアドレスを入力してください。",
    "INVITE_EMAIL_INVALID": "メール形式が無効です。user@example.com を使用してください",
    "PENDING_INVITATION_TITLE": "保留中の招待",
    "PENDING_INVITATION_REMOVE_QUESTION": "この保留中の招待をデータベースから削除しますか？",
    "PENDING_INVITATION_KEEP": "招待を保持",
    "PENDING_INVITATION_REMOVAL_FAILED": "削除に失敗しました。",
    "REMOVE_FROM_LIST_TITLE": "リストから削除",
    "REMOVE_FROM_LIST_WARNING": "このユーザーを今すぐ両方のリストから削除しますか？チャットアクセスは直ちに遮断されます。戻る唯一の方法は新しい招待です。",
    "REMOVE_FROM_LIST_KEEP": "ユーザーをリストに保持",
    "REMOVE_FROM_LIST_FAILED": "リストからの削除に失敗しました。",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "設定とライブステータス",
    "PERMISSION_DIALOG_ARIA": "設定とライブステータス",
    "PERMISSION_TRIGGER_ARIA": "設定ポップアップのトリガー",
    "PERMISSION_CLOSE_ARIA": "権限ポップアップを閉じる",
    "PERMISSION_LIVE_STATUS": "ライブステータス",
    "PERMISSION_SYSTEM_PERMISSION": "システム権限",
    "PERMISSION_APP_PUSH": "アプリプッシュ",
    "PERMISSION_LOCATION_PERMISSION": "位置情報権限",
    "PERMISSION_APP_LOCATION": "アプリ位置情報",
    "PERMISSION_CONTROLS": "権限制御",
    "PERMISSION_PUSH_NOTIFICATIONS": "プッシュ通知",
    "PERMISSION_LOCATION_ACCESS": "位置情報アクセス",
    "PERMISSION_IN_APP_SETTINGS": "アプリ内設定",
    "PERMISSION_ALERT_SOUND": "アラート音",
    "PERMISSION_APP_BADGE": "アプリアイコンバッジ",
    "PERMISSION_PASSWORD_SETTINGS": "パスワード設定",
    "PERMISSION_NAVIGATION_STATUS": "ナビゲーションステータス",
    "PERMISSION_SELECTED_ZONE": "選択中のゾーン",
    "PERMISSION_STAGED_CHAT_BANNER": "ステージ済みチャットバナー",
    "PERMISSION_CANVAS_CONTENT": "キャンバスコンテンツ",
    "PERMISSION_YOUR_DEVICES": "あなたのデバイス（{count}）",
    "PERMISSION_REFRESH_DEVICE_LIST": "デバイス一覧を更新",
    "PERMISSION_REFRESH_LIST": "一覧を更新",
    "PERMISSION_NO_REGISTERED_DEVICES": "登録済みデバイスが見つかりません。",
    "PERMISSION_RESIZE_POPUP_ARIA": "設定ポップアップのサイズを変更",
    "PERMISSION_TOGGLE_PUSH_ARIA": "プッシュ通知を切り替え",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "位置情報アクセスを切り替え",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "アラート音を切り替え",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "アプリアイコンバッジを切り替え",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "プロフィール表示を切り替え",
    "PERMISSION_OFF_IN_V1": "v1ではオフ",
    "PERMISSION_CHAT": "チャット",
    "PERMISSION_BANNER_LIST": "バナー一覧",
    "PERMISSION_PUSH_DISABLED_V1": "v1 Google Playリリースではプッシュ通知が無効です。",
    "PERMISSION_PUSH_ON_TOOLTIP": "このデバイスではプッシュ通知がオンです。",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "システム通知がブロックされています。タップして設定ヘルプを開きます。",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "配信の信頼性を高めるにはオンにしてください。",
    "PERMISSION_SYSTEM_DISABLE_HELP": "システム通知を無効にするには、ブラウザ/サイトの通知設定を開き、このサイトをブロックに設定してください。",
    "PERMISSION_SYSTEM_ALLOW_HELP": "システム通知の権限を変更するには、ブラウザ/サイトの通知設定を開き、このサイトを許可に設定してください。",
    "PERMISSION_LOCATION_ON_TOOLTIP": "位置情報アクセスは、距離ベースのLCACソートとマップ位置決めのためにオンです。",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "この環境では位置情報APIはサポートされていません。",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "位置情報アクセスがブロックされています。タップして設定ヘルプを開きます。",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "正確な距離ベースのLCACソートとアプリ内マップ位置決めを許可するにはオンにしてください。",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "この環境では位置情報アクセスはサポートされていません。",
    "PERMISSION_LOCATION_DISABLE_HELP": "位置情報アクセスを無効にするには、ブラウザ/サイトの位置情報設定を開き、このサイトをブロックに設定してください。",
    "PERMISSION_LOCATION_ALLOW_HELP": "距離ソートとアプリ内マップ位置決めのために位置情報アクセスを有効にするには、ブラウザ/サイトの位置情報設定を開き、このサイトを許可に設定してください。",
    "PERMISSION_DEVICE_LOAD_FAILED": "現在、登録済みデバイスを読み込めません。",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "UIブリッジを読み込み中...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "ローカルブリッジを読み込み中...",
    "RUNTIME_LOADING_BACKEND": "バックエンドを読み込み中...",
    "RUNTIME_LOADING": "読み込み中...",
    "RUNTIME_LOADING_FROM_DATABASE": "データベースから読み込み中...",
    "RUNTIME_BACKEND_CONNECTED": "バックエンド接続済み",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "キャッシュ済みフォールバックが有効",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "デフォルトフォールバックが有効",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "フォールバックデフォルトが有効",
    "RUNTIME_SAVING_THROUGH_BACKEND": "バックエンド経由で保存中...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "バックエンドサービスに保存済み",
    "RUNTIME_SAVE_FAILED": "保存失敗",
    "RUNTIME_LOAD_FAILED": "読み込み失敗",
    "RUNTIME_CONNECTED": "接続済み",
    "RUNTIME_LOGIN_REQUIRED": "ログインが必要",
    "RUNTIME_SAVED": "保存済み",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI準備完了 - ランタイム保留中",
    "RUNTIME_BACKEND_REJECTED_MODEL": "保護されたバックエンドセレクターサービスが、要求されたモデルオプションを拒否したか保存できませんでした。",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "保護されたバックエンドセレクターサービスが、要求されたWF1ルーティング変更を拒否したか保存できませんでした。",
    "RUNTIME_WF1_SELECTOR_BACKEND": "セレクターは現在、保護されたバックエンドサービスからアクティブ設定、Qwenルーティング、許可済みオプションを読み込んでいます。",
    "RUNTIME_WF1_SELECTOR_CACHED": "バックエンドセレクターサービスが現在利用できないため、最後にキャッシュされたセレクター状態を使用しています。",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "バックエンドまたはキャッシュ済みのセレクター状態を読み込めなかったため、セレクターのデフォルト値が有効です。",
    "RUNTIME_WF1_SELECTOR_SAVED": "保護されたバックエンドセレクターサービスがアクティブなWF1ルーティング設定を更新し、ランタイムドメインキャッシュを更新しました。",
    "FRONTEND_VERSION_TITLE": "フロントエンドバージョン",
    "FRONTEND_VERSION_HELPER_ACTIVE": "このセレクターは全ユーザーのアクティブなフロントエンドバージョンを制御します。FeV2.0.0が有効です。",
    "FRONTEND_VERSION_HELPER_RUNTIME": "このセレクターはconfig_domain_registryからアクティブなフロントエンドバージョンを読み込みます。ランタイムはFeV2.0.0に解決されます。",
    "FRONTEND_VERSION_HELPER_FALLBACK": "バックエンドのフロントエンドバージョン設定を読み込めなかったため、起動時ブートストラップが保護サービスを再度読み込めるまで、コード上のFeV2.0.0デフォルトが有効です。",
    "FRONTEND_VERSION_HELPER_SAVED": "アクティブなフロントエンドバージョンがconfig_domain_registryに保存されました。完全更新または次回アプリ読み込み時にランタイム値が適用されます。",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "バックエンドのフロントエンドバージョン制御サービスが、要求されたグローバルバージョンを保存できませんでした。",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "アクティブなフロントエンドバージョンです。",
    "CHAT_DELETE_WINDOW_TITLE": "チャット削除ウィンドウ",
    "CHAT_DELETE_HELPER": "この値は、「全員から削除」を利用できる時間枠を秒単位で制御します。保存後、バックエンドガードは直ちに変更されます。バブルの表示は、完全更新または次回アプリ読み込み後に変更されます。",
    "CHAT_DELETE_HELPER_FALLBACK": "バックエンドのチャット削除制御サービスを読み込めなかったため、起動時ブートストラップが保護サービスを再度読み込めるまで、コード上のデフォルトが有効のままです。",
    "CHAT_DELETE_HELPER_SAVED": "「全員から削除」を利用できる時間枠がconfig_domain_registryに保存されました。バックエンドガードは直ちに変更されます。バブルの表示は、完全更新または次回アプリ読み込み後に変更されます。",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "バックエンドのチャット削除制御サービスが、要求されたウィンドウ値を保存できませんでした。",
    "CHAT_DELETE_WINDOW_LABEL": "全員から削除のウィンドウ",
    "CHAT_DELETE_WINDOW_SECONDS": "{count}秒",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "値は整数秒で保存してください。現在の本番値は86400秒 = 1日です。",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "ウィンドウ秒数",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "0以上の整数を入力してください。",
    "CHAT_DELETE_SAVE_BUTTON": "削除ウィンドウを保存",
    "GUEST_BANNER_CONTROL_TITLE": "ゲストバナー",
    "GUEST_BANNER_CONTROL_LABEL": "ゲストQRチャット",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "すべてのユーザーにゲストバナーを表示",
    "GUEST_BANNER_CONTROL_HELPER": "固定ゲストバナーと保留中のQRトークンの有効期間を制御します。",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "ゲストバナーコントロールのローカルフォールバックが有効です。",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "ゲストバナーコントロールが保存されました。",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "ゲストバナーコントロールを保存できませんでした。",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} 件のゲストセッションが取り消されました。",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "保留中のQRのTTL (分)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "現在の保留中QRのTTL: {count} 分。",
    "GUEST_BANNER_PENDING_TTL_INVALID": "分数を正の整数で入力してください。",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "ゲストバナーを保存",
    "GUEST_QR_LOADING": "ゲストQRを準備中...",
    "GUEST_QR_READY": "スキャンして一時的なゲストチャットを開きます。",
    "GUEST_QR_ALT": "ゲストチャットQRコード",
    "GUEST_QR_LOAD_FAILED": "ゲストQRを準備できませんでした。",
    "GUEST_SESSION_ACTIVE": "ゲストは接続中です。",
    "GUEST_PUBLIC_TITLE": "ゲストチャット",
    "GUEST_PUBLIC_CONNECTING": "接続中...",
    "GUEST_PUBLIC_CONNECTED": "接続済み",
    "GUEST_PUBLIC_UNAVAILABLE": "このゲストリンクは利用できません。",
    "GUEST_PUBLIC_SEND_FAILED": "メッセージを送信できませんでした。",
    "UI_TEXTS_RUNTIME_TITLE": "UI言語ランタイム",
    "UI_TEXTS_RUNTIME_BACKEND": "UI言語ランタイムは、保護されたバックエンドサービスから読み込んでいます。変更は、次回のアプリの完全な読み込み時に適用されます。",
    "UI_TEXTS_RUNTIME_CACHED": "現在、バックエンドのUI言語ランタイムサービスが利用できないため、キャッシュされたデータまたはローカルのデフォルトが有効になっています。",
    "UI_TEXTS_RUNTIME_DEFAULTS": "バックエンドまたはキャッシュされた状態を読み込めなかったため、UI言語のランタイムデフォルトが有効になっています。",
    "UI_TEXTS_RUNTIME_SAVED": "UI言語のランタイムコントロールが保存されました。ユーザーが新しい言語ゲートを受け取るには、完全な更新または次回のアプリの読み込みが必要です。",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "保護されたバックエンドサービスは、要求されたUI言語のランタイム変更を保存できませんでした。",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "デバイス言語の適用",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "ランタイムUI言語を有効にする",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "ユーザーは、保存されている言語またはデバイスの言語のUIテキストペイロードを受信できます。",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "すべてのユーザーのUIテキストは英語に強制され、デバイスの言語は無視されます。",
    "PROFILE_VISIBILITY_TITLE": "プロフィール表示",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "アカウント表示を管理するにはログインが必要です。",
    "PROFILE_VISIBILITY_HELPER": "このスイッチはアカウントの表示状態のみを更新します。このフェーズでは、発見可能性とバナーリストの動作は変更されません。",
    "PROFILE_VISIBILITY_LOAD_FAILED": "現在、プロフィール表示を読み込めません。",
    "PROFILE_VISIBILITY_SAVE_FAILED": "現在、プロフィール表示を更新できません。",
    "PROFILE_VISIBILITY_SAVED": "アカウント表示は現在{visibility}です。このフェーズでは発見可能性フラグは変更されません。",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "公開アカウント",
    "PROFILE_VISIBILITY_STORED": "保存済み表示状態",
    "WF1_MODEL_CONTROL_TITLE": "WF1モデル制御",
    "WF1_ENABLE_TRANSLATION": "翻訳 / ピボットを有効化",
    "WF1_TRANSLATION_ACTIVE": "AI翻訳が有効です。",
    "WF1_TRANSLATION_INACTIVE": "WF1は実行を続けますが、ソーステキストはコピーされ、ピボットは非アクティブとしてマークされます。",
    "WF1_ACTIVE_RUNTIME_SLOT": "アクティブなランタイムスロット",
    "WF1_ALLOW_SAME_LANGUAGE": "同一言語ペアでAIを許可",
    "WF1_SAME_LANGUAGE_ACTIVE": "同一言語ペアは通常のWF1ルーティングに従います。",
    "WF1_SAME_LANGUAGE_INACTIVE": "同一言語ペアはAIをバイパスし、No Pivot言語アクティブとして保存されます。",
    "WF1_QWEN_ROUTING": "Qwenペアルーティング",
    "WF1_QWEN_ROUTING_HELPER": "以下でチェックされた言語は、ペアが同じチェック済み言語、チェック済み言語と英語、または2つのチェック済み非英語言語のいずれかの場合にQwen-Maxを使用します。それ以外の場合、選択されたプライマリモデルが有効のままです。",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouterテストスロット",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouterテストスロット - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "品質テストのみ",
    "WF1_OPENROUTER_HELPER": "このスロットは、一時的なOpenRouter品質テストのためだけに編集できます。このスロット自体がアクティブモデルにならない限り、運用中のQwenペアルーティングパスは変更されません。",
    "WF1_LABEL": "ラベル",
    "WF1_PRODUCT": "製品",
    "WF1_MODEL": "モデル",
    "WF1_PROVIDER_OPENROUTER": "プロバイダー: OpenRouter",
    "WF1_SECRET_OPENROUTER": "シークレット: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouterテストスロット · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "OpenRouter経由のQwen-Max",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google定価",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI定価",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter定価",
    "LANGUAGE_ENGLISH": "英語",
    "LANGUAGE_CHINESE_SIMPLIFIED": "中国語（簡体字）",
    "LANGUAGE_CHINESE_TRADITIONAL": "中国語（繁体字）",
    "LANGUAGE_JAPANESE": "日本語",
    "LANGUAGE_KOREAN": "韓国語",
    "LANGUAGE_PERSIAN": "ペルシア語",
    "LANGUAGE_TURKISH_ISTANBUL": "トルコ語（イスタンブール）",
    "LANGUAGE_ARABIC": "アラビア語",
    "LANGUAGE_FRENCH": "フランス語",
    "LANGUAGE_GERMAN": "ドイツ語",
    "LANGUAGE_SPANISH": "スペイン語",
    "LANGUAGE_PORTUGUESE": "ポルトガル語",
    "LANGUAGE_ITALIAN": "イタリア語",
    "LANGUAGE_RUSSIAN": "ロシア語",
    "LANGUAGE_DUTCH": "オランダ語",
    "LANGUAGE_VIETNAMESE": "ベトナム語",
    "LANGUAGE_INDONESIAN": "インドネシア語",
    "LANGUAGE_THAI": "タイ語",
    "LANGUAGE_MALAY": "マレー語",
    "WF1_PRICING_CUSTOM": "価格: カスタムスロットモデル - 現在のOpenRouter価格を確認してください",
    "WF1_SAVE_OPENROUTER_SLOT": "OpenRouterスロットを保存",
    "WF1_PRICING_LINE": "入力 {input} - 出力 {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "シークレット: {secret}",
    "ZONE_VISIBILITY_TITLE": "ゾーン表示制御",
    "ZONE_ENABLE": "{zone}を有効化",
    "ZONE_ENABLED_NOTE": "{zone}は、次回アプリ読み込み後に許可されたロールに表示される場合があります。",
    "ZONE_DISABLED_NOTE": "{zone}は、次回アプリ読み込み後にS_Admin以外のユーザーには存在しないものとして扱われます。",
    "ZONE_S_ADMIN_BYPASS": "S_Adminはこのロールリストをバイパスし、常にアクセスを保持します。",
    "ZONE_ROLE_LOCKED": "このゾーンが無効な間、ロール選択は一時的にロックされ、ゾーンが再度有効になると保存されたとおりに戻ります。",
    "ZONE_LCAC_CONTROL": "LCAC制御",
    "ZONE_RCAC_CONTROL": "RCAC制御",
    "ZONE_LCAC_DESCRIPTION": "左側の予約ゾーンの存在と、それを表示できるロールを制御します。",
    "ZONE_RCAC_DESCRIPTION": "右側の予約ゾーンの存在と、それを表示できるロールを制御します。",
    "ZONE_VISIBILITY_BACKEND": "ゾーン表示のブートストラップは現在、保護されたバックエンドサービスから読み込んでいます。変更は次回アプリ読み込み時に適用されます。",
    "ZONE_VISIBILITY_CACHED": "バックエンドのゾーン表示サービスが現在利用できないため、キャッシュ済みまたはローカルのデフォルトが有効です。",
    "ZONE_VISIBILITY_DEFAULTS": "バックエンドまたはキャッシュ済み状態を読み込めなかったため、ゾーン表示のデフォルトが有効です。",
    "ZONE_VISIBILITY_SAVED": "ゾーン表示のブートストラップが保存されました。ランタイム適用には強制再読み込みまたは次回アプリ読み込みが必要です。",
    "ZONE_VISIBILITY_SAVE_FAILED": "保護されたバックエンドサービスが、要求されたゾーン表示変更を保存できませんでした。",
    "ROLE_MEMBER": "メンバー",
    "ROLE_STAFF": "スタッフ",
    "ROLE_ADMIN": "管理者",
    "ZONE_LCAC_V2": "LCAC（V2）",
    "ZONE_RCAC_V2": "RCAC（V2）",
    "MAIN_ENABLE_NOTIFICATIONS": "新しいメッセージを受け取るには通知を有効にしてください。",
    "MAIN_LOG_OUT": "ログアウト",
    "NOTIFICATION_NEW_MESSAGE": "新着メッセージ",
    "NOTIFICATION_UNREAD_MESSAGE": "未読メッセージがあります。",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "全体表示",
    "MEDIA_AUDIO_ATTACHMENT": "音声添付ファイル",
    "MEDIA_FILE_FALLBACK": "ファイル",
    "MEDIA_DOWNLOAD_READY": "添付ファイルをダウンロードできます",
    "MEDIA_TYPE_UNSUPPORTED": "全体表示ではサポートされていない種類です",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "前の画像",
    "MEDIA_NEXT_IMAGE_ARIA": "次の画像",
    "MEDIA_OPEN_ORIGINAL": "元を開く",
    "MEDIA_DOWNLOAD": "ダウンロード",
    "MEDIA_CLOSE_ARIA": "閉じる",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name}のプロフィール画像",
    "MEDIA_PROFILE_ALT": "{name}のプロフィール",
    "MEDIA_UPLOAD_FAILED": "アップロード失敗",
    "MEDIA_BACKEND_TOKEN_ERROR": "バックエンドトークンエラー",
    "MEDIA_UPLOAD_URL_MISSING": "重大: バックエンド応答にアップロードURLがありません。",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "チャットアップロード用の認証トークンがありません",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "チャットアップロードトークンのリクエストに失敗しました",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "チャットアップロード応答が無効です",
    "MEDIA_GCS_UPLOAD_FAILED": "GCSアップロード失敗",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "ファイル名またはcontentTypeがありません",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_pathがありません",
    "BLOCK_NOTICE_TITLE": "永久ブロック通知",
    "BLOCK_NOTICE_MESSAGE": "ポリシー違反により、あなたのアカウントは一時的に停止されています。",
    "BLOCK_NOTICE_CONTACT_PREFIX": "追加対応が必要だと思われる場合は、こちらまでご連絡ください",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "メールで。",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "不明なユーザー",
    "GENERAL_GUEST": "ゲスト",
    "ADVISOR_FOR_CLIENT": "{client_display_name}のアドバイザー",
    "GUEST_FOR_CLIENT": "{client_display_name}のゲスト",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "トークンとパスワードは必須です",
    "AUTH_ERROR_REQUEST_BODY_JSON": "リクエスト本文はJSONである必要があります",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "招待トークンが無効または期限切れです",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "パスワード設定に失敗しました: セッションまたはユーザーがありません",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "サインイン中にパスワード設定に失敗しました",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "管理者トークンの生成に失敗しました",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "ログインに失敗しました: セッションまたはユーザーがありません",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "登録に成功しました。確認のためメールをチェックしてください。",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "不明な登録失敗",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "トークン処理が無効です",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "アクセストークンは必須です",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "トークンハッシュプレビューには、リダイレクトURLからのメールヒントが必要です",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "このトークンのIDを解決できません",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "User ZeroのみがWF1 LLMセレクターサービスにアクセスできます。",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "User Zeroのみがゾーン表示制御サービスにアクセスできます。",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "User Zeroのみがフロントエンドバージョン制御サービスにアクセスできます。",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "User Zeroのみが他のユーザーのフロントエンドバージョンを検査できます。",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "User Zeroのみがチャット削除制御サービスにアクセスできます。",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "User ZeroのみがUI言語ランタイム制御サービスにアクセスできます。",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "User Zeroのみがユーザーアカウントを完全に削除できます。",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "リクエストペイロードが無効です。",
    "API_ERROR_INTERNAL_SERVER": "内部サーバーエラー",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "バックエンドに関数がありません（再読み込みが必要）",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "delivered/readの遷移にはDB RPCのみが許可されています。",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "別のメッセージを送信する前にお待ちください。",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "メッセージを正常に送信しました。",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "お問い合わせサービスを利用できません。",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "メッセージ送信に失敗しました。",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "名前は必須です。",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "メールアドレスが無効です。",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "メッセージは必須です。",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "セレクターペイロードは必須です。",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "ゾーン表示ペイロードは必須です。",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "フロントエンドバージョンペイロードは必須です。",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "チャット削除制御ペイロードは必須です。",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "UI言語ランタイム制御ペイロードが必要です。",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "認証済みユーザーIDは必須です。",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "認証済み閲覧者ユーザーIDは必須です。",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "認証済み実行者ユーザーIDは必須です。",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_idは必須です。",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_idは必須です。",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_idsリストは必須です。",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_emailは必須です。",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_byは必須です。",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "グローバルフロントエンドバージョンにより検索ランタイムが無効です。",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "この保留中の招待をキャンセルする権限がありません。",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "ユーザーがすでに登録済みのため、この招待はもうキャンセルできません。",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "保留中の招待が見つかりません。",
    "INVITE_REPLY_ALREADY_MEMBER": "おめでとうございます。あなたの友人（{invitee_email}）はすでにこのアプリに登録されており、このワークスペースのメンバーです。",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "{invitee_email}への招待は保留中ですが、再送メールをトリガーできませんでした。メールログを確認してください。",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "{invitee_email}の招待レコードは作成されましたが、メール配信を確認できませんでした。後でもう一度お試しいただくか、メールログを確認してください。",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "招待レコードの作成に失敗しました。後でもう一度お試しください。",
    "INVITE_REPLY_SYSTEM_ERROR": "招待処理中のシステムエラー: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "バックエンド設定エラー: Supabase認証情報がありません",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "バックエンド設定エラー: Supabase URLが無効です",
    "CHAT_ERROR_ACCESS_DENIED": "アクセス拒否",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "テキストメッセージの内容を空にすることはできません",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "会話IDを判定できませんでした",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC認証コンテキストがありません",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPCが無効なメッセージペイロードを返しました",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "挿入に失敗しました。データが返されませんでした",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operationsはリストである必要があります",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "操作ペイロードが無効です",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_typeはサポートされていません",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_idは必須です",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "メッセージが見つかりません",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "削除は自分のメッセージでのみ許可されています",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "このメッセージでは「全員から削除」はもう利用できません",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "全員から削除に失敗しました",
    "API_ERROR_SERVER_CONFIGURATION": "サーバー設定エラー",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "webhookシークレットヘッダーがありません",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "未承認のwebhookソース",
    "API_ERROR_BACKEND_CONFIGURATION": "バックエンド設定エラー",
    "API_ERROR_MODULE_ATTRIBUTE": "モジュール属性エラー: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "待機中の認証ユーザーを削除している間、招待削除前に失敗しました。",
    "CHAT_ERROR_DB": "DBエラー: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "PERMISSION_MIC_PERMISSION": "",
    "PERMISSION_MIC_ACCESS": "",
    "PERMISSION_TOGGLE_MIC_ARIA": "",
    "PERMISSION_MIC_ON_TOOLTIP": "",
    "PERMISSION_MIC_ENABLE_TOOLTIP": "",
    "PERMISSION_MIC_BLOCKED_TOOLTIP": "",
    "PERMISSION_MIC_DISABLE_HELP": "",
    "PERMISSION_MIC_BLOCKED_HELP": "",
    "LIVE_CONV_MIC_PROMPT_TITLE": "",
    "LIVE_CONV_MIC_PROMPT_BODY": "",
    "LIVE_CONV_MIC_PROMPT_ALLOW": "",
    "LIVE_CONV_MIC_PROMPT_CANCEL": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
