# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/ko.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "메인",
    "APP_TITLE": "OTMEGA AI 플랫폼",
    "APP_SUBTITLE": "AI 어드바이저",
    "CHAT_PLACEHOLDER": "메시지를 입력하세요...",
    "CHAT_SEND_BUTTON": "보내기",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 어드바이저는 실수할 수 있으므로 내용을 다시 확인하세요.",
    "STATUS_ONLINE": "온라인",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "메뉴",
    "ICON_NEW_CHAT": "새 채팅",
    "ICON_HISTORY": "기록",
    "ICON_TEMPLATES": "템플릿",
    "ICON_SETTINGS": "설정",
    "ICON_USER_PROFILE": "사용자 프로필",
    "ICON_QUICK_ACTIONS": "빠른 작업",
    "ICON_PINNED": "고정됨",
    "ICON_GALLERY": "갤러리",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "앱 설치",
    "PWA_ANDROID_MSG": "더 나은 경험과 오프라인 접근을 위해 이 앱을 기기에 설치하세요.",
    "PWA_IOS_MSG": "iPhone/iPad에 이 앱을 설치하려면:\n1. 아래의 공유 버튼을 탭하세요\n2. '홈 화면에 추가'를 선택하세요",
    "PWA_BTN_INSTALL": "설치",
    "PWA_BTN_LATER": "나중에",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "어드바이저 네트워크에 로그인",
    "AUTH_HEADER_SIGNUP": "통합 계정 만들기",
    "AUTH_HEADER_LOGIN_NETWORK": "어드바이저 네트워크에 로그인",
    "AUTH_HEADER_SIGNUP_UNIFIED": "통합 계정 만들기",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "로그인",
    "AUTH_BUTTON_SIGNUP": "계정 만들기",
    "AUTH_BUTTON_GOOGLE": "Google로 계속하기",
    "AUTH_BUTTON_FORGOT_PASSWORD": "비밀번호 찾기",
    "AUTH_BUTTON_SEND_RESET_LINK": "재설정 링크 보내기",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "계정이 없으신가요? 가입하기",
    "AUTH_PROMPT_LOGIN": "이미 계정이 있으신가요? 로그인",
    "AUTH_HELPER_TEXT_SIGNUP": "이 플랫폼의 모든 어드바이저에 접근할 수 있는 통합 계정을 만들고 있습니다.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "이 플랫폼의 모든 어드바이저에 접근할 수 있는 통합 계정을 만들고 있습니다.",
    "AUTH_HELPER_TEXT_LOGIN": "이 네트워크의 다른 어드바이저에서 사용한 동일한 계정(이메일/비밀번호 또는 Google)을 사용하세요.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "이 네트워크의 다른 어드바이저에서 사용한 동일한 계정(이메일/비밀번호 또는 Google)을 사용하세요.",
    "AUTH_FORGOT_PASSWORD_LINK": "비밀번호를 잊으셨나요?",
    "AUTH_FORGOT_PASSWORD_TITLE": "비밀번호 재설정",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "이메일 주소를 입력하면 비밀번호 재설정 링크를 보내드립니다.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "이메일",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "로그인 중...",
    "AUTH_STATUS_LOADING_SIGNUP": "계정 생성 중...",
    "AUTH_STATUS_LOADING_RESET": "재설정 링크 보내는 중...",
    "AUTH_STATUS_SUCCESS_LOGIN": "로그인 성공! 다시 불러오는 중...",
    "AUTH_STATUS_SUCCESS_RESET": "재설정 링크를 성공적으로 보냈습니다. 이메일을 확인하세요.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "비밀번호 재설정 링크를 성공적으로 보냈습니다. 이메일을 확인하세요.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "이메일 또는 비밀번호가 올바르지 않습니다.",
    "AUTH_ERROR_EMAIL_EXISTS": "이 이메일의 계정이 어드바이저 네트워크에 이미 존재합니다.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "이 이메일의 계정이 이미 존재합니다. 로그인하세요. 현재 다음의 멤버입니다:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "이 이메일의 계정이 어드바이저 네트워크에 이미 존재합니다. 이 창을 닫고 동일한 이메일과 이전 비밀번호로 '로그인' 섹션을 사용하세요.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "현재 다음의 멤버입니다:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "이메일과 비밀번호가 필요합니다.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "계정은 생성되었지만 멤버십 설정에 실패했습니다. 지원팀에 문의하세요.",
    "AUTH_ERROR_DEFAULT": "오류가 발생했습니다. 다시 시도하세요.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "게스트 배너 제어 페이로드가 필요합니다.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "User Zero만 게스트 배너 컨트롤을 업데이트할 수 있습니다.",
    "AUTH_FORGOT_PASSWORD_ERROR": "재설정 링크를 보내지 못했습니다. 다시 시도하세요.",
    "INVITE_REPLY_EMAIL_SENT": "Collabra 초대 이메일이 {invitee_email} 주소의 친구에게 전송되었습니다.",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra 초대 이메일이 {invitee_email} 주소의 친구에게 다시 전송되었습니다.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "비밀번호 표시",
    "AUTH_PASSWORD_TOGGLE_HIDE": "비밀번호 숨기기",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "확인",
    "GENERAL_CANCEL": "취소",
    "GENERAL_CLOSE": "닫기",
    "GENERAL_SEND": "보내기",
    "GENERAL_SEARCH": "검색",
    "GENERAL_RESET": "재설정",
    "GENERAL_ENABLE": "활성화",
    "GENERAL_LOADING": "로딩 중...",
    "GENERAL_DELETE": "삭제",
    "GENERAL_DELETING": "삭제 중...",
    "GENERAL_SAVE_PASSWORD": "비밀번호 저장",
    "AUTH_REMEMBER_EMAIL_LABEL": "이메일 기억하기",
    "GENERAL_SAVING": "저장 중...",
    "GENERAL_SENDING": "전송 중...",
    "GENERAL_REMOVING": "제거 중...",
    "GENERAL_CONFIRM_REMOVAL": "제거 확인",
    "GENERAL_EMPTY": "비어 있음",
    "GENERAL_UNAVAILABLE": "사용할 수 없음",
    "GENERAL_ENABLED": "활성화됨",
    "GENERAL_DISABLED": "비활성화됨",
    "GENERAL_GRANTED": "허용됨",
    "GENERAL_DENIED": "거부됨",
    "GENERAL_DEFAULT": "기본값",
    "GENERAL_UNSUPPORTED": "지원되지 않음",
    "GENERAL_PUBLIC": "공개",
    "GENERAL_PRIVATE": "비공개",
    "GENERAL_USERNAME": "사용자 이름",
    "GENERAL_EMAIL": "이메일",
    "GENERAL_YOU": "나",
    "GENERAL_USER": "사용자",
    "GENERAL_UNKNOWN": "알 수 없음",
    "GENERAL_VISITOR": "방문자",
    "GENERAL_PROFILE": "프로필",
    "GENERAL_BANNER": "배너",
    "GENERAL_UNKNOWN_BANNER": "알 수 없는 배너",
    "GENERAL_ADVISOR_BANNER": "어드바이저 배너",
    "GENERAL_NOT_AVAILABLE": "해당 없음",
    "GENERAL_NOT_SELECTED": "선택되지 않음",
    "GENERAL_NO_EMAIL_FOUND": "이메일을 찾을 수 없음",
    "GENERAL_USER_ZERO_ONLY": "User Zero 전용",
    "GENERAL_CONNECTION_STATE": "연결 상태",
    "GENERAL_DISPLAY_ONLY": "표시 전용",
    "GENERAL_TEXTAREA": "텍스트 영역",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "메뉴 (LCAC)",
    "HEADER_CHAT_CCAC": "채팅 (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "빠른 작업 (RCAC)",
    "HEADER_CHANGE_STATUS": "상태 변경",
    "HEADER_OT_COIN_BALANCE": "OT Coin 잔액",
    "HEADER_ALT_USER": "사용자",
    "STATUS_BUSY": "바쁨",
    "STATUS_AWAY": "자리 비움",
    "STATUS_OFFLINE": "오프라인",
    "STATUS_INVISIBLE": "보이지 않음",
    "NETWORK_CHECKING_CONNECTION": "연결 확인 중...",
    "NETWORK_ONLINE_LATENCY": "온라인 (지연 시간: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "네트워크: 양호 (탭하여 ping)",
    "CHAT_TARGET_ALT": "채팅 대상",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "검색...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "{name}의 프로필 사진 열기",
    "CHAT_MESSAGE_INPUT_ARIA": "메시지 입력",
    "CHAT_TOGGLE_VIEW_ARIA": "보기 전환",
    "CHAT_ADD_USER_ARIA": "사용자 추가",
    "CHAT_ATTACH_ARIA": "첨부",
    "CHAT_MIC_ARIA": "마이크",
    "CHAT_SEND_ARIA": "보내기",
    "CHAT_SEARCH_ARIA": "검색",
    "CHAT_OPEN_SEARCH_ARIA": "검색 열기",
    "CHAT_CLOSE_SEARCH_ARIA": "검색 닫기",
    "CHAT_ATTACHMENT_ALT": "첨부 파일",
    "CHAT_PREVIEW_ALT": "미리보기",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "첨부 파일 제거",
    "CHAT_REPLYING_TO": "답장 대상",
    "CHAT_CANCEL_REPLY_ARIA": "답장 취소",
    "CHAT_UPLOADING": "업로드 중...",
    "CHAT_LOADING_CHATS": "채팅 불러오는 중...",
    "CHAT_SEND_FAILED": "전송 실패",
    "CHAT_SEND_FAILED_RETRY": "전송에 실패했습니다. 다시 시도하세요.",
    "CHAT_RETRY": "다시 시도",
    "CHAT_EDITED": "수정됨",
    "CHAT_TYPING": "입력 중",
    "CHAT_LOADING": "로딩 중",
    "CHAT_PENDING_INVITATION": "대기 중인 초대",
    "CHAT_PENDING_INVITATION_MIN": "{count}분 대기 중인 초대",
    "CHAT_PENDING_INVITATION_HR": "{count}시간 대기 중인 초대",
    "CHAT_PENDING_INVITATION_DAY": "{count}일 대기 중인 초대",
    "CHAT_WAITING_FOR_YOU": "{label} - 응답 대기 중",
    "CHAT_PENDING_ACCEPTANCE": "{label} - 수락 대기 중",
    "CHAT_MICROPHONE_ACCESS_DENIED": "마이크 접근이 거부되었습니다.",
    "CHAT_UPLOAD_FAILED": "업로드 실패: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "업로드에는 인터넷 연결이 필요합니다. 온라인 상태일 때 다시 시도하세요.",
    "CHAT_ERROR_AUTH": "인증 오류",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "파일 이름 또는 content_type이 없습니다",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id 또는 target_id가 없습니다",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "아바타가 아닌 업로드에는 conversation_id가 필요합니다",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "잘못된 아바타 file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase 서비스 클라이언트를 사용할 수 없습니다",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "아바타 읽음 확인은 어드바이저 채팅 컨텍스트에서만 유효합니다",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "아바타 흐름 메시지를 찾을 수 없거나 읽음 확인 대상이 아닙니다",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "아바타 메시지를 읽음으로 최종 처리하지 못했습니다",
    "CHAT_ATTACHMENT_COUNT_ONE": "첨부 파일 1개",
    "CHAT_ATTACHMENT_COUNT_MANY": "첨부 파일 {count}개",
    "CHAT_VOICE_NOTE": "음성 메모",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "채팅을 사용할 수 없습니다. 이 사용자가 당신을 차단했습니다.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "채팅을 사용할 수 없습니다. 당신이 이 사용자를 차단했습니다.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "계정 접근이 정책에 의해 차단되었습니다.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "채팅을 사용할 수 없습니다. 이 계정은 User Zero에 의해 최종 차단되었습니다.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "채팅을 사용할 수 없습니다. 상호 차단이 활성화되어 있습니다.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "차단 정책으로 인해 채팅을 사용할 수 없습니다.",
    "MESSAGE_PREVIEW_PHOTO": "사진",
    "MESSAGE_PREVIEW_VOICE": "음성 메시지",
    "MESSAGE_PREVIEW_VIDEO": "동영상",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "파일",
    "MESSAGE_PREVIEW_MESSAGE": "메시지",
    "MESSAGE_PREVIEW_SYSTEM": "시스템 메시지",
    "MESSAGE_PREVIEW_NEW": "새 메시지",
    "MESSAGE_UNKNOWN_FILE": "알 수 없는 파일",
    "MESSAGE_AUDIO_ATTACHMENT": "오디오 첨부 파일",
    "MESSAGE_FILE_ATTACHMENT": "첨부 파일",
    "BANNER_INVITED_BY": "{label} 님이 초대함",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "검색 결과",
    "SEARCH_QUERY_LABEL": "쿼리:",
    "SEARCH_LOADING_VISIBILITY": "검색 표시 설정을 불러오는 중...",
    "SEARCH_NO_RESULTS": "현재 검색 범위에서 결과를 찾을 수 없습니다.",
    "SHARE_WITH_COLLABRA": "Collabra와 공유",
    "SHARE_SEND_TO": "보낼 대상",
    "SHARE_SELECT_ONE_BANNER": "배너 하나를 선택하세요",
    "SHARE_BANNER_LIST_ARIA": "배너 목록",
    "SHARE_NO_MATCHING_BANNER": "일치하는 배너가 없습니다",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "댓글 추가...",
    "SHARE_RECENT_CHATS": "최근 채팅",
    "SHARE_LEFT_LIST": "왼쪽 목록",
    "SHARE_RIGHT_LIST": "오른쪽 목록",
    "SHARE_UNTITLED_BANNER": "제목 없는 배너",
    "SHARE_SHARED_CONTENT": "공유된 콘텐츠",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "공유된 콘텐츠를 열 수 없습니다.",
    "SHARE_OPEN_BANNER_FAILED": "선택한 배너를 열 수 없습니다.",
    "SHARE_ONE_PHOTO_SELECTED": "사진 1장 선택됨",
    "SHARE_MANY_PHOTOS_SELECTED": "사진 {count}장 선택됨",
    "SHARE_ONE_FILE_SELECTED": "파일 1개 선택됨",
    "SHARE_MANY_FILES_SELECTED": "파일 {count}개 선택됨",
    "FORWARD_MESSAGE_TITLE": "메시지 전달",
    "FORWARD_SELECT_RECIPIENTS": "수신자 선택",
    "FORWARD_NO_OTHER_BANNER": "사용 가능한 다른 배너가 없습니다.",
    "FORWARD_SEND_TO_COUNT": "{count}명에게 보내기",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "배너를 하나 이상 선택하세요.",
    "FORWARD_FAILED_DEFAULT": "전달에 실패했습니다. 다시 시도하세요.",
    "FORWARD_PARTIAL_SENT": "{count}개 전송됨. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "전달할 원본 메시지를 찾을 수 없습니다",
    "FORWARD_NO_FORWARDABLE_CONTENT": "이 메시지에는 아직 전달 가능한 콘텐츠가 없습니다",
    "FORWARD_DESTINATION_MISSING": "전달 대상이 없습니다",
    "FORWARD_MESSAGE_PREVIEW": "전달된 메시지",
    "MENU_PASTE": "붙여넣기",
    "MENU_COPY": "복사",
    "MENU_REPLY": "답장",
    "MENU_FORWARD": "전달",
    "MENU_REMOVE_INVITATION": "초대 제거",
    "MENU_REMOVE_FROM_LIST": "목록에서 제거",
    "MENU_GOODBYE_GUEST": "게스트 로그아웃",
    "MENU_ADD_TO_LIST": "목록에 추가",
    "MENU_REJECT_INVITATION": "초대 거절",
    "MENU_FRONTEND_VERSION": "프런트엔드 버전",
    "MENU_BANNER_HEADER": "배너 - {zone}",
    "MENU_BANNER_INFO": "배너 정보: {title}",
    "MENU_MESSAGE_BUBBLE": "메시지 버블",
    "MENU_CHAT_CANVAS_HEADER": "채팅 캔버스 - {zone}",
    "MENU_CANVAS_INFO": "캔버스 정보",
    "MENU_CHAT_CANVAS_SUBLABEL": "대화 영역 / 현재 채팅 표면",
    "MENU_INPUT_AREA_HEADER": "입력 영역 - {zone}",
    "MENU_INPUT_AREA_INFO": "입력 영역 정보: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "하단 입력 및 작업 도구 영역",
    "MENU_HEADER": "헤더 - {zone}",
    "MENU_HEADER_INFO": "헤더 정보: {title}",
    "MENU_HEADER_DESCRIPTION": "상단 탐색 및 페이지 컨트롤",
    "MENU_ZONE_HEADER": "영역 - {zone}",
    "MENU_ZONE_SPACE_INFO": "영역 공간 정보",
    "MENU_EMPTY_LIST_SURFACE": "빈/목록 표면",
    "MENU_BLOCK": "차단",
    "MENU_UNBLOCK": "차단 해제",
    "MENU_HIDE_IN_SEARCH": "검색에서 숨기기",
    "MENU_UNHIDE_IN_SEARCH": "검색에 표시",
    "MENU_VISIBLE_IN_SEARCH": "검색에 표시됨",
    "MENU_HIDDEN_IN_SEARCH": "검색에서 숨겨짐",
    "MENU_VISIBLE_IN_USER_LIST": "사용자 목록에 표시됨",
    "MENU_HIDDEN_IN_USER_LIST": "사용자 목록에서 숨겨짐",
    "MENU_NOT_BLOCKED": "차단되지 않음",
    "MENU_BLOCKED": "차단됨",
    "MENU_FRONTEND_VERSION_LOADING": "로딩 중...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "백엔드에서 배너별 값을 불러오는 중입니다. 데이터베이스 응답이 도착할 때까지 어떤 옵션도 활성으로 표시되지 않습니다.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "백엔드 값을 불러올 수 없습니다. 신뢰할 수 있는 활성 옵션이 표시되지 않습니다.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "명시적인 배너별 데이터베이스 값은 {overrideVersion}입니다. 전역 기본값은 {globalDefaultVersion}입니다. 대상 사용자는 시작 부트스트랩이 이를 적용하려면 앱을 완전히 새로고침하거나 다시 열어야 합니다.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "명시적인 배너별 데이터베이스 값이 저장되어 있지 않습니다. FeV2.0.0이 기본으로 활성화되어 있습니다. 전역 기본값은 {globalDefaultVersion}입니다.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "대상 앱이 완전히 다시 로드된 후 명시적인 배너별 데이터베이스 값이 활성화됩니다",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "명시적인 배너별 값이 저장되어 있지 않습니다. 이는 기본 개별 FeV2.0.0 상태입니다",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "이 옵션은 현재 전역 기본값과도 같습니다",
    "MENU_DELETE_PERMANENT_CONFIRM": "데이터베이스에서 {target}을(를) 영구 삭제하시겠습니까? 계정, 채팅 기록, 종속 항목이 제거되며 향후 재진입 시 완전히 새로운 초대 경로가 필요합니다.",
    "MENU_DELETE_PERMANENTLY": "영구 삭제",
    "MENU_REFRESH_PAGE": "페이지 새로고침",
    "MENU_LOG_OFF": "로그오프",
    "MENU_HARD_RELOAD": "강제 새로고침",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "이메일 (관리자 사용자)",
    "AUTH_PASSWORD_PLACEHOLDER": "비밀번호",
    "AUTH_CONNECTING": "연결 중...",
    "AUTH_SIGNING_OUT": "로그아웃 중...",
    "AUTH_BACK_TO_LOGIN": "로그인으로 돌아가기",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "잘못된 서버 응답: 토큰을 찾을 수 없습니다.",
    "AUTH_LOGIN_FAILED": "로그인 실패",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "비밀번호가 일치하지 않습니다.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "비밀번호가 일치하지 않습니다!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "비밀번호는 정확히 일치해야 합니다.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "새 비밀번호",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "비밀번호 확인",
    "AUTH_CHANGE_PASSWORD": "비밀번호 변경",
    "AUTH_SAVING_PASSWORD": "저장 중...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "비밀번호가 성공적으로 업데이트되었습니다.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "지금은 비밀번호를 변경할 수 없습니다.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "비밀번호를 변경하려면 로그인해야 합니다.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "새 비밀번호 표시 전환",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "비밀번호 확인 표시 전환",
    "REGISTER_TITLE": "등록 완료",
    "REGISTER_SUBTITLE": "비밀번호를 수동으로 설정하세요.",
    "REGISTER_CREATING_ACCOUNT": "계정 생성 중...",
    "REGISTER_FINISH_SETUP": "설정 완료",
    "REGISTER_FAILED_SET_PASSWORD": "비밀번호 설정 실패",
    "INVITE_EMAIL_INSTRUCTION": "초대받을 사람의 이메일을 입력하세요 (형식: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "초대",
    "INVITE_EMAIL_REQUIRED": "초대받을 사람의 이메일을 입력하세요.",
    "INVITE_EMAIL_INVALID": "잘못된 이메일 형식입니다. 다음 형식을 사용하세요: user@example.com",
    "PENDING_INVITATION_TITLE": "대기 중인 초대",
    "PENDING_INVITATION_REMOVE_QUESTION": "이 대기 중인 초대를 데이터베이스에서 제거하시겠습니까?",
    "PENDING_INVITATION_KEEP": "초대 유지",
    "PENDING_INVITATION_REMOVAL_FAILED": "제거에 실패했습니다.",
    "REMOVE_FROM_LIST_TITLE": "목록에서 제거",
    "REMOVE_FROM_LIST_WARNING": "지금 이 사용자를 두 목록 모두에서 제거하시겠습니까? 채팅 접근이 즉시 차단됩니다. 다시 들어오는 유일한 경로는 새 초대입니다.",
    "REMOVE_FROM_LIST_KEEP": "사용자를 목록에 유지",
    "REMOVE_FROM_LIST_FAILED": "목록에서 제거하지 못했습니다.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "설정 및 실시간 상태",
    "PERMISSION_DIALOG_ARIA": "설정 및 실시간 상태",
    "PERMISSION_TRIGGER_ARIA": "설정 팝업 트리거",
    "PERMISSION_CLOSE_ARIA": "권한 팝업 닫기",
    "PERMISSION_LIVE_STATUS": "실시간 상태",
    "PERMISSION_SYSTEM_PERMISSION": "시스템 권한",
    "PERMISSION_APP_PUSH": "앱 푸시",
    "PERMISSION_LOCATION_PERMISSION": "위치 권한",
    "PERMISSION_APP_LOCATION": "앱 위치",
    "PERMISSION_CONTROLS": "권한 컨트롤",
    "PERMISSION_PUSH_NOTIFICATIONS": "푸시 알림",
    "PERMISSION_LOCATION_ACCESS": "위치 접근",
    "PERMISSION_IN_APP_SETTINGS": "앱 내 설정",
    "PERMISSION_ALERT_SOUND": "알림음",
    "PERMISSION_APP_BADGE": "앱 배지",
    "PERMISSION_PASSWORD_SETTINGS": "비밀번호 설정",
    "PERMISSION_NAVIGATION_STATUS": "탐색 상태",
    "PERMISSION_SELECTED_ZONE": "선택된 영역",
    "PERMISSION_STAGED_CHAT_BANNER": "스테이징된 채팅 배너",
    "PERMISSION_CANVAS_CONTENT": "캔버스 콘텐츠",
    "PERMISSION_YOUR_DEVICES": "내 기기 ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "기기 목록 새로고침",
    "PERMISSION_REFRESH_LIST": "목록 새로고침",
    "PERMISSION_NO_REGISTERED_DEVICES": "등록된 기기를 찾을 수 없습니다.",
    "PERMISSION_RESIZE_POPUP_ARIA": "설정 팝업 크기 조정",
    "PERMISSION_TOGGLE_PUSH_ARIA": "푸시 알림 전환",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "위치 접근 전환",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "알림음 전환",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "앱 배지 전환",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "프로필 표시 여부 전환",
    "PERMISSION_OFF_IN_V1": "v1에서 꺼짐",
    "PERMISSION_CHAT": "채팅",
    "PERMISSION_BANNER_LIST": "배너 목록",
    "PERMISSION_PUSH_DISABLED_V1": "v1 Google Play 릴리스에서는 푸시 알림이 비활성화되어 있습니다.",
    "PERMISSION_PUSH_ON_TOOLTIP": "이 기기에서 푸시 알림이 켜져 있습니다.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "시스템 알림이 차단되어 있습니다. 설정 도움말을 열려면 탭하세요.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "전달 안정성을 높이려면 켜세요.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "시스템 알림을 비활성화하려면 브라우저/사이트 알림 설정을 열고 이 사이트를 차단으로 설정하세요.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "시스템 알림 권한을 변경하려면 브라우저/사이트 알림 설정을 열고 이 사이트를 허용으로 설정하세요.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "거리 기반 LCAC 정렬 및 지도 위치 지정에 위치 접근이 켜져 있습니다.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "이 환경에서는 위치 API가 지원되지 않습니다.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "위치 접근이 차단되어 있습니다. 설정 도움말을 열려면 탭하세요.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "정밀한 거리 기반 LCAC 정렬 및 앱 내 지도 위치 지정을 허용하려면 켜세요.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "이 환경에서는 위치 접근이 지원되지 않습니다.",
    "PERMISSION_LOCATION_DISABLE_HELP": "위치 접근을 비활성화하려면 브라우저/사이트 위치 설정을 열고 이 사이트를 차단으로 설정하세요.",
    "PERMISSION_LOCATION_ALLOW_HELP": "거리 정렬 및 앱 내 지도 위치 지정을 위해 위치 접근을 활성화하려면 브라우저/사이트 위치 설정을 열고 이 사이트를 허용으로 설정하세요.",
    "PERMISSION_DEVICE_LOAD_FAILED": "현재 등록된 기기를 불러올 수 없습니다.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "UI 브리지 로딩 중...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "로컬 브리지 로딩 중...",
    "RUNTIME_LOADING_BACKEND": "백엔드 로딩 중...",
    "RUNTIME_LOADING": "로딩 중...",
    "RUNTIME_LOADING_FROM_DATABASE": "데이터베이스에서 로딩 중...",
    "RUNTIME_BACKEND_CONNECTED": "백엔드 연결됨",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "캐시된 대체값 활성",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "기본 대체값 활성",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "대체 기본값 활성",
    "RUNTIME_SAVING_THROUGH_BACKEND": "백엔드를 통해 저장 중...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "백엔드 서비스에 저장됨",
    "RUNTIME_SAVE_FAILED": "저장 실패",
    "RUNTIME_LOAD_FAILED": "로드 실패",
    "RUNTIME_CONNECTED": "연결됨",
    "RUNTIME_LOGIN_REQUIRED": "로그인 필요",
    "RUNTIME_SAVED": "저장됨",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI 준비됨 - 런타임 대기 중",
    "RUNTIME_BACKEND_REJECTED_MODEL": "보호된 백엔드 선택기 서비스가 요청한 모델 옵션을 거부했거나 저장할 수 없습니다.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "보호된 백엔드 선택기 서비스가 요청한 WF1 라우팅 변경을 거부했거나 저장할 수 없습니다.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "선택기가 이제 보호된 백엔드 서비스에서 활성 구성, Qwen 라우팅 및 허용된 옵션을 읽고 있습니다.",
    "RUNTIME_WF1_SELECTOR_CACHED": "현재 백엔드 선택기 서비스를 사용할 수 없어 마지막 캐시된 선택기 상태가 사용됩니다.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "백엔드 또는 캐시된 선택기 상태를 불러올 수 없어 선택기 기본값이 활성화되어 있습니다.",
    "RUNTIME_WF1_SELECTOR_SAVED": "보호된 백엔드 선택기 서비스가 활성 WF1 라우팅 구성을 업데이트하고 런타임 도메인 캐시를 새로고침했습니다.",
    "FRONTEND_VERSION_TITLE": "프런트엔드 버전",
    "FRONTEND_VERSION_HELPER_ACTIVE": "이 선택기는 모든 사용자의 활성 프런트엔드 버전을 제어합니다. FeV2.0.0이 활성화되어 있습니다.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "이 선택기는 config_domain_registry에서 활성 프런트엔드 버전을 읽습니다. 런타임은 FeV2.0.0으로 해석됩니다.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "백엔드 프런트엔드 버전 구성을 불러올 수 없어, 시작 부트스트랩이 보호된 서비스를 다시 읽을 수 있을 때까지 코드화된 FeV2.0.0 기본값이 활성 상태로 유지됩니다.",
    "FRONTEND_VERSION_HELPER_SAVED": "활성 프런트엔드 버전이 config_domain_registry에 저장되었습니다. 전체 새로고침 또는 다음 앱 로드 시 런타임 값이 적용됩니다.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "백엔드 프런트엔드 버전 제어 서비스가 요청한 전역 버전을 저장할 수 없습니다.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "활성 프런트엔드 버전입니다.",
    "CHAT_DELETE_WINDOW_TITLE": "채팅 삭제 기간",
    "CHAT_DELETE_HELPER": "이 값은 모두에게 삭제 가능 기간을 초 단위로 제어합니다. 저장 후 백엔드 가드는 즉시 변경됩니다. 버블 표시 여부는 전체 새로고침 또는 다음 앱 로드 후 변경됩니다.",
    "CHAT_DELETE_HELPER_FALLBACK": "백엔드 채팅 삭제 제어 서비스를 불러올 수 없어, 시작 부트스트랩이 보호된 서비스를 다시 읽을 수 있을 때까지 코드화된 기본값이 활성 상태로 유지됩니다.",
    "CHAT_DELETE_HELPER_SAVED": "모두에게 삭제 가능 기간이 config_domain_registry에 저장되었습니다. 백엔드 가드는 즉시 변경됩니다. 버블 표시 여부는 전체 새로고침 또는 다음 앱 로드 후 변경됩니다.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "백엔드 채팅 삭제 제어 서비스가 요청한 기간 값을 저장할 수 없습니다.",
    "CHAT_DELETE_WINDOW_LABEL": "모두에게 삭제 기간",
    "CHAT_DELETE_WINDOW_SECONDS": "{count}초",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "값을 정수 초 단위로 저장하세요. 현재 프로덕션 값은 86400초 = 1일입니다.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "기간 초",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "0 이상인 정수를 입력하세요.",
    "CHAT_DELETE_SAVE_BUTTON": "삭제 기간 저장",
    "GUEST_BANNER_CONTROL_TITLE": "게스트 배너",
    "GUEST_BANNER_CONTROL_LABEL": "게스트 QR 채팅",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "모든 사용자에게 게스트 배너 표시",
    "GUEST_BANNER_CONTROL_HELPER": "고정된 게스트 배너와 대기 중인 QR 토큰 수명을 제어합니다.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "게스트 배너 제어에 로컬 폴백이 활성화되어 있습니다.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "게스트 배너 컨트롤이 저장되었습니다.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "게스트 배너 컨트롤을 저장할 수 없습니다.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count}개의 게스트 세션이 취소되었습니다.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "보류 중인 QR TTL(분)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "현재 보류 중인 QR TTL: {count}분.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "양의 정수(분)를 입력하세요.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "게스트 배너 저장",
    "GUEST_QR_LOADING": "게스트 QR 준비 중...",
    "GUEST_QR_READY": "스캔하여 임시 게스트 채팅을 여세요.",
    "GUEST_QR_ALT": "게스트 채팅 QR 코드",
    "GUEST_QR_LOAD_FAILED": "게스트 QR을 준비할 수 없습니다.",
    "GUEST_SESSION_ACTIVE": "게스트가 연결되었습니다.",
    "GUEST_PUBLIC_TITLE": "게스트 채팅",
    "GUEST_PUBLIC_CONNECTING": "연결 중...",
    "GUEST_PUBLIC_CONNECTED": "연결됨",
    "GUEST_PUBLIC_UNAVAILABLE": "이 게스트 링크는 사용할 수 없습니다.",
    "GUEST_PUBLIC_SEND_FAILED": "메시지를 보낼 수 없습니다.",
    "UI_TEXTS_RUNTIME_TITLE": "UI 언어 런타임",
    "UI_TEXTS_RUNTIME_BACKEND": "UI 언어 런타임이 보호된 백엔드 서비스에서 읽고 있습니다. 변경 사항은 다음에 앱을 전체 로드할 때 적용됩니다.",
    "UI_TEXTS_RUNTIME_CACHED": "백엔드 UI 언어 런타임 서비스를 지금 사용할 수 없으므로 캐시된 또는 로컬 기본값이 활성화됩니다.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "백엔드 또는 캐시된 상태를 로드할 수 없었기 때문에 UI 언어 런타임 기본값이 활성화됩니다.",
    "UI_TEXTS_RUNTIME_SAVED": "UI 언어 런타임 제어가 저장되었습니다. 사용자가 새로운 언어 게이트를 받으려면 전체 새로고침 또는 다음 앱 로드가 필요합니다.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "보호된 백엔드 서비스가 요청된 UI 언어 런타임 변경 사항을 저장할 수 없었습니다.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "기기 언어 적용",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "런타임 UI 언어 활성화",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "사용자는 저장된 언어 또는 기기 언어에 대한 UI 텍스트 페이로드를 받을 수 있습니다.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "모든 사용자는 영어 UI 텍스트를 강제로 사용하게 되며 기기 언어는 무시됩니다.",
    "PROFILE_VISIBILITY_TITLE": "프로필 표시 여부",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "계정 표시 여부를 관리하려면 로그인해야 합니다.",
    "PROFILE_VISIBILITY_HELPER": "이 스위치는 계정 표시 상태만 업데이트합니다. 이 단계에서는 검색 가능성과 배너 목록 동작은 변경되지 않습니다.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "현재 프로필 표시 여부를 불러올 수 없습니다.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "현재 프로필 표시 여부를 업데이트할 수 없습니다.",
    "PROFILE_VISIBILITY_SAVED": "계정 표시 여부가 이제 {visibility}입니다. 이 단계에서는 검색 가능성 플래그가 변경되지 않습니다.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "공개 계정",
    "PROFILE_VISIBILITY_STORED": "저장된 표시 여부",
    "WF1_MODEL_CONTROL_TITLE": "WF1 모델 제어",
    "WF1_ENABLE_TRANSLATION": "번역 / 피벗 활성화",
    "WF1_TRANSLATION_ACTIVE": "AI 번역이 활성화되어 있습니다.",
    "WF1_TRANSLATION_INACTIVE": "WF1은 계속 실행되지만 원본 텍스트가 복사되고 피벗은 비활성으로 표시됩니다.",
    "WF1_ACTIVE_RUNTIME_SLOT": "활성 런타임 슬롯",
    "WF1_ALLOW_SAME_LANGUAGE": "동일 언어 쌍에 AI 허용",
    "WF1_SAME_LANGUAGE_ACTIVE": "동일 언어 쌍은 일반 WF1 라우팅을 따릅니다.",
    "WF1_SAME_LANGUAGE_INACTIVE": "동일 언어 쌍은 AI를 우회하고 활성 피벗 언어 없음으로 저장됩니다.",
    "WF1_QWEN_ROUTING": "Qwen 쌍 라우팅",
    "WF1_QWEN_ROUTING_HELPER": "아래에서 선택된 언어는 쌍이 동일한 선택 언어이거나, 선택 언어와 영어이거나, 두 개의 선택된 비영어 언어일 때 Qwen-Max를 사용합니다. 그렇지 않으면 선택된 기본 모델이 활성 상태로 유지됩니다.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter 테스트 슬롯",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter 테스트 슬롯 - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "품질 테스트 전용",
    "WF1_OPENROUTER_HELPER": "이 슬롯은 임시 OpenRouter 품질 테스트용으로만 편집할 수 있습니다. 이 슬롯 자체가 활성 모델이 되지 않는 한 운영 Qwen 쌍 라우팅 경로를 변경하지 않습니다.",
    "WF1_LABEL": "라벨",
    "WF1_PRODUCT": "제품",
    "WF1_MODEL": "모델",
    "WF1_PROVIDER_OPENROUTER": "제공자: OpenRouter",
    "WF1_SECRET_OPENROUTER": "시크릿: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter 테스트 슬롯 · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "OpenRouter를 통한 Qwen-Max",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google 정가",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI 정가",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter 정가",
    "LANGUAGE_ENGLISH": "영어",
    "LANGUAGE_CHINESE_SIMPLIFIED": "중국어 (간체)",
    "LANGUAGE_CHINESE_TRADITIONAL": "중국어 (번체)",
    "LANGUAGE_JAPANESE": "일본어",
    "LANGUAGE_KOREAN": "한국어",
    "LANGUAGE_PERSIAN": "페르시아어",
    "LANGUAGE_TURKISH_ISTANBUL": "터키어 (이스탄불)",
    "LANGUAGE_ARABIC": "아랍어",
    "LANGUAGE_FRENCH": "프랑스어",
    "LANGUAGE_GERMAN": "독일어",
    "LANGUAGE_SPANISH": "스페인어",
    "LANGUAGE_PORTUGUESE": "포르투갈어",
    "LANGUAGE_ITALIAN": "이탈리아어",
    "LANGUAGE_RUSSIAN": "러시아어",
    "LANGUAGE_DUTCH": "네덜란드어",
    "LANGUAGE_VIETNAMESE": "베트남어",
    "LANGUAGE_INDONESIAN": "인도네시아어",
    "LANGUAGE_THAI": "태국어",
    "LANGUAGE_MALAY": "말레이어",
    "WF1_PRICING_CUSTOM": "가격: 사용자 지정 슬롯 모델 - 현재 OpenRouter 가격을 확인하세요",
    "WF1_SAVE_OPENROUTER_SLOT": "OpenRouter 슬롯 저장",
    "WF1_PRICING_LINE": "입력 {input} - 출력 {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "시크릿: {secret}",
    "ZONE_VISIBILITY_TITLE": "영역 표시 제어",
    "ZONE_ENABLE": "{zone} 활성화",
    "ZONE_ENABLED_NOTE": "{zone}은(는) 다음 앱 로드 후 허용된 역할에 표시될 수 있습니다.",
    "ZONE_DISABLED_NOTE": "{zone}은(는) 다음 앱 로드 후 S_Admin이 아닌 사용자에게 없는 것으로 처리됩니다.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin은 이 역할 목록을 우회하고 항상 접근을 유지합니다.",
    "ZONE_ROLE_LOCKED": "이 영역이 비활성화된 동안 역할 선택이 일시적으로 잠기며, 영역이 다시 활성화되면 저장된 그대로 복원됩니다.",
    "ZONE_LCAC_CONTROL": "LCAC 제어",
    "ZONE_RCAC_CONTROL": "RCAC 제어",
    "ZONE_LCAC_DESCRIPTION": "왼쪽 예약 영역의 존재와 이를 볼 수 있는 역할을 제어합니다.",
    "ZONE_RCAC_DESCRIPTION": "오른쪽 예약 영역의 존재와 이를 볼 수 있는 역할을 제어합니다.",
    "ZONE_VISIBILITY_BACKEND": "영역 표시 부트스트랩이 이제 보호된 백엔드 서비스에서 읽고 있습니다. 변경 사항은 다음 앱 로드 시 적용됩니다.",
    "ZONE_VISIBILITY_CACHED": "현재 백엔드 영역 표시 서비스를 사용할 수 없어 캐시된 값 또는 로컬 기본값이 활성화되어 있습니다.",
    "ZONE_VISIBILITY_DEFAULTS": "백엔드 또는 캐시된 상태를 불러올 수 없어 영역 표시 기본값이 활성화되어 있습니다.",
    "ZONE_VISIBILITY_SAVED": "영역 표시 부트스트랩이 저장되었습니다. 런타임 적용에는 강제 새로고침 또는 다음 앱 로드가 필요합니다.",
    "ZONE_VISIBILITY_SAVE_FAILED": "보호된 백엔드 서비스가 요청한 영역 표시 변경을 저장할 수 없습니다.",
    "ROLE_MEMBER": "멤버",
    "ROLE_STAFF": "스태프",
    "ROLE_ADMIN": "관리자",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "새 메시지를 받으려면 알림을 활성화하세요.",
    "MAIN_LOG_OUT": "로그아웃",
    "NOTIFICATION_NEW_MESSAGE": "새 메시지",
    "NOTIFICATION_UNREAD_MESSAGE": "읽지 않은 메시지가 있습니다.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "전체 보기",
    "MEDIA_AUDIO_ATTACHMENT": "오디오 첨부 파일",
    "MEDIA_FILE_FALLBACK": "파일",
    "MEDIA_DOWNLOAD_READY": "첨부 파일을 다운로드할 준비가 되었습니다",
    "MEDIA_TYPE_UNSUPPORTED": "전체 보기에서 지원되지 않는 형식",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "이전 이미지",
    "MEDIA_NEXT_IMAGE_ARIA": "다음 이미지",
    "MEDIA_OPEN_ORIGINAL": "원본 열기",
    "MEDIA_DOWNLOAD": "다운로드",
    "MEDIA_CLOSE_ARIA": "닫기",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name}의 프로필 사진",
    "MEDIA_PROFILE_ALT": "{name}의 프로필",
    "MEDIA_UPLOAD_FAILED": "업로드 실패",
    "MEDIA_BACKEND_TOKEN_ERROR": "백엔드 토큰 오류",
    "MEDIA_UPLOAD_URL_MISSING": "중요: 백엔드 응답에 업로드 URL이 없습니다.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "채팅 업로드용 인증 토큰이 없습니다",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "채팅 업로드 토큰 요청에 실패했습니다",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "잘못된 채팅 업로드 응답",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS 업로드 실패",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "파일 이름 또는 contentType이 없습니다",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path가 없습니다",
    "BLOCK_NOTICE_TITLE": "영구 차단 알림",
    "BLOCK_NOTICE_MESSAGE": "정책 위반으로 인해 계정이 일시적으로 정지되었습니다.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "추가 확인이 필요하다고 생각하시면 다음으로 문의하세요",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "이메일로.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "알 수 없는 사용자",
    "GENERAL_GUEST": "게스트",
    "ADVISOR_FOR_CLIENT": "{client_display_name}을(를) 위한 어드바이저",
    "GUEST_FOR_CLIENT": "{client_display_name}의 게스트",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "토큰과 비밀번호가 필요합니다",
    "AUTH_ERROR_REQUEST_BODY_JSON": "요청 본문은 JSON이어야 합니다",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "초대 토큰이 잘못되었거나 만료되었습니다",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "비밀번호 설정 실패: 세션 또는 사용자가 없습니다",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "로그인 중 비밀번호 설정에 실패했습니다",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "관리자 토큰 생성에 실패했습니다",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "로그인 실패: 세션 또는 사용자가 없습니다",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "등록이 성공했습니다. 인증을 위해 이메일을 확인하세요.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "알 수 없는 가입 실패",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "잘못된 토큰 처리",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "접근 토큰이 필요합니다",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "토큰 해시 미리보기에는 리디렉션 URL의 이메일 힌트가 필요합니다",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "이 토큰에 대한 신원을 확인할 수 없습니다",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "User Zero만 WF1 LLM 선택기 서비스에 접근할 수 있습니다.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "User Zero만 영역 표시 제어 서비스에 접근할 수 있습니다.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "User Zero만 프런트엔드 버전 제어 서비스에 접근할 수 있습니다.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "User Zero만 다른 사용자의 프런트엔드 버전을 검사할 수 있습니다.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "User Zero만 채팅 삭제 제어 서비스에 접근할 수 있습니다.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "User Zero만 UI 언어 런타임 제어 서비스에 액세스할 수 있습니다.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "User Zero만 사용자 계정을 영구 삭제할 수 있습니다.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "잘못된 요청 페이로드입니다.",
    "API_ERROR_INTERNAL_SERVER": "내부 서버 오류",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "백엔드에 함수가 없습니다 (새로고침 필요)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "delivered/read 전환에는 DB RPC만 허용됩니다.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "다른 메시지를 보내기 전에 잠시 기다려 주세요.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "메시지가 성공적으로 전송되었습니다.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "문의 서비스를 사용할 수 없습니다.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "메시지 전송에 실패했습니다.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "이름이 필요합니다.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "이메일이 올바르지 않습니다.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "메시지가 필요합니다.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "선택기 페이로드가 필요합니다.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "영역 표시 페이로드가 필요합니다.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "프런트엔드 버전 페이로드가 필요합니다.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "채팅 삭제 제어 페이로드가 필요합니다.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "UI 언어 런타임 제어 페이로드가 필요합니다.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "인증된 사용자 ID가 필요합니다.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "인증된 조회자 사용자 ID가 필요합니다.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "인증된 행위자 사용자 ID가 필요합니다.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id가 필요합니다.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id가 필요합니다.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids 목록이 필요합니다.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email이 필요합니다.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by가 필요합니다.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "전역 프런트엔드 버전에 의해 검색 런타임이 비활성화되어 있습니다.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "이 대기 중인 초대를 취소할 권한이 없습니다.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "사용자가 이미 등록되어 있어 이 초대는 더 이상 취소할 수 없습니다.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "대기 중인 초대를 찾을 수 없습니다.",
    "INVITE_REPLY_ALREADY_MEMBER": "축하합니다. 친구({invitee_email})는 이미 이 앱에 등록되어 있으며 이 워크스페이스의 멤버입니다.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "{invitee_email}에 대한 초대가 대기 중이지만 재시도 이메일을 트리거할 수 없습니다. 메일 로그를 확인하세요.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "{invitee_email}에 대한 초대 레코드가 생성되었지만 이메일 전달을 확인할 수 없습니다. 나중에 다시 시도하거나 메일 로그를 확인하세요.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "초대 레코드 생성에 실패했습니다. 나중에 다시 시도하세요.",
    "INVITE_REPLY_SYSTEM_ERROR": "초대 처리 중 시스템 오류: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "백엔드 구성 오류: Supabase 자격 증명이 없습니다",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "백엔드 구성 오류: 잘못된 Supabase URL",
    "CHAT_ERROR_ACCESS_DENIED": "접근 거부",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "텍스트 메시지의 콘텐츠는 비어 있을 수 없습니다",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "대화 ID를 결정할 수 없습니다",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC 인증 컨텍스트가 없습니다",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC가 잘못된 메시지 페이로드를 반환했습니다",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "삽입 실패, 반환된 데이터가 없습니다",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations는 목록이어야 합니다",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "잘못된 작업 페이로드",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "지원되지 않는 operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id가 필요합니다",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "메시지를 찾을 수 없습니다",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "삭제는 자신의 메시지에만 허용됩니다",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "이 메시지에서는 더 이상 모두에게 삭제를 사용할 수 없습니다",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "모두에게 삭제에 실패했습니다",
    "API_ERROR_SERVER_CONFIGURATION": "서버 구성 오류",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "webhook secret 헤더가 없습니다",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "허가되지 않은 webhook 소스",
    "API_ERROR_BACKEND_CONFIGURATION": "백엔드 구성 오류",
    "API_ERROR_MODULE_ATTRIBUTE": "모듈 속성 오류: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "대기 중인 인증 사용자를 제거하는 동안 초대 삭제 전에 실패했습니다.",
    "CHAT_ERROR_DB": "DB 오류: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
