# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/en.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Utama",
    "APP_TITLE": "Platform AI OTMEGA",
    "APP_SUBTITLE": "Penasihat AI",
    "CHAT_PLACEHOLDER": "Taip mesej anda...",
    "CHAT_SEND_BUTTON": "Hantar",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Penasihat boleh membuat kesilapan, jadi semak semula.",
    "STATUS_ONLINE": "Dalam talian",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Sembang Baharu",
    "ICON_HISTORY": "Sejarah",
    "ICON_TEMPLATES": "Templat",
    "ICON_SETTINGS": "Tetapan",
    "ICON_USER_PROFILE": "Profil Pengguna",
    "ICON_QUICK_ACTIONS": "Tindakan Pantas",
    "ICON_PINNED": "Dipin",
    "ICON_GALLERY": "Galeri",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Pasang Aplikasi",
    "PWA_ANDROID_MSG": "Pasang aplikasi ini pada peranti anda untuk pengalaman yang lebih baik dan akses luar talian.",
    "PWA_IOS_MSG": "Untuk memasang aplikasi ini pada iPhone/iPad anda:\n1. Ketik butang Kongsi di bawah\n2. Pilih 'Tambah ke Skrin Utama'",
    "PWA_BTN_INSTALL": "Pasang",
    "PWA_BTN_LATER": "Mungkin Kemudian",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Log masuk ke Rangkaian Penasihat",
    "AUTH_HEADER_SIGNUP": "Cipta Akaun Bersepadu Anda",
    "AUTH_HEADER_LOGIN_NETWORK": "Log masuk ke Rangkaian Penasihat",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Cipta Akaun Bersepadu Anda",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Log Masuk",
    "AUTH_BUTTON_SIGNUP": "Cipta Akaun",
    "AUTH_BUTTON_GOOGLE": "Teruskan dengan Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Lupa Kata Laluan",
    "AUTH_BUTTON_SEND_RESET_LINK": "Hantar Pautan Tetapan Semula",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Belum ada akaun? Daftar",
    "AUTH_PROMPT_LOGIN": "Sudah ada akaun? Log masuk",
    "AUTH_HELPER_TEXT_SIGNUP": "Anda sedang mencipta akaun bersepadu yang boleh digunakan untuk mengakses semua penasihat di platform ini.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Anda sedang mencipta akaun bersepadu yang boleh digunakan untuk mengakses semua penasihat di platform ini.",
    "AUTH_HELPER_TEXT_LOGIN": "Gunakan akaun yang sama (e-mel/kata laluan atau Google) yang anda gunakan untuk penasihat lain dalam rangkaian ini.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Gunakan akaun yang sama (e-mel/kata laluan atau Google) yang anda gunakan untuk penasihat lain dalam rangkaian ini.",
    "AUTH_FORGOT_PASSWORD_LINK": "Lupa kata laluan anda?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Tetapkan Semula Kata Laluan Anda",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Masukkan alamat e-mel anda dan kami akan menghantar pautan untuk menetapkan semula kata laluan anda.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-mel",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Sedang log masuk...",
    "AUTH_STATUS_LOADING_SIGNUP": "Sedang mencipta akaun anda...",
    "AUTH_STATUS_LOADING_RESET": "Menghantar pautan tetapan semula...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Log masuk berjaya! Memuat semula...",
    "AUTH_STATUS_SUCCESS_RESET": "Pautan tetapan semula berjaya dihantar. Sila semak e-mel anda.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Pautan tetapan semula kata laluan berjaya dihantar. Sila semak e-mel anda.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "E-mel atau kata laluan tidak sah.",
    "AUTH_ERROR_EMAIL_EXISTS": "Akaun dengan e-mel ini sudah wujud dalam rangkaian penasihat.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Akaun dengan e-mel ini sudah wujud. Sila log masuk. Anda kini ahli kepada:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Akaun dengan e-mel ini sudah wujud dalam rangkaian penasihat. Sila tutup tetingkap ini dan gunakan bahagian 'Login' dengan e-mel yang sama dan kata laluan terdahulu anda.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Anda kini ahli kepada:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-mel dan kata laluan diperlukan.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Akaun dicipta tetapi gagal menyediakan keahlian. Sila hubungi sokongan.",
    "AUTH_ERROR_DEFAULT": "Ralat berlaku. Sila cuba lagi.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Gagal menghantar pautan tetapan semula. Sila cuba lagi.",
    "INVITE_REPLY_EMAIL_SENT": "E-mel jemputan Collabra telah dihantar kepada rakan anda di {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "E-mel jemputan Collabra telah dihantar semula kepada rakan anda di {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Tunjukkan kata laluan",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Sembunyikan kata laluan",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Batal",
    "GENERAL_CLOSE": "Tutup",
    "GENERAL_SEND": "Hantar",
    "GENERAL_SEARCH": "Cari",
    "GENERAL_RESET": "Tetapkan Semula",
    "GENERAL_ENABLE": "Dayakan",
    "GENERAL_LOADING": "Memuatkan...",
    "GENERAL_DELETE": "Padam",
    "GENERAL_DELETING": "Memadam...",
    "GENERAL_SAVE_PASSWORD": "Simpan Kata Laluan",
    "AUTH_REMEMBER_EMAIL_LABEL": "Ingat e-mel",
    "GENERAL_SAVING": "Menyimpan...",
    "GENERAL_SENDING": "Menghantar...",
    "GENERAL_REMOVING": "Mengalih keluar...",
    "GENERAL_CONFIRM_REMOVAL": "Sahkan Pengalihan Keluar",
    "GENERAL_EMPTY": "Kosong",
    "GENERAL_UNAVAILABLE": "Tidak tersedia",
    "GENERAL_ENABLED": "Didayakan",
    "GENERAL_DISABLED": "Dilumpuhkan",
    "GENERAL_GRANTED": "Diberikan",
    "GENERAL_DENIED": "Ditolak",
    "GENERAL_DEFAULT": "Lalai",
    "GENERAL_UNSUPPORTED": "Tidak disokong",
    "GENERAL_PUBLIC": "Awam",
    "GENERAL_PRIVATE": "Peribadi",
    "GENERAL_USERNAME": "Nama pengguna",
    "GENERAL_EMAIL": "E-mel",
    "GENERAL_YOU": "Anda",
    "GENERAL_USER": "Pengguna",
    "GENERAL_UNKNOWN": "Tidak diketahui",
    "GENERAL_VISITOR": "Pelawat",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Sepanduk",
    "GENERAL_UNKNOWN_BANNER": "Sepanduk Tidak Diketahui",
    "GENERAL_ADVISOR_BANNER": "Sepanduk Penasihat",
    "GENERAL_NOT_AVAILABLE": "T/S",
    "GENERAL_NOT_SELECTED": "Belum Dipilih",
    "GENERAL_NO_EMAIL_FOUND": "Tiada e-mel ditemui",
    "GENERAL_USER_ZERO_ONLY": "User Zero Sahaja",
    "GENERAL_CONNECTION_STATE": "Keadaan Sambungan",
    "GENERAL_DISPLAY_ONLY": "Paparan sahaja",
    "GENERAL_TEXTAREA": "Kawasan teks",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Sembang (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Tindakan Pantas (RCAC)",
    "HEADER_CHANGE_STATUS": "Tukar Status",
    "HEADER_OT_COIN_BALANCE": "Baki OT Coin",
    "HEADER_ALT_USER": "Pengguna",
    "STATUS_BUSY": "Sibuk",
    "STATUS_AWAY": "Tiada",
    "STATUS_OFFLINE": "Luar talian",
    "STATUS_INVISIBLE": "Tidak kelihatan",
    "NETWORK_CHECKING_CONNECTION": "Memeriksa sambungan...",
    "NETWORK_ONLINE_LATENCY": "Dalam talian (Latensi: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Rangkaian: Baik (ketik untuk ping)",
    "CHAT_TARGET_ALT": "Sasaran sembang",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Cari...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Buka gambar profil {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Input mesej",
    "CHAT_TOGGLE_VIEW_ARIA": "Togol paparan",
    "CHAT_ADD_USER_ARIA": "Tambah pengguna",
    "CHAT_ATTACH_ARIA": "Lampirkan",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Hantar",
    "CHAT_SEARCH_ARIA": "Cari",
    "CHAT_OPEN_SEARCH_ARIA": "Buka carian",
    "CHAT_CLOSE_SEARCH_ARIA": "Tutup carian",
    "CHAT_ATTACHMENT_ALT": "Lampiran",
    "CHAT_PREVIEW_ALT": "Pratonton",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Alih keluar lampiran",
    "CHAT_REPLYING_TO": "Membalas kepada",
    "CHAT_CANCEL_REPLY_ARIA": "Batalkan balasan",
    "CHAT_UPLOADING": "Memuat naik...",
    "CHAT_LOADING_CHATS": "Memuatkan Sembang...",
    "CHAT_SEND_FAILED": "Penghantaran Gagal",
    "CHAT_SEND_FAILED_RETRY": "Penghantaran gagal. Sila cuba semula.",
    "CHAT_RETRY": "Cuba semula",
    "CHAT_EDITED": "diedit",
    "CHAT_TYPING": "Sedang menaip",
    "CHAT_LOADING": "Memuatkan",
    "CHAT_PENDING_INVITATION": "Jemputan belum selesai",
    "CHAT_PENDING_INVITATION_MIN": "{count} min jemputan belum selesai",
    "CHAT_PENDING_INVITATION_HR": "{count} jam jemputan belum selesai",
    "CHAT_PENDING_INVITATION_DAY": "{count} hari jemputan belum selesai",
    "CHAT_WAITING_FOR_YOU": "{label} - Menunggu anda",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Menunggu penerimaan",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Akses mikrofon ditolak.",
    "CHAT_UPLOAD_FAILED": "Muat naik gagal: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Muat naik memerlukan sambungan Internet. Sila cuba lagi apabila anda berada dalam talian.",
    "CHAT_ERROR_AUTH": "Ralat Pengesahan",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nama fail atau content_type hilang",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id atau target_id hilang",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id hilang untuk muat naik bukan avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path avatar tidak sah",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Klien perkhidmatan Supabase tidak tersedia",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Pengakuan baca avatar hanya sah dalam konteks sembang penasihat",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Mesej aliran avatar tidak ditemui atau tidak layak untuk pengakuan baca",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Gagal memuktamadkan mesej avatar sebagai dibaca",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 lampiran",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} lampiran",
    "CHAT_VOICE_NOTE": "Nota Suara",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Sembang tidak tersedia. Pengguna ini menyekat anda.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Sembang tidak tersedia. Anda menyekat pengguna ini.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Akses akaun disekat oleh dasar.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Sembang tidak tersedia. Akaun ini disekat akhir oleh User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Sembang tidak tersedia. Sekatan bersama aktif.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Sembang tidak tersedia disebabkan dasar sekatan.",
    "MESSAGE_PREVIEW_PHOTO": "Foto",
    "MESSAGE_PREVIEW_VOICE": "Mesej suara",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Fail",
    "MESSAGE_PREVIEW_MESSAGE": "Mesej",
    "MESSAGE_PREVIEW_SYSTEM": "Mesej sistem",
    "MESSAGE_PREVIEW_NEW": "Mesej baharu",
    "MESSAGE_UNKNOWN_FILE": "Fail Tidak Diketahui",
    "MESSAGE_AUDIO_ATTACHMENT": "Lampiran audio",
    "MESSAGE_FILE_ATTACHMENT": "Lampiran",
    "BANNER_INVITED_BY": "dijemput oleh {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Hasil Carian",
    "SEARCH_QUERY_LABEL": "Pertanyaan:",
    "SEARCH_LOADING_VISIBILITY": "Memuatkan keterlihatan carian...",
    "SEARCH_NO_RESULTS": "Tiada hasil ditemui dalam skop carian semasa.",
    "SHARE_WITH_COLLABRA": "Kongsi dengan Collabra",
    "SHARE_SEND_TO": "Hantar kepada",
    "SHARE_SELECT_ONE_BANNER": "Pilih satu sepanduk",
    "SHARE_BANNER_LIST_ARIA": "Senarai sepanduk",
    "SHARE_NO_MATCHING_BANNER": "Tiada sepanduk yang sepadan",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Tambah komen...",
    "SHARE_RECENT_CHATS": "Sembang terkini",
    "SHARE_LEFT_LIST": "Senarai kiri",
    "SHARE_RIGHT_LIST": "Senarai kanan",
    "SHARE_UNTITLED_BANNER": "Sepanduk tanpa tajuk",
    "SHARE_SHARED_CONTENT": "Kandungan dikongsi",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Kandungan dikongsi tidak dapat dibuka.",
    "SHARE_OPEN_BANNER_FAILED": "Tidak dapat membuka sepanduk yang dipilih.",
    "SHARE_ONE_PHOTO_SELECTED": "1 foto dipilih",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} foto dipilih",
    "SHARE_ONE_FILE_SELECTED": "1 fail dipilih",
    "SHARE_MANY_FILES_SELECTED": "{count} fail dipilih",
    "FORWARD_MESSAGE_TITLE": "Majukan Mesej",
    "FORWARD_SELECT_RECIPIENTS": "Pilih penerima",
    "FORWARD_NO_OTHER_BANNER": "Tiada sepanduk lain tersedia.",
    "FORWARD_SEND_TO_COUNT": "Hantar kepada {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Pilih sekurang-kurangnya satu sepanduk.",
    "FORWARD_FAILED_DEFAULT": "Pemajuan gagal. Sila cuba lagi.",
    "FORWARD_PARTIAL_SENT": "{count} dihantar. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Mesej sumber tidak ditemui untuk dimajukan",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Mesej ini belum mempunyai kandungan yang boleh dimajukan",
    "FORWARD_DESTINATION_MISSING": "Destinasi pemajuan hilang",
    "FORWARD_MESSAGE_PREVIEW": "Mesej dimajukan",
    "MENU_PASTE": "Tampal",
    "MENU_COPY": "Salin",
    "MENU_REPLY": "Balas",
    "MENU_FORWARD": "Majukan",
    "MENU_REMOVE_INVITATION": "Alih Keluar Jemputan",
    "MENU_REMOVE_FROM_LIST": "Alih Keluar Daripada Senarai",
    "MENU_ADD_TO_LIST": "Tambah Ke Senarai",
    "MENU_REJECT_INVITATION": "Tolak Jemputan",
    "MENU_FRONTEND_VERSION": "Versi Frontend",
    "MENU_BANNER_HEADER": "Sepanduk - {zone}",
    "MENU_BANNER_INFO": "Maklumat Sepanduk: {title}",
    "MENU_MESSAGE_BUBBLE": "Gelembung Mesej",
    "MENU_CHAT_CANVAS_HEADER": "Kanvas Sembang - {zone}",
    "MENU_CANVAS_INFO": "Maklumat Kanvas",
    "MENU_CHAT_CANVAS_SUBLABEL": "Kawasan perbualan / permukaan sembang semasa",
    "MENU_INPUT_AREA_HEADER": "Kawasan Input - {zone}",
    "MENU_INPUT_AREA_INFO": "Maklumat Kawasan Input: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Permukaan bawah untuk menaip dan alat tindakan",
    "MENU_HEADER": "Pengepala - {zone}",
    "MENU_HEADER_INFO": "Maklumat Pengepala: {title}",
    "MENU_HEADER_DESCRIPTION": "Navigasi atas dan kawalan halaman",
    "MENU_ZONE_HEADER": "Zon - {zone}",
    "MENU_ZONE_SPACE_INFO": "Maklumat Ruang Zon",
    "MENU_EMPTY_LIST_SURFACE": "Permukaan kosong/senarai",
    "MENU_BLOCK": "Sekat",
    "MENU_UNBLOCK": "Nyahsekat",
    "MENU_HIDE_IN_SEARCH": "Sembunyikan Dalam Carian",
    "MENU_UNHIDE_IN_SEARCH": "Tunjukkan Dalam Carian",
    "MENU_VISIBLE_IN_SEARCH": "Kelihatan Dalam Carian",
    "MENU_HIDDEN_IN_SEARCH": "Tersembunyi Dalam Carian",
    "MENU_VISIBLE_IN_USER_LIST": "Kelihatan Dalam Senarai Pengguna",
    "MENU_HIDDEN_IN_USER_LIST": "Tersembunyi Dalam Senarai Pengguna",
    "MENU_NOT_BLOCKED": "Tidak Disekat",
    "MENU_BLOCKED": "Disekat",
    "MENU_FRONTEND_VERSION_LOADING": "Memuatkan...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Memuatkan nilai per sepanduk daripada backend. Tiada pilihan ditandakan aktif sehingga respons pangkalan data tiba.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Nilai backend tidak dapat dimuatkan. Tiada pilihan aktif yang dipercayai dipaparkan.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Nilai eksplisit per sepanduk dalam pangkalan data ialah {overrideVersion}. Lalai global ialah {globalDefaultVersion}. Pengguna sasaran mesti menyegarkan sepenuhnya atau membuka semula aplikasi agar bootstrap permulaan menerapkannya.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Tiada nilai eksplisit per sepanduk disimpan. FeV2.0.0 aktif secara lalai. Lalai global ialah {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Nilai eksplisit per sepanduk aktif selepas aplikasi sasaran dimuat semula sepenuhnya",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Tiada nilai eksplisit per sepanduk disimpan; ini ialah keadaan individu FeV2.0.0 lalai",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Pilihan ini juga sama dengan lalai global semasa",
    "MENU_DELETE_PERMANENT_CONFIRM": "Padam {target} secara kekal daripada pangkalan data? Ini memadam akaun, sejarah sembang, pergantungan, dan memaksa laluan jemputan baharu sepenuhnya untuk kemasukan semula pada masa hadapan.",
    "MENU_DELETE_PERMANENTLY": "Padam Secara Kekal",
    "MENU_REFRESH_PAGE": "Muat Semula Halaman",
    "MENU_LOG_OFF": "Log Keluar",
    "MENU_HARD_RELOAD": "Muat Semula Paksa",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-mel (Pengguna Admin)",
    "AUTH_PASSWORD_PLACEHOLDER": "Kata laluan",
    "AUTH_CONNECTING": "Menyambung...",
    "AUTH_SIGNING_OUT": "Sedang Log Keluar...",
    "AUTH_BACK_TO_LOGIN": "Kembali ke Log Masuk",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Respons pelayan tidak sah: Tiada token ditemui.",
    "AUTH_LOGIN_FAILED": "Log Masuk Gagal",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Kata laluan tidak sepadan.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Kata laluan tidak sepadan!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Kata laluan mesti sepadan dengan tepat.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Kata Laluan Baharu",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Sahkan Kata Laluan",
    "AUTH_CHANGE_PASSWORD": "Tukar Kata Laluan",
    "AUTH_SAVING_PASSWORD": "Menyimpan...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Kata laluan berjaya dikemas kini.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Tidak dapat menukar kata laluan sekarang.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Anda mesti log masuk untuk menukar kata laluan anda.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Togol keterlihatan kata laluan baharu",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Togol keterlihatan pengesahan kata laluan",
    "REGISTER_TITLE": "Lengkapkan Pendaftaran",
    "REGISTER_SUBTITLE": "Sila tetapkan kata laluan anda secara manual.",
    "REGISTER_CREATING_ACCOUNT": "Mencipta Akaun...",
    "REGISTER_FINISH_SETUP": "Selesaikan Persediaan",
    "REGISTER_FAILED_SET_PASSWORD": "Gagal menetapkan kata laluan",
    "INVITE_EMAIL_INSTRUCTION": "Sila masukkan e-mel jemputan (Format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Jemput",
    "INVITE_EMAIL_REQUIRED": "Sila masukkan e-mel jemputan.",
    "INVITE_EMAIL_INVALID": "Format e-mel tidak sah. Sila gunakan: user@example.com",
    "PENDING_INVITATION_TITLE": "Jemputan Belum Selesai",
    "PENDING_INVITATION_REMOVE_QUESTION": "Padam jemputan belum selesai ini daripada pangkalan data?",
    "PENDING_INVITATION_KEEP": "Kekalkan Jemputan",
    "PENDING_INVITATION_REMOVAL_FAILED": "Pengalihan keluar gagal.",
    "REMOVE_FROM_LIST_TITLE": "Alih Keluar Daripada Senarai",
    "REMOVE_FROM_LIST_WARNING": "Alih keluar pengguna ini daripada kedua-dua senarai sekarang? Akses sembang akan diputuskan serta-merta. Satu-satunya laluan kembali ialah jemputan baharu.",
    "REMOVE_FROM_LIST_KEEP": "Kekalkan Pengguna Dalam Senarai",
    "REMOVE_FROM_LIST_FAILED": "Alih keluar daripada senarai gagal.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Tetapan & Status Langsung",
    "PERMISSION_DIALOG_ARIA": "Tetapan dan Status Langsung",
    "PERMISSION_TRIGGER_ARIA": "Pencetus popup tetapan",
    "PERMISSION_CLOSE_ARIA": "Tutup popup kebenaran",
    "PERMISSION_LIVE_STATUS": "Status Langsung",
    "PERMISSION_SYSTEM_PERMISSION": "Kebenaran Sistem",
    "PERMISSION_APP_PUSH": "Push Aplikasi",
    "PERMISSION_LOCATION_PERMISSION": "Kebenaran Lokasi",
    "PERMISSION_APP_LOCATION": "Lokasi Aplikasi",
    "PERMISSION_CONTROLS": "Kawalan Kebenaran",
    "PERMISSION_PUSH_NOTIFICATIONS": "Pemberitahuan push",
    "PERMISSION_LOCATION_ACCESS": "Akses lokasi",
    "PERMISSION_IN_APP_SETTINGS": "Tetapan Dalam Aplikasi",
    "PERMISSION_ALERT_SOUND": "Bunyi amaran",
    "PERMISSION_APP_BADGE": "Lencana aplikasi",
    "PERMISSION_PASSWORD_SETTINGS": "Tetapan kata laluan",
    "PERMISSION_NAVIGATION_STATUS": "Status navigasi",
    "PERMISSION_SELECTED_ZONE": "Zon dipilih",
    "PERMISSION_STAGED_CHAT_BANNER": "Sepanduk sembang dipentaskan",
    "PERMISSION_CANVAS_CONTENT": "Kandungan kanvas",
    "PERMISSION_YOUR_DEVICES": "Peranti anda ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Segarkan senarai peranti",
    "PERMISSION_REFRESH_LIST": "Segarkan Senarai",
    "PERMISSION_NO_REGISTERED_DEVICES": "Tiada peranti berdaftar ditemui.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Ubah saiz popup tetapan",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Togol pemberitahuan push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Togol akses lokasi",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Togol bunyi amaran",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Togol lencana aplikasi",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Togol keterlihatan profil",
    "PERMISSION_OFF_IN_V1": "Dimatikan dalam v1",
    "PERMISSION_CHAT": "Sembang",
    "PERMISSION_BANNER_LIST": "Senarai Sepanduk",
    "PERMISSION_PUSH_DISABLED_V1": "Pemberitahuan push dilumpuhkan untuk keluaran v1 Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Pemberitahuan push HIDUP untuk peranti ini.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Pemberitahuan sistem disekat. Ketik untuk membuka bantuan tetapan.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "HIDUPKAN untuk meningkatkan kebolehpercayaan penghantaran.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Untuk melumpuhkan pemberitahuan sistem, buka tetapan pemberitahuan pelayar/tapak anda dan tetapkan tapak ini kepada Sekat.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Untuk menukar kebenaran pemberitahuan sistem, buka tetapan pemberitahuan pelayar/tapak anda dan tetapkan tapak ini kepada Benarkan.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Akses lokasi HIDUP untuk pengisihan LCAC berasaskan jarak dan kedudukan peta.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API lokasi tidak disokong dalam persekitaran ini.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Akses lokasi disekat. Ketik untuk membuka bantuan tetapan.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "HIDUPKAN untuk membenarkan pengisihan LCAC berasaskan jarak yang tepat dan kedudukan peta dalam aplikasi.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Akses lokasi tidak disokong dalam persekitaran ini.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Untuk melumpuhkan akses lokasi, buka tetapan lokasi pelayar/tapak anda dan tetapkan tapak ini kepada Sekat.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Untuk mendayakan akses lokasi bagi pengisihan jarak dan kedudukan peta dalam aplikasi, buka tetapan lokasi pelayar/tapak anda dan tetapkan tapak ini kepada Benarkan.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Tidak dapat memuatkan peranti berdaftar sekarang.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Memuatkan UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Memuatkan Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Memuatkan Backend...",
    "RUNTIME_LOADING": "Memuatkan...",
    "RUNTIME_LOADING_FROM_DATABASE": "Memuatkan Dari Pangkalan Data...",
    "RUNTIME_BACKEND_CONNECTED": "Backend Bersambung",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Fallback Cache Aktif",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback Lalai Aktif",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Lalai Fallback Aktif",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Menyimpan Melalui Backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Disimpan Dalam Perkhidmatan Backend",
    "RUNTIME_SAVE_FAILED": "Simpan Gagal",
    "RUNTIME_LOAD_FAILED": "Muat Gagal",
    "RUNTIME_CONNECTED": "Bersambung",
    "RUNTIME_LOGIN_REQUIRED": "Log Masuk Diperlukan",
    "RUNTIME_SAVED": "Disimpan",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI Sedia - Runtime Belum Selesai",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Perkhidmatan pemilih backend yang dilindungi menolak atau tidak dapat menyimpan pilihan model yang diminta.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Perkhidmatan pemilih backend yang dilindungi menolak atau tidak dapat menyimpan perubahan penghalaan WF1 yang diminta.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Pemilih kini membaca konfigurasi aktif, penghalaan Qwen, dan pilihan yang dibenarkan daripada perkhidmatan backend yang dilindungi.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Perkhidmatan pemilih backend tidak tersedia sekarang, jadi keadaan pemilih cache terakhir sedang digunakan.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Nilai lalai pemilih aktif kerana tiada keadaan backend atau cache dapat dimuatkan.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Perkhidmatan pemilih backend yang dilindungi mengemas kini konfigurasi penghalaan WF1 aktif dan menyegarkan cache domain runtime.",
    "FRONTEND_VERSION_TITLE": "Versi Frontend",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Pemilih ini mengawal versi frontend aktif untuk semua pengguna. FeV2.0.0 aktif.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Pemilih ini membaca versi frontend aktif daripada config_domain_registry. Runtime menyelesaikan kepada FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Konfigurasi backend versi frontend tidak dapat dimuatkan, jadi lalai berkod FeV2.0.0 kekal aktif sehingga bootstrap permulaan dapat membaca semula perkhidmatan dilindungi.",
    "FRONTEND_VERSION_HELPER_SAVED": "Versi frontend aktif telah disimpan dalam config_domain_registry. Segar semula penuh atau muatan aplikasi seterusnya menerapkan nilai runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Perkhidmatan kawalan versi frontend backend tidak dapat menyimpan versi global yang diminta.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Versi frontend aktif.",
    "CHAT_DELETE_WINDOW_TITLE": "Tetingkap Padam Sembang",
    "CHAT_DELETE_HELPER": "Nilai ini mengawal tetingkap ketersediaan Padam untuk semua orang dalam saat. Pelindung backend berubah serta-merta selepas disimpan. Keterlihatan gelembung berubah selepas segar semula penuh atau muatan aplikasi seterusnya.",
    "CHAT_DELETE_HELPER_FALLBACK": "Perkhidmatan kawalan padam sembang backend tidak dapat dimuatkan, jadi lalai berkod kekal aktif sehingga bootstrap permulaan dapat membaca semula perkhidmatan dilindungi.",
    "CHAT_DELETE_HELPER_SAVED": "Tetingkap ketersediaan Padam untuk semua orang telah disimpan dalam config_domain_registry. Pelindung backend berubah serta-merta. Keterlihatan gelembung berubah selepas segar semula penuh atau muatan aplikasi seterusnya.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Perkhidmatan kawalan padam sembang backend tidak dapat menyimpan nilai tetingkap yang diminta.",
    "CHAT_DELETE_WINDOW_LABEL": "Tetingkap Padam untuk semua orang",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} saat",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Simpan nilai dalam saat bulat. Nilai produksi semasa ialah 86400 saat = 1 hari.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Saat Tetingkap",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Masukkan nombor bulat lebih besar atau sama dengan 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Simpan Tetingkap Padam",
    "PROFILE_VISIBILITY_TITLE": "Keterlihatan Profil",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Anda mesti log masuk untuk mengurus keterlihatan akaun.",
    "PROFILE_VISIBILITY_HELPER": "Suis ini hanya mengemas kini keadaan keterlihatan akaun anda. Kebolehcarian dan tingkah laku senarai sepanduk kekal tidak berubah dalam fasa ini.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Keterlihatan profil tidak dapat dimuatkan sekarang.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Keterlihatan profil tidak dapat dikemas kini sekarang.",
    "PROFILE_VISIBILITY_SAVED": "Keterlihatan akaun anda kini {visibility}. Bendera kebolehcarian kekal tidak berubah dalam fasa ini.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Akaun Awam",
    "PROFILE_VISIBILITY_STORED": "Keterlihatan Disimpan",
    "WF1_MODEL_CONTROL_TITLE": "Kawalan Model WF1",
    "WF1_ENABLE_TRANSLATION": "Dayakan Terjemahan / Pivot",
    "WF1_TRANSLATION_ACTIVE": "Terjemahan AI aktif.",
    "WF1_TRANSLATION_INACTIVE": "WF1 terus berjalan tetapi teks sumber disalin dan pivot ditandakan sebagai tidak aktif.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Slot Runtime Aktif",
    "WF1_ALLOW_SAME_LANGUAGE": "Benarkan AI Untuk Pasangan Bahasa Sama",
    "WF1_SAME_LANGUAGE_ACTIVE": "Pasangan bahasa yang sama mengikuti penghalaan WF1 biasa.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Pasangan bahasa yang sama memintas AI dan menyimpan bahasa No Pivot aktif.",
    "WF1_QWEN_ROUTING": "Penghalaan Pasangan Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Bahasa yang ditanda di bawah menggunakan Qwen-Max apabila pasangan itu sama ada bahasa bertanda yang sama, bahasa bertanda dengan Bahasa Inggeris, atau dua bahasa bukan Inggeris yang bertanda. Jika tidak, model utama yang dipilih kekal aktif.",
    "WF1_OPENROUTER_TEST_SLOT": "Slot Ujian OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Slot Ujian OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Ujian Kualiti Sahaja",
    "WF1_OPENROUTER_HELPER": "Slot ini boleh diedit hanya untuk ujian kualiti OpenRouter sementara. Ia tidak mengubah laluan operasi penghalaan pasangan Qwen melainkan slot ini sendiri menjadi model aktif.",
    "WF1_LABEL": "Label",
    "WF1_PRODUCT": "Produk",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Penyedia: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Rahsia: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Slot Ujian OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max melalui OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Harga senarai Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Harga senarai OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Harga senarai OpenRouter",
    "LANGUAGE_ENGLISH": "Bahasa Inggeris",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Bahasa Cina (Ringkas)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Bahasa Cina (Tradisional)",
    "LANGUAGE_JAPANESE": "Bahasa Jepun",
    "LANGUAGE_KOREAN": "Bahasa Korea",
    "LANGUAGE_PERSIAN": "Bahasa Parsi",
    "LANGUAGE_TURKISH_ISTANBUL": "Bahasa Turki (Istanbul)",
    "LANGUAGE_ARABIC": "Bahasa Arab",
    "LANGUAGE_FRENCH": "Bahasa Perancis",
    "LANGUAGE_GERMAN": "Bahasa Jerman",
    "LANGUAGE_SPANISH": "Bahasa Sepanyol",
    "LANGUAGE_PORTUGUESE": "Bahasa Portugis",
    "LANGUAGE_ITALIAN": "Bahasa Itali",
    "LANGUAGE_RUSSIAN": "Bahasa Rusia",
    "LANGUAGE_DUTCH": "Bahasa Belanda",
    "LANGUAGE_VIETNAMESE": "Bahasa Vietnam",
    "LANGUAGE_INDONESIAN": "Bahasa Indonesia",
    "LANGUAGE_THAI": "Bahasa Thai",
    "LANGUAGE_MALAY": "Bahasa Melayu",
    "WF1_PRICING_CUSTOM": "Harga: model slot tersuai - semak harga OpenRouter semasa",
    "WF1_SAVE_OPENROUTER_SLOT": "Simpan Slot OpenRouter",
    "WF1_PRICING_LINE": "Input {input} - Output {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Rahsia: {secret}",
    "ZONE_VISIBILITY_TITLE": "Kawalan Keterlihatan Zon",
    "ZONE_ENABLE": "Dayakan {zone}",
    "ZONE_ENABLED_NOTE": "{zone} boleh muncul untuk peranan yang dibenarkan selepas muatan aplikasi seterusnya.",
    "ZONE_DISABLED_NOTE": "{zone} dianggap tiada untuk pengguna bukan S_Admin selepas muatan aplikasi seterusnya.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin memintas senarai peranan ini dan sentiasa mengekalkan akses.",
    "ZONE_ROLE_LOCKED": "Pilihan peranan dikunci sementara semasa zon ini dilumpuhkan dan akan kembali tepat seperti yang disimpan apabila zon didayakan semula.",
    "ZONE_LCAC_CONTROL": "Kawalan LCAC",
    "ZONE_RCAC_CONTROL": "Kawalan RCAC",
    "ZONE_LCAC_DESCRIPTION": "Mengawal kewujudan zon tersimpan kiri dan peranan yang boleh melihatnya.",
    "ZONE_RCAC_DESCRIPTION": "Mengawal kewujudan zon tersimpan kanan dan peranan yang boleh melihatnya.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap keterlihatan zon kini membaca daripada perkhidmatan backend yang dilindungi. Perubahan diterapkan pada muatan aplikasi seterusnya.",
    "ZONE_VISIBILITY_CACHED": "Perkhidmatan keterlihatan zon backend tidak tersedia sekarang, jadi lalai cache atau tempatan aktif.",
    "ZONE_VISIBILITY_DEFAULTS": "Lalai keterlihatan zon aktif kerana tiada keadaan backend atau cache dapat dimuatkan.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap keterlihatan zon telah disimpan. Muat semula paksa atau muatan aplikasi seterusnya diperlukan untuk penerapan runtime.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Perkhidmatan backend yang dilindungi tidak dapat menyimpan perubahan keterlihatan zon yang diminta.",
    "ROLE_MEMBER": "Ahli",
    "ROLE_STAFF": "Staf",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Dayakan pemberitahuan untuk menerima mesej baharu.",
    "MAIN_LOG_OUT": "Log Keluar",
    "NOTIFICATION_NEW_MESSAGE": "Mesej baharu",
    "NOTIFICATION_UNREAD_MESSAGE": "Anda mempunyai mesej belum dibaca.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Paparan Penuh",
    "MEDIA_AUDIO_ATTACHMENT": "Lampiran audio",
    "MEDIA_FILE_FALLBACK": "Fail",
    "MEDIA_DOWNLOAD_READY": "Lampiran sedia untuk dimuat turun",
    "MEDIA_TYPE_UNSUPPORTED": "Jenis tidak disokong untuk paparan penuh",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Imej sebelumnya",
    "MEDIA_NEXT_IMAGE_ARIA": "Imej seterusnya",
    "MEDIA_OPEN_ORIGINAL": "Buka Asal",
    "MEDIA_DOWNLOAD": "Muat Turun",
    "MEDIA_CLOSE_ARIA": "Tutup",
    "MEDIA_PROFILE_PICTURE_ARIA": "Gambar profil {name}",
    "MEDIA_PROFILE_ALT": "Profil {name}",
    "MEDIA_UPLOAD_FAILED": "Muat naik gagal",
    "MEDIA_BACKEND_TOKEN_ERROR": "Ralat Token Backend",
    "MEDIA_UPLOAD_URL_MISSING": "Kritikal: URL muat naik hilang dalam respons backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Token pengesahan hilang untuk muat naik sembang",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Permintaan token muat naik sembang gagal",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Respons muat naik sembang tidak sah",
    "MEDIA_GCS_UPLOAD_FAILED": "Muat Naik GCS Gagal",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nama fail atau contentType hilang",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path hilang",
    "BLOCK_NOTICE_TITLE": "Notis Sekatan Kekal",
    "BLOCK_NOTICE_MESSAGE": "Akaun anda telah digantung sementara kerana pelanggaran dasar.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Jika anda percaya perkara ini memerlukan susulan, sila hubungi",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "melalui e-mel.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Pengguna Tidak Diketahui",
    "GENERAL_GUEST": "Tetamu",
    "ADVISOR_FOR_CLIENT": "Penasihat untuk {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token dan kata laluan diperlukan",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Badan permintaan mesti JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Token jemputan tidak sah atau tamat tempoh",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Tetapan kata laluan gagal: sesi atau pengguna hilang",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Tetapan kata laluan gagal semasa log masuk",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Penjanaan token admin gagal",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Log masuk gagal: sesi atau pengguna hilang",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Pendaftaran berjaya. Sila semak e-mel untuk pengesahan.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Pendaftaran gagal tidak diketahui",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Pemprosesan token tidak sah",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Token akses diperlukan",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Pratonton hash token memerlukan petunjuk e-mel daripada URL ubah hala",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Tidak dapat menyelesaikan identiti untuk token ini",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Hanya User Zero boleh mengakses perkhidmatan pemilih LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Hanya User Zero boleh mengakses perkhidmatan kawalan keterlihatan zon.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Hanya User Zero boleh mengakses perkhidmatan kawalan versi frontend.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Hanya User Zero boleh memeriksa versi frontend pengguna lain.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Hanya User Zero boleh mengakses perkhidmatan kawalan padam sembang.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Hanya User Zero boleh memadam akaun pengguna secara kekal.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Payload permintaan tidak sah.",
    "API_ERROR_INTERNAL_SERVER": "Ralat Pelayan Dalaman",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Fungsi hilang dalam backend (Muat Semula Diperlukan)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Hanya RPC DB dibenarkan untuk peralihan delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Sila tunggu sebelum menghantar mesej lain.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Mesej berjaya dihantar.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Perkhidmatan hubungan tidak tersedia.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Penghantaran mesej gagal.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Nama diperlukan.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-mel tidak sah.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Mesej diperlukan.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload pemilih diperlukan.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload keterlihatan zon diperlukan.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload versi frontend diperlukan.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload kawalan padam sembang diperlukan.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID pengguna yang disahkan diperlukan.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID pengguna penonton yang disahkan diperlukan.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID pengguna pelaku yang disahkan diperlukan.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id diperlukan.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id diperlukan.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Senarai owner_user_ids diperlukan.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email diperlukan.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by diperlukan.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime carian dilumpuhkan oleh versi frontend global.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Anda tidak dibenarkan membatalkan jemputan belum selesai ini.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Jemputan ini tidak boleh lagi dibatalkan kerana pengguna sudah berdaftar.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Jemputan belum selesai tidak ditemui.",
    "INVITE_REPLY_ALREADY_MEMBER": "Tahniah, rakan anda ({invitee_email}) sudah berdaftar dalam aplikasi ini dan merupakan ahli ruang kerja ini.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Jemputan sedang menunggu untuk {invitee_email}, tetapi e-mel cuba semula tidak dapat dicetuskan. Sila semak log mel.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Rekod jemputan telah dicipta untuk {invitee_email}, tetapi penghantaran e-mel tidak dapat disahkan. Sila cuba lagi kemudian atau semak log mel.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Gagal mencipta rekod jemputan. Sila cuba lagi kemudian.",
    "INVITE_REPLY_SYSTEM_ERROR": "Ralat sistem semasa proses jemputan: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Ralat Konfigurasi Backend: kelayakan Supabase hilang",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Ralat Konfigurasi Backend: URL Supabase tidak sah",
    "CHAT_ERROR_ACCESS_DENIED": "Akses Ditolak",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Kandungan tidak boleh kosong untuk mesej teks",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Tidak dapat menentukan ID perbualan",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Konteks pengesahan RPC hilang",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC mengembalikan payload mesej tidak sah",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Sisipan gagal, tiada data dikembalikan",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations mesti berupa senarai",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Payload operasi tidak sah",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type tidak disokong",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id diperlukan",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Mesej tidak ditemui",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Pemadaman hanya dibenarkan pada mesej anda sendiri",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Padam untuk semua orang tidak lagi tersedia untuk mesej ini",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Padam untuk semua orang gagal",
    "API_ERROR_SERVER_CONFIGURATION": "Ralat konfigurasi pelayan",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Pengepala rahsia webhook hilang",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Sumber webhook tidak dibenarkan",
    "API_ERROR_BACKEND_CONFIGURATION": "Ralat konfigurasi backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Ralat Atribut Modul: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Gagal sebelum pemadaman jemputan semasa mengalih keluar pengguna auth yang menunggu.",
    "CHAT_ERROR_DB": "Ralat DB: {error}",
}
