# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/en.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Hoofdscherm",
    "APP_TITLE": "OTMEGA AI-platform",
    "APP_SUBTITLE": "AI-adviseur",
    "CHAT_PLACEHOLDER": "Typ uw bericht...",
    "CHAT_SEND_BUTTON": "Verzenden",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 De adviseur kan fouten maken, controleer de informatie dus goed.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Nieuwe chat",
    "ICON_HISTORY": "Geschiedenis",
    "ICON_TEMPLATES": "Sjablonen",
    "ICON_SETTINGS": "Instellingen",
    "ICON_USER_PROFILE": "Gebruikersprofiel",
    "ICON_QUICK_ACTIONS": "Snelle acties",
    "ICON_PINNED": "Vastgezet",
    "ICON_GALLERY": "Galerij",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "App installeren",
    "PWA_ANDROID_MSG": "Installeer deze app op uw apparaat voor een betere ervaring en offline toegang.",
    "PWA_IOS_MSG": "Om deze app op uw iPhone/iPad te installeren:\n1. Tik hieronder op de knop Delen\n2. Selecteer 'Zet op beginscherm'",
    "PWA_BTN_INSTALL": "Installeren",
    "PWA_BTN_LATER": "Misschien later",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Log in op het adviseursnetwerk",
    "AUTH_HEADER_SIGNUP": "Maak uw uniforme account aan",
    "AUTH_HEADER_LOGIN_NETWORK": "Log in op het adviseursnetwerk",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Maak uw uniforme account aan",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Inloggen",
    "AUTH_BUTTON_SIGNUP": "Account aanmaken",
    "AUTH_BUTTON_GOOGLE": "Doorgaan met Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Wachtwoord vergeten",
    "AUTH_BUTTON_SEND_RESET_LINK": "Resetlink verzenden",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Nog geen account? Registreer u",
    "AUTH_PROMPT_LOGIN": "Heeft u al een account? Log in",
    "AUTH_HELPER_TEXT_SIGNUP": "U maakt een uniform account aan waarmee u toegang krijgt tot alle adviseurs op dit platform.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "U maakt een uniform account aan waarmee u toegang krijgt tot alle adviseurs op dit platform.",
    "AUTH_HELPER_TEXT_LOGIN": "Gebruik hetzelfde account (e-mail/wachtwoord of Google) dat u voor andere adviseurs in dit netwerk hebt gebruikt.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Gebruik hetzelfde account (e-mail/wachtwoord of Google) dat u voor andere adviseurs in dit netwerk hebt gebruikt.",
    "AUTH_FORGOT_PASSWORD_LINK": "Wachtwoord vergeten?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Uw wachtwoord resetten",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Voer uw e-mailadres in en wij sturen u een link om uw wachtwoord te resetten.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-mail",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "U wordt ingelogd...",
    "AUTH_STATUS_LOADING_SIGNUP": "Uw account wordt aangemaakt...",
    "AUTH_STATUS_LOADING_RESET": "Resetlink wordt verzonden...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Inloggen gelukt! Opnieuw laden...",
    "AUTH_STATUS_SUCCESS_RESET": "Resetlink succesvol verzonden. Controleer uw e-mail.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Wachtwoordresetlink succesvol verzonden. Controleer uw e-mail.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Ongeldig e-mailadres of wachtwoord.",
    "AUTH_ERROR_EMAIL_EXISTS": "Er bestaat al een account met dit e-mailadres in het adviseursnetwerk.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Er bestaat al een account met dit e-mailadres. Log in. U bent momenteel lid van:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Er bestaat al een account met dit e-mailadres in het adviseursnetwerk. Sluit dit venster en gebruik het gedeelte 'Inloggen' met hetzelfde e-mailadres en uw vorige wachtwoord.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "U bent momenteel lid van:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-mail en wachtwoord zijn vereist.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Account aangemaakt, maar het instellen van het lidmaatschap is mislukt. Neem contact op met support.",
    "AUTH_ERROR_DEFAULT": "Er is een fout opgetreden. Probeer het opnieuw.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Het verzenden van de resetlink is mislukt. Probeer het opnieuw.",
    "INVITE_REPLY_EMAIL_SENT": "De Collabra-uitnodigingsmail is verzonden naar uw vriend op {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "De Collabra-uitnodigingsmail is opnieuw verzonden naar uw vriend op {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Wachtwoord tonen",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Wachtwoord verbergen",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Annuleren",
    "GENERAL_CLOSE": "Sluiten",
    "GENERAL_SEND": "Verzenden",
    "GENERAL_SEARCH": "Zoeken",
    "GENERAL_RESET": "Resetten",
    "GENERAL_ENABLE": "Inschakelen",
    "GENERAL_LOADING": "Laden...",
    "GENERAL_DELETE": "Verwijderen",
    "GENERAL_DELETING": "Verwijderen...",
    "GENERAL_SAVE_PASSWORD": "Wachtwoord opslaan",
    "AUTH_REMEMBER_EMAIL_LABEL": "E-mail onthouden",
    "GENERAL_SAVING": "Opslaan...",
    "GENERAL_SENDING": "Verzenden...",
    "GENERAL_REMOVING": "Verwijderen...",
    "GENERAL_CONFIRM_REMOVAL": "Verwijdering bevestigen",
    "GENERAL_EMPTY": "Leeg",
    "GENERAL_UNAVAILABLE": "Niet beschikbaar",
    "GENERAL_ENABLED": "Ingeschakeld",
    "GENERAL_DISABLED": "Uitgeschakeld",
    "GENERAL_GRANTED": "Toegestaan",
    "GENERAL_DENIED": "Geweigerd",
    "GENERAL_DEFAULT": "Standaard",
    "GENERAL_UNSUPPORTED": "Niet ondersteund",
    "GENERAL_PUBLIC": "Openbaar",
    "GENERAL_PRIVATE": "Privé",
    "GENERAL_USERNAME": "Gebruikersnaam",
    "GENERAL_EMAIL": "E-mail",
    "GENERAL_YOU": "U",
    "GENERAL_USER": "Gebruiker",
    "GENERAL_UNKNOWN": "Onbekend",
    "GENERAL_VISITOR": "Bezoeker",
    "GENERAL_PROFILE": "Profiel",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Onbekende banner",
    "GENERAL_ADVISOR_BANNER": "Adviseursbanner",
    "GENERAL_NOT_AVAILABLE": "N.v.t.",
    "GENERAL_NOT_SELECTED": "Niet geselecteerd",
    "GENERAL_NO_EMAIL_FOUND": "Geen e-mail gevonden",
    "GENERAL_USER_ZERO_ONLY": "Alleen User Zero",
    "GENERAL_CONNECTION_STATE": "Verbindingsstatus",
    "GENERAL_DISPLAY_ONLY": "Alleen weergeven",
    "GENERAL_TEXTAREA": "Tekstgebied",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Snelle acties (RCAC)",
    "HEADER_CHANGE_STATUS": "Status wijzigen",
    "HEADER_OT_COIN_BALANCE": "OT Coin-saldo",
    "HEADER_ALT_USER": "Gebruiker",
    "STATUS_BUSY": "Bezet",
    "STATUS_AWAY": "Afwezig",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Onzichtbaar",
    "NETWORK_CHECKING_CONNECTION": "Verbinding controleren...",
    "NETWORK_ONLINE_LATENCY": "Online (latentie: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Netwerk: goed (tik om te pingen)",
    "CHAT_TARGET_ALT": "Chatdoel",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Zoeken...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Profielfoto van {name} openen",
    "CHAT_MESSAGE_INPUT_ARIA": "Berichtinvoer",
    "CHAT_TOGGLE_VIEW_ARIA": "Weergave wisselen",
    "CHAT_ADD_USER_ARIA": "Gebruiker toevoegen",
    "CHAT_ATTACH_ARIA": "Bijvoegen",
    "CHAT_MIC_ARIA": "Microfoon",
    "CHAT_SEND_ARIA": "Verzenden",
    "CHAT_SEARCH_ARIA": "Zoeken",
    "CHAT_OPEN_SEARCH_ARIA": "Zoeken openen",
    "CHAT_CLOSE_SEARCH_ARIA": "Zoeken sluiten",
    "CHAT_ATTACHMENT_ALT": "Bijlage",
    "CHAT_PREVIEW_ALT": "Voorbeeld",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Bijlage verwijderen",
    "CHAT_REPLYING_TO": "Antwoord op",
    "CHAT_CANCEL_REPLY_ARIA": "Antwoord annuleren",
    "CHAT_UPLOADING": "Uploaden...",
    "CHAT_LOADING_CHATS": "Chats laden...",
    "CHAT_SEND_FAILED": "Verzenden mislukt",
    "CHAT_SEND_FAILED_RETRY": "Verzenden mislukt. Probeer het opnieuw.",
    "CHAT_RETRY": "Opnieuw proberen",
    "CHAT_EDITED": "bewerkt",
    "CHAT_TYPING": "Typen",
    "CHAT_LOADING": "Laden",
    "CHAT_PENDING_INVITATION": "Uitnodiging in behandeling",
    "CHAT_PENDING_INVITATION_MIN": "{count} min uitnodiging in behandeling",
    "CHAT_PENDING_INVITATION_HR": "{count} uur uitnodiging in behandeling",
    "CHAT_PENDING_INVITATION_DAY": "{count} dag uitnodiging in behandeling",
    "CHAT_WAITING_FOR_YOU": "{label} - Wacht op u",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Acceptatie in behandeling",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Microfoontoegang geweigerd.",
    "CHAT_UPLOAD_FAILED": "Uploaden mislukt: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Uploaden vereist een internetverbinding. Probeer het opnieuw wanneer u online bent.",
    "CHAT_ERROR_AUTH": "Authenticatiefout",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Bestandsnaam of content_type ontbreekt",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id of target_id ontbreekt",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id ontbreekt voor niet-avatar-upload",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Ongeldig avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase-serviceclient niet beschikbaar",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Leesbevestiging voor avatar is alleen geldig in de context van adviseurschat",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatar-flowbericht niet gevonden of niet geschikt voor leesbevestiging",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Kan avatarbericht niet als gelezen afronden",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 bijlage",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} bijlagen",
    "CHAT_VOICE_NOTE": "Spraaknotitie",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat niet beschikbaar. Deze gebruiker heeft u geblokkeerd.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat niet beschikbaar. U hebt deze gebruiker geblokkeerd.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Accounttoegang is geblokkeerd door beleid.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat niet beschikbaar. Dit account is definitief geblokkeerd door User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat niet beschikbaar. Wederzijdse blokkering is actief.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat niet beschikbaar vanwege blokkeringsbeleid.",
    "MESSAGE_PREVIEW_PHOTO": "Foto",
    "MESSAGE_PREVIEW_VOICE": "Spraakbericht",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Bestand",
    "MESSAGE_PREVIEW_MESSAGE": "Bericht",
    "MESSAGE_PREVIEW_SYSTEM": "Systeembericht",
    "MESSAGE_PREVIEW_NEW": "Nieuw bericht",
    "MESSAGE_UNKNOWN_FILE": "Onbekend bestand",
    "MESSAGE_AUDIO_ATTACHMENT": "Audiobijlage",
    "MESSAGE_FILE_ATTACHMENT": "Bijlage",
    "BANNER_INVITED_BY": "uitgenodigd door {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Zoekresultaten",
    "SEARCH_QUERY_LABEL": "Zoekopdracht:",
    "SEARCH_LOADING_VISIBILITY": "Zoekzichtbaarheid laden...",
    "SEARCH_NO_RESULTS": "Geen resultaat gevonden binnen het huidige zoekbereik.",
    "SHARE_WITH_COLLABRA": "Delen met Collabra",
    "SHARE_SEND_TO": "Verzenden naar",
    "SHARE_SELECT_ONE_BANNER": "Selecteer één banner",
    "SHARE_BANNER_LIST_ARIA": "Bannerlijst",
    "SHARE_NO_MATCHING_BANNER": "Geen overeenkomende banner",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Voeg een opmerking toe...",
    "SHARE_RECENT_CHATS": "Recente chats",
    "SHARE_LEFT_LIST": "Linkerlijst",
    "SHARE_RIGHT_LIST": "Rechterlijst",
    "SHARE_UNTITLED_BANNER": "Banner zonder titel",
    "SHARE_SHARED_CONTENT": "Gedeelde inhoud",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Gedeelde inhoud kon niet worden geopend.",
    "SHARE_OPEN_BANNER_FAILED": "De geselecteerde banner kon niet worden geopend.",
    "SHARE_ONE_PHOTO_SELECTED": "1 foto geselecteerd",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} foto's geselecteerd",
    "SHARE_ONE_FILE_SELECTED": "1 bestand geselecteerd",
    "SHARE_MANY_FILES_SELECTED": "{count} bestanden geselecteerd",
    "FORWARD_MESSAGE_TITLE": "Bericht doorsturen",
    "FORWARD_SELECT_RECIPIENTS": "Ontvangers selecteren",
    "FORWARD_NO_OTHER_BANNER": "Geen andere banner beschikbaar.",
    "FORWARD_SEND_TO_COUNT": "Verzenden naar {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Selecteer ten minste één banner.",
    "FORWARD_FAILED_DEFAULT": "Doorsturen mislukt. Probeer het opnieuw.",
    "FORWARD_PARTIAL_SENT": "{count} verzonden. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Bronbericht voor doorsturen niet gevonden",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Dit bericht heeft nog geen doorstuurbare inhoud",
    "FORWARD_DESTINATION_MISSING": "Bestemming voor doorsturen ontbreekt",
    "FORWARD_MESSAGE_PREVIEW": "Doorgestuurd bericht",
    "MENU_PASTE": "Plakken",
    "MENU_COPY": "Kopiëren",
    "MENU_REPLY": "Beantwoorden",
    "MENU_FORWARD": "Doorsturen",
    "MENU_REMOVE_INVITATION": "Uitnodiging verwijderen",
    "MENU_REMOVE_FROM_LIST": "Uit lijst verwijderen",
    "MENU_ADD_TO_LIST": "Aan lijst toevoegen",
    "MENU_REJECT_INVITATION": "Uitnodiging afwijzen",
    "MENU_FRONTEND_VERSION": "Frontend-versie",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Bannerinformatie: {title}",
    "MENU_MESSAGE_BUBBLE": "Berichtballon",
    "MENU_CHAT_CANVAS_HEADER": "Chatcanvas - {zone}",
    "MENU_CANVAS_INFO": "Canvasinformatie",
    "MENU_CHAT_CANVAS_SUBLABEL": "Gespreksgebied / huidig chatoppervlak",
    "MENU_INPUT_AREA_HEADER": "Invoergebied - {zone}",
    "MENU_INPUT_AREA_INFO": "Invoergebiedinformatie: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Onderste oppervlak voor typen en actietools",
    "MENU_HEADER": "Koptekst - {zone}",
    "MENU_HEADER_INFO": "Koptekstinformatie: {title}",
    "MENU_HEADER_DESCRIPTION": "Bovenste navigatie en paginabediening",
    "MENU_ZONE_HEADER": "Zone - {zone}",
    "MENU_ZONE_SPACE_INFO": "Zone-ruimte-informatie",
    "MENU_EMPTY_LIST_SURFACE": "Leeg/lijstoppervlak",
    "MENU_BLOCK": "Blokkeren",
    "MENU_UNBLOCK": "Deblokkeren",
    "MENU_HIDE_IN_SEARCH": "Verbergen in zoeken",
    "MENU_UNHIDE_IN_SEARCH": "Weergeven in zoeken",
    "MENU_VISIBLE_IN_SEARCH": "Zichtbaar in zoeken",
    "MENU_HIDDEN_IN_SEARCH": "Verborgen in zoeken",
    "MENU_VISIBLE_IN_USER_LIST": "Zichtbaar in gebruikerslijst",
    "MENU_HIDDEN_IN_USER_LIST": "Verborgen in gebruikerslijst",
    "MENU_NOT_BLOCKED": "Niet geblokkeerd",
    "MENU_BLOCKED": "Geblokkeerd",
    "MENU_FRONTEND_VERSION_LOADING": "Laden...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Waarde per banner wordt geladen vanuit de backend. Geen optie wordt als actief gemarkeerd totdat de databaseantwoord is aangekomen.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backendwaarde kon niet worden geladen. Er wordt geen betrouwbare actieve optie weergegeven.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "De expliciete databasewaarde per banner is {overrideVersion}. De globale standaardwaarde is {globalDefaultVersion}. De doelgebruiker moet de app volledig vernieuwen of opnieuw openen zodat de opstart-bootstrap dit toepast.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Er is geen expliciete databasewaarde per banner opgeslagen. FeV2.0.0 is standaard actief. De globale standaardwaarde is {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "De expliciete databasewaarde per banner is actief nadat de doel-app volledig opnieuw is geladen",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Er is geen expliciete waarde per banner opgeslagen; dit is de standaard individuele FeV2.0.0-status",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Deze optie is ook gelijk aan de huidige globale standaardwaarde",
    "MENU_DELETE_PERMANENT_CONFIRM": "{target} permanent uit de database verwijderen? Dit verwijdert het account, de chatgeschiedenis en afhankelijkheden, en dwingt voor toekomstige terugkeer een volledig nieuw uitnodigingstraject af.",
    "MENU_DELETE_PERMANENTLY": "Permanent verwijderen",
    "MENU_REFRESH_PAGE": "Pagina vernieuwen",
    "MENU_LOG_OFF": "Afmelden",
    "MENU_HARD_RELOAD": "Hard herladen",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-mail (admin-gebruiker)",
    "AUTH_PASSWORD_PLACEHOLDER": "Wachtwoord",
    "AUTH_CONNECTING": "Verbinden...",
    "AUTH_SIGNING_OUT": "Afmelden...",
    "AUTH_BACK_TO_LOGIN": "Terug naar inloggen",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Ongeldige serverrespons: geen token gevonden.",
    "AUTH_LOGIN_FAILED": "Inloggen mislukt",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Wachtwoorden komen niet overeen.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Wachtwoorden komen niet overeen!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Wachtwoorden moeten exact overeenkomen.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nieuw wachtwoord",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Wachtwoord bevestigen",
    "AUTH_CHANGE_PASSWORD": "Wachtwoord wijzigen",
    "AUTH_SAVING_PASSWORD": "Opslaan...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Wachtwoord succesvol bijgewerkt.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Kan het wachtwoord momenteel niet wijzigen.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "U moet ingelogd zijn om uw wachtwoord te wijzigen.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Zichtbaarheid van nieuw wachtwoord wisselen",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Zichtbaarheid van wachtwoordbevestiging wisselen",
    "REGISTER_TITLE": "Registratie voltooien",
    "REGISTER_SUBTITLE": "Stel uw wachtwoord handmatig in.",
    "REGISTER_CREATING_ACCOUNT": "Account aanmaken...",
    "REGISTER_FINISH_SETUP": "Installatie voltooien",
    "REGISTER_FAILED_SET_PASSWORD": "Wachtwoord instellen mislukt",
    "INVITE_EMAIL_INSTRUCTION": "Voer het e-mailadres van de genodigde in (formaat: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Uitnodigen",
    "INVITE_EMAIL_REQUIRED": "Voer het e-mailadres van de genodigde in.",
    "INVITE_EMAIL_INVALID": "Ongeldig e-mailformaat. Gebruik: user@example.com",
    "PENDING_INVITATION_TITLE": "Uitnodiging in behandeling",
    "PENDING_INVITATION_REMOVE_QUESTION": "Deze openstaande uitnodiging uit de database verwijderen?",
    "PENDING_INVITATION_KEEP": "Uitnodiging behouden",
    "PENDING_INVITATION_REMOVAL_FAILED": "Verwijderen mislukt.",
    "REMOVE_FROM_LIST_TITLE": "Uit lijst verwijderen",
    "REMOVE_FROM_LIST_WARNING": "Deze gebruiker nu uit beide lijsten verwijderen? Chattoegang wordt onmiddellijk afgesloten. De enige terugkeerroute is een nieuwe uitnodiging.",
    "REMOVE_FROM_LIST_KEEP": "Gebruiker in lijst houden",
    "REMOVE_FROM_LIST_FAILED": "Verwijderen uit lijst mislukt.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Instellingen en live status",
    "PERMISSION_DIALOG_ARIA": "Instellingen en live status",
    "PERMISSION_TRIGGER_ARIA": "Trigger voor instellingenpop-up",
    "PERMISSION_CLOSE_ARIA": "Machtigingenpop-up sluiten",
    "PERMISSION_LIVE_STATUS": "Live status",
    "PERMISSION_SYSTEM_PERMISSION": "Systeemmachtiging",
    "PERMISSION_APP_PUSH": "App-push",
    "PERMISSION_LOCATION_PERMISSION": "Locatiemachtiging",
    "PERMISSION_APP_LOCATION": "App-locatie",
    "PERMISSION_CONTROLS": "Machtigingsbediening",
    "PERMISSION_PUSH_NOTIFICATIONS": "Pushmeldingen",
    "PERMISSION_LOCATION_ACCESS": "Locatietoegang",
    "PERMISSION_IN_APP_SETTINGS": "In-app-instellingen",
    "PERMISSION_ALERT_SOUND": "Waarschuwingsgeluid",
    "PERMISSION_APP_BADGE": "App-badge",
    "PERMISSION_PASSWORD_SETTINGS": "Wachtwoordinstellingen",
    "PERMISSION_NAVIGATION_STATUS": "Navigatiestatus",
    "PERMISSION_SELECTED_ZONE": "Geselecteerde zone",
    "PERMISSION_STAGED_CHAT_BANNER": "Voorbereide chatbanner",
    "PERMISSION_CANVAS_CONTENT": "Canvasinhoud",
    "PERMISSION_YOUR_DEVICES": "Uw apparaten ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Apparaatlijst vernieuwen",
    "PERMISSION_REFRESH_LIST": "Lijst vernieuwen",
    "PERMISSION_NO_REGISTERED_DEVICES": "Geen geregistreerde apparaten gevonden.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Instellingenpop-up vergroten/verkleinen",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Pushmeldingen wisselen",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Locatietoegang wisselen",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Waarschuwingsgeluid wisselen",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "App-badge wisselen",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Profielzichtbaarheid wisselen",
    "PERMISSION_OFF_IN_V1": "Uit in v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Bannerlijst",
    "PERMISSION_PUSH_DISABLED_V1": "Pushmeldingen zijn uitgeschakeld voor de v1 Google Play-release.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Pushmeldingen staan AAN voor dit apparaat.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Systeemmeldingen zijn geblokkeerd. Tik om hulp voor instellingen te openen.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Schakel IN om de afleverbetrouwbaarheid te verbeteren.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Om systeemmeldingen uit te schakelen, opent u de meldingsinstellingen van uw browser/site en zet u deze site op Blokkeren.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Om de machtiging voor systeemmeldingen te wijzigen, opent u de meldingsinstellingen van uw browser/site en zet u deze site op Toestaan.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Locatietoegang staat AAN voor afstandsgebaseerde LCAC-sortering en kaartpositionering.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "De Locatie-API wordt in deze omgeving niet ondersteund.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Locatietoegang is geblokkeerd. Tik om hulp voor instellingen te openen.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Schakel IN om nauwkeurige afstandsgebaseerde LCAC-sortering en in-app kaartpositionering toe te staan.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Locatietoegang wordt in deze omgeving niet ondersteund.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Om locatietoegang uit te schakelen, opent u de locatie-instellingen van uw browser/site en zet u deze site op Blokkeren.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Om locatietoegang voor afstandssortering en in-app kaartpositionering in te schakelen, opent u de locatie-instellingen van uw browser/site en zet u deze site op Toestaan.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Kan geregistreerde apparaten momenteel niet laden.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "UI Bridge laden...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Local Bridge laden...",
    "RUNTIME_LOADING_BACKEND": "Backend laden...",
    "RUNTIME_LOADING": "Laden...",
    "RUNTIME_LOADING_FROM_DATABASE": "Laden vanuit database...",
    "RUNTIME_BACKEND_CONNECTED": "Backend verbonden",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Gecachte fallback actief",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Standaardfallback actief",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallback-standaardwaarden actief",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Opslaan via backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Opgeslagen in backendservice",
    "RUNTIME_SAVE_FAILED": "Opslaan mislukt",
    "RUNTIME_LOAD_FAILED": "Laden mislukt",
    "RUNTIME_CONNECTED": "Verbonden",
    "RUNTIME_LOGIN_REQUIRED": "Inloggen vereist",
    "RUNTIME_SAVED": "Opgeslagen",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI gereed - runtime in behandeling",
    "RUNTIME_BACKEND_REJECTED_MODEL": "De beschermde backendselectordienst heeft de gevraagde modeloptie geweigerd of kon deze niet opslaan.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "De beschermde backendselectordienst heeft de gevraagde WF1-routeringswijziging geweigerd of kon deze niet opslaan.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "De selector leest nu actieve configuratie, Qwen-routering en toegestane opties vanuit de beschermde backendservice.",
    "RUNTIME_WF1_SELECTOR_CACHED": "De backendselectordienst is momenteel niet beschikbaar, dus de laatst gecachte selectorstatus wordt gebruikt.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "De standaardwaarden van de selector zijn actief omdat geen backend- of gecachte selectorstatus kon worden geladen.",
    "RUNTIME_WF1_SELECTOR_SAVED": "De beschermde backendselectordienst heeft de actieve WF1-routeringsconfiguratie bijgewerkt en de runtime-domeincache vernieuwd.",
    "FRONTEND_VERSION_TITLE": "Frontend-versie",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Deze selector beheert de actieve frontend-versie voor alle gebruikers. FeV2.0.0 is actief.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Deze selector leest de actieve frontend-versie uit config_domain_registry. Runtime resolveert naar FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "De backendconfiguratie voor frontend-versie kon niet worden geladen, dus de gecodeerde standaard FeV2.0.0 blijft actief totdat de opstart-bootstrap de beschermde service opnieuw kan lezen.",
    "FRONTEND_VERSION_HELPER_SAVED": "De actieve frontend-versie is opgeslagen in config_domain_registry. Een volledige vernieuwing of volgende app-laadbeurt past de runtimewaarde toe.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "De backendcontroledienst voor frontend-versie kon de gevraagde globale versie niet opslaan.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Actieve frontend-versie.",
    "CHAT_DELETE_WINDOW_TITLE": "Chatverwijderingsvenster",
    "CHAT_DELETE_HELPER": "Deze waarde bepaalt het beschikbaarheidsvenster voor Verwijderen voor iedereen in seconden. De backendguard wijzigt onmiddellijk na opslaan. De zichtbaarheid van de ballon wijzigt na volledig vernieuwen of bij de volgende app-laadbeurt.",
    "CHAT_DELETE_HELPER_FALLBACK": "De backendcontroledienst voor chatverwijdering kon niet worden geladen, dus de gecodeerde standaard blijft actief totdat de opstart-bootstrap de beschermde service opnieuw kan lezen.",
    "CHAT_DELETE_HELPER_SAVED": "Het beschikbaarheidsvenster voor Verwijderen voor iedereen is opgeslagen in config_domain_registry. De backendguard wijzigt onmiddellijk. De zichtbaarheid van de ballon wijzigt na volledig vernieuwen of bij de volgende app-laadbeurt.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "De backendcontroledienst voor chatverwijdering kon de gevraagde vensterwaarde niet opslaan.",
    "CHAT_DELETE_WINDOW_LABEL": "Venster Verwijderen voor iedereen",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} sec",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Sla de waarde op in hele seconden. De huidige productiewaarde is 86400 seconden = 1 dag.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Vensterseconden",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Voer een geheel getal in dat groter is dan of gelijk is aan 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Verwijderingsvenster opslaan",
    "PROFILE_VISIBILITY_TITLE": "Profielzichtbaarheid",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "U moet ingelogd zijn om accountzichtbaarheid te beheren.",
    "PROFILE_VISIBILITY_HELPER": "Deze schakelaar werkt alleen de zichtbaarheidsstatus van uw account bij. Vindbaarheid en bannerlijstgedrag blijven in deze fase ongewijzigd.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Profielzichtbaarheid kon momenteel niet worden geladen.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Profielzichtbaarheid kon momenteel niet worden bijgewerkt.",
    "PROFILE_VISIBILITY_SAVED": "Uw accountzichtbaarheid is nu {visibility}. Vindbaarheidsvlaggen blijven in deze fase ongewijzigd.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Openbaar account",
    "PROFILE_VISIBILITY_STORED": "Opgeslagen zichtbaarheid",
    "WF1_MODEL_CONTROL_TITLE": "WF1-modelbeheer",
    "WF1_ENABLE_TRANSLATION": "Vertaling / pivot inschakelen",
    "WF1_TRANSLATION_ACTIVE": "AI-vertaling is actief.",
    "WF1_TRANSLATION_INACTIVE": "WF1 blijft draaien, maar de brontekst wordt gekopieerd en de pivot wordt als inactief gemarkeerd.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Actieve runtime-slot",
    "WF1_ALLOW_SAME_LANGUAGE": "AI toestaan voor paren met dezelfde taal",
    "WF1_SAME_LANGUAGE_ACTIVE": "Paren met dezelfde taal volgen normale WF1-routering.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Paren met dezelfde taal omzeilen AI en slaan Geen actieve pivottal op.",
    "WF1_QWEN_ROUTING": "Qwen-paarroutering",
    "WF1_QWEN_ROUTING_HELPER": "De hieronder aangevinkte talen gebruiken Qwen-Max wanneer het paar dezelfde aangevinkte taal is, een aangevinkte taal met Engels, of twee aangevinkte niet-Engelse talen. Anders blijft het geselecteerde primaire model actief.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter-testslot",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter-testslot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Alleen kwaliteitstest",
    "WF1_OPENROUTER_HELPER": "Deze slot is alleen bewerkbaar voor tijdelijke OpenRouter-kwaliteitstests. Dit wijzigt het operationele Qwen-paarrouteringspad niet, tenzij deze slot zelf het actieve model wordt.",
    "WF1_LABEL": "Label",
    "WF1_PRODUCT": "Product",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Provider: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Geheim: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter-testslot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max via OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google-lijstprijs",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI-lijstprijs",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter-lijstprijs",
    "LANGUAGE_ENGLISH": "Engels",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Chinees (vereenvoudigd)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Chinees (traditioneel)",
    "LANGUAGE_JAPANESE": "Japans",
    "LANGUAGE_KOREAN": "Koreaans",
    "LANGUAGE_PERSIAN": "Perzisch",
    "LANGUAGE_TURKISH_ISTANBUL": "Turks (Istanbul)",
    "LANGUAGE_ARABIC": "Arabisch",
    "LANGUAGE_FRENCH": "Frans",
    "LANGUAGE_GERMAN": "Duits",
    "LANGUAGE_SPANISH": "Spaans",
    "LANGUAGE_PORTUGUESE": "Portugees",
    "LANGUAGE_ITALIAN": "Italiaans",
    "LANGUAGE_RUSSIAN": "Russisch",
    "LANGUAGE_DUTCH": "Nederlands",
    "LANGUAGE_VIETNAMESE": "Vietnamees",
    "LANGUAGE_INDONESIAN": "Indonesisch",
    "LANGUAGE_THAI": "Thais",
    "LANGUAGE_MALAY": "Maleis",
    "WF1_PRICING_CUSTOM": "Prijzen: aangepast slotmodel - controleer de huidige OpenRouter-prijzen",
    "WF1_SAVE_OPENROUTER_SLOT": "OpenRouter-slot opslaan",
    "WF1_PRICING_LINE": "Invoer {input} - Uitvoer {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Geheim: {secret}",
    "ZONE_VISIBILITY_TITLE": "Beheer van zonezichtbaarheid",
    "ZONE_ENABLE": "{zone} inschakelen",
    "ZONE_ENABLED_NOTE": "{zone} kan verschijnen voor toegestane rollen na de volgende app-laadbeurt.",
    "ZONE_DISABLED_NOTE": "{zone} wordt behandeld als afwezig voor niet-S_Admin-gebruikers na de volgende app-laadbeurt.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin omzeilt deze rollenlijst en behoudt altijd toegang.",
    "ZONE_ROLE_LOCKED": "Rolselecties zijn tijdelijk vergrendeld terwijl deze zone is uitgeschakeld en keren exact terug zoals opgeslagen wanneer de zone weer wordt ingeschakeld.",
    "ZONE_LCAC_CONTROL": "LCAC-beheer",
    "ZONE_RCAC_CONTROL": "RCAC-beheer",
    "ZONE_LCAC_DESCRIPTION": "Beheert het bestaan van de linker gereserveerde zone en de rollen die deze mogen zien.",
    "ZONE_RCAC_DESCRIPTION": "Beheert het bestaan van de rechter gereserveerde zone en de rollen die deze mogen zien.",
    "ZONE_VISIBILITY_BACKEND": "De bootstrap voor zonezichtbaarheid leest nu vanuit de beschermde backendservice. Wijzigingen worden toegepast bij de volgende app-laadbeurt.",
    "ZONE_VISIBILITY_CACHED": "De backendservice voor zonezichtbaarheid is momenteel niet beschikbaar, dus gecachte of lokale standaardwaarden zijn actief.",
    "ZONE_VISIBILITY_DEFAULTS": "Standaardwaarden voor zonezichtbaarheid zijn actief omdat geen backend- of gecachte status kon worden geladen.",
    "ZONE_VISIBILITY_SAVED": "De bootstrap voor zonezichtbaarheid is opgeslagen. Hard herladen of de volgende app-laadbeurt is vereist voor runtime-toepassing.",
    "ZONE_VISIBILITY_SAVE_FAILED": "De beschermde backendservice kon de gevraagde wijziging van zonezichtbaarheid niet opslaan.",
    "ROLE_MEMBER": "Lid",
    "ROLE_STAFF": "Medewerker",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Schakel meldingen in om nieuwe berichten te ontvangen.",
    "MAIN_LOG_OUT": "Uitloggen",
    "NOTIFICATION_NEW_MESSAGE": "Nieuw bericht",
    "NOTIFICATION_UNREAD_MESSAGE": "U hebt een ongelezen bericht.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Volledige weergave",
    "MEDIA_AUDIO_ATTACHMENT": "Audiobijlage",
    "MEDIA_FILE_FALLBACK": "Bestand",
    "MEDIA_DOWNLOAD_READY": "Bijlage klaar om te downloaden",
    "MEDIA_TYPE_UNSUPPORTED": "Type niet ondersteund voor volledige weergave",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Vorige afbeelding",
    "MEDIA_NEXT_IMAGE_ARIA": "Volgende afbeelding",
    "MEDIA_OPEN_ORIGINAL": "Origineel openen",
    "MEDIA_DOWNLOAD": "Downloaden",
    "MEDIA_CLOSE_ARIA": "Sluiten",
    "MEDIA_PROFILE_PICTURE_ARIA": "Profielfoto van {name}",
    "MEDIA_PROFILE_ALT": "Profiel van {name}",
    "MEDIA_UPLOAD_FAILED": "Uploaden mislukt",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend-tokenfout",
    "MEDIA_UPLOAD_URL_MISSING": "Kritiek: upload-URL ontbreekt in backendrespons.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Authenticatietoken ontbreekt voor chatupload",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Aanvraag voor chatuploadtoken mislukt",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Ongeldige chatuploadrespons",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS-upload mislukt",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Bestandsnaam of contentType ontbreekt",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path ontbreekt",
    "BLOCK_NOTICE_TITLE": "Melding van permanente blokkering",
    "BLOCK_NOTICE_MESSAGE": "Uw account is tijdelijk opgeschort wegens een beleidsovertreding.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Als u denkt dat dit opvolging vereist, neem dan contact op met",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "per e-mail.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Onbekende gebruiker",
    "GENERAL_GUEST": "Gast",
    "ADVISOR_FOR_CLIENT": "Adviseur voor {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token en wachtwoord zijn vereist",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Request body moet JSON zijn",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Ongeldig of verlopen uitnodigingstoken",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Wachtwoord instellen mislukt: sessie of gebruiker ontbreekt",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Wachtwoord instellen mislukt tijdens inloggen",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Genereren van admin-token mislukt",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Inloggen mislukt: sessie of gebruiker ontbreekt",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registratie geslaagd. Controleer uw e-mail voor verificatie.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Registratie mislukt onbekend",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Ongeldige tokenverwerking",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Toegangstoken is vereist",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Voor token-hashvoorbeeld is een e-mailhint uit de omleidings-URL vereist",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Kan identiteit voor dit token niet oplossen",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Alleen User Zero heeft toegang tot de WF1 LLM-selectordienst.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Alleen User Zero heeft toegang tot de controledienst voor zonezichtbaarheid.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Alleen User Zero heeft toegang tot de controledienst voor frontend-versie.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Alleen User Zero kan de frontend-versie van een andere gebruiker inspecteren.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Alleen User Zero heeft toegang tot de controledienst voor chatverwijdering.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Alleen User Zero kan een gebruikersaccount permanent verwijderen.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Ongeldige request payload.",
    "API_ERROR_INTERNAL_SERVER": "Interne serverfout",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Functie ontbreekt in backend (herladen vereist)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Alleen DB RPC is toegestaan voor delivered/read-overgangen.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Wacht even voordat u nog een bericht verzendt.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Bericht succesvol verzonden.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Contactservice is niet beschikbaar.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Bericht verzenden mislukt.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Naam is vereist.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-mail is ongeldig.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Bericht is vereist.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Selectorpayload is vereist.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload voor zonezichtbaarheid is vereist.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload voor frontend-versie is vereist.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload voor chatverwijderingsbeheer is vereist.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Geauthenticeerde gebruikers-ID is vereist.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Geauthenticeerde kijker-gebruikers-ID is vereist.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Geauthenticeerde actor-gebruikers-ID is vereist.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id is vereist.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id is vereist.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids-lijst is vereist.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email is vereist.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by is vereist.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Zoekruntime is uitgeschakeld door de globale frontend-versie.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "U mag deze openstaande uitnodiging niet annuleren.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Deze uitnodiging kan niet meer worden geannuleerd omdat de gebruiker al geregistreerd is.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Uitnodiging in behandeling niet gevonden.",
    "INVITE_REPLY_ALREADY_MEMBER": "Gefeliciteerd, uw vriend ({invitee_email}) is al geregistreerd in deze app en is lid van deze werkruimte.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Er staat een uitnodiging open voor {invitee_email}, maar de herhalingsmail kon niet worden gestart. Controleer de maillogs.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Er is een uitnodigingsrecord aangemaakt voor {invitee_email}, maar e-mailbezorging kon niet worden bevestigd. Probeer het later opnieuw of controleer de maillogs.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Aanmaken van uitnodigingsrecord mislukt. Probeer het later opnieuw.",
    "INVITE_REPLY_SYSTEM_ERROR": "Systeemfout tijdens uitnodigingsproces: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backendconfiguratiefout: Supabase-referenties ontbreken",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backendconfiguratiefout: ongeldige Supabase-URL",
    "CHAT_ERROR_ACCESS_DENIED": "Toegang geweigerd",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Inhoud mag niet leeg zijn voor tekstberichten",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Kan conversatie-ID niet bepalen",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC-authenticatiecontext ontbreekt",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC retourneerde een ongeldige berichtpayload",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Invoegen mislukt, geen gegevens geretourneerd",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations moet een lijst zijn",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Ongeldige bewerkingspayload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type wordt niet ondersteund",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id is vereist",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Bericht niet gevonden",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Verwijderen is alleen toegestaan voor uw eigen bericht",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Verwijderen voor iedereen is niet meer beschikbaar voor dit bericht",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Verwijderen voor iedereen mislukt",
    "API_ERROR_SERVER_CONFIGURATION": "Serverconfiguratiefout",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Webhook-geheime header ontbreekt",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Niet-geautoriseerde webhookbron",
    "API_ERROR_BACKEND_CONFIGURATION": "Backendconfiguratiefout",
    "API_ERROR_MODULE_ATTRIBUTE": "Module-attribuutfout: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Mislukt vóór het verwijderen van de uitnodiging tijdens het verwijderen van de wachtende auth-gebruiker.",
    "CHAT_ERROR_DB": "DB-fout: {error}",
}
