# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/no.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Hovedside",
    "APP_TITLE": "OTMEGA AI-plattform",
    "APP_SUBTITLE": "AI-rådgiver",
    "CHAT_PLACEHOLDER": "Skriv meldingen din...",
    "CHAT_SEND_BUTTON": "Send",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Rådgiveren kan gjøre feil, så dobbeltsjekk informasjonen.",
    "STATUS_ONLINE": "På nett",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Meny",
    "ICON_NEW_CHAT": "Ny chat",
    "ICON_HISTORY": "Historikk",
    "ICON_TEMPLATES": "Maler",
    "ICON_SETTINGS": "Innstillinger",
    "ICON_USER_PROFILE": "Brukerprofil",
    "ICON_QUICK_ACTIONS": "Hurtighandlinger",
    "ICON_PINNED": "Festet",
    "ICON_GALLERY": "Galleri",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Installer appen",
    "PWA_ANDROID_MSG": "Installer denne appen på enheten din for en bedre opplevelse og frakoblet tilgang.",
    "PWA_IOS_MSG": "For å installere denne appen på iPhone/iPad:\n1. Trykk på Del-knappen nedenfor\n2. Velg 'Legg til på Hjem-skjermen'",
    "PWA_BTN_INSTALL": "Installer",
    "PWA_BTN_LATER": "Kanskje senere",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Logg inn på rådgivernettverket",
    "AUTH_HEADER_SIGNUP": "Opprett den enhetlige kontoen din",
    "AUTH_HEADER_LOGIN_NETWORK": "Logg inn på rådgivernettverket",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Opprett den enhetlige kontoen din",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Logg inn",
    "AUTH_BUTTON_SIGNUP": "Opprett konto",
    "AUTH_BUTTON_GOOGLE": "Fortsett med Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Glemt passord",
    "AUTH_BUTTON_SEND_RESET_LINK": "Send tilbakestillingslenke",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Har du ikke en konto? Registrer deg",
    "AUTH_PROMPT_LOGIN": "Har du allerede en konto? Logg inn",
    "AUTH_HELPER_TEXT_SIGNUP": "Du oppretter en enhetlig konto som du kan bruke til å få tilgang til alle rådgivere på denne plattformen.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Du oppretter en enhetlig konto som du kan bruke til å få tilgang til alle rådgivere på denne plattformen.",
    "AUTH_HELPER_TEXT_LOGIN": "Bruk samme konto (e-post/passord eller Google) som du brukte for andre rådgivere i dette nettverket.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Bruk samme konto (e-post/passord eller Google) som du brukte for andre rådgivere i dette nettverket.",
    "AUTH_FORGOT_PASSWORD_LINK": "Glemt passordet ditt?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Tilbakestill passordet ditt",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Skriv inn e-postadressen din, så sender vi deg en lenke for å tilbakestille passordet ditt.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-post",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Logger deg inn...",
    "AUTH_STATUS_LOADING_SIGNUP": "Oppretter kontoen din...",
    "AUTH_STATUS_LOADING_RESET": "Sender tilbakestillingslenke...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Innloggingen var vellykket! Laster inn på nytt...",
    "AUTH_STATUS_SUCCESS_RESET": "Tilbakestillingslenke sendt. Sjekk e-posten din.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Lenke for tilbakestilling av passord er sendt. Sjekk e-posten din.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Ugyldig e-postadresse eller passord.",
    "AUTH_ERROR_EMAIL_EXISTS": "En konto med denne e-postadressen finnes allerede i rådgivernettverket.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "En konto med denne e-postadressen finnes allerede. Logg inn. Du er for øyeblikket medlem av:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "En konto med denne e-postadressen finnes allerede i rådgivernettverket. Lukk dette vinduet og bruk 'Innlogging'-delen med samme e-postadresse og det tidligere passordet ditt.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Du er for øyeblikket medlem av:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-postadresse og passord kreves.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Kontoen ble opprettet, men medlemskapet kunne ikke konfigureres. Kontakt kundestøtte.",
    "AUTH_ERROR_DEFAULT": "Det oppstod en feil. Prøv igjen.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Nyttelast for kontroll av gjestebanner er påkrevd.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Bare Bruker Null kan oppdatere kontroller for gjestebanner.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Kunne ikke sende tilbakestillingslenke. Prøv igjen.",
    "INVITE_REPLY_EMAIL_SENT": "Invitasjons-e-posten fra Collabra ble sendt til vennen din på {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Invitasjons-e-posten fra Collabra ble sendt på nytt til vennen din på {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Vis passord",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Skjul passord",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Avbryt",
    "GENERAL_CLOSE": "Lukk",
    "GENERAL_SEND": "Send",
    "GENERAL_SEARCH": "Søk",
    "GENERAL_RESET": "Tilbakestill",
    "GENERAL_ENABLE": "Aktiver",
    "GENERAL_LOADING": "Laster...",
    "GENERAL_DELETE": "Slett",
    "GENERAL_DELETING": "Sletter...",
    "GENERAL_SAVE_PASSWORD": "Lagre passord",
    "AUTH_REMEMBER_EMAIL_LABEL": "Husk e-post",
    "GENERAL_SAVING": "Lagrer...",
    "GENERAL_SENDING": "Sender...",
    "GENERAL_REMOVING": "Fjerner...",
    "GENERAL_CONFIRM_REMOVAL": "Bekreft fjerning",
    "GENERAL_EMPTY": "Tom",
    "GENERAL_UNAVAILABLE": "Ikke tilgjengelig",
    "GENERAL_ENABLED": "Aktivert",
    "GENERAL_DISABLED": "Deaktivert",
    "GENERAL_GRANTED": "Gitt",
    "GENERAL_DENIED": "Avvist",
    "GENERAL_DEFAULT": "Standard",
    "GENERAL_UNSUPPORTED": "Ikke støttet",
    "GENERAL_PUBLIC": "Offentlig",
    "GENERAL_PRIVATE": "Privat",
    "GENERAL_USERNAME": "Brukernavn",
    "GENERAL_EMAIL": "E-post",
    "GENERAL_YOU": "Deg",
    "GENERAL_USER": "Bruker",
    "GENERAL_UNKNOWN": "Ukjent",
    "GENERAL_VISITOR": "Besøkende",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Ukjent banner",
    "GENERAL_ADVISOR_BANNER": "Rådgiverbanner",
    "GENERAL_NOT_AVAILABLE": "Ikke tilgjengelig",
    "GENERAL_NOT_SELECTED": "Ikke valgt",
    "GENERAL_NO_EMAIL_FOUND": "Ingen e-post funnet",
    "GENERAL_USER_ZERO_ONLY": "Kun User Zero",
    "GENERAL_CONNECTION_STATE": "Tilkoblingstilstand",
    "GENERAL_DISPLAY_ONLY": "Kun visning",
    "GENERAL_TEXTAREA": "Tekstområde",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Meny (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Hurtighandlinger (RCAC)",
    "HEADER_CHANGE_STATUS": "Endre status",
    "HEADER_OT_COIN_BALANCE": "OT Coin-saldo",
    "HEADER_ALT_USER": "Bruker",
    "STATUS_BUSY": "Opptatt",
    "STATUS_AWAY": "Borte",
    "STATUS_OFFLINE": "Frakoblet",
    "STATUS_INVISIBLE": "Usynlig",
    "NETWORK_CHECKING_CONNECTION": "Sjekker tilkobling...",
    "NETWORK_ONLINE_LATENCY": "På nett (ventetid: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Nettverk: bra (trykk for å pinge)",
    "CHAT_TARGET_ALT": "Chatmål",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Søk...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Åpne profilbildet til {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Meldingsfelt",
    "CHAT_TOGGLE_VIEW_ARIA": "Bytt visning",
    "CHAT_ADD_USER_ARIA": "Legg til bruker",
    "CHAT_ATTACH_ARIA": "Legg ved",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Send",
    "CHAT_SEARCH_ARIA": "Søk",
    "CHAT_OPEN_SEARCH_ARIA": "Åpne søk",
    "CHAT_CLOSE_SEARCH_ARIA": "Lukk søk",
    "CHAT_ATTACHMENT_ALT": "Vedlegg",
    "CHAT_PREVIEW_ALT": "Forhåndsvisning",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Fjern vedlegg",
    "CHAT_REPLYING_TO": "Svarer på",
    "CHAT_CANCEL_REPLY_ARIA": "Avbryt svar",
    "CHAT_UPLOADING": "Laster opp...",
    "CHAT_LOADING_CHATS": "Laster chatter...",
    "CHAT_SEND_FAILED": "Sending mislyktes",
    "CHAT_SEND_FAILED_RETRY": "Sending mislyktes. Prøv igjen.",
    "CHAT_RETRY": "Prøv igjen",
    "CHAT_EDITED": "redigert",
    "CHAT_TYPING": "Skriver",
    "CHAT_LOADING": "Laster",
    "CHAT_PENDING_INVITATION": "Ventende invitasjon",
    "CHAT_PENDING_INVITATION_MIN": "{count} min ventende invitasjon",
    "CHAT_PENDING_INVITATION_HR": "{count} t ventende invitasjon",
    "CHAT_PENDING_INVITATION_DAY": "{count} d ventende invitasjon",
    "CHAT_WAITING_FOR_YOU": "{label} - Venter på deg",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Venter på aksept",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Mikrofontilgang avvist.",
    "CHAT_UPLOAD_FAILED": "Opplasting mislyktes: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Opplasting krever en internettforbindelse. Prøv igjen når du er på nett.",
    "CHAT_ERROR_AUTH": "Autentiseringsfeil",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Manglende filnavn eller content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Manglende conversation_id eller target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Manglende conversation_id for opplasting uden avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Ugyldig avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase serviceklient er ikke tilgjengelig",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Avatar-lesekvittering er bare gyldig i rådgiverchatkontekst",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatar-flowmelding ble ikke funnet eller er ikke berettiget til lesekvittering",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Kunne ikke markere avatarmelding som lest",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 vedlegg",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} vedlegg",
    "CHAT_VOICE_NOTE": "Talenotat",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat er ikke tilgjengelig. Denne bruker har blokkert dig.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat er ikke tilgjengelig. Du har blokkert denne bruker.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Kontotilgang er blokkert af policy.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat er ikke tilgjengelig. Denne konto er permanent blokkert af User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat er ikke tilgjengelig. Gensidig blokkering er aktiv.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat er ikke tilgjengelig på grund af blokkeringspolicy.",
    "MESSAGE_PREVIEW_PHOTO": "Bilde",
    "MESSAGE_PREVIEW_VOICE": "Talemelding",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Fil",
    "MESSAGE_PREVIEW_MESSAGE": "Melding",
    "MESSAGE_PREVIEW_SYSTEM": "Systemmelding",
    "MESSAGE_PREVIEW_NEW": "Ny melding",
    "MESSAGE_UNKNOWN_FILE": "Ukjent fil",
    "MESSAGE_AUDIO_ATTACHMENT": "Lydvedlegg",
    "MESSAGE_FILE_ATTACHMENT": "Vedlegg",
    "BANNER_INVITED_BY": "invitert av {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Søkeresultater",
    "SEARCH_QUERY_LABEL": "Spørring:",
    "SEARCH_LOADING_VISIBILITY": "Laster søkesynlighet...",
    "SEARCH_NO_RESULTS": "Ingen resultater funnet i gjeldende søkeområde.",
    "SHARE_WITH_COLLABRA": "Del med Collabra",
    "SHARE_SEND_TO": "Send til",
    "SHARE_SELECT_ONE_BANNER": "Velg ett banner",
    "SHARE_BANNER_LIST_ARIA": "Bannerliste",
    "SHARE_NO_MATCHING_BANNER": "Ingen samsvarende banner",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Legg til en kommentar...",
    "SHARE_RECENT_CHATS": "Nylige chatter",
    "SHARE_LEFT_LIST": "Venstre liste",
    "SHARE_RIGHT_LIST": "Høyre liste",
    "SHARE_UNTITLED_BANNER": "Banner uten tittel",
    "SHARE_SHARED_CONTENT": "Delt innhold",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Det delte indhold kunne ikke åpnees.",
    "SHARE_OPEN_BANNER_FAILED": "Kunne ikke åpnee det valgte banner.",
    "SHARE_ONE_PHOTO_SELECTED": "1 foto valgt",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} fotos valgt",
    "SHARE_ONE_FILE_SELECTED": "1 fil valgt",
    "SHARE_MANY_FILES_SELECTED": "{count} filer valgt",
    "FORWARD_MESSAGE_TITLE": "Videresend melding",
    "FORWARD_SELECT_RECIPIENTS": "Velg mottakere",
    "FORWARD_NO_OTHER_BANNER": "Ingen andre bannere tilgjengelige.",
    "FORWARD_SEND_TO_COUNT": "Send til {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Velg minst ett banner.",
    "FORWARD_FAILED_DEFAULT": "Videresending mislyktes. Prøv igjen.",
    "FORWARD_PARTIAL_SENT": "{count} sendt. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Kildemelding ikke funnet for videresending",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Denne meldingen har ikke noe videresendbart innhold ennå",
    "FORWARD_DESTINATION_MISSING": "Videresendingsmålet mangler",
    "FORWARD_MESSAGE_PREVIEW": "Videresendt melding",
    "MENU_PASTE": "Lim inn",
    "MENU_COPY": "Kopier",
    "MENU_REPLY": "Svar",
    "MENU_FORWARD": "Videresend",
    "MENU_REMOVE_INVITATION": "Fjern invitasjon",
    "MENU_REMOVE_FROM_LIST": "Fjern fra liste",
    "MENU_GOODBYE_GUEST": "Ha det, gjest",
    "MENU_ADD_TO_LIST": "Legg til i liste",
    "MENU_REJECT_INVITATION": "Avvis invitasjon",
    "MENU_FRONTEND_VERSION": "Frontend-versjon",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Bannerinformasjon: {title}",
    "MENU_MESSAGE_BUBBLE": "Meldingsboble",
    "MENU_CHAT_CANVAS_HEADER": "Chat-lerret - {zone}",
    "MENU_CANVAS_INFO": "Lerretsinformasjon",
    "MENU_CHAT_CANVAS_SUBLABEL": "Samtaleområde / gjeldende chatflate",
    "MENU_INPUT_AREA_HEADER": "Inndataområde - {zone}",
    "MENU_INPUT_AREA_INFO": "Informasjon om inndataområde: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Nederste flate for skriving og handlingsverktøy",
    "MENU_HEADER": "Topptekst - {zone}",
    "MENU_HEADER_INFO": "Topptekstinformasjon: {title}",
    "MENU_HEADER_DESCRIPTION": "Øvre navigasjon og sidekontroller",
    "MENU_ZONE_HEADER": "Sone - {zone}",
    "MENU_ZONE_SPACE_INFO": "Informasjon om soneområde",
    "MENU_EMPTY_LIST_SURFACE": "Tom/listflate",
    "MENU_BLOCK": "Blokker",
    "MENU_UNBLOCK": "Opphev blokkering",
    "MENU_HIDE_IN_SEARCH": "Skjul i søk",
    "MENU_UNHIDE_IN_SEARCH": "Vis i søk",
    "MENU_VISIBLE_IN_SEARCH": "Synlig i søk",
    "MENU_HIDDEN_IN_SEARCH": "Skjult i søk",
    "MENU_VISIBLE_IN_USER_LIST": "Synlig i brukerliste",
    "MENU_HIDDEN_IN_USER_LIST": "Skjult i brukerliste",
    "MENU_NOT_BLOCKED": "Ikke blokkert",
    "MENU_BLOCKED": "Blokkert",
    "MENU_FRONTEND_VERSION_LOADING": "Laster...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Laster værdi pr. banner fra backend. Ingen mulighed markeres som aktiv, før databaseresponsen ankommer.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend-værdien kunne ikke indleses. Ingen betroet aktiv mulighed vises.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Eksplicit databaseværdi pr. banner er {overrideVersion}. Global standard er {globalDefaultVersion}. Målbrukeren skal laste inn på nytt fuldt eller genåpnee appen, for at oppstarts-bootstrap kan anvende den.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Ingen eksplicit databaseværdi pr. banner er lagret. FeV2.0.0 er aktiv som standard. Global standard er {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Eksplicit databaseværdi pr. banner bliver aktiv, efter målappen er fuldt genindlest",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Ingen eksplicit værdi pr. banner er lagret; dette er den individuelle FeV2.0.0-standardtilstand",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Denne mulighed er også lig med den aktuelle globale standard",
    "MENU_DELETE_PERMANENT_CONFIRM": "Slett {target} permanent fra databasen? Dette fjerner kontoen, chathistorik, afhængigheder og tvinger en helt ny invitasjonsvej for fremtidig genindtræden.",
    "MENU_DELETE_PERMANENTLY": "Slett permanent",
    "MENU_REFRESH_PAGE": "Oppdater siden",
    "MENU_LOG_OFF": "Logg av",
    "MENU_HARD_RELOAD": "Hard omlasting",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-post (administratorbruker)",
    "AUTH_PASSWORD_PLACEHOLDER": "Passord",
    "AUTH_CONNECTING": "Kobler til...",
    "AUTH_SIGNING_OUT": "Logger av...",
    "AUTH_BACK_TO_LOGIN": "Tilbake til innlogging",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Ugyldig serversvar: ingen token funnet.",
    "AUTH_LOGIN_FAILED": "Innlogging mislyktes",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Passordene samsvarer ikke.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Passordene samsvarer ikke!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Passordene må samsvare nøyaktig.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nytt passord",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Bekreft passord",
    "AUTH_CHANGE_PASSWORD": "Endre passord",
    "AUTH_SAVING_PASSWORD": "Lagrer...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Passordet er oppdatert.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Kan ikke endre passord akkurat nå.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Du må være logget inn for å endre passordet ditt.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Skift synlighet for ny passord",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Skift synlighet for bekræftelse af passord",
    "REGISTER_TITLE": "Fullfør registrering",
    "REGISTER_SUBTITLE": "Angi passordet ditt manuelt.",
    "REGISTER_CREATING_ACCOUNT": "Oppretter konto...",
    "REGISTER_FINISH_SETUP": "Fullfør oppsett",
    "REGISTER_FAILED_SET_PASSWORD": "Kunne ikke angi passord",
    "INVITE_EMAIL_INSTRUCTION": "Skriv inn e-postadressen til den inviterte (format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Inviter",
    "INVITE_EMAIL_REQUIRED": "Skriv inn e-postadressen til den inviterte.",
    "INVITE_EMAIL_INVALID": "Ugyldig e-postformat. Bruk: user@example.com",
    "PENDING_INVITATION_TITLE": "Ventende invitasjon",
    "PENDING_INVITATION_REMOVE_QUESTION": "Fjerne denne ventende invitasjonen fra databasen?",
    "PENDING_INVITATION_KEEP": "Behold invitasjon",
    "PENDING_INVITATION_REMOVAL_FAILED": "Fjerning mislyktes.",
    "REMOVE_FROM_LIST_TITLE": "Fjern fra liste",
    "REMOVE_FROM_LIST_WARNING": "Fjerne denne brukeren fra begge listene nå? Chattilgangen kuttes umiddelbart. Den eneste veien tilbake er en ny invitasjon.",
    "REMOVE_FROM_LIST_KEEP": "Behold bruker i listen",
    "REMOVE_FROM_LIST_FAILED": "Fjerning fra liste mislyktes.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Innstilling og livestatus",
    "PERMISSION_DIALOG_ARIA": "Innstilling og livestatus",
    "PERMISSION_TRIGGER_ARIA": "Utløser for innstillingspopup",
    "PERMISSION_CLOSE_ARIA": "Lukk tillatelsespopup",
    "PERMISSION_LIVE_STATUS": "Livestatus",
    "PERMISSION_SYSTEM_PERMISSION": "Systemtillatelse",
    "PERMISSION_APP_PUSH": "App-push",
    "PERMISSION_LOCATION_PERMISSION": "Posisjonstillatelse",
    "PERMISSION_APP_LOCATION": "App-posisjon",
    "PERMISSION_CONTROLS": "Tillatelseskontroller",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push-varsler",
    "PERMISSION_LOCATION_ACCESS": "Posisjonstilgang",
    "PERMISSION_IN_APP_SETTINGS": "Innstillinger i appen",
    "PERMISSION_ALERT_SOUND": "Varslingslyd",
    "PERMISSION_APP_BADGE": "App-merke",
    "PERMISSION_PASSWORD_SETTINGS": "Passordinnstillinger",
    "PERMISSION_NAVIGATION_STATUS": "Navigasjonsstatus",
    "PERMISSION_SELECTED_ZONE": "Valgt sone",
    "PERMISSION_STAGED_CHAT_BANNER": "Klargjort chatbanner",
    "PERMISSION_CANVAS_CONTENT": "Lerretsinnhold",
    "PERMISSION_YOUR_DEVICES": "Dine enheter ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Oppdater enhetsliste",
    "PERMISSION_REFRESH_LIST": "Oppdater liste",
    "PERMISSION_NO_REGISTERED_DEVICES": "Ingen registrerte enheter funnet.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Endre størrelse på innstillingspopup",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Slå push-varsler av/på",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Slå posisjonstilgang av/på",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Slå varslingslyd av/på",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Slå app-merke av/på",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Slå profilsynlighet av/på",
    "PERMISSION_OFF_IN_V1": "Av i v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Bannerliste",
    "PERMISSION_PUSH_DISABLED_V1": "Pushvarsler er deaktivert for v1 Google Play-utgivelsen.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Pushvarsler er slået TIL for denne enhet.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Systemvarsler er blokkert. Trykk for at åpnee hjælp til indstillinger.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Slå TIL for å forbedre leveringspåliteligheten.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "For at deaktivere systemvarsler skal du åpnee browserens/webstedets varselsindstillinger og sætte dette websted til Blokker.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "For at ændre systemvarselstillatelse skal du åpnee browserens/webstedets varselsindstillinger og sætte dette websted til Tillat.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Posisjonstilgang er slået TIL for avstandsbaseret LCAC-sortering og kartposisjonering.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Posisjons-API understøttes ikke i dette miljø.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Posisjonstilgang er blokkert. Trykk for at åpnee hjælp til indstillinger.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Slå TIL for at tillate presis avstandsbaseret LCAC-sortering og kartposisjonering i appen.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Posisjonstilgang understøttes ikke i dette miljø.",
    "PERMISSION_LOCATION_DISABLE_HELP": "For at deaktivere posisjonstilgang skal du åpnee browserens/webstedets posisjonsindstillinger og sætte dette websted til Blokker.",
    "PERMISSION_LOCATION_ALLOW_HELP": "For at aktivere posisjonstilgang til avstandssortering og kartposisjonering i appen skal du åpnee browserens/webstedets posisjonsindstillinger og sætte dette websted til Tillat.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Kan ikke indlese registrerte enheter lige nu.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Laster UI-bro...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Laster lokal bro...",
    "RUNTIME_LOADING_BACKEND": "Laster backend...",
    "RUNTIME_LOADING": "Laster...",
    "RUNTIME_LOADING_FROM_DATABASE": "Laster fra database...",
    "RUNTIME_BACKEND_CONNECTED": "Backend tilkoblet",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Bufret fallback aktiv",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Standard fallback aktiv",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Standard fallback-verdier aktive",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Lagrer via backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Lagret i backend-tjeneste",
    "RUNTIME_SAVE_FAILED": "Lagring mislyktes",
    "RUNTIME_LOAD_FAILED": "Lasting mislyktes",
    "RUNTIME_CONNECTED": "Tilkoblet",
    "RUNTIME_LOGIN_REQUIRED": "Innlogging kreves",
    "RUNTIME_SAVED": "Lagret",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI klar - runtime venter",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Den beskyttede backend-selektortjeneste avviste eller kunne ikke lagreme den ønskede modellindstilling.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Den beskyttede backend-selektortjeneste avviste eller kunne ikke lagreme den ønskede WF1-ruteændring.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selektoren leser nu aktiv konfiguration, Qwen-routing og tillatte muligheder fra den beskyttede backendtjeneste.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend-selektortjenesten er ikke tilgjengelig lige nu, så den senest cachede selektortilstand bruges.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Selektorens standardverdier er aktive, fordi ingen backend- eller bufret selektortilstand kunne indleses.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Den beskyttede backend-selektortjeneste oppdaterte den aktive WF1-routingkonfiguration og oppdaterte runtime-domenecachen.",
    "FRONTEND_VERSION_TITLE": "Frontend-versjon",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Denne selektor styrer den aktive frontend-version for alle brukere. FeV2.0.0 er aktiv.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Denne selektor leser den aktive frontend-version fra config_domain_registry. Runtime opløses til FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend-konfigurationen for frontend-version kunne ikke indleses, så den kodede FeV2.0.0-standard er aktiv, til oppstarts-bootstrap kan lese den beskyttede tjeneste igen.",
    "FRONTEND_VERSION_HELPER_SAVED": "Den aktive frontend-version ble lagret i config_domain_registry. En fuld opdatering eller neste applasting anvender runtime-værdien.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend-kontrolltjenesten for frontend-version kunne ikke lagreme den ønskede globale version.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktiv frontend-versjon.",
    "CHAT_DELETE_WINDOW_TITLE": "Vindu for chatsletting",
    "CHAT_DELETE_HELPER": "Denne værdi styrer tilgjengelighedsvinduet for Slett for alle i sekunder. Backend-vakten ændres umiddelbart efter lagrening. Boblesynligheten ændres efter en fuld opdatering eller neste applasting.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend-kontrolltjenesten for chatslettning kunne ikke indleses, så den kodede standard forbliver aktiv, til oppstarts-bootstrap kan lese den beskyttede tjeneste igen.",
    "CHAT_DELETE_HELPER_SAVED": "Tilgjengelighedsvinduet for Slett for alle ble lagret i config_domain_registry. Backend-vakten ændres umiddelbart. Boblesynligheten ændres efter en fuld opdatering eller neste applasting.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend-kontrolltjenesten for chatslettning kunne ikke lagreme den ønskede vinduesværdi.",
    "CHAT_DELETE_WINDOW_LABEL": "Vindu for Slett for alle",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} sek",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Lagre verdien i hele sekunder. Gjeldende produksjonsverdi er 86400 sekunder = 1 dag.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Vindusekunder",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Skriv inn et heltall større enn eller lik 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Lagre slettevindu",
    "GUEST_BANNER_CONTROL_TITLE": "Gjestebanner",
    "GUEST_BANNER_CONTROL_LABEL": "Gjest QR-chat",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Vis gjestebanner for alle brukere",
    "GUEST_BANNER_CONTROL_HELPER": "Kontrollerer det faste gjestebanneret og levetiden for ventende QR-token.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Lokal reserve er aktiv for gjestebannerkontroller.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Gjestebannerkontroller lagret.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Gjestebannerkontroller kunne ikke lagres.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} gjesteøkter inndratt.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "Ventende QR TTL (minutter)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "Nåværende ventende QR TTL: {count} minutter.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Angi et positivt heltall i minutter.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Lagre gjestebanner",
    "GUEST_QR_LOADING": "Klargjør gjeste-QR...",
    "GUEST_QR_READY": "Skann for å åpne den midlertidige gjestechatten.",
    "GUEST_QR_ALT": "QR-kode for gjestechat",
    "GUEST_QR_LOAD_FAILED": "Gjeste-QR kunne ikke klargjøres.",
    "GUEST_SESSION_ACTIVE": "Gjest er tilkoblet.",
    "GUEST_PUBLIC_TITLE": "Gjestechat",
    "GUEST_PUBLIC_CONNECTING": "Kobler til ...",
    "GUEST_PUBLIC_CONNECTED": "Tilkoblet",
    "GUEST_PUBLIC_UNAVAILABLE": "Denne gjestelenken er utilgjengelig.",
    "GUEST_PUBLIC_SEND_FAILED": "Meldingen kunne ikke sendes.",
    "UI_TEXTS_RUNTIME_TITLE": "Kjøretid for UI-språk",
    "UI_TEXTS_RUNTIME_BACKEND": "Kjøretid for UI-språk leser fra den beskyttede backend-tjenesten. Endringer trer i kraft ved neste fullstendige app-innlasting.",
    "UI_TEXTS_RUNTIME_CACHED": "Backend-tjenesten for kjøretid for UI-språk er utilgjengelig akkurat nå, så hurtigbufrede eller lokale standardinnstillinger er aktive.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "Standardinnstillinger for UI-språk er aktive fordi ingen backend- eller bufret tilstand kunne lastes.",
    "UI_TEXTS_RUNTIME_SAVED": "Kontroll for UI-språk ble lagret. En fullstendig oppdatering eller neste app-innlasting er nødvendig for at brukere skal motta den nye språkporten.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Den beskyttede backend-tjenesten kunne ikke lagre den forespurte endringen av UI-språk.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Anvendelse av enhetsspråk",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Aktiver UI-språk for kjøretid",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Brukere kan motta UI-tekst-nyttelaster for sitt lagrede språk eller enhetsspråk.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Alle brukere tvinges til engelsk UI-tekst, og enhetens språk ignoreres.",
    "PROFILE_VISIBILITY_TITLE": "Profilsynlighet",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Du skal være logget ind for at administrere kontosynlighet.",
    "PROFILE_VISIBILITY_HELPER": "Denne kontakt oppdaterer kun kontoen dins synlighetstilstand. Synlighet i søkning og bannerlisteadfærd forbliver uændret i denne fase.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Profilsynlighet kunne ikke indleses lige nu.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Profilsynlighet kunne ikke opdateres lige nu.",
    "PROFILE_VISIBILITY_SAVED": "Din kontosynlighet er nu {visibility}. Synlighetsflag forbliver uændrede i denne fase.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Offentlig konto",
    "PROFILE_VISIBILITY_STORED": "Lagret synlighet",
    "WF1_MODEL_CONTROL_TITLE": "WF1-modellkontroll",
    "WF1_ENABLE_TRANSLATION": "Aktiver oversettelse / pivot",
    "WF1_TRANSLATION_ACTIVE": "AI-oversettelse er aktiv.",
    "WF1_TRANSLATION_INACTIVE": "WF1 fortsætter med at køre, men kildeteksten kopieres, og pivot markeres som inaktiv.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktiv runtime-plass",
    "WF1_ALLOW_SAME_LANGUAGE": "Tillat AI for språkpar med samme språk",
    "WF1_SAME_LANGUAGE_ACTIVE": "Språkpar med samme språk følger normal WF1-routing.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Språkpar med samme språk omgår AI og lagremer Ingen aktivt pivotspråk.",
    "WF1_QWEN_ROUTING": "Qwen-parruting",
    "WF1_QWEN_ROUTING_HELPER": "Språk merket nedenfor bruker Qwen-Max, når parret enten er det samme markerede språk, et merket språk med engelsk eller to markerede ikke-engelske språk. Ellers forbliver den valgte primære modell aktiv.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter-testplass",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter-testslot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Kun kvalitetstest",
    "WF1_OPENROUTER_HELPER": "Denne slot kan kun redigeres til midlertidige OpenRouter-kvalitetstests. Den ændrer ikke den operationelle Qwen-parroutingsti, medmindre denne slot selv bliver den aktive modell.",
    "WF1_LABEL": "Etikett",
    "WF1_PRODUCT": "Produkt",
    "WF1_MODEL": "Modell",
    "WF1_PROVIDER_OPENROUTER": "Leverandør: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Hemmelighet: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Lagreini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Lagreini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Lagreini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter-testslot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max via OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google listepris",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI listepris",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter listepris",
    "LANGUAGE_ENGLISH": "Engelsk",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Kinesisk (forenklet)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Kinesisk (tradisjonell)",
    "LANGUAGE_JAPANESE": "Japansk",
    "LANGUAGE_KOREAN": "Koreansk",
    "LANGUAGE_PERSIAN": "Persisk",
    "LANGUAGE_TURKISH_ISTANBUL": "Tyrkisk (Istanbul)",
    "LANGUAGE_ARABIC": "Arabisk",
    "LANGUAGE_FRENCH": "Fransk",
    "LANGUAGE_GERMAN": "Tysk",
    "LANGUAGE_SPANISH": "Spansk",
    "LANGUAGE_PORTUGUESE": "Portugisisk",
    "LANGUAGE_ITALIAN": "Italiensk",
    "LANGUAGE_RUSSIAN": "Russisk",
    "LANGUAGE_DUTCH": "Nederlandsk",
    "LANGUAGE_VIETNAMESE": "Vietnamesisk",
    "LANGUAGE_INDONESIAN": "Indonesisk",
    "LANGUAGE_THAI": "Thai",
    "LANGUAGE_MALAY": "Malayisk",
    "WF1_PRICING_CUSTOM": "Prising: egendefinert plassmodell - sjekk gjeldende OpenRouter-prising",
    "WF1_SAVE_OPENROUTER_SLOT": "Lagre OpenRouter-plass",
    "WF1_PRICING_LINE": "Inndata {input} - Utdata {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Hemmelighet: {secret}",
    "ZONE_VISIBILITY_TITLE": "Kontroll for sonesynlighet",
    "ZONE_ENABLE": "Aktiver {zone}",
    "ZONE_ENABLED_NOTE": "{zone} kan vises for tillatte roller efter neste applasting.",
    "ZONE_DISABLED_NOTE": "{zone} behandles som fraværende for ikke-S_Admin-brukere efter neste applasting.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin omgår denne rollelistenn og beholder altid tilgang.",
    "ZONE_ROLE_LOCKED": "Rollevalg er midlertidig låst, mens denne sone er deaktivert, og vender tilbage presis som lagret, når sonen aktiveres igen.",
    "ZONE_LCAC_CONTROL": "LCAC-kontroll",
    "ZONE_RCAC_CONTROL": "RCAC-kontroll",
    "ZONE_LCAC_DESCRIPTION": "Styrer eksistensen af den venstre reserverede sone og de roller, der kan se den.",
    "ZONE_RCAC_DESCRIPTION": "Styrer eksistensen af den højre reserverede sone og de roller, der kan se den.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap for sonesynlighet leser nu fra den beskyttede backendtjeneste. Ændringer anvendes ved neste applasting.",
    "ZONE_VISIBILITY_CACHED": "Backendtjenesten for sonesynlighet er ikke tilgjengelig lige nu, så cachede eller lokale standarder er aktive.",
    "ZONE_VISIBILITY_DEFAULTS": "Standarder for sonesynlighet er aktive, fordi ingen backend- eller bufret tilstand kunne indleses.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap for sonesynlighet ble lagret. Hard omlasting eller neste applasting er kreves for runtime-anvendelse.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Den beskyttede backendtjeneste kunne ikke lagreme den ønskede ændring af sonesynlighet.",
    "ROLE_MEMBER": "Medlem",
    "ROLE_STAFF": "Ansatte",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Aktiver varsler for å motta nye meldinger.",
    "MAIN_LOG_OUT": "Logg av",
    "NOTIFICATION_NEW_MESSAGE": "Ny melding",
    "NOTIFICATION_UNREAD_MESSAGE": "Du har en ulest melding.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Full visning",
    "MEDIA_AUDIO_ATTACHMENT": "Lydvedlegg",
    "MEDIA_FILE_FALLBACK": "Fil",
    "MEDIA_DOWNLOAD_READY": "Vedlegg klart for nedlasting",
    "MEDIA_TYPE_UNSUPPORTED": "Typen støttes ikke i full visning",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Forrige bilde",
    "MEDIA_NEXT_IMAGE_ARIA": "Neste bilde",
    "MEDIA_OPEN_ORIGINAL": "Åpne original",
    "MEDIA_DOWNLOAD": "Last ned",
    "MEDIA_CLOSE_ARIA": "Lukk",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name} profilbilde",
    "MEDIA_PROFILE_ALT": "{name} profil",
    "MEDIA_UPLOAD_FAILED": "Opplasting mislyktes",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend-tokenfeil",
    "MEDIA_UPLOAD_URL_MISSING": "Kritisk: opplasting-URL mangler i backend-svaret.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Manglende godkendelsestoken til chatopplasting",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Anmodning om chatopplastingtoken mislyktes",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Ugyldigt chatopplastingsvar",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS-opplasting mislyktes",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Manglende filnavn eller contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path mangler",
    "BLOCK_NOTICE_TITLE": "Varsel om permanent blokkering",
    "BLOCK_NOTICE_MESSAGE": "Kontoen din er midlertidig suspendert på grunn av brudd på policyen.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Hvis du mener dette krever oppfølging, kontakt",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "via e-post.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Ukjent bruker",
    "GENERAL_GUEST": "Gjest",
    "ADVISOR_FOR_CLIENT": "Rådgiver for {client_display_name}",
    "GUEST_FOR_CLIENT": "Gjest for {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token og passord kreves",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Forespørselens body må være JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Ugyldig eller utløpt invitasjonstoken",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Angielse af passord mislyktes: manglende session eller bruker",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Angielse af passord mislyktes under innlogging",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Generering af admintoken mislyktes",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Innlogging mislyktes: manglende session eller bruker",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registrering lykkedes. Sjekk vennligst e-post for bekræftelse.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Registrering mislyktes ukjent",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Ugyldig tokenbehandling",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Tilgangstoken kreves",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Token-hashforhåndsvisning kræver e-posthint fra redirect-URL",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Kan ikke løse identitet for denne tokenen",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Bare User Zero kan få tilgang til WF1 LLM-selektortjenesten.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Bare User Zero kan få tilgang til kontrolltjenesten for sonesynlighet.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Bare User Zero kan få tilgang til kontrolltjenesten for frontend-version.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Bare User Zero kan inspicere en anden brukers frontend-version.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Bare User Zero kan få tilgang til kontrolltjenesten for chatslettning.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Kun Bruker Null har tilgang til tjenesten for kjøretidskontroll av UI-språk.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Bare User Zero kan permanent slettte en brukerkonto.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Ugyldig forespørselspayload.",
    "API_ERROR_INTERNAL_SERVER": "Intern serverfeil",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funksjon mangler i backend (genindlæsning kreves)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Kun DB RPC er tillatt for delivered/read-overgange.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Vent før du sender en ny melding.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Melding sendt.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Kontakttjenesten er utilgjengelig.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Sending av melding mislyktes.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Navn kreves.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-postadressen er ugyldig.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Melding kreves.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Selektorpayload er kreves.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload for sonesynlighet er kreves.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload for frontend-version er kreves.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload for chatslettningskontrol er kreves.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Nyttelast for kjøretidskontroll av UI-språk er påkrevd.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Godkendt bruker-id er kreves.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Godkendt viewer-bruker-id er kreves.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Godkendt aktør-bruker-id er kreves.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id kreves.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id kreves.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids-liste er kreves.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email kreves.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by kreves.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Søkeruntime er deaktivert af global frontend-version.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Du har ikke tillatelse til at avbryte denne afventende invitasjon.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Denne invitasjon kan ikke lenger avbrytes, fordi brukeren allerede er registreret.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Ventende invitasjon ikke funnet.",
    "INVITE_REPLY_ALREADY_MEMBER": "Gratulerer, vennen din ({invitee_email}) er allerede registrert i denne appen og er medlem av dette arbeidsområdet.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "En invitasjon afventer for {invitee_email}, men retry-e-posten kunne ikke udløses. Sjekk vennligst mail-loggene.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Invitasjonsposten ble opprettet for {invitee_email}, men e-postlevering kunne ikke bekræftes. Prøv igjen senere eller sjekk mail-loggene.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Kunne ikke opprette invitasjonsoppføring. Prøv igjen senere.",
    "INVITE_REPLY_SYSTEM_ERROR": "Systemfeil under invitasjonsprosessen: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend-konfigurasjonsfeil: manglende Supabase-legitimasjon",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend-konfigurasjonsfeil: ugyldig Supabase-URL",
    "CHAT_ERROR_ACCESS_DENIED": "Tilgang avvist",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Innhold kan ikke være tomt for tekstmeldinger",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Kunne ikke fastslå samtale-ID",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC-autentiseringskontekst mangler",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC returnerede ugyldig meldingpayload",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Lim inntelse mislyktes, ingen data returnert",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations må være en liste",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Ugyldig operationspayload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type understøttes ikke",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id kreves",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Melding ikke funnet",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Sletting er bare tillatt for din egen melding",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Slett for alle er ikke lenger tilgjengelig for denne meldingen",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Slett for alle mislyktes",
    "API_ERROR_SERVER_CONFIGURATION": "Serverkonfigurasjonsfeil",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Manglende webhook-hemmelighetshode",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Uautorisert webhook-kilde",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend-konfigurasjonsfeil",
    "API_ERROR_MODULE_ATTRIBUTE": "Modulattributtfeil: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Mislyktes før invitasjonsslettning under fjerning af ventende auth-bruker.",
    "CHAT_ERROR_DB": "DB-feil: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
