# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/pl.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Główna",
    "APP_TITLE": "Platforma AI OTMEGA",
    "APP_SUBTITLE": "Doradca AI",
    "CHAT_PLACEHOLDER": "Wpisz wiadomość...",
    "CHAT_SEND_BUTTON": "Wyślij",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Doradca może popełniać błędy, więc sprawdź informacje.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Nowy czat",
    "ICON_HISTORY": "Historia",
    "ICON_TEMPLATES": "Szablony",
    "ICON_SETTINGS": "Ustawienia",
    "ICON_USER_PROFILE": "Profil użytkownika",
    "ICON_QUICK_ACTIONS": "Szybkie akcje",
    "ICON_PINNED": "Przypięte",
    "ICON_GALLERY": "Galeria",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Zainstaluj aplikację",
    "PWA_ANDROID_MSG": "Zainstaluj tę aplikację na swoim urządzeniu, aby uzyskać lepsze doświadczenie i dostęp offline.",
    "PWA_IOS_MSG": "Aby zainstalować tę aplikację na iPhonie/iPadzie:\n1. Stuknij przycisk Udostępnij poniżej\n2. Wybierz 'Dodaj do ekranu początkowego'",
    "PWA_BTN_INSTALL": "Zainstaluj",
    "PWA_BTN_LATER": "Może później",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Zaloguj się do sieci doradców",
    "AUTH_HEADER_SIGNUP": "Utwórz swoje ujednolicone konto",
    "AUTH_HEADER_LOGIN_NETWORK": "Zaloguj się do sieci doradców",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Utwórz swoje ujednolicone konto",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Logowanie",
    "AUTH_BUTTON_SIGNUP": "Utwórz konto",
    "AUTH_BUTTON_GOOGLE": "Kontynuuj z Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Nie pamiętam hasła",
    "AUTH_BUTTON_SEND_RESET_LINK": "Wyślij link resetujący",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Nie masz konta? Zarejestruj się",
    "AUTH_PROMPT_LOGIN": "Masz już konto? Zaloguj się",
    "AUTH_HELPER_TEXT_SIGNUP": "Tworzysz ujednolicone konto, którego możesz używać do dostępu do wszystkich doradców na tej platformie.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Tworzysz ujednolicone konto, którego możesz używać do dostępu do wszystkich doradców na tej platformie.",
    "AUTH_HELPER_TEXT_LOGIN": "Użyj tego samego konta (email/hasło lub Google), którego używano dla innych doradców w tej sieci.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Użyj tego samego konta (email/hasło lub Google), którego używano dla innych doradców w tej sieci.",
    "AUTH_FORGOT_PASSWORD_LINK": "Nie pamiętasz hasła?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Zresetuj hasło",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Wpisz swój adres email, a wyślemy Ci link do zresetowania hasła.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Email",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Logowanie...",
    "AUTH_STATUS_LOADING_SIGNUP": "Tworzenie konta...",
    "AUTH_STATUS_LOADING_RESET": "Wysyłanie linku resetującego...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Logowanie udane! Ponowne ładowanie...",
    "AUTH_STATUS_SUCCESS_RESET": "Link resetujący został pomyślnie wysłany. Sprawdź pocztę email.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Link do resetowania hasła został pomyślnie wysłany. Sprawdź pocztę email.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Nieprawidłowy email lub hasło.",
    "AUTH_ERROR_EMAIL_EXISTS": "Konto z tym adresem email już istnieje w sieci doradców.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Konto z tym adresem email już istnieje. Zaloguj się. Obecnie jesteś członkiem:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Konto z tym adresem email już istnieje w sieci doradców. Zamknij to okno i użyj sekcji 'Login' z tym samym adresem email i poprzednim hasłem.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Obecnie jesteś członkiem:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "Email i hasło są wymagane.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Konto zostało utworzone, ale nie udało się skonfigurować członkostwa. Skontaktuj się z pomocą techniczną.",
    "AUTH_ERROR_DEFAULT": "Wystąpił błąd. Spróbuj ponownie.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "",
    "AUTH_FORGOT_PASSWORD_ERROR": "Nie udało się wysłać linku resetującego. Spróbuj ponownie.",
    "INVITE_REPLY_EMAIL_SENT": "Email z zaproszeniem Collabra został wysłany do Twojego znajomego na adres {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Email z zaproszeniem Collabra został ponownie wysłany do Twojego znajomego na adres {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Pokaż hasło",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Ukryj hasło",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Anuluj",
    "GENERAL_CLOSE": "Zamknij",
    "GENERAL_SEND": "Wyślij",
    "GENERAL_SEARCH": "Szukaj",
    "GENERAL_RESET": "Resetuj",
    "GENERAL_ENABLE": "Włącz",
    "GENERAL_LOADING": "Ładowanie...",
    "GENERAL_DELETE": "Usuń",
    "GENERAL_DELETING": "Usuwanie...",
    "GENERAL_SAVE_PASSWORD": "Zapisz hasło",
    "AUTH_REMEMBER_EMAIL_LABEL": "Zapamiętaj email",
    "GENERAL_SAVING": "Zapisywanie...",
    "GENERAL_SENDING": "Wysyłanie...",
    "GENERAL_REMOVING": "Usuwanie...",
    "GENERAL_CONFIRM_REMOVAL": "Potwierdź usunięcie",
    "GENERAL_EMPTY": "Puste",
    "GENERAL_UNAVAILABLE": "Niedostępne",
    "GENERAL_ENABLED": "Włączone",
    "GENERAL_DISABLED": "Wyłączone",
    "GENERAL_GRANTED": "Przyznano",
    "GENERAL_DENIED": "Odmówiono",
    "GENERAL_DEFAULT": "Domyślne",
    "GENERAL_UNSUPPORTED": "Nieobsługiwane",
    "GENERAL_PUBLIC": "Publiczne",
    "GENERAL_PRIVATE": "Prywatne",
    "GENERAL_USERNAME": "Nazwa użytkownika",
    "GENERAL_EMAIL": "Email",
    "GENERAL_YOU": "Ty",
    "GENERAL_USER": "Użytkownik",
    "GENERAL_UNKNOWN": "Nieznane",
    "GENERAL_VISITOR": "Gość",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Baner",
    "GENERAL_UNKNOWN_BANNER": "Nieznany baner",
    "GENERAL_ADVISOR_BANNER": "Baner doradcy",
    "GENERAL_NOT_AVAILABLE": "N/D",
    "GENERAL_NOT_SELECTED": "Nie wybrano",
    "GENERAL_NO_EMAIL_FOUND": "Nie znaleziono emaila",
    "GENERAL_USER_ZERO_ONLY": "Tylko User Zero",
    "GENERAL_CONNECTION_STATE": "Stan połączenia",
    "GENERAL_DISPLAY_ONLY": "Tylko wyświetlanie",
    "GENERAL_TEXTAREA": "Pole tekstowe",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Czat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Szybkie akcje (RCAC)",
    "HEADER_CHANGE_STATUS": "Zmień status",
    "HEADER_OT_COIN_BALANCE": "Saldo OT Coin",
    "HEADER_ALT_USER": "Użytkownik",
    "STATUS_BUSY": "Zajęty",
    "STATUS_AWAY": "Nieobecny",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Niewidoczny",
    "NETWORK_CHECKING_CONNECTION": "Sprawdzanie połączenia...",
    "NETWORK_ONLINE_LATENCY": "Online (opóźnienie: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Sieć: dobra (stuknij, aby wykonać ping)",
    "CHAT_TARGET_ALT": "Cel czatu",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Szukaj...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Otwórz zdjęcie profilowe {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Pole wiadomości",
    "CHAT_TOGGLE_VIEW_ARIA": "Przełącz widok",
    "CHAT_ADD_USER_ARIA": "Dodaj użytkownika",
    "CHAT_ATTACH_ARIA": "Załącz",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Wyślij",
    "CHAT_SEARCH_ARIA": "Szukaj",
    "CHAT_OPEN_SEARCH_ARIA": "Otwórz wyszukiwanie",
    "CHAT_CLOSE_SEARCH_ARIA": "Zamknij wyszukiwanie",
    "CHAT_ATTACHMENT_ALT": "Załącznik",
    "CHAT_PREVIEW_ALT": "Podgląd",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Usuń załącznik",
    "CHAT_REPLYING_TO": "Odpowiedź do",
    "CHAT_CANCEL_REPLY_ARIA": "Anuluj odpowiedź",
    "CHAT_UPLOADING": "Przesyłanie...",
    "CHAT_LOADING_CHATS": "Ładowanie czatów...",
    "CHAT_SEND_FAILED": "Wysyłanie nie powiodło się",
    "CHAT_SEND_FAILED_RETRY": "Wysyłanie nie powiodło się. Spróbuj ponownie.",
    "CHAT_RETRY": "Ponów",
    "CHAT_EDITED": "edytowano",
    "CHAT_TYPING": "Pisanie",
    "CHAT_LOADING": "Ładowanie",
    "CHAT_PENDING_INVITATION": "Zaproszenie oczekuje",
    "CHAT_PENDING_INVITATION_MIN": "{count} min zaproszenie oczekuje",
    "CHAT_PENDING_INVITATION_HR": "{count} godz. zaproszenie oczekuje",
    "CHAT_PENDING_INVITATION_DAY": "{count} dni zaproszenie oczekuje",
    "CHAT_WAITING_FOR_YOU": "{label} - Czeka na Ciebie",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Oczekuje akceptacji",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Odmówiono dostępu do mikrofonu.",
    "CHAT_UPLOAD_FAILED": "Przesyłanie nie powiodło się: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Przesyłanie wymaga połączenia internetowego. Spróbuj ponownie, gdy będziesz online.",
    "CHAT_ERROR_AUTH": "Błąd uwierzytelniania",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Brak nazwy pliku lub content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Brak conversation_id lub target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Brak conversation_id dla przesyłania innego niż avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Nieprawidłowy file_path avatara",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Klient usługi Supabase jest niedostępny",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Potwierdzenie odczytu avatara jest ważne tylko w kontekście czatu doradcy",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Nie znaleziono wiadomości przepływu avatara lub nie kwalifikuje się ona do potwierdzenia odczytu",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Nie udało się sfinalizować wiadomości avatara jako przeczytanej",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 załącznik",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} załączników",
    "CHAT_VOICE_NOTE": "Notatka głosowa",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Czat niedostępny. Ten użytkownik Cię zablokował.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Czat niedostępny. Zablokowałeś tego użytkownika.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Dostęp do konta jest zablokowany przez zasady.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Czat niedostępny. To konto jest ostatecznie zablokowane przez User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Czat niedostępny. Aktywna jest wzajemna blokada.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Czat niedostępny z powodu zasad blokowania.",
    "MESSAGE_PREVIEW_PHOTO": "Zdjęcie",
    "MESSAGE_PREVIEW_VOICE": "Wiadomość głosowa",
    "MESSAGE_PREVIEW_VIDEO": "Wideo",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Plik",
    "MESSAGE_PREVIEW_MESSAGE": "Wiadomość",
    "MESSAGE_PREVIEW_SYSTEM": "Wiadomość systemowa",
    "MESSAGE_PREVIEW_NEW": "Nowa wiadomość",
    "MESSAGE_UNKNOWN_FILE": "Nieznany plik",
    "MESSAGE_AUDIO_ATTACHMENT": "Załącznik audio",
    "MESSAGE_FILE_ATTACHMENT": "Załącznik",
    "BANNER_INVITED_BY": "zaproszony przez {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Wyniki wyszukiwania",
    "SEARCH_QUERY_LABEL": "Zapytanie:",
    "SEARCH_LOADING_VISIBILITY": "Ładowanie widoczności wyszukiwania...",
    "SEARCH_NO_RESULTS": "Nie znaleziono wyników w bieżącym zakresie wyszukiwania.",
    "SHARE_WITH_COLLABRA": "Udostępnij w Collabra",
    "SHARE_SEND_TO": "Wyślij do",
    "SHARE_SELECT_ONE_BANNER": "Wybierz jeden baner",
    "SHARE_BANNER_LIST_ARIA": "Lista banerów",
    "SHARE_NO_MATCHING_BANNER": "Brak pasującego banera",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Dodaj komentarz...",
    "SHARE_RECENT_CHATS": "Ostatnie czaty",
    "SHARE_LEFT_LIST": "Lewa lista",
    "SHARE_RIGHT_LIST": "Prawa lista",
    "SHARE_UNTITLED_BANNER": "Baner bez tytułu",
    "SHARE_SHARED_CONTENT": "Udostępniona treść",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Nie można otworzyć udostępnionej treści.",
    "SHARE_OPEN_BANNER_FAILED": "Nie można otworzyć wybranego banera.",
    "SHARE_ONE_PHOTO_SELECTED": "Wybrano 1 zdjęcie",
    "SHARE_MANY_PHOTOS_SELECTED": "Wybrano {count} zdjęć",
    "SHARE_ONE_FILE_SELECTED": "Wybrano 1 plik",
    "SHARE_MANY_FILES_SELECTED": "Wybrano {count} plików",
    "FORWARD_MESSAGE_TITLE": "Przekaż wiadomość",
    "FORWARD_SELECT_RECIPIENTS": "Wybierz odbiorców",
    "FORWARD_NO_OTHER_BANNER": "Brak dostępnego innego banera.",
    "FORWARD_SEND_TO_COUNT": "Wyślij do {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Wybierz co najmniej jeden baner.",
    "FORWARD_FAILED_DEFAULT": "Przekazywanie nie powiodło się. Spróbuj ponownie.",
    "FORWARD_PARTIAL_SENT": "Wysłano {count}. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Nie znaleziono wiadomości źródłowej do przekazania",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Ta wiadomość nie ma jeszcze treści możliwej do przekazania",
    "FORWARD_DESTINATION_MISSING": "Brakuje miejsca docelowego przekazania",
    "FORWARD_MESSAGE_PREVIEW": "Przekazana wiadomość",
    "MENU_PASTE": "Wklej",
    "MENU_COPY": "Kopiuj",
    "MENU_REPLY": "Odpowiedz",
    "MENU_FORWARD": "Przekaż",
    "MENU_REMOVE_INVITATION": "Usuń zaproszenie",
    "MENU_REMOVE_FROM_LIST": "Usuń z listy",
    "MENU_GOODBYE_GUEST": "",
    "MENU_ADD_TO_LIST": "Dodaj do listy",
    "MENU_REJECT_INVITATION": "Odrzuć zaproszenie",
    "MENU_FRONTEND_VERSION": "Wersja frontendu",
    "MENU_BANNER_HEADER": "Baner - {zone}",
    "MENU_BANNER_INFO": "Informacje o banerze: {title}",
    "MENU_MESSAGE_BUBBLE": "Dymek wiadomości",
    "MENU_CHAT_CANVAS_HEADER": "Obszar czatu - {zone}",
    "MENU_CANVAS_INFO": "Informacje o obszarze",
    "MENU_CHAT_CANVAS_SUBLABEL": "Obszar rozmowy / bieżąca powierzchnia czatu",
    "MENU_INPUT_AREA_HEADER": "Obszar wprowadzania - {zone}",
    "MENU_INPUT_AREA_INFO": "Informacje o obszarze wprowadzania: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Dolna powierzchnia pisania i narzędzi akcji",
    "MENU_HEADER": "Nagłówek - {zone}",
    "MENU_HEADER_INFO": "Informacje o nagłówku: {title}",
    "MENU_HEADER_DESCRIPTION": "Górna nawigacja i kontrolki strony",
    "MENU_ZONE_HEADER": "Strefa - {zone}",
    "MENU_ZONE_SPACE_INFO": "Informacje o przestrzeni strefy",
    "MENU_EMPTY_LIST_SURFACE": "Pusta powierzchnia/lista",
    "MENU_BLOCK": "Zablokuj",
    "MENU_UNBLOCK": "Odblokuj",
    "MENU_HIDE_IN_SEARCH": "Ukryj w wyszukiwaniu",
    "MENU_UNHIDE_IN_SEARCH": "Pokaż w wyszukiwaniu",
    "MENU_VISIBLE_IN_SEARCH": "Widoczne w wyszukiwaniu",
    "MENU_HIDDEN_IN_SEARCH": "Ukryte w wyszukiwaniu",
    "MENU_VISIBLE_IN_USER_LIST": "Widoczne na liście użytkowników",
    "MENU_HIDDEN_IN_USER_LIST": "Ukryte na liście użytkowników",
    "MENU_NOT_BLOCKED": "Nie zablokowano",
    "MENU_BLOCKED": "Zablokowano",
    "MENU_FRONTEND_VERSION_LOADING": "Ładowanie...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Ładowanie wartości dla banera z backendu. Żadna opcja nie jest oznaczona jako aktywna, dopóki nie nadejdzie odpowiedź bazy danych.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Nie udało się załadować wartości backendu. Nie pokazano żadnej zaufanej aktywnej opcji.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Jawna wartość dla banera w bazie danych to {overrideVersion}. Globalna wartość domyślna to {globalDefaultVersion}. Użytkownik docelowy musi całkowicie odświeżyć lub ponownie otworzyć aplikację, aby bootstrap startowy ją zastosował.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Nie zapisano jawnej wartości dla banera w bazie danych. FeV2.0.0 jest aktywna domyślnie. Globalna wartość domyślna to {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Jawna wartość dla banera w bazie danych staje się aktywna po pełnym przeładowaniu aplikacji docelowej",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Nie zapisano jawnej wartości dla banera; jest to domyślny indywidualny stan FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Ta opcja jest również równa bieżącej globalnej wartości domyślnej",
    "MENU_DELETE_PERMANENT_CONFIRM": "Trwale usunąć {target} z bazy danych? Spowoduje to usunięcie konta, historii czatu, zależności i wymusi pełną nową ścieżkę zaproszenia przy przyszłym powrocie.",
    "MENU_DELETE_PERMANENTLY": "Usuń trwale",
    "MENU_REFRESH_PAGE": "Odśwież stronę",
    "MENU_LOG_OFF": "Wyloguj",
    "MENU_HARD_RELOAD": "Twarde przeładowanie",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Email (użytkownik admin)",
    "AUTH_PASSWORD_PLACEHOLDER": "Hasło",
    "AUTH_CONNECTING": "Łączenie...",
    "AUTH_SIGNING_OUT": "Wylogowywanie...",
    "AUTH_BACK_TO_LOGIN": "Powrót do logowania",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Nieprawidłowa odpowiedź serwera: nie znaleziono tokena.",
    "AUTH_LOGIN_FAILED": "Logowanie nie powiodło się",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Hasła nie są zgodne.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Hasła nie są zgodne!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Hasła muszą być dokładnie takie same.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nowe hasło",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Potwierdź hasło",
    "AUTH_CHANGE_PASSWORD": "Zmień hasło",
    "AUTH_SAVING_PASSWORD": "Zapisywanie...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Hasło zostało pomyślnie zaktualizowane.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Nie można teraz zmienić hasła.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Musisz być zalogowany, aby zmienić hasło.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Przełącz widoczność nowego hasła",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Przełącz widoczność potwierdzenia hasła",
    "REGISTER_TITLE": "Dokończ rejestrację",
    "REGISTER_SUBTITLE": "Ustaw hasło ręcznie.",
    "REGISTER_CREATING_ACCOUNT": "Tworzenie konta...",
    "REGISTER_FINISH_SETUP": "Zakończ konfigurację",
    "REGISTER_FAILED_SET_PASSWORD": "Nie udało się ustawić hasła",
    "INVITE_EMAIL_INSTRUCTION": "Wpisz email osoby zapraszanej (format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Zaproś",
    "INVITE_EMAIL_REQUIRED": "Wpisz email osoby zapraszanej.",
    "INVITE_EMAIL_INVALID": "Nieprawidłowy format emaila. Użyj: user@example.com",
    "PENDING_INVITATION_TITLE": "Oczekujące zaproszenie",
    "PENDING_INVITATION_REMOVE_QUESTION": "Usunąć to oczekujące zaproszenie z bazy danych?",
    "PENDING_INVITATION_KEEP": "Zachowaj zaproszenie",
    "PENDING_INVITATION_REMOVAL_FAILED": "Usunięcie nie powiodło się.",
    "REMOVE_FROM_LIST_TITLE": "Usuń z listy",
    "REMOVE_FROM_LIST_WARNING": "Usunąć teraz tego użytkownika z obu list? Dostęp do czatu zostanie natychmiast odcięty. Jedyną ścieżką powrotu jest nowe zaproszenie.",
    "REMOVE_FROM_LIST_KEEP": "Zachowaj użytkownika na liście",
    "REMOVE_FROM_LIST_FAILED": "Usunięcie z listy nie powiodło się.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Ustawienia i status na żywo",
    "PERMISSION_DIALOG_ARIA": "Ustawienia i status na żywo",
    "PERMISSION_TRIGGER_ARIA": "Wyzwalacz okna ustawień",
    "PERMISSION_CLOSE_ARIA": "Zamknij okno uprawnień",
    "PERMISSION_LIVE_STATUS": "Status na żywo",
    "PERMISSION_SYSTEM_PERMISSION": "Uprawnienie systemowe",
    "PERMISSION_APP_PUSH": "Push aplikacji",
    "PERMISSION_LOCATION_PERMISSION": "Uprawnienie lokalizacji",
    "PERMISSION_APP_LOCATION": "Lokalizacja aplikacji",
    "PERMISSION_CONTROLS": "Kontrolki uprawnień",
    "PERMISSION_PUSH_NOTIFICATIONS": "Powiadomienia push",
    "PERMISSION_LOCATION_ACCESS": "Dostęp do lokalizacji",
    "PERMISSION_IN_APP_SETTINGS": "Ustawienia w aplikacji",
    "PERMISSION_ALERT_SOUND": "Dźwięk alertu",
    "PERMISSION_APP_BADGE": "Plakietka aplikacji",
    "PERMISSION_PASSWORD_SETTINGS": "Ustawienia hasła",
    "PERMISSION_NAVIGATION_STATUS": "Status nawigacji",
    "PERMISSION_SELECTED_ZONE": "Wybrana strefa",
    "PERMISSION_STAGED_CHAT_BANNER": "Przygotowany baner czatu",
    "PERMISSION_CANVAS_CONTENT": "Zawartość obszaru",
    "PERMISSION_YOUR_DEVICES": "Twoje urządzenia ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Odśwież listę urządzeń",
    "PERMISSION_REFRESH_LIST": "Odśwież listę",
    "PERMISSION_NO_REGISTERED_DEVICES": "Nie znaleziono zarejestrowanych urządzeń.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Zmień rozmiar okna ustawień",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Przełącz powiadomienia push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Przełącz dostęp do lokalizacji",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Przełącz dźwięk alertu",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Przełącz plakietkę aplikacji",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Przełącz widoczność profilu",
    "PERMISSION_OFF_IN_V1": "Wyłączone w v1",
    "PERMISSION_CHAT": "Czat",
    "PERMISSION_BANNER_LIST": "Lista banerów",
    "PERMISSION_PUSH_DISABLED_V1": "Powiadomienia push są wyłączone dla wydania v1 w Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Powiadomienia push są WŁĄCZONE dla tego urządzenia.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Powiadomienia systemowe są zablokowane. Stuknij, aby otworzyć pomoc ustawień.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Włącz, aby poprawić niezawodność dostarczania.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Aby wyłączyć powiadomienia systemowe, otwórz ustawienia powiadomień przeglądarki/witryny i ustaw tę witrynę jako zablokowaną.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Aby zmienić uprawnienie powiadomień systemowych, otwórz ustawienia powiadomień przeglądarki/witryny i zezwól tej witrynie.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Dostęp do lokalizacji jest WŁĄCZONY dla sortowania LCAC według odległości i pozycjonowania na mapie.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API lokalizacji nie jest obsługiwane w tym środowisku.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Dostęp do lokalizacji jest zablokowany. Stuknij, aby otworzyć pomoc ustawień.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Włącz, aby zezwolić na dokładne sortowanie LCAC według odległości i pozycjonowanie na mapie w aplikacji.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Dostęp do lokalizacji nie jest obsługiwany w tym środowisku.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Aby wyłączyć dostęp do lokalizacji, otwórz ustawienia lokalizacji przeglądarki/witryny i ustaw tę witrynę jako zablokowaną.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Aby włączyć dostęp do lokalizacji dla sortowania według odległości i pozycjonowania na mapie w aplikacji, otwórz ustawienia lokalizacji przeglądarki/witryny i zezwól tej witrynie.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Nie można teraz załadować zarejestrowanych urządzeń.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Ładowanie mostu UI...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Ładowanie mostu lokalnego...",
    "RUNTIME_LOADING_BACKEND": "Ładowanie backendu...",
    "RUNTIME_LOADING": "Ładowanie...",
    "RUNTIME_LOADING_FROM_DATABASE": "Ładowanie z bazy danych...",
    "RUNTIME_BACKEND_CONNECTED": "Backend połączony",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Aktywny fallback z pamięci podręcznej",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Aktywny domyślny fallback",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Aktywne domyślne wartości fallback",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Zapisywanie przez backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Zapisano w usłudze backendu",
    "RUNTIME_SAVE_FAILED": "Zapis nie powiódł się",
    "RUNTIME_LOAD_FAILED": "Ładowanie nie powiodło się",
    "RUNTIME_CONNECTED": "Połączono",
    "RUNTIME_LOGIN_REQUIRED": "Wymagane logowanie",
    "RUNTIME_SAVED": "Zapisano",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI gotowe - runtime oczekuje",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Chroniona usługa selektora backendu odrzuciła lub nie mogła zapisać żądanej opcji modelu.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Chroniona usługa selektora backendu odrzuciła lub nie mogła zapisać żądanej zmiany routingu WF1.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selektor odczytuje teraz aktywną konfigurację, routing Qwen i dozwolone opcje z chronionej usługi backendu.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Usługa selektora backendu jest teraz niedostępna, więc używany jest ostatni zapisany w pamięci podręcznej stan selektora.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Domyślne wartości selektora są aktywne, ponieważ nie można było załadować stanu z backendu ani z pamięci podręcznej.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Chroniona usługa selektora backendu zaktualizowała aktywną konfigurację routingu WF1 i odświeżyła pamięć podręczną domeny runtime.",
    "FRONTEND_VERSION_TITLE": "Wersja frontendu",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Ten selektor kontroluje aktywną wersję frontendu dla wszystkich użytkowników. FeV2.0.0 jest aktywna.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Ten selektor odczytuje aktywną wersję frontendu z config_domain_registry. Runtime rozwiązuje się do FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Nie udało się załadować konfiguracji backendu wersji frontendu, więc zakodowana domyślna FeV2.0.0 pozostaje aktywna, dopóki bootstrap startowy nie będzie mógł ponownie odczytać chronionej usługi.",
    "FRONTEND_VERSION_HELPER_SAVED": "Aktywna wersja frontendu została zapisana w config_domain_registry. Pełne odświeżenie lub następne ładowanie aplikacji zastosuje wartość runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Usługa backendu kontroli wersji frontendu nie mogła zapisać żądanej wersji globalnej.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktywna wersja frontendu.",
    "CHAT_DELETE_WINDOW_TITLE": "Okno usuwania czatu",
    "CHAT_DELETE_HELPER": "Ta wartość kontroluje okno dostępności opcji Usuń dla wszystkich w sekundach. Ochrona backendu zmienia się natychmiast po zapisie. Widoczność dymka zmienia się po pełnym odświeżeniu lub następnym ładowaniu aplikacji.",
    "CHAT_DELETE_HELPER_FALLBACK": "Nie udało się załadować usługi backendu kontroli usuwania czatu, więc zakodowana wartość domyślna pozostaje aktywna, dopóki bootstrap startowy nie będzie mógł ponownie odczytać chronionej usługi.",
    "CHAT_DELETE_HELPER_SAVED": "Okno dostępności opcji Usuń dla wszystkich zostało zapisane w config_domain_registry. Ochrona backendu zmienia się natychmiast. Widoczność dymka zmienia się po pełnym odświeżeniu lub następnym ładowaniu aplikacji.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Usługa backendu kontroli usuwania czatu nie mogła zapisać żądanej wartości okna.",
    "CHAT_DELETE_WINDOW_LABEL": "Okno Usuń dla wszystkich",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} s",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Zapisz wartość w pełnych sekundach. Obecna wartość produkcyjna to 86400 sekund = 1 dzień.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Sekundy okna",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Wpisz liczbę całkowitą większą lub równą 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Zapisz okno usuwania",
    "GUEST_BANNER_CONTROL_TITLE": "",
    "GUEST_BANNER_CONTROL_LABEL": "",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "",
    "GUEST_BANNER_CONTROL_HELPER": "",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "",
    "GUEST_BANNER_PENDING_TTL_INVALID": "",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "",
    "GUEST_QR_LOADING": "",
    "GUEST_QR_READY": "",
    "GUEST_QR_ALT": "",
    "GUEST_QR_LOAD_FAILED": "",
    "GUEST_SESSION_ACTIVE": "",
    "GUEST_PUBLIC_TITLE": "",
    "GUEST_PUBLIC_CONNECTING": "",
    "GUEST_PUBLIC_CONNECTED": "",
    "GUEST_PUBLIC_UNAVAILABLE": "",
    "GUEST_PUBLIC_SEND_FAILED": "",
    "UI_TEXTS_RUNTIME_TITLE": "",
    "UI_TEXTS_RUNTIME_BACKEND": "",
    "UI_TEXTS_RUNTIME_CACHED": "",
    "UI_TEXTS_RUNTIME_DEFAULTS": "",
    "UI_TEXTS_RUNTIME_SAVED": "",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "",
    "PROFILE_VISIBILITY_TITLE": "Widoczność profilu",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Musisz być zalogowany, aby zarządzać widocznością konta.",
    "PROFILE_VISIBILITY_HELPER": "Ten przełącznik aktualizuje tylko stan widoczności Twojego konta. Wykrywalność i zachowanie listy banerów pozostają bez zmian w tej fazie.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Nie można teraz załadować widoczności profilu.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Nie można teraz zaktualizować widoczności profilu.",
    "PROFILE_VISIBILITY_SAVED": "Widoczność Twojego konta to teraz {visibility}. Flagi wykrywalności pozostają bez zmian w tej fazie.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Konto publiczne",
    "PROFILE_VISIBILITY_STORED": "Zapisana widoczność",
    "WF1_MODEL_CONTROL_TITLE": "Kontrola modelu WF1",
    "WF1_ENABLE_TRANSLATION": "Włącz tłumaczenie / pivot",
    "WF1_TRANSLATION_ACTIVE": "Tłumaczenie AI jest aktywne.",
    "WF1_TRANSLATION_INACTIVE": "WF1 nadal działa, ale tekst źródłowy jest kopiowany, a pivot oznaczony jako nieaktywny.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktywny slot runtime",
    "WF1_ALLOW_SAME_LANGUAGE": "Zezwalaj na AI dla par tego samego języka",
    "WF1_SAME_LANGUAGE_ACTIVE": "Pary tego samego języka korzystają z normalnego routingu WF1.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Pary tego samego języka omijają AI i zapisują brak aktywnego języka pivot.",
    "WF1_QWEN_ROUTING": "Routing par Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Języki zaznaczone poniżej używają Qwen-Max, gdy para jest tym samym zaznaczonym językiem, zaznaczonym językiem z angielskim albo dwoma zaznaczonymi językami nieangielskimi. W przeciwnym razie aktywny pozostaje wybrany model główny.",
    "WF1_OPENROUTER_TEST_SLOT": "Slot testowy OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Slot testowy OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Tylko test jakości",
    "WF1_OPENROUTER_HELPER": "Ten slot można edytować tylko na potrzeby tymczasowych testów jakości OpenRouter. Nie zmienia operacyjnej ścieżki routingu par Qwen, chyba że sam ten slot stanie się aktywnym modelem.",
    "WF1_LABEL": "Etykieta",
    "WF1_PRODUCT": "Produkt",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Dostawca: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Sekret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Slot testowy OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max przez OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Cena katalogowa Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Cena katalogowa OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Cena katalogowa OpenRouter",
    "LANGUAGE_ENGLISH": "Angielski",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Chiński (uproszczony)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Chiński (tradycyjny)",
    "LANGUAGE_JAPANESE": "Japoński",
    "LANGUAGE_KOREAN": "Koreański",
    "LANGUAGE_PERSIAN": "Perski",
    "LANGUAGE_TURKISH_ISTANBUL": "Turecki (Stambuł)",
    "LANGUAGE_ARABIC": "Arabski",
    "LANGUAGE_FRENCH": "Francuski",
    "LANGUAGE_GERMAN": "Niemiecki",
    "LANGUAGE_SPANISH": "Hiszpański",
    "LANGUAGE_PORTUGUESE": "Portugalski",
    "LANGUAGE_ITALIAN": "Włoski",
    "LANGUAGE_RUSSIAN": "Rosyjski",
    "LANGUAGE_DUTCH": "Niderlandzki",
    "LANGUAGE_VIETNAMESE": "Wietnamski",
    "LANGUAGE_INDONESIAN": "Indonezyjski",
    "LANGUAGE_THAI": "Tajski",
    "LANGUAGE_MALAY": "Malajski",
    "WF1_PRICING_CUSTOM": "Cennik: niestandardowy model slotu - sprawdź aktualne ceny OpenRouter",
    "WF1_SAVE_OPENROUTER_SLOT": "Zapisz slot OpenRouter",
    "WF1_PRICING_LINE": "Wejście {input} - Wyjście {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Sekret: {secret}",
    "ZONE_VISIBILITY_TITLE": "Kontrola widoczności stref",
    "ZONE_ENABLE": "Włącz {zone}",
    "ZONE_ENABLED_NOTE": "{zone} może pojawić się dla dozwolonych ról po następnym ładowaniu aplikacji.",
    "ZONE_DISABLED_NOTE": "{zone} jest traktowana jako nieobecna dla użytkowników spoza S_Admin po następnym ładowaniu aplikacji.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin omija tę listę ról i zawsze zachowuje dostęp.",
    "ZONE_ROLE_LOCKED": "Wybory ról są tymczasowo zablokowane, gdy ta strefa jest wyłączona, i wrócą dokładnie tak, jak zapisano, gdy strefa zostanie ponownie włączona.",
    "ZONE_LCAC_CONTROL": "Kontrola LCAC",
    "ZONE_RCAC_CONTROL": "Kontrola RCAC",
    "ZONE_LCAC_DESCRIPTION": "Kontroluje istnienie lewej zarezerwowanej strefy oraz role, które mogą ją widzieć.",
    "ZONE_RCAC_DESCRIPTION": "Kontroluje istnienie prawej zarezerwowanej strefy oraz role, które mogą ją widzieć.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap widoczności stref odczytuje teraz dane z chronionej usługi backendu. Zmiany zastosują się przy następnym ładowaniu aplikacji.",
    "ZONE_VISIBILITY_CACHED": "Usługa backendu widoczności stref jest teraz niedostępna, więc aktywne są wartości z pamięci podręcznej lub lokalne wartości domyślne.",
    "ZONE_VISIBILITY_DEFAULTS": "Domyślne wartości widoczności stref są aktywne, ponieważ nie można było załadować stanu z backendu ani z pamięci podręcznej.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap widoczności stref został zapisany. Do zastosowania w runtime wymagane jest twarde przeładowanie lub następne ładowanie aplikacji.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Chroniona usługa backendu nie mogła zapisać żądanej zmiany widoczności strefy.",
    "ROLE_MEMBER": "Członek",
    "ROLE_STAFF": "Personel",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Włącz powiadomienia, aby otrzymywać nowe wiadomości.",
    "MAIN_LOG_OUT": "Wyloguj",
    "NOTIFICATION_NEW_MESSAGE": "Nowa wiadomość",
    "NOTIFICATION_UNREAD_MESSAGE": "Masz nieprzeczytaną wiadomość.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Pełny widok",
    "MEDIA_AUDIO_ATTACHMENT": "Załącznik audio",
    "MEDIA_FILE_FALLBACK": "Plik",
    "MEDIA_DOWNLOAD_READY": "Załącznik gotowy do pobrania",
    "MEDIA_TYPE_UNSUPPORTED": "Typ nieobsługiwany w pełnym widoku",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Poprzedni obraz",
    "MEDIA_NEXT_IMAGE_ARIA": "Następny obraz",
    "MEDIA_OPEN_ORIGINAL": "Otwórz oryginał",
    "MEDIA_DOWNLOAD": "Pobierz",
    "MEDIA_CLOSE_ARIA": "Zamknij",
    "MEDIA_PROFILE_PICTURE_ARIA": "Zdjęcie profilowe {name}",
    "MEDIA_PROFILE_ALT": "Profil {name}",
    "MEDIA_UPLOAD_FAILED": "Przesyłanie nie powiodło się",
    "MEDIA_BACKEND_TOKEN_ERROR": "Błąd tokena backendu",
    "MEDIA_UPLOAD_URL_MISSING": "Krytyczne: w odpowiedzi backendu brakuje adresu URL przesyłania.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Brak tokena uwierzytelniania do przesyłania czatu",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Żądanie tokena przesyłania czatu nie powiodło się",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Nieprawidłowa odpowiedź przesyłania czatu",
    "MEDIA_GCS_UPLOAD_FAILED": "Przesyłanie GCS nie powiodło się",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Brak nazwy pliku lub contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Brak file_path",
    "BLOCK_NOTICE_TITLE": "Powiadomienie o trwałej blokadzie",
    "BLOCK_NOTICE_MESSAGE": "Twoje konto zostało tymczasowo zawieszone z powodu naruszenia zasad.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Jeśli uważasz, że wymaga to dalszych działań, skontaktuj się z",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "przez email.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Nieznany użytkownik",
    "GENERAL_GUEST": "Gość",
    "ADVISOR_FOR_CLIENT": "Doradca dla {client_display_name}",
    "GUEST_FOR_CLIENT": "",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token i hasło są wymagane",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Treść żądania musi być w formacie JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Nieprawidłowy lub wygasły token zaproszenia",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Ustawienie hasła nie powiodło się: brak sesji lub użytkownika",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Ustawienie hasła nie powiodło się podczas logowania",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Generowanie tokena admina nie powiodło się",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Logowanie nie powiodło się: brak sesji lub użytkownika",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Rejestracja zakończona pomyślnie. Sprawdź email w celu weryfikacji.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Nieznany błąd rejestracji",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Nieprawidłowe przetwarzanie tokena",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Token dostępu jest wymagany",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Podgląd hasha tokena wymaga wskazówki email z adresu URL przekierowania",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Nie można rozwiązać tożsamości dla tego tokena",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Tylko User Zero może uzyskać dostęp do usługi selektora LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Tylko User Zero może uzyskać dostęp do usługi kontroli widoczności stref.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Tylko User Zero może uzyskać dostęp do usługi kontroli wersji frontendu.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Tylko User Zero może sprawdzać wersję frontendu innego użytkownika.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Tylko User Zero może uzyskać dostęp do usługi kontroli usuwania czatu.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Tylko User Zero może trwale usunąć konto użytkownika.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Nieprawidłowy payload żądania.",
    "API_ERROR_INTERNAL_SERVER": "Wewnętrzny błąd serwera",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Brak funkcji w backendzie (wymagane przeładowanie)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Tylko DB RPC jest dozwolone dla przejść delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Poczekaj przed wysłaniem kolejnej wiadomości.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Wiadomość wysłana pomyślnie.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Usługa kontaktu jest niedostępna.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Wysyłanie wiadomości nie powiodło się.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Imię jest wymagane.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Email jest nieprawidłowy.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Wiadomość jest wymagana.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload selektora jest wymagany.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload widoczności stref jest wymagany.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload wersji frontendu jest wymagany.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload kontroli usuwania czatu jest wymagany.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID uwierzytelnionego użytkownika jest wymagane.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID uwierzytelnionego użytkownika przeglądającego jest wymagane.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID uwierzytelnionego użytkownika wykonującego akcję jest wymagane.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id jest wymagane.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id jest wymagane.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Lista owner_user_ids jest wymagana.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email jest wymagane.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by jest wymagane.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime wyszukiwania jest wyłączony przez globalną wersję frontendu.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Nie masz uprawnień do anulowania tego oczekującego zaproszenia.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Tego zaproszenia nie można już anulować, ponieważ użytkownik jest już zarejestrowany.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Nie znaleziono oczekującego zaproszenia.",
    "INVITE_REPLY_ALREADY_MEMBER": "Gratulacje, Twój znajomy ({invitee_email}) jest już zarejestrowany w tej aplikacji i jest członkiem tego obszaru roboczego.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Zaproszenie dla {invitee_email} oczekuje, ale nie udało się wyzwolić ponownego emaila. Sprawdź logi poczty.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Rekord zaproszenia został utworzony dla {invitee_email}, ale nie można było potwierdzić dostarczenia emaila. Spróbuj ponownie później lub sprawdź logi poczty.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Nie udało się utworzyć rekordu zaproszenia. Spróbuj ponownie później.",
    "INVITE_REPLY_SYSTEM_ERROR": "Błąd systemu podczas procesu zapraszania: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Błąd konfiguracji backendu: brak poświadczeń Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Błąd konfiguracji backendu: nieprawidłowy URL Supabase",
    "CHAT_ERROR_ACCESS_DENIED": "Odmowa dostępu",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Treść nie może być pusta dla wiadomości tekstowych",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Nie można określić ID rozmowy",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Brakuje kontekstu uwierzytelniania RPC",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC zwróciło nieprawidłowy payload wiadomości",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Wstawianie nie powiodło się, nie zwrócono danych",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations musi być listą",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Nieprawidłowy payload operacji",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Nieobsługiwany operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id jest wymagane",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Nie znaleziono wiadomości",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Usuwanie jest dozwolone tylko dla własnej wiadomości",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Opcja Usuń dla wszystkich nie jest już dostępna dla tej wiadomości",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Usuń dla wszystkich nie powiodło się",
    "API_ERROR_SERVER_CONFIGURATION": "Błąd konfiguracji serwera",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Brak nagłówka sekretu webhooka",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Nieautoryzowane źródło webhooka",
    "API_ERROR_BACKEND_CONFIGURATION": "Błąd konfiguracji backendu",
    "API_ERROR_MODULE_ATTRIBUTE": "Błąd atrybutu modułu: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Niepowodzenie przed usunięciem zaproszenia podczas usuwania oczekującego użytkownika auth.",
    "CHAT_ERROR_DB": "Błąd DB: {error}",
}
