# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/pt.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Principal",
    "APP_TITLE": "Plataforma de IA OTMEGA",
    "APP_SUBTITLE": "Consultor de IA",
    "CHAT_PLACEHOLDER": "Digite sua mensagem...",
    "CHAT_SEND_BUTTON": "Enviar",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 O consultor pode cometer erros, então verifique as informações.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Nova conversa",
    "ICON_HISTORY": "Histórico",
    "ICON_TEMPLATES": "Modelos",
    "ICON_SETTINGS": "Configurações",
    "ICON_USER_PROFILE": "Perfil do usuário",
    "ICON_QUICK_ACTIONS": "Ações rápidas",
    "ICON_PINNED": "Fixado",
    "ICON_GALLERY": "Galeria",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Instalar app",
    "PWA_ANDROID_MSG": "Instale este app no seu dispositivo para uma melhor experiência e acesso offline.",
    "PWA_IOS_MSG": "Para instalar este app no seu iPhone/iPad:\n1. Toque no botão Compartilhar abaixo\n2. Selecione 'Adicionar à Tela de Início'",
    "PWA_BTN_INSTALL": "Instalar",
    "PWA_BTN_LATER": "Talvez mais tarde",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Entrar na Rede de Consultores",
    "AUTH_HEADER_SIGNUP": "Crie sua conta unificada",
    "AUTH_HEADER_LOGIN_NETWORK": "Entrar na Rede de Consultores",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Crie sua conta unificada",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Entrar",
    "AUTH_BUTTON_SIGNUP": "Criar conta",
    "AUTH_BUTTON_GOOGLE": "Continuar com Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Esqueci a senha",
    "AUTH_BUTTON_SEND_RESET_LINK": "Enviar link de redefinição",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Não tem uma conta? Cadastre-se",
    "AUTH_PROMPT_LOGIN": "Já tem uma conta? Entrar",
    "AUTH_HELPER_TEXT_SIGNUP": "Você está criando uma conta unificada que pode usar para acessar todos os consultores nesta plataforma.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Você está criando uma conta unificada que pode usar para acessar todos os consultores nesta plataforma.",
    "AUTH_HELPER_TEXT_LOGIN": "Use a mesma conta (e-mail/senha ou Google) que você usou para outros consultores nesta rede.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Use a mesma conta (e-mail/senha ou Google) que você usou para outros consultores nesta rede.",
    "AUTH_FORGOT_PASSWORD_LINK": "Esqueceu sua senha?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Redefinir sua senha",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Digite seu endereço de e-mail e enviaremos um link para redefinir sua senha.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-mail",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Entrando...",
    "AUTH_STATUS_LOADING_SIGNUP": "Criando sua conta...",
    "AUTH_STATUS_LOADING_RESET": "Enviando link de redefinição...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Login realizado com sucesso! Recarregando...",
    "AUTH_STATUS_SUCCESS_RESET": "Link de redefinição enviado com sucesso. Verifique seu e-mail.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Link de redefinição de senha enviado com sucesso. Verifique seu e-mail.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "E-mail ou senha inválidos.",
    "AUTH_ERROR_EMAIL_EXISTS": "Já existe uma conta com este e-mail na rede de consultores.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Já existe uma conta com este e-mail. Faça login. Você atualmente é membro de:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Já existe uma conta com este e-mail na rede de consultores. Feche esta janela e use a seção 'Login' com o mesmo e-mail e sua senha anterior.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Você atualmente é membro de:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-mail e senha são obrigatórios.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Conta criada, mas não foi possível configurar a associação. Entre em contato com o suporte.",
    "AUTH_ERROR_DEFAULT": "Ocorreu um erro. Tente novamente.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "A carga útil de controle do banner de convidado é necessária.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Apenas o Usuário Zero pode atualizar os controles do banner de convidado.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Falha ao enviar o link de redefinição. Tente novamente.",
    "INVITE_REPLY_EMAIL_SENT": "O e-mail de convite do Collabra foi enviado para seu amigo em {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "O e-mail de convite do Collabra foi reenviado para seu amigo em {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Mostrar senha",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Ocultar senha",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Cancelar",
    "GENERAL_CLOSE": "Fechar",
    "GENERAL_SEND": "Enviar",
    "GENERAL_SEARCH": "Pesquisar",
    "GENERAL_RESET": "Redefinir",
    "GENERAL_ENABLE": "Ativar",
    "GENERAL_LOADING": "Carregando...",
    "GENERAL_DELETE": "Excluir",
    "GENERAL_DELETING": "Excluindo...",
    "GENERAL_SAVE_PASSWORD": "Salvar senha",
    "AUTH_REMEMBER_EMAIL_LABEL": "Lembrar e-mail",
    "GENERAL_SAVING": "Salvando...",
    "GENERAL_SENDING": "Enviando...",
    "GENERAL_REMOVING": "Removendo...",
    "GENERAL_CONFIRM_REMOVAL": "Confirmar remoção",
    "GENERAL_EMPTY": "Vazio",
    "GENERAL_UNAVAILABLE": "Indisponível",
    "GENERAL_ENABLED": "Ativado",
    "GENERAL_DISABLED": "Desativado",
    "GENERAL_GRANTED": "Concedido",
    "GENERAL_DENIED": "Negado",
    "GENERAL_DEFAULT": "Padrão",
    "GENERAL_UNSUPPORTED": "Não suportado",
    "GENERAL_PUBLIC": "Público",
    "GENERAL_PRIVATE": "Privado",
    "GENERAL_USERNAME": "Nome de usuário",
    "GENERAL_EMAIL": "E-mail",
    "GENERAL_YOU": "Você",
    "GENERAL_USER": "Usuário",
    "GENERAL_UNKNOWN": "Desconhecido",
    "GENERAL_VISITOR": "Visitante",
    "GENERAL_PROFILE": "Perfil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Banner desconhecido",
    "GENERAL_ADVISOR_BANNER": "Banner do consultor",
    "GENERAL_NOT_AVAILABLE": "N/D",
    "GENERAL_NOT_SELECTED": "Não selecionado",
    "GENERAL_NO_EMAIL_FOUND": "Nenhum e-mail encontrado",
    "GENERAL_USER_ZERO_ONLY": "Somente Usuário Zero",
    "GENERAL_CONNECTION_STATE": "Estado da conexão",
    "GENERAL_DISPLAY_ONLY": "Somente exibição",
    "GENERAL_TEXTAREA": "Área de texto",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Ações rápidas (RCAC)",
    "HEADER_CHANGE_STATUS": "Alterar status",
    "HEADER_OT_COIN_BALANCE": "Saldo de OT Coin",
    "HEADER_ALT_USER": "Usuário",
    "STATUS_BUSY": "Ocupado",
    "STATUS_AWAY": "Ausente",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Invisível",
    "NETWORK_CHECKING_CONNECTION": "Verificando conexão...",
    "NETWORK_ONLINE_LATENCY": "Online (latência: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Rede: boa (toque para testar)",
    "CHAT_TARGET_ALT": "Destino do chat",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Pesquisar...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Abrir foto de perfil de {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Campo de mensagem",
    "CHAT_TOGGLE_VIEW_ARIA": "Alternar visualização",
    "CHAT_ADD_USER_ARIA": "Adicionar usuário",
    "CHAT_ATTACH_ARIA": "Anexar",
    "CHAT_MIC_ARIA": "Microfone",
    "CHAT_SEND_ARIA": "Enviar",
    "CHAT_SEARCH_ARIA": "Pesquisar",
    "CHAT_OPEN_SEARCH_ARIA": "Abrir pesquisa",
    "CHAT_CLOSE_SEARCH_ARIA": "Fechar pesquisa",
    "CHAT_ATTACHMENT_ALT": "Anexo",
    "CHAT_PREVIEW_ALT": "Pré-visualização",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Remover anexo",
    "CHAT_REPLYING_TO": "Respondendo a",
    "CHAT_CANCEL_REPLY_ARIA": "Cancelar resposta",
    "CHAT_UPLOADING": "Enviando arquivo...",
    "CHAT_LOADING_CHATS": "Carregando conversas...",
    "CHAT_SEND_FAILED": "Falha no envio",
    "CHAT_SEND_FAILED_RETRY": "Falha ao enviar. Tente novamente.",
    "CHAT_RETRY": "Tentar novamente",
    "CHAT_EDITED": "editado",
    "CHAT_TYPING": "Digitando",
    "CHAT_LOADING": "Carregando",
    "CHAT_PENDING_INVITATION": "Convite pendente",
    "CHAT_PENDING_INVITATION_MIN": "{count} min Convite pendente",
    "CHAT_PENDING_INVITATION_HR": "{count} h Convite pendente",
    "CHAT_PENDING_INVITATION_DAY": "{count} dia Convite pendente",
    "CHAT_WAITING_FOR_YOU": "{label} - Aguardando você",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Aceitação pendente",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Acesso ao microfone negado.",
    "CHAT_UPLOAD_FAILED": "Falha no upload: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "O upload exige conexão com a internet. Tente novamente quando estiver online.",
    "OFFLINE_SHOWING_SAVED_DATA": "",
    "OFFLINE_DATA_MAY_BE_OUTDATED": "",
    "OFFLINE_ACTION_REQUIRES_CONNECTION": "",
    "OFFLINE_MESSAGE_WAITING_CONNECTION": "",
    "OFFLINE_PENDING_MESSAGES_TOOLTIP": "",
    "APP_BACK_EXIT_HINT": "",
    "CHAT_ERROR_AUTH": "Erro de autenticação",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nome do arquivo ou content_type ausente",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id ou target_id ausente",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id ausente para upload que não é avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path do avatar inválido",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Cliente de serviço Supabase indisponível",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "A confirmação de leitura do avatar só é válida no contexto do chat do consultor",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Mensagem de fluxo de avatar não encontrada ou não elegível para confirmação de leitura",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Falha ao finalizar a mensagem de avatar como lida",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 anexo",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} anexos",
    "CHAT_VOICE_NOTE": "Nota de voz",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat indisponível. Este usuário bloqueou você.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat indisponível. Você bloqueou este usuário.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "O acesso à conta está bloqueado por política.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat indisponível. Esta conta está bloqueada definitivamente pelo Usuário Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat indisponível. O bloqueio mútuo está ativo.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat indisponível devido à política de bloqueio.",
    "MESSAGE_PREVIEW_PHOTO": "Foto",
    "MESSAGE_PREVIEW_VOICE": "Mensagem de voz",
    "MESSAGE_PREVIEW_VIDEO": "Vídeo",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Arquivo",
    "MESSAGE_PREVIEW_MESSAGE": "Mensagem",
    "MESSAGE_PREVIEW_SYSTEM": "Mensagem do sistema",
    "MESSAGE_PREVIEW_NEW": "Nova mensagem",
    "MESSAGE_UNKNOWN_FILE": "Arquivo desconhecido",
    "MESSAGE_AUDIO_ATTACHMENT": "Anexo de áudio",
    "MESSAGE_FILE_ATTACHMENT": "Anexo",
    "BANNER_INVITED_BY": "convidado por {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Resultados da pesquisa",
    "SEARCH_QUERY_LABEL": "Consulta:",
    "SEARCH_LOADING_VISIBILITY": "Carregando visibilidade da pesquisa...",
    "SEARCH_NO_RESULTS": "Nenhum resultado encontrado no escopo de pesquisa atual.",
    "SHARE_WITH_COLLABRA": "Compartilhar com Collabra",
    "SHARE_SEND_TO": "Enviar para",
    "SHARE_SELECT_ONE_BANNER": "Selecione um banner",
    "SHARE_BANNER_LIST_ARIA": "Lista de banners",
    "SHARE_NO_MATCHING_BANNER": "Nenhum banner correspondente",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Adicionar um comentário...",
    "SHARE_RECENT_CHATS": "Conversas recentes",
    "SHARE_LEFT_LIST": "Lista esquerda",
    "SHARE_RIGHT_LIST": "Lista direita",
    "SHARE_UNTITLED_BANNER": "Banner sem título",
    "SHARE_SHARED_CONTENT": "Conteúdo compartilhado",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Não foi possível abrir o conteúdo compartilhado.",
    "SHARE_OPEN_BANNER_FAILED": "Não foi possível abrir o banner selecionado.",
    "SHARE_ONE_PHOTO_SELECTED": "1 foto selecionada",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} fotos selecionadas",
    "SHARE_ONE_FILE_SELECTED": "1 arquivo selecionado",
    "SHARE_MANY_FILES_SELECTED": "{count} arquivos selecionados",
    "FORWARD_MESSAGE_TITLE": "Encaminhar mensagem",
    "FORWARD_SELECT_RECIPIENTS": "Selecionar destinatários",
    "FORWARD_NO_OTHER_BANNER": "Nenhum outro banner disponível.",
    "FORWARD_SEND_TO_COUNT": "Enviar para {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Selecione pelo menos um banner.",
    "FORWARD_FAILED_DEFAULT": "Falha ao encaminhar. Tente novamente.",
    "FORWARD_PARTIAL_SENT": "{count} enviado(s). {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Mensagem de origem não encontrada para encaminhamento",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Esta mensagem ainda não tem conteúdo encaminhável",
    "FORWARD_DESTINATION_MISSING": "O destino do encaminhamento está ausente",
    "FORWARD_MESSAGE_PREVIEW": "Mensagem encaminhada",
    "MENU_PASTE": "Colar",
    "MENU_COPY": "Copiar",
    "MENU_REPLY": "Responder",
    "MENU_FORWARD": "Encaminhar",
    "MENU_REMOVE_INVITATION": "Remover convite",
    "MENU_REMOVE_FROM_LIST": "Remover da lista",
    "MENU_GOODBYE_GUEST": "Adeus, Convidado",
    "MENU_ADD_TO_LIST": "Adicionar à lista",
    "MENU_REJECT_INVITATION": "Rejeitar convite",
    "MENU_FRONTEND_VERSION": "Versão do frontend",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Informações do banner: {title}",
    "MENU_MESSAGE_BUBBLE": "Bolha de mensagem",
    "MENU_CHAT_CANVAS_HEADER": "Canvas do chat - {zone}",
    "MENU_CANVAS_INFO": "Informações do canvas",
    "MENU_CHAT_CANVAS_SUBLABEL": "Área de conversa / superfície do chat atual",
    "MENU_INPUT_AREA_HEADER": "Área de entrada - {zone}",
    "MENU_INPUT_AREA_INFO": "Informações da área de entrada: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Superfície inferior de digitação e ferramentas de ação",
    "MENU_HEADER": "Cabeçalho - {zone}",
    "MENU_HEADER_INFO": "Informações do cabeçalho: {title}",
    "MENU_HEADER_DESCRIPTION": "Navegação superior e controles da página",
    "MENU_ZONE_HEADER": "Zona - {zone}",
    "MENU_ZONE_SPACE_INFO": "Informações do espaço da zona",
    "MENU_EMPTY_LIST_SURFACE": "Superfície vazia/lista",
    "MENU_BLOCK": "Bloquear",
    "MENU_UNBLOCK": "Desbloquear",
    "MENU_HIDE_IN_SEARCH": "Ocultar na pesquisa",
    "MENU_UNHIDE_IN_SEARCH": "Mostrar na pesquisa",
    "MENU_VISIBLE_IN_SEARCH": "Visível na pesquisa",
    "MENU_HIDDEN_IN_SEARCH": "Oculto na pesquisa",
    "MENU_VISIBLE_IN_USER_LIST": "Visível na lista de usuários",
    "MENU_HIDDEN_IN_USER_LIST": "Oculto na lista de usuários",
    "MENU_NOT_BLOCKED": "Não bloqueado",
    "MENU_BLOCKED": "Bloqueado",
    "MENU_FRONTEND_VERSION_LOADING": "Carregando...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Carregando o valor por banner a partir do backend. Nenhuma opção é marcada como ativa até a resposta do banco de dados chegar.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Não foi possível carregar o valor do backend. Nenhuma opção ativa confiável é exibida.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "O valor explícito por banner no banco de dados é {overrideVersion}. O padrão global é {globalDefaultVersion}. O usuário de destino deve atualizar completamente ou reabrir o app para que o bootstrap de inicialização o aplique.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Nenhum valor explícito por banner está armazenado. FeV2.0.0 está ativo por padrão. O padrão global é {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "O valor explícito por banner fica ativo depois que o app de destino é recarregado completamente",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Nenhum valor explícito por banner está armazenado; este é o estado individual padrão FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Esta opção também é igual ao padrão global atual",
    "MENU_DELETE_PERMANENT_CONFIRM": "Excluir {target} permanentemente do banco de dados? Isso remove a conta, o histórico de chat, as dependências e força um novo fluxo de convite para qualquer reentrada futura.",
    "MENU_DELETE_PERMANENTLY": "Excluir permanentemente",
    "MENU_REFRESH_PAGE": "Atualizar página",
    "MENU_LOG_OFF": "Sair",
    "MENU_HARD_RELOAD": "Recarregamento forçado",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-mail (usuário admin)",
    "AUTH_PASSWORD_PLACEHOLDER": "Senha",
    "AUTH_CONNECTING": "Conectando...",
    "AUTH_SIGNING_OUT": "Saindo...",
    "AUTH_BACK_TO_LOGIN": "Voltar ao login",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Resposta inválida do servidor: nenhum token encontrado.",
    "AUTH_LOGIN_FAILED": "Falha no login",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "As senhas não coincidem.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "As senhas não coincidem!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "As senhas devem coincidir exatamente.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nova senha",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Confirmar senha",
    "AUTH_CHANGE_PASSWORD": "Alterar senha",
    "AUTH_SAVING_PASSWORD": "Salvando...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Senha atualizada com sucesso.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Não é possível alterar a senha agora.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Você precisa estar conectado para alterar sua senha.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Alternar visibilidade da nova senha",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Alternar visibilidade da confirmação de senha",
    "REGISTER_TITLE": "Concluir cadastro",
    "REGISTER_SUBTITLE": "Defina sua senha manualmente.",
    "REGISTER_CREATING_ACCOUNT": "Criando conta...",
    "REGISTER_FINISH_SETUP": "Finalizar configuração",
    "REGISTER_FAILED_SET_PASSWORD": "Falha ao definir senha",
    "INVITE_EMAIL_INSTRUCTION": "Digite o e-mail do convidado (formato: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Convidar",
    "INVITE_EMAIL_REQUIRED": "Digite o e-mail do convidado.",
    "INVITE_EMAIL_INVALID": "Formato de e-mail inválido. Use: user@example.com",
    "PENDING_INVITATION_TITLE": "Convite pendente",
    "PENDING_INVITATION_REMOVE_QUESTION": "Remover este convite pendente do banco de dados?",
    "PENDING_INVITATION_KEEP": "Manter convite",
    "PENDING_INVITATION_REMOVAL_FAILED": "Falha na remoção.",
    "REMOVE_FROM_LIST_TITLE": "Remover da lista",
    "REMOVE_FROM_LIST_WARNING": "Remover este usuário de ambas as listas agora? O acesso ao chat será cortado imediatamente. O único caminho de retorno é um novo convite.",
    "REMOVE_FROM_LIST_KEEP": "Manter usuário na lista",
    "REMOVE_FROM_LIST_FAILED": "Falha ao remover da lista.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Configuração e status ao vivo",
    "PERMISSION_DIALOG_ARIA": "Configuração e status ao vivo",
    "PERMISSION_TRIGGER_ARIA": "Acionador do pop-up de configurações",
    "PERMISSION_CLOSE_ARIA": "Fechar pop-up de permissões",
    "PERMISSION_LIVE_STATUS": "Status ao vivo",
    "PERMISSION_SYSTEM_PERMISSION": "Permissão do sistema",
    "PERMISSION_APP_PUSH": "Push do app",
    "PERMISSION_LOCATION_PERMISSION": "Permissão de localização",
    "PERMISSION_APP_LOCATION": "Localização do app",
    "PERMISSION_CONTROLS": "Controles de permissão",
    "PERMISSION_PUSH_NOTIFICATIONS": "Notificações push",
    "PERMISSION_LOCATION_ACCESS": "Acesso à localização",
    "PERMISSION_IN_APP_SETTINGS": "Configurações no app",
    "PERMISSION_ALERT_SOUND": "Som de alerta",
    "PERMISSION_APP_BADGE": "Badge do app",
    "PERMISSION_PASSWORD_SETTINGS": "Configurações de senha",
    "PERMISSION_NAVIGATION_STATUS": "Status de navegação",
    "PERMISSION_SELECTED_ZONE": "Zona selecionada",
    "PERMISSION_STAGED_CHAT_BANNER": "Banner de chat preparado",
    "PERMISSION_CANVAS_CONTENT": "Conteúdo do canvas",
    "PERMISSION_YOUR_DEVICES": "Seus dispositivos ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Atualizar lista de dispositivos",
    "PERMISSION_REFRESH_LIST": "Atualizar lista",
    "PERMISSION_NO_REGISTERED_DEVICES": "Nenhum dispositivo registrado encontrado.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Redimensionar pop-up de configurações",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Alternar notificações push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Alternar acesso à localização",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Alternar som de alerta",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Alternar badge do app",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Alternar visibilidade do perfil",
    "PERMISSION_OFF_IN_V1": "Desativado na v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Lista de banners",
    "PERMISSION_PUSH_DISABLED_V1": "As notificações push estão desativadas para a versão v1 do Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "As notificações push estão ativadas para este dispositivo.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "As notificações do sistema estão bloqueadas. Toque para abrir a ajuda das configurações.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Ative para melhorar a confiabilidade da entrega.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Para desativar as notificações do sistema, abra as configurações de notificação do seu navegador/site e defina este site como Bloquear.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Para alterar a permissão de notificações do sistema, abra as configurações de notificação do seu navegador/site e defina este site como Permitir.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "O acesso à localização está ativado para ordenação LCAC baseada em distância e posicionamento no mapa.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "A API de localização não é suportada neste ambiente.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "O acesso à localização está bloqueado. Toque para abrir a ajuda das configurações.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Ative para permitir ordenação LCAC precisa baseada em distância e posicionamento no mapa dentro do app.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "O acesso à localização não é suportado neste ambiente.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Para desativar o acesso à localização, abra as configurações de localização do seu navegador/site e defina este site como Bloquear.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Para ativar o acesso à localização para ordenação por distância e posicionamento no mapa dentro do app, abra as configurações de localização do seu navegador/site e defina este site como Permitir.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Não foi possível carregar os dispositivos registrados agora.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Carregando ponte de UI...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Carregando ponte local...",
    "RUNTIME_LOADING_BACKEND": "Carregando backend...",
    "RUNTIME_LOADING": "Carregando...",
    "RUNTIME_LOADING_FROM_DATABASE": "Carregando do banco de dados...",
    "RUNTIME_BACKEND_CONNECTED": "Backend conectado",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Fallback em cache ativo",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback padrão ativo",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Padrões de fallback ativos",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Salvando pelo backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Salvo no serviço de backend",
    "RUNTIME_SAVE_FAILED": "Falha ao salvar",
    "RUNTIME_LOAD_FAILED": "Falha ao carregar",
    "RUNTIME_CONNECTED": "Conectado",
    "RUNTIME_LOGIN_REQUIRED": "Login obrigatório",
    "RUNTIME_SAVED": "Salvo",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI pronta - runtime pendente",
    "RUNTIME_BACKEND_REJECTED_MODEL": "O serviço seletor protegido do backend rejeitou ou não pôde salvar a opção de modelo solicitada.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "O serviço seletor protegido do backend rejeitou ou não pôde salvar a alteração de roteamento WF1 solicitada.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "O seletor agora está lendo a configuração ativa, o roteamento Qwen e as opções permitidas a partir do serviço de backend protegido.",
    "RUNTIME_WF1_SELECTOR_CACHED": "O serviço seletor do backend está indisponível agora, portanto o último estado em cache do seletor está sendo usado.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Os valores padrão do seletor estão ativos porque nenhum estado de backend ou cache pôde ser carregado.",
    "RUNTIME_WF1_SELECTOR_SAVED": "O serviço seletor protegido do backend atualizou a configuração ativa de roteamento WF1 e atualizou o cache de domínio runtime.",
    "FRONTEND_VERSION_TITLE": "Versão do frontend",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Este seletor controla a versão frontend ativa para todos os usuários. FeV2.0.0 está ativo.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Este seletor lê a versão frontend ativa de config_domain_registry. O runtime resolve para FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "A configuração de versão frontend do backend não pôde ser carregada, então o padrão codificado FeV2.0.0 permanece ativo até que o bootstrap de inicialização possa ler novamente o serviço protegido.",
    "FRONTEND_VERSION_HELPER_SAVED": "A versão frontend ativa foi salva em config_domain_registry. Uma atualização completa ou o próximo carregamento do app aplica o valor runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "O serviço de controle de versão frontend do backend não pôde salvar a versão global solicitada.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Versão frontend ativa.",
    "CHAT_DELETE_WINDOW_TITLE": "Janela de exclusão do chat",
    "CHAT_DELETE_HELPER": "Este valor controla a janela de disponibilidade de Excluir para todos em segundos. A guarda do backend muda imediatamente após salvar. A visibilidade da bolha muda após uma atualização completa ou no próximo carregamento do app.",
    "CHAT_DELETE_HELPER_FALLBACK": "O serviço de controle de exclusão de chat do backend não pôde ser carregado, então o padrão codificado permanece ativo até que o bootstrap de inicialização possa ler novamente o serviço protegido.",
    "CHAT_DELETE_HELPER_SAVED": "A janela de disponibilidade de Excluir para todos foi salva em config_domain_registry. A guarda do backend muda imediatamente. A visibilidade da bolha muda após uma atualização completa ou no próximo carregamento do app.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "O serviço de controle de exclusão de chat do backend não pôde salvar o valor de janela solicitado.",
    "CHAT_DELETE_WINDOW_LABEL": "Janela de Excluir para todos",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} s",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Armazene o valor em segundos inteiros. O valor atual de produção é 86400 segundos = 1 dia.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Segundos da janela",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Digite um número inteiro maior ou igual a 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Salvar janela de exclusão",
    "GUEST_BANNER_CONTROL_TITLE": "Banner de Convidado",
    "GUEST_BANNER_CONTROL_LABEL": "Chat QR de Convidado",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Mostrar banner de convidado para todos os usuários",
    "GUEST_BANNER_CONTROL_HELPER": "Controla o banner fixo de Convidado e o tempo de vida do token QR pendente.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "O fallback local está ativo para os controlos do banner de Convidado.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Controlos do banner de Convidado guardados.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Não foi possível guardar os controlos do banner de Convidado.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "{count} sessões de Convidado revogadas.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "TTL do QR pendente (minutos)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "TTL do QR pendente atual: {count} minutos.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Insira um número inteiro positivo de minutos.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Salvar banner de convidado",
    "GUEST_QR_LOADING": "Preparando QR de convidado...",
    "GUEST_QR_READY": "Escaneie para abrir o chat de convidado temporário.",
    "GUEST_QR_ALT": "Código QR do chat de convidado",
    "GUEST_QR_LOAD_FAILED": "Não foi possível preparar o QR de convidado.",
    "GUEST_SESSION_ACTIVE": "O convidado está conectado.",
    "GUEST_PUBLIC_TITLE": "Chat de Convidado",
    "GUEST_PUBLIC_CONNECTING": "Conectando...",
    "GUEST_PUBLIC_CONNECTED": "Conectado",
    "GUEST_PUBLIC_UNAVAILABLE": "Este link de convidado não está disponível.",
    "GUEST_PUBLIC_SEND_FAILED": "A mensagem não pôde ser enviada.",
    "UI_TEXTS_RUNTIME_TITLE": "Runtime do Idioma da IU",
    "UI_TEXTS_RUNTIME_BACKEND": "O runtime do idioma da IU está a ler a partir do serviço de backend protegido. As alterações serão aplicadas no próximo carregamento completo da aplicação.",
    "UI_TEXTS_RUNTIME_CACHED": "O serviço de runtime do idioma da IU do backend está indisponível de momento, pelo que as predefinições em cache ou locais estão ativas.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "As predefinições do runtime do idioma da IU estão ativas porque não foi possível carregar nenhum estado de backend ou em cache.",
    "UI_TEXTS_RUNTIME_SAVED": "O controlo do runtime do idioma da IU foi guardado. É necessária uma atualização completa ou o próximo carregamento da aplicação para que os utilizadores recebam a nova configuração de idioma.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "O serviço de backend protegido não conseguiu salvar a alteração de tempo de execução do idioma da IU solicitada.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Aplicação do idioma do dispositivo",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Ativar idiomas da IU em tempo de execução",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Os usuários podem receber cargas de texto da IU para o idioma armazenado ou do dispositivo.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Todos os usuários são forçados a usar o texto da IU em inglês, e o idioma do dispositivo é ignorado.",
    "PROFILE_VISIBILITY_TITLE": "Visibilidade do perfil",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Você precisa estar conectado para gerenciar a visibilidade da conta.",
    "PROFILE_VISIBILITY_HELPER": "Esta chave atualiza apenas o estado de visibilidade da sua conta. A descobribilidade e o comportamento da lista de banners permanecem inalterados nesta fase.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Não foi possível carregar a visibilidade do perfil agora.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Não foi possível atualizar a visibilidade do perfil agora.",
    "PROFILE_VISIBILITY_SAVED": "A visibilidade da sua conta agora é {visibility}. Os sinalizadores de descobribilidade permanecem inalterados nesta fase.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Conta pública",
    "PROFILE_VISIBILITY_STORED": "Visibilidade armazenada",
    "WF1_MODEL_CONTROL_TITLE": "Controle de modelo WF1",
    "WF1_ENABLE_TRANSLATION": "Ativar tradução / pivô",
    "WF1_TRANSLATION_ACTIVE": "A tradução por IA está ativa.",
    "WF1_TRANSLATION_INACTIVE": "WF1 continua em execução, mas o texto de origem é copiado e o pivô é marcado como inativo.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Slot runtime ativo",
    "WF1_ALLOW_SAME_LANGUAGE": "Permitir IA para pares do mesmo idioma",
    "WF1_SAME_LANGUAGE_ACTIVE": "Pares do mesmo idioma seguem o roteamento WF1 normal.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Pares do mesmo idioma ignoram a IA e armazenam Nenhum idioma pivô ativo.",
    "WF1_QWEN_ROUTING": "Roteamento de pares Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Os idiomas marcados abaixo usam Qwen-Max quando o par é o mesmo idioma marcado, um idioma marcado com inglês ou dois idiomas não ingleses marcados. Caso contrário, o modelo primário selecionado permanece ativo.",
    "WF1_OPENROUTER_TEST_SLOT": "Slot de teste OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Slot de teste OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Apenas teste de qualidade",
    "WF1_OPENROUTER_HELPER": "Este slot é editável apenas para testes temporários de qualidade OpenRouter. Ele não altera o caminho operacional de roteamento de pares Qwen, a menos que este próprio slot se torne o modelo ativo.",
    "WF1_LABEL": "Rótulo",
    "WF1_PRODUCT": "Produto",
    "WF1_MODEL": "Modelo",
    "WF1_PROVIDER_OPENROUTER": "Provedor: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Segredo: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Slot de teste OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max via OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Preço de tabela do Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Preço de tabela da OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Preço de tabela da OpenRouter",
    "LANGUAGE_ENGLISH": "Inglês",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Chinês (simplificado)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Chinês (tradicional)",
    "LANGUAGE_JAPANESE": "Japonês",
    "LANGUAGE_KOREAN": "Coreano",
    "LANGUAGE_PERSIAN": "Persa",
    "LANGUAGE_TURKISH_ISTANBUL": "Turco (Istambul)",
    "LANGUAGE_ARABIC": "Árabe",
    "LANGUAGE_FRENCH": "Francês",
    "LANGUAGE_GERMAN": "Alemão",
    "LANGUAGE_SPANISH": "Espanhol",
    "LANGUAGE_PORTUGUESE": "Português",
    "LANGUAGE_ITALIAN": "Italiano",
    "LANGUAGE_RUSSIAN": "Russo",
    "LANGUAGE_DUTCH": "Holandês",
    "LANGUAGE_VIETNAMESE": "Vietnamita",
    "LANGUAGE_INDONESIAN": "Indonésio",
    "LANGUAGE_THAI": "Tailandês",
    "LANGUAGE_MALAY": "Malaio",
    "WF1_PRICING_CUSTOM": "Preço: modelo de slot personalizado - verifique o preço atual da OpenRouter",
    "WF1_SAVE_OPENROUTER_SLOT": "Salvar slot OpenRouter",
    "WF1_PRICING_LINE": "Entrada {input} - Saída {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Segredo: {secret}",
    "ZONE_VISIBILITY_TITLE": "Controle de visibilidade de zonas",
    "ZONE_ENABLE": "Ativar {zone}",
    "ZONE_ENABLED_NOTE": "{zone} pode aparecer para funções permitidas após o próximo carregamento do app.",
    "ZONE_DISABLED_NOTE": "{zone} é tratada como ausente para usuários que não são S_Admin após o próximo carregamento do app.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin ignora esta lista de funções e sempre mantém o acesso.",
    "ZONE_ROLE_LOCKED": "As seleções de função ficam temporariamente bloqueadas enquanto esta zona está desativada e retornarão exatamente como foram salvas quando a zona for ativada novamente.",
    "ZONE_LCAC_CONTROL": "Controle LCAC",
    "ZONE_RCAC_CONTROL": "Controle RCAC",
    "ZONE_LCAC_DESCRIPTION": "Controla a existência da zona reservada esquerda e as funções que podem vê-la.",
    "ZONE_RCAC_DESCRIPTION": "Controla a existência da zona reservada direita e as funções que podem vê-la.",
    "ZONE_VISIBILITY_BACKEND": "O bootstrap de visibilidade de zonas agora está lendo do serviço de backend protegido. As alterações se aplicam no próximo carregamento do app.",
    "ZONE_VISIBILITY_CACHED": "O serviço de visibilidade de zonas do backend está indisponível agora, então valores em cache ou padrões locais estão ativos.",
    "ZONE_VISIBILITY_DEFAULTS": "Os padrões de visibilidade de zonas estão ativos porque nenhum estado de backend ou cache pôde ser carregado.",
    "ZONE_VISIBILITY_SAVED": "O bootstrap de visibilidade de zonas foi salvo. Um recarregamento forçado ou o próximo carregamento do app é necessário para aplicação em runtime.",
    "ZONE_VISIBILITY_SAVE_FAILED": "O serviço de backend protegido não pôde salvar a alteração de visibilidade de zona solicitada.",
    "ROLE_MEMBER": "Membro",
    "ROLE_STAFF": "Equipe",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Ative as notificações para receber novas mensagens.",
    "MAIN_LOG_OUT": "Sair",
    "NOTIFICATION_NEW_MESSAGE": "Nova mensagem",
    "NOTIFICATION_UNREAD_MESSAGE": "Você tem uma mensagem não lida.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Visualização completa",
    "MEDIA_AUDIO_ATTACHMENT": "Anexo de áudio",
    "MEDIA_FILE_FALLBACK": "Arquivo",
    "MEDIA_DOWNLOAD_READY": "Anexo pronto para download",
    "MEDIA_TYPE_UNSUPPORTED": "Tipo não suportado para visualização completa",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Imagem anterior",
    "MEDIA_NEXT_IMAGE_ARIA": "Próxima imagem",
    "MEDIA_OPEN_ORIGINAL": "Abrir original",
    "MEDIA_DOWNLOAD": "Baixar",
    "MEDIA_CLOSE_ARIA": "Fechar",
    "MEDIA_PROFILE_PICTURE_ARIA": "Foto de perfil de {name}",
    "MEDIA_PROFILE_ALT": "Perfil de {name}",
    "MEDIA_UPLOAD_FAILED": "Falha no upload",
    "MEDIA_BACKEND_TOKEN_ERROR": "Erro de token do backend",
    "MEDIA_UPLOAD_URL_MISSING": "Crítico: a URL de upload está ausente na resposta do backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Token de autenticação ausente para upload de chat",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Falha na solicitação de token de upload de chat",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Resposta de upload de chat inválida",
    "MEDIA_GCS_UPLOAD_FAILED": "Falha no upload GCS",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Nome do arquivo ou contentType ausente",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path ausente",
    "BLOCK_NOTICE_TITLE": "Aviso de bloqueio permanente",
    "BLOCK_NOTICE_MESSAGE": "Sua conta foi temporariamente suspensa devido à violação da política.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Se você acredita que isso requer acompanhamento, entre em contato com",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "por e-mail.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Usuário desconhecido",
    "GENERAL_GUEST": "Convidado",
    "ADVISOR_FOR_CLIENT": "Consultor para {client_display_name}",
    "GUEST_FOR_CLIENT": "Convidado para {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token e senha são obrigatórios",
    "AUTH_ERROR_REQUEST_BODY_JSON": "O corpo da solicitação deve ser JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Token de convite inválido ou expirado",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Falha ao definir senha: sessão ou usuário ausente",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Falha ao definir senha durante o login",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Falha na geração do token admin",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Falha no login: sessão ou usuário ausente",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Cadastro realizado com sucesso. Verifique o e-mail para confirmação.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Falha desconhecida no cadastro",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Processamento de token inválido",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Token de acesso é obrigatório",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "A prévia do hash do token requer dica de e-mail da URL de redirecionamento",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Não foi possível resolver a identidade para este token",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Somente o Usuário Zero pode acessar o serviço seletor LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Somente o Usuário Zero pode acessar o serviço de controle de visibilidade de zonas.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Somente o Usuário Zero pode acessar o serviço de controle de versão frontend.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Somente o Usuário Zero pode inspecionar a versão frontend de outro usuário.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Somente o Usuário Zero pode acessar o serviço de controle de exclusão de chat.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Apenas o Usuário Zero pode acessar o serviço de controle de tempo de execução do idioma da UI.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Somente o Usuário Zero pode excluir permanentemente uma conta de usuário.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Payload de solicitação inválido.",
    "API_ERROR_INTERNAL_SERVER": "Erro interno do servidor",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Função ausente no backend (recarregamento necessário)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Somente DB RPC é permitido para transições delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Aguarde antes de enviar outra mensagem.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Mensagem enviada com sucesso.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "O serviço de contato está indisponível.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Falha no envio da mensagem.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Nome é obrigatório.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-mail inválido.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Mensagem é obrigatória.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload do seletor é obrigatório.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload de visibilidade de zonas é obrigatório.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload da versão frontend é obrigatório.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload de controle de exclusão de chat é obrigatório.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "O payload de controle de tempo de execução do idioma da UI é obrigatório.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID do usuário autenticado é obrigatório.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID do visualizador autenticado é obrigatório.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID do ator autenticado é obrigatório.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id é obrigatório.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id é obrigatório.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "A lista owner_user_ids é obrigatória.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email é obrigatório.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by é obrigatório.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "O runtime de pesquisa está desativado pela versão frontend global.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Você não tem permissão para cancelar este convite pendente.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Este convite não pode mais ser cancelado porque o usuário já está registrado.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Convite pendente não encontrado.",
    "INVITE_REPLY_ALREADY_MEMBER": "Parabéns, seu amigo ({invitee_email}) já está registrado neste app e é membro deste workspace.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Há um convite pendente para {invitee_email}, mas o e-mail de reenvio não pôde ser acionado. Verifique os logs de e-mail.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "O registro de convite foi criado para {invitee_email}, mas a entrega do e-mail não pôde ser confirmada. Tente novamente mais tarde ou verifique os logs de e-mail.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Falha ao criar registro de convite. Tente novamente mais tarde.",
    "INVITE_REPLY_SYSTEM_ERROR": "Erro do sistema durante o processo de convite: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Erro de configuração do backend: credenciais Supabase ausentes",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Erro de configuração do backend: URL Supabase inválida",
    "CHAT_ERROR_ACCESS_DENIED": "Acesso negado",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "O conteúdo não pode estar vazio para mensagens de texto",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Não foi possível determinar o ID da conversa",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "O contexto de autenticação RPC está ausente",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "A RPC retornou um payload de mensagem inválido",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Falha na inserção, nenhum dado retornado",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations deve ser uma lista",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Payload de operação inválido",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type não suportado",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id é obrigatório",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Mensagem não encontrada",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "A exclusão só é permitida em sua própria mensagem",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Excluir para todos não está mais disponível para esta mensagem",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Falha ao excluir para todos",
    "API_ERROR_SERVER_CONFIGURATION": "Erro de configuração do servidor",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Cabeçalho secreto do webhook ausente",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Fonte de webhook não autorizada",
    "API_ERROR_BACKEND_CONFIGURATION": "Erro de configuração do backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Erro de atributo do módulo: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Falha antes da exclusão do convite ao remover o usuário auth em espera.",
    "CHAT_ERROR_DB": "Erro de DB: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "PERMISSION_MIC_PERMISSION": "",
    "PERMISSION_MIC_ACCESS": "",
    "PERMISSION_TOGGLE_MIC_ARIA": "",
    "PERMISSION_MIC_ON_TOOLTIP": "",
    "PERMISSION_MIC_ENABLE_TOOLTIP": "",
    "PERMISSION_MIC_BLOCKED_TOOLTIP": "",
    "PERMISSION_MIC_DISABLE_HELP": "",
    "PERMISSION_MIC_BLOCKED_HELP": "",
    "LIVE_CONV_MIC_PROMPT_TITLE": "",
    "LIVE_CONV_MIC_PROMPT_BODY": "",
    "LIVE_CONV_MIC_PROMPT_ALLOW": "",
    "LIVE_CONV_MIC_PROMPT_CANCEL": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
