# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/ro.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Principal",
    "APP_TITLE": "Platforma AI OTMEGA",
    "APP_SUBTITLE": "Consilier AI",
    "CHAT_PLACEHOLDER": "Scrieți mesajul...",
    "CHAT_SEND_BUTTON": "Trimite",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Consilierul poate face greșeli, așadar verificați informațiile.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Meniu",
    "ICON_NEW_CHAT": "Conversație nouă",
    "ICON_HISTORY": "Istoric",
    "ICON_TEMPLATES": "Șabloane",
    "ICON_SETTINGS": "Setări",
    "ICON_USER_PROFILE": "Profil utilizator",
    "ICON_QUICK_ACTIONS": "Acțiuni rapide",
    "ICON_PINNED": "Fixat",
    "ICON_GALLERY": "Galerie",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Instalează aplicația",
    "PWA_ANDROID_MSG": "Instalați această aplicație pe dispozitiv pentru o experiență mai bună și acces offline.",
    "PWA_IOS_MSG": "Pentru a instala această aplicație pe iPhone/iPad:\n1. Atingeți butonul Partajare de mai jos\n2. Selectați „Adaugă pe ecranul principal”",
    "PWA_BTN_INSTALL": "Instalează",
    "PWA_BTN_LATER": "Poate mai târziu",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Conectați-vă la rețeaua de consilieri",
    "AUTH_HEADER_SIGNUP": "Creați-vă contul unificat",
    "AUTH_HEADER_LOGIN_NETWORK": "Conectați-vă la rețeaua de consilieri",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Creați-vă contul unificat",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Autentificare",
    "AUTH_BUTTON_SIGNUP": "Creează cont",
    "AUTH_BUTTON_GOOGLE": "Continuă cu Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Am uitat parola",
    "AUTH_BUTTON_SEND_RESET_LINK": "Trimite linkul de resetare",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Nu aveți cont? Înscrieți-vă",
    "AUTH_PROMPT_LOGIN": "Aveți deja un cont? Conectați-vă",
    "AUTH_HELPER_TEXT_SIGNUP": "Creați un cont unificat pe care îl puteți folosi pentru a accesa toți consilierii de pe această platformă.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Creați un cont unificat pe care îl puteți folosi pentru a accesa toți consilierii de pe această platformă.",
    "AUTH_HELPER_TEXT_LOGIN": "Folosiți același cont (e-mail/parolă sau Google) pe care l-ați folosit pentru alți consilieri din această rețea.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Folosiți același cont (e-mail/parolă sau Google) pe care l-ați folosit pentru alți consilieri din această rețea.",
    "AUTH_FORGOT_PASSWORD_LINK": "Ați uitat parola?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Resetați parola",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Introduceți adresa de e-mail și vă vom trimite un link pentru resetarea parolei.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-mail",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Vă conectăm...",
    "AUTH_STATUS_LOADING_SIGNUP": "Se creează contul...",
    "AUTH_STATUS_LOADING_RESET": "Se trimite linkul de resetare...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Autentificare reușită! Se reîncarcă...",
    "AUTH_STATUS_SUCCESS_RESET": "Linkul de resetare a fost trimis cu succes. Verificați e-mailul.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Linkul de resetare a parolei a fost trimis cu succes. Verificați e-mailul.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "E-mail sau parolă nevalidă.",
    "AUTH_ERROR_EMAIL_EXISTS": "Există deja un cont cu acest e-mail în rețeaua de consilieri.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Există deja un cont cu acest e-mail. Vă rugăm să vă conectați. În prezent sunteți membru în:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Există deja un cont cu acest e-mail în rețeaua de consilieri. Închideți această fereastră și folosiți secțiunea „Autentificare” cu același e-mail și parola anterioară.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "În prezent sunteți membru în:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-mailul și parola sunt obligatorii.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Contul a fost creat, dar configurarea apartenenței a eșuat. Contactați suportul.",
    "AUTH_ERROR_DEFAULT": "A apărut o eroare. Încercați din nou.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "",
    "AUTH_FORGOT_PASSWORD_ERROR": "Trimiterea linkului de resetare a eșuat. Încercați din nou.",
    "INVITE_REPLY_EMAIL_SENT": "E-mailul de invitație Collabra a fost trimis prietenului dvs. la {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "E-mailul de invitație Collabra a fost retrimis prietenului dvs. la {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Afișează parola",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Ascunde parola",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Anulează",
    "GENERAL_CLOSE": "Închide",
    "GENERAL_SEND": "Trimite",
    "GENERAL_SEARCH": "Caută",
    "GENERAL_RESET": "Resetează",
    "GENERAL_ENABLE": "Activează",
    "GENERAL_LOADING": "Se încarcă...",
    "GENERAL_DELETE": "Șterge",
    "GENERAL_DELETING": "Se șterge...",
    "GENERAL_SAVE_PASSWORD": "Salvează parola",
    "AUTH_REMEMBER_EMAIL_LABEL": "Reține e-mailul",
    "GENERAL_SAVING": "Se salvează...",
    "GENERAL_SENDING": "Se trimite...",
    "GENERAL_REMOVING": "Se elimină...",
    "GENERAL_CONFIRM_REMOVAL": "Confirmă eliminarea",
    "GENERAL_EMPTY": "Gol",
    "GENERAL_UNAVAILABLE": "Indisponibil",
    "GENERAL_ENABLED": "Activat",
    "GENERAL_DISABLED": "Dezactivat",
    "GENERAL_GRANTED": "Acordat",
    "GENERAL_DENIED": "Refuzat",
    "GENERAL_DEFAULT": "Implicit",
    "GENERAL_UNSUPPORTED": "Neacceptat",
    "GENERAL_PUBLIC": "Public",
    "GENERAL_PRIVATE": "Privat",
    "GENERAL_USERNAME": "Nume de utilizator",
    "GENERAL_EMAIL": "E-mail",
    "GENERAL_YOU": "Dvs.",
    "GENERAL_USER": "Utilizator",
    "GENERAL_UNKNOWN": "Necunoscut",
    "GENERAL_VISITOR": "Vizitator",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Banner necunoscut",
    "GENERAL_ADVISOR_BANNER": "Banner consilier",
    "GENERAL_NOT_AVAILABLE": "N/D",
    "GENERAL_NOT_SELECTED": "Neselectat",
    "GENERAL_NO_EMAIL_FOUND": "Nu s-a găsit niciun e-mail",
    "GENERAL_USER_ZERO_ONLY": "Doar User Zero",
    "GENERAL_CONNECTION_STATE": "Starea conexiunii",
    "GENERAL_DISPLAY_ONLY": "Doar afișare",
    "GENERAL_TEXTAREA": "Zonă de text",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Meniu (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Acțiuni rapide (RCAC)",
    "HEADER_CHANGE_STATUS": "Schimbă starea",
    "HEADER_OT_COIN_BALANCE": "Sold OT Coin",
    "HEADER_ALT_USER": "Utilizator",
    "STATUS_BUSY": "Ocupat",
    "STATUS_AWAY": "Plecat",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Invizibil",
    "NETWORK_CHECKING_CONNECTION": "Se verifică conexiunea...",
    "NETWORK_ONLINE_LATENCY": "Online (latență: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Rețea: bună (atingeți pentru ping)",
    "CHAT_TARGET_ALT": "Țintă chat",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Caută...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Deschide fotografia de profil a lui {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Câmp mesaj",
    "CHAT_TOGGLE_VIEW_ARIA": "Comută vizualizarea",
    "CHAT_ADD_USER_ARIA": "Adaugă utilizator",
    "CHAT_ATTACH_ARIA": "Atașează",
    "CHAT_MIC_ARIA": "Microfon",
    "CHAT_SEND_ARIA": "Trimite",
    "CHAT_SEARCH_ARIA": "Caută",
    "CHAT_OPEN_SEARCH_ARIA": "Deschide căutarea",
    "CHAT_CLOSE_SEARCH_ARIA": "Închide căutarea",
    "CHAT_ATTACHMENT_ALT": "Atașament",
    "CHAT_PREVIEW_ALT": "Previzualizare",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Elimină atașamentul",
    "CHAT_REPLYING_TO": "Răspuns către",
    "CHAT_CANCEL_REPLY_ARIA": "Anulează răspunsul",
    "CHAT_UPLOADING": "Se încarcă...",
    "CHAT_LOADING_CHATS": "Se încarcă chat-urile...",
    "CHAT_SEND_FAILED": "Trimitere eșuată",
    "CHAT_SEND_FAILED_RETRY": "Trimiterea a eșuat. Încercați din nou.",
    "CHAT_RETRY": "Reîncearcă",
    "CHAT_EDITED": "editat",
    "CHAT_TYPING": "Se scrie",
    "CHAT_LOADING": "Se încarcă",
    "CHAT_PENDING_INVITATION": "Invitație în așteptare",
    "CHAT_PENDING_INVITATION_MIN": "{count} min invitație în așteptare",
    "CHAT_PENDING_INVITATION_HR": "{count} h invitație în așteptare",
    "CHAT_PENDING_INVITATION_DAY": "{count} zi invitație în așteptare",
    "CHAT_WAITING_FOR_YOU": "{label} - Așteaptă după dvs.",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Acceptare în așteptare",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Accesul la microfon a fost refuzat.",
    "CHAT_UPLOAD_FAILED": "Încărcare eșuată: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Încărcarea necesită o conexiune la internet. Încercați din nou când sunteți online.",
    "CHAT_ERROR_AUTH": "Eroare de autentificare",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Lipsește numele fișierului sau content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Lipsește conversation_id sau target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Lipsește conversation_id pentru încărcarea non-avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path avatar nevalid",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Clientul de serviciu Supabase este indisponibil",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Confirmarea citirii avatarului este validă doar în contextul chatului cu consilierul",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Mesajul fluxului avatar nu a fost găsit sau nu este eligibil pentru confirmarea citirii",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Finalizarea mesajului avatar ca citit a eșuat",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 atașament",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} atașamente",
    "CHAT_VOICE_NOTE": "Notă vocală",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat indisponibil. Acest utilizator v-a blocat.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat indisponibil. Ați blocat acest utilizator.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Accesul la cont este blocat de politică.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat indisponibil. Acest cont este blocat definitiv de User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat indisponibil. Blocarea reciprocă este activă.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat indisponibil din cauza politicii de blocare.",
    "MESSAGE_PREVIEW_PHOTO": "Fotografie",
    "MESSAGE_PREVIEW_VOICE": "Mesaj vocal",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Fișier",
    "MESSAGE_PREVIEW_MESSAGE": "Mesaj",
    "MESSAGE_PREVIEW_SYSTEM": "Mesaj de sistem",
    "MESSAGE_PREVIEW_NEW": "Mesaj nou",
    "MESSAGE_UNKNOWN_FILE": "Fișier necunoscut",
    "MESSAGE_AUDIO_ATTACHMENT": "Atașament audio",
    "MESSAGE_FILE_ATTACHMENT": "Atașament",
    "BANNER_INVITED_BY": "invitat de {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Rezultatele căutării",
    "SEARCH_QUERY_LABEL": "Interogare:",
    "SEARCH_LOADING_VISIBILITY": "Se încarcă vizibilitatea căutării...",
    "SEARCH_NO_RESULTS": "Nu s-a găsit niciun rezultat în domeniul curent de căutare.",
    "SHARE_WITH_COLLABRA": "Partajează cu Collabra",
    "SHARE_SEND_TO": "Trimite către",
    "SHARE_SELECT_ONE_BANNER": "Selectați un banner",
    "SHARE_BANNER_LIST_ARIA": "Listă bannere",
    "SHARE_NO_MATCHING_BANNER": "Niciun banner corespunzător",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Adăugați un comentariu...",
    "SHARE_RECENT_CHATS": "Chat-uri recente",
    "SHARE_LEFT_LIST": "Lista din stânga",
    "SHARE_RIGHT_LIST": "Lista din dreapta",
    "SHARE_UNTITLED_BANNER": "Banner fără titlu",
    "SHARE_SHARED_CONTENT": "Conținut partajat",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Conținutul partajat nu a putut fi deschis.",
    "SHARE_OPEN_BANNER_FAILED": "Bannerul selectat nu a putut fi deschis.",
    "SHARE_ONE_PHOTO_SELECTED": "1 fotografie selectată",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} fotografii selectate",
    "SHARE_ONE_FILE_SELECTED": "1 fișier selectat",
    "SHARE_MANY_FILES_SELECTED": "{count} fișiere selectate",
    "FORWARD_MESSAGE_TITLE": "Redirecționează mesajul",
    "FORWARD_SELECT_RECIPIENTS": "Selectați destinatarii",
    "FORWARD_NO_OTHER_BANNER": "Nu există alt banner disponibil.",
    "FORWARD_SEND_TO_COUNT": "Trimite către {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Selectați cel puțin un banner.",
    "FORWARD_FAILED_DEFAULT": "Redirecționarea a eșuat. Încercați din nou.",
    "FORWARD_PARTIAL_SENT": "{count} trimise. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Mesajul sursă pentru redirecționare nu a fost găsit",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Acest mesaj nu are încă conținut ce poate fi redirecționat",
    "FORWARD_DESTINATION_MISSING": "Destinația redirecționării lipsește",
    "FORWARD_MESSAGE_PREVIEW": "Mesaj redirecționat",
    "MENU_PASTE": "Lipește",
    "MENU_COPY": "Copiază",
    "MENU_REPLY": "Răspunde",
    "MENU_FORWARD": "Redirecționează",
    "MENU_REMOVE_INVITATION": "Elimină invitația",
    "MENU_REMOVE_FROM_LIST": "Elimină din listă",
    "MENU_GOODBYE_GUEST": "",
    "MENU_ADD_TO_LIST": "Adaugă în listă",
    "MENU_REJECT_INVITATION": "Respinge invitația",
    "MENU_FRONTEND_VERSION": "Versiune frontend",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Informații banner: {title}",
    "MENU_MESSAGE_BUBBLE": "Bulă de mesaj",
    "MENU_CHAT_CANVAS_HEADER": "Canvas chat - {zone}",
    "MENU_CANVAS_INFO": "Informații canvas",
    "MENU_CHAT_CANVAS_SUBLABEL": "Zonă de conversație / suprafața chatului curent",
    "MENU_INPUT_AREA_HEADER": "Zonă de introducere - {zone}",
    "MENU_INPUT_AREA_INFO": "Informații zonă de introducere: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Suprafața inferioară pentru tastare și instrumente de acțiune",
    "MENU_HEADER": "Antet - {zone}",
    "MENU_HEADER_INFO": "Informații antet: {title}",
    "MENU_HEADER_DESCRIPTION": "Navigare superioară și controale de pagină",
    "MENU_ZONE_HEADER": "Zonă - {zone}",
    "MENU_ZONE_SPACE_INFO": "Informații spațiu zonă",
    "MENU_EMPTY_LIST_SURFACE": "Suprafață goală/listă",
    "MENU_BLOCK": "Blochează",
    "MENU_UNBLOCK": "Deblochează",
    "MENU_HIDE_IN_SEARCH": "Ascunde în căutare",
    "MENU_UNHIDE_IN_SEARCH": "Afișează în căutare",
    "MENU_VISIBLE_IN_SEARCH": "Vizibil în căutare",
    "MENU_HIDDEN_IN_SEARCH": "Ascuns în căutare",
    "MENU_VISIBLE_IN_USER_LIST": "Vizibil în lista de utilizatori",
    "MENU_HIDDEN_IN_USER_LIST": "Ascuns în lista de utilizatori",
    "MENU_NOT_BLOCKED": "Neblocat",
    "MENU_BLOCKED": "Blocat",
    "MENU_FRONTEND_VERSION_LOADING": "Se încarcă...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Se încarcă valoarea per banner din backend. Nicio opțiune nu este marcată activă până la sosirea răspunsului din baza de date.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Valoarea backend nu a putut fi încărcată. Nu este afișată nicio opțiune activă de încredere.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Valoarea explicită per banner din baza de date este {overrideVersion}. Valoarea globală implicită este {globalDefaultVersion}. Utilizatorul țintă trebuie să reîmprospăteze complet sau să redeschidă aplicația pentru ca bootstrap-ul de pornire să o aplice.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Nu este stocată nicio valoare explicită per banner. FeV2.0.0 este activ implicit. Valoarea globală implicită este {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Valoarea explicită per banner este activă după reîncărcarea completă a aplicației țintă",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Nu este stocată nicio valoare explicită per banner; aceasta este starea individuală implicită FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Această opțiune este, de asemenea, egală cu valoarea globală implicită curentă",
    "MENU_DELETE_PERMANENT_CONFIRM": "Ștergeți definitiv {target} din baza de date? Aceasta elimină contul, istoricul chatului, dependențele și forțează un traseu complet nou de invitație pentru reveniri viitoare.",
    "MENU_DELETE_PERMANENTLY": "Șterge definitiv",
    "MENU_REFRESH_PAGE": "Reîmprospătează pagina",
    "MENU_LOG_OFF": "Deconectare",
    "MENU_HARD_RELOAD": "Reîncărcare forțată",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-mail (utilizator admin)",
    "AUTH_PASSWORD_PLACEHOLDER": "Parolă",
    "AUTH_CONNECTING": "Se conectează...",
    "AUTH_SIGNING_OUT": "Se deconectează...",
    "AUTH_BACK_TO_LOGIN": "Înapoi la autentificare",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Răspuns server nevalid: nu s-a găsit niciun token.",
    "AUTH_LOGIN_FAILED": "Autentificare eșuată",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Parolele nu se potrivesc.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Parolele nu se potrivesc!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Parolele trebuie să se potrivească exact.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Parolă nouă",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Confirmă parola",
    "AUTH_CHANGE_PASSWORD": "Schimbă parola",
    "AUTH_SAVING_PASSWORD": "Se salvează...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Parola a fost actualizată cu succes.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Parola nu poate fi schimbată acum.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Trebuie să fiți autentificat pentru a vă schimba parola.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Comută vizibilitatea parolei noi",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Comută vizibilitatea confirmării parolei",
    "REGISTER_TITLE": "Finalizare înregistrare",
    "REGISTER_SUBTITLE": "Vă rugăm să setați manual parola.",
    "REGISTER_CREATING_ACCOUNT": "Se creează contul...",
    "REGISTER_FINISH_SETUP": "Finalizează configurarea",
    "REGISTER_FAILED_SET_PASSWORD": "Setarea parolei a eșuat",
    "INVITE_EMAIL_INSTRUCTION": "Introduceți e-mailul invitatului (format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Invită",
    "INVITE_EMAIL_REQUIRED": "Introduceți e-mailul invitatului.",
    "INVITE_EMAIL_INVALID": "Format de e-mail nevalid. Folosiți: user@example.com",
    "PENDING_INVITATION_TITLE": "Invitație în așteptare",
    "PENDING_INVITATION_REMOVE_QUESTION": "Eliminați această invitație în așteptare din baza de date?",
    "PENDING_INVITATION_KEEP": "Păstrează invitația",
    "PENDING_INVITATION_REMOVAL_FAILED": "Eliminarea a eșuat.",
    "REMOVE_FROM_LIST_TITLE": "Elimină din listă",
    "REMOVE_FROM_LIST_WARNING": "Eliminați acum acest utilizator din ambele liste? Accesul la chat va fi întrerupt imediat. Singura cale de revenire este o invitație nouă.",
    "REMOVE_FROM_LIST_KEEP": "Păstrează utilizatorul în listă",
    "REMOVE_FROM_LIST_FAILED": "Eliminarea din listă a eșuat.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Setări și stare live",
    "PERMISSION_DIALOG_ARIA": "Setări și stare live",
    "PERMISSION_TRIGGER_ARIA": "Declanșator popup setări",
    "PERMISSION_CLOSE_ARIA": "Închide popup-ul de permisiuni",
    "PERMISSION_LIVE_STATUS": "Stare live",
    "PERMISSION_SYSTEM_PERMISSION": "Permisiune sistem",
    "PERMISSION_APP_PUSH": "Push aplicație",
    "PERMISSION_LOCATION_PERMISSION": "Permisiune locație",
    "PERMISSION_APP_LOCATION": "Locația aplicației",
    "PERMISSION_CONTROLS": "Controale permisiuni",
    "PERMISSION_PUSH_NOTIFICATIONS": "Notificări push",
    "PERMISSION_LOCATION_ACCESS": "Acces la locație",
    "PERMISSION_IN_APP_SETTINGS": "Setări în aplicație",
    "PERMISSION_ALERT_SOUND": "Sunet alertă",
    "PERMISSION_APP_BADGE": "Insignă aplicație",
    "PERMISSION_PASSWORD_SETTINGS": "Setări parolă",
    "PERMISSION_NAVIGATION_STATUS": "Stare navigare",
    "PERMISSION_SELECTED_ZONE": "Zonă selectată",
    "PERMISSION_STAGED_CHAT_BANNER": "Banner chat pregătit",
    "PERMISSION_CANVAS_CONTENT": "Conținut canvas",
    "PERMISSION_YOUR_DEVICES": "Dispozitivele dvs. ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Reîmprospătează lista dispozitivelor",
    "PERMISSION_REFRESH_LIST": "Reîmprospătează lista",
    "PERMISSION_NO_REGISTERED_DEVICES": "Nu s-au găsit dispozitive înregistrate.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Redimensionează popup-ul de setări",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Comută notificările push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Comută accesul la locație",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Comută sunetul de alertă",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Comută insigna aplicației",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Comută vizibilitatea profilului",
    "PERMISSION_OFF_IN_V1": "Oprit în v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Listă bannere",
    "PERMISSION_PUSH_DISABLED_V1": "Notificările push sunt dezactivate pentru lansarea Google Play v1.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Notificările push sunt activate pentru acest dispozitiv.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Notificările de sistem sunt blocate. Atingeți pentru a deschide ajutorul pentru setări.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Activați pentru a îmbunătăți fiabilitatea livrării.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Pentru a dezactiva notificările de sistem, deschideți setările de notificări ale browserului/site-ului și setați acest site la Blocare.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Pentru a modifica permisiunea notificărilor de sistem, deschideți setările de notificări ale browserului/site-ului și setați acest site la Permitere.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Accesul la locație este activ pentru sortarea LCAC pe bază de distanță și poziționarea pe hartă.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API-ul de locație nu este acceptat în acest mediu.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Accesul la locație este blocat. Atingeți pentru a deschide ajutorul pentru setări.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Activați pentru a permite sortarea LCAC precisă pe bază de distanță și poziționarea pe harta din aplicație.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Accesul la locație nu este acceptat în acest mediu.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Pentru a dezactiva accesul la locație, deschideți setările de locație ale browserului/site-ului și setați acest site la Blocare.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Pentru a activa accesul la locație pentru sortarea pe distanță și poziționarea pe harta din aplicație, deschideți setările de locație ale browserului/site-ului și setați acest site la Permitere.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Dispozitivele înregistrate nu pot fi încărcate acum.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Se încarcă puntea UI...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Se încarcă puntea locală...",
    "RUNTIME_LOADING_BACKEND": "Se încarcă backend-ul...",
    "RUNTIME_LOADING": "Se încarcă...",
    "RUNTIME_LOADING_FROM_DATABASE": "Se încarcă din baza de date...",
    "RUNTIME_BACKEND_CONNECTED": "Backend conectat",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Fallback cache activ",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback implicit activ",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Valori implicite fallback active",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Se salvează prin backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Salvat în serviciul backend",
    "RUNTIME_SAVE_FAILED": "Salvare eșuată",
    "RUNTIME_LOAD_FAILED": "Încărcare eșuată",
    "RUNTIME_CONNECTED": "Conectat",
    "RUNTIME_LOGIN_REQUIRED": "Autentificare necesară",
    "RUNTIME_SAVED": "Salvat",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI pregătită - runtime în așteptare",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Serviciul backend protejat al selectorului a respins sau nu a putut salva opțiunea de model solicitată.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Serviciul backend protejat al selectorului a respins sau nu a putut salva modificarea de rutare WF1 solicitată.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selectorul citește acum configurația activă, rutarea Qwen și opțiunile permise din serviciul backend protejat.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Serviciul backend al selectorului este indisponibil acum, deci este folosită ultima stare cache a selectorului.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Valorile implicite ale selectorului sunt active deoarece nu a putut fi încărcată nicio stare backend sau cache.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Serviciul backend protejat al selectorului a actualizat configurația activă de rutare WF1 și a reîmprospătat cache-ul domeniului runtime.",
    "FRONTEND_VERSION_TITLE": "Versiune frontend",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Acest selector controlează versiunea frontend activă pentru toți utilizatorii. FeV2.0.0 este activă.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Acest selector citește versiunea frontend activă din config_domain_registry. Runtime se rezolvă la FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Configurația backend a versiunii frontend nu a putut fi încărcată, deci valoarea implicită codificată FeV2.0.0 rămâne activă până când bootstrap-ul de pornire poate citi din nou serviciul protejat.",
    "FRONTEND_VERSION_HELPER_SAVED": "Versiunea frontend activă a fost salvată în config_domain_registry. O reîmprospătare completă sau următoarea încărcare a aplicației aplică valoarea runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Serviciul backend de control al versiunii frontend nu a putut salva versiunea globală solicitată.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Versiune frontend activă.",
    "CHAT_DELETE_WINDOW_TITLE": "Fereastră de ștergere chat",
    "CHAT_DELETE_HELPER": "Această valoare controlează fereastra de disponibilitate pentru Șterge pentru toți, în secunde. Garda backend se schimbă imediat după salvare. Vizibilitatea bulei se schimbă după o reîmprospătare completă sau la următoarea încărcare a aplicației.",
    "CHAT_DELETE_HELPER_FALLBACK": "Serviciul backend de control al ștergerii chatului nu a putut fi încărcat, deci valoarea implicită codificată rămâne activă până când bootstrap-ul de pornire poate citi din nou serviciul protejat.",
    "CHAT_DELETE_HELPER_SAVED": "Fereastra de disponibilitate pentru Șterge pentru toți a fost salvată în config_domain_registry. Garda backend se schimbă imediat. Vizibilitatea bulei se schimbă după o reîmprospătare completă sau la următoarea încărcare a aplicației.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Serviciul backend de control al ștergerii chatului nu a putut salva valoarea ferestrei solicitate.",
    "CHAT_DELETE_WINDOW_LABEL": "Fereastră Șterge pentru toți",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} sec",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Stocați valoarea în secunde întregi. Valoarea curentă de producție este 86400 secunde = 1 zi.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Secunde fereastră",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Introduceți un număr întreg mai mare sau egal cu 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Salvează fereastra de ștergere",
    "GUEST_BANNER_CONTROL_TITLE": "",
    "GUEST_BANNER_CONTROL_LABEL": "",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "",
    "GUEST_BANNER_CONTROL_HELPER": "",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "",
    "GUEST_BANNER_PENDING_TTL_INVALID": "",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "",
    "GUEST_QR_LOADING": "",
    "GUEST_QR_READY": "",
    "GUEST_QR_ALT": "",
    "GUEST_QR_LOAD_FAILED": "",
    "GUEST_SESSION_ACTIVE": "",
    "GUEST_PUBLIC_TITLE": "",
    "GUEST_PUBLIC_CONNECTING": "",
    "GUEST_PUBLIC_CONNECTED": "",
    "GUEST_PUBLIC_UNAVAILABLE": "",
    "GUEST_PUBLIC_SEND_FAILED": "",
    "UI_TEXTS_RUNTIME_TITLE": "",
    "UI_TEXTS_RUNTIME_BACKEND": "",
    "UI_TEXTS_RUNTIME_CACHED": "",
    "UI_TEXTS_RUNTIME_DEFAULTS": "",
    "UI_TEXTS_RUNTIME_SAVED": "",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "",
    "PROFILE_VISIBILITY_TITLE": "Vizibilitate profil",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Trebuie să fiți autentificat pentru a gestiona vizibilitatea contului.",
    "PROFILE_VISIBILITY_HELPER": "Acest comutator actualizează doar starea de vizibilitate a contului dvs. Descoperibilitatea și comportamentul listei de bannere rămân neschimbate în această fază.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Vizibilitatea profilului nu a putut fi încărcată acum.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Vizibilitatea profilului nu a putut fi actualizată acum.",
    "PROFILE_VISIBILITY_SAVED": "Vizibilitatea contului dvs. este acum {visibility}. Indicatorii de descoperibilitate rămân neschimbați în această fază.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Cont public",
    "PROFILE_VISIBILITY_STORED": "Vizibilitate stocată",
    "WF1_MODEL_CONTROL_TITLE": "Control model WF1",
    "WF1_ENABLE_TRANSLATION": "Activează traducerea / pivotul",
    "WF1_TRANSLATION_ACTIVE": "Traducerea AI este activă.",
    "WF1_TRANSLATION_INACTIVE": "WF1 continuă să ruleze, dar textul sursă este copiat și pivotul este marcat ca inactiv.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Slot runtime activ",
    "WF1_ALLOW_SAME_LANGUAGE": "Permite AI pentru perechi de aceeași limbă",
    "WF1_SAME_LANGUAGE_ACTIVE": "Perechile de aceeași limbă urmează rutarea WF1 normală.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Perechile de aceeași limbă ocolesc AI și stochează limba No Pivot ca activă.",
    "WF1_QWEN_ROUTING": "Rutare perechi Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Limbile bifate mai jos folosesc Qwen-Max atunci când perechea este fie aceeași limbă bifată, fie o limbă bifată cu engleza, fie două limbi non-engleze bifate. În caz contrar, modelul principal selectat rămâne activ.",
    "WF1_OPENROUTER_TEST_SLOT": "Slot de test OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Slot de test OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Doar test de calitate",
    "WF1_OPENROUTER_HELPER": "Acest slot este editabil doar pentru teste temporare de calitate OpenRouter. Nu schimbă traseul operațional de rutare a perechilor Qwen decât dacă acest slot devine el însuși modelul activ.",
    "WF1_LABEL": "Etichetă",
    "WF1_PRODUCT": "Produs",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Furnizor: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Slot de test OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max prin OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Preț de listă Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Preț de listă OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Preț de listă OpenRouter",
    "LANGUAGE_ENGLISH": "Engleză",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Chineză (simplificată)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Chineză (tradițională)",
    "LANGUAGE_JAPANESE": "Japoneză",
    "LANGUAGE_KOREAN": "Coreeană",
    "LANGUAGE_PERSIAN": "Persană",
    "LANGUAGE_TURKISH_ISTANBUL": "Turcă (Istanbul)",
    "LANGUAGE_ARABIC": "Arabă",
    "LANGUAGE_FRENCH": "Franceză",
    "LANGUAGE_GERMAN": "Germană",
    "LANGUAGE_SPANISH": "Spaniolă",
    "LANGUAGE_PORTUGUESE": "Portugheză",
    "LANGUAGE_ITALIAN": "Italiană",
    "LANGUAGE_RUSSIAN": "Rusă",
    "LANGUAGE_DUTCH": "Neerlandeză",
    "LANGUAGE_VIETNAMESE": "Vietnameză",
    "LANGUAGE_INDONESIAN": "Indoneziană",
    "LANGUAGE_THAI": "Thailandeză",
    "LANGUAGE_MALAY": "Malaeză",
    "WF1_PRICING_CUSTOM": "Preț: model de slot personalizat - verificați prețurile OpenRouter curente",
    "WF1_SAVE_OPENROUTER_SLOT": "Salvează slotul OpenRouter",
    "WF1_PRICING_LINE": "Intrare {input} - Ieșire {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "Control vizibilitate zone",
    "ZONE_ENABLE": "Activează {zone}",
    "ZONE_ENABLED_NOTE": "{zone} poate apărea pentru rolurile permise după următoarea încărcare a aplicației.",
    "ZONE_DISABLED_NOTE": "{zone} este tratată ca absentă pentru utilizatorii non-S_Admin după următoarea încărcare a aplicației.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin ocolește această listă de roluri și păstrează întotdeauna accesul.",
    "ZONE_ROLE_LOCKED": "Selecțiile de roluri sunt blocate temporar cât timp această zonă este dezactivată și vor reveni exact cum au fost salvate atunci când zona este reactivată.",
    "ZONE_LCAC_CONTROL": "Control LCAC",
    "ZONE_RCAC_CONTROL": "Control RCAC",
    "ZONE_LCAC_DESCRIPTION": "Controlează existența zonei rezervate din stânga și rolurile care o pot vedea.",
    "ZONE_RCAC_DESCRIPTION": "Controlează existența zonei rezervate din dreapta și rolurile care o pot vedea.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap-ul de vizibilitate a zonelor citește acum din serviciul backend protejat. Modificările se aplică la următoarea încărcare a aplicației.",
    "ZONE_VISIBILITY_CACHED": "Serviciul backend de vizibilitate a zonelor este indisponibil acum, deci sunt active valorile cache sau locale implicite.",
    "ZONE_VISIBILITY_DEFAULTS": "Valorile implicite de vizibilitate a zonelor sunt active deoarece nu a putut fi încărcată nicio stare backend sau cache.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap-ul de vizibilitate a zonelor a fost salvat. Este necesară o reîncărcare forțată sau următoarea încărcare a aplicației pentru aplicarea runtime.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Serviciul backend protejat nu a putut salva modificarea solicitată de vizibilitate a zonei.",
    "ROLE_MEMBER": "Membru",
    "ROLE_STAFF": "Personal",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Activați notificările pentru a primi mesaje noi.",
    "MAIN_LOG_OUT": "Deconectare",
    "NOTIFICATION_NEW_MESSAGE": "Mesaj nou",
    "NOTIFICATION_UNREAD_MESSAGE": "Aveți un mesaj necitit.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Vizualizare completă",
    "MEDIA_AUDIO_ATTACHMENT": "Atașament audio",
    "MEDIA_FILE_FALLBACK": "Fișier",
    "MEDIA_DOWNLOAD_READY": "Atașament pregătit pentru descărcare",
    "MEDIA_TYPE_UNSUPPORTED": "Tip neacceptat pentru vizualizare completă",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Imaginea anterioară",
    "MEDIA_NEXT_IMAGE_ARIA": "Imaginea următoare",
    "MEDIA_OPEN_ORIGINAL": "Deschide originalul",
    "MEDIA_DOWNLOAD": "Descarcă",
    "MEDIA_CLOSE_ARIA": "Închide",
    "MEDIA_PROFILE_PICTURE_ARIA": "Fotografia de profil a lui {name}",
    "MEDIA_PROFILE_ALT": "Profilul lui {name}",
    "MEDIA_UPLOAD_FAILED": "Încărcare eșuată",
    "MEDIA_BACKEND_TOKEN_ERROR": "Eroare token backend",
    "MEDIA_UPLOAD_URL_MISSING": "Critic: URL-ul de încărcare lipsește din răspunsul backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Lipsește tokenul de autentificare pentru încărcarea în chat",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Cererea tokenului de încărcare în chat a eșuat",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Răspuns de încărcare în chat nevalid",
    "MEDIA_GCS_UPLOAD_FAILED": "Încărcare GCS eșuată",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Lipsește numele fișierului sau contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Lipsește file_path",
    "BLOCK_NOTICE_TITLE": "Notificare de blocare permanentă",
    "BLOCK_NOTICE_MESSAGE": "Contul dvs. a fost suspendat temporar din cauza încălcării politicii.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Dacă credeți că este necesară o urmărire, contactați",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "prin e-mail.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Utilizator necunoscut",
    "GENERAL_GUEST": "Oaspete",
    "ADVISOR_FOR_CLIENT": "Consilier pentru {client_display_name}",
    "GUEST_FOR_CLIENT": "",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Tokenul și parola sunt obligatorii",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Corpul cererii trebuie să fie JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Token de invitație nevalid sau expirat",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Setarea parolei a eșuat: sesiune sau utilizator lipsă",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Setarea parolei a eșuat în timpul autentificării",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Generarea tokenului admin a eșuat",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Autentificarea a eșuat: sesiune sau utilizator lipsă",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Înregistrare reușită. Verificați e-mailul pentru confirmare.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Înscriere eșuată necunoscută",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Procesare token nevalidă",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Tokenul de acces este obligatoriu",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Previzualizarea hash-ului tokenului necesită indiciul de e-mail din URL-ul de redirecționare",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Identitatea pentru acest token nu a putut fi rezolvată",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Doar User Zero poate accesa serviciul selector LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Doar User Zero poate accesa serviciul de control al vizibilității zonelor.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Doar User Zero poate accesa serviciul de control al versiunii frontend.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Doar User Zero poate inspecta versiunea frontend a altui utilizator.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Doar User Zero poate accesa serviciul de control al ștergerii chatului.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Doar User Zero poate șterge definitiv un cont de utilizator.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Payload de cerere nevalid.",
    "API_ERROR_INTERNAL_SERVER": "Eroare internă de server",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funcție lipsă în backend (reîncărcare necesară)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Doar RPC-ul bazei de date este permis pentru tranzițiile delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Așteptați înainte de a trimite un alt mesaj.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Mesaj trimis cu succes.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Serviciul de contact este indisponibil.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Trimiterea mesajului a eșuat.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Numele este obligatoriu.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-mailul este nevalid.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Mesajul este obligatoriu.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload-ul selectorului este obligatoriu.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload-ul vizibilității zonelor este obligatoriu.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload-ul versiunii frontend este obligatoriu.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload-ul controlului de ștergere a chatului este obligatoriu.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID-ul utilizatorului autentificat este obligatoriu.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID-ul vizualizatorului autentificat este obligatoriu.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID-ul actorului autentificat este obligatoriu.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id este obligatoriu.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id este obligatoriu.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Lista owner_user_ids este obligatorie.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email este obligatoriu.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by este obligatoriu.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime-ul de căutare este dezactivat de versiunea frontend globală.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Nu aveți permisiunea să anulați această invitație în așteptare.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Această invitație nu mai poate fi anulată deoarece utilizatorul este deja înregistrat.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Invitația în așteptare nu a fost găsită.",
    "INVITE_REPLY_ALREADY_MEMBER": "Felicitări, prietenul dvs. ({invitee_email}) este deja înregistrat în această aplicație și este membru al acestui spațiu de lucru.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Există o invitație în așteptare pentru {invitee_email}, dar e-mailul de reîncercare nu a putut fi declanșat. Verificați jurnalele de e-mail.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Înregistrarea invitației a fost creată pentru {invitee_email}, dar livrarea e-mailului nu a putut fi confirmată. Încercați din nou mai târziu sau verificați jurnalele de e-mail.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Crearea înregistrării invitației a eșuat. Încercați din nou mai târziu.",
    "INVITE_REPLY_SYSTEM_ERROR": "Eroare de sistem în timpul procesului de invitație: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Eroare de configurare backend: lipsesc credențialele Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Eroare de configurare backend: URL Supabase nevalid",
    "CHAT_ERROR_ACCESS_DENIED": "Acces refuzat",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Conținutul nu poate fi gol pentru mesajele text",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "ID-ul conversației nu a putut fi determinat",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Contextul de autentificare RPC lipsește",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC a returnat un payload de mesaj nevalid",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Inserarea a eșuat, nu s-au returnat date",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations trebuie să fie o listă",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Payload de operațiune nevalid",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type neacceptat",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id este obligatoriu",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Mesajul nu a fost găsit",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Ștergerea este permisă doar pentru propriul mesaj",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Șterge pentru toți nu mai este disponibil pentru acest mesaj",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Șterge pentru toți a eșuat",
    "API_ERROR_SERVER_CONFIGURATION": "Eroare de configurare server",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Lipsește antetul secret webhook",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Sursă webhook neautorizată",
    "API_ERROR_BACKEND_CONFIGURATION": "Eroare de configurare backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Eroare atribut modul: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Eșec înainte de ștergerea invitației în timpul eliminării utilizatorului auth în așteptare.",
    "CHAT_ERROR_DB": "Eroare DB: {error}",
}
