# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/ru.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Главная",
    "APP_TITLE": "Платформа ИИ OTMEGA",
    "APP_SUBTITLE": "ИИ-советник",
    "CHAT_PLACEHOLDER": "Введите сообщение...",
    "CHAT_SEND_BUTTON": "Отправить",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Советник может ошибаться, поэтому перепроверяйте информацию.",
    "STATUS_ONLINE": "В сети",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Меню",
    "ICON_NEW_CHAT": "Новый чат",
    "ICON_HISTORY": "История",
    "ICON_TEMPLATES": "Шаблоны",
    "ICON_SETTINGS": "Настройки",
    "ICON_USER_PROFILE": "Профиль пользователя",
    "ICON_QUICK_ACTIONS": "Быстрые действия",
    "ICON_PINNED": "Закреплено",
    "ICON_GALLERY": "Галерея",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Установить приложение",
    "PWA_ANDROID_MSG": "Установите это приложение на свое устройство для более удобной работы и доступа офлайн.",
    "PWA_IOS_MSG": "Чтобы установить это приложение на iPhone/iPad:\n1. Нажмите кнопку «Поделиться» ниже\n2. Выберите «Добавить на экран Домой»",
    "PWA_BTN_INSTALL": "Установить",
    "PWA_BTN_LATER": "Возможно позже",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Войдите в сеть советников",
    "AUTH_HEADER_SIGNUP": "Создайте единую учетную запись",
    "AUTH_HEADER_LOGIN_NETWORK": "Войдите в сеть советников",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Создайте единую учетную запись",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Войти",
    "AUTH_BUTTON_SIGNUP": "Создать учетную запись",
    "AUTH_BUTTON_GOOGLE": "Продолжить с Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Забыли пароль",
    "AUTH_BUTTON_SEND_RESET_LINK": "Отправить ссылку для сброса",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Нет учетной записи? Зарегистрируйтесь",
    "AUTH_PROMPT_LOGIN": "Уже есть учетная запись? Войдите",
    "AUTH_HELPER_TEXT_SIGNUP": "Вы создаете единую учетную запись, которую сможете использовать для доступа ко всем советникам на этой платформе.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Вы создаете единую учетную запись, которую сможете использовать для доступа ко всем советникам на этой платформе.",
    "AUTH_HELPER_TEXT_LOGIN": "Используйте ту же учетную запись (email/пароль или Google), которую вы использовали для других советников в этой сети.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Используйте ту же учетную запись (email/пароль или Google), которую вы использовали для других советников в этой сети.",
    "AUTH_FORGOT_PASSWORD_LINK": "Забыли пароль?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Сбросить пароль",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Введите адрес электронной почты, и мы отправим вам ссылку для сброса пароля.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Email",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Выполняется вход...",
    "AUTH_STATUS_LOADING_SIGNUP": "Создаем вашу учетную запись...",
    "AUTH_STATUS_LOADING_RESET": "Отправляем ссылку для сброса...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Вход выполнен успешно! Перезагрузка...",
    "AUTH_STATUS_SUCCESS_RESET": "Ссылка для сброса успешно отправлена. Проверьте email.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Ссылка для сброса пароля успешно отправлена. Проверьте email.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Неверный email или пароль.",
    "AUTH_ERROR_EMAIL_EXISTS": "Учетная запись с этим email уже существует в сети советников.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Учетная запись с этим email уже существует. Пожалуйста, войдите. Сейчас вы являетесь участником:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Учетная запись с этим email уже существует в сети советников. Закройте это окно и используйте раздел «Вход» с тем же email и прежним паролем.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Сейчас вы являетесь участником:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "Email и пароль обязательны.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Учетная запись создана, но не удалось настроить членство. Обратитесь в поддержку.",
    "AUTH_ERROR_DEFAULT": "Произошла ошибка. Попробуйте еще раз.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Требуются данные для управления гостевым баннером.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Только User Zero может обновлять элементы управления гостевым баннером.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Не удалось отправить ссылку для сброса. Попробуйте еще раз.",
    "INVITE_REPLY_EMAIL_SENT": "Письмо-приглашение Collabra было отправлено вашему другу на адрес {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Письмо-приглашение Collabra было повторно отправлено вашему другу на адрес {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Показать пароль",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Скрыть пароль",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Отмена",
    "GENERAL_CLOSE": "Закрыть",
    "GENERAL_SEND": "Отправить",
    "GENERAL_SEARCH": "Поиск",
    "GENERAL_RESET": "Сбросить",
    "GENERAL_ENABLE": "Включить",
    "GENERAL_LOADING": "Загрузка...",
    "GENERAL_DELETE": "Удалить",
    "GENERAL_DELETING": "Удаление...",
    "GENERAL_SAVE_PASSWORD": "Сохранить пароль",
    "AUTH_REMEMBER_EMAIL_LABEL": "Запомнить email",
    "GENERAL_SAVING": "Сохранение...",
    "GENERAL_SENDING": "Отправка...",
    "GENERAL_REMOVING": "Удаление...",
    "GENERAL_CONFIRM_REMOVAL": "Подтвердить удаление",
    "GENERAL_EMPTY": "Пусто",
    "GENERAL_UNAVAILABLE": "Недоступно",
    "GENERAL_ENABLED": "Включено",
    "GENERAL_DISABLED": "Отключено",
    "GENERAL_GRANTED": "Разрешено",
    "GENERAL_DENIED": "Запрещено",
    "GENERAL_DEFAULT": "По умолчанию",
    "GENERAL_UNSUPPORTED": "Не поддерживается",
    "GENERAL_PUBLIC": "Публичный",
    "GENERAL_PRIVATE": "Приватный",
    "GENERAL_USERNAME": "Имя пользователя",
    "GENERAL_EMAIL": "Email",
    "GENERAL_YOU": "Вы",
    "GENERAL_USER": "Пользователь",
    "GENERAL_UNKNOWN": "Неизвестно",
    "GENERAL_VISITOR": "Посетитель",
    "GENERAL_PROFILE": "Профиль",
    "GENERAL_BANNER": "Баннер",
    "GENERAL_UNKNOWN_BANNER": "Неизвестный баннер",
    "GENERAL_ADVISOR_BANNER": "Баннер советника",
    "GENERAL_NOT_AVAILABLE": "Н/Д",
    "GENERAL_NOT_SELECTED": "Не выбрано",
    "GENERAL_NO_EMAIL_FOUND": "Email не найден",
    "GENERAL_USER_ZERO_ONLY": "Только User Zero",
    "GENERAL_CONNECTION_STATE": "Состояние подключения",
    "GENERAL_DISPLAY_ONLY": "Только отображение",
    "GENERAL_TEXTAREA": "Текстовое поле",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Меню (LCAC)",
    "HEADER_CHAT_CCAC": "Чат (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Быстрые действия (RCAC)",
    "HEADER_CHANGE_STATUS": "Изменить статус",
    "HEADER_OT_COIN_BALANCE": "Баланс OT Coin",
    "HEADER_ALT_USER": "Пользователь",
    "STATUS_BUSY": "Занят",
    "STATUS_AWAY": "Отошел",
    "STATUS_OFFLINE": "Не в сети",
    "STATUS_INVISIBLE": "Невидимый",
    "NETWORK_CHECKING_CONNECTION": "Проверка подключения...",
    "NETWORK_ONLINE_LATENCY": "В сети (задержка: {latency} мс)",
    "NETWORK_GOOD_TAP_TO_PING": "Сеть: хорошо (нажмите для проверки)",
    "CHAT_TARGET_ALT": "Цель чата",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Поиск...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Открыть фото профиля {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Поле ввода сообщения",
    "CHAT_TOGGLE_VIEW_ARIA": "Переключить вид",
    "CHAT_ADD_USER_ARIA": "Добавить пользователя",
    "CHAT_ATTACH_ARIA": "Прикрепить",
    "CHAT_MIC_ARIA": "Микрофон",
    "CHAT_SEND_ARIA": "Отправить",
    "CHAT_SEARCH_ARIA": "Поиск",
    "CHAT_OPEN_SEARCH_ARIA": "Открыть поиск",
    "CHAT_CLOSE_SEARCH_ARIA": "Закрыть поиск",
    "CHAT_ATTACHMENT_ALT": "Вложение",
    "CHAT_PREVIEW_ALT": "Предпросмотр",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Удалить вложение",
    "CHAT_REPLYING_TO": "Ответ на",
    "CHAT_CANCEL_REPLY_ARIA": "Отменить ответ",
    "CHAT_UPLOADING": "Загрузка файла...",
    "CHAT_LOADING_CHATS": "Загрузка чатов...",
    "CHAT_SEND_FAILED": "Не удалось отправить",
    "CHAT_SEND_FAILED_RETRY": "Не удалось отправить. Повторите попытку.",
    "CHAT_RETRY": "Повторить",
    "CHAT_EDITED": "изменено",
    "CHAT_TYPING": "Печатает",
    "CHAT_LOADING": "Загрузка",
    "CHAT_PENDING_INVITATION": "Приглашение ожидает",
    "CHAT_PENDING_INVITATION_MIN": "{count} мин Приглашение ожидает",
    "CHAT_PENDING_INVITATION_HR": "{count} ч Приглашение ожидает",
    "CHAT_PENDING_INVITATION_DAY": "{count} дн. Приглашение ожидает",
    "CHAT_WAITING_FOR_YOU": "{label} - ожидает вас",
    "CHAT_PENDING_ACCEPTANCE": "{label} - ожидает принятия",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Доступ к микрофону запрещен.",
    "CHAT_UPLOAD_FAILED": "Ошибка загрузки: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Для загрузки требуется подключение к интернету. Повторите попытку, когда будете онлайн.",
    "OFFLINE_SHOWING_SAVED_DATA": "",
    "OFFLINE_DATA_MAY_BE_OUTDATED": "",
    "OFFLINE_ACTION_REQUIRES_CONNECTION": "",
    "OFFLINE_MESSAGE_WAITING_CONNECTION": "",
    "OFFLINE_PENDING_MESSAGES_TOOLTIP": "",
    "APP_BACK_EXIT_HINT": "",
    "CHAT_ERROR_AUTH": "Ошибка аутентификации",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Отсутствует имя файла или content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Отсутствует conversation_id или target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Отсутствует conversation_id для загрузки неаватарного файла",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Недопустимый file_path аватара",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Сервисный клиент Supabase недоступен",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Подтверждение прочтения аватара допустимо только в контексте чата с советником",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Сообщение потока аватара не найдено или не подходит для подтверждения прочтения",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Не удалось финализировать сообщение аватара как прочитанное",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 вложение",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} вложений",
    "CHAT_VOICE_NOTE": "Голосовая заметка",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Чат недоступен. Этот пользователь заблокировал вас.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Чат недоступен. Вы заблокировали этого пользователя.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Доступ к учетной записи заблокирован политикой.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Чат недоступен. Эта учетная запись окончательно заблокирована User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Чат недоступен. Взаимная блокировка активна.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Чат недоступен из-за политики блокировки.",
    "MESSAGE_PREVIEW_PHOTO": "Фото",
    "MESSAGE_PREVIEW_VOICE": "Голосовое сообщение",
    "MESSAGE_PREVIEW_VIDEO": "Видео",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Файл",
    "MESSAGE_PREVIEW_MESSAGE": "Сообщение",
    "MESSAGE_PREVIEW_SYSTEM": "Системное сообщение",
    "MESSAGE_PREVIEW_NEW": "Новое сообщение",
    "MESSAGE_UNKNOWN_FILE": "Неизвестный файл",
    "MESSAGE_AUDIO_ATTACHMENT": "Аудиовложение",
    "MESSAGE_FILE_ATTACHMENT": "Вложение",
    "BANNER_INVITED_BY": "приглашен {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Результаты поиска",
    "SEARCH_QUERY_LABEL": "Запрос:",
    "SEARCH_LOADING_VISIBILITY": "Загрузка видимости поиска...",
    "SEARCH_NO_RESULTS": "В текущей области поиска ничего не найдено.",
    "SHARE_WITH_COLLABRA": "Поделиться через Collabra",
    "SHARE_SEND_TO": "Отправить",
    "SHARE_SELECT_ONE_BANNER": "Выберите один баннер",
    "SHARE_BANNER_LIST_ARIA": "Список баннеров",
    "SHARE_NO_MATCHING_BANNER": "Нет подходящего баннера",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Добавить комментарий...",
    "SHARE_RECENT_CHATS": "Недавние чаты",
    "SHARE_LEFT_LIST": "Левый список",
    "SHARE_RIGHT_LIST": "Правый список",
    "SHARE_UNTITLED_BANNER": "Баннер без названия",
    "SHARE_SHARED_CONTENT": "Общий контент",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Не удалось открыть общий контент.",
    "SHARE_OPEN_BANNER_FAILED": "Не удалось открыть выбранный баннер.",
    "SHARE_ONE_PHOTO_SELECTED": "Выбрано 1 фото",
    "SHARE_MANY_PHOTOS_SELECTED": "Выбрано фото: {count}",
    "SHARE_ONE_FILE_SELECTED": "Выбран 1 файл",
    "SHARE_MANY_FILES_SELECTED": "Выбрано файлов: {count}",
    "FORWARD_MESSAGE_TITLE": "Переслать сообщение",
    "FORWARD_SELECT_RECIPIENTS": "Выберите получателей",
    "FORWARD_NO_OTHER_BANNER": "Нет другого доступного баннера.",
    "FORWARD_SEND_TO_COUNT": "Отправить: {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Выберите хотя бы один баннер.",
    "FORWARD_FAILED_DEFAULT": "Не удалось переслать. Попробуйте еще раз.",
    "FORWARD_PARTIAL_SENT": "Отправлено: {count}. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Исходное сообщение для пересылки не найдено",
    "FORWARD_NO_FORWARDABLE_CONTENT": "В этом сообщении пока нет содержимого для пересылки",
    "FORWARD_DESTINATION_MISSING": "Не указано назначение пересылки",
    "FORWARD_MESSAGE_PREVIEW": "Пересланное сообщение",
    "MENU_PASTE": "Вставить",
    "MENU_COPY": "Копировать",
    "MENU_REPLY": "Ответить",
    "MENU_FORWARD": "Переслать",
    "MENU_REMOVE_INVITATION": "Удалить приглашение",
    "MENU_REMOVE_FROM_LIST": "Удалить из списка",
    "MENU_GOODBYE_GUEST": "До свидания, Гость",
    "MENU_ADD_TO_LIST": "Добавить в список",
    "MENU_REJECT_INVITATION": "Отклонить приглашение",
    "MENU_FRONTEND_VERSION": "Версия фронтенда",
    "MENU_BANNER_HEADER": "Баннер - {zone}",
    "MENU_BANNER_INFO": "Информация о баннере: {title}",
    "MENU_MESSAGE_BUBBLE": "Пузырь сообщения",
    "MENU_CHAT_CANVAS_HEADER": "Полотно чата - {zone}",
    "MENU_CANVAS_INFO": "Информация о полотне",
    "MENU_CHAT_CANVAS_SUBLABEL": "Область беседы / текущая поверхность чата",
    "MENU_INPUT_AREA_HEADER": "Область ввода - {zone}",
    "MENU_INPUT_AREA_INFO": "Информация об области ввода: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Нижняя поверхность ввода и инструментов действий",
    "MENU_HEADER": "Заголовок - {zone}",
    "MENU_HEADER_INFO": "Информация о заголовке: {title}",
    "MENU_HEADER_DESCRIPTION": "Верхняя навигация и элементы управления страницей",
    "MENU_ZONE_HEADER": "Зона - {zone}",
    "MENU_ZONE_SPACE_INFO": "Информация о пространстве зоны",
    "MENU_EMPTY_LIST_SURFACE": "Пустая поверхность/список",
    "MENU_BLOCK": "Заблокировать",
    "MENU_UNBLOCK": "Разблокировать",
    "MENU_HIDE_IN_SEARCH": "Скрыть в поиске",
    "MENU_UNHIDE_IN_SEARCH": "Показать в поиске",
    "MENU_VISIBLE_IN_SEARCH": "Видимо в поиске",
    "MENU_HIDDEN_IN_SEARCH": "Скрыто в поиске",
    "MENU_VISIBLE_IN_USER_LIST": "Видимо в списке пользователей",
    "MENU_HIDDEN_IN_USER_LIST": "Скрыто в списке пользователей",
    "MENU_NOT_BLOCKED": "Не заблокирован",
    "MENU_BLOCKED": "Заблокирован",
    "MENU_FRONTEND_VERSION_LOADING": "Загрузка...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Загрузка значения для баннера из backend. Ни один вариант не помечается как активный, пока не придет ответ базы данных.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Не удалось загрузить значение backend. Надежный активный вариант не отображается.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Явное значение для баннера в базе данных: {overrideVersion}. Глобальное значение по умолчанию: {globalDefaultVersion}. Целевой пользователь должен полностью обновить или заново открыть приложение, чтобы стартовая инициализация применила его.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Явное значение для баннера не сохранено. FeV2.0.0 активен по умолчанию. Глобальное значение по умолчанию: {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Явное значение для баннера становится активным после полной перезагрузки целевого приложения",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Явное значение для баннера не сохранено; это индивидуальное состояние FeV2.0.0 по умолчанию",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Этот вариант также совпадает с текущим глобальным значением по умолчанию",
    "MENU_DELETE_PERMANENT_CONFIRM": "Удалить {target} из базы данных навсегда? Это удалит учетную запись, историю чата, зависимости и заставит пройти полный новый путь приглашения для будущего повторного входа.",
    "MENU_DELETE_PERMANENTLY": "Удалить навсегда",
    "MENU_REFRESH_PAGE": "Обновить страницу",
    "MENU_LOG_OFF": "Выйти",
    "MENU_HARD_RELOAD": "Жесткая перезагрузка",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Email (администратор)",
    "AUTH_PASSWORD_PLACEHOLDER": "Пароль",
    "AUTH_CONNECTING": "Подключение...",
    "AUTH_SIGNING_OUT": "Выход...",
    "AUTH_BACK_TO_LOGIN": "Назад ко входу",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Недопустимый ответ сервера: токен не найден.",
    "AUTH_LOGIN_FAILED": "Вход не выполнен",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Пароли не совпадают.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Пароли не совпадают!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Пароли должны совпадать точно.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Новый пароль",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Подтвердите пароль",
    "AUTH_CHANGE_PASSWORD": "Изменить пароль",
    "AUTH_SAVING_PASSWORD": "Сохранение...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Пароль успешно обновлен.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Сейчас невозможно изменить пароль.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Вы должны войти, чтобы изменить пароль.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Переключить видимость нового пароля",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Переключить видимость подтверждения пароля",
    "REGISTER_TITLE": "Завершить регистрацию",
    "REGISTER_SUBTITLE": "Задайте пароль вручную.",
    "REGISTER_CREATING_ACCOUNT": "Создание учетной записи...",
    "REGISTER_FINISH_SETUP": "Завершить настройку",
    "REGISTER_FAILED_SET_PASSWORD": "Не удалось задать пароль",
    "INVITE_EMAIL_INSTRUCTION": "Введите email приглашенного (формат: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Пригласить",
    "INVITE_EMAIL_REQUIRED": "Введите email приглашенного.",
    "INVITE_EMAIL_INVALID": "Недопустимый формат email. Используйте: user@example.com",
    "PENDING_INVITATION_TITLE": "Ожидающее приглашение",
    "PENDING_INVITATION_REMOVE_QUESTION": "Удалить это ожидающее приглашение из базы данных?",
    "PENDING_INVITATION_KEEP": "Оставить приглашение",
    "PENDING_INVITATION_REMOVAL_FAILED": "Не удалось удалить.",
    "REMOVE_FROM_LIST_TITLE": "Удалить из списка",
    "REMOVE_FROM_LIST_WARNING": "Удалить этого пользователя из обоих списков сейчас? Доступ к чату будет немедленно прекращен. Единственный путь возврата — новое приглашение.",
    "REMOVE_FROM_LIST_KEEP": "Оставить пользователя в списке",
    "REMOVE_FROM_LIST_FAILED": "Не удалось удалить из списка.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Настройки и текущий статус",
    "PERMISSION_DIALOG_ARIA": "Настройки и текущий статус",
    "PERMISSION_TRIGGER_ARIA": "Триггер всплывающего окна настроек",
    "PERMISSION_CLOSE_ARIA": "Закрыть всплывающее окно разрешений",
    "PERMISSION_LIVE_STATUS": "Текущий статус",
    "PERMISSION_SYSTEM_PERMISSION": "Системное разрешение",
    "PERMISSION_APP_PUSH": "Push приложения",
    "PERMISSION_LOCATION_PERMISSION": "Разрешение геолокации",
    "PERMISSION_APP_LOCATION": "Геолокация приложения",
    "PERMISSION_CONTROLS": "Управление разрешениями",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push-уведомления",
    "PERMISSION_LOCATION_ACCESS": "Доступ к геолокации",
    "PERMISSION_IN_APP_SETTINGS": "Настройки в приложении",
    "PERMISSION_ALERT_SOUND": "Звук оповещения",
    "PERMISSION_APP_BADGE": "Значок приложения",
    "PERMISSION_PASSWORD_SETTINGS": "Настройки пароля",
    "PERMISSION_NAVIGATION_STATUS": "Статус навигации",
    "PERMISSION_SELECTED_ZONE": "Выбранная зона",
    "PERMISSION_STAGED_CHAT_BANNER": "Подготовленный баннер чата",
    "PERMISSION_CANVAS_CONTENT": "Содержимое полотна",
    "PERMISSION_YOUR_DEVICES": "Ваши устройства ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Обновить список устройств",
    "PERMISSION_REFRESH_LIST": "Обновить список",
    "PERMISSION_NO_REGISTERED_DEVICES": "Зарегистрированные устройства не найдены.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Изменить размер всплывающего окна настроек",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Переключить push-уведомления",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Переключить доступ к геолокации",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Переключить звук оповещения",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Переключить значок приложения",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Переключить видимость профиля",
    "PERMISSION_OFF_IN_V1": "Отключено в v1",
    "PERMISSION_CHAT": "Чат",
    "PERMISSION_BANNER_LIST": "Список баннеров",
    "PERMISSION_PUSH_DISABLED_V1": "Push-уведомления отключены для выпуска v1 Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Push-уведомления включены для этого устройства.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Системные уведомления заблокированы. Нажмите, чтобы открыть помощь по настройкам.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Включите, чтобы повысить надежность доставки.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Чтобы отключить системные уведомления, откройте настройки уведомлений браузера/сайта и установите для этого сайта Блокировать.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Чтобы изменить разрешение системных уведомлений, откройте настройки уведомлений браузера/сайта и установите для этого сайта Разрешить.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Доступ к геолокации включен для сортировки LCAC по расстоянию и позиционирования на карте.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API геолокации не поддерживается в этой среде.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Доступ к геолокации заблокирован. Нажмите, чтобы открыть помощь по настройкам.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Включите, чтобы разрешить точную сортировку LCAC по расстоянию и позиционирование на карте в приложении.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Доступ к геолокации не поддерживается в этой среде.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Чтобы отключить доступ к геолокации, откройте настройки геолокации браузера/сайта и установите для этого сайта Блокировать.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Чтобы включить доступ к геолокации для сортировки по расстоянию и позиционирования на карте в приложении, откройте настройки геолокации браузера/сайта и установите для этого сайта Разрешить.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Сейчас невозможно загрузить зарегистрированные устройства.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Загрузка UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Загрузка Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Загрузка backend...",
    "RUNTIME_LOADING": "Загрузка...",
    "RUNTIME_LOADING_FROM_DATABASE": "Загрузка из базы данных...",
    "RUNTIME_BACKEND_CONNECTED": "Backend подключен",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Активен кэшированный резервный режим",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Активен резервный режим по умолчанию",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Активны резервные значения по умолчанию",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Сохранение через backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Сохранено в backend-сервисе",
    "RUNTIME_SAVE_FAILED": "Не удалось сохранить",
    "RUNTIME_LOAD_FAILED": "Не удалось загрузить",
    "RUNTIME_CONNECTED": "Подключено",
    "RUNTIME_LOGIN_REQUIRED": "Требуется вход",
    "RUNTIME_SAVED": "Сохранено",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI готов - runtime ожидает",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Защищенный backend-сервис селектора отклонил или не смог сохранить запрошенный вариант модели.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Защищенный backend-сервис селектора отклонил или не смог сохранить запрошенное изменение маршрутизации WF1.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Селектор теперь читает активную конфигурацию, маршрутизацию Qwen и разрешенные варианты из защищенного backend-сервиса.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend-сервис селектора сейчас недоступен, поэтому используется последнее кэшированное состояние селектора.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Активны значения селектора по умолчанию, потому что не удалось загрузить ни backend-состояние, ни кэшированное состояние.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Защищенный backend-сервис селектора обновил активную конфигурацию маршрутизации WF1 и обновил кэш домена runtime.",
    "FRONTEND_VERSION_TITLE": "Версия фронтенда",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Этот селектор управляет активной версией фронтенда для всех пользователей. FeV2.0.0 активен.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Этот селектор читает активную версию фронтенда из config_domain_registry. Runtime разрешается в FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend-конфигурацию версии фронтенда не удалось загрузить, поэтому закодированное значение FeV2.0.0 по умолчанию остается активным, пока стартовая инициализация снова не сможет прочитать защищенный сервис.",
    "FRONTEND_VERSION_HELPER_SAVED": "Активная версия фронтенда была сохранена в config_domain_registry. Полное обновление или следующий запуск приложения применит значение runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend-сервис управления версией фронтенда не смог сохранить запрошенную глобальную версию.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Активная версия фронтенда.",
    "CHAT_DELETE_WINDOW_TITLE": "Окно удаления чата",
    "CHAT_DELETE_HELPER": "Это значение управляет окном доступности функции «Удалить для всех» в секундах. Backend-защита меняется сразу после сохранения. Видимость пузыря меняется после полного обновления или следующего запуска приложения.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend-сервис управления удалением чата не удалось загрузить, поэтому закодированное значение по умолчанию остается активным, пока стартовая инициализация снова не сможет прочитать защищенный сервис.",
    "CHAT_DELETE_HELPER_SAVED": "Окно доступности «Удалить для всех» было сохранено в config_domain_registry. Backend-защита меняется сразу. Видимость пузыря меняется после полного обновления или следующего запуска приложения.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend-сервис управления удалением чата не смог сохранить запрошенное значение окна.",
    "CHAT_DELETE_WINDOW_LABEL": "Окно «Удалить для всех»",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} сек",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Сохраняйте значение в целых секундах. Текущее production-значение: 86400 секунд = 1 день.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Секунды окна",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Введите целое число больше или равное 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Сохранить окно удаления",
    "GUEST_BANNER_CONTROL_TITLE": "Гостевой баннер",
    "GUEST_BANNER_CONTROL_LABEL": "Гостевой QR-чат",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Показывать гостевой баннер для всех пользователей",
    "GUEST_BANNER_CONTROL_HELPER": "Управляет фиксированным гостевым баннером и сроком действия ожидающего QR-токена.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Для элементов управления гостевым баннером активен локальный резервный вариант.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Элементы управления гостевым баннером сохранены.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Не удалось сохранить элементы управления гостевым баннером.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "Отозвано {count} гостевых сеансов.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "TTL для ожидающего QR-кода (минуты)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "Текущий TTL для ожидающего QR-кода: {count} минут.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Введите положительное целое число минут.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Сохранить гостевой баннер",
    "GUEST_QR_LOADING": "Подготовка гостевого QR-кода...",
    "GUEST_QR_READY": "Отсканируйте, чтобы открыть временный гостевой чат.",
    "GUEST_QR_ALT": "QR-код гостевого чата",
    "GUEST_QR_LOAD_FAILED": "Не удалось подготовить гостевой QR-код.",
    "GUEST_SESSION_ACTIVE": "Гость подключен.",
    "GUEST_PUBLIC_TITLE": "Гостевой чат",
    "GUEST_PUBLIC_CONNECTING": "Подключение...",
    "GUEST_PUBLIC_CONNECTED": "Подключено",
    "GUEST_PUBLIC_UNAVAILABLE": "Эта гостевая ссылка недоступна.",
    "GUEST_PUBLIC_SEND_FAILED": "Не удалось отправить сообщение.",
    "UI_TEXTS_RUNTIME_TITLE": "Среда выполнения языка интерфейса",
    "UI_TEXTS_RUNTIME_BACKEND": "Среда выполнения языка интерфейса считывает данные из защищенной серверной службы. Изменения вступят в силу при следующей полной загрузке приложения.",
    "UI_TEXTS_RUNTIME_CACHED": "Серверная служба среды выполнения языка интерфейса сейчас недоступна, поэтому используются кэшированные или локальные значения по умолчанию.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "Используются стандартные языковые настройки интерфейса, так как не удалось загрузить данные с сервера или из кэша.",
    "UI_TEXTS_RUNTIME_SAVED": "Настройки языка интерфейса сохранены. Чтобы пользователи получили новые языковые настройки, требуется полное обновление страницы или следующий запуск приложения.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Защищенная серверная служба не смогла сохранить запрошенное изменение языка интерфейса.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Применение языка устройства",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Включить языки интерфейса во время выполнения",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Пользователи могут получать тексты интерфейса на сохраненном языке или языке устройства.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Для всех пользователей принудительно установлен английский язык интерфейса, язык устройства игнорируется.",
    "PROFILE_VISIBILITY_TITLE": "Видимость профиля",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Вы должны войти, чтобы управлять видимостью учетной записи.",
    "PROFILE_VISIBILITY_HELPER": "Этот переключатель обновляет только состояние видимости вашей учетной записи. Обнаруживаемость и поведение списка баннеров на этом этапе не меняются.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Сейчас не удалось загрузить видимость профиля.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Сейчас не удалось обновить видимость профиля.",
    "PROFILE_VISIBILITY_SAVED": "Видимость вашей учетной записи теперь {visibility}. Флаги обнаруживаемости на этом этапе остаются без изменений.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Публичная учетная запись",
    "PROFILE_VISIBILITY_STORED": "Сохраненная видимость",
    "WF1_MODEL_CONTROL_TITLE": "Управление моделью WF1",
    "WF1_ENABLE_TRANSLATION": "Включить перевод / pivot",
    "WF1_TRANSLATION_ACTIVE": "ИИ-перевод активен.",
    "WF1_TRANSLATION_INACTIVE": "WF1 продолжает работать, но исходный текст копируется, а pivot помечается как неактивный.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Активный runtime-слот",
    "WF1_ALLOW_SAME_LANGUAGE": "Разрешить ИИ для пар одного языка",
    "WF1_SAME_LANGUAGE_ACTIVE": "Пары одного языка следуют обычной маршрутизации WF1.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Пары одного языка обходят ИИ и сохраняют активное состояние «без pivot-языка».",
    "WF1_QWEN_ROUTING": "Маршрутизация пар Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Отмеченные ниже языки используют Qwen-Max, когда пара является либо тем же отмеченным языком, либо отмеченным языком с английским, либо двумя отмеченными неанглийскими языками. В остальных случаях активной остается выбранная основная модель.",
    "WF1_OPENROUTER_TEST_SLOT": "Тестовый слот OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Тестовый слот OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Только тест качества",
    "WF1_OPENROUTER_HELPER": "Этот слот доступен для редактирования только для временных тестов качества OpenRouter. Он не меняет рабочий путь маршрутизации пар Qwen, если только сам этот слот не станет активной моделью.",
    "WF1_LABEL": "Метка",
    "WF1_PRODUCT": "Продукт",
    "WF1_MODEL": "Модель",
    "WF1_PROVIDER_OPENROUTER": "Провайдер: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Секрет: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Тестовый слот OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max через OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Прайс-лист Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Прайс-лист OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Прайс-лист OpenRouter",
    "LANGUAGE_ENGLISH": "Английский",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Китайский (упрощенный)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Китайский (традиционный)",
    "LANGUAGE_JAPANESE": "Японский",
    "LANGUAGE_KOREAN": "Корейский",
    "LANGUAGE_PERSIAN": "Персидский",
    "LANGUAGE_TURKISH_ISTANBUL": "Турецкий (Стамбул)",
    "LANGUAGE_ARABIC": "Арабский",
    "LANGUAGE_FRENCH": "Французский",
    "LANGUAGE_GERMAN": "Немецкий",
    "LANGUAGE_SPANISH": "Испанский",
    "LANGUAGE_PORTUGUESE": "Португальский",
    "LANGUAGE_ITALIAN": "Итальянский",
    "LANGUAGE_RUSSIAN": "Русский",
    "LANGUAGE_DUTCH": "Нидерландский",
    "LANGUAGE_VIETNAMESE": "Вьетнамский",
    "LANGUAGE_INDONESIAN": "Индонезийский",
    "LANGUAGE_THAI": "Тайский",
    "LANGUAGE_MALAY": "Малайский",
    "WF1_PRICING_CUSTOM": "Цены: модель пользовательского слота - проверьте текущие цены OpenRouter",
    "WF1_SAVE_OPENROUTER_SLOT": "Сохранить слот OpenRouter",
    "WF1_PRICING_LINE": "Вход {input} - выход {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Секрет: {secret}",
    "ZONE_VISIBILITY_TITLE": "Управление видимостью зон",
    "ZONE_ENABLE": "Включить {zone}",
    "ZONE_ENABLED_NOTE": "{zone} может отображаться для разрешенных ролей после следующей загрузки приложения.",
    "ZONE_DISABLED_NOTE": "{zone} считается отсутствующей для пользователей не S_Admin после следующей загрузки приложения.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin обходит этот список ролей и всегда сохраняет доступ.",
    "ZONE_ROLE_LOCKED": "Выборы ролей временно заблокированы, пока эта зона отключена, и вернутся точно в сохраненном виде, когда зона снова будет включена.",
    "ZONE_LCAC_CONTROL": "Управление LCAC",
    "ZONE_RCAC_CONTROL": "Управление RCAC",
    "ZONE_LCAC_DESCRIPTION": "Управляет существованием левой зарезервированной зоны и ролями, которые могут ее видеть.",
    "ZONE_RCAC_DESCRIPTION": "Управляет существованием правой зарезервированной зоны и ролями, которые могут ее видеть.",
    "ZONE_VISIBILITY_BACKEND": "Стартовая инициализация видимости зон теперь читает данные из защищенного backend-сервиса. Изменения применяются при следующей загрузке приложения.",
    "ZONE_VISIBILITY_CACHED": "Backend-сервис видимости зон сейчас недоступен, поэтому активны кэшированные или локальные значения по умолчанию.",
    "ZONE_VISIBILITY_DEFAULTS": "Активны значения видимости зон по умолчанию, потому что не удалось загрузить ни backend-состояние, ни кэшированное состояние.",
    "ZONE_VISIBILITY_SAVED": "Стартовая инициализация видимости зон сохранена. Для применения в runtime требуется жесткая перезагрузка или следующая загрузка приложения.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Защищенный backend-сервис не смог сохранить запрошенное изменение видимости зоны.",
    "ROLE_MEMBER": "Участник",
    "ROLE_STAFF": "Персонал",
    "ROLE_ADMIN": "Администратор",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Включите уведомления, чтобы получать новые сообщения.",
    "MAIN_LOG_OUT": "Выйти",
    "NOTIFICATION_NEW_MESSAGE": "Новое сообщение",
    "NOTIFICATION_UNREAD_MESSAGE": "У вас есть непрочитанное сообщение.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Полный вид",
    "MEDIA_AUDIO_ATTACHMENT": "Аудиовложение",
    "MEDIA_FILE_FALLBACK": "Файл",
    "MEDIA_DOWNLOAD_READY": "Вложение готово к скачиванию",
    "MEDIA_TYPE_UNSUPPORTED": "Тип не поддерживается в полном просмотре",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Предыдущее изображение",
    "MEDIA_NEXT_IMAGE_ARIA": "Следующее изображение",
    "MEDIA_OPEN_ORIGINAL": "Открыть оригинал",
    "MEDIA_DOWNLOAD": "Скачать",
    "MEDIA_CLOSE_ARIA": "Закрыть",
    "MEDIA_PROFILE_PICTURE_ARIA": "Фото профиля {name}",
    "MEDIA_PROFILE_ALT": "Профиль {name}",
    "MEDIA_UPLOAD_FAILED": "Загрузка не удалась",
    "MEDIA_BACKEND_TOKEN_ERROR": "Ошибка backend-токена",
    "MEDIA_UPLOAD_URL_MISSING": "Критично: URL загрузки отсутствует в ответе backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Отсутствует токен аутентификации для загрузки в чат",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Запрос токена загрузки в чат не удался",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Недопустимый ответ загрузки в чат",
    "MEDIA_GCS_UPLOAD_FAILED": "Ошибка загрузки GCS",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Отсутствует имя файла или contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Отсутствует file_path",
    "BLOCK_NOTICE_TITLE": "Уведомление о постоянной блокировке",
    "BLOCK_NOTICE_MESSAGE": "Ваша учетная запись была временно приостановлена из-за нарушения политики.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Если вы считаете, что это требует дальнейшего рассмотрения, обратитесь",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "по email.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Неизвестный пользователь",
    "GENERAL_GUEST": "Гость",
    "ADVISOR_FOR_CLIENT": "Советник для {client_display_name}",
    "GUEST_FOR_CLIENT": "Гость для {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Токен и пароль обязательны",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Тело запроса должно быть JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Недопустимый или истекший токен приглашения",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Не удалось задать пароль: отсутствует сессия или пользователь",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Не удалось задать пароль во время входа",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Не удалось сгенерировать admin-токен",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Вход не удался: отсутствует сессия или пользователь",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Регистрация прошла успешно. Проверьте email для подтверждения.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Неизвестная ошибка регистрации",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Недопустимая обработка токена",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Требуется access token",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Для предварительного просмотра хеша токена требуется подсказка email из URL перенаправления",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Не удалось определить идентичность для этого токена",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Только User Zero может получить доступ к сервису выбора LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Только User Zero может получить доступ к сервису управления видимостью зон.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Только User Zero может получить доступ к сервису управления версией фронтенда.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Только User Zero может проверять версию фронтенда другого пользователя.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Только User Zero может получить доступ к сервису управления удалением чата.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Только User Zero может получить доступ к службе управления языком интерфейса во время выполнения.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Только User Zero может навсегда удалить учетную запись пользователя.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Недопустимая полезная нагрузка запроса.",
    "API_ERROR_INTERNAL_SERVER": "Внутренняя ошибка сервера",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Функция отсутствует в backend (требуется перезагрузка)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Для переходов delivered/read разрешен только DB RPC.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Пожалуйста, подождите перед отправкой следующего сообщения.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Сообщение успешно отправлено.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Сервис контактов недоступен.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Не удалось отправить сообщение.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Имя обязательно.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Email недопустим.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Сообщение обязательно.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Требуется payload селектора.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Требуется payload видимости зон.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Требуется payload версии фронтенда.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Требуется payload управления удалением чата.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Требуются данные для управления языком интерфейса во время выполнения.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Требуется идентификатор аутентифицированного пользователя.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Требуется идентификатор аутентифицированного пользователя-наблюдателя.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Требуется идентификатор аутентифицированного пользователя-актора.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id обязателен.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id обязателен.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Список owner_user_ids обязателен.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email обязателен.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by обязателен.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime поиска отключен глобальной версией фронтенда.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Вам не разрешено отменять это ожидающее приглашение.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Это приглашение больше нельзя отменить, потому что пользователь уже зарегистрирован.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Ожидающее приглашение не найдено.",
    "INVITE_REPLY_ALREADY_MEMBER": "Поздравляем, ваш друг ({invitee_email}) уже зарегистрирован в этом приложении и является участником этой рабочей области.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Для {invitee_email} ожидает приглашение, но повторное письмо не удалось запустить. Проверьте почтовые логи.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Запись приглашения была создана для {invitee_email}, но доставку email не удалось подтвердить. Попробуйте позже или проверьте почтовые логи.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Не удалось создать запись приглашения. Попробуйте позже.",
    "INVITE_REPLY_SYSTEM_ERROR": "Системная ошибка во время процесса приглашения: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Ошибка конфигурации backend: отсутствуют учетные данные Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Ошибка конфигурации backend: недопустимый URL Supabase",
    "CHAT_ERROR_ACCESS_DENIED": "Доступ запрещен",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Содержимое текстовых сообщений не может быть пустым",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Не удалось определить ID беседы",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Контекст аутентификации RPC отсутствует",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC вернул недопустимый payload сообщения",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Вставка не удалась, данные не возвращены",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations должен быть списком",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Недопустимый payload операции",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type не поддерживается",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id обязателен",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Сообщение не найдено",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Удаление разрешено только для вашего собственного сообщения",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Функция «Удалить для всех» больше недоступна для этого сообщения",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Не удалось удалить для всех",
    "API_ERROR_SERVER_CONFIGURATION": "Ошибка конфигурации сервера",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Отсутствует секретный заголовок webhook",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Неавторизованный источник webhook",
    "API_ERROR_BACKEND_CONFIGURATION": "Ошибка конфигурации backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Ошибка атрибута модуля: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Сбой перед удалением приглашения при удалении ожидающего auth-пользователя.",
    "CHAT_ERROR_DB": "Ошибка БД: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "PERMISSION_MIC_PERMISSION": "",
    "PERMISSION_MIC_ACCESS": "",
    "PERMISSION_TOGGLE_MIC_ARIA": "",
    "PERMISSION_MIC_ON_TOOLTIP": "",
    "PERMISSION_MIC_ENABLE_TOOLTIP": "",
    "PERMISSION_MIC_BLOCKED_TOOLTIP": "",
    "PERMISSION_MIC_DISABLE_HELP": "",
    "PERMISSION_MIC_BLOCKED_HELP": "",
    "LIVE_CONV_MIC_PROMPT_TITLE": "",
    "LIVE_CONV_MIC_PROMPT_BODY": "",
    "LIVE_CONV_MIC_PROMPT_ALLOW": "",
    "LIVE_CONV_MIC_PROMPT_CANCEL": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
