# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/sk.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Hlavné",
    "APP_TITLE": "AI platforma OTMEGA",
    "APP_SUBTITLE": "AI poradca",
    "CHAT_PLACEHOLDER": "Napíšte svoju správu...",
    "CHAT_SEND_BUTTON": "Odoslať",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Poradca sa môže mýliť, preto si informácie overte.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Nový chat",
    "ICON_HISTORY": "História",
    "ICON_TEMPLATES": "Šablóny",
    "ICON_SETTINGS": "Nastavenia",
    "ICON_USER_PROFILE": "Profil používateľa",
    "ICON_QUICK_ACTIONS": "Rýchle akcie",
    "ICON_PINNED": "Pripnuté",
    "ICON_GALLERY": "Galéria",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Nainštalovať aplikáciu",
    "PWA_ANDROID_MSG": "Nainštalujte si túto aplikáciu do svojho zariadenia pre lepší zážitok a offline prístup.",
    "PWA_IOS_MSG": "Ak chcete túto aplikáciu nainštalovať na iPhone/iPad:\n1. Ťuknite dole na tlačidlo Zdieľať\n2. Vyberte 'Pridať na plochu'",
    "PWA_BTN_INSTALL": "Nainštalovať",
    "PWA_BTN_LATER": "Možno neskôr",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Prihláste sa do siete poradcov",
    "AUTH_HEADER_SIGNUP": "Vytvorte si jednotný účet",
    "AUTH_HEADER_LOGIN_NETWORK": "Prihláste sa do siete poradcov",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Vytvorte si jednotný účet",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Prihlásiť sa",
    "AUTH_BUTTON_SIGNUP": "Vytvoriť účet",
    "AUTH_BUTTON_GOOGLE": "Pokračovať cez Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Zabudnuté heslo",
    "AUTH_BUTTON_SEND_RESET_LINK": "Odoslať odkaz na resetovanie",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Nemáte účet? Zaregistrujte sa",
    "AUTH_PROMPT_LOGIN": "Už máte účet? Prihláste sa",
    "AUTH_HELPER_TEXT_SIGNUP": "Vytvárate jednotný účet, ktorý môžete používať na prístup ku všetkým poradcom na tejto platforme.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Vytvárate jednotný účet, ktorý môžete používať na prístup ku všetkým poradcom na tejto platforme.",
    "AUTH_HELPER_TEXT_LOGIN": "Použite rovnaký účet (e-mail/heslo alebo Google), ktorý ste použili pre iných poradcov v tejto sieti.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Použite rovnaký účet (e-mail/heslo alebo Google), ktorý ste použili pre iných poradcov v tejto sieti.",
    "AUTH_FORGOT_PASSWORD_LINK": "Zabudli ste heslo?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Resetovať heslo",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Zadajte svoju e-mailovú adresu a pošleme vám odkaz na resetovanie hesla.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-mail",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Prihlasovanie...",
    "AUTH_STATUS_LOADING_SIGNUP": "Vytváranie účtu...",
    "AUTH_STATUS_LOADING_RESET": "Odosielanie odkazu na resetovanie...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Prihlásenie bolo úspešné! Znovu sa načítava...",
    "AUTH_STATUS_SUCCESS_RESET": "Odkaz na resetovanie bol úspešne odoslaný. Skontrolujte si e-mail.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Odkaz na resetovanie hesla bol úspešne odoslaný. Skontrolujte si e-mail.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Neplatný e-mail alebo heslo.",
    "AUTH_ERROR_EMAIL_EXISTS": "Účet s týmto e-mailom už existuje v sieti poradcov.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Účet s týmto e-mailom už existuje. Prihláste sa. Aktuálne ste členom:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Účet s týmto e-mailom už existuje v sieti poradcov. Zatvorte toto okno a použite sekciu 'Login' s rovnakým e-mailom a vaším predchádzajúcim heslom.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Aktuálne ste členom:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-mail a heslo sú povinné.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Účet bol vytvorený, ale nepodarilo sa nastaviť členstvo. Kontaktujte podporu.",
    "AUTH_ERROR_DEFAULT": "Vyskytla sa chyba. Skúste to prosím znova.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "",
    "AUTH_FORGOT_PASSWORD_ERROR": "Nepodarilo sa odoslať odkaz na resetovanie. Skúste to prosím znova.",
    "INVITE_REPLY_EMAIL_SENT": "E-mail s pozvánkou Collabra bol odoslaný vášmu priateľovi na adresu {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "E-mail s pozvánkou Collabra bol znova odoslaný vášmu priateľovi na adresu {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Zobraziť heslo",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Skryť heslo",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Zrušiť",
    "GENERAL_CLOSE": "Zavrieť",
    "GENERAL_SEND": "Odoslať",
    "GENERAL_SEARCH": "Hľadať",
    "GENERAL_RESET": "Resetovať",
    "GENERAL_ENABLE": "Povoliť",
    "GENERAL_LOADING": "Načítava sa...",
    "GENERAL_DELETE": "Odstrániť",
    "GENERAL_DELETING": "Odstraňuje sa...",
    "GENERAL_SAVE_PASSWORD": "Uložiť heslo",
    "AUTH_REMEMBER_EMAIL_LABEL": "Zapamätať e-mail",
    "GENERAL_SAVING": "Ukladá sa...",
    "GENERAL_SENDING": "Odosiela sa...",
    "GENERAL_REMOVING": "Odstraňuje sa...",
    "GENERAL_CONFIRM_REMOVAL": "Potvrdiť odstránenie",
    "GENERAL_EMPTY": "Prázdne",
    "GENERAL_UNAVAILABLE": "Nedostupné",
    "GENERAL_ENABLED": "Povolené",
    "GENERAL_DISABLED": "Zakázané",
    "GENERAL_GRANTED": "Udelené",
    "GENERAL_DENIED": "Zamietnuté",
    "GENERAL_DEFAULT": "Predvolené",
    "GENERAL_UNSUPPORTED": "Nepodporované",
    "GENERAL_PUBLIC": "Verejné",
    "GENERAL_PRIVATE": "Súkromné",
    "GENERAL_USERNAME": "Používateľské meno",
    "GENERAL_EMAIL": "E-mail",
    "GENERAL_YOU": "Vy",
    "GENERAL_USER": "Používateľ",
    "GENERAL_UNKNOWN": "Neznáme",
    "GENERAL_VISITOR": "Návštevník",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Neznámy banner",
    "GENERAL_ADVISOR_BANNER": "Banner poradcu",
    "GENERAL_NOT_AVAILABLE": "N/A",
    "GENERAL_NOT_SELECTED": "Nevybrané",
    "GENERAL_NO_EMAIL_FOUND": "Nenašiel sa žiadny e-mail",
    "GENERAL_USER_ZERO_ONLY": "Iba User Zero",
    "GENERAL_CONNECTION_STATE": "Stav pripojenia",
    "GENERAL_DISPLAY_ONLY": "Iba zobrazenie",
    "GENERAL_TEXTAREA": "Textové pole",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Chat (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Rýchle akcie (RCAC)",
    "HEADER_CHANGE_STATUS": "Zmeniť stav",
    "HEADER_OT_COIN_BALANCE": "Zostátok OT Coin",
    "HEADER_ALT_USER": "Používateľ",
    "STATUS_BUSY": "Zaneprázdnený",
    "STATUS_AWAY": "Preč",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Neviditeľný",
    "NETWORK_CHECKING_CONNECTION": "Kontrola pripojenia...",
    "NETWORK_ONLINE_LATENCY": "Online (latencia: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Sieť: dobrá (ťuknite pre ping)",
    "CHAT_TARGET_ALT": "Cieľ chatu",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Hľadať...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Otvoriť profilovú fotografiu používateľa {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Vstup správy",
    "CHAT_TOGGLE_VIEW_ARIA": "Prepnúť zobrazenie",
    "CHAT_ADD_USER_ARIA": "Pridať používateľa",
    "CHAT_ATTACH_ARIA": "Priložiť",
    "CHAT_MIC_ARIA": "Mikrofón",
    "CHAT_SEND_ARIA": "Odoslať",
    "CHAT_SEARCH_ARIA": "Hľadať",
    "CHAT_OPEN_SEARCH_ARIA": "Otvoriť vyhľadávanie",
    "CHAT_CLOSE_SEARCH_ARIA": "Zavrieť vyhľadávanie",
    "CHAT_ATTACHMENT_ALT": "Príloha",
    "CHAT_PREVIEW_ALT": "Náhľad",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Odstrániť prílohu",
    "CHAT_REPLYING_TO": "Odpoveď na",
    "CHAT_CANCEL_REPLY_ARIA": "Zrušiť odpoveď",
    "CHAT_UPLOADING": "Nahráva sa...",
    "CHAT_LOADING_CHATS": "Načítavajú sa chaty...",
    "CHAT_SEND_FAILED": "Odoslanie zlyhalo",
    "CHAT_SEND_FAILED_RETRY": "Odoslanie zlyhalo. Skúste to znova.",
    "CHAT_RETRY": "Skúsiť znova",
    "CHAT_EDITED": "upravené",
    "CHAT_TYPING": "Píše",
    "CHAT_LOADING": "Načítava sa",
    "CHAT_PENDING_INVITATION": "Čakajúca pozvánka",
    "CHAT_PENDING_INVITATION_MIN": "{count} min čakajúca pozvánka",
    "CHAT_PENDING_INVITATION_HR": "{count} h čakajúca pozvánka",
    "CHAT_PENDING_INVITATION_DAY": "{count} d čakajúca pozvánka",
    "CHAT_WAITING_FOR_YOU": "{label} - Čaká sa na vás",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Čaká na prijatie",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Prístup k mikrofónu bol zamietnutý.",
    "CHAT_UPLOAD_FAILED": "Nahrávanie zlyhalo: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Nahrávanie vyžaduje internetové pripojenie. Skúste to prosím znova, keď budete online.",
    "CHAT_ERROR_AUTH": "Chyba overenia",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Chýba názov súboru alebo content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Chýba conversation_id alebo target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Chýba conversation_id pre nahrávanie mimo avatara",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Neplatný file_path avatara",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Servisný klient Supabase je nedostupný",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Potvrdenie prečítania avatara je platné iba v kontexte chatu s poradcom",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Správa toku avatara sa nenašla alebo nie je vhodná na potvrdenie prečítania",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Nepodarilo sa dokončiť správu avatara ako prečítanú",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 príloha",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} príloh",
    "CHAT_VOICE_NOTE": "Hlasová poznámka",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chat je nedostupný. Tento používateľ vás zablokoval.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chat je nedostupný. Zablokovali ste tohto používateľa.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Prístup k účtu je blokovaný zásadami.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chat je nedostupný. Tento účet je definitívne zablokovaný používateľom User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chat je nedostupný. Vzájomné blokovanie je aktívne.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chat je nedostupný z dôvodu zásad blokovania.",
    "MESSAGE_PREVIEW_PHOTO": "Fotografia",
    "MESSAGE_PREVIEW_VOICE": "Hlasová správa",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Súbor",
    "MESSAGE_PREVIEW_MESSAGE": "Správa",
    "MESSAGE_PREVIEW_SYSTEM": "Systémová správa",
    "MESSAGE_PREVIEW_NEW": "Nová správa",
    "MESSAGE_UNKNOWN_FILE": "Neznámy súbor",
    "MESSAGE_AUDIO_ATTACHMENT": "Zvuková príloha",
    "MESSAGE_FILE_ATTACHMENT": "Príloha",
    "BANNER_INVITED_BY": "pozval(a) {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Výsledky vyhľadávanie",
    "SEARCH_QUERY_LABEL": "Dotaz:",
    "SEARCH_LOADING_VISIBILITY": "Načítavanie viditeľnosťi vyhľadávanie...",
    "SEARCH_NO_RESULTS": "V aktuálnym rozsahu vyhľadávanie sa nenašiel žiadny výsledek.",
    "SHARE_WITH_COLLABRA": "Sdílet s Collabra",
    "SHARE_SEND_TO": "Odoslať komu",
    "SHARE_SELECT_ONE_BANNER": "Vyberte jeden banner",
    "SHARE_BANNER_LIST_ARIA": "Zoznam bannerov",
    "SHARE_NO_MATCHING_BANNER": "Žiadny odpovídající banner",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Pridať komentár...",
    "SHARE_RECENT_CHATS": "Nedávné chaty",
    "SHARE_LEFT_LIST": "Ľavý zoznam",
    "SHARE_RIGHT_LIST": "Pravý zoznam",
    "SHARE_UNTITLED_BANNER": "Banner bez názvu",
    "SHARE_SHARED_CONTENT": "Sdílený obsah",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Zdieľaný obsah sa nepodarilo otvoriť.",
    "SHARE_OPEN_BANNER_FAILED": "Vybraný banner sa nepodarilo otvoriť.",
    "SHARE_ONE_PHOTO_SELECTED": "Vybranýa 1 fotografia",
    "SHARE_MANY_PHOTOS_SELECTED": "Vybranýo {count} fotografií",
    "SHARE_ONE_FILE_SELECTED": "Vybraný 1 súbor",
    "SHARE_MANY_FILES_SELECTED": "Vybraných {count} súborov",
    "FORWARD_MESSAGE_TITLE": "Preposlať správu",
    "FORWARD_SELECT_RECIPIENTS": "Vyberte príjemcov",
    "FORWARD_NO_OTHER_BANNER": "Nie je dostupný žiadny iný banner.",
    "FORWARD_SEND_TO_COUNT": "Odoslať pro {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Vyberte alespoň jeden banner.",
    "FORWARD_FAILED_DEFAULT": "Preposlanie zlyhalo. Skúste to prosím znova.",
    "FORWARD_PARTIAL_SENT": "Odesláno {count}. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Zdrojová správa na preposlanie sa nenašla",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Táto správa zatiaľ nemá obsah, ktorý sa dá preposlať",
    "FORWARD_DESTINATION_MISSING": "Chýba cieľ preposlania",
    "FORWARD_MESSAGE_PREVIEW": "Preposlaná správa",
    "MENU_PASTE": "Vložit",
    "MENU_COPY": "Kopírovat",
    "MENU_REPLY": "Odpovedať",
    "MENU_FORWARD": "Preposlať",
    "MENU_REMOVE_INVITATION": "Odstrániť pozvánku",
    "MENU_REMOVE_FROM_LIST": "Odstrániť zo zoznamu",
    "MENU_GOODBYE_GUEST": "",
    "MENU_ADD_TO_LIST": "Pridať do zoznamu",
    "MENU_REJECT_INVITATION": "Odmítnout pozvánku",
    "MENU_FRONTEND_VERSION": "Verze frontendu",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Informace o banneru: {title}",
    "MENU_MESSAGE_BUBBLE": "Bublina správy",
    "MENU_CHAT_CANVAS_HEADER": "Plátno chatu - {zone}",
    "MENU_CANVAS_INFO": "Informácie o plátne",
    "MENU_CHAT_CANVAS_SUBLABEL": "Oblasť konverzácie / aktuálny plocha chatu",
    "MENU_INPUT_AREA_HEADER": "Vstupní oblasť - {zone}",
    "MENU_INPUT_AREA_INFO": "Informace o vstupní oblasťi: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Spodní plocha pro psaní a akční nástroje",
    "MENU_HEADER": "Hlavička - {zone}",
    "MENU_HEADER_INFO": "Informace o hlavička: {title}",
    "MENU_HEADER_DESCRIPTION": "Horní navigace a ovládací prvky stránky",
    "MENU_ZONE_HEADER": "Zóna - {zone}",
    "MENU_ZONE_SPACE_INFO": "Informace o priestoru zóny",
    "MENU_EMPTY_LIST_SURFACE": "Prázdná/zoznamová plocha",
    "MENU_BLOCK": "Blokovať",
    "MENU_UNBLOCK": "Odblokovať",
    "MENU_HIDE_IN_SEARCH": "Skryť vo vyhľadávaní",
    "MENU_UNHIDE_IN_SEARCH": "Zobraziť vo vyhľadávaní",
    "MENU_VISIBLE_IN_SEARCH": "Viditeľné vo vyhľadávaní",
    "MENU_HIDDEN_IN_SEARCH": "Skryté vo vyhľadávaní",
    "MENU_VISIBLE_IN_USER_LIST": "Viditeľné v zozname používateľov",
    "MENU_HIDDEN_IN_USER_LIST": "Skryté v zozname používateľov",
    "MENU_NOT_BLOCKED": "Nie je blokované",
    "MENU_BLOCKED": "Blokované",
    "MENU_FRONTEND_VERSION_LOADING": "Načítavanie...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Načítava sa hodnota pre banner z backendu. Kým nepríde odpoveď databázy, žiadna možnosť nie je označená ako aktívna.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Hodnotu z backendu sa nepodarilo načítať. Nezobrazuje sa žiadna dôveryhodná aktívna možnosť.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Explicitná databázová hodnota pre banner je {overrideVersion}. Globálna predvolená hodnota je {globalDefaultVersion}. Cieľový používateľ musí aplikáciu úplne obnoviť alebo znova otvoriť, aby ju spúšťací bootstrap použil.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Nie je uložená žiadna explicitná databázová hodnota pre banner. FeV2.0.0 je predvolene aktívny. Globálna predvolená hodnota je {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Explicitná databázová hodnota pre banner sa aktivuje po úplnom opätovnom načítaní cieľovej aplikácie",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Nie je uložená žiadna explicitná hodnota pre banner; toto je predvolený individuálny stav FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Táto možnosť sa tiež rovná aktuálnej globálnej predvolenej hodnote",
    "MENU_DELETE_PERMANENT_CONFIRM": "Natrvalo odstrániť {target} z databázy? Tým sa odstráni účet, história chatu, závislosti a pre budúci opätovný vstup sa vynúti úplne nová cesta pozvánky.",
    "MENU_DELETE_PERMANENTLY": "Natrvalo odstrániť",
    "MENU_REFRESH_PAGE": "Obnoviť stránku",
    "MENU_LOG_OFF": "Odhlásiť sa",
    "MENU_HARD_RELOAD": "Tvrdé obnovenie",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-mail (admin používateľ)",
    "AUTH_PASSWORD_PLACEHOLDER": "Heslo",
    "AUTH_CONNECTING": "Pripájanie...",
    "AUTH_SIGNING_OUT": "Odhlasovanie...",
    "AUTH_BACK_TO_LOGIN": "Späť na prihlásenie",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Neplatná odpoveď servera: nenašiel sa žiadny token.",
    "AUTH_LOGIN_FAILED": "Prihlásenie zlyhalo",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Heslá sa nezhodujú.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Heslá sa nezhodujú!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Heslá sa musia presne zhodovať.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nové heslo",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Potvrdiť heslo",
    "AUTH_CHANGE_PASSWORD": "Zmeniť heslo",
    "AUTH_SAVING_PASSWORD": "Ukladanie...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Heslo bolo úspešne aktualizované.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Heslo teraz nie je možné zmeniť.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Na zmenu hesla musíte byť prihlásený.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Prepnúť viditeľnosť nového hesla",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Prepnúť viditeľnosť potvrdenia hesla",
    "REGISTER_TITLE": "Dokončiť registráciu",
    "REGISTER_SUBTITLE": "Nastavte prosím svoje heslo ručne.",
    "REGISTER_CREATING_ACCOUNT": "Vytváranie účtu...",
    "REGISTER_FINISH_SETUP": "Dokončiť nastavenie",
    "REGISTER_FAILED_SET_PASSWORD": "Nepodarilo sa nastaviť heslo",
    "INVITE_EMAIL_INSTRUCTION": "Zadajte e-mail pozvaného (formát: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Pozvať",
    "INVITE_EMAIL_REQUIRED": "Zadajte prosím e-mail pozvaného.",
    "INVITE_EMAIL_INVALID": "Neplatný formát e-mailu. Použite: user@example.com",
    "PENDING_INVITATION_TITLE": "Čakajúca pozvánka",
    "PENDING_INVITATION_REMOVE_QUESTION": "Odstrániť túto čakajúcu pozvánku z databázy?",
    "PENDING_INVITATION_KEEP": "Ponechať pozvánku",
    "PENDING_INVITATION_REMOVAL_FAILED": "Odstránenie zlyhalo.",
    "REMOVE_FROM_LIST_TITLE": "Odstrániť zo zoznamu",
    "REMOVE_FROM_LIST_WARNING": "Odstrániť teraz tohto používateľa z oboch zoznamov? Prístup k chatu bude okamžite prerušený. Jedinou cestou späť je nová pozvánka.",
    "REMOVE_FROM_LIST_KEEP": "Ponechať používateľa v zozname",
    "REMOVE_FROM_LIST_FAILED": "Odstránenie zo zoznamu zlyhalo.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Nastavenia a živý stav",
    "PERMISSION_DIALOG_ARIA": "Nastavenia a živý stav",
    "PERMISSION_TRIGGER_ARIA": "Spúšťač vyskakovacieho okna nastavení",
    "PERMISSION_CLOSE_ARIA": "Zavrieť vyskakovacie okno povolení",
    "PERMISSION_LIVE_STATUS": "Živý stav",
    "PERMISSION_SYSTEM_PERMISSION": "Systémové povolenie",
    "PERMISSION_APP_PUSH": "Push aplikácie",
    "PERMISSION_LOCATION_PERMISSION": "Povolenie k poloze",
    "PERMISSION_APP_LOCATION": "Poloha aplikácie",
    "PERMISSION_CONTROLS": "Ovládacie prvky povolení",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push oznámenia",
    "PERMISSION_LOCATION_ACCESS": "Prístup k poloze",
    "PERMISSION_IN_APP_SETTINGS": "Nastavenia v aplikácii",
    "PERMISSION_ALERT_SOUND": "Zvuk upozornenie",
    "PERMISSION_APP_BADGE": "Odznak aplikácie",
    "PERMISSION_PASSWORD_SETTINGS": "Nastavenia hesla",
    "PERMISSION_NAVIGATION_STATUS": "Stav navigace",
    "PERMISSION_SELECTED_ZONE": "Vybraná zóna",
    "PERMISSION_STAGED_CHAT_BANNER": "Pripravený chatový banner",
    "PERMISSION_CANVAS_CONTENT": "Obsah plátna",
    "PERMISSION_YOUR_DEVICES": "Vaše zariadenie ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Obnoviť zoznam zariadenie",
    "PERMISSION_REFRESH_LIST": "Obnoviť zoznam",
    "PERMISSION_NO_REGISTERED_DEVICES": "Nenašlo sa žiadna registrovaná zariadenie.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Zmeniť velikost vyskakovacího okna nastavenia",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Prepnúť push oznámenia",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Prepnúť prístup k poloze",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Prepnúť zvuk upozornenie",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Prepnúť odznak aplikácie",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Prepnúť viditeľnosť profilu",
    "PERMISSION_OFF_IN_V1": "Vypnuto ve v1",
    "PERMISSION_CHAT": "Chat",
    "PERMISSION_BANNER_LIST": "Zoznam bannerov",
    "PERMISSION_PUSH_DISABLED_V1": "Push oznámenia sú pro vydání v1 Google Play zakázanýa.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Push oznámenia sú pro toto zariadenie zapnutá.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Systémové oznámenia sú blokované. Ťuknutím otvoríte pomoc k nastaveniam.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Zapnite pre zlepšenie spoľahlivosti doručovania.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Chcete-li zakázat systémová oznámenia, otvorte nastavenia oznámenia prehliadače/webu a nastavte tento web na Blokovat.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Chcete-li zmeniť povolenie systémových oznámenia, otvorte nastavenia oznámenia prehliadače/webu a nastavte tento web na Povoliť.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Prístup k polohe je zapnutý pre triedenie LCAC podľa vzdialenosti a umiestnenie na mape.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API polohy nie je v tomto prostredí podporované.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Prístup k polohe je blokovaný. Ťuknutím otvoríte pomoc k nastaveniam.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Zapnite pre presné triedenie LCAC podľa vzdialenosti a umiestnenie na mape v aplikácii.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Prístup k polohe nie je v tomto prostredí podporovaný.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Chcete-li zakázat prístup k poloze, otvorte nastavenia polohy prehliadače/webu a nastavte tento web na Blokovat.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Ak chcete povoliť prístup k polohe pre triedenie podľa vzdialenosti a umiestnenie na mape v aplikácii, otvorte nastavenia polohy prehliadača/webu a nastavte tento web na Povoliť.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Registrované zariadenia sa teraz nepodarilo načítať.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Načítavanie UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Načítavanie Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Načítavanie backendu...",
    "RUNTIME_LOADING": "Načítavanie...",
    "RUNTIME_LOADING_FROM_DATABASE": "Načítavanie z databázy...",
    "RUNTIME_BACKEND_CONNECTED": "Backend pripojený",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Aktívny záložní režim z cache",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Aktívny predvolené záložní režim",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Aktívny predvolené záložní hodnoty",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Ukladanie cez backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Uloženo ve službe backendu",
    "RUNTIME_SAVE_FAILED": "Uloženie zlyhalo",
    "RUNTIME_LOAD_FAILED": "Načítanie zlyhalo",
    "RUNTIME_CONNECTED": "Pripojené",
    "RUNTIME_LOGIN_REQUIRED": "Povinné prihlásenie",
    "RUNTIME_SAVED": "Uloženo",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI pripravené - runtime čaká",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Chránená backendová služba selektora odmietla alebo nemohla uložiť požadovanú možnosť modelu.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Chránená backendová služba selektora odmietla alebo nemohla uložiť požadovanú zmenu smerovania WF1.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selektor teraz číta aktívnu konfiguráciu, smerovanie Qwen a povolené možnosťi z chránenej backendovej služby.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backendová služba selektora je práve nedostupná, preto sa používa posledný stav selektora z cache.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Predvolené hodnoty selektora sú aktívne, pretože nebolo možné načítať žiadny backendový ani uložený stav selektora.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Chránená backendová služba selektora aktualizovala aktívnu konfiguráciu smerovania WF1 a obnovila cache runtime domény.",
    "FRONTEND_VERSION_TITLE": "Verze frontendu",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Tento selektor riadi aktívnu verziu frontendu pre všetkých používateľov. FeV2.0.0 je aktívny.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Tento selektor číta aktívnu verziu frontendu z config_domain_registry. Runtime sa vyhodnotí ako FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Konfiguráciu verzie frontendu z backendu sa nepodarilo načítať, preto zostáva aktívna zakódovaná predvolená hodnota FeV2.0.0, kým spúšťací bootstrap znova neprečíta chránenú službu.",
    "FRONTEND_VERSION_HELPER_SAVED": "Aktívna verzia frontendu bola uložená v config_domain_registry. Úplné obnovenie alebo ďalšie načítanie aplikácie použije runtime hodnotu.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backendová služba riadenia verzie frontendu nemohla uložiť požadovanú globálnu verziu.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktívny verze frontendu.",
    "CHAT_DELETE_WINDOW_TITLE": "Okno mazání chatu",
    "CHAT_DELETE_HELPER": "Táto hodnota riadi okno dostupnosti funkcie Odstrániť pre všetkých v sekundách. Backendová kontrola sa zmení okamžite po uložení. Viditeľnosť bubliny sa zmení po úplnom obnovení alebo pri ďalšom načítaní aplikácie.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backendovú službu riadenia mazania chatu sa nepodarilo načítať, preto zostáva aktívna zakódovaná predvolená hodnota, kým spúšťací bootstrap znova neprečíta chránenú službu.",
    "CHAT_DELETE_HELPER_SAVED": "Okno dostupnosti funkcie Odstrániť pre všetkých bolo uložené v config_domain_registry. Backendová kontrola sa zmení okamžite. Viditeľnosť bubliny sa zmení po úplnom obnovení alebo pri ďalšom načítaní aplikácie.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backendová služba riadenia mazania chatu nemohla uložiť požadovanú hodnotu okna.",
    "CHAT_DELETE_WINDOW_LABEL": "Okno Odstrániť pro všechny",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} s",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Uložte hodnotu v celých sekundách. Aktuálny produkční hodnota je 86400 sekund = 1 den.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Sekundy okna",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Zadajte celé číslo väčšie alebo rovné 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Uložiť okno mazání",
    "GUEST_BANNER_CONTROL_TITLE": "",
    "GUEST_BANNER_CONTROL_LABEL": "",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "",
    "GUEST_BANNER_CONTROL_HELPER": "",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "",
    "GUEST_BANNER_PENDING_TTL_INVALID": "",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "",
    "GUEST_QR_LOADING": "",
    "GUEST_QR_READY": "",
    "GUEST_QR_ALT": "",
    "GUEST_QR_LOAD_FAILED": "",
    "GUEST_SESSION_ACTIVE": "",
    "GUEST_PUBLIC_TITLE": "",
    "GUEST_PUBLIC_CONNECTING": "",
    "GUEST_PUBLIC_CONNECTED": "",
    "GUEST_PUBLIC_UNAVAILABLE": "",
    "GUEST_PUBLIC_SEND_FAILED": "",
    "UI_TEXTS_RUNTIME_TITLE": "",
    "UI_TEXTS_RUNTIME_BACKEND": "",
    "UI_TEXTS_RUNTIME_CACHED": "",
    "UI_TEXTS_RUNTIME_DEFAULTS": "",
    "UI_TEXTS_RUNTIME_SAVED": "",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "",
    "PROFILE_VISIBILITY_TITLE": "Viditeľnosť profilu",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Pro správu viditeľnosťi účtu musíte být prihlásení.",
    "PROFILE_VISIBILITY_HELPER": "Tento prepínač aktualizuje iba stav viditeľnosti vášho účtu. Dohľadateľnosť a správanie zoznamu bannerov zostávajú v tejto fáze bez zmeny.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Viditeľnosť profilu sa teraz nepodarilo načítať.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Viditeľnosť profilu sa teraz nepodarilo aktualizovať.",
    "PROFILE_VISIBILITY_SAVED": "Viditeľnosť vášho účtu je teraz {visibility}. Príznaky dohľadateľnosti zostávajú v tejto fáze bez zmeny.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Verejný účet",
    "PROFILE_VISIBILITY_STORED": "Uložená viditeľnosť",
    "WF1_MODEL_CONTROL_TITLE": "Řízení modelu WF1",
    "WF1_ENABLE_TRANSLATION": "Povoliť preklad / pivot",
    "WF1_TRANSLATION_ACTIVE": "AI preklad je aktívny.",
    "WF1_TRANSLATION_INACTIVE": "WF1 beží ďalej, ale zdrojový text sa skopíruje a pivot sa označí ako neaktívny.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktívny runtime slot",
    "WF1_ALLOW_SAME_LANGUAGE": "Povoliť AI pro páry rovnakého jazyka",
    "WF1_SAME_LANGUAGE_ACTIVE": "Páry rovnakého jazyka používajú bežné smerovanie WF1.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Páry rovnakého jazyka obchádzajú AI a ukladajú stav Žiadny aktívny pivot jazyk.",
    "WF1_QWEN_ROUTING": "Smerovanie párov Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Nižšie zaškrtnuté jazyky používajú Qwen-Max, keď je pár buď rovnaký zaškrtnutý jazyk, zaškrtnutý jazyk s angličtinou, alebo dva zaškrtnuté neanglické jazyky. Inak zostáva aktívny vybraný primárny model.",
    "WF1_OPENROUTER_TEST_SLOT": "Testovací slot OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Testovací slot OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Iba test kvality",
    "WF1_OPENROUTER_HELPER": "Tento slot je možné upravovať iba pre dočasné testy kvality OpenRouter. Nemení prevádzkovú cestu smerovania párov Qwen, pokiaľ sa tento slot sám nestane aktívnym modelom.",
    "WF1_LABEL": "Štítek",
    "WF1_PRODUCT": "Produkt",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Poskytovatel: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Tajný klíč: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Testovací slot OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max cez OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Ceníková cena Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Ceníková cena OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Ceníková cena OpenRouter",
    "LANGUAGE_ENGLISH": "Angličtina",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Čínština (zjednodušená)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Čínština (tradičná)",
    "LANGUAGE_JAPANESE": "Japončina",
    "LANGUAGE_KOREAN": "Kórejčina",
    "LANGUAGE_PERSIAN": "Perzština",
    "LANGUAGE_TURKISH_ISTANBUL": "Turečtina (Istanbul)",
    "LANGUAGE_ARABIC": "Arabčina",
    "LANGUAGE_FRENCH": "Francúzština",
    "LANGUAGE_GERMAN": "Nemčina",
    "LANGUAGE_SPANISH": "Španielčina",
    "LANGUAGE_PORTUGUESE": "Portugalčina",
    "LANGUAGE_ITALIAN": "Taliančina",
    "LANGUAGE_RUSSIAN": "Ruština",
    "LANGUAGE_DUTCH": "Holandčina",
    "LANGUAGE_VIETNAMESE": "Vietnamčina",
    "LANGUAGE_INDONESIAN": "Indonézština",
    "LANGUAGE_THAI": "Thajčina",
    "LANGUAGE_MALAY": "Malajčina",
    "WF1_PRICING_CUSTOM": "Ceny: vlastný model slotu - zkontrolujte aktuálny ceny OpenRouter",
    "WF1_SAVE_OPENROUTER_SLOT": "Uložiť slot OpenRouter",
    "WF1_PRICING_LINE": "Vstup {input} - Výstup {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Tajný klíč: {secret}",
    "ZONE_VISIBILITY_TITLE": "Řízení viditeľnosťi zón",
    "ZONE_ENABLE": "Povoliť {zone}",
    "ZONE_ENABLED_NOTE": "{zone} sa môže zobraziť povoleným rolám po ďalšom načítaní aplikácie.",
    "ZONE_DISABLED_NOTE": "{zone} sa po ďalšom načítaní aplikácie pre používateľov mimo S_Admin považuje za neprítomnú.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin obchází tento zoznam rolí a vždy si zachovává prístup.",
    "ZONE_ROLE_LOCKED": "Výbery rolí sú dočasne uzamknuté, kým je táto zóna zakázaná, a po opätovnom povolení zóny sa vrátia presne tak, ako boli uložené.",
    "ZONE_LCAC_CONTROL": "Řízení LCAC",
    "ZONE_RCAC_CONTROL": "Řízení RCAC",
    "ZONE_LCAC_DESCRIPTION": "Riadi existenciu ľavej vyhradenej zóny a roly, ktoré ju môžu vidieť.",
    "ZONE_RCAC_DESCRIPTION": "Riadi existenciu pravej vyhradenej zóny a roly, ktoré ju môžu vidieť.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap viditeľnosti zón teraz číta z chránenej backendovej služby. Zmeny sa použijú pri ďalšom načítaní aplikácie.",
    "ZONE_VISIBILITY_CACHED": "Backendová služba viditeľnosti zón je práve nedostupná, preto sú aktívne hodnoty z cache alebo miestne predvolené hodnoty.",
    "ZONE_VISIBILITY_DEFAULTS": "Predvolené hodnoty viditeľnosti zón sú aktívne, pretože nebolo možné načítať žiadny backendový ani uložený stav.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap viditeľnosti zón bol uložený. Pre runtime použitie je potrebné tvrdé obnovenie alebo ďalšie načítanie aplikácie.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Chránená backendová služba nemohla uložiť požadovanú zmenu viditeľnosti zóny.",
    "ROLE_MEMBER": "Člen",
    "ROLE_STAFF": "Personál",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Povolte oznámenia, abyste dostávali nové správy.",
    "MAIN_LOG_OUT": "Odhlásiť sa",
    "NOTIFICATION_NEW_MESSAGE": "Nová správa",
    "NOTIFICATION_UNREAD_MESSAGE": "Máte neprečítanú správu.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Plné zobrazenie",
    "MEDIA_AUDIO_ATTACHMENT": "Zvuková príloha",
    "MEDIA_FILE_FALLBACK": "Súbor",
    "MEDIA_DOWNLOAD_READY": "Príloha je pripravená na stiahnutie",
    "MEDIA_TYPE_UNSUPPORTED": "Typ nie je podporován pro plné zobrazenie",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Predchádzajúci obrázok",
    "MEDIA_NEXT_IMAGE_ARIA": "Další obrázek",
    "MEDIA_OPEN_ORIGINAL": "Otvoriť originál",
    "MEDIA_DOWNLOAD": "Stáhnout",
    "MEDIA_CLOSE_ARIA": "Zavrieť",
    "MEDIA_PROFILE_PICTURE_ARIA": "Profilový obrázek {name}",
    "MEDIA_PROFILE_ALT": "Profil {name}",
    "MEDIA_UPLOAD_FAILED": "Nahrávanie zlyhalo",
    "MEDIA_BACKEND_TOKEN_ERROR": "Chyba backendového tokenu",
    "MEDIA_UPLOAD_URL_MISSING": "Kritické: v odpovedi backendu chýba URL na nahrávanie.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Chýba overovací token na nahrávanie do chatu",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Požiadavka na token pro nahrávanie do chatu selhal",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Neplatná odpoveď nahrávanie do chatu",
    "MEDIA_GCS_UPLOAD_FAILED": "Nahrávanie GCS zlyhalo",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Chýba název súboru alebo contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Chýba file_path",
    "BLOCK_NOTICE_TITLE": "Oznámenia o trvalém blokování",
    "BLOCK_NOTICE_MESSAGE": "Váš účet bol dočasne pozastavený z dôvodu porušenia zásad.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Ak sa domnievate, že je potrebné ďalšie riešenie, kontaktujte prosím",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "e-mailem.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Neznámy používateľ",
    "GENERAL_GUEST": "Hosť",
    "ADVISOR_FOR_CLIENT": "Poradca pre {client_display_name}",
    "GUEST_FOR_CLIENT": "",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token a heslo sú povinné",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Telo požiadavky musí byť JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Neplatný alebo expirovaný token pozvánky",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Nastavenie hesla zlyhalo: chýba relácia alebo používateľ",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Nastavenie hesla zlyhalo počas prihlasovania",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Vygenerování admin tokenu zlyhalo",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Prihlásenie zlyhalo: chýba relácia alebo používateľ",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registrácia bola úspešná. Skontrolujte e-mail na overenie.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Neznámé zlyhanie registrace",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Neplatné zpracování tokenu",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Prístupový token je povinný",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Náhľad hashu tokenu vyžaduje e-mailovú pomôcku z URL presmerovania",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Pre tento token sa nepodarilo vyriešiť identitu",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Ke službe selektoru WF1 LLM má prístup iba User Zero.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "K službe riadenia viditeľnosti zón má prístup iba User Zero.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "K službe riadenia verzie frontendu má prístup iba User Zero.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Iba User Zero môže kontrolovať verziu frontendu iného používateľa.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "K službe riadenia mazania chatu má prístup iba User Zero.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Iba User Zero môže natrvalo odstrániť používateľský účet.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Neplatný payload požiadavky.",
    "API_ERROR_INTERNAL_SERVER": "Interná chyba servera",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funkcia chýba v backendu (vyžaduje sa opätovné načítanie)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Pre prechody delivered/read je povolené iba DB RPC.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Pred odoslaním ďalšej správy prosím počkajte.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Správa bola úspešne odoslaná.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Kontaktní služba nie je dostupná.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Odeslání správy zlyhalo.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Meno je povinné.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-mail je neplatný.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Správa je povinná.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload selektora je povinný.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload viditeľnosti zón je povinný.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload verzie frontendu je povinný.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload riadenia mazania chatu je povinný.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID overeného používateľa je povinné.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID overeného prehliadajúceho používateľa je povinné.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID overeného konajúceho používateľa je povinné.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id je povinné.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id je povinné.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Zoznam owner_user_ids je povinný.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email je povinné.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by je povinné.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime vyhľadávania je zakázaný globálnou verziou frontendu.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Nemáte povolenie zrušiť túto čakajúcu pozvánku.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Túto pozvánku už nie je možné zrušiť, pretože používateľ je už registrovaný.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Čakajúca pozvánka sa nenašla.",
    "INVITE_REPLY_ALREADY_MEMBER": "Gratulujeme, váš priateľ ({invitee_email}) je už v tejto aplikácii zaregistrovaný a je členom tohto pracovného priestoru.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Pre {invitee_email} čaká pozvánka, ale e-mail na opakované odoslanie sa nepodarilo spustiť. Skontrolujte prosím poštové logy.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Záznam pozvánky bol vytvorený pre {invitee_email}, ale doručenie e-mailu nebolo možné potvrdiť. Skúste to prosím neskôr alebo skontrolujte poštové logy.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Vytvorenie záznamu pozvánky zlyhalo. Skúste to prosím neskôr.",
    "INVITE_REPLY_SYSTEM_ERROR": "Systémová chyba počas procesu pozvania: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Chyba konfigurácie backendu: chýbajú prihlasovacie údaje Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Chyba konfigurácie backendu: neplatná URL adresa Supabase",
    "CHAT_ERROR_ACCESS_DENIED": "Prístup zamietnutý",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Obsah textových správ nemôže byť prázdny",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Nepodarilo sa určiť ID konverzácie",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Chýba kontext overenia RPC",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC vrátilo neplatný payload správy",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Vloženie zlyhalo, aleboli vrátené žiadne dáta",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations musí byť zoznam",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Neplatný payload operácie",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Nepodporovaný operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id je povinné",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Správa sa nenašla",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Odstránenie je povolené iba pri vašej vlastnej správe",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Odstrániť pre všetkých už nie je pre túto správu dostupné",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Odstránenie pre všetkých zlyhalo",
    "API_ERROR_SERVER_CONFIGURATION": "Chyba konfigurácie servera",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Chýba hlavička tajného kľúča webhooku",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Neautorizovaný zdroj webhooku",
    "API_ERROR_BACKEND_CONFIGURATION": "Chyba konfigurácie backendu",
    "API_ERROR_MODULE_ATTRIBUTE": "Chyba atribútu modulu: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Zlyhanie pred odstránením pozvánky pri odstraňovaní čakajúceho overeného používateľa.",
    "CHAT_ERROR_DB": "Chyba DB: {error}",
}
