# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/sl.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Glavno",
    "APP_TITLE": "Platforma OTMEGA AI",
    "APP_SUBTITLE": "AI svetovalec",
    "CHAT_PLACEHOLDER": "Vnesite sporočilo...",
    "CHAT_SEND_BUTTON": "Pošlji",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Svetovalec se lahko zmoti, zato informacije preverite.",
    "STATUS_ONLINE": "Na spletu",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Meni",
    "ICON_NEW_CHAT": "Nov klepet",
    "ICON_HISTORY": "Zgodovina",
    "ICON_TEMPLATES": "Predloge",
    "ICON_SETTINGS": "Nastavitve",
    "ICON_USER_PROFILE": "Uporabniški profil",
    "ICON_QUICK_ACTIONS": "Hitra dejanja",
    "ICON_PINNED": "Pripeto",
    "ICON_GALLERY": "Galerija",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Namesti aplikacijo",
    "PWA_ANDROID_MSG": "Namestite to aplikacijo v svojo napravo za boljšo izkušnjo in dostop brez povezave.",
    "PWA_IOS_MSG": "Za namestitev te aplikacije na iPhone/iPad:\n1. Tapnite spodnji gumb Deli\n2. Izberite Dodaj na začetni zaslon",
    "PWA_BTN_INSTALL": "Namesti",
    "PWA_BTN_LATER": "Morda pozneje",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Prijavite se v omrežje svetovalcev",
    "AUTH_HEADER_SIGNUP": "Ustvarite svoj poenoten račun",
    "AUTH_HEADER_LOGIN_NETWORK": "Prijavite se v omrežje svetovalcev",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Ustvarite svoj poenoten račun",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Prijava",
    "AUTH_BUTTON_SIGNUP": "Ustvari račun",
    "AUTH_BUTTON_GOOGLE": "Nadaljuj z Googlom",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Pozabljeno geslo",
    "AUTH_BUTTON_SEND_RESET_LINK": "Pošlji povezavo za ponastavitev",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Nimate računa? Registrirajte se",
    "AUTH_PROMPT_LOGIN": "Že imate račun? Prijavite se",
    "AUTH_HELPER_TEXT_SIGNUP": "Ustvarjate poenoten račun, ki ga lahko uporabite za dostop do vseh svetovalcev na tej platformi.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Ustvarjate poenoten račun, ki ga lahko uporabite za dostop do vseh svetovalcev na tej platformi.",
    "AUTH_HELPER_TEXT_LOGIN": "Uporabite isti račun (e-pošta/geslo ali Google), ki ste ga uporabili za druge svetovalce v tem omrežju.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Uporabite isti račun (e-pošta/geslo ali Google), ki ste ga uporabili za druge svetovalce v tem omrežju.",
    "AUTH_FORGOT_PASSWORD_LINK": "Ste pozabili geslo?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Ponastavite geslo",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Vnesite svoj e-poštni naslov in poslali vam bomo povezavo za ponastavitev gesla.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-pošta",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Prijavljamo vas...",
    "AUTH_STATUS_LOADING_SIGNUP": "Ustvarjanje računa...",
    "AUTH_STATUS_LOADING_RESET": "Pošiljanje povezave za ponastavitev...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Prijava uspešna! Ponovno nalaganje...",
    "AUTH_STATUS_SUCCESS_RESET": "Povezava za ponastavitev je bila uspešno poslana. Preverite svojo e-pošto.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Povezava za ponastavitev gesla je bila uspešno poslana. Preverite svojo e-pošto.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Neveljavna e-pošta ali geslo.",
    "AUTH_ERROR_EMAIL_EXISTS": "Račun s tem e-poštnim naslovom že obstaja v omrežju svetovalcev.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Račun s tem e-poštnim naslovom že obstaja. Prijavite se. Trenutno ste član:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Račun s tem e-poštnim naslovom že obstaja v omrežju svetovalcev. Zaprite to okno in uporabite razdelek Prijava z istim e-poštnim naslovom in prejšnjim geslom.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Trenutno ste član:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-pošta in geslo sta obvezna.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Račun je bil ustvarjen, vendar nastavitev članstva ni uspela. Obrnite se na podporo.",
    "AUTH_ERROR_DEFAULT": "Prišlo je do napake. Poskusite znova.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Zahtevana je vsebina za nadzor pasice za goste.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Samo uporabnik nič lahko posodobi nadzor pasice za goste.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Pošiljanje povezave za ponastavitev ni uspelo. Poskusite znova.",
    "INVITE_REPLY_EMAIL_SENT": "E-pošta s povabilom Collabra je bila poslana vašemu prijatelju na {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "E-pošta s povabilom Collabra je bila ponovno poslana vašemu prijatelju na {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Prikaži geslo",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Skrij geslo",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "V redu",
    "GENERAL_CANCEL": "Prekliči",
    "GENERAL_CLOSE": "Zapri",
    "GENERAL_SEND": "Pošlji",
    "GENERAL_SEARCH": "Išči",
    "GENERAL_RESET": "Ponastavi",
    "GENERAL_ENABLE": "Omogoči",
    "GENERAL_LOADING": "Nalaganje...",
    "GENERAL_DELETE": "Izbriši",
    "GENERAL_DELETING": "Brisanje...",
    "GENERAL_SAVE_PASSWORD": "Shrani geslo",
    "AUTH_REMEMBER_EMAIL_LABEL": "Zapomni si e-pošto",
    "GENERAL_SAVING": "Shranjevanje...",
    "GENERAL_SENDING": "Pošiljanje...",
    "GENERAL_REMOVING": "Odstranjevanje...",
    "GENERAL_CONFIRM_REMOVAL": "Potrdi odstranitev",
    "GENERAL_EMPTY": "Prazno",
    "GENERAL_UNAVAILABLE": "Ni na voljo",
    "GENERAL_ENABLED": "Omogočeno",
    "GENERAL_DISABLED": "Onemogočeno",
    "GENERAL_GRANTED": "Dovoljeno",
    "GENERAL_DENIED": "Zavrnjeno",
    "GENERAL_DEFAULT": "Privzeto",
    "GENERAL_UNSUPPORTED": "Ni podprto",
    "GENERAL_PUBLIC": "Javno",
    "GENERAL_PRIVATE": "Zasebno",
    "GENERAL_USERNAME": "Uporabniško ime",
    "GENERAL_EMAIL": "E-pošta",
    "GENERAL_YOU": "Vi",
    "GENERAL_USER": "Uporabnik",
    "GENERAL_UNKNOWN": "Neznano",
    "GENERAL_VISITOR": "Obiskovalec",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Pasica",
    "GENERAL_UNKNOWN_BANNER": "Neznana pasica",
    "GENERAL_ADVISOR_BANNER": "Pasica svetovalca",
    "GENERAL_NOT_AVAILABLE": "N/V",
    "GENERAL_NOT_SELECTED": "Ni izbrano",
    "GENERAL_NO_EMAIL_FOUND": "E-pošta ni najdena",
    "GENERAL_USER_ZERO_ONLY": "Samo User Zero",
    "GENERAL_CONNECTION_STATE": "Stanje povezave",
    "GENERAL_DISPLAY_ONLY": "Samo prikaz",
    "GENERAL_TEXTAREA": "Besedilno polje",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Meni (LCAC)",
    "HEADER_CHAT_CCAC": "Klepet (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Hitra dejanja (RCAC)",
    "HEADER_CHANGE_STATUS": "Spremeni stanje",
    "HEADER_OT_COIN_BALANCE": "Stanje OT Coin",
    "HEADER_ALT_USER": "Uporabnik",
    "STATUS_BUSY": "Zaseden",
    "STATUS_AWAY": "Odsoten",
    "STATUS_OFFLINE": "Brez povezave",
    "STATUS_INVISIBLE": "Neviden",
    "NETWORK_CHECKING_CONNECTION": "Preverjanje povezave...",
    "NETWORK_ONLINE_LATENCY": "Na spletu (zakasnitev: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Omrežje: dobro (tapnite za ping)",
    "CHAT_TARGET_ALT": "Cilj klepeta",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Išči...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Odpri profilno sliko osebe {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Vnos sporočila",
    "CHAT_TOGGLE_VIEW_ARIA": "Preklopi pogled",
    "CHAT_ADD_USER_ARIA": "Dodaj uporabnika",
    "CHAT_ATTACH_ARIA": "Priloži",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Pošlji",
    "CHAT_SEARCH_ARIA": "Išči",
    "CHAT_OPEN_SEARCH_ARIA": "Odpri iskanje",
    "CHAT_CLOSE_SEARCH_ARIA": "Zapri iskanje",
    "CHAT_ATTACHMENT_ALT": "Priloga",
    "CHAT_PREVIEW_ALT": "Predogled",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Odstrani prilogo",
    "CHAT_REPLYING_TO": "Odgovor na",
    "CHAT_CANCEL_REPLY_ARIA": "Prekliči odgovor",
    "CHAT_UPLOADING": "Nalaganje...",
    "CHAT_LOADING_CHATS": "Nalaganje klepetov...",
    "CHAT_SEND_FAILED": "Pošiljanje ni uspelo",
    "CHAT_SEND_FAILED_RETRY": "Pošiljanje ni uspelo. Poskusite znova.",
    "CHAT_RETRY": "Poskusi znova",
    "CHAT_EDITED": "urejeno",
    "CHAT_TYPING": "Tipkanje",
    "CHAT_LOADING": "Nalaganje",
    "CHAT_PENDING_INVITATION": "Povabilo v čakanju",
    "CHAT_PENDING_INVITATION_MIN": "{count} min povabilo v čakanju",
    "CHAT_PENDING_INVITATION_HR": "{count} h povabilo v čakanju",
    "CHAT_PENDING_INVITATION_DAY": "{count} d povabilo v čakanju",
    "CHAT_WAITING_FOR_YOU": "{label} - čaka na vas",
    "CHAT_PENDING_ACCEPTANCE": "{label} - čaka na sprejem",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Dostop do mikrofona zavrnjen.",
    "CHAT_UPLOAD_FAILED": "Nalaganje ni uspelo: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Nalaganje zahteva internetno povezavo. Poskusite znova, ko boste povezani.",
    "CHAT_ERROR_AUTH": "Napaka pri preverjanju pristnosti",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Manjka ime datoteke ali content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Manjka conversation_id ali target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Manjka conversation_id za nalaganje, ki ni avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Neveljaven file_path avatarja",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Storitveni odjemalec Supabase ni na voljo",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Potrditev branja avatarja je veljavna samo v kontekstu klepeta s svetovalcem",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Sporočilo toka avatarja ni najdeno ali ni primerno za potrditev branja",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Dokončanje sporočila avatarja kot prebranega ni uspelo",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 priloga",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} prilog",
    "CHAT_VOICE_NOTE": "Glasovna opomba",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Klepet ni na voljo. Ta uporabnik vas je blokiral.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Klepet ni na voljo. Tega uporabnika ste blokirali.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Dostop do računa je blokiran s pravilnikom.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Klepet ni na voljo. Ta račun je dokončno blokiral User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Klepet ni na voljo. Vzajemna blokada je aktivna.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Klepet ni na voljo zaradi pravilnika blokiranja.",
    "MESSAGE_PREVIEW_PHOTO": "Fotografija",
    "MESSAGE_PREVIEW_VOICE": "Glasovno sporočilo",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Datoteka",
    "MESSAGE_PREVIEW_MESSAGE": "Sporočilo",
    "MESSAGE_PREVIEW_SYSTEM": "Sistemsko sporočilo",
    "MESSAGE_PREVIEW_NEW": "Novo sporočilo",
    "MESSAGE_UNKNOWN_FILE": "Neznana datoteka",
    "MESSAGE_AUDIO_ATTACHMENT": "Zvočna priloga",
    "MESSAGE_FILE_ATTACHMENT": "Priloga",
    "BANNER_INVITED_BY": "povabil {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Rezultati iskanja",
    "SEARCH_QUERY_LABEL": "Poizvedba:",
    "SEARCH_LOADING_VISIBILITY": "Nalaganje vidnosti iskanja...",
    "SEARCH_NO_RESULTS": "V trenutnem obsegu iskanja ni bilo najdenih rezultatov.",
    "SHARE_WITH_COLLABRA": "Deli s Collabra",
    "SHARE_SEND_TO": "Pošlji na",
    "SHARE_SELECT_ONE_BANNER": "Izberite eno pasico",
    "SHARE_BANNER_LIST_ARIA": "Seznam pasic",
    "SHARE_NO_MATCHING_BANNER": "Ni ujemajoče se pasice",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Dodajte komentar...",
    "SHARE_RECENT_CHATS": "Nedavni klepeti",
    "SHARE_LEFT_LIST": "Levi seznam",
    "SHARE_RIGHT_LIST": "Desni seznam",
    "SHARE_UNTITLED_BANNER": "Pasica brez naslova",
    "SHARE_SHARED_CONTENT": "Deljena vsebina",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Deljene vsebine ni bilo mogoče odpreti.",
    "SHARE_OPEN_BANNER_FAILED": "Izbrane pasice ni bilo mogoče odpreti.",
    "SHARE_ONE_PHOTO_SELECTED": "Izbrana 1 fotografija",
    "SHARE_MANY_PHOTOS_SELECTED": "Izbranih {count} fotografij",
    "SHARE_ONE_FILE_SELECTED": "Izbrana 1 datoteka",
    "SHARE_MANY_FILES_SELECTED": "Izbranih {count} datotek",
    "FORWARD_MESSAGE_TITLE": "Posreduj sporočilo",
    "FORWARD_SELECT_RECIPIENTS": "Izberite prejemnike",
    "FORWARD_NO_OTHER_BANNER": "Ni na voljo druge pasice.",
    "FORWARD_SEND_TO_COUNT": "Pošlji na {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Izberite vsaj eno pasico.",
    "FORWARD_FAILED_DEFAULT": "Posredovanje ni uspelo. Poskusite znova.",
    "FORWARD_PARTIAL_SENT": "{count} poslano. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Izvorno sporočilo za posredovanje ni bilo najdeno",
    "FORWARD_NO_FORWARDABLE_CONTENT": "To sporočilo še nima vsebine za posredovanje",
    "FORWARD_DESTINATION_MISSING": "Cilj posredovanja manjka",
    "FORWARD_MESSAGE_PREVIEW": "Posredovano sporočilo",
    "MENU_PASTE": "Prilepi",
    "MENU_COPY": "Kopiraj",
    "MENU_REPLY": "Odgovori",
    "MENU_FORWARD": "Posreduj",
    "MENU_REMOVE_INVITATION": "Odstrani povabilo",
    "MENU_REMOVE_FROM_LIST": "Odstrani s seznama",
    "MENU_GOODBYE_GUEST": "Nasvidenje, gost",
    "MENU_ADD_TO_LIST": "Dodaj na seznam",
    "MENU_REJECT_INVITATION": "Zavrni povabilo",
    "MENU_FRONTEND_VERSION": "Različica frontenda",
    "MENU_BANNER_HEADER": "Pasica - {zone}",
    "MENU_BANNER_INFO": "Informacije o pasici: {title}",
    "MENU_MESSAGE_BUBBLE": "Oblaček sporočila",
    "MENU_CHAT_CANVAS_HEADER": "Platno klepeta - {zone}",
    "MENU_CANVAS_INFO": "Informacije o platnu",
    "MENU_CHAT_CANVAS_SUBLABEL": "Območje pogovora / trenutna površina klepeta",
    "MENU_INPUT_AREA_HEADER": "Območje vnosa - {zone}",
    "MENU_INPUT_AREA_INFO": "Informacije o območju vnosa: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Spodnja površina za tipkanje in akcijska orodja",
    "MENU_HEADER": "Glava - {zone}",
    "MENU_HEADER_INFO": "Informacije o glavi: {title}",
    "MENU_HEADER_DESCRIPTION": "Zgornja navigacija in kontrolniki strani",
    "MENU_ZONE_HEADER": "Cona - {zone}",
    "MENU_ZONE_SPACE_INFO": "Informacije o prostoru cone",
    "MENU_EMPTY_LIST_SURFACE": "Prazna/seznamska površina",
    "MENU_BLOCK": "Blokiraj",
    "MENU_UNBLOCK": "Odblokiraj",
    "MENU_HIDE_IN_SEARCH": "Skrij v iskanju",
    "MENU_UNHIDE_IN_SEARCH": "Prikaži v iskanju",
    "MENU_VISIBLE_IN_SEARCH": "Vidno v iskanju",
    "MENU_HIDDEN_IN_SEARCH": "Skrito v iskanju",
    "MENU_VISIBLE_IN_USER_LIST": "Vidno na seznamu uporabnikov",
    "MENU_HIDDEN_IN_USER_LIST": "Skrito na seznamu uporabnikov",
    "MENU_NOT_BLOCKED": "Ni blokirano",
    "MENU_BLOCKED": "Blokirano",
    "MENU_FRONTEND_VERSION_LOADING": "Nalaganje...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Nalaganje vrednosti za posamezno pasico iz backenda. Nobena možnost ni označena kot aktivna, dokler ne prispe odgovor baze podatkov.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Vrednosti iz backenda ni bilo mogoče naložiti. Nobena zaupanja vredna aktivna možnost ni prikazana.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Izrecna vrednost v bazi podatkov za posamezno pasico je {overrideVersion}. Globalna privzeta vrednost je {globalDefaultVersion}. Ciljni uporabnik mora v celoti osvežiti ali znova odpreti aplikacijo, da jo zagonski bootstrap uporabi.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Izrecna vrednost za posamezno pasico ni shranjena. FeV2.0.0 je privzeto aktiven. Globalna privzeta vrednost je {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Izrecna vrednost baze podatkov za posamezno pasico postane aktivna po popolnem ponovnem nalaganju ciljne aplikacije",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Izrecna vrednost za posamezno pasico ni shranjena; to je privzeto individualno stanje FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Ta možnost je tudi enaka trenutni globalni privzeti vrednosti",
    "MENU_DELETE_PERMANENT_CONFIRM": "Trajno izbrisati {target} iz baze podatkov? To odstrani račun, zgodovino klepeta, odvisnosti in za prihodnji ponovni vstop zahteva popolnoma novo pot povabila.",
    "MENU_DELETE_PERMANENTLY": "Trajno izbriši",
    "MENU_REFRESH_PAGE": "Osveži stran",
    "MENU_LOG_OFF": "Odjava",
    "MENU_HARD_RELOAD": "Trdo ponovno nalaganje",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-pošta (skrbniški uporabnik)",
    "AUTH_PASSWORD_PLACEHOLDER": "Geslo",
    "AUTH_CONNECTING": "Povezovanje...",
    "AUTH_SIGNING_OUT": "Odjavljanje...",
    "AUTH_BACK_TO_LOGIN": "Nazaj na prijavo",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Neveljaven odgovor strežnika: žeton ni najden.",
    "AUTH_LOGIN_FAILED": "Prijava ni uspela",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Gesli se ne ujemata.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Gesli se ne ujemata!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Gesli se morata natančno ujemati.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Novo geslo",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Potrdite geslo",
    "AUTH_CHANGE_PASSWORD": "Spremeni geslo",
    "AUTH_SAVING_PASSWORD": "Shranjevanje...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Geslo je bilo uspešno posodobljeno.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Gesla trenutno ni mogoče spremeniti.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Za spremembo gesla morate biti prijavljeni.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Preklopi vidnost novega gesla",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Preklopi vidnost potrditve gesla",
    "REGISTER_TITLE": "Dokončaj registracijo",
    "REGISTER_SUBTITLE": "Prosimo, ročno nastavite svoje geslo.",
    "REGISTER_CREATING_ACCOUNT": "Ustvarjanje računa...",
    "REGISTER_FINISH_SETUP": "Dokončaj nastavitev",
    "REGISTER_FAILED_SET_PASSWORD": "Nastavitev gesla ni uspela",
    "INVITE_EMAIL_INSTRUCTION": "Vnesite e-pošto povabljenca (oblika: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Povabi",
    "INVITE_EMAIL_REQUIRED": "Vnesite e-pošto povabljenca.",
    "INVITE_EMAIL_INVALID": "Neveljavna oblika e-pošte. Uporabite: user@example.com",
    "PENDING_INVITATION_TITLE": "Povabilo v čakanju",
    "PENDING_INVITATION_REMOVE_QUESTION": "Odstraniti to povabilo v čakanju iz baze podatkov?",
    "PENDING_INVITATION_KEEP": "Ohrani povabilo",
    "PENDING_INVITATION_REMOVAL_FAILED": "Odstranitev ni uspela.",
    "REMOVE_FROM_LIST_TITLE": "Odstrani s seznama",
    "REMOVE_FROM_LIST_WARNING": "Odstraniti tega uporabnika z obeh seznamov zdaj? Dostop do klepeta bo takoj prekinjen. Edina pot nazaj je novo povabilo.",
    "REMOVE_FROM_LIST_KEEP": "Ohrani uporabnika na seznamu",
    "REMOVE_FROM_LIST_FAILED": "Odstranitev s seznama ni uspela.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Nastavitve in stanje v živo",
    "PERMISSION_DIALOG_ARIA": "Nastavitve in stanje v živo",
    "PERMISSION_TRIGGER_ARIA": "Sprožilec pojavnega okna nastavitev",
    "PERMISSION_CLOSE_ARIA": "Zapri pojavno okno dovoljenj",
    "PERMISSION_LIVE_STATUS": "Stanje v živo",
    "PERMISSION_SYSTEM_PERMISSION": "Sistemsko dovoljenje",
    "PERMISSION_APP_PUSH": "Potisna obvestila aplikacije",
    "PERMISSION_LOCATION_PERMISSION": "Dovoljenje za lokacijo",
    "PERMISSION_APP_LOCATION": "Lokacija aplikacije",
    "PERMISSION_CONTROLS": "Kontrolniki dovoljenj",
    "PERMISSION_PUSH_NOTIFICATIONS": "Potisna obvestila",
    "PERMISSION_LOCATION_ACCESS": "Dostop do lokacije",
    "PERMISSION_IN_APP_SETTINGS": "Nastavitve v aplikaciji",
    "PERMISSION_ALERT_SOUND": "Zvok opozorila",
    "PERMISSION_APP_BADGE": "Značka aplikacije",
    "PERMISSION_PASSWORD_SETTINGS": "Nastavitve gesla",
    "PERMISSION_NAVIGATION_STATUS": "Stanje navigacije",
    "PERMISSION_SELECTED_ZONE": "Izbrana cona",
    "PERMISSION_STAGED_CHAT_BANNER": "Pripravljena pasica klepeta",
    "PERMISSION_CANVAS_CONTENT": "Vsebina platna",
    "PERMISSION_YOUR_DEVICES": "Vaše naprave ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Osveži seznam naprav",
    "PERMISSION_REFRESH_LIST": "Osveži seznam",
    "PERMISSION_NO_REGISTERED_DEVICES": "Registrirane naprave niso bile najdene.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Spremeni velikost pojavnega okna nastavitev",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Preklopi potisna obvestila",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Preklopi dostop do lokacije",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Preklopi zvok opozorila",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Preklopi značko aplikacije",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Preklopi vidnost profila",
    "PERMISSION_OFF_IN_V1": "Izklopljeno v v1",
    "PERMISSION_CHAT": "Klepet",
    "PERMISSION_BANNER_LIST": "Seznam pasic",
    "PERMISSION_PUSH_DISABLED_V1": "Potisna obvestila so onemogočena za izdajo v1 Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Potisna obvestila so za to napravo VKLOPLJENA.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Sistemska obvestila so blokirana. Tapnite za odpiranje pomoči za nastavitve.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Vklopite za izboljšanje zanesljivosti dostave.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Za onemogočanje sistemskih obvestil odprite nastavitve obvestil brskalnika/spletnega mesta in to mesto nastavite na Blokiraj.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Za spremembo dovoljenja sistemskih obvestil odprite nastavitve obvestil brskalnika/spletnega mesta in to mesto nastavite na Dovoli.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Dostop do lokacije je VKLOPLJEN za razvrščanje LCAC glede na razdaljo in pozicioniranje zemljevida.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API za lokacijo v tem okolju ni podprt.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Dostop do lokacije je blokiran. Tapnite za odpiranje pomoči za nastavitve.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Vklopite za omogočanje natančnega razvrščanja LCAC glede na razdaljo in pozicioniranja zemljevida v aplikaciji.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Dostop do lokacije v tem okolju ni podprt.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Za onemogočanje dostopa do lokacije odprite nastavitve lokacije brskalnika/spletnega mesta in to mesto nastavite na Blokiraj.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Za omogočanje dostopa do lokacije za razvrščanje po razdalji in pozicioniranje zemljevida v aplikaciji odprite nastavitve lokacije brskalnika/spletnega mesta in to mesto nastavite na Dovoli.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Registriranih naprav trenutno ni mogoče naložiti.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Nalaganje UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Nalaganje Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Nalaganje backenda...",
    "RUNTIME_LOADING": "Nalaganje...",
    "RUNTIME_LOADING_FROM_DATABASE": "Nalaganje iz baze podatkov...",
    "RUNTIME_BACKEND_CONNECTED": "Backend povezan",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Predpomnjena nadomestna možnost aktivna",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Privzeta nadomestna možnost aktivna",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Privzete nadomestne vrednosti aktivne",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Shranjevanje prek backenda...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Shranjeno v backend storitvi",
    "RUNTIME_SAVE_FAILED": "Shranjevanje ni uspelo",
    "RUNTIME_LOAD_FAILED": "Nalaganje ni uspelo",
    "RUNTIME_CONNECTED": "Povezano",
    "RUNTIME_LOGIN_REQUIRED": "Prijava je obvezna",
    "RUNTIME_SAVED": "Shranjeno",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI pripravljen - runtime v čakanju",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Zaščitena backend storitev izbirnika je zavrnila ali ni mogla shraniti zahtevane možnosti modela.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Zaščitena backend storitev izbirnika je zavrnila ali ni mogla shraniti zahtevane spremembe usmerjanja WF1.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Izbirnik zdaj bere aktivno konfiguracijo, usmerjanje Qwen in dovoljene možnosti iz zaščitene backend storitve.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend storitev izbirnika trenutno ni na voljo, zato se uporablja zadnje predpomnjeno stanje izbirnika.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Privzete vrednosti izbirnika so aktivne, ker ni bilo mogoče naložiti nobenega backend ali predpomnjenega stanja izbirnika.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Zaščitena backend storitev izbirnika je posodobila aktivno konfiguracijo usmerjanja WF1 in osvežila predpomnilnik runtime domene.",
    "FRONTEND_VERSION_TITLE": "Različica frontenda",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Ta izbirnik nadzoruje aktivno različico frontenda za vse uporabnike. FeV2.0.0 je aktiven.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Ta izbirnik bere aktivno različico frontenda iz config_domain_registry. Runtime se razreši v FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend konfiguracije različice frontenda ni bilo mogoče naložiti, zato ostane kodirana privzeta vrednost FeV2.0.0 aktivna, dokler zagonski bootstrap znova ne prebere zaščitene storitve.",
    "FRONTEND_VERSION_HELPER_SAVED": "Aktivna različica frontenda je bila shranjena v config_domain_registry. Popolna osvežitev ali naslednje nalaganje aplikacije uporabi runtime vrednost.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend storitev za nadzor različice frontenda ni mogla shraniti zahtevane globalne različice.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktivna različica frontenda.",
    "CHAT_DELETE_WINDOW_TITLE": "Okno za brisanje klepeta",
    "CHAT_DELETE_HELPER": "Ta vrednost nadzoruje okno razpoložljivosti funkcije Izbriši za vse v sekundah. Backend varovalo se spremeni takoj po shranjevanju. Vidnost oblačka se spremeni po popolni osvežitvi ali naslednjem nalaganju aplikacije.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend storitve za nadzor brisanja klepeta ni bilo mogoče naložiti, zato kodirana privzeta vrednost ostane aktivna, dokler zagonski bootstrap znova ne prebere zaščitene storitve.",
    "CHAT_DELETE_HELPER_SAVED": "Okno razpoložljivosti funkcije Izbriši za vse je bilo shranjeno v config_domain_registry. Backend varovalo se spremeni takoj. Vidnost oblačka se spremeni po popolni osvežitvi ali naslednjem nalaganju aplikacije.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend storitev za nadzor brisanja klepeta ni mogla shraniti zahtevane vrednosti okna.",
    "CHAT_DELETE_WINDOW_LABEL": "Okno Izbriši za vse",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} s",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Vrednost shranite v celih sekundah. Trenutna produkcijska vrednost je 86400 sekund = 1 dan.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Sekunde okna",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Vnesite celo število, večje ali enako 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Shrani okno za brisanje",
    "GUEST_BANNER_CONTROL_TITLE": "Pasica za goste",
    "GUEST_BANNER_CONTROL_LABEL": "Klepet QR za goste",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Prikaži pasico za goste vsem uporabnikom",
    "GUEST_BANNER_CONTROL_HELPER": "Upravlja fiksno pasico za goste in življenjsko dobo čakajočega žetona QR.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Za nadzor pasice za goste je aktivna lokalna nadomestna rešitev.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Nastavitve pasice za goste so shranjene.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Nastavitev pasice za goste ni bilo mogoče shraniti.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "Preklicanih je {count} sej gostov.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "TTL čakajoče kode QR (v minutah)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "Trenutni čakajoči TTL kode QR: {count} minut.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Vnesite pozitivno celo število minut.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Shrani pasico za goste",
    "GUEST_QR_LOADING": "Pripravljanje kode QR za goste ...",
    "GUEST_QR_READY": "Skenirajte za odprtje začasnega klepeta za goste.",
    "GUEST_QR_ALT": "Koda QR za klepet za goste",
    "GUEST_QR_LOAD_FAILED": "QR kode za gosta ni bilo mogoče pripraviti.",
    "GUEST_SESSION_ACTIVE": "Gost je povezan.",
    "GUEST_PUBLIC_TITLE": "Gostujoči klepet",
    "GUEST_PUBLIC_CONNECTING": "Povezovanje...",
    "GUEST_PUBLIC_CONNECTED": "Povezano",
    "GUEST_PUBLIC_UNAVAILABLE": "Ta povezava za gosta ni na voljo.",
    "GUEST_PUBLIC_SEND_FAILED": "Sporočila ni bilo mogoče poslati.",
    "UI_TEXTS_RUNTIME_TITLE": "Izvajalno okolje jezika uporabniškega vmesnika",
    "UI_TEXTS_RUNTIME_BACKEND": "Izvajalno okolje jezika uporabniškega vmesnika bere iz zaščitene zaledne storitve. Spremembe bodo uveljavljene ob naslednjem polnem nalaganju aplikacije.",
    "UI_TEXTS_RUNTIME_CACHED": "Zaledna storitev izvajalnega okolja jezika uporabniškega vmesnika trenutno ni na voljo, zato so aktivne predpomnjene ali lokalne privzete vrednosti.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "Privzete vrednosti izvajalnega okolja jezika uporabniškega vmesnika so aktivne, ker ni bilo mogoče naložiti zalednega ali predpomnjenega stanja.",
    "UI_TEXTS_RUNTIME_SAVED": "Nadzor izvajalnega okolja jezika uporabniškega vmesnika je bil shranjen. Za uporabnike je potrebna popolna osvežitev ali naslednje nalaganje aplikacije, da prejmejo nova jezikovna vrata.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Zaščitena zaledna storitev ni mogla shraniti zahtevane spremembe jezika uporabniškega vmesnika med izvajanjem.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Uporaba jezika naprave",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Omogoči jezike uporabniškega vmesnika med izvajanjem",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Uporabniki lahko prejmejo besedila uporabniškega vmesnika v svojem shranjenem jeziku ali jeziku naprave.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Vsi uporabniki morajo uporabljati besedila uporabniškega vmesnika v angleščini in jezik naprave se prezre.",
    "PROFILE_VISIBILITY_TITLE": "Vidnost profila",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Za upravljanje vidnosti računa morate biti prijavljeni.",
    "PROFILE_VISIBILITY_HELPER": "To stikalo posodobi samo stanje vidnosti vašega računa. Odkrivnost in vedenje seznama pasic v tej fazi ostaneta nespremenjena.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Vidnosti profila trenutno ni bilo mogoče naložiti.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Vidnosti profila trenutno ni bilo mogoče posodobiti.",
    "PROFILE_VISIBILITY_SAVED": "Vidnost vašega računa je zdaj {visibility}. Oznake odkrivnosti v tej fazi ostanejo nespremenjene.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Javni račun",
    "PROFILE_VISIBILITY_STORED": "Shranjena vidnost",
    "WF1_MODEL_CONTROL_TITLE": "Nadzor modela WF1",
    "WF1_ENABLE_TRANSLATION": "Omogoči prevod / pivot",
    "WF1_TRANSLATION_ACTIVE": "AI prevajanje je aktivno.",
    "WF1_TRANSLATION_INACTIVE": "WF1 še naprej deluje, vendar je izvorno besedilo kopirano, pivot pa označen kot neaktiven.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktivna runtime reža",
    "WF1_ALLOW_SAME_LANGUAGE": "Dovoli AI za jezikovne pare istega jezika",
    "WF1_SAME_LANGUAGE_ACTIVE": "Jezikovni pari istega jezika sledijo običajnemu usmerjanju WF1.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Jezikovni pari istega jezika obidejo AI in shranijo stanje brez aktivnega pivot jezika.",
    "WF1_QWEN_ROUTING": "Usmerjanje parov Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Spodaj označeni jeziki uporabljajo Qwen-Max, kadar je par isti označeni jezik, označeni jezik z angleščino ali dva označena neangleška jezika. V nasprotnem primeru ostane aktiven izbrani primarni model.",
    "WF1_OPENROUTER_TEST_SLOT": "Testna reža OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Testna reža OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Samo test kakovosti",
    "WF1_OPENROUTER_HELPER": "Ta reža je urediva samo za začasne teste kakovosti OpenRouter. Ne spremeni operativne poti usmerjanja parov Qwen, razen če ta reža sama postane aktivni model.",
    "WF1_LABEL": "Oznaka",
    "WF1_PRODUCT": "Izdelek",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Ponudnik: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Skrivnost: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Testna reža OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max prek OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Cenik Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Cenik OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Cenik OpenRouter",
    "LANGUAGE_ENGLISH": "Angleščina",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Kitajščina (poenostavljena)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Kitajščina (tradicionalna)",
    "LANGUAGE_JAPANESE": "Japonščina",
    "LANGUAGE_KOREAN": "Korejščina",
    "LANGUAGE_PERSIAN": "Perzijščina",
    "LANGUAGE_TURKISH_ISTANBUL": "Turščina (Istanbul)",
    "LANGUAGE_ARABIC": "Arabščina",
    "LANGUAGE_FRENCH": "Francoščina",
    "LANGUAGE_GERMAN": "Nemščina",
    "LANGUAGE_SPANISH": "Španščina",
    "LANGUAGE_PORTUGUESE": "Portugalščina",
    "LANGUAGE_ITALIAN": "Italijanščina",
    "LANGUAGE_RUSSIAN": "Ruščina",
    "LANGUAGE_DUTCH": "Nizozemščina",
    "LANGUAGE_VIETNAMESE": "Vietnamščina",
    "LANGUAGE_INDONESIAN": "Indonezijščina",
    "LANGUAGE_THAI": "Tajščina",
    "LANGUAGE_MALAY": "Malajščina",
    "WF1_PRICING_CUSTOM": "Cene: model reže po meri - preverite trenutne cene OpenRouter",
    "WF1_SAVE_OPENROUTER_SLOT": "Shrani režo OpenRouter",
    "WF1_PRICING_LINE": "Vhod {input} - Izhod {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Skrivnost: {secret}",
    "ZONE_VISIBILITY_TITLE": "Nadzor vidnosti con",
    "ZONE_ENABLE": "Omogoči {zone}",
    "ZONE_ENABLED_NOTE": "{zone} se lahko prikaže za dovoljene vloge po naslednjem nalaganju aplikacije.",
    "ZONE_DISABLED_NOTE": "{zone} se po naslednjem nalaganju aplikacije za uporabnike, ki niso S_Admin, obravnava kot odsotna.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin obide ta seznam vlog in vedno ohrani dostop.",
    "ZONE_ROLE_LOCKED": "Izbire vlog so začasno zaklenjene, medtem ko je ta cona onemogočena, in se bodo vrnile natanko tako, kot so shranjene, ko bo cona znova omogočena.",
    "ZONE_LCAC_CONTROL": "Nadzor LCAC",
    "ZONE_RCAC_CONTROL": "Nadzor RCAC",
    "ZONE_LCAC_DESCRIPTION": "Nadzira obstoj leve rezervirane cone in vloge, ki jo lahko vidijo.",
    "ZONE_RCAC_DESCRIPTION": "Nadzira obstoj desne rezervirane cone in vloge, ki jo lahko vidijo.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap vidnosti con zdaj bere iz zaščitene backend storitve. Spremembe se uporabijo ob naslednjem nalaganju aplikacije.",
    "ZONE_VISIBILITY_CACHED": "Backend storitev za vidnost con trenutno ni na voljo, zato so aktivne predpomnjene ali lokalne privzete vrednosti.",
    "ZONE_VISIBILITY_DEFAULTS": "Privzete vrednosti vidnosti con so aktivne, ker ni bilo mogoče naložiti nobenega backend ali predpomnjenega stanja.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap vidnosti con je bil shranjen. Za uporabo v runtime je potreben trdi ponovni zagon ali naslednje nalaganje aplikacije.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Zaščitena backend storitev ni mogla shraniti zahtevane spremembe vidnosti cone.",
    "ROLE_MEMBER": "Član",
    "ROLE_STAFF": "Osebje",
    "ROLE_ADMIN": "Skrbnik",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Omogočite obvestila za prejemanje novih sporočil.",
    "MAIN_LOG_OUT": "Odjava",
    "NOTIFICATION_NEW_MESSAGE": "Novo sporočilo",
    "NOTIFICATION_UNREAD_MESSAGE": "Imate neprebrano sporočilo.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Celoten pogled",
    "MEDIA_AUDIO_ATTACHMENT": "Zvočna priloga",
    "MEDIA_FILE_FALLBACK": "Datoteka",
    "MEDIA_DOWNLOAD_READY": "Priloga je pripravljena za prenos",
    "MEDIA_TYPE_UNSUPPORTED": "Vrsta ni podprta za celoten pogled",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Prejšnja slika",
    "MEDIA_NEXT_IMAGE_ARIA": "Naslednja slika",
    "MEDIA_OPEN_ORIGINAL": "Odpri izvirnik",
    "MEDIA_DOWNLOAD": "Prenesi",
    "MEDIA_CLOSE_ARIA": "Zapri",
    "MEDIA_PROFILE_PICTURE_ARIA": "Profilna slika osebe {name}",
    "MEDIA_PROFILE_ALT": "Profil osebe {name}",
    "MEDIA_UPLOAD_FAILED": "Nalaganje ni uspelo",
    "MEDIA_BACKEND_TOKEN_ERROR": "Napaka backend žetona",
    "MEDIA_UPLOAD_URL_MISSING": "Kritično: URL za nalaganje manjka v odgovoru backenda.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Manjka auth žeton za nalaganje v klepetu",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Zahteva za žeton nalaganja v klepetu ni uspela",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Neveljaven odgovor nalaganja v klepetu",
    "MEDIA_GCS_UPLOAD_FAILED": "Nalaganje GCS ni uspelo",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Manjka ime datoteke ali contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Manjka file_path",
    "BLOCK_NOTICE_TITLE": "Obvestilo o trajni blokadi",
    "BLOCK_NOTICE_MESSAGE": "Vaš račun je bil začasno suspendiran zaradi kršitve pravilnika.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Če menite, da je potrebno nadaljnje ukrepanje, se obrnite na",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "po e-pošti.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Neznan uporabnik",
    "GENERAL_GUEST": "Gost",
    "ADVISOR_FOR_CLIENT": "Svetovalec za {client_display_name}",
    "GUEST_FOR_CLIENT": "Gost za {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Žeton in geslo sta obvezna",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Telo zahteve mora biti JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Neveljaven ali potekel žeton povabila",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Nastavitev gesla ni uspela: manjka seja ali uporabnik",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Nastavitev gesla med prijavo ni uspela",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Ustvarjanje skrbniškega žetona ni uspelo",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Prijava ni uspela: manjka seja ali uporabnik",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registracija uspešna. Preverite e-pošto za potrditev.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Neznana napaka pri registraciji",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Neveljavna obdelava žetona",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Dostopni žeton je obvezen",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Predogled zgoščene vrednosti žetona zahteva e-poštni namig iz preusmeritvenega URL-ja",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Identitete za ta žeton ni mogoče razrešiti",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Samo User Zero lahko dostopa do storitve izbirnika WF1 LLM.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Samo User Zero lahko dostopa do storitve za nadzor vidnosti con.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Samo User Zero lahko dostopa do storitve za nadzor različice frontenda.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Samo User Zero lahko pregleda različico frontenda drugega uporabnika.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Samo User Zero lahko dostopa do storitve za nadzor brisanja klepeta.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Do storitve za nadzor jezika uporabniškega vmesnika med izvajanjem lahko dostopa samo Uporabnik Zero.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Samo User Zero lahko trajno izbriše uporabniški račun.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Neveljaven payload zahteve.",
    "API_ERROR_INTERNAL_SERVER": "Notranja napaka strežnika",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funkcija manjka v backendu (potrebno ponovno nalaganje)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Za prehode delivered/read je dovoljen samo DB RPC.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Počakajte, preden pošljete drugo sporočilo.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Sporočilo je bilo uspešno poslano.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Kontaktna storitev ni na voljo.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Pošiljanje sporočila ni uspelo.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Ime je obvezno.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-pošta je neveljavna.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Sporočilo je obvezno.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload izbirnika je obvezen.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload vidnosti con je obvezen.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload različice frontenda je obvezen.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload nadzora brisanja klepeta je obvezen.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Vsebina za nadzor jezika uporabniškega vmesnika med izvajanjem je obvezna.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID preverjenega uporabnika je obvezen.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID preverjenega uporabnika gledalca je obvezen.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID preverjenega uporabnika akterja je obvezen.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id je obvezen.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id je obvezen.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Seznam owner_user_ids je obvezen.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email je obvezen.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by je obvezen.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime iskanja je onemogočen z globalno različico frontenda.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Tega povabila v čakanju ne smete preklicati.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Tega povabila ni več mogoče preklicati, ker je uporabnik že registriran.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Povabilo v čakanju ni najdeno.",
    "INVITE_REPLY_ALREADY_MEMBER": "Čestitamo, vaš prijatelj ({invitee_email}) je že registriran v tej aplikaciji in je član tega delovnega prostora.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Za {invitee_email} je povabilo v čakanju, vendar e-pošte za ponovni poskus ni bilo mogoče sprožiti. Preverite poštne dnevnike.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Zapis povabila je bil ustvarjen za {invitee_email}, vendar dostave e-pošte ni bilo mogoče potrditi. Poskusite znova pozneje ali preverite poštne dnevnike.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Ustvarjanje zapisa povabila ni uspelo. Poskusite znova pozneje.",
    "INVITE_REPLY_SYSTEM_ERROR": "Sistemska napaka med postopkom povabila: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Napaka konfiguracije backenda: manjkajo poverilnice Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Napaka konfiguracije backenda: neveljaven URL Supabase",
    "CHAT_ERROR_ACCESS_DENIED": "Dostop zavrnjen",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Vsebina pri besedilnih sporočilih ne sme biti prazna",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "ID-ja pogovora ni bilo mogoče določiti",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Kontekst preverjanja pristnosti RPC manjka",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC je vrnil neveljaven payload sporočila",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Vstavljanje ni uspelo, podatki niso bili vrnjeni",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations mora biti seznam",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Neveljaven payload operacije",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type ni podprt",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id je obvezen",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Sporočilo ni najdeno",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Brisanje je dovoljeno samo za vaše lastno sporočilo",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Funkcija Izbriši za vse ni več na voljo za to sporočilo",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Izbriši za vse ni uspelo",
    "API_ERROR_SERVER_CONFIGURATION": "Napaka konfiguracije strežnika",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Manjka glava skrivnosti webhooka",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Nepooblaščen vir webhooka",
    "API_ERROR_BACKEND_CONFIGURATION": "Napaka konfiguracije backenda",
    "API_ERROR_MODULE_ATTRIBUTE": "Napaka atributa modula: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Napaka pred brisanjem povabila med odstranjevanjem čakajočega auth uporabnika.",
    "CHAT_ERROR_DB": "Napaka DB: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
