# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/sv.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Huvudvy",
    "APP_TITLE": "OTMEGA AI-plattform",
    "APP_SUBTITLE": "AI-rådgivare",
    "CHAT_PLACEHOLDER": "Skriv ditt meddelande...",
    "CHAT_SEND_BUTTON": "Skicka",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Rådgivaren kan göra misstag, så dubbelkolla informationen.",
    "STATUS_ONLINE": "Online",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Meny",
    "ICON_NEW_CHAT": "Ny chatt",
    "ICON_HISTORY": "Historik",
    "ICON_TEMPLATES": "Mallar",
    "ICON_SETTINGS": "Inställningar",
    "ICON_USER_PROFILE": "Användarprofil",
    "ICON_QUICK_ACTIONS": "Snabbåtgärder",
    "ICON_PINNED": "Fäst",
    "ICON_GALLERY": "Galleri",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Installera appen",
    "PWA_ANDROID_MSG": "Installera den här appen på din enhet för en bättre upplevelse och offlineåtkomst.",
    "PWA_IOS_MSG": "För att installera den här appen på din iPhone/iPad:\n1. Tryck på delningsknappen nedan\n2. Välj 'Lägg till på hemskärmen'",
    "PWA_BTN_INSTALL": "Installera",
    "PWA_BTN_LATER": "Kanske senare",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Logga in på rådgivarnätverket",
    "AUTH_HEADER_SIGNUP": "Skapa ditt enhetliga konto",
    "AUTH_HEADER_LOGIN_NETWORK": "Logga in på rådgivarnätverket",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Skapa ditt enhetliga konto",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Logga in",
    "AUTH_BUTTON_SIGNUP": "Skapa konto",
    "AUTH_BUTTON_GOOGLE": "Fortsätt med Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Glömt lösenord",
    "AUTH_BUTTON_SEND_RESET_LINK": "Skicka återställningslänk",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Har du inget konto? Registrera dig",
    "AUTH_PROMPT_LOGIN": "Har du redan ett konto? Logga in",
    "AUTH_HELPER_TEXT_SIGNUP": "Du skapar ett enhetligt konto som du kan använda för att komma åt alla rådgivare på den här plattformen.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Du skapar ett enhetligt konto som du kan använda för att komma åt alla rådgivare på den här plattformen.",
    "AUTH_HELPER_TEXT_LOGIN": "Använd samma konto (e-post/lösenord eller Google) som du använde för andra rådgivare i det här nätverket.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Använd samma konto (e-post/lösenord eller Google) som du använde för andra rådgivare i det här nätverket.",
    "AUTH_FORGOT_PASSWORD_LINK": "Glömt ditt lösenord?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Återställ ditt lösenord",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Ange din e-postadress så skickar vi en länk för att återställa ditt lösenord.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-post",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Loggar in dig...",
    "AUTH_STATUS_LOADING_SIGNUP": "Skapar ditt konto...",
    "AUTH_STATUS_LOADING_RESET": "Skickar återställningslänk...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Inloggningen lyckades! Laddar om...",
    "AUTH_STATUS_SUCCESS_RESET": "Återställningslänken har skickats. Kontrollera din e-post.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Länken för lösenordsåterställning har skickats. Kontrollera din e-post.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Ogiltig e-postadress eller ogiltigt lösenord.",
    "AUTH_ERROR_EMAIL_EXISTS": "Ett konto med den här e-postadressen finns redan i rådgivarnätverket.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Ett konto med den här e-postadressen finns redan. Logga in. Du är för närvarande medlem i:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Ett konto med den här e-postadressen finns redan i rådgivarnätverket. Stäng det här fönstret och använd avsnittet 'Login' med samma e-postadress och ditt tidigare lösenord.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Du är för närvarande medlem i:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-postadress och lösenord krävs.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Kontot skapades men medlemskapet kunde inte konfigureras. Kontakta supporten.",
    "AUTH_ERROR_DEFAULT": "Ett fel uppstod. Försök igen.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "",
    "AUTH_FORGOT_PASSWORD_ERROR": "Det gick inte att skicka återställningslänken. Försök igen.",
    "INVITE_REPLY_EMAIL_SENT": "Collabra-inbjudan skickades via e-post till din vän på {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra-inbjudan skickades på nytt via e-post till din vän på {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Visa lösenord",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Dölj lösenord",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Avbryt",
    "GENERAL_CLOSE": "Stäng",
    "GENERAL_SEND": "Skicka",
    "GENERAL_SEARCH": "Sök",
    "GENERAL_RESET": "Återställ",
    "GENERAL_ENABLE": "Aktivera",
    "GENERAL_LOADING": "Laddar...",
    "GENERAL_DELETE": "Ta bort",
    "GENERAL_DELETING": "Tar bort...",
    "GENERAL_SAVE_PASSWORD": "Spara lösenord",
    "AUTH_REMEMBER_EMAIL_LABEL": "Kom ihåg e-post",
    "GENERAL_SAVING": "Sparar...",
    "GENERAL_SENDING": "Skickar...",
    "GENERAL_REMOVING": "Tar bort...",
    "GENERAL_CONFIRM_REMOVAL": "Bekräfta borttagning",
    "GENERAL_EMPTY": "Tom",
    "GENERAL_UNAVAILABLE": "Inte tillgänglig",
    "GENERAL_ENABLED": "Aktiverad",
    "GENERAL_DISABLED": "Inaktiverad",
    "GENERAL_GRANTED": "Beviljad",
    "GENERAL_DENIED": "Nekad",
    "GENERAL_DEFAULT": "Standard",
    "GENERAL_UNSUPPORTED": "Stöds inte",
    "GENERAL_PUBLIC": "Offentlig",
    "GENERAL_PRIVATE": "Privat",
    "GENERAL_USERNAME": "Användarnamn",
    "GENERAL_EMAIL": "E-post",
    "GENERAL_YOU": "Du",
    "GENERAL_USER": "Användare",
    "GENERAL_UNKNOWN": "Okänd",
    "GENERAL_VISITOR": "Besökare",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Okänd banner",
    "GENERAL_ADVISOR_BANNER": "Rådgivarbanner",
    "GENERAL_NOT_AVAILABLE": "Ej tillgängligt",
    "GENERAL_NOT_SELECTED": "Inte valt",
    "GENERAL_NO_EMAIL_FOUND": "Ingen e-post hittades",
    "GENERAL_USER_ZERO_ONLY": "Endast User Zero",
    "GENERAL_CONNECTION_STATE": "Anslutningsstatus",
    "GENERAL_DISPLAY_ONLY": "Endast visning",
    "GENERAL_TEXTAREA": "Textområde",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Meny (LCAC)",
    "HEADER_CHAT_CCAC": "Chatt (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Snabbåtgärder (RCAC)",
    "HEADER_CHANGE_STATUS": "Ändra status",
    "HEADER_OT_COIN_BALANCE": "OT Coin-saldo",
    "HEADER_ALT_USER": "Användare",
    "STATUS_BUSY": "Upptagen",
    "STATUS_AWAY": "Borta",
    "STATUS_OFFLINE": "Offline",
    "STATUS_INVISIBLE": "Osynlig",
    "NETWORK_CHECKING_CONNECTION": "Kontrollerar anslutning...",
    "NETWORK_ONLINE_LATENCY": "Online (latens: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Nätverk: bra (tryck för att pinga)",
    "CHAT_TARGET_ALT": "Chattmål",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Sök...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Öppna profilbilden för {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Meddelandefält",
    "CHAT_TOGGLE_VIEW_ARIA": "Växla vy",
    "CHAT_ADD_USER_ARIA": "Lägg till användare",
    "CHAT_ATTACH_ARIA": "Bifoga",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Skicka",
    "CHAT_SEARCH_ARIA": "Sök",
    "CHAT_OPEN_SEARCH_ARIA": "Öppna sökning",
    "CHAT_CLOSE_SEARCH_ARIA": "Stäng sökning",
    "CHAT_ATTACHMENT_ALT": "Bilaga",
    "CHAT_PREVIEW_ALT": "Förhandsvisning",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Ta bort bilaga",
    "CHAT_REPLYING_TO": "Svarar på",
    "CHAT_CANCEL_REPLY_ARIA": "Avbryt svar",
    "CHAT_UPLOADING": "Laddar upp...",
    "CHAT_LOADING_CHATS": "Laddar chattar...",
    "CHAT_SEND_FAILED": "Sändningen misslyckades",
    "CHAT_SEND_FAILED_RETRY": "Sändningen misslyckades. Försök igen.",
    "CHAT_RETRY": "Försök igen",
    "CHAT_EDITED": "redigerad",
    "CHAT_TYPING": "Skriver",
    "CHAT_LOADING": "Laddar",
    "CHAT_PENDING_INVITATION": "Väntande inbjudan",
    "CHAT_PENDING_INVITATION_MIN": "{count} min väntande inbjudan",
    "CHAT_PENDING_INVITATION_HR": "{count} tim väntande inbjudan",
    "CHAT_PENDING_INVITATION_DAY": "{count} dag väntande inbjudan",
    "CHAT_WAITING_FOR_YOU": "{label} - Väntar på dig",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Väntar på godkännande",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Åtkomst till mikrofon nekades.",
    "CHAT_UPLOAD_FAILED": "Uppladdning misslyckades: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Uppladdning kräver internetanslutning. Försök igen när du är online.",
    "CHAT_ERROR_AUTH": "Autentiseringsfel",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Filnamn eller content_type saknas",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id eller target_id saknas",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "conversation_id saknas för uppladdning som inte är avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Ogiltig avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase-tjänstklient är inte tillgänglig",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Läskvitto för avatar är endast giltigt i rådgivarchattens kontext",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatarflödesmeddelande hittades inte eller är inte kvalificerat för läskvitto",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Det gick inte att markera avatarmeddelandet som läst",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 bilaga",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} bilagor",
    "CHAT_VOICE_NOTE": "Röstanteckning",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Chatten är inte tillgänglig. Den här användaren har blockerat dig.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Chatten är inte tillgänglig. Du har blockerat den här användaren.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Kontoåtkomst är blockerad enligt policy.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Chatten är inte tillgänglig. Det här kontot är slutgiltigt blockerat av User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Chatten är inte tillgänglig. Ömsesidig blockering är aktiv.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Chatten är inte tillgänglig på grund av blockeringspolicy.",
    "MESSAGE_PREVIEW_PHOTO": "Foto",
    "MESSAGE_PREVIEW_VOICE": "Röstmeddelande",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Fil",
    "MESSAGE_PREVIEW_MESSAGE": "Meddelande",
    "MESSAGE_PREVIEW_SYSTEM": "Systemmeddelande",
    "MESSAGE_PREVIEW_NEW": "Nytt meddelande",
    "MESSAGE_UNKNOWN_FILE": "Okänd fil",
    "MESSAGE_AUDIO_ATTACHMENT": "Ljudbilaga",
    "MESSAGE_FILE_ATTACHMENT": "Bilaga",
    "BANNER_INVITED_BY": "inbjuden av {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Sökresultat",
    "SEARCH_QUERY_LABEL": "Fråga:",
    "SEARCH_LOADING_VISIBILITY": "Laddar söksynlighet...",
    "SEARCH_NO_RESULTS": "Inga resultat hittades i aktuellt sökomfång.",
    "SHARE_WITH_COLLABRA": "Dela med Collabra",
    "SHARE_SEND_TO": "Skicka till",
    "SHARE_SELECT_ONE_BANNER": "Välj en banner",
    "SHARE_BANNER_LIST_ARIA": "Bannerlista",
    "SHARE_NO_MATCHING_BANNER": "Ingen matchande banner",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Lägg till en kommentar...",
    "SHARE_RECENT_CHATS": "Senaste chattar",
    "SHARE_LEFT_LIST": "Vänster lista",
    "SHARE_RIGHT_LIST": "Höger lista",
    "SHARE_UNTITLED_BANNER": "Namnlös banner",
    "SHARE_SHARED_CONTENT": "Delat innehåll",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Det delade innehållet kunde inte öppnas.",
    "SHARE_OPEN_BANNER_FAILED": "Det gick inte att öppna den valda bannern.",
    "SHARE_ONE_PHOTO_SELECTED": "1 foto valt",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} foton valda",
    "SHARE_ONE_FILE_SELECTED": "1 fil vald",
    "SHARE_MANY_FILES_SELECTED": "{count} filer valda",
    "FORWARD_MESSAGE_TITLE": "Vidarebefordra meddelande",
    "FORWARD_SELECT_RECIPIENTS": "Välj mottagare",
    "FORWARD_NO_OTHER_BANNER": "Ingen annan banner tillgänglig.",
    "FORWARD_SEND_TO_COUNT": "Skicka till {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Välj minst en banner.",
    "FORWARD_FAILED_DEFAULT": "Vidarebefordran misslyckades. Försök igen.",
    "FORWARD_PARTIAL_SENT": "{count} skickade. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Källmeddelandet för vidarebefordran hittades inte",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Det här meddelandet har ännu inget innehåll som kan vidarebefordras",
    "FORWARD_DESTINATION_MISSING": "Destination för vidarebefordran saknas",
    "FORWARD_MESSAGE_PREVIEW": "Vidarebefordrat meddelande",
    "MENU_PASTE": "Klistra in",
    "MENU_COPY": "Kopiera",
    "MENU_REPLY": "Svara",
    "MENU_FORWARD": "Vidarebefordra",
    "MENU_REMOVE_INVITATION": "Ta bort inbjudan",
    "MENU_REMOVE_FROM_LIST": "Ta bort från listan",
    "MENU_GOODBYE_GUEST": "",
    "MENU_ADD_TO_LIST": "Lägg till i listan",
    "MENU_REJECT_INVITATION": "Avvisa inbjudan",
    "MENU_FRONTEND_VERSION": "Frontend-version",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Bannerinformation: {title}",
    "MENU_MESSAGE_BUBBLE": "Meddelandebubbla",
    "MENU_CHAT_CANVAS_HEADER": "Chattcanvas - {zone}",
    "MENU_CANVAS_INFO": "Canvasinformation",
    "MENU_CHAT_CANVAS_SUBLABEL": "Konversationsområde / aktuell chattyta",
    "MENU_INPUT_AREA_HEADER": "Inmatningsområde - {zone}",
    "MENU_INPUT_AREA_INFO": "Information om inmatningsområde: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Nedre yta för skrivning och åtgärdsverktyg",
    "MENU_HEADER": "Rubrik - {zone}",
    "MENU_HEADER_INFO": "Rubrikinformation: {title}",
    "MENU_HEADER_DESCRIPTION": "Övre navigering och sidkontroller",
    "MENU_ZONE_HEADER": "Zon - {zone}",
    "MENU_ZONE_SPACE_INFO": "Information om zonområde",
    "MENU_EMPTY_LIST_SURFACE": "Tom/listyta",
    "MENU_BLOCK": "Blockera",
    "MENU_UNBLOCK": "Avblockera",
    "MENU_HIDE_IN_SEARCH": "Dölj i sökning",
    "MENU_UNHIDE_IN_SEARCH": "Visa i sökning",
    "MENU_VISIBLE_IN_SEARCH": "Synlig i sökning",
    "MENU_HIDDEN_IN_SEARCH": "Dold i sökning",
    "MENU_VISIBLE_IN_USER_LIST": "Synlig i användarlista",
    "MENU_HIDDEN_IN_USER_LIST": "Dold i användarlista",
    "MENU_NOT_BLOCKED": "Inte blockerad",
    "MENU_BLOCKED": "Blockerad",
    "MENU_FRONTEND_VERSION_LOADING": "Laddar...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Laddar värde per banner från backend. Inget alternativ markeras som aktivt förrän databassvaret kommer.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend-värdet kunde inte laddas. Inget betrott aktivt alternativ visas.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Det explicita databasvärdet per banner är {overrideVersion}. Globalt standardvärde är {globalDefaultVersion}. Målanvändaren måste uppdatera helt eller öppna appen igen för att start-bootstrap ska tillämpa det.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Inget explicit databasvärde per banner är lagrat. FeV2.0.0 är aktiv som standard. Globalt standardvärde är {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Det explicita databasvärdet per banner blir aktivt efter att målappen laddas om helt",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Inget explicit värde per banner är lagrat; detta är standardläget för individuell FeV2.0.0",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Det här alternativet är också lika med det nuvarande globala standardvärdet",
    "MENU_DELETE_PERMANENT_CONFIRM": "Ta bort {target} permanent från databasen? Detta tar bort kontot, chatthistorik, beroenden och tvingar fram en helt ny inbjudningsväg för framtida återinträde.",
    "MENU_DELETE_PERMANENTLY": "Ta bort permanent",
    "MENU_REFRESH_PAGE": "Uppdatera sidan",
    "MENU_LOG_OFF": "Logga ut",
    "MENU_HARD_RELOAD": "Hård omladdning",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-post (adminanvändare)",
    "AUTH_PASSWORD_PLACEHOLDER": "Lösenord",
    "AUTH_CONNECTING": "Ansluter...",
    "AUTH_SIGNING_OUT": "Loggar ut...",
    "AUTH_BACK_TO_LOGIN": "Tillbaka till inloggning",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Ogiltigt serversvar: ingen token hittades.",
    "AUTH_LOGIN_FAILED": "Inloggning misslyckades",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Lösenorden stämmer inte överens.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Lösenorden stämmer inte överens!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Lösenorden måste stämma exakt.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Nytt lösenord",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Bekräfta lösenord",
    "AUTH_CHANGE_PASSWORD": "Ändra lösenord",
    "AUTH_SAVING_PASSWORD": "Sparar...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Lösenordet har uppdaterats.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Det går inte att ändra lösenord just nu.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Du måste vara inloggad för att ändra ditt lösenord.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Växla synlighet för nytt lösenord",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Växla synlighet för lösenordsbekräftelse",
    "REGISTER_TITLE": "Slutför registrering",
    "REGISTER_SUBTITLE": "Ange ditt lösenord manuellt.",
    "REGISTER_CREATING_ACCOUNT": "Skapar konto...",
    "REGISTER_FINISH_SETUP": "Slutför konfiguration",
    "REGISTER_FAILED_SET_PASSWORD": "Det gick inte att ange lösenord",
    "INVITE_EMAIL_INSTRUCTION": "Ange inbjuden persons e-postadress (format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Bjud in",
    "INVITE_EMAIL_REQUIRED": "Ange den inbjudna personens e-postadress.",
    "INVITE_EMAIL_INVALID": "Ogiltigt e-postformat. Använd: user@example.com",
    "PENDING_INVITATION_TITLE": "Väntande inbjudan",
    "PENDING_INVITATION_REMOVE_QUESTION": "Ta bort den här väntande inbjudan från databasen?",
    "PENDING_INVITATION_KEEP": "Behåll inbjudan",
    "PENDING_INVITATION_REMOVAL_FAILED": "Borttagning misslyckades.",
    "REMOVE_FROM_LIST_TITLE": "Ta bort från listan",
    "REMOVE_FROM_LIST_WARNING": "Ta bort den här användaren från båda listorna nu? Chattåtkomsten bryts omedelbart. Den enda vägen tillbaka är en ny inbjudan.",
    "REMOVE_FROM_LIST_KEEP": "Behåll användaren i listan",
    "REMOVE_FROM_LIST_FAILED": "Borttagning från listan misslyckades.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Inställning och live-status",
    "PERMISSION_DIALOG_ARIA": "Inställning och live-status",
    "PERMISSION_TRIGGER_ARIA": "Utlösare för inställningspopup",
    "PERMISSION_CLOSE_ARIA": "Stäng behörighetspopup",
    "PERMISSION_LIVE_STATUS": "Live-status",
    "PERMISSION_SYSTEM_PERMISSION": "Systembehörighet",
    "PERMISSION_APP_PUSH": "App-push",
    "PERMISSION_LOCATION_PERMISSION": "Platsbehörighet",
    "PERMISSION_APP_LOCATION": "App-plats",
    "PERMISSION_CONTROLS": "Behörighetskontroller",
    "PERMISSION_PUSH_NOTIFICATIONS": "Pushnotiser",
    "PERMISSION_LOCATION_ACCESS": "Platsåtkomst",
    "PERMISSION_IN_APP_SETTINGS": "Inställningar i appen",
    "PERMISSION_ALERT_SOUND": "Aviseringsljud",
    "PERMISSION_APP_BADGE": "App-bricka",
    "PERMISSION_PASSWORD_SETTINGS": "Lösenordsinställningar",
    "PERMISSION_NAVIGATION_STATUS": "Navigeringsstatus",
    "PERMISSION_SELECTED_ZONE": "Vald zon",
    "PERMISSION_STAGED_CHAT_BANNER": "Förberedd chattbanner",
    "PERMISSION_CANVAS_CONTENT": "Canvasinnehåll",
    "PERMISSION_YOUR_DEVICES": "Dina enheter ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Uppdatera enhetslista",
    "PERMISSION_REFRESH_LIST": "Uppdatera lista",
    "PERMISSION_NO_REGISTERED_DEVICES": "Inga registrerade enheter hittades.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Ändra storlek på inställningspopup",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Växla pushnotiser",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Växla platsåtkomst",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Växla aviseringsljud",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Växla app-bricka",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Växla profilsynlighet",
    "PERMISSION_OFF_IN_V1": "Av i v1",
    "PERMISSION_CHAT": "Chatt",
    "PERMISSION_BANNER_LIST": "Bannerlista",
    "PERMISSION_PUSH_DISABLED_V1": "Pushnotiser är inaktiverade för v1-versionen på Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Pushnotiser är PÅ för den här enheten.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Systemnotiser är blockerade. Tryck för att öppna inställningshjälpen.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Slå PÅ för att förbättra leveranssäkerheten.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "För att inaktivera systemnotiser öppnar du webbläsarens/webbplatsens notisinställningar och blockerar den här webbplatsen.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "För att ändra systembehörighet för notiser öppnar du webbläsarens/webbplatsens notisinställningar och tillåter den här webbplatsen.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Platsåtkomst är PÅ för distansbaserad LCAC-sortering och kartpositionering.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Plats-API stöds inte i den här miljön.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Platsåtkomst är blockerad. Tryck för att öppna inställningshjälpen.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Slå PÅ för att tillåta exakt distansbaserad LCAC-sortering och kartpositionering i appen.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Platsåtkomst stöds inte i den här miljön.",
    "PERMISSION_LOCATION_DISABLE_HELP": "För att inaktivera platsåtkomst öppnar du webbläsarens/webbplatsens platsinställningar och blockerar den här webbplatsen.",
    "PERMISSION_LOCATION_ALLOW_HELP": "För att aktivera platsåtkomst för distanssortering och kartpositionering i appen öppnar du webbläsarens/webbplatsens platsinställningar och tillåter den här webbplatsen.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Det går inte att ladda registrerade enheter just nu.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Laddar UI-brygga...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Laddar lokal brygga...",
    "RUNTIME_LOADING_BACKEND": "Laddar backend...",
    "RUNTIME_LOADING": "Laddar...",
    "RUNTIME_LOADING_FROM_DATABASE": "Laddar från databas...",
    "RUNTIME_BACKEND_CONNECTED": "Backend ansluten",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Cachad fallback aktiv",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Standardfallback aktiv",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallback-standardvärden aktiva",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Sparar via backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Sparat i backend-tjänsten",
    "RUNTIME_SAVE_FAILED": "Sparande misslyckades",
    "RUNTIME_LOAD_FAILED": "Laddning misslyckades",
    "RUNTIME_CONNECTED": "Ansluten",
    "RUNTIME_LOGIN_REQUIRED": "Inloggning krävs",
    "RUNTIME_SAVED": "Sparat",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI redo - runtime väntar",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Den skyddade backend-väljartjänsten avvisade eller kunde inte spara det begärda modellalternativet.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Den skyddade backend-väljartjänsten avvisade eller kunde inte spara den begärda WF1-dirigeringsändringen.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Väljaren läser nu aktiv konfiguration, Qwen-dirigering och tillåtna alternativ från den skyddade backend-tjänsten.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend-väljartjänsten är inte tillgänglig just nu, så det senaste cachade väljartillståndet används.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Väljarens standardvärden är aktiva eftersom inget backend- eller cachat väljartillstånd kunde laddas.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Den skyddade backend-väljartjänsten uppdaterade den aktiva WF1-dirigeringskonfigurationen och uppdaterade runtime-domäncachen.",
    "FRONTEND_VERSION_TITLE": "Frontend-version",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Den här väljaren styr den aktiva frontend-versionen för alla användare. FeV2.0.0 är aktiv.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Den här väljaren läser den aktiva frontend-versionen från config_domain_registry. Runtime löses till FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend-konfigurationen för frontend-version kunde inte laddas, så det kodade standardvärdet FeV2.0.0 är aktivt tills start-bootstrap kan läsa den skyddade tjänsten igen.",
    "FRONTEND_VERSION_HELPER_SAVED": "Den aktiva frontend-versionen sparades i config_domain_registry. En fullständig uppdatering eller nästa appinläsning tillämpar runtime-värdet.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend-tjänsten för kontroll av frontend-version kunde inte spara den begärda globala versionen.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktiv frontend-version.",
    "CHAT_DELETE_WINDOW_TITLE": "Fönster för chattborttagning",
    "CHAT_DELETE_HELPER": "Det här värdet styr tillgänglighetsfönstret för Ta bort för alla i sekunder. Backend-skyddet ändras omedelbart efter sparande. Bubblans synlighet ändras efter en fullständig uppdatering eller nästa appinläsning.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend-tjänsten för kontroll av chattborttagning kunde inte laddas, så det kodade standardvärdet förblir aktivt tills start-bootstrap kan läsa den skyddade tjänsten igen.",
    "CHAT_DELETE_HELPER_SAVED": "Tillgänglighetsfönstret för Ta bort för alla sparades i config_domain_registry. Backend-skyddet ändras omedelbart. Bubblans synlighet ändras efter en fullständig uppdatering eller nästa appinläsning.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend-tjänsten för kontroll av chattborttagning kunde inte spara det begärda fönstervärdet.",
    "CHAT_DELETE_WINDOW_LABEL": "Fönster för Ta bort för alla",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} sek",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Lagra värdet i hela sekunder. Nuvarande produktionsvärde är 86400 sekunder = 1 dag.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Fönstersekunder",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Ange ett heltal som är större än eller lika med 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Spara borttagningsfönster",
    "GUEST_BANNER_CONTROL_TITLE": "",
    "GUEST_BANNER_CONTROL_LABEL": "",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "",
    "GUEST_BANNER_CONTROL_HELPER": "",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "",
    "GUEST_BANNER_PENDING_TTL_INVALID": "",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "",
    "GUEST_QR_LOADING": "",
    "GUEST_QR_READY": "",
    "GUEST_QR_ALT": "",
    "GUEST_QR_LOAD_FAILED": "",
    "GUEST_SESSION_ACTIVE": "",
    "GUEST_PUBLIC_TITLE": "",
    "GUEST_PUBLIC_CONNECTING": "",
    "GUEST_PUBLIC_CONNECTED": "",
    "GUEST_PUBLIC_UNAVAILABLE": "",
    "GUEST_PUBLIC_SEND_FAILED": "",
    "UI_TEXTS_RUNTIME_TITLE": "",
    "UI_TEXTS_RUNTIME_BACKEND": "",
    "UI_TEXTS_RUNTIME_CACHED": "",
    "UI_TEXTS_RUNTIME_DEFAULTS": "",
    "UI_TEXTS_RUNTIME_SAVED": "",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "",
    "PROFILE_VISIBILITY_TITLE": "Profilsynlighet",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Du måste vara inloggad för att hantera kontosynlighet.",
    "PROFILE_VISIBILITY_HELPER": "Den här reglaget uppdaterar endast ditt kontos synlighetsstatus. Upptäckbarhet och bannerlistbeteende förblir oförändrade i den här fasen.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Profilsynlighet kunde inte laddas just nu.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Profilsynlighet kunde inte uppdateras just nu.",
    "PROFILE_VISIBILITY_SAVED": "Ditt kontos synlighet är nu {visibility}. Upptäckbarhetsflaggor förblir oförändrade i den här fasen.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Offentligt konto",
    "PROFILE_VISIBILITY_STORED": "Lagrad synlighet",
    "WF1_MODEL_CONTROL_TITLE": "WF1-modellkontroll",
    "WF1_ENABLE_TRANSLATION": "Aktivera översättning / pivot",
    "WF1_TRANSLATION_ACTIVE": "AI-översättning är aktiv.",
    "WF1_TRANSLATION_INACTIVE": "WF1 fortsätter att köras men källtexten kopieras och pivot markeras som inaktiv.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktiv runtime-plats",
    "WF1_ALLOW_SAME_LANGUAGE": "Tillåt AI för språkpar med samma språk",
    "WF1_SAME_LANGUAGE_ACTIVE": "Språkpar med samma språk följer normal WF1-dirigering.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Språkpar med samma språk kringgår AI och lagrar Ingen pivot som aktivt språk.",
    "WF1_QWEN_ROUTING": "Qwen-pardirigering",
    "WF1_QWEN_ROUTING_HELPER": "Språk som markeras nedan använder Qwen-Max när paret antingen är samma markerade språk, ett markerat språk med engelska eller två markerade icke-engelska språk. Annars förblir den valda primära modellen aktiv.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter-testplats",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter-testplats - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Endast kvalitetstest",
    "WF1_OPENROUTER_HELPER": "Den här platsen kan endast redigeras för tillfälliga OpenRouter-kvalitetstester. Den ändrar inte den operativa Qwen-pardirigeringsvägen om inte själva platsen blir den aktiva modellen.",
    "WF1_LABEL": "Etikett",
    "WF1_PRODUCT": "Produkt",
    "WF1_MODEL": "Modell",
    "WF1_PROVIDER_OPENROUTER": "Leverantör: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Hemlighet: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter-testplats · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max via OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Googles listpris",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI-listpris",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter-listpris",
    "LANGUAGE_ENGLISH": "Engelska",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Kinesiska (förenklad)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Kinesiska (traditionell)",
    "LANGUAGE_JAPANESE": "Japanska",
    "LANGUAGE_KOREAN": "Koreanska",
    "LANGUAGE_PERSIAN": "Persiska",
    "LANGUAGE_TURKISH_ISTANBUL": "Turkiska (Istanbul)",
    "LANGUAGE_ARABIC": "Arabiska",
    "LANGUAGE_FRENCH": "Franska",
    "LANGUAGE_GERMAN": "Tyska",
    "LANGUAGE_SPANISH": "Spanska",
    "LANGUAGE_PORTUGUESE": "Portugisiska",
    "LANGUAGE_ITALIAN": "Italienska",
    "LANGUAGE_RUSSIAN": "Ryska",
    "LANGUAGE_DUTCH": "Nederländska",
    "LANGUAGE_VIETNAMESE": "Vietnamesiska",
    "LANGUAGE_INDONESIAN": "Indonesiska",
    "LANGUAGE_THAI": "Thailändska",
    "LANGUAGE_MALAY": "Malajiska",
    "WF1_PRICING_CUSTOM": "Prissättning: anpassad platsmodell - kontrollera aktuell OpenRouter-prissättning",
    "WF1_SAVE_OPENROUTER_SLOT": "Spara OpenRouter-plats",
    "WF1_PRICING_LINE": "Inmatning {input} - Utmatning {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Hemlighet: {secret}",
    "ZONE_VISIBILITY_TITLE": "Kontroll av zonsynlighet",
    "ZONE_ENABLE": "Aktivera {zone}",
    "ZONE_ENABLED_NOTE": "{zone} kan visas för tillåtna roller efter nästa appinläsning.",
    "ZONE_DISABLED_NOTE": "{zone} behandlas som frånvarande för icke-S_Admin-användare efter nästa appinläsning.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin kringgår den här rollistan och behåller alltid åtkomst.",
    "ZONE_ROLE_LOCKED": "Rollval är tillfälligt låsta medan den här zonen är inaktiverad och återgår exakt som sparade när zonen aktiveras igen.",
    "ZONE_LCAC_CONTROL": "LCAC-kontroll",
    "ZONE_RCAC_CONTROL": "RCAC-kontroll",
    "ZONE_LCAC_DESCRIPTION": "Styr existensen av den vänstra reserverade zonen och rollerna som kan se den.",
    "ZONE_RCAC_DESCRIPTION": "Styr existensen av den högra reserverade zonen och rollerna som kan se den.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap för zonsynlighet läser nu från den skyddade backend-tjänsten. Ändringar tillämpas vid nästa appinläsning.",
    "ZONE_VISIBILITY_CACHED": "Backend-tjänsten för zonsynlighet är inte tillgänglig just nu, så cachade eller lokala standardvärden är aktiva.",
    "ZONE_VISIBILITY_DEFAULTS": "Standardvärden för zonsynlighet är aktiva eftersom inget backend- eller cachat tillstånd kunde laddas.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap för zonsynlighet sparades. Hård omladdning eller nästa appinläsning krävs för runtime-tillämpning.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Den skyddade backend-tjänsten kunde inte spara den begärda ändringen av zonsynlighet.",
    "ROLE_MEMBER": "Medlem",
    "ROLE_STAFF": "Personal",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Aktivera notiser för att ta emot nya meddelanden.",
    "MAIN_LOG_OUT": "Logga ut",
    "NOTIFICATION_NEW_MESSAGE": "Nytt meddelande",
    "NOTIFICATION_UNREAD_MESSAGE": "Du har ett oläst meddelande.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Fullständig vy",
    "MEDIA_AUDIO_ATTACHMENT": "Ljudbilaga",
    "MEDIA_FILE_FALLBACK": "Fil",
    "MEDIA_DOWNLOAD_READY": "Bilaga redo för nedladdning",
    "MEDIA_TYPE_UNSUPPORTED": "Typ stöds inte i fullständig vy",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Föregående bild",
    "MEDIA_NEXT_IMAGE_ARIA": "Nästa bild",
    "MEDIA_OPEN_ORIGINAL": "Öppna original",
    "MEDIA_DOWNLOAD": "Ladda ner",
    "MEDIA_CLOSE_ARIA": "Stäng",
    "MEDIA_PROFILE_PICTURE_ARIA": "Profilbild för {name}",
    "MEDIA_PROFILE_ALT": "Profil för {name}",
    "MEDIA_UPLOAD_FAILED": "Uppladdning misslyckades",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend-tokenfel",
    "MEDIA_UPLOAD_URL_MISSING": "Kritiskt: uppladdnings-URL saknas i backend-svaret.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Autentiseringstoken saknas för chattuppladdning",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Begäran om chattuppladdningstoken misslyckades",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Ogiltigt svar för chattuppladdning",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS-uppladdning misslyckades",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Filnamn eller contentType saknas",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path saknas",
    "BLOCK_NOTICE_TITLE": "Meddelande om permanent blockering",
    "BLOCK_NOTICE_MESSAGE": "Ditt konto har tillfälligt stängts av på grund av en policyöverträdelse.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Om du anser att detta kräver uppföljning, kontakta",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "via e-post.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Okänd användare",
    "GENERAL_GUEST": "Gäst",
    "ADVISOR_FOR_CLIENT": "Rådgivare för {client_display_name}",
    "GUEST_FOR_CLIENT": "",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token och lösenord krävs",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Begärans brödtext måste vara JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Ogiltig eller utgången inbjudningstoken",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Lösenordsinställning misslyckades: session eller användare saknas",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Lösenordsinställning misslyckades under inloggning",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Generering av admin-token misslyckades",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Inloggning misslyckades: session eller användare saknas",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registreringen lyckades. Kontrollera e-post för verifiering.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Registrering misslyckades av okänd anledning",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Ogiltig tokenbearbetning",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Åtkomsttoken krävs",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Förhandsvisning av tokenhash kräver e-posttips från omdirigerings-URL",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Det går inte att fastställa identiteten för den här tokenen",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Endast User Zero kan komma åt WF1 LLM-väljartjänsten.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Endast User Zero kan komma åt kontrolltjänsten för zonsynlighet.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Endast User Zero kan komma åt kontrolltjänsten för frontend-version.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Endast User Zero kan inspektera en annan användares frontend-version.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Endast User Zero kan komma åt kontrolltjänsten för chattborttagning.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Endast User Zero kan permanent ta bort ett användarkonto.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Ogiltig begäranspayload.",
    "API_ERROR_INTERNAL_SERVER": "Internt serverfel",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Funktion saknas i backend (omladdning krävs)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Endast DB RPC är tillåtet för delivered/read-övergångar.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Vänta innan du skickar ett nytt meddelande.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Meddelandet har skickats.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Kontakttjänsten är inte tillgänglig.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Meddelandesändning misslyckades.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Namn krävs.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-postadressen är ogiltig.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Meddelande krävs.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Väljarpayload krävs.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload för zonsynlighet krävs.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload för frontend-version krävs.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload för kontroll av chattborttagning krävs.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Autentiserat användar-id krävs.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Autentiserat visningsanvändar-id krävs.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Autentiserat aktörsanvändar-id krävs.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id krävs.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id krävs.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids-lista krävs.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email krävs.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by krävs.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Sökruntime är inaktiverad av global frontend-version.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Du har inte behörighet att avbryta den här väntande inbjudan.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Den här inbjudan kan inte längre avbrytas eftersom användaren redan är registrerad.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Väntande inbjudan hittades inte.",
    "INVITE_REPLY_ALREADY_MEMBER": "Grattis, din vän ({invitee_email}) är redan registrerad i den här appen och är medlem i den här arbetsytan.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "En inbjudan väntar för {invitee_email}, men e-postmeddelandet för nytt försök kunde inte utlösas. Kontrollera e-postloggarna.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Inbjudningsposten skapades för {invitee_email}, men e-postleveransen kunde inte bekräftas. Försök igen senare eller kontrollera e-postloggarna.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Det gick inte att skapa inbjudningsposten. Försök igen senare.",
    "INVITE_REPLY_SYSTEM_ERROR": "Systemfel under inbjudningsprocessen: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend-konfigurationsfel: Supabase-uppgifter saknas",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend-konfigurationsfel: ogiltig Supabase-URL",
    "CHAT_ERROR_ACCESS_DENIED": "Åtkomst nekad",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Innehåll får inte vara tomt för textmeddelanden",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Kunde inte fastställa konversations-ID",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC-autentiseringskontext saknas",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC returnerade ogiltig meddelandepayload",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Infogning misslyckades, inga data returnerades",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations måste vara en lista",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Ogiltig åtgärdspayload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type stöds inte",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id krävs",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Meddelandet hittades inte",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Borttagning är endast tillåten för ditt eget meddelande",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Ta bort för alla är inte längre tillgängligt för det här meddelandet",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Ta bort för alla misslyckades",
    "API_ERROR_SERVER_CONFIGURATION": "Serverkonfigurationsfel",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Webhook-hemlighetsrubrik saknas",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Obehörig webhook-källa",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend-konfigurationsfel",
    "API_ERROR_MODULE_ATTRIBUTE": "Modulattributfel: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Misslyckades före borttagning av inbjudan vid borttagning av väntande auth-användare.",
    "CHAT_ERROR_DB": "DB-fel: {error}",
}
