# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/th.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "หลัก",
    "APP_TITLE": "แพลตฟอร์ม AI ของ OTMEGA",
    "APP_SUBTITLE": "ที่ปรึกษา AI",
    "CHAT_PLACEHOLDER": "พิมพ์ข้อความของคุณ...",
    "CHAT_SEND_BUTTON": "ส่ง",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 ที่ปรึกษาอาจผิดพลาดได้ โปรดตรวจสอบอีกครั้ง",
    "STATUS_ONLINE": "ออนไลน์",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "เมนู",
    "ICON_NEW_CHAT": "แชทใหม่",
    "ICON_HISTORY": "ประวัติ",
    "ICON_TEMPLATES": "เทมเพลต",
    "ICON_SETTINGS": "การตั้งค่า",
    "ICON_USER_PROFILE": "โปรไฟล์ผู้ใช้",
    "ICON_QUICK_ACTIONS": "การดำเนินการด่วน",
    "ICON_PINNED": "ปักหมุด",
    "ICON_GALLERY": "แกลเลอรี",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "ติดตั้งแอป",
    "PWA_ANDROID_MSG": "ติดตั้งแอปนี้บนอุปกรณ์ของคุณเพื่อประสบการณ์ที่ดีขึ้นและการเข้าถึงแบบออฟไลน์",
    "PWA_IOS_MSG": "หากต้องการติดตั้งแอปนี้บน iPhone/iPad ของคุณ:\n1. แตะปุ่มแชร์ด้านล่าง\n2. เลือก 'เพิ่มไปยังหน้าจอหลัก'",
    "PWA_BTN_INSTALL": "ติดตั้ง",
    "PWA_BTN_LATER": "ไว้ภายหลัง",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "เข้าสู่ระบบเครือข่ายที่ปรึกษา",
    "AUTH_HEADER_SIGNUP": "สร้างบัญชีรวมของคุณ",
    "AUTH_HEADER_LOGIN_NETWORK": "เข้าสู่ระบบเครือข่ายที่ปรึกษา",
    "AUTH_HEADER_SIGNUP_UNIFIED": "สร้างบัญชีรวมของคุณ",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "เข้าสู่ระบบ",
    "AUTH_BUTTON_SIGNUP": "สร้างบัญชี",
    "AUTH_BUTTON_GOOGLE": "ดำเนินการต่อด้วย Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "ลืมรหัสผ่าน",
    "AUTH_BUTTON_SEND_RESET_LINK": "ส่งลิงก์รีเซ็ต",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "ยังไม่มีบัญชี? สมัครใช้งาน",
    "AUTH_PROMPT_LOGIN": "มีบัญชีอยู่แล้ว? เข้าสู่ระบบ",
    "AUTH_HELPER_TEXT_SIGNUP": "คุณกำลังสร้างบัญชีรวมที่สามารถใช้เข้าถึงที่ปรึกษาทั้งหมดในแพลตฟอร์มนี้",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "คุณกำลังสร้างบัญชีรวมที่สามารถใช้เข้าถึงที่ปรึกษาทั้งหมดในแพลตฟอร์มนี้",
    "AUTH_HELPER_TEXT_LOGIN": "ใช้บัญชีเดิม (อีเมล/รหัสผ่าน หรือ Google) ที่คุณใช้กับที่ปรึกษาอื่นในเครือข่ายนี้",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "ใช้บัญชีเดิม (อีเมล/รหัสผ่าน หรือ Google) ที่คุณใช้กับที่ปรึกษาอื่นในเครือข่ายนี้",
    "AUTH_FORGOT_PASSWORD_LINK": "ลืมรหัสผ่านใช่ไหม?",
    "AUTH_FORGOT_PASSWORD_TITLE": "รีเซ็ตรหัสผ่านของคุณ",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "กรอกที่อยู่อีเมลของคุณ แล้วเราจะส่งลิงก์สำหรับรีเซ็ตรหัสผ่านให้คุณ",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "อีเมล",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "กำลังเข้าสู่ระบบ...",
    "AUTH_STATUS_LOADING_SIGNUP": "กำลังสร้างบัญชีของคุณ...",
    "AUTH_STATUS_LOADING_RESET": "กำลังส่งลิงก์รีเซ็ต...",
    "AUTH_STATUS_SUCCESS_LOGIN": "เข้าสู่ระบบสำเร็จ! กำลังโหลดใหม่...",
    "AUTH_STATUS_SUCCESS_RESET": "ส่งลิงก์รีเซ็ตสำเร็จแล้ว โปรดตรวจสอบอีเมลของคุณ",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "ส่งลิงก์รีเซ็ตรหัสผ่านสำเร็จแล้ว โปรดตรวจสอบอีเมลของคุณ",

    "AUTH_ERROR_INVALID_CREDENTIALS": "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
    "AUTH_ERROR_EMAIL_EXISTS": "มีบัญชีที่ใช้อีเมลนี้อยู่แล้วในเครือข่ายที่ปรึกษา",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "มีบัญชีที่ใช้อีเมลนี้อยู่แล้ว โปรดเข้าสู่ระบบ ตอนนี้คุณเป็นสมาชิกของ:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "มีบัญชีที่ใช้อีเมลนี้อยู่แล้วในเครือข่ายที่ปรึกษา โปรดปิดหน้าต่างนี้และใช้ส่วน 'เข้าสู่ระบบ' ด้วยอีเมลเดิมและรหัสผ่านก่อนหน้าของคุณ",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "ตอนนี้คุณเป็นสมาชิกของ:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "ต้องระบุอีเมลและรหัสผ่าน",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "สร้างบัญชีแล้ว แต่ตั้งค่าการเป็นสมาชิกไม่สำเร็จ โปรดติดต่อฝ่ายสนับสนุน",
    "AUTH_ERROR_DEFAULT": "เกิดข้อผิดพลาด โปรดลองอีกครั้ง",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "",
    "AUTH_FORGOT_PASSWORD_ERROR": "ส่งลิงก์รีเซ็ตไม่สำเร็จ โปรดลองอีกครั้ง",
    "INVITE_REPLY_EMAIL_SENT": "ส่งอีเมลเชิญ Collabra ไปยังเพื่อนของคุณที่ {invitee_email} แล้ว",
    "INVITE_REPLY_EMAIL_RESENT": "ส่งอีเมลเชิญ Collabra ซ้ำไปยังเพื่อนของคุณที่ {invitee_email} แล้ว",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "แสดงรหัสผ่าน",
    "AUTH_PASSWORD_TOGGLE_HIDE": "ซ่อนรหัสผ่าน",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "ตกลง",
    "GENERAL_CANCEL": "ยกเลิก",
    "GENERAL_CLOSE": "ปิด",
    "GENERAL_SEND": "ส่ง",
    "GENERAL_SEARCH": "ค้นหา",
    "GENERAL_RESET": "รีเซ็ต",
    "GENERAL_ENABLE": "เปิดใช้งาน",
    "GENERAL_LOADING": "กำลังโหลด...",
    "GENERAL_DELETE": "ลบ",
    "GENERAL_DELETING": "กำลังลบ...",
    "GENERAL_SAVE_PASSWORD": "บันทึกรหัสผ่าน",
    "AUTH_REMEMBER_EMAIL_LABEL": "จดจำอีเมล",
    "GENERAL_SAVING": "กำลังบันทึก...",
    "GENERAL_SENDING": "กำลังส่ง...",
    "GENERAL_REMOVING": "กำลังนำออก...",
    "GENERAL_CONFIRM_REMOVAL": "ยืนยันการนำออก",
    "GENERAL_EMPTY": "ว่าง",
    "GENERAL_UNAVAILABLE": "ไม่พร้อมใช้งาน",
    "GENERAL_ENABLED": "เปิดใช้งานแล้ว",
    "GENERAL_DISABLED": "ปิดใช้งานแล้ว",
    "GENERAL_GRANTED": "อนุญาตแล้ว",
    "GENERAL_DENIED": "ปฏิเสธแล้ว",
    "GENERAL_DEFAULT": "ค่าเริ่มต้น",
    "GENERAL_UNSUPPORTED": "ไม่รองรับ",
    "GENERAL_PUBLIC": "สาธารณะ",
    "GENERAL_PRIVATE": "ส่วนตัว",
    "GENERAL_USERNAME": "ชื่อผู้ใช้",
    "GENERAL_EMAIL": "อีเมล",
    "GENERAL_YOU": "คุณ",
    "GENERAL_USER": "ผู้ใช้",
    "GENERAL_UNKNOWN": "ไม่ทราบ",
    "GENERAL_VISITOR": "ผู้เยี่ยมชม",
    "GENERAL_PROFILE": "โปรไฟล์",
    "GENERAL_BANNER": "แบนเนอร์",
    "GENERAL_UNKNOWN_BANNER": "แบนเนอร์ที่ไม่ทราบ",
    "GENERAL_ADVISOR_BANNER": "แบนเนอร์ที่ปรึกษา",
    "GENERAL_NOT_AVAILABLE": "ไม่มีข้อมูล",
    "GENERAL_NOT_SELECTED": "ยังไม่ได้เลือก",
    "GENERAL_NO_EMAIL_FOUND": "ไม่พบอีเมล",
    "GENERAL_USER_ZERO_ONLY": "เฉพาะ User Zero เท่านั้น",
    "GENERAL_CONNECTION_STATE": "สถานะการเชื่อมต่อ",
    "GENERAL_DISPLAY_ONLY": "แสดงผลเท่านั้น",
    "GENERAL_TEXTAREA": "พื้นที่ข้อความ",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "เมนู (LCAC)",
    "HEADER_CHAT_CCAC": "แชท (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "การดำเนินการด่วน (RCAC)",
    "HEADER_CHANGE_STATUS": "เปลี่ยนสถานะ",
    "HEADER_OT_COIN_BALANCE": "ยอดคงเหลือ OT Coin",
    "HEADER_ALT_USER": "ผู้ใช้",
    "STATUS_BUSY": "ไม่ว่าง",
    "STATUS_AWAY": "ไม่อยู่",
    "STATUS_OFFLINE": "ออฟไลน์",
    "STATUS_INVISIBLE": "ล่องหน",
    "NETWORK_CHECKING_CONNECTION": "กำลังตรวจสอบการเชื่อมต่อ...",
    "NETWORK_ONLINE_LATENCY": "ออนไลน์ (เวลาแฝง: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "เครือข่าย: ดี (แตะเพื่อ ping)",
    "CHAT_TARGET_ALT": "เป้าหมายแชท",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "ค้นหา...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "เปิดรูปโปรไฟล์ของ {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "ช่องกรอกข้อความ",
    "CHAT_TOGGLE_VIEW_ARIA": "สลับมุมมอง",
    "CHAT_ADD_USER_ARIA": "เพิ่มผู้ใช้",
    "CHAT_ATTACH_ARIA": "แนบไฟล์",
    "CHAT_MIC_ARIA": "ไมโครโฟน",
    "CHAT_SEND_ARIA": "ส่ง",
    "CHAT_SEARCH_ARIA": "ค้นหา",
    "CHAT_OPEN_SEARCH_ARIA": "เปิดการค้นหา",
    "CHAT_CLOSE_SEARCH_ARIA": "ปิดการค้นหา",
    "CHAT_ATTACHMENT_ALT": "ไฟล์แนบ",
    "CHAT_PREVIEW_ALT": "ตัวอย่าง",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "นำไฟล์แนบออก",
    "CHAT_REPLYING_TO": "กำลังตอบกลับ",
    "CHAT_CANCEL_REPLY_ARIA": "ยกเลิกการตอบกลับ",
    "CHAT_UPLOADING": "กำลังอัปโหลด...",
    "CHAT_LOADING_CHATS": "กำลังโหลดแชท...",
    "CHAT_SEND_FAILED": "ส่งไม่สำเร็จ",
    "CHAT_SEND_FAILED_RETRY": "ส่งไม่สำเร็จ โปรดลองอีกครั้ง",
    "CHAT_RETRY": "ลองอีกครั้ง",
    "CHAT_EDITED": "แก้ไขแล้ว",
    "CHAT_TYPING": "กำลังพิมพ์",
    "CHAT_LOADING": "กำลังโหลด",
    "CHAT_PENDING_INVITATION": "คำเชิญที่รอดำเนินการ",
    "CHAT_PENDING_INVITATION_MIN": "{count} นาที คำเชิญที่รอดำเนินการ",
    "CHAT_PENDING_INVITATION_HR": "{count} ชม. คำเชิญที่รอดำเนินการ",
    "CHAT_PENDING_INVITATION_DAY": "{count} วัน คำเชิญที่รอดำเนินการ",
    "CHAT_WAITING_FOR_YOU": "{label} - กำลังรอคุณ",
    "CHAT_PENDING_ACCEPTANCE": "{label} - รอการยอมรับ",
    "CHAT_MICROPHONE_ACCESS_DENIED": "การเข้าถึงไมโครโฟนถูกปฏิเสธ",
    "CHAT_UPLOAD_FAILED": "อัปโหลดไม่สำเร็จ: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "การอัปโหลดต้องใช้การเชื่อมต่ออินเทอร์เน็ต โปรดลองอีกครั้งเมื่อคุณออนไลน์",
    "CHAT_ERROR_AUTH": "ข้อผิดพลาดการยืนยันตัวตน",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "ไม่มีชื่อไฟล์หรือ content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "ไม่มี conversation_id หรือ target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "ไม่มี conversation_id สำหรับการอัปโหลดที่ไม่ใช่อวาตาร์",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path ของอวาตาร์ไม่ถูกต้อง",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "ไคลเอนต์บริการ Supabase ไม่พร้อมใช้งาน",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "การยืนยันว่าอ่านอวาตาร์ใช้ได้เฉพาะในบริบทแชทที่ปรึกษาเท่านั้น",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "ไม่พบข้อความโฟลว์อวาตาร์ หรือไม่มีสิทธิ์สำหรับการยืนยันว่าอ่านแล้ว",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "ไม่สามารถทำให้ข้อความอวาตาร์เสร็จสิ้นเป็นสถานะอ่านแล้ว",
    "CHAT_ATTACHMENT_COUNT_ONE": "ไฟล์แนบ 1 รายการ",
    "CHAT_ATTACHMENT_COUNT_MANY": "ไฟล์แนบ {count} รายการ",
    "CHAT_VOICE_NOTE": "บันทึกเสียง",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "แชทไม่พร้อมใช้งาน ผู้ใช้นี้บล็อกคุณ",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "แชทไม่พร้อมใช้งาน คุณบล็อกผู้ใช้นี้",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "การเข้าถึงบัญชีถูกบล็อกตามนโยบาย",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "แชทไม่พร้อมใช้งาน บัญชีนี้ถูก User Zero บล็อกแบบถาวร",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "แชทไม่พร้อมใช้งาน การบล็อกทั้งสองฝ่ายเปิดใช้งานอยู่",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "แชทไม่พร้อมใช้งานเนื่องจากนโยบายการบล็อก",
    "MESSAGE_PREVIEW_PHOTO": "รูปภาพ",
    "MESSAGE_PREVIEW_VOICE": "ข้อความเสียง",
    "MESSAGE_PREVIEW_VIDEO": "วิดีโอ",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "ไฟล์",
    "MESSAGE_PREVIEW_MESSAGE": "ข้อความ",
    "MESSAGE_PREVIEW_SYSTEM": "ข้อความระบบ",
    "MESSAGE_PREVIEW_NEW": "ข้อความใหม่",
    "MESSAGE_UNKNOWN_FILE": "ไฟล์ที่ไม่ทราบ",
    "MESSAGE_AUDIO_ATTACHMENT": "ไฟล์แนบเสียง",
    "MESSAGE_FILE_ATTACHMENT": "ไฟล์แนบ",
    "BANNER_INVITED_BY": "เชิญโดย {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "ผลการค้นหา",
    "SEARCH_QUERY_LABEL": "คำค้นหา:",
    "SEARCH_LOADING_VISIBILITY": "กำลังโหลดการมองเห็นการค้นหา...",
    "SEARCH_NO_RESULTS": "ไม่พบผลลัพธ์ในขอบเขตการค้นหาปัจจุบัน",
    "SHARE_WITH_COLLABRA": "แชร์กับ Collabra",
    "SHARE_SEND_TO": "ส่งถึง",
    "SHARE_SELECT_ONE_BANNER": "เลือกหนึ่งแบนเนอร์",
    "SHARE_BANNER_LIST_ARIA": "รายการแบนเนอร์",
    "SHARE_NO_MATCHING_BANNER": "ไม่มีแบนเนอร์ที่ตรงกัน",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "เพิ่มความคิดเห็น...",
    "SHARE_RECENT_CHATS": "แชทล่าสุด",
    "SHARE_LEFT_LIST": "รายการด้านซ้าย",
    "SHARE_RIGHT_LIST": "รายการด้านขวา",
    "SHARE_UNTITLED_BANNER": "แบนเนอร์ไม่มีชื่อ",
    "SHARE_SHARED_CONTENT": "เนื้อหาที่แชร์",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "ไม่สามารถเปิดเนื้อหาที่แชร์ได้",
    "SHARE_OPEN_BANNER_FAILED": "ไม่สามารถเปิดแบนเนอร์ที่เลือกได้",
    "SHARE_ONE_PHOTO_SELECTED": "เลือกรูปภาพ 1 รูป",
    "SHARE_MANY_PHOTOS_SELECTED": "เลือกรูปภาพ {count} รูป",
    "SHARE_ONE_FILE_SELECTED": "เลือกไฟล์ 1 ไฟล์",
    "SHARE_MANY_FILES_SELECTED": "เลือกไฟล์ {count} ไฟล์",
    "FORWARD_MESSAGE_TITLE": "ส่งต่อข้อความ",
    "FORWARD_SELECT_RECIPIENTS": "เลือกผู้รับ",
    "FORWARD_NO_OTHER_BANNER": "ไม่มีแบนเนอร์อื่นที่พร้อมใช้งาน",
    "FORWARD_SEND_TO_COUNT": "ส่งถึง {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "เลือกอย่างน้อยหนึ่งแบนเนอร์",
    "FORWARD_FAILED_DEFAULT": "การส่งต่อไม่สำเร็จ โปรดลองอีกครั้ง",
    "FORWARD_PARTIAL_SENT": "ส่งแล้ว {count} รายการ {error}",
    "FORWARD_SOURCE_NOT_FOUND": "ไม่พบข้อความต้นทางสำหรับการส่งต่อ",
    "FORWARD_NO_FORWARDABLE_CONTENT": "ข้อความนี้ยังไม่มีเนื้อหาที่ส่งต่อได้",
    "FORWARD_DESTINATION_MISSING": "ไม่มีปลายทางสำหรับการส่งต่อ",
    "FORWARD_MESSAGE_PREVIEW": "ข้อความที่ส่งต่อ",
    "MENU_PASTE": "วาง",
    "MENU_COPY": "คัดลอก",
    "MENU_REPLY": "ตอบกลับ",
    "MENU_FORWARD": "ส่งต่อ",
    "MENU_REMOVE_INVITATION": "นำคำเชิญออก",
    "MENU_REMOVE_FROM_LIST": "นำออกจากรายการ",
    "MENU_GOODBYE_GUEST": "",
    "MENU_ADD_TO_LIST": "เพิ่มในรายการ",
    "MENU_REJECT_INVITATION": "ปฏิเสธคำเชิญ",
    "MENU_FRONTEND_VERSION": "เวอร์ชัน Frontend",
    "MENU_BANNER_HEADER": "แบนเนอร์ - {zone}",
    "MENU_BANNER_INFO": "ข้อมูลแบนเนอร์: {title}",
    "MENU_MESSAGE_BUBBLE": "บับเบิลข้อความ",
    "MENU_CHAT_CANVAS_HEADER": "แคนวาสแชท - {zone}",
    "MENU_CANVAS_INFO": "ข้อมูลแคนวาส",
    "MENU_CHAT_CANVAS_SUBLABEL": "พื้นที่สนทนา / พื้นผิวแชทปัจจุบัน",
    "MENU_INPUT_AREA_HEADER": "พื้นที่ป้อนข้อมูล - {zone}",
    "MENU_INPUT_AREA_INFO": "ข้อมูลพื้นที่ป้อนข้อมูล: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "พื้นที่ด้านล่างสำหรับพิมพ์และเครื่องมือดำเนินการ",
    "MENU_HEADER": "ส่วนหัว - {zone}",
    "MENU_HEADER_INFO": "ข้อมูลส่วนหัว: {title}",
    "MENU_HEADER_DESCRIPTION": "การนำทางด้านบนและตัวควบคุมหน้า",
    "MENU_ZONE_HEADER": "โซน - {zone}",
    "MENU_ZONE_SPACE_INFO": "ข้อมูลพื้นที่โซน",
    "MENU_EMPTY_LIST_SURFACE": "พื้นผิวว่าง/รายการ",
    "MENU_BLOCK": "บล็อก",
    "MENU_UNBLOCK": "เลิกบล็อก",
    "MENU_HIDE_IN_SEARCH": "ซ่อนในการค้นหา",
    "MENU_UNHIDE_IN_SEARCH": "เลิกซ่อนในการค้นหา",
    "MENU_VISIBLE_IN_SEARCH": "มองเห็นในการค้นหา",
    "MENU_HIDDEN_IN_SEARCH": "ซ่อนในการค้นหา",
    "MENU_VISIBLE_IN_USER_LIST": "มองเห็นในรายการผู้ใช้",
    "MENU_HIDDEN_IN_USER_LIST": "ซ่อนในรายการผู้ใช้",
    "MENU_NOT_BLOCKED": "ไม่ได้บล็อก",
    "MENU_BLOCKED": "ถูกบล็อก",
    "MENU_FRONTEND_VERSION_LOADING": "กำลังโหลด...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "กำลังโหลดค่าต่อแบนเนอร์จาก backend ไม่มีตัวเลือกใดถูกทำเครื่องหมายว่า active จนกว่าการตอบกลับจากฐานข้อมูลจะมาถึง",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "ไม่สามารถโหลดค่า backend ได้ จึงไม่แสดงตัวเลือก active ที่เชื่อถือได้",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "ค่าฐานข้อมูลต่อแบนเนอร์ที่ระบุไว้คือ {overrideVersion} ค่าเริ่มต้นส่วนกลางคือ {globalDefaultVersion} ผู้ใช้เป้าหมายต้องรีเฟรชเต็มรูปแบบหรือเปิดแอปใหม่เพื่อให้ startup bootstrap นำไปใช้",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "ไม่มีค่าต่อแบนเนอร์ที่ระบุไว้ถูกจัดเก็บ FeV2.0.0 active ตามค่าเริ่มต้น ค่าเริ่มต้นส่วนกลางคือ {globalDefaultVersion}",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "ค่าฐานข้อมูลต่อแบนเนอร์ที่ระบุไว้จะ active หลังจากแอปเป้าหมายโหลดใหม่อย่างสมบูรณ์",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "ไม่มีค่าต่อแบนเนอร์ที่ระบุไว้ถูกจัดเก็บ นี่คือสถานะ FeV2.0.0 รายบุคคลตามค่าเริ่มต้น",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "ตัวเลือกนี้ยังเท่ากับค่าเริ่มต้นส่วนกลางปัจจุบันด้วย",
    "MENU_DELETE_PERMANENT_CONFIRM": "ลบ {target} ออกจากฐานข้อมูลอย่างถาวรหรือไม่? การดำเนินการนี้จะลบบัญชี ประวัติแชท dependencies และบังคับให้ใช้เส้นทางเชิญใหม่ทั้งหมดสำหรับการกลับเข้ามาในอนาคต",
    "MENU_DELETE_PERMANENTLY": "ลบถาวร",
    "MENU_REFRESH_PAGE": "รีเฟรชหน้า",
    "MENU_LOG_OFF": "ออกจากระบบ",
    "MENU_HARD_RELOAD": "โหลดใหม่แบบบังคับ",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "อีเมล (ผู้ดูแลระบบ)",
    "AUTH_PASSWORD_PLACEHOLDER": "รหัสผ่าน",
    "AUTH_CONNECTING": "กำลังเชื่อมต่อ...",
    "AUTH_SIGNING_OUT": "กำลังออกจากระบบ...",
    "AUTH_BACK_TO_LOGIN": "กลับไปเข้าสู่ระบบ",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "การตอบกลับจากเซิร์ฟเวอร์ไม่ถูกต้อง: ไม่พบโทเค็น",
    "AUTH_LOGIN_FAILED": "เข้าสู่ระบบไม่สำเร็จ",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "รหัสผ่านไม่ตรงกัน",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "รหัสผ่านไม่ตรงกัน!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "รหัสผ่านต้องตรงกันทุกประการ",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "รหัสผ่านใหม่",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "ยืนยันรหัสผ่าน",
    "AUTH_CHANGE_PASSWORD": "เปลี่ยนรหัสผ่าน",
    "AUTH_SAVING_PASSWORD": "กำลังบันทึก...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "อัปเดตรหัสผ่านสำเร็จแล้ว",
    "AUTH_CHANGE_PASSWORD_UNABLE": "ไม่สามารถเปลี่ยนรหัสผ่านได้ในขณะนี้",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "คุณต้องเข้าสู่ระบบเพื่อเปลี่ยนรหัสผ่าน",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "สลับการมองเห็นรหัสผ่านใหม่",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "สลับการมองเห็นการยืนยันรหัสผ่าน",
    "REGISTER_TITLE": "ลงทะเบียนให้เสร็จสมบูรณ์",
    "REGISTER_SUBTITLE": "โปรดตั้งรหัสผ่านด้วยตนเอง",
    "REGISTER_CREATING_ACCOUNT": "กำลังสร้างบัญชี...",
    "REGISTER_FINISH_SETUP": "เสร็จสิ้นการตั้งค่า",
    "REGISTER_FAILED_SET_PASSWORD": "ตั้งรหัสผ่านไม่สำเร็จ",
    "INVITE_EMAIL_INSTRUCTION": "โปรดกรอกอีเมลของผู้ได้รับเชิญ (รูปแบบ: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "เชิญ",
    "INVITE_EMAIL_REQUIRED": "โปรดกรอกอีเมลของผู้ได้รับเชิญ",
    "INVITE_EMAIL_INVALID": "รูปแบบอีเมลไม่ถูกต้อง โปรดใช้: user@example.com",
    "PENDING_INVITATION_TITLE": "คำเชิญที่รอดำเนินการ",
    "PENDING_INVITATION_REMOVE_QUESTION": "นำคำเชิญที่รอดำเนินการนี้ออกจากฐานข้อมูลหรือไม่?",
    "PENDING_INVITATION_KEEP": "เก็บคำเชิญไว้",
    "PENDING_INVITATION_REMOVAL_FAILED": "การนำออกไม่สำเร็จ",
    "REMOVE_FROM_LIST_TITLE": "นำออกจากรายการ",
    "REMOVE_FROM_LIST_WARNING": "นำผู้ใช้นี้ออกจากทั้งสองรายการตอนนี้หรือไม่? การเข้าถึงแชทจะถูกตัดทันที เส้นทางเดียวในการกลับมาคือต้องได้รับคำเชิญใหม่",
    "REMOVE_FROM_LIST_KEEP": "เก็บผู้ใช้ไว้ในรายการ",
    "REMOVE_FROM_LIST_FAILED": "นำออกจากรายการไม่สำเร็จ",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "การตั้งค่าและสถานะสด",
    "PERMISSION_DIALOG_ARIA": "การตั้งค่าและสถานะสด",
    "PERMISSION_TRIGGER_ARIA": "ตัวเรียก popup การตั้งค่า",
    "PERMISSION_CLOSE_ARIA": "ปิด popup สิทธิ์",
    "PERMISSION_LIVE_STATUS": "สถานะสด",
    "PERMISSION_SYSTEM_PERMISSION": "สิทธิ์ระบบ",
    "PERMISSION_APP_PUSH": "Push ของแอป",
    "PERMISSION_LOCATION_PERMISSION": "สิทธิ์ตำแหน่งที่ตั้ง",
    "PERMISSION_APP_LOCATION": "ตำแหน่งที่ตั้งของแอป",
    "PERMISSION_CONTROLS": "ตัวควบคุมสิทธิ์",
    "PERMISSION_PUSH_NOTIFICATIONS": "การแจ้งเตือนแบบ push",
    "PERMISSION_LOCATION_ACCESS": "การเข้าถึงตำแหน่งที่ตั้ง",
    "PERMISSION_IN_APP_SETTINGS": "การตั้งค่าในแอป",
    "PERMISSION_ALERT_SOUND": "เสียงแจ้งเตือน",
    "PERMISSION_APP_BADGE": "ป้ายแอป",
    "PERMISSION_PASSWORD_SETTINGS": "การตั้งค่ารหัสผ่าน",
    "PERMISSION_NAVIGATION_STATUS": "สถานะการนำทาง",
    "PERMISSION_SELECTED_ZONE": "โซนที่เลือก",
    "PERMISSION_STAGED_CHAT_BANNER": "แบนเนอร์แชทที่เตรียมไว้",
    "PERMISSION_CANVAS_CONTENT": "เนื้อหาแคนวาส",
    "PERMISSION_YOUR_DEVICES": "อุปกรณ์ของคุณ ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "รีเฟรชรายการอุปกรณ์",
    "PERMISSION_REFRESH_LIST": "รีเฟรชรายการ",
    "PERMISSION_NO_REGISTERED_DEVICES": "ไม่พบอุปกรณ์ที่ลงทะเบียนไว้",
    "PERMISSION_RESIZE_POPUP_ARIA": "ปรับขนาด popup การตั้งค่า",
    "PERMISSION_TOGGLE_PUSH_ARIA": "สลับการแจ้งเตือน push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "สลับการเข้าถึงตำแหน่งที่ตั้ง",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "สลับเสียงแจ้งเตือน",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "สลับป้ายแอป",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "สลับการมองเห็นโปรไฟล์",
    "PERMISSION_OFF_IN_V1": "ปิดใน v1",
    "PERMISSION_CHAT": "แชท",
    "PERMISSION_BANNER_LIST": "รายการแบนเนอร์",
    "PERMISSION_PUSH_DISABLED_V1": "การแจ้งเตือน push ถูกปิดใช้งานสำหรับรุ่น v1 Google Play",
    "PERMISSION_PUSH_ON_TOOLTIP": "การแจ้งเตือน push เปิดอยู่สำหรับอุปกรณ์นี้",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "การแจ้งเตือนระบบถูกบล็อก แตะเพื่อเปิดความช่วยเหลือการตั้งค่า",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "เปิดเพื่อปรับปรุงความน่าเชื่อถือในการส่ง",
    "PERMISSION_SYSTEM_DISABLE_HELP": "หากต้องการปิดการแจ้งเตือนระบบ ให้เปิดการตั้งค่าการแจ้งเตือนของเบราว์เซอร์/ไซต์ แล้วตั้งไซต์นี้เป็น Block",
    "PERMISSION_SYSTEM_ALLOW_HELP": "หากต้องการเปลี่ยนสิทธิ์การแจ้งเตือนระบบ ให้เปิดการตั้งค่าการแจ้งเตือนของเบราว์เซอร์/ไซต์ แล้วตั้งไซต์นี้เป็น Allow",
    "PERMISSION_LOCATION_ON_TOOLTIP": "การเข้าถึงตำแหน่งที่ตั้งเปิดอยู่สำหรับการจัดเรียง LCAC ตามระยะทางและการวางตำแหน่งบนแผนที่",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Location API ไม่รองรับในสภาพแวดล้อมนี้",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "การเข้าถึงตำแหน่งที่ตั้งถูกบล็อก แตะเพื่อเปิดความช่วยเหลือการตั้งค่า",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "เปิดเพื่ออนุญาตการจัดเรียง LCAC ตามระยะทางอย่างแม่นยำและการวางตำแหน่งบนแผนที่ในแอป",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "การเข้าถึงตำแหน่งที่ตั้งไม่รองรับในสภาพแวดล้อมนี้",
    "PERMISSION_LOCATION_DISABLE_HELP": "หากต้องการปิดการเข้าถึงตำแหน่งที่ตั้ง ให้เปิดการตั้งค่าตำแหน่งของเบราว์เซอร์/ไซต์ แล้วตั้งไซต์นี้เป็น Block",
    "PERMISSION_LOCATION_ALLOW_HELP": "หากต้องการเปิดการเข้าถึงตำแหน่งที่ตั้งสำหรับการจัดเรียงตามระยะทางและการวางตำแหน่งบนแผนที่ในแอป ให้เปิดการตั้งค่าตำแหน่งของเบราว์เซอร์/ไซต์ แล้วตั้งไซต์นี้เป็น Allow",
    "PERMISSION_DEVICE_LOAD_FAILED": "ไม่สามารถโหลดอุปกรณ์ที่ลงทะเบียนได้ในขณะนี้",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "กำลังโหลด UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "กำลังโหลด Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "กำลังโหลด Backend...",
    "RUNTIME_LOADING": "กำลังโหลด...",
    "RUNTIME_LOADING_FROM_DATABASE": "กำลังโหลดจากฐานข้อมูล...",
    "RUNTIME_BACKEND_CONNECTED": "Backend เชื่อมต่อแล้ว",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Fallback ที่แคชไว้ active",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback ค่าเริ่มต้น active",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "ค่าเริ่มต้น fallback active",
    "RUNTIME_SAVING_THROUGH_BACKEND": "กำลังบันทึกผ่าน Backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "บันทึกในบริการ Backend แล้ว",
    "RUNTIME_SAVE_FAILED": "บันทึกไม่สำเร็จ",
    "RUNTIME_LOAD_FAILED": "โหลดไม่สำเร็จ",
    "RUNTIME_CONNECTED": "เชื่อมต่อแล้ว",
    "RUNTIME_LOGIN_REQUIRED": "ต้องเข้าสู่ระบบ",
    "RUNTIME_SAVED": "บันทึกแล้ว",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI พร้อมแล้ว - Runtime รอดำเนินการ",
    "RUNTIME_BACKEND_REJECTED_MODEL": "บริการ selector backend ที่ได้รับการป้องกันปฏิเสธหรือไม่สามารถบันทึกตัวเลือกโมเดลที่ร้องขอได้",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "บริการ selector backend ที่ได้รับการป้องกันปฏิเสธหรือไม่สามารถบันทึกการเปลี่ยน routing WF1 ที่ร้องขอได้",
    "RUNTIME_WF1_SELECTOR_BACKEND": "ตอนนี้ selector กำลังอ่าน config ที่ active, routing Qwen และตัวเลือกที่อนุญาตจากบริการ backend ที่ได้รับการป้องกัน",
    "RUNTIME_WF1_SELECTOR_CACHED": "บริการ backend selector ไม่พร้อมใช้งานในขณะนี้ จึงใช้สถานะ selector ที่แคชไว้ล่าสุด",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "ค่าเริ่มต้นของ selector active อยู่ เพราะไม่สามารถโหลดสถานะ backend หรือสถานะแคชได้",
    "RUNTIME_WF1_SELECTOR_SAVED": "บริการ selector backend ที่ได้รับการป้องกันได้อัปเดต config routing WF1 ที่ active และรีเฟรชแคชโดเมน runtime แล้ว",
    "FRONTEND_VERSION_TITLE": "เวอร์ชัน Frontend",
    "FRONTEND_VERSION_HELPER_ACTIVE": "selector นี้ควบคุมเวอร์ชัน frontend ที่ active สำหรับผู้ใช้ทั้งหมด FeV2.0.0 active อยู่",
    "FRONTEND_VERSION_HELPER_RUNTIME": "selector นี้อ่านเวอร์ชัน frontend ที่ active จาก config_domain_registry Runtime resolve เป็น FeV2.0.0",
    "FRONTEND_VERSION_HELPER_FALLBACK": "ไม่สามารถโหลด config เวอร์ชัน frontend จาก backend ได้ ดังนั้นค่าเริ่มต้น FeV2.0.0 ที่เขียนไว้ในโค้ดจะยัง active จนกว่า startup bootstrap จะอ่านบริการที่ได้รับการป้องกันได้อีกครั้ง",
    "FRONTEND_VERSION_HELPER_SAVED": "เวอร์ชัน frontend ที่ active ถูกบันทึกใน config_domain_registry แล้ว การรีเฟรชเต็มรูปแบบหรือการโหลดแอปครั้งถัดไปจะนำค่า runtime ไปใช้",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "บริการควบคุมเวอร์ชัน frontend ของ backend ไม่สามารถบันทึกเวอร์ชันส่วนกลางที่ร้องขอได้",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "เวอร์ชัน frontend ที่ active",
    "CHAT_DELETE_WINDOW_TITLE": "หน้าต่างเวลาลบแชท",
    "CHAT_DELETE_HELPER": "ค่านี้ควบคุมหน้าต่างเวลาที่ใช้ Delete for everyone ได้เป็นวินาที backend guard จะเปลี่ยนทันทีหลังบันทึก การมองเห็น bubble จะเปลี่ยนหลังรีเฟรชเต็มรูปแบบหรือโหลดแอปครั้งถัดไป",
    "CHAT_DELETE_HELPER_FALLBACK": "ไม่สามารถโหลดบริการควบคุมการลบแชทของ backend ได้ ดังนั้นค่าเริ่มต้นที่เขียนไว้ในโค้ดจะยัง active จนกว่า startup bootstrap จะอ่านบริการที่ได้รับการป้องกันได้อีกครั้ง",
    "CHAT_DELETE_HELPER_SAVED": "หน้าต่างเวลาที่ใช้ Delete for everyone ได้ถูกบันทึกใน config_domain_registry แล้ว backend guard เปลี่ยนทันที การมองเห็น bubble จะเปลี่ยนหลังรีเฟรชเต็มรูปแบบหรือโหลดแอปครั้งถัดไป",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "บริการควบคุมการลบแชทของ backend ไม่สามารถบันทึกค่าหน้าต่างเวลาที่ร้องขอได้",
    "CHAT_DELETE_WINDOW_LABEL": "หน้าต่างเวลา Delete for everyone",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} วินาที",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "เก็บค่าเป็นจำนวนวินาทีเต็ม ค่า production ปัจจุบันคือ 86400 วินาที = 1 วัน",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "วินาทีของหน้าต่างเวลา",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "กรอกจำนวนเต็มที่มากกว่าหรือเท่ากับ 0",
    "CHAT_DELETE_SAVE_BUTTON": "บันทึกหน้าต่างเวลาลบ",
    "GUEST_BANNER_CONTROL_TITLE": "",
    "GUEST_BANNER_CONTROL_LABEL": "",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "",
    "GUEST_BANNER_CONTROL_HELPER": "",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "",
    "GUEST_BANNER_PENDING_TTL_INVALID": "",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "",
    "GUEST_QR_LOADING": "",
    "GUEST_QR_READY": "",
    "GUEST_QR_ALT": "",
    "GUEST_QR_LOAD_FAILED": "",
    "GUEST_SESSION_ACTIVE": "",
    "GUEST_PUBLIC_TITLE": "",
    "GUEST_PUBLIC_CONNECTING": "",
    "GUEST_PUBLIC_CONNECTED": "",
    "GUEST_PUBLIC_UNAVAILABLE": "",
    "GUEST_PUBLIC_SEND_FAILED": "",
    "UI_TEXTS_RUNTIME_TITLE": "",
    "UI_TEXTS_RUNTIME_BACKEND": "",
    "UI_TEXTS_RUNTIME_CACHED": "",
    "UI_TEXTS_RUNTIME_DEFAULTS": "",
    "UI_TEXTS_RUNTIME_SAVED": "",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "",
    "PROFILE_VISIBILITY_TITLE": "การมองเห็นโปรไฟล์",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "คุณต้องเข้าสู่ระบบเพื่อจัดการการมองเห็นบัญชี",
    "PROFILE_VISIBILITY_HELPER": "สวิตช์นี้อัปเดตเฉพาะสถานะการมองเห็นบัญชีของคุณ การค้นพบและพฤติกรรมรายการแบนเนอร์ยังคงไม่เปลี่ยนแปลงในเฟสนี้",
    "PROFILE_VISIBILITY_LOAD_FAILED": "ไม่สามารถโหลดการมองเห็นโปรไฟล์ได้ในขณะนี้",
    "PROFILE_VISIBILITY_SAVE_FAILED": "ไม่สามารถอัปเดตการมองเห็นโปรไฟล์ได้ในขณะนี้",
    "PROFILE_VISIBILITY_SAVED": "ตอนนี้การมองเห็นบัญชีของคุณคือ {visibility} แฟล็กการค้นพบยังคงไม่เปลี่ยนแปลงในเฟสนี้",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "บัญชีสาธารณะ",
    "PROFILE_VISIBILITY_STORED": "การมองเห็นที่จัดเก็บไว้",
    "WF1_MODEL_CONTROL_TITLE": "การควบคุมโมเดล WF1",
    "WF1_ENABLE_TRANSLATION": "เปิดใช้งานการแปล / Pivot",
    "WF1_TRANSLATION_ACTIVE": "การแปลด้วย AI active อยู่",
    "WF1_TRANSLATION_INACTIVE": "WF1 ยังคงทำงานต่อ แต่ข้อความต้นฉบับจะถูกคัดลอกและ pivot ถูกทำเครื่องหมายว่า inactive",
    "WF1_ACTIVE_RUNTIME_SLOT": "สล็อต Runtime ที่ active",
    "WF1_ALLOW_SAME_LANGUAGE": "อนุญาต AI สำหรับคู่ภาษาเดียวกัน",
    "WF1_SAME_LANGUAGE_ACTIVE": "คู่ภาษาเดียวกันใช้ routing WF1 ปกติ",
    "WF1_SAME_LANGUAGE_INACTIVE": "คู่ภาษาเดียวกันข้าม AI และจัดเก็บเป็นไม่มีภาษา Pivot ที่ active",
    "WF1_QWEN_ROUTING": "Routing คู่ภาษา Qwen",
    "WF1_QWEN_ROUTING_HELPER": "ภาษาที่เลือกด้านล่างจะใช้ Qwen-Max เมื่อคู่นั้นเป็นภาษาเดียวกันที่เลือก, ภาษาที่เลือกกับอังกฤษ, หรือภาษาที่ไม่ใช่อังกฤษสองภาษาที่เลือก มิฉะนั้นโมเดลหลักที่เลือกจะยัง active",
    "WF1_OPENROUTER_TEST_SLOT": "สล็อตทดสอบ OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "สล็อตทดสอบ OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "ทดสอบคุณภาพเท่านั้น",
    "WF1_OPENROUTER_HELPER": "สล็อตนี้แก้ไขได้เฉพาะสำหรับการทดสอบคุณภาพ OpenRouter ชั่วคราวเท่านั้น ไม่เปลี่ยนเส้นทางปฏิบัติการ routing คู่ภาษา Qwen เว้นแต่สล็อตนี้เองจะกลายเป็นโมเดล active",
    "WF1_LABEL": "ป้ายกำกับ",
    "WF1_PRODUCT": "ผลิตภัณฑ์",
    "WF1_MODEL": "โมเดล",
    "WF1_PROVIDER_OPENROUTER": "ผู้ให้บริการ: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "สล็อตทดสอบ OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max ผ่าน OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "ราคาปลีกของ Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "ราคาปลีกของ OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "ราคาปลีกของ OpenRouter",
    "LANGUAGE_ENGLISH": "อังกฤษ",
    "LANGUAGE_CHINESE_SIMPLIFIED": "จีน (ตัวย่อ)",
    "LANGUAGE_CHINESE_TRADITIONAL": "จีน (ตัวเต็ม)",
    "LANGUAGE_JAPANESE": "ญี่ปุ่น",
    "LANGUAGE_KOREAN": "เกาหลี",
    "LANGUAGE_PERSIAN": "เปอร์เซีย",
    "LANGUAGE_TURKISH_ISTANBUL": "ตุรกี (อิสตันบูล)",
    "LANGUAGE_ARABIC": "อาหรับ",
    "LANGUAGE_FRENCH": "ฝรั่งเศส",
    "LANGUAGE_GERMAN": "เยอรมัน",
    "LANGUAGE_SPANISH": "สเปน",
    "LANGUAGE_PORTUGUESE": "โปรตุเกส",
    "LANGUAGE_ITALIAN": "อิตาลี",
    "LANGUAGE_RUSSIAN": "รัสเซีย",
    "LANGUAGE_DUTCH": "ดัตช์",
    "LANGUAGE_VIETNAMESE": "เวียดนาม",
    "LANGUAGE_INDONESIAN": "อินโดนีเซีย",
    "LANGUAGE_THAI": "ไทย",
    "LANGUAGE_MALAY": "มาเลย์",
    "WF1_PRICING_CUSTOM": "ราคา: โมเดลสล็อตกำหนดเอง - ตรวจสอบราคา OpenRouter ปัจจุบัน",
    "WF1_SAVE_OPENROUTER_SLOT": "บันทึกสล็อต OpenRouter",
    "WF1_PRICING_LINE": "อินพุต {input} - เอาต์พุต {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "การควบคุมการมองเห็นโซน",
    "ZONE_ENABLE": "เปิดใช้งาน {zone}",
    "ZONE_ENABLED_NOTE": "{zone} สามารถปรากฏสำหรับบทบาทที่ได้รับอนุญาตหลังการโหลดแอปครั้งถัดไป",
    "ZONE_DISABLED_NOTE": "{zone} จะถูกถือว่าไม่มีอยู่สำหรับผู้ใช้ที่ไม่ใช่ S_Admin หลังการโหลดแอปครั้งถัดไป",
    "ZONE_S_ADMIN_BYPASS": "S_Admin ข้ามรายการบทบาทนี้และมีสิทธิ์เข้าถึงเสมอ",
    "ZONE_ROLE_LOCKED": "การเลือกบทบาทถูกล็อกชั่วคราวขณะที่โซนนี้ถูกปิดใช้งาน และจะกลับมาเหมือนที่บันทึกไว้ทุกประการเมื่อเปิดใช้งานโซนอีกครั้ง",
    "ZONE_LCAC_CONTROL": "การควบคุม LCAC",
    "ZONE_RCAC_CONTROL": "การควบคุม RCAC",
    "ZONE_LCAC_DESCRIPTION": "ควบคุมการมีอยู่ของโซน reserved ด้านซ้ายและบทบาทที่สามารถมองเห็นได้",
    "ZONE_RCAC_DESCRIPTION": "ควบคุมการมีอยู่ของโซน reserved ด้านขวาและบทบาทที่สามารถมองเห็นได้",
    "ZONE_VISIBILITY_BACKEND": "ตอนนี้ bootstrap การมองเห็นโซนกำลังอ่านจากบริการ backend ที่ได้รับการป้องกัน การเปลี่ยนแปลงจะมีผลเมื่อโหลดแอปครั้งถัดไป",
    "ZONE_VISIBILITY_CACHED": "บริการ backend การมองเห็นโซนไม่พร้อมใช้งานในขณะนี้ จึงใช้ค่าแคชหรือค่า local default",
    "ZONE_VISIBILITY_DEFAULTS": "ค่าเริ่มต้นการมองเห็นโซน active อยู่ เพราะไม่สามารถโหลดสถานะ backend หรือสถานะแคชได้",
    "ZONE_VISIBILITY_SAVED": "บันทึก bootstrap การมองเห็นโซนแล้ว ต้อง hard reload หรือโหลดแอปครั้งถัดไปเพื่อให้ runtime นำไปใช้",
    "ZONE_VISIBILITY_SAVE_FAILED": "บริการ backend ที่ได้รับการป้องกันไม่สามารถบันทึกการเปลี่ยนแปลงการมองเห็นโซนที่ร้องขอได้",
    "ROLE_MEMBER": "สมาชิก",
    "ROLE_STAFF": "พนักงาน",
    "ROLE_ADMIN": "ผู้ดูแลระบบ",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "เปิดใช้งานการแจ้งเตือนเพื่อรับข้อความใหม่",
    "MAIN_LOG_OUT": "ออกจากระบบ",
    "NOTIFICATION_NEW_MESSAGE": "ข้อความใหม่",
    "NOTIFICATION_UNREAD_MESSAGE": "คุณมีข้อความที่ยังไม่ได้อ่าน",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "มุมมองเต็ม",
    "MEDIA_AUDIO_ATTACHMENT": "ไฟล์แนบเสียง",
    "MEDIA_FILE_FALLBACK": "ไฟล์",
    "MEDIA_DOWNLOAD_READY": "ไฟล์แนบพร้อมสำหรับดาวน์โหลด",
    "MEDIA_TYPE_UNSUPPORTED": "ไม่รองรับชนิดนี้สำหรับมุมมองเต็ม",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "รูปภาพก่อนหน้า",
    "MEDIA_NEXT_IMAGE_ARIA": "รูปภาพถัดไป",
    "MEDIA_OPEN_ORIGINAL": "เปิดต้นฉบับ",
    "MEDIA_DOWNLOAD": "ดาวน์โหลด",
    "MEDIA_CLOSE_ARIA": "ปิด",
    "MEDIA_PROFILE_PICTURE_ARIA": "รูปโปรไฟล์ของ {name}",
    "MEDIA_PROFILE_ALT": "โปรไฟล์ของ {name}",
    "MEDIA_UPLOAD_FAILED": "อัปโหลดไม่สำเร็จ",
    "MEDIA_BACKEND_TOKEN_ERROR": "ข้อผิดพลาดโทเค็น Backend",
    "MEDIA_UPLOAD_URL_MISSING": "สำคัญ: ไม่มี URL อัปโหลดในการตอบกลับจาก backend",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "ไม่มีโทเค็นยืนยันตัวตนสำหรับการอัปโหลดแชท",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "คำขอโทเค็นอัปโหลดแชทล้มเหลว",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "การตอบกลับการอัปโหลดแชทไม่ถูกต้อง",
    "MEDIA_GCS_UPLOAD_FAILED": "อัปโหลด GCS ไม่สำเร็จ",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "ไม่มีชื่อไฟล์หรือ contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "ไม่มี file_path",
    "BLOCK_NOTICE_TITLE": "ประกาศการบล็อกถาวร",
    "BLOCK_NOTICE_MESSAGE": "บัญชีของคุณถูกระงับชั่วคราวเนื่องจากละเมิดนโยบาย",
    "BLOCK_NOTICE_CONTACT_PREFIX": "หากคุณเชื่อว่าเรื่องนี้ต้องมีการติดตาม โปรดติดต่อ",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "ทางอีเมล",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "ผู้ใช้ที่ไม่ทราบ",
    "GENERAL_GUEST": "ผู้เยี่ยมชม",
    "ADVISOR_FOR_CLIENT": "ที่ปรึกษาสำหรับ {client_display_name}",
    "GUEST_FOR_CLIENT": "",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "ต้องระบุโทเค็นและรหัสผ่าน",
    "AUTH_ERROR_REQUEST_BODY_JSON": "เนื้อหาคำขอต้องเป็น JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "โทเค็นคำเชิญไม่ถูกต้องหรือหมดอายุ",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "ตั้งรหัสผ่านไม่สำเร็จ: ไม่มี session หรือ user",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "ตั้งรหัสผ่านไม่สำเร็จระหว่างการเข้าสู่ระบบ",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "สร้างโทเค็น admin ไม่สำเร็จ",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "เข้าสู่ระบบไม่สำเร็จ: ไม่มี session หรือ user",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "ลงทะเบียนสำเร็จ โปรดตรวจสอบอีเมลเพื่อยืนยัน",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "สมัครใช้งานล้มเหลวโดยไม่ทราบสาเหตุ",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "การประมวลผลโทเค็นไม่ถูกต้อง",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "ต้องมี access token",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "การดูตัวอย่าง token hash ต้องมี email hint จาก redirect URL",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "ไม่สามารถ resolve identity สำหรับโทเค็นนี้ได้",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "เฉพาะ User Zero เท่านั้นที่เข้าถึงบริการ selector LLM ของ WF1 ได้",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "เฉพาะ User Zero เท่านั้นที่เข้าถึงบริการควบคุมการมองเห็นโซนได้",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "เฉพาะ User Zero เท่านั้นที่เข้าถึงบริการควบคุมเวอร์ชัน frontend ได้",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "เฉพาะ User Zero เท่านั้นที่ตรวจสอบเวอร์ชัน frontend ของผู้ใช้อื่นได้",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "เฉพาะ User Zero เท่านั้นที่เข้าถึงบริการควบคุมการลบแชทได้",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "เฉพาะ User Zero เท่านั้นที่ลบบัญชีผู้ใช้อย่างถาวรได้",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "payload คำขอไม่ถูกต้อง",
    "API_ERROR_INTERNAL_SERVER": "ข้อผิดพลาดภายในเซิร์ฟเวอร์",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "ไม่มีฟังก์ชันใน backend (ต้องโหลดใหม่)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "อนุญาตเฉพาะ DB RPC สำหรับการเปลี่ยนสถานะ delivered/read",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "โปรดรอสักครู่ก่อนส่งข้อความอีกครั้ง",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "ส่งข้อความสำเร็จแล้ว",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "บริการติดต่อไม่พร้อมใช้งาน",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "ส่งข้อความไม่สำเร็จ",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "ต้องระบุชื่อ",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "อีเมลไม่ถูกต้อง",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "ต้องระบุข้อความ",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "ต้องมี payload ของ selector",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "ต้องมี payload การมองเห็นโซน",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "ต้องมี payload เวอร์ชัน frontend",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "ต้องมี payload การควบคุมการลบแชท",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ต้องมีรหัสผู้ใช้ที่ยืนยันตัวตนแล้ว",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ต้องมีรหัสผู้ชมที่ยืนยันตัวตนแล้ว",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ต้องมีรหัสผู้กระทำที่ยืนยันตัวตนแล้ว",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id จำเป็นต้องระบุ",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id จำเป็นต้องระบุ",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "ต้องระบุรายการ owner_user_ids",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email จำเป็นต้องระบุ",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by จำเป็นต้องระบุ",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "runtime การค้นหาถูกปิดใช้งานโดยเวอร์ชัน frontend ส่วนกลาง",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "คุณไม่ได้รับอนุญาตให้ยกเลิกคำเชิญที่รอดำเนินการนี้",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "ไม่สามารถยกเลิกคำเชิญนี้ได้อีกต่อไป เพราะผู้ใช้ลงทะเบียนแล้ว",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "ไม่พบคำเชิญที่รอดำเนินการ",
    "INVITE_REPLY_ALREADY_MEMBER": "ยินดีด้วย เพื่อนของคุณ ({invitee_email}) ลงทะเบียนในแอปนี้แล้วและเป็นสมาชิกของ workspace นี้",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "มีคำเชิญที่รอดำเนินการสำหรับ {invitee_email} แต่ไม่สามารถเรียกส่งอีเมลซ้ำได้ โปรดตรวจสอบ mail logs",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "สร้างบันทึกคำเชิญสำหรับ {invitee_email} แล้ว แต่ไม่สามารถยืนยันการส่งอีเมลได้ โปรดลองอีกครั้งภายหลังหรือตรวจสอบ mail logs",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "สร้างบันทึกคำเชิญไม่สำเร็จ โปรดลองอีกครั้งภายหลัง",
    "INVITE_REPLY_SYSTEM_ERROR": "ข้อผิดพลาดของระบบระหว่างกระบวนการเชิญ: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "ข้อผิดพลาดการกำหนดค่า Backend: ไม่มีข้อมูลรับรอง Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "ข้อผิดพลาดการกำหนดค่า Backend: URL Supabase ไม่ถูกต้อง",
    "CHAT_ERROR_ACCESS_DENIED": "ปฏิเสธการเข้าถึง",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "เนื้อหาต้องไม่ว่างสำหรับข้อความแบบข้อความ",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "ไม่สามารถกำหนด ID การสนทนาได้",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "ไม่มีบริบทการยืนยันตัวตน RPC",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC ส่งคืน payload ข้อความที่ไม่ถูกต้อง",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "แทรกไม่สำเร็จ ไม่มีข้อมูลถูกส่งคืน",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations ต้องเป็น list",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "payload การดำเนินการไม่ถูกต้อง",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "ไม่รองรับ operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id จำเป็นต้องระบุ",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "ไม่พบข้อความ",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "อนุญาตให้ลบได้เฉพาะข้อความของคุณเองเท่านั้น",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Delete for everyone ไม่พร้อมใช้งานสำหรับข้อความนี้อีกต่อไป",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Delete for everyone ไม่สำเร็จ",
    "API_ERROR_SERVER_CONFIGURATION": "ข้อผิดพลาดการกำหนดค่าเซิร์ฟเวอร์",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "ไม่มี header secret ของ webhook",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "แหล่งที่มาของ webhook ไม่ได้รับอนุญาต",
    "API_ERROR_BACKEND_CONFIGURATION": "ข้อผิดพลาดการกำหนดค่า backend",
    "API_ERROR_MODULE_ATTRIBUTE": "ข้อผิดพลาด Attribute ของโมดูล: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "ล้มเหลวก่อนการลบคำเชิญ ขณะนำผู้ใช้ auth ที่รอดำเนินการออก",
    "CHAT_ERROR_DB": "ข้อผิดพลาด DB: {error}",
}
