# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/tr.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Ana Sayfa",
    "APP_TITLE": "OTMEGA AI Platformu",
    "APP_SUBTITLE": "Yapay Zeka Danışmanı",
    "CHAT_PLACEHOLDER": "Mesajınızı yazın...",
    "CHAT_SEND_BUTTON": "Gönder",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Danışman hata yapabilir, bu yüzden bilgileri tekrar kontrol edin.",
    "STATUS_ONLINE": "Çevrimiçi",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menü",
    "ICON_NEW_CHAT": "Yeni Sohbet",
    "ICON_HISTORY": "Geçmiş",
    "ICON_TEMPLATES": "Şablonlar",
    "ICON_SETTINGS": "Ayarlar",
    "ICON_USER_PROFILE": "Kullanıcı Profili",
    "ICON_QUICK_ACTIONS": "Hızlı İşlemler",
    "ICON_PINNED": "Sabitlenmiş",
    "ICON_GALLERY": "Galeri",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Uygulamayı Yükle",
    "PWA_ANDROID_MSG": "Daha iyi bir deneyim ve çevrimdışı erişim için bu uygulamayı cihazınıza yükleyin.",
    "PWA_IOS_MSG": "Bu uygulamayı iPhone/iPad'inize yüklemek için:\n1. Aşağıdaki Paylaş düğmesine dokunun\n2. Ana Ekrana Ekle seçeneğini seçin",
    "PWA_BTN_INSTALL": "Yükle",
    "PWA_BTN_LATER": "Belki Daha Sonra",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Danışman Ağı'na giriş yapın",
    "AUTH_HEADER_SIGNUP": "Birleşik hesabınızı oluşturun",
    "AUTH_HEADER_LOGIN_NETWORK": "Danışman Ağı'na giriş yapın",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Birleşik hesabınızı oluşturun",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Giriş Yap",
    "AUTH_BUTTON_SIGNUP": "Hesap Oluştur",
    "AUTH_BUTTON_GOOGLE": "Google ile devam et",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Şifremi Unuttum",
    "AUTH_BUTTON_SEND_RESET_LINK": "Sıfırlama Bağlantısı Gönder",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Hesabınız yok mu? Kaydolun",
    "AUTH_PROMPT_LOGIN": "Zaten hesabınız var mı? Giriş yapın",
    "AUTH_HELPER_TEXT_SIGNUP": "Bu platformdaki tüm danışmanlara erişmek için kullanabileceğiniz birleşik bir hesap oluşturuyorsunuz.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Bu platformdaki tüm danışmanlara erişmek için kullanabileceğiniz birleşik bir hesap oluşturuyorsunuz.",
    "AUTH_HELPER_TEXT_LOGIN": "Bu ağdaki diğer danışmanlar için kullandığınız aynı hesabı (e-posta/şifre veya Google) kullanın.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Bu ağdaki diğer danışmanlar için kullandığınız aynı hesabı (e-posta/şifre veya Google) kullanın.",
    "AUTH_FORGOT_PASSWORD_LINK": "Şifrenizi mi unuttunuz?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Şifrenizi Sıfırlayın",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "E-posta adresinizi girin; şifrenizi sıfırlamanız için size bir bağlantı gönderelim.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "E-posta",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Girişiniz yapılıyor...",
    "AUTH_STATUS_LOADING_SIGNUP": "Hesabınız oluşturuluyor...",
    "AUTH_STATUS_LOADING_RESET": "Sıfırlama bağlantısı gönderiliyor...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Giriş başarılı! Yeniden yükleniyor...",
    "AUTH_STATUS_SUCCESS_RESET": "Sıfırlama bağlantısı başarıyla gönderildi. Lütfen e-postanızı kontrol edin.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Şifre sıfırlama bağlantısı başarıyla gönderildi. Lütfen e-postanızı kontrol edin.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Geçersiz e-posta veya şifre.",
    "AUTH_ERROR_EMAIL_EXISTS": "Bu e-posta ile danışman ağında zaten bir hesap var.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Bu e-posta ile zaten bir hesap var. Lütfen giriş yapın. Şu anda üyesi olduğunuz alanlar:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Bu e-posta ile danışman ağında zaten bir hesap var. Lütfen bu pencereyi kapatın ve aynı e-posta ile önceki şifrenizi kullanarak 'Giriş' bölümünü kullanın.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Şu anda üyesi olduğunuz alanlar:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "E-posta ve şifre gereklidir.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Hesap oluşturuldu ancak üyelik kurulumu başarısız oldu. Lütfen destek ile iletişime geçin.",
    "AUTH_ERROR_DEFAULT": "Bir hata oluştu. Lütfen tekrar deneyin.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "",
    "AUTH_FORGOT_PASSWORD_ERROR": "Sıfırlama bağlantısı gönderilemedi. Lütfen tekrar deneyin.",
    "INVITE_REPLY_EMAIL_SENT": "Collabra davet e-postası arkadaşınıza {invitee_email} adresinden gönderildi.",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra davet e-postası arkadaşınıza {invitee_email} adresinden yeniden gönderildi.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Şifreyi göster",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Şifreyi gizle",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "Tamam",
    "GENERAL_CANCEL": "İptal",
    "GENERAL_CLOSE": "Kapat",
    "GENERAL_SEND": "Gönder",
    "GENERAL_SEARCH": "Ara",
    "GENERAL_RESET": "Sıfırla",
    "GENERAL_ENABLE": "Etkinleştir",
    "GENERAL_LOADING": "Yükleniyor...",
    "GENERAL_DELETE": "Sil",
    "GENERAL_DELETING": "Siliniyor...",
    "GENERAL_SAVE_PASSWORD": "Şifreyi Kaydet",
    "AUTH_REMEMBER_EMAIL_LABEL": "E-postayı hatırla",
    "GENERAL_SAVING": "Kaydediliyor...",
    "GENERAL_SENDING": "Gönderiliyor...",
    "GENERAL_REMOVING": "Kaldırılıyor...",
    "GENERAL_CONFIRM_REMOVAL": "Kaldırmayı Onayla",
    "GENERAL_EMPTY": "Boş",
    "GENERAL_UNAVAILABLE": "Kullanılamıyor",
    "GENERAL_ENABLED": "Etkin",
    "GENERAL_DISABLED": "Devre Dışı",
    "GENERAL_GRANTED": "İzin Verildi",
    "GENERAL_DENIED": "Reddedildi",
    "GENERAL_DEFAULT": "Varsayılan",
    "GENERAL_UNSUPPORTED": "Desteklenmiyor",
    "GENERAL_PUBLIC": "Herkese Açık",
    "GENERAL_PRIVATE": "Özel",
    "GENERAL_USERNAME": "Kullanıcı adı",
    "GENERAL_EMAIL": "E-posta",
    "GENERAL_YOU": "Siz",
    "GENERAL_USER": "Kullanıcı",
    "GENERAL_UNKNOWN": "Bilinmiyor",
    "GENERAL_VISITOR": "Ziyaretçi",
    "GENERAL_PROFILE": "Profil",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Bilinmeyen Banner",
    "GENERAL_ADVISOR_BANNER": "Danışman Bannerı",
    "GENERAL_NOT_AVAILABLE": "Yok",
    "GENERAL_NOT_SELECTED": "Seçilmedi",
    "GENERAL_NO_EMAIL_FOUND": "E-posta bulunamadı",
    "GENERAL_USER_ZERO_ONLY": "Yalnızca User Zero",
    "GENERAL_CONNECTION_STATE": "Bağlantı Durumu",
    "GENERAL_DISPLAY_ONLY": "Yalnızca görüntüleme",
    "GENERAL_TEXTAREA": "Metin alanı",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menü (LCAC)",
    "HEADER_CHAT_CCAC": "Sohbet (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Hızlı İşlemler (RCAC)",
    "HEADER_CHANGE_STATUS": "Durumu Değiştir",
    "HEADER_OT_COIN_BALANCE": "OT Coin Bakiyesi",
    "HEADER_ALT_USER": "Kullanıcı",
    "STATUS_BUSY": "Meşgul",
    "STATUS_AWAY": "Uzakta",
    "STATUS_OFFLINE": "Çevrimdışı",
    "STATUS_INVISIBLE": "Görünmez",
    "NETWORK_CHECKING_CONNECTION": "Bağlantı kontrol ediliyor...",
    "NETWORK_ONLINE_LATENCY": "Çevrimiçi (Gecikme: {latency} ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Ağ: İyi (ping için dokunun)",
    "CHAT_TARGET_ALT": "Sohbet hedefi",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Ara...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "{name} profil resmini aç",
    "CHAT_MESSAGE_INPUT_ARIA": "Mesaj girişi",
    "CHAT_TOGGLE_VIEW_ARIA": "Görünümü değiştir",
    "CHAT_ADD_USER_ARIA": "Kullanıcı ekle",
    "CHAT_ATTACH_ARIA": "Ekle",
    "CHAT_MIC_ARIA": "Mikrofon",
    "CHAT_SEND_ARIA": "Gönder",
    "CHAT_SEARCH_ARIA": "Ara",
    "CHAT_OPEN_SEARCH_ARIA": "Aramayı aç",
    "CHAT_CLOSE_SEARCH_ARIA": "Aramayı kapat",
    "CHAT_ATTACHMENT_ALT": "Ek",
    "CHAT_PREVIEW_ALT": "Önizleme",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Eki kaldır",
    "CHAT_REPLYING_TO": "Yanıtlanan",
    "CHAT_CANCEL_REPLY_ARIA": "Yanıtı iptal et",
    "CHAT_UPLOADING": "Yükleniyor...",
    "CHAT_LOADING_CHATS": "Sohbetler yükleniyor...",
    "CHAT_SEND_FAILED": "Gönderme Başarısız",
    "CHAT_SEND_FAILED_RETRY": "Gönderilemedi. Lütfen tekrar deneyin.",
    "CHAT_RETRY": "Tekrar dene",
    "CHAT_EDITED": "düzenlendi",
    "CHAT_TYPING": "Yazıyor",
    "CHAT_LOADING": "Yükleniyor",
    "CHAT_PENDING_INVITATION": "Bekleyen davet",
    "CHAT_PENDING_INVITATION_MIN": "{count} dk Bekleyen davet",
    "CHAT_PENDING_INVITATION_HR": "{count} sa Bekleyen davet",
    "CHAT_PENDING_INVITATION_DAY": "{count} gün Bekleyen davet",
    "CHAT_WAITING_FOR_YOU": "{label} - Sizi bekliyor",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Kabul bekliyor",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Mikrofon erişimi reddedildi.",
    "CHAT_UPLOAD_FAILED": "Yükleme Başarısız: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Yükleme için internet bağlantısı gerekir. Lütfen çevrimiçi olduğunuzda tekrar deneyin.",
    "CHAT_ERROR_AUTH": "Kimlik Doğrulama Hatası",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Dosya adı veya content_type eksik",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id veya target_id eksik",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Avatar dışı yükleme için conversation_id eksik",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Geçersiz avatar file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase servis istemcisi kullanılamıyor",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Avatar okundu bilgisi yalnızca danışman sohbeti bağlamında geçerlidir",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatar akışı mesajı bulunamadı veya okundu bilgisi için uygun değil",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Avatar mesajı okundu olarak sonlandırılamadı",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 ek",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} ek",
    "CHAT_VOICE_NOTE": "Sesli Not",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Sohbet kullanılamıyor. Bu kullanıcı sizi engelledi.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Sohbet kullanılamıyor. Bu kullanıcıyı engellediniz.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Hesap erişimi politika nedeniyle engellendi.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Sohbet kullanılamıyor. Bu hesap User Zero tarafından kalıcı olarak engellenmiş.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Sohbet kullanılamıyor. Karşılıklı engelleme aktif.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Engelleme politikası nedeniyle sohbet kullanılamıyor.",
    "MESSAGE_PREVIEW_PHOTO": "Fotoğraf",
    "MESSAGE_PREVIEW_VOICE": "Sesli mesaj",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Dosya",
    "MESSAGE_PREVIEW_MESSAGE": "Mesaj",
    "MESSAGE_PREVIEW_SYSTEM": "Sistem mesajı",
    "MESSAGE_PREVIEW_NEW": "Yeni mesaj",
    "MESSAGE_UNKNOWN_FILE": "Bilinmeyen Dosya",
    "MESSAGE_AUDIO_ATTACHMENT": "Ses eki",
    "MESSAGE_FILE_ATTACHMENT": "Ek",
    "BANNER_INVITED_BY": "{label} tarafından davet edildi",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Arama Sonuçları",
    "SEARCH_QUERY_LABEL": "Sorgu:",
    "SEARCH_LOADING_VISIBILITY": "Arama görünürlüğü yükleniyor...",
    "SEARCH_NO_RESULTS": "Geçerli arama kapsamında sonuç bulunamadı.",
    "SHARE_WITH_COLLABRA": "Collabra ile paylaş",
    "SHARE_SEND_TO": "Şuna gönder",
    "SHARE_SELECT_ONE_BANNER": "Bir banner seçin",
    "SHARE_BANNER_LIST_ARIA": "Banner listesi",
    "SHARE_NO_MATCHING_BANNER": "Eşleşen banner yok",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Yorum ekleyin...",
    "SHARE_RECENT_CHATS": "Son sohbetler",
    "SHARE_LEFT_LIST": "Sol liste",
    "SHARE_RIGHT_LIST": "Sağ liste",
    "SHARE_UNTITLED_BANNER": "Başlıksız banner",
    "SHARE_SHARED_CONTENT": "Paylaşılan içerik",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Paylaşılan içerik açılamadı.",
    "SHARE_OPEN_BANNER_FAILED": "Seçilen banner açılamadı.",
    "SHARE_ONE_PHOTO_SELECTED": "1 fotoğraf seçildi",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} fotoğraf seçildi",
    "SHARE_ONE_FILE_SELECTED": "1 dosya seçildi",
    "SHARE_MANY_FILES_SELECTED": "{count} dosya seçildi",
    "FORWARD_MESSAGE_TITLE": "Mesajı İlet",
    "FORWARD_SELECT_RECIPIENTS": "Alıcıları seçin",
    "FORWARD_NO_OTHER_BANNER": "Başka banner mevcut değil.",
    "FORWARD_SEND_TO_COUNT": "{count} kişiye gönder",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "En az bir banner seçin.",
    "FORWARD_FAILED_DEFAULT": "İletme başarısız oldu. Lütfen tekrar deneyin.",
    "FORWARD_PARTIAL_SENT": "{count} gönderildi. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "İletme için kaynak mesaj bulunamadı",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Bu mesajda henüz iletilebilir içerik yok",
    "FORWARD_DESTINATION_MISSING": "İletme hedefi eksik",
    "FORWARD_MESSAGE_PREVIEW": "İletilen mesaj",
    "MENU_PASTE": "Yapıştır",
    "MENU_COPY": "Kopyala",
    "MENU_REPLY": "Yanıtla",
    "MENU_FORWARD": "İlet",
    "MENU_REMOVE_INVITATION": "Daveti Kaldır",
    "MENU_REMOVE_FROM_LIST": "Listeden Kaldır",
    "MENU_GOODBYE_GUEST": "",
    "MENU_ADD_TO_LIST": "Listeye Ekle",
    "MENU_REJECT_INVITATION": "Daveti Reddet",
    "MENU_FRONTEND_VERSION": "Frontend Sürümü",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Banner Bilgisi: {title}",
    "MENU_MESSAGE_BUBBLE": "Mesaj Balonu",
    "MENU_CHAT_CANVAS_HEADER": "Sohbet Tuvali - {zone}",
    "MENU_CANVAS_INFO": "Tuval Bilgisi",
    "MENU_CHAT_CANVAS_SUBLABEL": "Konuşma alanı / mevcut sohbet yüzeyi",
    "MENU_INPUT_AREA_HEADER": "Giriş Alanı - {zone}",
    "MENU_INPUT_AREA_INFO": "Giriş Alanı Bilgisi: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Alt yazma ve işlem araçları yüzeyi",
    "MENU_HEADER": "Başlık - {zone}",
    "MENU_HEADER_INFO": "Başlık Bilgisi: {title}",
    "MENU_HEADER_DESCRIPTION": "Üst gezinme ve sayfa kontrolleri",
    "MENU_ZONE_HEADER": "Bölge - {zone}",
    "MENU_ZONE_SPACE_INFO": "Bölge Alanı Bilgisi",
    "MENU_EMPTY_LIST_SURFACE": "Boş/liste yüzeyi",
    "MENU_BLOCK": "Engelle",
    "MENU_UNBLOCK": "Engeli kaldır",
    "MENU_HIDE_IN_SEARCH": "Aramada Gizle",
    "MENU_UNHIDE_IN_SEARCH": "Aramada Göster",
    "MENU_VISIBLE_IN_SEARCH": "Aramada Görünür",
    "MENU_HIDDEN_IN_SEARCH": "Aramada Gizli",
    "MENU_VISIBLE_IN_USER_LIST": "Kullanıcı Listesinde Görünür",
    "MENU_HIDDEN_IN_USER_LIST": "Kullanıcı Listesinde Gizli",
    "MENU_NOT_BLOCKED": "Engellenmedi",
    "MENU_BLOCKED": "Engellendi",
    "MENU_FRONTEND_VERSION_LOADING": "Yükleniyor...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Banner bazlı değer backend'den yükleniyor. Veritabanı yanıtı gelene kadar hiçbir seçenek aktif olarak işaretlenmez.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend değeri yüklenemedi. Güvenilir aktif seçenek gösterilmiyor.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Açık banner bazlı veritabanı değeri {overrideVersion}. Genel varsayılan {globalDefaultVersion}. Başlangıç bootstrap'ının bunu uygulaması için hedef kullanıcının uygulamayı tamamen yenilemesi veya yeniden açması gerekir.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Açık banner bazlı veritabanı değeri saklanmıyor. FeV2.0.0 varsayılan olarak aktiftir. Genel varsayılan {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Açık banner bazlı veritabanı değeri, hedef uygulama tamamen yeniden yüklendikten sonra aktif olur",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Açık banner bazlı değer saklanmıyor; bu varsayılan bireysel FeV2.0.0 durumudur",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Bu seçenek aynı zamanda geçerli genel varsayılan değere eşittir",
    "MENU_DELETE_PERMANENT_CONFIRM": "{target} veritabanından kalıcı olarak silinsin mi? Bu işlem hesabı, sohbet geçmişini, bağımlılıkları siler ve gelecekte yeniden giriş için tamamen yeni bir davet yolunu zorunlu kılar.",
    "MENU_DELETE_PERMANENTLY": "Kalıcı Olarak Sil",
    "MENU_REFRESH_PAGE": "Sayfayı Yenile",
    "MENU_LOG_OFF": "Oturumu Kapat",
    "MENU_HARD_RELOAD": "En Son Sürümü Al",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "E-posta (Yönetici Kullanıcı)",
    "AUTH_PASSWORD_PLACEHOLDER": "Şifre",
    "AUTH_CONNECTING": "Bağlanıyor...",
    "AUTH_SIGNING_OUT": "Oturum kapatılıyor...",
    "AUTH_BACK_TO_LOGIN": "Girişe dön",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Geçersiz sunucu yanıtı: Token bulunamadı.",
    "AUTH_LOGIN_FAILED": "Giriş Başarısız",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Şifreler eşleşmiyor.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Şifreler eşleşmiyor!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Şifreler tam olarak eşleşmelidir.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Yeni Şifre",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Şifreyi Onayla",
    "AUTH_CHANGE_PASSWORD": "Şifreyi Değiştir",
    "AUTH_SAVING_PASSWORD": "Kaydediliyor...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Şifre başarıyla güncellendi.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Şifre şu anda değiştirilemiyor.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Şifrenizi değiştirmek için giriş yapmış olmanız gerekir.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Yeni şifre görünürlüğünü değiştir",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Şifre onayı görünürlüğünü değiştir",
    "REGISTER_TITLE": "Kaydı Tamamla",
    "REGISTER_SUBTITLE": "Lütfen şifrenizi manuel olarak belirleyin.",
    "REGISTER_CREATING_ACCOUNT": "Hesap Oluşturuluyor...",
    "REGISTER_FINISH_SETUP": "Kurulumu Bitir",
    "REGISTER_FAILED_SET_PASSWORD": "Şifre belirlenemedi",
    "INVITE_EMAIL_INSTRUCTION": "Lütfen davet edilen kişinin e-postasını girin (Format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Davet Et",
    "INVITE_EMAIL_REQUIRED": "Lütfen davet edilen kişinin e-postasını girin.",
    "INVITE_EMAIL_INVALID": "Geçersiz e-posta formatı. Lütfen şunu kullanın: user@example.com",
    "PENDING_INVITATION_TITLE": "Bekleyen Davet",
    "PENDING_INVITATION_REMOVE_QUESTION": "Bu bekleyen davet veritabanından kaldırılsın mı?",
    "PENDING_INVITATION_KEEP": "Daveti Koru",
    "PENDING_INVITATION_REMOVAL_FAILED": "Kaldırma başarısız oldu.",
    "REMOVE_FROM_LIST_TITLE": "Listeden Kaldır",
    "REMOVE_FROM_LIST_WARNING": "Bu kullanıcı şimdi her iki listeden kaldırılsın mı? Sohbet erişimi hemen kesilecektir. Tek dönüş yolu yeni bir davettir.",
    "REMOVE_FROM_LIST_KEEP": "Kullanıcıyı Listede Tut",
    "REMOVE_FROM_LIST_FAILED": "Listeden kaldırma başarısız oldu.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Ayar ve Canlı Durum",
    "PERMISSION_DIALOG_ARIA": "Ayar ve Canlı Durum",
    "PERMISSION_TRIGGER_ARIA": "Ayarlar açılır penceresi tetikleyicisi",
    "PERMISSION_CLOSE_ARIA": "İzin açılır penceresini kapat",
    "PERMISSION_LIVE_STATUS": "Canlı Durum",
    "PERMISSION_SYSTEM_PERMISSION": "Sistem İzni",
    "PERMISSION_APP_PUSH": "Uygulama Push",
    "PERMISSION_LOCATION_PERMISSION": "Konum İzni",
    "PERMISSION_APP_LOCATION": "Uygulama Konumu",
    "PERMISSION_CONTROLS": "İzin Kontrolleri",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push Bildirimleri",
    "PERMISSION_LOCATION_ACCESS": "Konum Erişimi",
    "PERMISSION_IN_APP_SETTINGS": "Uygulama İçi Ayarlar",
    "PERMISSION_ALERT_SOUND": "Uyarı Sesi",
    "PERMISSION_APP_BADGE": "Uygulama Rozeti",
    "PERMISSION_PASSWORD_SETTINGS": "Şifre Ayarları",
    "PERMISSION_NAVIGATION_STATUS": "Gezinme Durumu",
    "PERMISSION_SELECTED_ZONE": "Seçili Bölge",
    "PERMISSION_STAGED_CHAT_BANNER": "Hazırlanan Sohbet Bannerı",
    "PERMISSION_CANVAS_CONTENT": "Tuval İçeriği",
    "PERMISSION_YOUR_DEVICES": "Cihazlarınız ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Cihaz listesini yenile",
    "PERMISSION_REFRESH_LIST": "Listeyi Yenile",
    "PERMISSION_NO_REGISTERED_DEVICES": "Kayıtlı cihaz bulunamadı.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Ayarlar açılır penceresini yeniden boyutlandır",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Push bildirimlerini değiştir",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Konum erişimini değiştir",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Uyarı sesini değiştir",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Uygulama rozetini değiştir",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Profil görünürlüğünü değiştir",
    "PERMISSION_OFF_IN_V1": "v1'de kapalı",
    "PERMISSION_CHAT": "Sohbet",
    "PERMISSION_BANNER_LIST": "Banner Listesi",
    "PERMISSION_PUSH_DISABLED_V1": "Push bildirimleri v1 Google Play sürümü için devre dışıdır.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Push bildirimleri bu cihaz için AÇIK.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Sistem bildirimleri engellendi. Ayarlar yardımını açmak için dokunun.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Teslimat güvenilirliğini artırmak için AÇIK konuma getirin.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Sistem bildirimlerini devre dışı bırakmak için tarayıcı/site bildirim ayarlarınızı açın ve bu siteyi Engelle olarak ayarlayın.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Sistem bildirim iznini değiştirmek için tarayıcı/site bildirim ayarlarınızı açın ve bu siteyi İzin Ver olarak ayarlayın.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Konum erişimi, mesafeye dayalı LCAC sıralaması ve harita konumlandırması için AÇIK.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Konum API'si bu ortamda desteklenmiyor.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Konum erişimi engellendi. Ayarlar yardımını açmak için dokunun.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Hassas mesafeye dayalı LCAC sıralaması ve uygulama içi harita konumlandırmasına izin vermek için AÇIK konuma getirin.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Konum erişimi bu ortamda desteklenmiyor.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Konum erişimini devre dışı bırakmak için tarayıcı/site konum ayarlarınızı açın ve bu siteyi Engelle olarak ayarlayın.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Mesafe sıralaması ve uygulama içi harita konumlandırması için konum erişimini etkinleştirmek üzere tarayıcı/site konum ayarlarınızı açın ve bu siteyi İzin Ver olarak ayarlayın.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Kayıtlı cihazlar şu anda yüklenemiyor.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "UI Bridge yükleniyor...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Local Bridge yükleniyor...",
    "RUNTIME_LOADING_BACKEND": "Backend yükleniyor...",
    "RUNTIME_LOADING": "Yükleniyor...",
    "RUNTIME_LOADING_FROM_DATABASE": "Veritabanından yükleniyor...",
    "RUNTIME_BACKEND_CONNECTED": "Backend Bağlandı",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Önbelleğe Alınmış Fallback Aktif",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Varsayılan Fallback Aktif",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallback Varsayılanları Aktif",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Backend Üzerinden Kaydediliyor...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Backend Servisine Kaydedildi",
    "RUNTIME_SAVE_FAILED": "Kaydetme Başarısız",
    "RUNTIME_LOAD_FAILED": "Yükleme Başarısız",
    "RUNTIME_CONNECTED": "Bağlandı",
    "RUNTIME_LOGIN_REQUIRED": "Giriş Gerekli",
    "RUNTIME_SAVED": "Kaydedildi",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI Hazır - Runtime Beklemede",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Korunan backend seçici servisi istenen model seçeneğini reddetti veya kaydedemedi.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Korunan backend seçici servisi istenen WF1 yönlendirme değişikliğini reddetti veya kaydedemedi.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Seçici artık aktif yapılandırmayı, Qwen yönlendirmesini ve izin verilen seçenekleri korunan backend servisinden okuyor.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend seçici servisi şu anda kullanılamıyor, bu yüzden son önbelleğe alınmış seçici durumu kullanılıyor.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Backend veya önbelleğe alınmış seçici durumu yüklenemediği için seçici varsayılan değerleri aktif.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Korunan backend seçici servisi aktif WF1 yönlendirme yapılandırmasını güncelledi ve runtime domain önbelleğini yeniledi.",
    "FRONTEND_VERSION_TITLE": "Frontend Sürümü",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Bu seçici tüm kullanıcılar için aktif frontend sürümünü kontrol eder. FeV2.0.0 aktiftir.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Bu seçici aktif frontend sürümünü config_domain_registry'den okur. Runtime FeV2.0.0 olarak çözümlenir.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend frontend sürümü yapılandırması yüklenemedi, bu yüzden kodlanmış FeV2.0.0 varsayılanı başlangıç bootstrap'ı korunan servisi tekrar okuyana kadar aktif kalır.",
    "FRONTEND_VERSION_HELPER_SAVED": "Aktif frontend sürümü config_domain_registry'ye kaydedildi. Tam yenileme veya bir sonraki uygulama yüklemesi runtime değerini uygular.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend frontend sürümü kontrol servisi istenen genel sürümü kaydedemedi.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Aktif frontend sürümü.",
    "CHAT_DELETE_WINDOW_TITLE": "Sohbet Silme Penceresi",
    "CHAT_DELETE_HELPER": "Bu değer, herkes için silme kullanılabilirlik penceresini saniye cinsinden kontrol eder. Backend koruması kaydetmeden hemen sonra değişir. Balon görünürlüğü tam yenileme veya bir sonraki uygulama yüklemesinden sonra değişir.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend sohbet silme kontrol servisi yüklenemedi, bu yüzden kodlanmış varsayılan değer başlangıç bootstrap'ı korunan servisi tekrar okuyana kadar aktif kalır.",
    "CHAT_DELETE_HELPER_SAVED": "Herkes için silme kullanılabilirlik penceresi config_domain_registry'ye kaydedildi. Backend koruması hemen değişir. Balon görünürlüğü tam yenileme veya bir sonraki uygulama yüklemesinden sonra değişir.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend sohbet silme kontrol servisi istenen pencere değerini kaydedemedi.",
    "CHAT_DELETE_WINDOW_LABEL": "Herkes için silme penceresi",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} sn",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Değeri tam saniye olarak saklayın. Geçerli üretim değeri 86400 saniye = 1 gündür.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Pencere Saniyesi",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "0'dan büyük veya 0'a eşit bir tam sayı girin.",
    "CHAT_DELETE_SAVE_BUTTON": "Silme Penceresini Kaydet",
    "GUEST_BANNER_CONTROL_TITLE": "",
    "GUEST_BANNER_CONTROL_LABEL": "",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "",
    "GUEST_BANNER_CONTROL_HELPER": "",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "",
    "GUEST_BANNER_PENDING_TTL_INVALID": "",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "",
    "GUEST_QR_LOADING": "",
    "GUEST_QR_READY": "",
    "GUEST_QR_ALT": "",
    "GUEST_QR_LOAD_FAILED": "",
    "GUEST_SESSION_ACTIVE": "",
    "GUEST_PUBLIC_TITLE": "",
    "GUEST_PUBLIC_CONNECTING": "",
    "GUEST_PUBLIC_CONNECTED": "",
    "GUEST_PUBLIC_UNAVAILABLE": "",
    "GUEST_PUBLIC_SEND_FAILED": "",
    "UI_TEXTS_RUNTIME_TITLE": "",
    "UI_TEXTS_RUNTIME_BACKEND": "",
    "UI_TEXTS_RUNTIME_CACHED": "",
    "UI_TEXTS_RUNTIME_DEFAULTS": "",
    "UI_TEXTS_RUNTIME_SAVED": "",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "",
    "PROFILE_VISIBILITY_TITLE": "Profil Görünürlüğü",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Hesap görünürlüğünü yönetmek için giriş yapmış olmanız gerekir.",
    "PROFILE_VISIBILITY_HELPER": "Bu anahtar yalnızca hesap görünürlüğü durumunuzu günceller. Keşfedilebilirlik ve banner listesi davranışı bu aşamada değişmeden kalır.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Profil görünürlüğü şu anda yüklenemedi.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Profil görünürlüğü şu anda güncellenemedi.",
    "PROFILE_VISIBILITY_SAVED": "Hesap görünürlüğünüz artık {visibility}. Keşfedilebilirlik işaretleri bu aşamada değişmeden kalır.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Herkese Açık Hesap",
    "PROFILE_VISIBILITY_STORED": "Saklanan Görünürlük",
    "WF1_MODEL_CONTROL_TITLE": "WF1 Model Kontrolü",
    "WF1_ENABLE_TRANSLATION": "Çeviriyi / Pivotu Etkinleştir",
    "WF1_TRANSLATION_ACTIVE": "Yapay zeka çevirisi aktif.",
    "WF1_TRANSLATION_INACTIVE": "WF1 çalışmaya devam eder ancak kaynak metin kopyalanır ve pivot pasif olarak işaretlenir.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Aktif Runtime Slotu",
    "WF1_ALLOW_SAME_LANGUAGE": "Aynı Dil Çiftleri İçin Yapay Zekaya İzin Ver",
    "WF1_SAME_LANGUAGE_ACTIVE": "Aynı dil çiftleri normal WF1 yönlendirmesini izler.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Aynı dil çiftleri yapay zekayı atlar ve aktif pivot dili yok olarak saklanır.",
    "WF1_QWEN_ROUTING": "Qwen Çift Yönlendirmesi",
    "WF1_QWEN_ROUTING_HELPER": "Aşağıda işaretlenen diller, çift aynı işaretli dil, işaretli bir dil ile İngilizce veya iki işaretli İngilizce dışı dil olduğunda Qwen-Max kullanır. Aksi halde seçili birincil model aktif kalır.",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter Test Slotu",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter Test Slotu - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Yalnızca Kalite Testi",
    "WF1_OPENROUTER_HELPER": "Bu slot yalnızca geçici OpenRouter kalite testleri için düzenlenebilir. Bu slotun kendisi aktif model olmadıkça operasyonel Qwen çift yönlendirme yolunu değiştirmez.",
    "WF1_LABEL": "Etiket",
    "WF1_PRODUCT": "Ürün",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Sağlayıcı: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter Test Slotu · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "OpenRouter üzerinden Qwen-Max",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google liste fiyatı",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI liste fiyatı",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter liste fiyatı",
    "LANGUAGE_ENGLISH": "İngilizce",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Çince (Basitleştirilmiş)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Çince (Geleneksel)",
    "LANGUAGE_JAPANESE": "Japonca",
    "LANGUAGE_KOREAN": "Korece",
    "LANGUAGE_PERSIAN": "Farsça",
    "LANGUAGE_TURKISH_ISTANBUL": "Türkçe (İstanbul)",
    "LANGUAGE_ARABIC": "Arapça",
    "LANGUAGE_FRENCH": "Fransızca",
    "LANGUAGE_GERMAN": "Almanca",
    "LANGUAGE_SPANISH": "İspanyolca",
    "LANGUAGE_PORTUGUESE": "Portekizce",
    "LANGUAGE_ITALIAN": "İtalyanca",
    "LANGUAGE_RUSSIAN": "Rusça",
    "LANGUAGE_DUTCH": "Felemenkçe",
    "LANGUAGE_VIETNAMESE": "Vietnamca",
    "LANGUAGE_INDONESIAN": "Endonezce",
    "LANGUAGE_THAI": "Tayca",
    "LANGUAGE_MALAY": "Malayca",
    "WF1_PRICING_CUSTOM": "Fiyatlandırma: özel slot modeli - güncel OpenRouter fiyatlandırmasını kontrol edin",
    "WF1_SAVE_OPENROUTER_SLOT": "OpenRouter Slotunu Kaydet",
    "WF1_PRICING_LINE": "Girdi {input} - Çıktı {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "Bölge Görünürlüğü Kontrolü",
    "ZONE_ENABLE": "{zone} etkinleştir",
    "ZONE_ENABLED_NOTE": "{zone}, bir sonraki uygulama yüklemesinden sonra izin verilen roller için görünebilir.",
    "ZONE_DISABLED_NOTE": "{zone}, bir sonraki uygulama yüklemesinden sonra S_Admin olmayan kullanıcılar için yok sayılır.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin bu rol listesini atlar ve her zaman erişimi korur.",
    "ZONE_ROLE_LOCKED": "Bu bölge devre dışıyken rol seçimleri geçici olarak kilitlenir ve bölge tekrar etkinleştirildiğinde tam olarak kaydedildiği gibi geri döner.",
    "ZONE_LCAC_CONTROL": "LCAC Kontrolü",
    "ZONE_RCAC_CONTROL": "RCAC Kontrolü",
    "ZONE_LCAC_DESCRIPTION": "Sol ayrılmış bölgenin varlığını ve onu görebilecek rolleri kontrol eder.",
    "ZONE_RCAC_DESCRIPTION": "Sağ ayrılmış bölgenin varlığını ve onu görebilecek rolleri kontrol eder.",
    "ZONE_VISIBILITY_BACKEND": "Bölge görünürlüğü bootstrap'ı artık korunan backend servisinden okuyor. Değişiklikler bir sonraki uygulama yüklemesinde uygulanır.",
    "ZONE_VISIBILITY_CACHED": "Backend bölge görünürlüğü servisi şu anda kullanılamıyor, bu yüzden önbelleğe alınmış veya yerel varsayılanlar aktif.",
    "ZONE_VISIBILITY_DEFAULTS": "Backend veya önbelleğe alınmış durum yüklenemediği için bölge görünürlüğü varsayılanları aktif.",
    "ZONE_VISIBILITY_SAVED": "Bölge görünürlüğü bootstrap'ı kaydedildi. Runtime uygulaması için zorla yeniden yükleme veya bir sonraki uygulama yüklemesi gerekir.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Korunan backend servisi istenen bölge görünürlüğü değişikliğini kaydedemedi.",
    "ROLE_MEMBER": "Üye",
    "ROLE_STAFF": "Personel",
    "ROLE_ADMIN": "Yönetici",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Yeni mesajları almak için bildirimleri etkinleştirin.",
    "MAIN_LOG_OUT": "Oturumu Kapat",
    "NOTIFICATION_NEW_MESSAGE": "Yeni mesaj",
    "NOTIFICATION_UNREAD_MESSAGE": "Okunmamış bir mesajınız var.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Tam Görünüm",
    "MEDIA_AUDIO_ATTACHMENT": "Ses eki",
    "MEDIA_FILE_FALLBACK": "Dosya",
    "MEDIA_DOWNLOAD_READY": "Ek indirmeye hazır",
    "MEDIA_TYPE_UNSUPPORTED": "Tam görünüm için tür desteklenmiyor",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Önceki resim",
    "MEDIA_NEXT_IMAGE_ARIA": "Sonraki resim",
    "MEDIA_OPEN_ORIGINAL": "Orijinali Aç",
    "MEDIA_DOWNLOAD": "İndir",
    "MEDIA_CLOSE_ARIA": "Kapat",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name} profil resmi",
    "MEDIA_PROFILE_ALT": "{name} profili",
    "MEDIA_UPLOAD_FAILED": "Yükleme başarısız",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend Token Hatası",
    "MEDIA_UPLOAD_URL_MISSING": "Kritik: backend yanıtında yükleme URL'si eksik.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Sohbet yüklemesi için kimlik doğrulama tokenı eksik",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Sohbet yükleme tokenı isteği başarısız oldu",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Geçersiz sohbet yükleme yanıtı",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS Yüklemesi Başarısız",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Dosya adı veya contentType eksik",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path eksik",
    "BLOCK_NOTICE_TITLE": "Kalıcı Engelleme Bildirimi",
    "BLOCK_NOTICE_MESSAGE": "Hesabınız politika ihlali nedeniyle geçici olarak askıya alınmıştır.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Bunun takip gerektirdiğini düşünüyorsanız lütfen iletişime geçin:",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "e-posta yoluyla.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Bilinmeyen Kullanıcı",
    "GENERAL_GUEST": "Misafir",
    "ADVISOR_FOR_CLIENT": "{client_display_name} için Danışman",
    "GUEST_FOR_CLIENT": "",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token ve şifre gereklidir",
    "AUTH_ERROR_REQUEST_BODY_JSON": "İstek gövdesi JSON olmalıdır",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Geçersiz veya süresi dolmuş davet tokenı",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Şifre belirleme başarısız: oturum veya kullanıcı eksik",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Şifre belirleme, giriş sırasında başarısız oldu",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Yönetici tokenı oluşturma başarısız oldu",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Giriş başarısız: oturum veya kullanıcı eksik",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Kayıt başarılı. Doğrulama için lütfen e-postanızı kontrol edin.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Kayıt başarısız, bilinmeyen hata",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Geçersiz token işleme",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Erişim tokenı gereklidir",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Token hash önizlemesi, yönlendirme URL'sinden e-posta ipucu gerektirir",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Bu token için kimlik çözümlenemiyor",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "WF1 LLM seçici servisine yalnızca User Zero erişebilir.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Bölge görünürlüğü kontrol servisine yalnızca User Zero erişebilir.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Frontend sürümü kontrol servisine yalnızca User Zero erişebilir.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Başka bir kullanıcının frontend sürümünü yalnızca User Zero inceleyebilir.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Sohbet silme kontrol servisine yalnızca User Zero erişebilir.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Bir kullanıcı hesabını kalıcı olarak yalnızca User Zero silebilir.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Geçersiz istek payload'ı.",
    "API_ERROR_INTERNAL_SERVER": "İç Sunucu Hatası",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Backend'de fonksiyon eksik (Yeniden Yükleme Gerekli)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "delivered/read geçişleri için yalnızca DB RPC'ye izin verilir.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Başka bir mesaj göndermeden önce lütfen bekleyin.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Mesaj başarıyla gönderildi.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "İletişim servisi kullanılamıyor.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Mesaj gönderimi başarısız oldu.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Ad gereklidir.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "E-posta geçersiz.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Mesaj gereklidir.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Seçici payload'ı gereklidir.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Bölge görünürlüğü payload'ı gereklidir.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Frontend sürümü payload'ı gereklidir.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Sohbet silme kontrol payload'ı gereklidir.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Kimliği doğrulanmış kullanıcı kimliği gereklidir.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Kimliği doğrulanmış görüntüleyici kullanıcı kimliği gereklidir.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Kimliği doğrulanmış aktör kullanıcı kimliği gereklidir.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id gereklidir.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id gereklidir.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids listesi gereklidir.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email gereklidir.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by gereklidir.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Arama runtime'ı genel frontend sürümü tarafından devre dışı bırakılmıştır.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Bu bekleyen daveti iptal etmenize izin verilmiyor.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Kullanıcı zaten kayıtlı olduğu için bu davet artık iptal edilemez.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Bekleyen davet bulunamadı.",
    "INVITE_REPLY_ALREADY_MEMBER": "Tebrikler, arkadaşınız ({invitee_email}) zaten bu uygulamaya kayıtlı ve bu çalışma alanının üyesi.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "{invitee_email} için bekleyen bir davet var, ancak tekrar e-postası tetiklenemedi. Lütfen posta günlüklerini kontrol edin.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "{invitee_email} için davet kaydı oluşturuldu, ancak e-posta teslimi doğrulanamadı. Lütfen daha sonra tekrar deneyin veya posta günlüklerini kontrol edin.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Davet kaydı oluşturulamadı. Lütfen daha sonra tekrar deneyin.",
    "INVITE_REPLY_SYSTEM_ERROR": "Davet sürecinde Sistem Hatası: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend Yapılandırma Hatası: Supabase kimlik bilgileri eksik",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend Yapılandırma Hatası: Geçersiz Supabase URL'si",
    "CHAT_ERROR_ACCESS_DENIED": "Erişim Reddedildi",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Metin mesajları için içerik boş olamaz",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Konuşma ID'si belirlenemedi",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC kimlik doğrulama bağlamı eksik",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC geçersiz mesaj payload'ı döndürdü",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Ekleme başarısız, veri döndürülmedi",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations bir liste olmalıdır",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Geçersiz operation payload'ı",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Desteklenmeyen operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id gereklidir",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Mesaj bulunamadı",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Silme yalnızca kendi mesajınızda izinlidir",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Herkes için silme artık bu mesaj için kullanılamıyor",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Herkes için silme başarısız oldu",
    "API_ERROR_SERVER_CONFIGURATION": "Sunucu yapılandırma hatası",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Webhook secret başlığı eksik",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Yetkisiz webhook kaynağı",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend yapılandırma hatası",
    "API_ERROR_MODULE_ATTRIBUTE": "Modül Attribute Hatası: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Bekleyen auth kullanıcısı kaldırılırken davet silme işleminden önce başarısız oldu.",
    "CHAT_ERROR_DB": "DB Hatası: {error}",
}
