# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/uk.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Головна",
    "APP_TITLE": "Платформа ШІ OTMEGA",
    "APP_SUBTITLE": "ШІ-радник",
    "CHAT_PLACEHOLDER": "Введіть ваше повідомлення...",
    "CHAT_SEND_BUTTON": "Надіслати",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Радник може помилятися, тому перевіряйте інформацію.",
    "STATUS_ONLINE": "Онлайн",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Меню",
    "ICON_NEW_CHAT": "Новий чат",
    "ICON_HISTORY": "Історія",
    "ICON_TEMPLATES": "Шаблони",
    "ICON_SETTINGS": "Налаштування",
    "ICON_USER_PROFILE": "Профіль користувача",
    "ICON_QUICK_ACTIONS": "Швидкі дії",
    "ICON_PINNED": "Закріплено",
    "ICON_GALLERY": "Галерея",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Встановити застосунок",
    "PWA_ANDROID_MSG": "Встановіть цей застосунок на свій пристрій для кращого досвіду та офлайн-доступу.",
    "PWA_IOS_MSG": "Щоб встановити цей застосунок на iPhone/iPad:\n1. Натисніть кнопку Поділитися нижче\n2. Виберіть 'Додати на головний екран'",
    "PWA_BTN_INSTALL": "Встановити",
    "PWA_BTN_LATER": "Можливо пізніше",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Увійдіть до мережі радників",
    "AUTH_HEADER_SIGNUP": "Створіть свій уніфікований обліковий запис",
    "AUTH_HEADER_LOGIN_NETWORK": "Увійдіть до мережі радників",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Створіть свій уніфікований обліковий запис",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Увійти",
    "AUTH_BUTTON_SIGNUP": "Створити обліковий запис",
    "AUTH_BUTTON_GOOGLE": "Продовжити з Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Забули пароль",
    "AUTH_BUTTON_SEND_RESET_LINK": "Надіслати посилання для скидання",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Немає облікового запису? Зареєструйтеся",
    "AUTH_PROMPT_LOGIN": "Вже маєте обліковий запис? Увійдіть",
    "AUTH_HELPER_TEXT_SIGNUP": "Ви створюєте уніфікований обліковий запис, який можна використовувати для доступу до всіх радників на цій платформі.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Ви створюєте уніфікований обліковий запис, який можна використовувати для доступу до всіх радників на цій платформі.",
    "AUTH_HELPER_TEXT_LOGIN": "Використовуйте той самий обліковий запис (email/пароль або Google), який ви використовували для інших радників у цій мережі.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Використовуйте той самий обліковий запис (email/пароль або Google), який ви використовували для інших радників у цій мережі.",
    "AUTH_FORGOT_PASSWORD_LINK": "Забули пароль?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Скинути пароль",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Введіть свою email-адресу, і ми надішлемо вам посилання для скидання пароля.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Email",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Виконується вхід...",
    "AUTH_STATUS_LOADING_SIGNUP": "Створюємо ваш обліковий запис...",
    "AUTH_STATUS_LOADING_RESET": "Надсилаємо посилання для скидання...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Вхід успішний! Перезавантаження...",
    "AUTH_STATUS_SUCCESS_RESET": "Посилання для скидання успішно надіслано. Перевірте вашу електронну пошту.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Посилання для скидання пароля успішно надіслано. Перевірте вашу електронну пошту.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Неправильний email або пароль.",
    "AUTH_ERROR_EMAIL_EXISTS": "Обліковий запис із цим email уже існує в мережі радників.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Обліковий запис із цим email уже існує. Будь ласка, увійдіть. Зараз ви є учасником:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Обліковий запис із цим email уже існує в мережі радників. Закрийте це вікно та використайте розділ 'Login' з тим самим email і вашим попереднім паролем.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Зараз ви є учасником:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "Email і пароль обов’язкові.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Обліковий запис створено, але не вдалося налаштувати членство. Зверніться до підтримки.",
    "AUTH_ERROR_DEFAULT": "Сталася помилка. Спробуйте ще раз.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "",
    "AUTH_FORGOT_PASSWORD_ERROR": "Не вдалося надіслати посилання для скидання. Спробуйте ще раз.",
    "INVITE_REPLY_EMAIL_SENT": "Лист-запрошення Collabra було надіслано вашому другу на {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Лист-запрошення Collabra було повторно надіслано вашому другу на {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Показати пароль",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Приховати пароль",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Скасувати",
    "GENERAL_CLOSE": "Закрити",
    "GENERAL_SEND": "Надіслати",
    "GENERAL_SEARCH": "Пошук",
    "GENERAL_RESET": "Скинути",
    "GENERAL_ENABLE": "Увімкнути",
    "GENERAL_LOADING": "Завантаження...",
    "GENERAL_DELETE": "Видалити",
    "GENERAL_DELETING": "Видалення...",
    "GENERAL_SAVE_PASSWORD": "Зберегти пароль",
    "AUTH_REMEMBER_EMAIL_LABEL": "Запам’ятати email",
    "GENERAL_SAVING": "Збереження...",
    "GENERAL_SENDING": "Надсилання...",
    "GENERAL_REMOVING": "Видалення...",
    "GENERAL_CONFIRM_REMOVAL": "Підтвердити видалення",
    "GENERAL_EMPTY": "Порожньо",
    "GENERAL_UNAVAILABLE": "Недоступно",
    "GENERAL_ENABLED": "Увімкнено",
    "GENERAL_DISABLED": "Вимкнено",
    "GENERAL_GRANTED": "Надано",
    "GENERAL_DENIED": "Відмовлено",
    "GENERAL_DEFAULT": "За замовчуванням",
    "GENERAL_UNSUPPORTED": "Не підтримується",
    "GENERAL_PUBLIC": "Публічний",
    "GENERAL_PRIVATE": "Приватний",
    "GENERAL_USERNAME": "Ім’я користувача",
    "GENERAL_EMAIL": "Email",
    "GENERAL_YOU": "Ви",
    "GENERAL_USER": "Користувач",
    "GENERAL_UNKNOWN": "Невідомо",
    "GENERAL_VISITOR": "Відвідувач",
    "GENERAL_PROFILE": "Профіль",
    "GENERAL_BANNER": "Банер",
    "GENERAL_UNKNOWN_BANNER": "Невідомий банер",
    "GENERAL_ADVISOR_BANNER": "Банер радника",
    "GENERAL_NOT_AVAILABLE": "Н/Д",
    "GENERAL_NOT_SELECTED": "Не вибрано",
    "GENERAL_NO_EMAIL_FOUND": "Email не знайдено",
    "GENERAL_USER_ZERO_ONLY": "Тільки User Zero",
    "GENERAL_CONNECTION_STATE": "Стан з’єднання",
    "GENERAL_DISPLAY_ONLY": "Тільки відображення",
    "GENERAL_TEXTAREA": "Текстова область",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Меню (LCAC)",
    "HEADER_CHAT_CCAC": "Чат (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Швидкі дії (RCAC)",
    "HEADER_CHANGE_STATUS": "Змінити статус",
    "HEADER_OT_COIN_BALANCE": "Баланс OT Coin",
    "HEADER_ALT_USER": "Користувач",
    "STATUS_BUSY": "Зайнятий",
    "STATUS_AWAY": "Відійшов",
    "STATUS_OFFLINE": "Офлайн",
    "STATUS_INVISIBLE": "Невидимий",
    "NETWORK_CHECKING_CONNECTION": "Перевірка з’єднання...",
    "NETWORK_ONLINE_LATENCY": "Онлайн (затримка: {latency} мс)",
    "NETWORK_GOOD_TAP_TO_PING": "Мережа: добра (натисніть для ping)",
    "CHAT_TARGET_ALT": "Ціль чату",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Пошук...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Відкрити фото профілю {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Поле введення повідомлення",
    "CHAT_TOGGLE_VIEW_ARIA": "Перемкнути вигляд",
    "CHAT_ADD_USER_ARIA": "Додати користувача",
    "CHAT_ATTACH_ARIA": "Прикріпити",
    "CHAT_MIC_ARIA": "Мікрофон",
    "CHAT_SEND_ARIA": "Надіслати",
    "CHAT_SEARCH_ARIA": "Пошук",
    "CHAT_OPEN_SEARCH_ARIA": "Відкрити пошук",
    "CHAT_CLOSE_SEARCH_ARIA": "Закрити пошук",
    "CHAT_ATTACHMENT_ALT": "Вкладення",
    "CHAT_PREVIEW_ALT": "Попередній перегляд",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Видалити вкладення",
    "CHAT_REPLYING_TO": "Відповідь на",
    "CHAT_CANCEL_REPLY_ARIA": "Скасувати відповідь",
    "CHAT_UPLOADING": "Завантаження...",
    "CHAT_LOADING_CHATS": "Завантаження чатів...",
    "CHAT_SEND_FAILED": "Не вдалося надіслати",
    "CHAT_SEND_FAILED_RETRY": "Надсилання не вдалося. Спробуйте ще раз.",
    "CHAT_RETRY": "Повторити",
    "CHAT_EDITED": "змінено",
    "CHAT_TYPING": "Введення",
    "CHAT_LOADING": "Завантаження",
    "CHAT_PENDING_INVITATION": "Запрошення очікує",
    "CHAT_PENDING_INVITATION_MIN": "{count} хв запрошення очікує",
    "CHAT_PENDING_INVITATION_HR": "{count} год запрошення очікує",
    "CHAT_PENDING_INVITATION_DAY": "{count} дн запрошення очікує",
    "CHAT_WAITING_FOR_YOU": "{label} - Очікує на вас",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Очікує прийняття",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Доступ до мікрофона заборонено.",
    "CHAT_UPLOAD_FAILED": "Завантаження не вдалося: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Для завантаження потрібне інтернет-з’єднання. Спробуйте ще раз, коли будете онлайн.",
    "CHAT_ERROR_AUTH": "Помилка автентифікації",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Відсутня назва файлу або content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Відсутній conversation_id або target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Відсутній conversation_id для завантаження не аватара",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "Недійсний file_path аватара",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Сервісний клієнт Supabase недоступний",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Підтвердження прочитання аватара дійсне лише в контексті чату з радником",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Повідомлення потоку аватара не знайдено або воно не підходить для підтвердження прочитання",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Не вдалося позначити повідомлення аватара як прочитане",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 вкладення",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} вкладень",
    "CHAT_VOICE_NOTE": "Голосова нотатка",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Чат недоступний. Цей користувач заблокував вас.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Чат недоступний. Ви заблокували цього користувача.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Доступ до облікового запису заблоковано політикою.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Чат недоступний. Цей обліковий запис остаточно заблокований User Zero.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Чат недоступний. Активне взаємне блокування.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Чат недоступний через політику блокування.",
    "MESSAGE_PREVIEW_PHOTO": "Фото",
    "MESSAGE_PREVIEW_VOICE": "Голосове повідомлення",
    "MESSAGE_PREVIEW_VIDEO": "Відео",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Файл",
    "MESSAGE_PREVIEW_MESSAGE": "Повідомлення",
    "MESSAGE_PREVIEW_SYSTEM": "Системне повідомлення",
    "MESSAGE_PREVIEW_NEW": "Нове повідомлення",
    "MESSAGE_UNKNOWN_FILE": "Невідомий файл",
    "MESSAGE_AUDIO_ATTACHMENT": "Аудіовкладення",
    "MESSAGE_FILE_ATTACHMENT": "Вкладення",
    "BANNER_INVITED_BY": "запрошено {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Результати пошуку",
    "SEARCH_QUERY_LABEL": "Запит:",
    "SEARCH_LOADING_VISIBILITY": "Завантаження видимості пошуку...",
    "SEARCH_NO_RESULTS": "У поточній області пошуку нічого не знайдено.",
    "SHARE_WITH_COLLABRA": "Поділитися з Collabra",
    "SHARE_SEND_TO": "Надіслати до",
    "SHARE_SELECT_ONE_BANNER": "Виберіть один банер",
    "SHARE_BANNER_LIST_ARIA": "Список банерів",
    "SHARE_NO_MATCHING_BANNER": "Відповідних банерів немає",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Додайте коментар...",
    "SHARE_RECENT_CHATS": "Нещодавні чати",
    "SHARE_LEFT_LIST": "Лівий список",
    "SHARE_RIGHT_LIST": "Правий список",
    "SHARE_UNTITLED_BANNER": "Банер без назви",
    "SHARE_SHARED_CONTENT": "Поширений вміст",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Не вдалося відкрити поширений вміст.",
    "SHARE_OPEN_BANNER_FAILED": "Не вдалося відкрити вибраний банер.",
    "SHARE_ONE_PHOTO_SELECTED": "Вибрано 1 фото",
    "SHARE_MANY_PHOTOS_SELECTED": "Вибрано фото: {count}",
    "SHARE_ONE_FILE_SELECTED": "Вибрано 1 файл",
    "SHARE_MANY_FILES_SELECTED": "Вибрано файлів: {count}",
    "FORWARD_MESSAGE_TITLE": "Переслати повідомлення",
    "FORWARD_SELECT_RECIPIENTS": "Виберіть одержувачів",
    "FORWARD_NO_OTHER_BANNER": "Інший банер недоступний.",
    "FORWARD_SEND_TO_COUNT": "Надіслати до {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Виберіть принаймні один банер.",
    "FORWARD_FAILED_DEFAULT": "Пересилання не вдалося. Спробуйте ще раз.",
    "FORWARD_PARTIAL_SENT": "Надіслано: {count}. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Вихідне повідомлення для пересилання не знайдено",
    "FORWARD_NO_FORWARDABLE_CONTENT": "У цьому повідомленні ще немає вмісту, який можна переслати",
    "FORWARD_DESTINATION_MISSING": "Відсутній пункт призначення пересилання",
    "FORWARD_MESSAGE_PREVIEW": "Переслане повідомлення",
    "MENU_PASTE": "Вставити",
    "MENU_COPY": "Копіювати",
    "MENU_REPLY": "Відповісти",
    "MENU_FORWARD": "Переслати",
    "MENU_REMOVE_INVITATION": "Видалити запрошення",
    "MENU_REMOVE_FROM_LIST": "Видалити зі списку",
    "MENU_GOODBYE_GUEST": "",
    "MENU_ADD_TO_LIST": "Додати до списку",
    "MENU_REJECT_INVITATION": "Відхилити запрошення",
    "MENU_FRONTEND_VERSION": "Версія фронтенду",
    "MENU_BANNER_HEADER": "Банер - {zone}",
    "MENU_BANNER_INFO": "Інформація про банер: {title}",
    "MENU_MESSAGE_BUBBLE": "Бульбашка повідомлення",
    "MENU_CHAT_CANVAS_HEADER": "Полотно чату - {zone}",
    "MENU_CANVAS_INFO": "Інформація про полотно",
    "MENU_CHAT_CANVAS_SUBLABEL": "Область розмови / поточна поверхня чату",
    "MENU_INPUT_AREA_HEADER": "Область введення - {zone}",
    "MENU_INPUT_AREA_INFO": "Інформація про область введення: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Нижня поверхня введення та інструментів дій",
    "MENU_HEADER": "Заголовок - {zone}",
    "MENU_HEADER_INFO": "Інформація заголовка: {title}",
    "MENU_HEADER_DESCRIPTION": "Верхня навігація та елементи керування сторінкою",
    "MENU_ZONE_HEADER": "Зона - {zone}",
    "MENU_ZONE_SPACE_INFO": "Інформація про простір зони",
    "MENU_EMPTY_LIST_SURFACE": "Порожня поверхня/список",
    "MENU_BLOCK": "Заблокувати",
    "MENU_UNBLOCK": "Розблокувати",
    "MENU_HIDE_IN_SEARCH": "Приховати в пошуку",
    "MENU_UNHIDE_IN_SEARCH": "Показати в пошуку",
    "MENU_VISIBLE_IN_SEARCH": "Видимий у пошуку",
    "MENU_HIDDEN_IN_SEARCH": "Прихований у пошуку",
    "MENU_VISIBLE_IN_USER_LIST": "Видимий у списку користувачів",
    "MENU_HIDDEN_IN_USER_LIST": "Прихований у списку користувачів",
    "MENU_NOT_BLOCKED": "Не заблоковано",
    "MENU_BLOCKED": "Заблоковано",
    "MENU_FRONTEND_VERSION_LOADING": "Завантаження...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Завантаження значення для кожного банера з backend. Жодна опція не позначається активною, доки не надійде відповідь бази даних.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Не вдалося завантажити значення backend. Надійна активна опція не показується.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Явне значення в базі даних для банера: {overrideVersion}. Глобальне значення за замовчуванням: {globalDefaultVersion}. Цільовий користувач має повністю оновити або повторно відкрити застосунок, щоб стартовий bootstrap застосував його.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Явне значення для банера не збережено. FeV2.0.0 активний за замовчуванням. Глобальне значення за замовчуванням: {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Явне значення бази даних для банера стає активним після повного перезавантаження цільового застосунку",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Явне значення для банера не збережено; це індивідуальний стан FeV2.0.0 за замовчуванням",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Ця опція також дорівнює поточному глобальному значенню за замовчуванням",
    "MENU_DELETE_PERMANENT_CONFIRM": "Назавжди видалити {target} з бази даних? Це видалить обліковий запис, історію чату, залежності та примусово створить повністю новий шлях запрошення для майбутнього повторного входу.",
    "MENU_DELETE_PERMANENTLY": "Видалити назавжди",
    "MENU_REFRESH_PAGE": "Оновити сторінку",
    "MENU_LOG_OFF": "Вийти",
    "MENU_HARD_RELOAD": "Жорстке перезавантаження",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Email (адміністратор)",
    "AUTH_PASSWORD_PLACEHOLDER": "Пароль",
    "AUTH_CONNECTING": "Підключення...",
    "AUTH_SIGNING_OUT": "Вихід...",
    "AUTH_BACK_TO_LOGIN": "Назад до входу",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Недійсна відповідь сервера: токен не знайдено.",
    "AUTH_LOGIN_FAILED": "Вхід не вдався",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Паролі не збігаються.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Паролі не збігаються!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Паролі мають збігатися точно.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Новий пароль",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Підтвердьте пароль",
    "AUTH_CHANGE_PASSWORD": "Змінити пароль",
    "AUTH_SAVING_PASSWORD": "Збереження...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Пароль успішно оновлено.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Наразі неможливо змінити пароль.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Ви маєте увійти, щоб змінити пароль.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Перемкнути видимість нового пароля",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Перемкнути видимість підтвердження пароля",
    "REGISTER_TITLE": "Завершити реєстрацію",
    "REGISTER_SUBTITLE": "Будь ласка, встановіть пароль вручну.",
    "REGISTER_CREATING_ACCOUNT": "Створення облікового запису...",
    "REGISTER_FINISH_SETUP": "Завершити налаштування",
    "REGISTER_FAILED_SET_PASSWORD": "Не вдалося встановити пароль",
    "INVITE_EMAIL_INSTRUCTION": "Введіть email запрошуваного (формат: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Запросити",
    "INVITE_EMAIL_REQUIRED": "Введіть email запрошуваного.",
    "INVITE_EMAIL_INVALID": "Недійсний формат email. Використовуйте: user@example.com",
    "PENDING_INVITATION_TITLE": "Запрошення очікує",
    "PENDING_INVITATION_REMOVE_QUESTION": "Видалити це очікуване запрошення з бази даних?",
    "PENDING_INVITATION_KEEP": "Зберегти запрошення",
    "PENDING_INVITATION_REMOVAL_FAILED": "Видалення не вдалося.",
    "REMOVE_FROM_LIST_TITLE": "Видалити зі списку",
    "REMOVE_FROM_LIST_WARNING": "Видалити цього користувача з обох списків зараз? Доступ до чату буде негайно припинено. Єдиний шлях повернення — нове запрошення.",
    "REMOVE_FROM_LIST_KEEP": "Залишити користувача в списку",
    "REMOVE_FROM_LIST_FAILED": "Не вдалося видалити зі списку.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Налаштування та живий статус",
    "PERMISSION_DIALOG_ARIA": "Налаштування та живий статус",
    "PERMISSION_TRIGGER_ARIA": "Тригер спливаючого вікна налаштувань",
    "PERMISSION_CLOSE_ARIA": "Закрити спливаюче вікно дозволів",
    "PERMISSION_LIVE_STATUS": "Живий статус",
    "PERMISSION_SYSTEM_PERMISSION": "Системний дозвіл",
    "PERMISSION_APP_PUSH": "Push застосунку",
    "PERMISSION_LOCATION_PERMISSION": "Дозвіл на місцезнаходження",
    "PERMISSION_APP_LOCATION": "Місцезнаходження застосунку",
    "PERMISSION_CONTROLS": "Керування дозволами",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push-сповіщення",
    "PERMISSION_LOCATION_ACCESS": "Доступ до місцезнаходження",
    "PERMISSION_IN_APP_SETTINGS": "Налаштування в застосунку",
    "PERMISSION_ALERT_SOUND": "Звук сповіщення",
    "PERMISSION_APP_BADGE": "Значок застосунку",
    "PERMISSION_PASSWORD_SETTINGS": "Налаштування пароля",
    "PERMISSION_NAVIGATION_STATUS": "Статус навігації",
    "PERMISSION_SELECTED_ZONE": "Вибрана зона",
    "PERMISSION_STAGED_CHAT_BANNER": "Підготовлений банер чату",
    "PERMISSION_CANVAS_CONTENT": "Вміст полотна",
    "PERMISSION_YOUR_DEVICES": "Ваші пристрої ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Оновити список пристроїв",
    "PERMISSION_REFRESH_LIST": "Оновити список",
    "PERMISSION_NO_REGISTERED_DEVICES": "Зареєстрованих пристроїв не знайдено.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Змінити розмір спливаючого вікна налаштувань",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Перемкнути push-сповіщення",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Перемкнути доступ до місцезнаходження",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Перемкнути звук сповіщення",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Перемкнути значок застосунку",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Перемкнути видимість профілю",
    "PERMISSION_OFF_IN_V1": "Вимкнено у v1",
    "PERMISSION_CHAT": "Чат",
    "PERMISSION_BANNER_LIST": "Список банерів",
    "PERMISSION_PUSH_DISABLED_V1": "Push-сповіщення вимкнені для релізу v1 Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Push-сповіщення увімкнені для цього пристрою.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Системні сповіщення заблоковані. Натисніть, щоб відкрити довідку з налаштувань.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "Увімкніть, щоб підвищити надійність доставки.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Щоб вимкнути системні сповіщення, відкрийте налаштування сповіщень браузера/сайту та встановіть для цього сайту Block.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Щоб змінити дозвіл системних сповіщень, відкрийте налаштування сповіщень браузера/сайту та встановіть для цього сайту Allow.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Доступ до місцезнаходження увімкнено для сортування LCAC за відстанню та позиціонування на карті.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API місцезнаходження не підтримується в цьому середовищі.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Доступ до місцезнаходження заблоковано. Натисніть, щоб відкрити довідку з налаштувань.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "Увімкніть, щоб дозволити точне сортування LCAC за відстанню та позиціонування на карті в застосунку.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Доступ до місцезнаходження не підтримується в цьому середовищі.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Щоб вимкнути доступ до місцезнаходження, відкрийте налаштування місцезнаходження браузера/сайту та встановіть для цього сайту Block.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Щоб увімкнути доступ до місцезнаходження для сортування за відстанню та позиціонування на карті в застосунку, відкрийте налаштування місцезнаходження браузера/сайту та встановіть для цього сайту Allow.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Наразі неможливо завантажити зареєстровані пристрої.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Завантаження UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Завантаження Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Завантаження backend...",
    "RUNTIME_LOADING": "Завантаження...",
    "RUNTIME_LOADING_FROM_DATABASE": "Завантаження з бази даних...",
    "RUNTIME_BACKEND_CONNECTED": "Backend підключено",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Активний кешований fallback",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Активний fallback за замовчуванням",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Активні fallback-значення за замовчуванням",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Збереження через backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Збережено в backend-сервісі",
    "RUNTIME_SAVE_FAILED": "Збереження не вдалося",
    "RUNTIME_LOAD_FAILED": "Завантаження не вдалося",
    "RUNTIME_CONNECTED": "Підключено",
    "RUNTIME_LOGIN_REQUIRED": "Потрібен вхід",
    "RUNTIME_SAVED": "Збережено",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI готовий - runtime очікує",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Захищений backend-сервіс селектора відхилив або не зміг зберегти запитану опцію моделі.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Захищений backend-сервіс селектора відхилив або не зміг зберегти запитану зміну маршрутизації WF1.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Селектор тепер читає активну конфігурацію, маршрутизацію Qwen і дозволені опції із захищеного backend-сервісу.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend-сервіс селектора зараз недоступний, тому використовується останній кешований стан селектора.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Значення селектора за замовчуванням активні, оскільки не вдалося завантажити backend-стан або кешований стан.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Захищений backend-сервіс селектора оновив активну конфігурацію маршрутизації WF1 і оновив кеш домену runtime.",
    "FRONTEND_VERSION_TITLE": "Версія фронтенду",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Цей селектор керує активною версією фронтенду для всіх користувачів. FeV2.0.0 активна.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Цей селектор читає активну версію фронтенду з config_domain_registry. Runtime визначається як FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Backend-конфігурацію версії фронтенду не вдалося завантажити, тому закодоване значення FeV2.0.0 за замовчуванням залишається активним, доки стартовий bootstrap знову не зможе прочитати захищений сервіс.",
    "FRONTEND_VERSION_HELPER_SAVED": "Активну версію фронтенду збережено в config_domain_registry. Повне оновлення або наступне завантаження застосунку застосує runtime-значення.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Backend-сервіс керування версією фронтенду не зміг зберегти запитану глобальну версію.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Активна версія фронтенду.",
    "CHAT_DELETE_WINDOW_TITLE": "Вікно видалення чату",
    "CHAT_DELETE_HELPER": "Це значення керує вікном доступності функції Видалити для всіх у секундах. Backend-захист змінюється одразу після збереження. Видимість бульбашки змінюється після повного оновлення або наступного завантаження застосунку.",
    "CHAT_DELETE_HELPER_FALLBACK": "Backend-сервіс керування видаленням чату не вдалося завантажити, тому закодоване значення за замовчуванням залишається активним, доки стартовий bootstrap знову не зможе прочитати захищений сервіс.",
    "CHAT_DELETE_HELPER_SAVED": "Вікно доступності функції Видалити для всіх збережено в config_domain_registry. Backend-захист змінюється одразу. Видимість бульбашки змінюється після повного оновлення або наступного завантаження застосунку.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Backend-сервіс керування видаленням чату не зміг зберегти запитане значення вікна.",
    "CHAT_DELETE_WINDOW_LABEL": "Вікно Видалити для всіх",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} с",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Зберігайте значення в цілих секундах. Поточне production-значення: 86400 секунд = 1 день.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Секунди вікна",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Введіть ціле число, більше або рівне 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Зберегти вікно видалення",
    "GUEST_BANNER_CONTROL_TITLE": "",
    "GUEST_BANNER_CONTROL_LABEL": "",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "",
    "GUEST_BANNER_CONTROL_HELPER": "",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "",
    "GUEST_BANNER_PENDING_TTL_INVALID": "",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "",
    "GUEST_QR_LOADING": "",
    "GUEST_QR_READY": "",
    "GUEST_QR_ALT": "",
    "GUEST_QR_LOAD_FAILED": "",
    "GUEST_SESSION_ACTIVE": "",
    "GUEST_PUBLIC_TITLE": "",
    "GUEST_PUBLIC_CONNECTING": "",
    "GUEST_PUBLIC_CONNECTED": "",
    "GUEST_PUBLIC_UNAVAILABLE": "",
    "GUEST_PUBLIC_SEND_FAILED": "",
    "UI_TEXTS_RUNTIME_TITLE": "",
    "UI_TEXTS_RUNTIME_BACKEND": "",
    "UI_TEXTS_RUNTIME_CACHED": "",
    "UI_TEXTS_RUNTIME_DEFAULTS": "",
    "UI_TEXTS_RUNTIME_SAVED": "",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "",
    "PROFILE_VISIBILITY_TITLE": "Видимість профілю",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Ви маєте увійти, щоб керувати видимістю облікового запису.",
    "PROFILE_VISIBILITY_HELPER": "Цей перемикач оновлює лише стан видимості вашого облікового запису. Виявлення та поведінка списку банерів залишаються незмінними на цьому етапі.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Наразі не вдалося завантажити видимість профілю.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Наразі не вдалося оновити видимість профілю.",
    "PROFILE_VISIBILITY_SAVED": "Видимість вашого облікового запису тепер {visibility}. Прапорці виявлення залишаються незмінними на цьому етапі.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Публічний обліковий запис",
    "PROFILE_VISIBILITY_STORED": "Збережена видимість",
    "WF1_MODEL_CONTROL_TITLE": "Керування моделлю WF1",
    "WF1_ENABLE_TRANSLATION": "Увімкнути переклад / pivot",
    "WF1_TRANSLATION_ACTIVE": "ШІ-переклад активний.",
    "WF1_TRANSLATION_INACTIVE": "WF1 продовжує працювати, але вихідний текст копіюється, а pivot позначається як неактивний.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Активний runtime-слот",
    "WF1_ALLOW_SAME_LANGUAGE": "Дозволити ШІ для пар однакової мови",
    "WF1_SAME_LANGUAGE_ACTIVE": "Пари однакової мови використовують звичайну маршрутизацію WF1.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Пари однакової мови обходять ШІ та зберігають активну мову No Pivot.",
    "WF1_QWEN_ROUTING": "Маршрутизація пар Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Позначені нижче мови використовують Qwen-Max, коли пара є або тією самою позначеною мовою, або позначеною мовою з англійською, або двома позначеними неанглійськими мовами. Інакше вибрана основна модель залишається активною.",
    "WF1_OPENROUTER_TEST_SLOT": "Тестовий слот OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Тестовий слот OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Тільки тест якості",
    "WF1_OPENROUTER_HELPER": "Цей слот редагується лише для тимчасових тестів якості OpenRouter. Він не змінює операційний шлях маршрутизації пар Qwen, якщо сам цей слот не стане активною моделлю.",
    "WF1_LABEL": "Мітка",
    "WF1_PRODUCT": "Продукт",
    "WF1_MODEL": "Модель",
    "WF1_PROVIDER_OPENROUTER": "Постачальник: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Секрет: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Тестовий слот OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max через OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Прайсова ціна Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Прайсова ціна OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Прайсова ціна OpenRouter",
    "LANGUAGE_ENGLISH": "Англійська",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Китайська (спрощена)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Китайська (традиційна)",
    "LANGUAGE_JAPANESE": "Японська",
    "LANGUAGE_KOREAN": "Корейська",
    "LANGUAGE_PERSIAN": "Перська",
    "LANGUAGE_TURKISH_ISTANBUL": "Турецька (Стамбул)",
    "LANGUAGE_ARABIC": "Арабська",
    "LANGUAGE_FRENCH": "Французька",
    "LANGUAGE_GERMAN": "Німецька",
    "LANGUAGE_SPANISH": "Іспанська",
    "LANGUAGE_PORTUGUESE": "Португальська",
    "LANGUAGE_ITALIAN": "Італійська",
    "LANGUAGE_RUSSIAN": "Російська",
    "LANGUAGE_DUTCH": "Нідерландська",
    "LANGUAGE_VIETNAMESE": "В’єтнамська",
    "LANGUAGE_INDONESIAN": "Індонезійська",
    "LANGUAGE_THAI": "Тайська",
    "LANGUAGE_MALAY": "Малайська",
    "WF1_PRICING_CUSTOM": "Ціноутворення: модель користувацького слота - перевірте актуальні ціни OpenRouter",
    "WF1_SAVE_OPENROUTER_SLOT": "Зберегти слот OpenRouter",
    "WF1_PRICING_LINE": "Вхід {input} - Вихід {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Секрет: {secret}",
    "ZONE_VISIBILITY_TITLE": "Керування видимістю зон",
    "ZONE_ENABLE": "Увімкнути {zone}",
    "ZONE_ENABLED_NOTE": "{zone} може з’являтися для дозволених ролей після наступного завантаження застосунку.",
    "ZONE_DISABLED_NOTE": "{zone} вважається відсутньою для користувачів не S_Admin після наступного завантаження застосунку.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin обходить цей список ролей і завжди зберігає доступ.",
    "ZONE_ROLE_LOCKED": "Вибір ролей тимчасово заблоковано, поки ця зона вимкнена, і він повернеться точно у збереженому вигляді, коли зону знову ввімкнуть.",
    "ZONE_LCAC_CONTROL": "Керування LCAC",
    "ZONE_RCAC_CONTROL": "Керування RCAC",
    "ZONE_LCAC_DESCRIPTION": "Керує існуванням лівої зарезервованої зони та ролями, які можуть її бачити.",
    "ZONE_RCAC_DESCRIPTION": "Керує існуванням правої зарезервованої зони та ролями, які можуть її бачити.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap видимості зон тепер читає дані із захищеного backend-сервісу. Зміни застосуються під час наступного завантаження застосунку.",
    "ZONE_VISIBILITY_CACHED": "Backend-сервіс видимості зон зараз недоступний, тому активні кешовані або локальні значення за замовчуванням.",
    "ZONE_VISIBILITY_DEFAULTS": "Значення видимості зон за замовчуванням активні, оскільки не вдалося завантажити backend-стан або кешований стан.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap видимості зон збережено. Для застосування в runtime потрібне жорстке перезавантаження або наступне завантаження застосунку.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Захищений backend-сервіс не зміг зберегти запитану зміну видимості зони.",
    "ROLE_MEMBER": "Учасник",
    "ROLE_STAFF": "Персонал",
    "ROLE_ADMIN": "Адміністратор",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Увімкніть сповіщення, щоб отримувати нові повідомлення.",
    "MAIN_LOG_OUT": "Вийти",
    "NOTIFICATION_NEW_MESSAGE": "Нове повідомлення",
    "NOTIFICATION_UNREAD_MESSAGE": "У вас є непрочитане повідомлення.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Повний перегляд",
    "MEDIA_AUDIO_ATTACHMENT": "Аудіовкладення",
    "MEDIA_FILE_FALLBACK": "Файл",
    "MEDIA_DOWNLOAD_READY": "Вкладення готове до завантаження",
    "MEDIA_TYPE_UNSUPPORTED": "Тип не підтримується для повного перегляду",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Попереднє зображення",
    "MEDIA_NEXT_IMAGE_ARIA": "Наступне зображення",
    "MEDIA_OPEN_ORIGINAL": "Відкрити оригінал",
    "MEDIA_DOWNLOAD": "Завантажити",
    "MEDIA_CLOSE_ARIA": "Закрити",
    "MEDIA_PROFILE_PICTURE_ARIA": "Фото профілю {name}",
    "MEDIA_PROFILE_ALT": "Профіль {name}",
    "MEDIA_UPLOAD_FAILED": "Завантаження не вдалося",
    "MEDIA_BACKEND_TOKEN_ERROR": "Помилка backend-токена",
    "MEDIA_UPLOAD_URL_MISSING": "Критично: URL завантаження відсутній у відповіді backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Відсутній токен автентифікації для завантаження в чат",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Запит токена завантаження в чат не вдався",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Недійсна відповідь завантаження в чат",
    "MEDIA_GCS_UPLOAD_FAILED": "Завантаження GCS не вдалося",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Відсутня назва файлу або contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Відсутній file_path",
    "BLOCK_NOTICE_TITLE": "Повідомлення про постійне блокування",
    "BLOCK_NOTICE_MESSAGE": "Ваш обліковий запис тимчасово призупинено через порушення політики.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Якщо ви вважаєте, що це потребує подальшого розгляду, зверніться до",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "електронною поштою.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Невідомий користувач",
    "GENERAL_GUEST": "Гість",
    "ADVISOR_FOR_CLIENT": "Радник для {client_display_name}",
    "GUEST_FOR_CLIENT": "",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Токен і пароль обов’язкові",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Тіло запиту має бути JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Недійсний або прострочений токен запрошення",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Не вдалося встановити пароль: відсутня сесія або користувач",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Не вдалося встановити пароль під час входу",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Не вдалося згенерувати admin-токен",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Вхід не вдався: відсутня сесія або користувач",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Реєстрація успішна. Перевірте email для підтвердження.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Невідома помилка реєстрації",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Недійсна обробка токена",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Потрібен токен доступу",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Для попереднього перегляду hash токена потрібна email-підказка з URL перенаправлення",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Не вдалося визначити ідентичність для цього токена",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Тільки User Zero може отримати доступ до сервісу вибору LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Тільки User Zero може отримати доступ до сервісу керування видимістю зон.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Тільки User Zero може отримати доступ до сервісу керування версією фронтенду.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Тільки User Zero може перевіряти версію фронтенду іншого користувача.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Тільки User Zero може отримати доступ до сервісу керування видаленням чату.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Тільки User Zero може назавжди видалити обліковий запис користувача.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Недійсний payload запиту.",
    "API_ERROR_INTERNAL_SERVER": "Внутрішня помилка сервера",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Функція відсутня в backend (потрібне перезавантаження)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Для переходів delivered/read дозволено лише DB RPC.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Зачекайте перед надсиланням іншого повідомлення.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Повідомлення успішно надіслано.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Сервіс контактів недоступний.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Надсилання повідомлення не вдалося.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Ім’я обов’язкове.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Email недійсний.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Повідомлення обов’язкове.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload селектора обов’язковий.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload видимості зон обов’язковий.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload версії фронтенду обов’язковий.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload керування видаленням чату обов’язковий.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID автентифікованого користувача обов’язковий.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID автентифікованого глядача обов’язковий.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID автентифікованого актора обов’язковий.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id обов’язковий.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id обов’язковий.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Список owner_user_ids обов’язковий.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email обов’язковий.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by обов’язковий.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime пошуку вимкнено глобальною версією фронтенду.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Вам не дозволено скасувати це очікуване запрошення.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Це запрошення більше не можна скасувати, оскільки користувач уже зареєстрований.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Очікуване запрошення не знайдено.",
    "INVITE_REPLY_ALREADY_MEMBER": "Вітаємо, ваш друг ({invitee_email}) уже зареєстрований у цьому застосунку та є учасником цього робочого простору.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Для {invitee_email} є очікуване запрошення, але повторний email не вдалося запустити. Перевірте журнали пошти.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Запис запрошення створено для {invitee_email}, але доставку email не вдалося підтвердити. Спробуйте пізніше або перевірте журнали пошти.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Не вдалося створити запис запрошення. Спробуйте пізніше.",
    "INVITE_REPLY_SYSTEM_ERROR": "Системна помилка під час процесу запрошення: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Помилка конфігурації backend: відсутні облікові дані Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Помилка конфігурації backend: недійсний URL Supabase",
    "CHAT_ERROR_ACCESS_DENIED": "Доступ заборонено",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Вміст не може бути порожнім для текстових повідомлень",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Не вдалося визначити ID розмови",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Контекст автентифікації RPC відсутній",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC повернув недійсний payload повідомлення",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Вставка не вдалася, дані не повернуто",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations має бути списком",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Недійсний payload операції",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type не підтримується",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id обов’язковий",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Повідомлення не знайдено",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Видалення дозволено лише для власного повідомлення",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Видалити для всіх більше недоступно для цього повідомлення",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Видалити для всіх не вдалося",
    "API_ERROR_SERVER_CONFIGURATION": "Помилка конфігурації сервера",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Відсутній секретний заголовок webhook",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Неавторизоване джерело webhook",
    "API_ERROR_BACKEND_CONFIGURATION": "Помилка конфігурації backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Помилка атрибута модуля: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Помилка перед видаленням запрошення під час видалення очікуваного auth-користувача.",
    "CHAT_ERROR_DB": "Помилка DB: {error}",
}
