# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/ur.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "مرکزی",
    "APP_TITLE": "OTMEGA AI پلیٹ فارم",
    "APP_SUBTITLE": "AI مشیر",
    "CHAT_PLACEHOLDER": "اپنا پیغام لکھیں...",
    "CHAT_SEND_BUTTON": "بھیجیں",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 مشیر غلطی کر سکتا ہے، اس لیے معلومات دوبارہ چیک کریں۔",
    "STATUS_ONLINE": "آن لائن",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "مینو",
    "ICON_NEW_CHAT": "نئی چیٹ",
    "ICON_HISTORY": "تاریخ",
    "ICON_TEMPLATES": "ٹیمپلیٹس",
    "ICON_SETTINGS": "ترتیبات",
    "ICON_USER_PROFILE": "صارف پروفائل",
    "ICON_QUICK_ACTIONS": "فوری کارروائیاں",
    "ICON_PINNED": "پن شدہ",
    "ICON_GALLERY": "گیلری",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "ایپ انسٹال کریں",
    "PWA_ANDROID_MSG": "بہتر تجربے اور آف لائن رسائی کے لیے اس ایپ کو اپنے ڈیوائس پر انسٹال کریں۔",
    "PWA_IOS_MSG": "اس ایپ کو اپنے iPhone/iPad پر انسٹال کرنے کے لیے:\n1. نیچے Share بٹن پر ٹیپ کریں\n2. 'Add to Home Screen' منتخب کریں",
    "PWA_BTN_INSTALL": "انسٹال کریں",
    "PWA_BTN_LATER": "شاید بعد میں",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Advisor Network میں لاگ اِن کریں",
    "AUTH_HEADER_SIGNUP": "اپنا متحد اکاؤنٹ بنائیں",
    "AUTH_HEADER_LOGIN_NETWORK": "Advisor Network میں لاگ اِن کریں",
    "AUTH_HEADER_SIGNUP_UNIFIED": "اپنا متحد اکاؤنٹ بنائیں",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "لاگ اِن",
    "AUTH_BUTTON_SIGNUP": "اکاؤنٹ بنائیں",
    "AUTH_BUTTON_GOOGLE": "Google کے ساتھ جاری رکھیں",
    "AUTH_BUTTON_FORGOT_PASSWORD": "پاس ورڈ بھول گئے",
    "AUTH_BUTTON_SEND_RESET_LINK": "ری سیٹ لنک بھیجیں",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "اکاؤنٹ نہیں ہے؟ سائن اپ کریں",
    "AUTH_PROMPT_LOGIN": "پہلے سے اکاؤنٹ ہے؟ لاگ اِن کریں",
    "AUTH_HELPER_TEXT_SIGNUP": "آپ ایک متحد اکاؤنٹ بنا رہے ہیں جسے آپ اس پلیٹ فارم کے تمام مشیروں تک رسائی کے لیے استعمال کر سکتے ہیں۔",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "آپ ایک متحد اکاؤنٹ بنا رہے ہیں جسے آپ اس پلیٹ فارم کے تمام مشیروں تک رسائی کے لیے استعمال کر سکتے ہیں۔",
    "AUTH_HELPER_TEXT_LOGIN": "وہی اکاؤنٹ (ای میل/پاس ورڈ یا Google) استعمال کریں جو آپ نے اس نیٹ ورک کے دوسرے مشیروں کے لیے استعمال کیا تھا۔",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "وہی اکاؤنٹ (ای میل/پاس ورڈ یا Google) استعمال کریں جو آپ نے اس نیٹ ورک کے دوسرے مشیروں کے لیے استعمال کیا تھا۔",
    "AUTH_FORGOT_PASSWORD_LINK": "اپنا پاس ورڈ بھول گئے؟",
    "AUTH_FORGOT_PASSWORD_TITLE": "اپنا پاس ورڈ ری سیٹ کریں",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "اپنا ای میل پتہ درج کریں؛ ہم آپ کو پاس ورڈ ری سیٹ کرنے کا لنک بھیجیں گے۔",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "ای میل",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "آپ کو لاگ اِن کیا جا رہا ہے...",
    "AUTH_STATUS_LOADING_SIGNUP": "آپ کا اکاؤنٹ بنایا جا رہا ہے...",
    "AUTH_STATUS_LOADING_RESET": "ری سیٹ لنک بھیجا جا رہا ہے...",
    "AUTH_STATUS_SUCCESS_LOGIN": "لاگ اِن کامیاب! دوبارہ لوڈ ہو رہا ہے...",
    "AUTH_STATUS_SUCCESS_RESET": "ری سیٹ لنک کامیابی سے بھیج دیا گیا۔ براہ کرم اپنا ای میل چیک کریں۔",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "پاس ورڈ ری سیٹ لنک کامیابی سے بھیج دیا گیا۔ براہ کرم اپنا ای میل چیک کریں۔",

    "AUTH_ERROR_INVALID_CREDENTIALS": "ای میل یا پاس ورڈ درست نہیں ہے۔",
    "AUTH_ERROR_EMAIL_EXISTS": "اس ای میل کے ساتھ Advisor Network میں پہلے سے ایک اکاؤنٹ موجود ہے۔",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "اس ای میل کے ساتھ پہلے سے ایک اکاؤنٹ موجود ہے۔ براہ کرم لاگ اِن کریں۔ آپ اس وقت اس کے رکن ہیں:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "اس ای میل کے ساتھ Advisor Network میں پہلے سے ایک اکاؤنٹ موجود ہے۔ براہ کرم یہ ونڈو بند کریں اور اسی ای میل اور اپنے پچھلے پاس ورڈ کے ساتھ 'Login' سیکشن استعمال کریں۔",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "آپ اس وقت اس کے رکن ہیں:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "ای میل اور پاس ورڈ ضروری ہیں۔",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "اکاؤنٹ بن گیا لیکن رکنیت سیٹ اپ نہیں ہو سکی۔ براہ کرم سپورٹ سے رابطہ کریں۔",
    "AUTH_ERROR_DEFAULT": "ایک خرابی پیش آئی۔ براہ کرم دوبارہ کوشش کریں۔",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "",
    "AUTH_FORGOT_PASSWORD_ERROR": "ری سیٹ لنک بھیجنے میں ناکامی۔ براہ کرم دوبارہ کوشش کریں۔",
    "INVITE_REPLY_EMAIL_SENT": "Collabra دعوتی ای میل آپ کے دوست کو {invitee_email} پر بھیج دی گئی۔",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra دعوتی ای میل آپ کے دوست کو {invitee_email} پر دوبارہ بھیج دی گئی۔",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "پاس ورڈ دکھائیں",
    "AUTH_PASSWORD_TOGGLE_HIDE": "پاس ورڈ چھپائیں",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "ٹھیک ہے",
    "GENERAL_CANCEL": "منسوخ کریں",
    "GENERAL_CLOSE": "بند کریں",
    "GENERAL_SEND": "بھیجیں",
    "GENERAL_SEARCH": "تلاش کریں",
    "GENERAL_RESET": "ری سیٹ",
    "GENERAL_ENABLE": "فعال کریں",
    "GENERAL_LOADING": "لوڈ ہو رہا ہے...",
    "GENERAL_DELETE": "حذف کریں",
    "GENERAL_DELETING": "حذف کیا جا رہا ہے...",
    "GENERAL_SAVE_PASSWORD": "پاس ورڈ محفوظ کریں",
    "AUTH_REMEMBER_EMAIL_LABEL": "ای میل یاد رکھیں",
    "GENERAL_SAVING": "محفوظ کیا جا رہا ہے...",
    "GENERAL_SENDING": "بھیجا جا رہا ہے...",
    "GENERAL_REMOVING": "ہٹایا جا رہا ہے...",
    "GENERAL_CONFIRM_REMOVAL": "ہٹانے کی تصدیق کریں",
    "GENERAL_EMPTY": "خالی",
    "GENERAL_UNAVAILABLE": "دستیاب نہیں",
    "GENERAL_ENABLED": "فعال",
    "GENERAL_DISABLED": "غیر فعال",
    "GENERAL_GRANTED": "منظور شدہ",
    "GENERAL_DENIED": "مسترد",
    "GENERAL_DEFAULT": "ڈیفالٹ",
    "GENERAL_UNSUPPORTED": "غیر معاون",
    "GENERAL_PUBLIC": "عوامی",
    "GENERAL_PRIVATE": "نجی",
    "GENERAL_USERNAME": "صارف نام",
    "GENERAL_EMAIL": "ای میل",
    "GENERAL_YOU": "آپ",
    "GENERAL_USER": "صارف",
    "GENERAL_UNKNOWN": "نامعلوم",
    "GENERAL_VISITOR": "وزیٹر",
    "GENERAL_PROFILE": "پروفائل",
    "GENERAL_BANNER": "بینر",
    "GENERAL_UNKNOWN_BANNER": "نامعلوم بینر",
    "GENERAL_ADVISOR_BANNER": "مشیر بینر",
    "GENERAL_NOT_AVAILABLE": "N/A",
    "GENERAL_NOT_SELECTED": "منتخب نہیں",
    "GENERAL_NO_EMAIL_FOUND": "کوئی ای میل نہیں ملا",
    "GENERAL_USER_ZERO_ONLY": "صرف User Zero",
    "GENERAL_CONNECTION_STATE": "کنکشن کی حالت",
    "GENERAL_DISPLAY_ONLY": "صرف نمایش",
    "GENERAL_TEXTAREA": "متنی خانہ",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "مینو (LCAC)",
    "HEADER_CHAT_CCAC": "چیٹ (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "فوری کارروائیاں (RCAC)",
    "HEADER_CHANGE_STATUS": "اسٹیٹس تبدیل کریں",
    "HEADER_OT_COIN_BALANCE": "OT Coin بیلنس",
    "HEADER_ALT_USER": "صارف",
    "STATUS_BUSY": "مصروف",
    "STATUS_AWAY": "دور",
    "STATUS_OFFLINE": "آف لائن",
    "STATUS_INVISIBLE": "غیر مرئی",
    "NETWORK_CHECKING_CONNECTION": "کنکشن چیک کیا جا رہا ہے...",
    "NETWORK_ONLINE_LATENCY": "آن لائن (Latency: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "نیٹ ورک: اچھا (ping کے لیے ٹیپ کریں)",
    "CHAT_TARGET_ALT": "چیٹ ہدف",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "تلاش کریں...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "{name} کی پروفائل تصویر کھولیں",
    "CHAT_MESSAGE_INPUT_ARIA": "پیغام ان پٹ",
    "CHAT_TOGGLE_VIEW_ARIA": "ویو تبدیل کریں",
    "CHAT_ADD_USER_ARIA": "صارف شامل کریں",
    "CHAT_ATTACH_ARIA": "منسلک کریں",
    "CHAT_MIC_ARIA": "مائیکروفون",
    "CHAT_SEND_ARIA": "بھیجیں",
    "CHAT_SEARCH_ARIA": "تلاش کریں",
    "CHAT_OPEN_SEARCH_ARIA": "تلاش کھولیں",
    "CHAT_CLOSE_SEARCH_ARIA": "تلاش بند کریں",
    "CHAT_ATTACHMENT_ALT": "منسلکہ",
    "CHAT_PREVIEW_ALT": "پیش نظارہ",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "منسلکہ ہٹائیں",
    "CHAT_REPLYING_TO": "جواب دیا جا رہا ہے",
    "CHAT_CANCEL_REPLY_ARIA": "جواب منسوخ کریں",
    "CHAT_UPLOADING": "اپ لوڈ ہو رہا ہے...",
    "CHAT_LOADING_CHATS": "چیٹس لوڈ ہو رہی ہیں...",
    "CHAT_SEND_FAILED": "بھیجنے میں ناکامی",
    "CHAT_SEND_FAILED_RETRY": "بھیجنے میں ناکامی۔ براہ کرم دوبارہ کوشش کریں۔",
    "CHAT_RETRY": "دوبارہ کوشش",
    "CHAT_EDITED": "ترمیم شدہ",
    "CHAT_TYPING": "ٹائپنگ",
    "CHAT_LOADING": "لوڈ ہو رہا ہے",
    "CHAT_PENDING_INVITATION": "زیر التوا دعوت",
    "CHAT_PENDING_INVITATION_MIN": "{count} منٹ زیر التوا دعوت",
    "CHAT_PENDING_INVITATION_HR": "{count} گھنٹے زیر التوا دعوت",
    "CHAT_PENDING_INVITATION_DAY": "{count} دن زیر التوا دعوت",
    "CHAT_WAITING_FOR_YOU": "{label} - آپ کے انتظار میں",
    "CHAT_PENDING_ACCEPTANCE": "{label} - قبولیت زیر التوا",
    "CHAT_MICROPHONE_ACCESS_DENIED": "مائیکروفون تک رسائی مسترد ہو گئی۔",
    "CHAT_UPLOAD_FAILED": "اپ لوڈ ناکام: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "اپ لوڈ کے لیے انٹرنیٹ کنکشن ضروری ہے۔ آن لائن ہونے پر دوبارہ کوشش کریں۔",
    "CHAT_ERROR_AUTH": "تصدیق کی خرابی",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "filename یا content_type موجود نہیں",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "conversation_id یا target_id موجود نہیں",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "غیر avatar اپ لوڈ کے لیے conversation_id موجود نہیں",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "avatar file_path غلط ہے",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase service client دستیاب نہیں",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Avatar read ack صرف advisor chat context میں درست ہے",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Avatar flow message نہیں ملا یا read ack کے لیے اہل نہیں",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "avatar message کو read کے طور پر finalize کرنے میں ناکامی",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 منسلکہ",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} منسلکات",
    "CHAT_VOICE_NOTE": "وائس نوٹ",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "چیٹ دستیاب نہیں۔ اس صارف نے آپ کو بلاک کیا ہے۔",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "چیٹ دستیاب نہیں۔ آپ نے اس صارف کو بلاک کیا ہے۔",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "اکاؤنٹ تک رسائی پالیسی کے تحت بلاک ہے۔",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "چیٹ دستیاب نہیں۔ یہ اکاؤنٹ User Zero کے ذریعے final-blocked ہے۔",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "چیٹ دستیاب نہیں۔ Mutual block فعال ہے۔",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "block policy کی وجہ سے چیٹ دستیاب نہیں۔",
    "MESSAGE_PREVIEW_PHOTO": "تصویر",
    "MESSAGE_PREVIEW_VOICE": "وائس پیغام",
    "MESSAGE_PREVIEW_VIDEO": "ویڈیو",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "فائل",
    "MESSAGE_PREVIEW_MESSAGE": "پیغام",
    "MESSAGE_PREVIEW_SYSTEM": "سسٹم پیغام",
    "MESSAGE_PREVIEW_NEW": "نیا پیغام",
    "MESSAGE_UNKNOWN_FILE": "نامعلوم فائل",
    "MESSAGE_AUDIO_ATTACHMENT": "آڈیو منسلکہ",
    "MESSAGE_FILE_ATTACHMENT": "منسلکہ",
    "BANNER_INVITED_BY": "{label} کے ذریعے مدعو",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "تلاش کے نتائج",
    "SEARCH_QUERY_LABEL": "Query:",
    "SEARCH_LOADING_VISIBILITY": "تلاش کی visibility لوڈ ہو رہی ہے...",
    "SEARCH_NO_RESULTS": "موجودہ search scope میں کوئی نتیجہ نہیں ملا۔",
    "SHARE_WITH_COLLABRA": "Collabra کے ساتھ شیئر کریں",
    "SHARE_SEND_TO": "بھیجیں",
    "SHARE_SELECT_ONE_BANNER": "ایک بینر منتخب کریں",
    "SHARE_BANNER_LIST_ARIA": "بینر فہرست",
    "SHARE_NO_MATCHING_BANNER": "کوئی matching banner نہیں",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "تبصرہ شامل کریں...",
    "SHARE_RECENT_CHATS": "حالیہ چیٹس",
    "SHARE_LEFT_LIST": "بائیں فہرست",
    "SHARE_RIGHT_LIST": "دائیں فہرست",
    "SHARE_UNTITLED_BANNER": "بلا عنوان بینر",
    "SHARE_SHARED_CONTENT": "شیئر کیا گیا مواد",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "شیئر کیا گیا مواد نہیں کھولا جا سکا۔",
    "SHARE_OPEN_BANNER_FAILED": "منتخب بینر نہیں کھولا جا سکا۔",
    "SHARE_ONE_PHOTO_SELECTED": "1 تصویر منتخب",
    "SHARE_MANY_PHOTOS_SELECTED": "{count} تصاویر منتخب",
    "SHARE_ONE_FILE_SELECTED": "1 فائل منتخب",
    "SHARE_MANY_FILES_SELECTED": "{count} فائلیں منتخب",
    "FORWARD_MESSAGE_TITLE": "پیغام آگے بھیجیں",
    "FORWARD_SELECT_RECIPIENTS": "وصول کنندگان منتخب کریں",
    "FORWARD_NO_OTHER_BANNER": "کوئی دوسرا بینر دستیاب نہیں۔",
    "FORWARD_SEND_TO_COUNT": "{count} کو بھیجیں",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "کم از کم ایک بینر منتخب کریں۔",
    "FORWARD_FAILED_DEFAULT": "آگے بھیجنا ناکام۔ براہ کرم دوبارہ کوشش کریں۔",
    "FORWARD_PARTIAL_SENT": "{count} بھیجا گیا۔ {error}",
    "FORWARD_SOURCE_NOT_FOUND": "forwarding کے لیے source message نہیں ملا",
    "FORWARD_NO_FORWARDABLE_CONTENT": "اس پیغام میں ابھی کوئی forwardable content نہیں ہے",
    "FORWARD_DESTINATION_MISSING": "forward destination موجود نہیں",
    "FORWARD_MESSAGE_PREVIEW": "آگے بھیجا گیا پیغام",
    "MENU_PASTE": "پیسٹ کریں",
    "MENU_COPY": "کاپی کریں",
    "MENU_REPLY": "جواب دیں",
    "MENU_FORWARD": "آگے بھیجیں",
    "MENU_REMOVE_INVITATION": "دعوت ہٹائیں",
    "MENU_REMOVE_FROM_LIST": "فہرست سے ہٹائیں",
    "MENU_GOODBYE_GUEST": "",
    "MENU_ADD_TO_LIST": "فہرست میں شامل کریں",
    "MENU_REJECT_INVITATION": "دعوت مسترد کریں",
    "MENU_FRONTEND_VERSION": "Frontend Version",
    "MENU_BANNER_HEADER": "بینر - {zone}",
    "MENU_BANNER_INFO": "بینر معلومات: {title}",
    "MENU_MESSAGE_BUBBLE": "پیغام ببل",
    "MENU_CHAT_CANVAS_HEADER": "چیٹ کینوس - {zone}",
    "MENU_CANVAS_INFO": "کینوس معلومات",
    "MENU_CHAT_CANVAS_SUBLABEL": "گفتگو کا علاقہ / موجودہ چیٹ سطح",
    "MENU_INPUT_AREA_HEADER": "ان پٹ علاقہ - {zone}",
    "MENU_INPUT_AREA_INFO": "ان پٹ علاقہ معلومات: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "نیچے typing اور action tools کی سطح",
    "MENU_HEADER": "ہیڈر - {zone}",
    "MENU_HEADER_INFO": "ہیڈر معلومات: {title}",
    "MENU_HEADER_DESCRIPTION": "اوپر navigation اور page controls",
    "MENU_ZONE_HEADER": "زون - {zone}",
    "MENU_ZONE_SPACE_INFO": "زون اسپیس معلومات",
    "MENU_EMPTY_LIST_SURFACE": "خالی/فہرست سطح",
    "MENU_BLOCK": "بلاک کریں",
    "MENU_UNBLOCK": "ان بلاک کریں",
    "MENU_HIDE_IN_SEARCH": "تلاش میں چھپائیں",
    "MENU_UNHIDE_IN_SEARCH": "تلاش میں دکھائیں",
    "MENU_VISIBLE_IN_SEARCH": "تلاش میں ظاہر",
    "MENU_HIDDEN_IN_SEARCH": "تلاش میں پوشیدہ",
    "MENU_VISIBLE_IN_USER_LIST": "صارف فہرست میں ظاہر",
    "MENU_HIDDEN_IN_USER_LIST": "صارف فہرست میں پوشیدہ",
    "MENU_NOT_BLOCKED": "بلاک نہیں",
    "MENU_BLOCKED": "بلاک شدہ",
    "MENU_FRONTEND_VERSION_LOADING": "لوڈ ہو رہا ہے...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "backend سے per-banner value لوڈ ہو رہی ہے۔ database response آنے تک کوئی option active نشان زد نہیں کیا جاتا۔",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Backend value لوڈ نہیں ہو سکی۔ کوئی trusted active option نہیں دکھایا گیا۔",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "explicit per-banner database value {overrideVersion} ہے۔ global default {globalDefaultVersion} ہے۔ startup bootstrap کے اطلاق کے لیے target user کو app مکمل refresh یا دوبارہ open کرنا ہوگا۔",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "کوئی explicit per-banner database value محفوظ نہیں۔ FeV2.0.0 default طور پر active ہے۔ global default {globalDefaultVersion} ہے۔",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "target app مکمل reload ہونے کے بعد explicit per-banner database value active ہوتی ہے",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "کوئی explicit per-banner value محفوظ نہیں؛ یہ default individual FeV2.0.0 state ہے",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "یہ option موجودہ global default کے برابر بھی ہے",
    "MENU_DELETE_PERMANENT_CONFIRM": "کیا {target} کو database سے مستقل طور پر حذف کر دیں؟ یہ account، chat history، dependencies کو حذف کرتا ہے اور future re-entry کے لیے مکمل نئی invite path لازمی کرتا ہے۔",
    "MENU_DELETE_PERMANENTLY": "مستقل طور پر حذف کریں",
    "MENU_REFRESH_PAGE": "صفحہ refresh کریں",
    "MENU_LOG_OFF": "لاگ آف",
    "MENU_HARD_RELOAD": "Hard Reload",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "ای میل (Admin User)",
    "AUTH_PASSWORD_PLACEHOLDER": "پاس ورڈ",
    "AUTH_CONNECTING": "کنیکٹ ہو رہا ہے...",
    "AUTH_SIGNING_OUT": "سائن آؤٹ ہو رہا ہے...",
    "AUTH_BACK_TO_LOGIN": "لاگ اِن پر واپس",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "server response غلط ہے: کوئی token نہیں ملا۔",
    "AUTH_LOGIN_FAILED": "لاگ اِن ناکام",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "پاس ورڈز مماثل نہیں ہیں۔",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "پاس ورڈز مماثل نہیں ہیں!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "پاس ورڈز بالکل مماثل ہونے چاہئیں۔",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "نیا پاس ورڈ",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "پاس ورڈ کی تصدیق کریں",
    "AUTH_CHANGE_PASSWORD": "پاس ورڈ تبدیل کریں",
    "AUTH_SAVING_PASSWORD": "محفوظ کیا جا رہا ہے...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "پاس ورڈ کامیابی سے اپ ڈیٹ ہو گیا۔",
    "AUTH_CHANGE_PASSWORD_UNABLE": "اس وقت پاس ورڈ تبدیل نہیں کیا جا سکتا۔",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "پاس ورڈ تبدیل کرنے کے لیے آپ کا لاگ اِن ہونا ضروری ہے۔",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "نئے پاس ورڈ کی visibility toggle کریں",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "confirm password visibility toggle کریں",
    "REGISTER_TITLE": "رجسٹریشن مکمل کریں",
    "REGISTER_SUBTITLE": "براہ کرم اپنا پاس ورڈ دستی طور پر سیٹ کریں۔",
    "REGISTER_CREATING_ACCOUNT": "اکاؤنٹ بنایا جا رہا ہے...",
    "REGISTER_FINISH_SETUP": "سیٹ اپ مکمل کریں",
    "REGISTER_FAILED_SET_PASSWORD": "پاس ورڈ سیٹ کرنے میں ناکامی",
    "INVITE_EMAIL_INSTRUCTION": "براہ کرم invitee email درج کریں (Format: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "دعوت دیں",
    "INVITE_EMAIL_REQUIRED": "براہ کرم invitee email درج کریں۔",
    "INVITE_EMAIL_INVALID": "ای میل format غلط ہے۔ براہ کرم استعمال کریں: user@example.com",
    "PENDING_INVITATION_TITLE": "زیر التوا دعوت",
    "PENDING_INVITATION_REMOVE_QUESTION": "کیا اس زیر التوا دعوت کو database سے ہٹا دیں؟",
    "PENDING_INVITATION_KEEP": "دعوت برقرار رکھیں",
    "PENDING_INVITATION_REMOVAL_FAILED": "ہٹانا ناکام۔",
    "REMOVE_FROM_LIST_TITLE": "فہرست سے ہٹائیں",
    "REMOVE_FROM_LIST_WARNING": "کیا اس صارف کو ابھی دونوں فہرستوں سے ہٹا دیں؟ Chat access فوراً ختم ہو جائے گی۔ واپسی کا واحد راستہ نئی invite ہے۔",
    "REMOVE_FROM_LIST_KEEP": "صارف کو فہرست میں رکھیں",
    "REMOVE_FROM_LIST_FAILED": "فہرست سے ہٹانا ناکام۔",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "ترتیب اور Live Status",
    "PERMISSION_DIALOG_ARIA": "ترتیب اور Live Status",
    "PERMISSION_TRIGGER_ARIA": "settings popup trigger",
    "PERMISSION_CLOSE_ARIA": "permission popup بند کریں",
    "PERMISSION_LIVE_STATUS": "Live Status",
    "PERMISSION_SYSTEM_PERMISSION": "System Permission",
    "PERMISSION_APP_PUSH": "App Push",
    "PERMISSION_LOCATION_PERMISSION": "Location Permission",
    "PERMISSION_APP_LOCATION": "App Location",
    "PERMISSION_CONTROLS": "Permission Controls",
    "PERMISSION_PUSH_NOTIFICATIONS": "Push Notifications",
    "PERMISSION_LOCATION_ACCESS": "Location Access",
    "PERMISSION_IN_APP_SETTINGS": "In-App Settings",
    "PERMISSION_ALERT_SOUND": "Alert Sound",
    "PERMISSION_APP_BADGE": "App Badge",
    "PERMISSION_PASSWORD_SETTINGS": "Password Settings",
    "PERMISSION_NAVIGATION_STATUS": "Navigation Status",
    "PERMISSION_SELECTED_ZONE": "Selected Zone",
    "PERMISSION_STAGED_CHAT_BANNER": "Staged Chat Banner",
    "PERMISSION_CANVAS_CONTENT": "Canvas Content",
    "PERMISSION_YOUR_DEVICES": "آپ کے ڈیوائسز ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "ڈیوائس فہرست refresh کریں",
    "PERMISSION_REFRESH_LIST": "فہرست refresh کریں",
    "PERMISSION_NO_REGISTERED_DEVICES": "کوئی registered device نہیں ملا۔",
    "PERMISSION_RESIZE_POPUP_ARIA": "settings popup کا سائز تبدیل کریں",
    "PERMISSION_TOGGLE_PUSH_ARIA": "push notifications toggle کریں",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "location access toggle کریں",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "alert sound toggle کریں",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "app badge toggle کریں",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "profile visibility toggle کریں",
    "PERMISSION_OFF_IN_V1": "v1 میں بند",
    "PERMISSION_CHAT": "چیٹ",
    "PERMISSION_BANNER_LIST": "بینر فہرست",
    "PERMISSION_PUSH_DISABLED_V1": "v1 Google Play release کے لیے push notifications غیر فعال ہیں۔",
    "PERMISSION_PUSH_ON_TOOLTIP": "اس device کے لیے push notifications ON ہیں۔",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "System notifications بلاک ہیں۔ settings help کھولنے کے لیے ٹیپ کریں۔",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "delivery reliability بہتر کرنے کے لیے ON کریں۔",
    "PERMISSION_SYSTEM_DISABLE_HELP": "system notifications بند کرنے کے لیے اپنے browser/site notification settings کھولیں اور اس site کو Block پر set کریں۔",
    "PERMISSION_SYSTEM_ALLOW_HELP": "system notification permission تبدیل کرنے کے لیے اپنے browser/site notification settings کھولیں اور اس site کو Allow پر set کریں۔",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Location access distance-based LCAC sorting اور map positioning کے لیے ON ہے۔",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "Location API اس environment میں supported نہیں ہے۔",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Location access بلاک ہے۔ settings help کھولنے کے لیے ٹیپ کریں۔",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "precise distance-based LCAC sorting اور in-app map positioning کی اجازت کے لیے ON کریں۔",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Location access اس environment میں supported نہیں ہے۔",
    "PERMISSION_LOCATION_DISABLE_HELP": "location access بند کرنے کے لیے اپنے browser/site location settings کھولیں اور اس site کو Block پر set کریں۔",
    "PERMISSION_LOCATION_ALLOW_HELP": "distance sorting اور in-app map positioning کے لیے location access فعال کرنے کو اپنے browser/site location settings کھولیں اور اس site کو Allow پر set کریں۔",
    "PERMISSION_DEVICE_LOAD_FAILED": "registered devices اس وقت load نہیں ہو سکے۔",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "UI Bridge لوڈ ہو رہا ہے...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Local Bridge لوڈ ہو رہا ہے...",
    "RUNTIME_LOADING_BACKEND": "Backend لوڈ ہو رہا ہے...",
    "RUNTIME_LOADING": "لوڈ ہو رہا ہے...",
    "RUNTIME_LOADING_FROM_DATABASE": "Database سے لوڈ ہو رہا ہے...",
    "RUNTIME_BACKEND_CONNECTED": "Backend Connected",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Cached Fallback Active",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback Default Active",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Fallback Defaults Active",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Backend کے ذریعے محفوظ کیا جا رہا ہے...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Backend Service میں محفوظ",
    "RUNTIME_SAVE_FAILED": "محفوظ کرنا ناکام",
    "RUNTIME_LOAD_FAILED": "لوڈ ناکام",
    "RUNTIME_CONNECTED": "Connected",
    "RUNTIME_LOGIN_REQUIRED": "لاگ اِن ضروری ہے",
    "RUNTIME_SAVED": "محفوظ",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI Ready - Runtime Pending",
    "RUNTIME_BACKEND_REJECTED_MODEL": "protected backend selector service نے requested model option کو reject کیا یا محفوظ نہیں کر سکا۔",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "protected backend selector service نے requested WF1 routing change کو reject کیا یا محفوظ نہیں کر سکا۔",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selector اب protected backend service سے active config، Qwen routing، اور allowed options پڑھ رہا ہے۔",
    "RUNTIME_WF1_SELECTOR_CACHED": "Backend selector service اس وقت unavailable ہے، اس لیے آخری cached selector state استعمال ہو رہی ہے۔",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Selector default values active ہیں کیونکہ کوئی backend یا cached selector state load نہیں ہو سکی۔",
    "RUNTIME_WF1_SELECTOR_SAVED": "protected backend selector service نے active WF1 routing config update کیا اور runtime domain cache refresh کیا۔",
    "FRONTEND_VERSION_TITLE": "Frontend Version",
    "FRONTEND_VERSION_HELPER_ACTIVE": "یہ selector تمام users کے لیے active frontend version control کرتا ہے۔ FeV2.0.0 active ہے۔",
    "FRONTEND_VERSION_HELPER_RUNTIME": "یہ selector config_domain_registry سے active frontend version پڑھتا ہے۔ Runtime FeV2.0.0 پر resolve ہوتا ہے۔",
    "FRONTEND_VERSION_HELPER_FALLBACK": "backend frontend-version config load نہیں ہو سکی، اس لیے coded FeV2.0.0 default active رہے گا جب تک startup bootstrap protected service دوبارہ پڑھ سکے۔",
    "FRONTEND_VERSION_HELPER_SAVED": "active frontend version config_domain_registry میں محفوظ ہو گیا۔ full refresh یا next app load runtime value apply کرتا ہے۔",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "backend frontend-version control service requested global version محفوظ نہیں کر سکی۔",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Active frontend version۔",
    "CHAT_DELETE_WINDOW_TITLE": "Chat Delete Window",
    "CHAT_DELETE_HELPER": "یہ value Delete for everyone availability window کو seconds میں control کرتی ہے۔ save کے فوراً بعد Backend guard تبدیل ہوتا ہے۔ Bubble visibility full refresh یا next app load کے بعد تبدیل ہوتی ہے۔",
    "CHAT_DELETE_HELPER_FALLBACK": "backend chat delete control service load نہیں ہو سکی، اس لیے coded default active رہے گا جب تک startup bootstrap protected service دوبارہ پڑھ سکے۔",
    "CHAT_DELETE_HELPER_SAVED": "Delete for everyone availability window config_domain_registry میں محفوظ ہو گیا۔ Backend guard فوراً تبدیل ہوتا ہے۔ Bubble visibility full refresh یا next app load کے بعد تبدیل ہوتی ہے۔",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "backend chat delete control service requested window value محفوظ نہیں کر سکی۔",
    "CHAT_DELETE_WINDOW_LABEL": "Delete for everyone window",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} سیکنڈ",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "value کو whole seconds میں store کریں۔ current production value 86400 seconds = 1 day ہے۔",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Window Seconds",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "0 یا اس سے زیادہ کا مکمل عدد درج کریں۔",
    "CHAT_DELETE_SAVE_BUTTON": "Delete Window محفوظ کریں",
    "GUEST_BANNER_CONTROL_TITLE": "",
    "GUEST_BANNER_CONTROL_LABEL": "",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "",
    "GUEST_BANNER_CONTROL_HELPER": "",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "",
    "GUEST_BANNER_PENDING_TTL_INVALID": "",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "",
    "GUEST_QR_LOADING": "",
    "GUEST_QR_READY": "",
    "GUEST_QR_ALT": "",
    "GUEST_QR_LOAD_FAILED": "",
    "GUEST_SESSION_ACTIVE": "",
    "GUEST_PUBLIC_TITLE": "",
    "GUEST_PUBLIC_CONNECTING": "",
    "GUEST_PUBLIC_CONNECTED": "",
    "GUEST_PUBLIC_UNAVAILABLE": "",
    "GUEST_PUBLIC_SEND_FAILED": "",
    "UI_TEXTS_RUNTIME_TITLE": "",
    "UI_TEXTS_RUNTIME_BACKEND": "",
    "UI_TEXTS_RUNTIME_CACHED": "",
    "UI_TEXTS_RUNTIME_DEFAULTS": "",
    "UI_TEXTS_RUNTIME_SAVED": "",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "",
    "PROFILE_VISIBILITY_TITLE": "Profile Visibility",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "account visibility manage کرنے کے لیے آپ کا login ہونا ضروری ہے۔",
    "PROFILE_VISIBILITY_HELPER": "یہ switch صرف آپ کے account visibility state کو update کرتا ہے۔ Discoverability اور banner-list behavior اس phase میں unchanged رہتے ہیں۔",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Profile visibility اس وقت load نہیں ہو سکی۔",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Profile visibility اس وقت update نہیں ہو سکی۔",
    "PROFILE_VISIBILITY_SAVED": "آپ کے account کی visibility اب {visibility} ہے۔ Discoverability flags اس phase میں unchanged رہتے ہیں۔",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Public Account",
    "PROFILE_VISIBILITY_STORED": "Stored Visibility",
    "WF1_MODEL_CONTROL_TITLE": "WF1 Model Control",
    "WF1_ENABLE_TRANSLATION": "Translation / Pivot فعال کریں",
    "WF1_TRANSLATION_ACTIVE": "AI translation active ہے۔",
    "WF1_TRANSLATION_INACTIVE": "WF1 چلتا رہتا ہے مگر source text copied ہے اور pivot inactive کے طور پر mark ہے۔",
    "WF1_ACTIVE_RUNTIME_SLOT": "Active Runtime Slot",
    "WF1_ALLOW_SAME_LANGUAGE": "Same-Language Pairs کے لیے AI کی اجازت دیں",
    "WF1_SAME_LANGUAGE_ACTIVE": "Same-language pairs normal WF1 routing follow کرتے ہیں۔",
    "WF1_SAME_LANGUAGE_INACTIVE": "Same-language pairs AI کو bypass کرتے ہیں اور No Pivot language active store کرتے ہیں۔",
    "WF1_QWEN_ROUTING": "Qwen Pair Routing",
    "WF1_QWEN_ROUTING_HELPER": "نیچے checked languages Qwen-Max استعمال کرتی ہیں جب pair یا تو وہی checked language ہو، checked language with English ہو، یا دو checked non-English languages ہوں۔ ورنہ selected primary model active رہتا ہے۔",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter Test Slot",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter Test Slot - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "صرف Quality Test",
    "WF1_OPENROUTER_HELPER": "یہ slot صرف temporary OpenRouter quality tests کے لیے editable ہے۔ یہ operational Qwen pair-routing path تبدیل نہیں کرتا جب تک یہ slot خود active model نہ بن جائے۔",
    "WF1_LABEL": "لیبل",
    "WF1_PRODUCT": "پروڈکٹ",
    "WF1_MODEL": "ماڈل",
    "WF1_PROVIDER_OPENROUTER": "Provider: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter Test Slot · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "OpenRouter کے ذریعے Qwen-Max",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google list price",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI list price",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter list price",
    "LANGUAGE_ENGLISH": "انگریزی",
    "LANGUAGE_CHINESE_SIMPLIFIED": "چینی (Simplified)",
    "LANGUAGE_CHINESE_TRADITIONAL": "چینی (Traditional)",
    "LANGUAGE_JAPANESE": "جاپانی",
    "LANGUAGE_KOREAN": "کورین",
    "LANGUAGE_PERSIAN": "فارسی",
    "LANGUAGE_TURKISH_ISTANBUL": "ترکی (Istanbul)",
    "LANGUAGE_ARABIC": "عربی",
    "LANGUAGE_FRENCH": "فرانسیسی",
    "LANGUAGE_GERMAN": "جرمن",
    "LANGUAGE_SPANISH": "ہسپانوی",
    "LANGUAGE_PORTUGUESE": "پرتگالی",
    "LANGUAGE_ITALIAN": "اطالوی",
    "LANGUAGE_RUSSIAN": "روسی",
    "LANGUAGE_DUTCH": "ڈچ",
    "LANGUAGE_VIETNAMESE": "ویتنامی",
    "LANGUAGE_INDONESIAN": "انڈونیشیائی",
    "LANGUAGE_THAI": "تھائی",
    "LANGUAGE_MALAY": "مالائی",
    "WF1_PRICING_CUSTOM": "Pricing: custom slot model - current OpenRouter pricing چیک کریں",
    "WF1_SAVE_OPENROUTER_SLOT": "OpenRouter Slot محفوظ کریں",
    "WF1_PRICING_LINE": "Input {input} - Output {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "Zone Visibility Control",
    "ZONE_ENABLE": "{zone} فعال کریں",
    "ZONE_ENABLED_NOTE": "{zone} next app load کے بعد allowed roles کے لیے ظاہر ہو سکتا ہے۔",
    "ZONE_DISABLED_NOTE": "{zone} next app load کے بعد non-S_Admin users کے لیے absent سمجھا جاتا ہے۔",
    "ZONE_S_ADMIN_BYPASS": "S_Admin اس role list کو bypass کرتا ہے اور ہمیشہ access رکھتا ہے۔",
    "ZONE_ROLE_LOCKED": "Role selections عارضی طور پر locked ہیں جبکہ یہ zone disabled ہے اور zone دوبارہ enabled ہونے پر exactly saved state میں واپس آئیں گے۔",
    "ZONE_LCAC_CONTROL": "LCAC Control",
    "ZONE_RCAC_CONTROL": "RCAC Control",
    "ZONE_LCAC_DESCRIPTION": "left reserved zone کے existence اور اسے دیکھنے والے roles کو control کرتا ہے۔",
    "ZONE_RCAC_DESCRIPTION": "right reserved zone کے existence اور اسے دیکھنے والے roles کو control کرتا ہے۔",
    "ZONE_VISIBILITY_BACKEND": "Zone visibility bootstrap اب protected backend service سے read کر رہا ہے۔ Changes next app load پر apply ہوتے ہیں۔",
    "ZONE_VISIBILITY_CACHED": "Backend zone visibility service اس وقت unavailable ہے، اس لیے cached یا local defaults active ہیں۔",
    "ZONE_VISIBILITY_DEFAULTS": "Zone visibility defaults active ہیں کیونکہ کوئی backend یا cached state load نہیں ہو سکی۔",
    "ZONE_VISIBILITY_SAVED": "Zone visibility bootstrap saved ہو گیا۔ runtime application کے لیے Hard reload یا next app load ضروری ہے۔",
    "ZONE_VISIBILITY_SAVE_FAILED": "protected backend service requested zone visibility change محفوظ نہیں کر سکی۔",
    "ROLE_MEMBER": "Member",
    "ROLE_STAFF": "Staff",
    "ROLE_ADMIN": "Admin",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "نئے پیغامات وصول کرنے کے لیے notifications فعال کریں۔",
    "MAIN_LOG_OUT": "لاگ آؤٹ",
    "NOTIFICATION_NEW_MESSAGE": "نیا پیغام",
    "NOTIFICATION_UNREAD_MESSAGE": "آپ کے پاس ایک unread message ہے۔",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Full View",
    "MEDIA_AUDIO_ATTACHMENT": "آڈیو منسلکہ",
    "MEDIA_FILE_FALLBACK": "فائل",
    "MEDIA_DOWNLOAD_READY": "منسلکہ download کے لیے تیار ہے",
    "MEDIA_TYPE_UNSUPPORTED": "full view کے لیے type supported نہیں",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "پچھلی تصویر",
    "MEDIA_NEXT_IMAGE_ARIA": "اگلی تصویر",
    "MEDIA_OPEN_ORIGINAL": "Original کھولیں",
    "MEDIA_DOWNLOAD": "Download",
    "MEDIA_CLOSE_ARIA": "بند کریں",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name} کی پروفائل تصویر",
    "MEDIA_PROFILE_ALT": "{name} پروفائل",
    "MEDIA_UPLOAD_FAILED": "اپ لوڈ ناکام",
    "MEDIA_BACKEND_TOKEN_ERROR": "Backend Token Error",
    "MEDIA_UPLOAD_URL_MISSING": "Critical: backend response میں upload URL موجود نہیں۔",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "chat upload کے لیے auth token موجود نہیں",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "chat upload token request ناکام",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "chat upload response غلط ہے",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS Upload Failed",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "filename یا contentType موجود نہیں",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "file_path موجود نہیں",
    "BLOCK_NOTICE_TITLE": "Permanent Block Notice",
    "BLOCK_NOTICE_MESSAGE": "policy violation کی وجہ سے آپ کا account عارضی طور پر suspend کیا گیا ہے۔",
    "BLOCK_NOTICE_CONTACT_PREFIX": "اگر آپ سمجھتے ہیں کہ اس پر follow-up ضروری ہے تو براہ کرم رابطہ کریں",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "ای میل کے ذریعے۔",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "نامعلوم صارف",
    "GENERAL_GUEST": "Guest",
    "ADVISOR_FOR_CLIENT": "{client_display_name} کے لیے مشیر",
    "GUEST_FOR_CLIENT": "",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token اور password ضروری ہیں",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Request body JSON ہونی چاہیے",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Invitation token غلط یا expired ہے",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Password set ناکام: session یا user موجود نہیں",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "sign-in کے دوران password set ناکام",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Admin token generation ناکام",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Login ناکام: session یا user موجود نہیں",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Registration کامیاب۔ verification کے لیے براہ کرم email check کریں۔",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Signup failed unknown",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Invalid token processing",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Access token ضروری ہے",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Token hash preview کے لیے redirect URL سے email hint ضروری ہے",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "اس token کے لیے identity resolve نہیں ہو سکی",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "صرف User Zero WF1 LLM selector service تک access کر سکتا ہے۔",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "صرف User Zero zone visibility control service تک access کر سکتا ہے۔",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "صرف User Zero frontend version control service تک access کر سکتا ہے۔",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "صرف User Zero کسی دوسرے user کا frontend version inspect کر سکتا ہے۔",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "صرف User Zero chat delete control service تک access کر سکتا ہے۔",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "صرف User Zero user account کو permanently delete کر سکتا ہے۔",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Request payload غلط ہے۔",
    "API_ERROR_INTERNAL_SERVER": "Internal Server Error",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Backend میں function missing ہے (Reload Required)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "delivered/read transitions کے لیے صرف DB RPC allowed ہے۔",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "براہ کرم دوسرا پیغام بھیجنے سے پہلے انتظار کریں۔",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "پیغام کامیابی سے بھیج دیا گیا۔",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Contact service unavailable ہے۔",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Message sending failed۔",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Name ضروری ہے۔",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Email invalid ہے۔",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Message ضروری ہے۔",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Selector payload ضروری ہے۔",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Zone visibility payload ضروری ہے۔",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Frontend version payload ضروری ہے۔",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Chat delete control payload ضروری ہے۔",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "Authenticated user id ضروری ہے۔",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "Authenticated viewer user id ضروری ہے۔",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "Authenticated actor user id ضروری ہے۔",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id ضروری ہے۔",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id ضروری ہے۔",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids list ضروری ہے۔",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email ضروری ہے۔",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by ضروری ہے۔",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Search runtime global frontend version کے ذریعے disabled ہے۔",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "آپ کو یہ pending invitation cancel کرنے کی اجازت نہیں ہے۔",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "یہ invitation مزید cancel نہیں ہو سکتی کیونکہ user already registered ہے۔",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Pending invitation نہیں ملی۔",
    "INVITE_REPLY_ALREADY_MEMBER": "مبارک ہو، آپ کا دوست ({invitee_email}) پہلے ہی اس app میں registered ہے اور اس workspace کا member ہے۔",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "{invitee_email} کے لیے invitation pending ہے، مگر retry email trigger نہیں ہو سکی۔ براہ کرم mail logs چیک کریں۔",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "{invitee_email} کے لیے invitation record بنایا گیا، مگر email delivery confirm نہیں ہو سکی۔ براہ کرم بعد میں دوبارہ کوشش کریں یا mail logs چیک کریں۔",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "invitation record بنانے میں ناکامی۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
    "INVITE_REPLY_SYSTEM_ERROR": "Invitation process کے دوران System Error: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Backend Configuration Error: Supabase credentials missing ہیں",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Backend Configuration Error: Supabase URL invalid ہے",
    "CHAT_ERROR_ACCESS_DENIED": "Access Denied",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "text messages کے لیے content خالی نہیں ہو سکتا",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "conversation ID determine نہیں ہو سکی",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "RPC auth context missing ہے",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC نے invalid message payload واپس کیا",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Insert failed، کوئی data return نہیں ہوا",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations ایک list ہونی چاہیے",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Invalid operation payload",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "Unsupported operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id ضروری ہے",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Message نہیں ملا",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Delete صرف آپ کے اپنے message پر allowed ہے",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "اس message کے لیے Delete for everyone اب دستیاب نہیں",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Delete for everyone ناکام",
    "API_ERROR_SERVER_CONFIGURATION": "Server configuration error",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Missing webhook secret header",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Unauthorized webhook source",
    "API_ERROR_BACKEND_CONFIGURATION": "Backend configuration error",
    "API_ERROR_MODULE_ATTRIBUTE": "Module Attribute Error: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "waiting auth user کو remove کرتے ہوئے invitation deletion سے پہلے ناکامی۔",
    "CHAT_ERROR_DB": "DB Error: {error}",
}
