# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/vi.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "Chính",
    "APP_TITLE": "Nền tảng AI OTMEGA",
    "APP_SUBTITLE": "Cố vấn AI",
    "CHAT_PLACEHOLDER": "Nhập tin nhắn của bạn...",
    "CHAT_SEND_BUTTON": "Gửi",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 Cố vấn có thể mắc lỗi, vì vậy hãy kiểm tra lại.",
    "STATUS_ONLINE": "Trực tuyến",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "Menu",
    "ICON_NEW_CHAT": "Cuộc trò chuyện mới",
    "ICON_HISTORY": "Lịch sử",
    "ICON_TEMPLATES": "Mẫu",
    "ICON_SETTINGS": "Cài đặt",
    "ICON_USER_PROFILE": "Hồ sơ người dùng",
    "ICON_QUICK_ACTIONS": "Hành động nhanh",
    "ICON_PINNED": "Đã ghim",
    "ICON_GALLERY": "Thư viện",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "Cài đặt ứng dụng",
    "PWA_ANDROID_MSG": "Cài đặt ứng dụng này trên thiết bị của bạn để có trải nghiệm tốt hơn và truy cập ngoại tuyến.",
    "PWA_IOS_MSG": "Để cài đặt ứng dụng này trên iPhone/iPad của bạn:\n1. Chạm vào nút Chia sẻ bên dưới\n2. Chọn 'Thêm vào Màn hình chính'",
    "PWA_BTN_INSTALL": "Cài đặt",
    "PWA_BTN_LATER": "Để sau",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "Đăng nhập vào Mạng lưới Cố vấn",
    "AUTH_HEADER_SIGNUP": "Tạo tài khoản hợp nhất của bạn",
    "AUTH_HEADER_LOGIN_NETWORK": "Đăng nhập vào Mạng lưới Cố vấn",
    "AUTH_HEADER_SIGNUP_UNIFIED": "Tạo tài khoản hợp nhất của bạn",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "Đăng nhập",
    "AUTH_BUTTON_SIGNUP": "Tạo tài khoản",
    "AUTH_BUTTON_GOOGLE": "Tiếp tục với Google",
    "AUTH_BUTTON_FORGOT_PASSWORD": "Quên mật khẩu",
    "AUTH_BUTTON_SEND_RESET_LINK": "Gửi liên kết đặt lại",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "Chưa có tài khoản? Đăng ký",
    "AUTH_PROMPT_LOGIN": "Đã có tài khoản? Đăng nhập",
    "AUTH_HELPER_TEXT_SIGNUP": "Bạn đang tạo một tài khoản hợp nhất có thể dùng để truy cập tất cả cố vấn trong nền tảng này.",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "Bạn đang tạo một tài khoản hợp nhất có thể dùng để truy cập tất cả cố vấn trong nền tảng này.",
    "AUTH_HELPER_TEXT_LOGIN": "Sử dụng cùng tài khoản (email/mật khẩu hoặc Google) mà bạn đã dùng cho các cố vấn khác trong mạng lưới này.",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "Sử dụng cùng tài khoản (email/mật khẩu hoặc Google) mà bạn đã dùng cho các cố vấn khác trong mạng lưới này.",
    "AUTH_FORGOT_PASSWORD_LINK": "Quên mật khẩu?",
    "AUTH_FORGOT_PASSWORD_TITLE": "Đặt lại mật khẩu của bạn",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "Nhập địa chỉ email của bạn và chúng tôi sẽ gửi cho bạn liên kết để đặt lại mật khẩu.",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "Email",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "Đang đăng nhập...",
    "AUTH_STATUS_LOADING_SIGNUP": "Đang tạo tài khoản của bạn...",
    "AUTH_STATUS_LOADING_RESET": "Đang gửi liên kết đặt lại...",
    "AUTH_STATUS_SUCCESS_LOGIN": "Đăng nhập thành công! Đang tải lại...",
    "AUTH_STATUS_SUCCESS_RESET": "Đã gửi liên kết đặt lại thành công. Vui lòng kiểm tra email của bạn.",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "Đã gửi liên kết đặt lại mật khẩu thành công. Vui lòng kiểm tra email của bạn.",

    "AUTH_ERROR_INVALID_CREDENTIALS": "Email hoặc mật khẩu không hợp lệ.",
    "AUTH_ERROR_EMAIL_EXISTS": "Một tài khoản với email này đã tồn tại trong mạng lưới cố vấn.",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "Một tài khoản với email này đã tồn tại. Vui lòng đăng nhập. Bạn hiện là thành viên của:",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "Một tài khoản với email này đã tồn tại trong mạng lưới cố vấn. Vui lòng đóng cửa sổ này và sử dụng phần 'Đăng nhập' với cùng email và mật khẩu trước đây của bạn.",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "Bạn hiện là thành viên của:",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "Email và mật khẩu là bắt buộc.",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "Tài khoản đã được tạo nhưng không thiết lập được tư cách thành viên. Vui lòng liên hệ hỗ trợ.",
    "AUTH_ERROR_DEFAULT": "Đã xảy ra lỗi. Vui lòng thử lại.",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "Cần có tải trọng kiểm soát biểu ngữ khách.",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "Chỉ User Zero mới có thể cập nhật các điều khiển biểu ngữ khách.",
    "AUTH_FORGOT_PASSWORD_ERROR": "Không gửi được liên kết đặt lại. Vui lòng thử lại.",
    "INVITE_REPLY_EMAIL_SENT": "Email lời mời Collabra đã được gửi tới bạn của bạn tại {invitee_email}.",
    "INVITE_REPLY_EMAIL_RESENT": "Email lời mời Collabra đã được gửi lại tới bạn của bạn tại {invitee_email}.",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "Hiển thị mật khẩu",
    "AUTH_PASSWORD_TOGGLE_HIDE": "Ẩn mật khẩu",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "OK",
    "GENERAL_CANCEL": "Hủy",
    "GENERAL_CLOSE": "Đóng",
    "GENERAL_SEND": "Gửi",
    "GENERAL_SEARCH": "Tìm kiếm",
    "GENERAL_RESET": "Đặt lại",
    "GENERAL_ENABLE": "Bật",
    "GENERAL_LOADING": "Đang tải...",
    "GENERAL_DELETE": "Xóa",
    "GENERAL_DELETING": "Đang xóa...",
    "GENERAL_SAVE_PASSWORD": "Lưu mật khẩu",
    "AUTH_REMEMBER_EMAIL_LABEL": "Ghi nhớ email",
    "GENERAL_SAVING": "Đang lưu...",
    "GENERAL_SENDING": "Đang gửi...",
    "GENERAL_REMOVING": "Đang gỡ bỏ...",
    "GENERAL_CONFIRM_REMOVAL": "Xác nhận gỡ bỏ",
    "GENERAL_EMPTY": "Trống",
    "GENERAL_UNAVAILABLE": "Không khả dụng",
    "GENERAL_ENABLED": "Đã bật",
    "GENERAL_DISABLED": "Đã tắt",
    "GENERAL_GRANTED": "Đã cấp",
    "GENERAL_DENIED": "Bị từ chối",
    "GENERAL_DEFAULT": "Mặc định",
    "GENERAL_UNSUPPORTED": "Không được hỗ trợ",
    "GENERAL_PUBLIC": "Công khai",
    "GENERAL_PRIVATE": "Riêng tư",
    "GENERAL_USERNAME": "Tên người dùng",
    "GENERAL_EMAIL": "Email",
    "GENERAL_YOU": "Bạn",
    "GENERAL_USER": "Người dùng",
    "GENERAL_UNKNOWN": "Không xác định",
    "GENERAL_VISITOR": "Khách truy cập",
    "GENERAL_PROFILE": "Hồ sơ",
    "GENERAL_BANNER": "Banner",
    "GENERAL_UNKNOWN_BANNER": "Banner không xác định",
    "GENERAL_ADVISOR_BANNER": "Banner cố vấn",
    "GENERAL_NOT_AVAILABLE": "N/A",
    "GENERAL_NOT_SELECTED": "Chưa chọn",
    "GENERAL_NO_EMAIL_FOUND": "Không tìm thấy email",
    "GENERAL_USER_ZERO_ONLY": "Chỉ dành cho User Zero",
    "GENERAL_CONNECTION_STATE": "Trạng thái kết nối",
    "GENERAL_DISPLAY_ONLY": "Chỉ hiển thị",
    "GENERAL_TEXTAREA": "Vùng văn bản",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "Menu (LCAC)",
    "HEADER_CHAT_CCAC": "Trò chuyện (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "Hành động nhanh (RCAC)",
    "HEADER_CHANGE_STATUS": "Thay đổi trạng thái",
    "HEADER_OT_COIN_BALANCE": "Số dư OT Coin",
    "HEADER_ALT_USER": "Người dùng",
    "STATUS_BUSY": "Bận",
    "STATUS_AWAY": "Vắng mặt",
    "STATUS_OFFLINE": "Ngoại tuyến",
    "STATUS_INVISIBLE": "Ẩn mặt",
    "NETWORK_CHECKING_CONNECTION": "Đang kiểm tra kết nối...",
    "NETWORK_ONLINE_LATENCY": "Trực tuyến (Độ trễ: {latency}ms)",
    "NETWORK_GOOD_TAP_TO_PING": "Mạng: Tốt (chạm để ping)",
    "CHAT_TARGET_ALT": "Đích trò chuyện",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "Tìm kiếm...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "Mở ảnh hồ sơ của {name}",
    "CHAT_MESSAGE_INPUT_ARIA": "Ô nhập tin nhắn",
    "CHAT_TOGGLE_VIEW_ARIA": "Chuyển đổi chế độ xem",
    "CHAT_ADD_USER_ARIA": "Thêm người dùng",
    "CHAT_ATTACH_ARIA": "Đính kèm",
    "CHAT_MIC_ARIA": "Micro",
    "CHAT_SEND_ARIA": "Gửi",
    "CHAT_SEARCH_ARIA": "Tìm kiếm",
    "CHAT_OPEN_SEARCH_ARIA": "Mở tìm kiếm",
    "CHAT_CLOSE_SEARCH_ARIA": "Đóng tìm kiếm",
    "CHAT_ATTACHMENT_ALT": "Tệp đính kèm",
    "CHAT_PREVIEW_ALT": "Xem trước",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "Gỡ tệp đính kèm",
    "CHAT_REPLYING_TO": "Đang trả lời",
    "CHAT_CANCEL_REPLY_ARIA": "Hủy trả lời",
    "CHAT_UPLOADING": "Đang tải lên...",
    "CHAT_LOADING_CHATS": "Đang tải cuộc trò chuyện...",
    "CHAT_SEND_FAILED": "Gửi thất bại",
    "CHAT_SEND_FAILED_RETRY": "Gửi thất bại. Vui lòng thử lại.",
    "CHAT_RETRY": "Thử lại",
    "CHAT_EDITED": "đã chỉnh sửa",
    "CHAT_TYPING": "Đang nhập",
    "CHAT_LOADING": "Đang tải",
    "CHAT_PENDING_INVITATION": "Lời mời đang chờ",
    "CHAT_PENDING_INVITATION_MIN": "{count} phút Lời mời đang chờ",
    "CHAT_PENDING_INVITATION_HR": "{count} giờ Lời mời đang chờ",
    "CHAT_PENDING_INVITATION_DAY": "{count} ngày Lời mời đang chờ",
    "CHAT_WAITING_FOR_YOU": "{label} - Đang chờ bạn",
    "CHAT_PENDING_ACCEPTANCE": "{label} - Đang chờ chấp nhận",
    "CHAT_MICROPHONE_ACCESS_DENIED": "Quyền truy cập micro bị từ chối.",
    "CHAT_UPLOAD_FAILED": "Tải lên thất bại: {error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "Việc tải lên yêu cầu kết nối Internet. Vui lòng thử lại khi bạn trực tuyến.",
    "CHAT_ERROR_AUTH": "Lỗi xác thực",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Thiếu tên tệp hoặc content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "Thiếu conversation_id hoặc target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "Thiếu conversation_id cho tải lên không phải avatar",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "file_path avatar không hợp lệ",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Client dịch vụ Supabase không khả dụng",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "Xác nhận đã đọc avatar chỉ hợp lệ trong ngữ cảnh trò chuyện cố vấn",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "Không tìm thấy tin nhắn luồng avatar hoặc không đủ điều kiện xác nhận đã đọc",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "Không thể hoàn tất đánh dấu tin nhắn avatar là đã đọc",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 tệp đính kèm",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} tệp đính kèm",
    "CHAT_VOICE_NOTE": "Ghi chú thoại",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "Trò chuyện không khả dụng. Người dùng này đã chặn bạn.",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "Trò chuyện không khả dụng. Bạn đã chặn người dùng này.",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "Quyền truy cập tài khoản bị chặn theo chính sách.",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "Trò chuyện không khả dụng. Tài khoản này bị User Zero chặn vĩnh viễn.",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "Trò chuyện không khả dụng. Chặn lẫn nhau đang hoạt động.",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "Trò chuyện không khả dụng do chính sách chặn.",
    "MESSAGE_PREVIEW_PHOTO": "Ảnh",
    "MESSAGE_PREVIEW_VOICE": "Tin nhắn thoại",
    "MESSAGE_PREVIEW_VIDEO": "Video",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "Tệp",
    "MESSAGE_PREVIEW_MESSAGE": "Tin nhắn",
    "MESSAGE_PREVIEW_SYSTEM": "Tin nhắn hệ thống",
    "MESSAGE_PREVIEW_NEW": "Tin nhắn mới",
    "MESSAGE_UNKNOWN_FILE": "Tệp không xác định",
    "MESSAGE_AUDIO_ATTACHMENT": "Tệp âm thanh đính kèm",
    "MESSAGE_FILE_ATTACHMENT": "Tệp đính kèm",
    "BANNER_INVITED_BY": "được mời bởi {label}",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "Kết quả tìm kiếm",
    "SEARCH_QUERY_LABEL": "Truy vấn:",
    "SEARCH_LOADING_VISIBILITY": "Đang tải khả năng hiển thị tìm kiếm...",
    "SEARCH_NO_RESULTS": "Không tìm thấy kết quả trong phạm vi tìm kiếm hiện tại.",
    "SHARE_WITH_COLLABRA": "Chia sẻ với Collabra",
    "SHARE_SEND_TO": "Gửi tới",
    "SHARE_SELECT_ONE_BANNER": "Chọn một banner",
    "SHARE_BANNER_LIST_ARIA": "Danh sách banner",
    "SHARE_NO_MATCHING_BANNER": "Không có banner phù hợp",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "Thêm bình luận...",
    "SHARE_RECENT_CHATS": "Cuộc trò chuyện gần đây",
    "SHARE_LEFT_LIST": "Danh sách bên trái",
    "SHARE_RIGHT_LIST": "Danh sách bên phải",
    "SHARE_UNTITLED_BANNER": "Banner chưa có tiêu đề",
    "SHARE_SHARED_CONTENT": "Nội dung đã chia sẻ",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "Không thể mở nội dung đã chia sẻ.",
    "SHARE_OPEN_BANNER_FAILED": "Không thể mở banner đã chọn.",
    "SHARE_ONE_PHOTO_SELECTED": "Đã chọn 1 ảnh",
    "SHARE_MANY_PHOTOS_SELECTED": "Đã chọn {count} ảnh",
    "SHARE_ONE_FILE_SELECTED": "Đã chọn 1 tệp",
    "SHARE_MANY_FILES_SELECTED": "Đã chọn {count} tệp",
    "FORWARD_MESSAGE_TITLE": "Chuyển tiếp tin nhắn",
    "FORWARD_SELECT_RECIPIENTS": "Chọn người nhận",
    "FORWARD_NO_OTHER_BANNER": "Không có banner khác khả dụng.",
    "FORWARD_SEND_TO_COUNT": "Gửi tới {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "Chọn ít nhất một banner.",
    "FORWARD_FAILED_DEFAULT": "Chuyển tiếp thất bại. Vui lòng thử lại.",
    "FORWARD_PARTIAL_SENT": "Đã gửi {count}. {error}",
    "FORWARD_SOURCE_NOT_FOUND": "Không tìm thấy tin nhắn nguồn để chuyển tiếp",
    "FORWARD_NO_FORWARDABLE_CONTENT": "Tin nhắn này chưa có nội dung có thể chuyển tiếp",
    "FORWARD_DESTINATION_MISSING": "Thiếu đích chuyển tiếp",
    "FORWARD_MESSAGE_PREVIEW": "Tin nhắn đã chuyển tiếp",
    "MENU_PASTE": "Dán",
    "MENU_COPY": "Sao chép",
    "MENU_REPLY": "Trả lời",
    "MENU_FORWARD": "Chuyển tiếp",
    "MENU_REMOVE_INVITATION": "Xóa lời mời",
    "MENU_REMOVE_FROM_LIST": "Gỡ khỏi danh sách",
    "MENU_GOODBYE_GUEST": "Tạm biệt khách",
    "MENU_ADD_TO_LIST": "Thêm vào danh sách",
    "MENU_REJECT_INVITATION": "Từ chối lời mời",
    "MENU_FRONTEND_VERSION": "Phiên bản frontend",
    "MENU_BANNER_HEADER": "Banner - {zone}",
    "MENU_BANNER_INFO": "Thông tin banner: {title}",
    "MENU_MESSAGE_BUBBLE": "Bong bóng tin nhắn",
    "MENU_CHAT_CANVAS_HEADER": "Canvas trò chuyện - {zone}",
    "MENU_CANVAS_INFO": "Thông tin canvas",
    "MENU_CHAT_CANVAS_SUBLABEL": "Khu vực hội thoại / bề mặt trò chuyện hiện tại",
    "MENU_INPUT_AREA_HEADER": "Khu vực nhập - {zone}",
    "MENU_INPUT_AREA_INFO": "Thông tin khu vực nhập: {title}",
    "MENU_INPUT_AREA_DESCRIPTION": "Bề mặt nhập liệu và công cụ hành động phía dưới",
    "MENU_HEADER": "Tiêu đề - {zone}",
    "MENU_HEADER_INFO": "Thông tin tiêu đề: {title}",
    "MENU_HEADER_DESCRIPTION": "Điều hướng phía trên và điều khiển trang",
    "MENU_ZONE_HEADER": "Vùng - {zone}",
    "MENU_ZONE_SPACE_INFO": "Thông tin không gian vùng",
    "MENU_EMPTY_LIST_SURFACE": "Bề mặt trống/danh sách",
    "MENU_BLOCK": "Chặn",
    "MENU_UNBLOCK": "Bỏ chặn",
    "MENU_HIDE_IN_SEARCH": "Ẩn trong tìm kiếm",
    "MENU_UNHIDE_IN_SEARCH": "Hiện trong tìm kiếm",
    "MENU_VISIBLE_IN_SEARCH": "Hiển thị trong tìm kiếm",
    "MENU_HIDDEN_IN_SEARCH": "Ẩn trong tìm kiếm",
    "MENU_VISIBLE_IN_USER_LIST": "Hiển thị trong danh sách người dùng",
    "MENU_HIDDEN_IN_USER_LIST": "Ẩn trong danh sách người dùng",
    "MENU_NOT_BLOCKED": "Không bị chặn",
    "MENU_BLOCKED": "Đã bị chặn",
    "MENU_FRONTEND_VERSION_LOADING": "Đang tải...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "Đang tải giá trị theo từng banner từ backend. Không có tùy chọn nào được đánh dấu là hoạt động cho đến khi phản hồi cơ sở dữ liệu đến.",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "Không thể tải giá trị backend. Không hiển thị tùy chọn đang hoạt động đáng tin cậy nào.",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "Giá trị cơ sở dữ liệu theo từng banner rõ ràng là {overrideVersion}. Giá trị mặc định toàn cục là {globalDefaultVersion}. Người dùng mục tiêu phải làm mới hoàn toàn hoặc mở lại ứng dụng để bootstrap khởi động áp dụng giá trị này.",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "Không có giá trị cơ sở dữ liệu theo từng banner rõ ràng nào được lưu. FeV2.0.0 đang hoạt động theo mặc định. Giá trị mặc định toàn cục là {globalDefaultVersion}.",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "Giá trị cơ sở dữ liệu theo từng banner rõ ràng sẽ hoạt động sau khi ứng dụng mục tiêu tải lại hoàn toàn",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "Không có giá trị theo từng banner rõ ràng nào được lưu; đây là trạng thái FeV2.0.0 cá nhân mặc định",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "Tùy chọn này cũng bằng giá trị mặc định toàn cục hiện tại",
    "MENU_DELETE_PERMANENT_CONFIRM": "Xóa vĩnh viễn {target} khỏi cơ sở dữ liệu? Việc này xóa tài khoản, lịch sử trò chuyện, các phụ thuộc và buộc phải đi theo lộ trình mời mới hoàn toàn cho lần tham gia lại trong tương lai.",
    "MENU_DELETE_PERMANENTLY": "Xóa vĩnh viễn",
    "MENU_REFRESH_PAGE": "Làm mới trang",
    "MENU_LOG_OFF": "Đăng xuất",
    "MENU_HARD_RELOAD": "Tải lại cưỡng bức",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "Email (Người dùng quản trị)",
    "AUTH_PASSWORD_PLACEHOLDER": "Mật khẩu",
    "AUTH_CONNECTING": "Đang kết nối...",
    "AUTH_SIGNING_OUT": "Đang đăng xuất...",
    "AUTH_BACK_TO_LOGIN": "Quay lại đăng nhập",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "Phản hồi máy chủ không hợp lệ: Không tìm thấy token.",
    "AUTH_LOGIN_FAILED": "Đăng nhập thất bại",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "Mật khẩu không khớp.",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "Mật khẩu không khớp!",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "Mật khẩu phải khớp chính xác.",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "Mật khẩu mới",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "Xác nhận mật khẩu",
    "AUTH_CHANGE_PASSWORD": "Đổi mật khẩu",
    "AUTH_SAVING_PASSWORD": "Đang lưu...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "Mật khẩu đã được cập nhật thành công.",
    "AUTH_CHANGE_PASSWORD_UNABLE": "Hiện không thể đổi mật khẩu.",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "Bạn phải đăng nhập để đổi mật khẩu.",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "Chuyển đổi hiển thị mật khẩu mới",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "Chuyển đổi hiển thị xác nhận mật khẩu",
    "REGISTER_TITLE": "Hoàn tất đăng ký",
    "REGISTER_SUBTITLE": "Vui lòng đặt mật khẩu của bạn thủ công.",
    "REGISTER_CREATING_ACCOUNT": "Đang tạo tài khoản...",
    "REGISTER_FINISH_SETUP": "Hoàn tất thiết lập",
    "REGISTER_FAILED_SET_PASSWORD": "Không đặt được mật khẩu",
    "INVITE_EMAIL_INSTRUCTION": "Vui lòng nhập email người được mời (Định dạng: user@example.com)",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "Mời",
    "INVITE_EMAIL_REQUIRED": "Vui lòng nhập email người được mời.",
    "INVITE_EMAIL_INVALID": "Định dạng email không hợp lệ. Vui lòng sử dụng: user@example.com",
    "PENDING_INVITATION_TITLE": "Lời mời đang chờ",
    "PENDING_INVITATION_REMOVE_QUESTION": "Xóa lời mời đang chờ này khỏi cơ sở dữ liệu?",
    "PENDING_INVITATION_KEEP": "Giữ lời mời",
    "PENDING_INVITATION_REMOVAL_FAILED": "Gỡ bỏ thất bại.",
    "REMOVE_FROM_LIST_TITLE": "Gỡ khỏi danh sách",
    "REMOVE_FROM_LIST_WARNING": "Gỡ người dùng này khỏi cả hai danh sách ngay bây giờ? Quyền truy cập trò chuyện sẽ bị cắt ngay lập tức. Cách duy nhất để quay lại là lời mời mới.",
    "REMOVE_FROM_LIST_KEEP": "Giữ người dùng trong danh sách",
    "REMOVE_FROM_LIST_FAILED": "Gỡ khỏi danh sách thất bại.",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "Cài đặt & trạng thái trực tiếp",
    "PERMISSION_DIALOG_ARIA": "Cài đặt và trạng thái trực tiếp",
    "PERMISSION_TRIGGER_ARIA": "Trình kích hoạt popup cài đặt",
    "PERMISSION_CLOSE_ARIA": "Đóng popup quyền",
    "PERMISSION_LIVE_STATUS": "Trạng thái trực tiếp",
    "PERMISSION_SYSTEM_PERMISSION": "Quyền hệ thống",
    "PERMISSION_APP_PUSH": "Push ứng dụng",
    "PERMISSION_LOCATION_PERMISSION": "Quyền vị trí",
    "PERMISSION_APP_LOCATION": "Vị trí ứng dụng",
    "PERMISSION_CONTROLS": "Điều khiển quyền",
    "PERMISSION_PUSH_NOTIFICATIONS": "Thông báo push",
    "PERMISSION_LOCATION_ACCESS": "Truy cập vị trí",
    "PERMISSION_IN_APP_SETTINGS": "Cài đặt trong ứng dụng",
    "PERMISSION_ALERT_SOUND": "Âm thanh cảnh báo",
    "PERMISSION_APP_BADGE": "Huy hiệu ứng dụng",
    "PERMISSION_PASSWORD_SETTINGS": "Cài đặt mật khẩu",
    "PERMISSION_NAVIGATION_STATUS": "Trạng thái điều hướng",
    "PERMISSION_SELECTED_ZONE": "Vùng đã chọn",
    "PERMISSION_STAGED_CHAT_BANNER": "Banner trò chuyện đã chuẩn bị",
    "PERMISSION_CANVAS_CONTENT": "Nội dung canvas",
    "PERMISSION_YOUR_DEVICES": "Thiết bị của bạn ({count})",
    "PERMISSION_REFRESH_DEVICE_LIST": "Làm mới danh sách thiết bị",
    "PERMISSION_REFRESH_LIST": "Làm mới danh sách",
    "PERMISSION_NO_REGISTERED_DEVICES": "Không tìm thấy thiết bị đã đăng ký.",
    "PERMISSION_RESIZE_POPUP_ARIA": "Thay đổi kích thước popup cài đặt",
    "PERMISSION_TOGGLE_PUSH_ARIA": "Chuyển đổi thông báo push",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "Chuyển đổi quyền truy cập vị trí",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "Chuyển đổi âm thanh cảnh báo",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "Chuyển đổi huy hiệu ứng dụng",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "Chuyển đổi khả năng hiển thị hồ sơ",
    "PERMISSION_OFF_IN_V1": "Tắt trong v1",
    "PERMISSION_CHAT": "Trò chuyện",
    "PERMISSION_BANNER_LIST": "Danh sách banner",
    "PERMISSION_PUSH_DISABLED_V1": "Thông báo push bị tắt cho bản phát hành v1 Google Play.",
    "PERMISSION_PUSH_ON_TOOLTIP": "Thông báo push đang BẬT cho thiết bị này.",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "Thông báo hệ thống bị chặn. Chạm để mở trợ giúp cài đặt.",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "BẬT để cải thiện độ tin cậy khi gửi.",
    "PERMISSION_SYSTEM_DISABLE_HELP": "Để tắt thông báo hệ thống, hãy mở cài đặt thông báo của trình duyệt/trang web và đặt trang này thành Chặn.",
    "PERMISSION_SYSTEM_ALLOW_HELP": "Để thay đổi quyền thông báo hệ thống, hãy mở cài đặt thông báo của trình duyệt/trang web và đặt trang này thành Cho phép.",
    "PERMISSION_LOCATION_ON_TOOLTIP": "Quyền truy cập vị trí đang BẬT cho sắp xếp LCAC dựa trên khoảng cách và định vị bản đồ.",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "API vị trí không được hỗ trợ trong môi trường này.",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "Quyền truy cập vị trí bị chặn. Chạm để mở trợ giúp cài đặt.",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "BẬT để cho phép sắp xếp LCAC chính xác theo khoảng cách và định vị bản đồ trong ứng dụng.",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "Quyền truy cập vị trí không được hỗ trợ trong môi trường này.",
    "PERMISSION_LOCATION_DISABLE_HELP": "Để tắt quyền truy cập vị trí, hãy mở cài đặt vị trí của trình duyệt/trang web và đặt trang này thành Chặn.",
    "PERMISSION_LOCATION_ALLOW_HELP": "Để bật quyền truy cập vị trí cho sắp xếp theo khoảng cách và định vị bản đồ trong ứng dụng, hãy mở cài đặt vị trí của trình duyệt/trang web và đặt trang này thành Cho phép.",
    "PERMISSION_DEVICE_LOAD_FAILED": "Hiện không thể tải các thiết bị đã đăng ký.",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "Đang tải UI Bridge...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "Đang tải Local Bridge...",
    "RUNTIME_LOADING_BACKEND": "Đang tải backend...",
    "RUNTIME_LOADING": "Đang tải...",
    "RUNTIME_LOADING_FROM_DATABASE": "Đang tải từ cơ sở dữ liệu...",
    "RUNTIME_BACKEND_CONNECTED": "Backend đã kết nối",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "Fallback được lưu cache đang hoạt động",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "Fallback mặc định đang hoạt động",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "Các giá trị fallback mặc định đang hoạt động",
    "RUNTIME_SAVING_THROUGH_BACKEND": "Đang lưu qua backend...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "Đã lưu trong dịch vụ backend",
    "RUNTIME_SAVE_FAILED": "Lưu thất bại",
    "RUNTIME_LOAD_FAILED": "Tải thất bại",
    "RUNTIME_CONNECTED": "Đã kết nối",
    "RUNTIME_LOGIN_REQUIRED": "Yêu cầu đăng nhập",
    "RUNTIME_SAVED": "Đã lưu",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI sẵn sàng - Runtime đang chờ",
    "RUNTIME_BACKEND_REJECTED_MODEL": "Dịch vụ selector backend được bảo vệ đã từ chối hoặc không thể lưu tùy chọn model được yêu cầu.",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "Dịch vụ selector backend được bảo vệ đã từ chối hoặc không thể lưu thay đổi định tuyến WF1 được yêu cầu.",
    "RUNTIME_WF1_SELECTOR_BACKEND": "Selector hiện đang đọc cấu hình hoạt động, định tuyến Qwen và các tùy chọn được phép từ dịch vụ backend được bảo vệ.",
    "RUNTIME_WF1_SELECTOR_CACHED": "Dịch vụ selector backend hiện không khả dụng, nên trạng thái selector được lưu cache gần nhất đang được sử dụng.",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "Giá trị mặc định của selector đang hoạt động vì không tải được trạng thái backend hoặc cache nào.",
    "RUNTIME_WF1_SELECTOR_SAVED": "Dịch vụ selector backend được bảo vệ đã cập nhật cấu hình định tuyến WF1 đang hoạt động và làm mới cache miền runtime.",
    "FRONTEND_VERSION_TITLE": "Phiên bản frontend",
    "FRONTEND_VERSION_HELPER_ACTIVE": "Selector này kiểm soát phiên bản frontend đang hoạt động cho tất cả người dùng. FeV2.0.0 đang hoạt động.",
    "FRONTEND_VERSION_HELPER_RUNTIME": "Selector này đọc phiên bản frontend đang hoạt động từ config_domain_registry. Runtime phân giải thành FeV2.0.0.",
    "FRONTEND_VERSION_HELPER_FALLBACK": "Không thể tải cấu hình phiên bản frontend của backend, nên mặc định mã hóa FeV2.0.0 vẫn hoạt động cho đến khi bootstrap khởi động có thể đọc lại dịch vụ được bảo vệ.",
    "FRONTEND_VERSION_HELPER_SAVED": "Phiên bản frontend đang hoạt động đã được lưu trong config_domain_registry. Làm mới hoàn toàn hoặc lần tải ứng dụng tiếp theo sẽ áp dụng giá trị runtime.",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "Dịch vụ điều khiển phiên bản frontend của backend không thể lưu phiên bản toàn cục được yêu cầu.",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "Phiên bản frontend đang hoạt động.",
    "CHAT_DELETE_WINDOW_TITLE": "Cửa sổ xóa trò chuyện",
    "CHAT_DELETE_HELPER": "Giá trị này kiểm soát khoảng thời gian khả dụng của Xóa cho mọi người tính bằng giây. Cơ chế bảo vệ backend thay đổi ngay sau khi lưu. Khả năng hiển thị bong bóng thay đổi sau khi làm mới hoàn toàn hoặc lần tải ứng dụng tiếp theo.",
    "CHAT_DELETE_HELPER_FALLBACK": "Không thể tải dịch vụ điều khiển xóa trò chuyện của backend, nên mặc định mã hóa vẫn hoạt động cho đến khi bootstrap khởi động có thể đọc lại dịch vụ được bảo vệ.",
    "CHAT_DELETE_HELPER_SAVED": "Khoảng thời gian khả dụng của Xóa cho mọi người đã được lưu trong config_domain_registry. Cơ chế bảo vệ backend thay đổi ngay lập tức. Khả năng hiển thị bong bóng thay đổi sau khi làm mới hoàn toàn hoặc lần tải ứng dụng tiếp theo.",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "Dịch vụ điều khiển xóa trò chuyện của backend không thể lưu giá trị cửa sổ được yêu cầu.",
    "CHAT_DELETE_WINDOW_LABEL": "Cửa sổ Xóa cho mọi người",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} giây",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "Lưu giá trị bằng số giây nguyên. Giá trị sản xuất hiện tại là 86400 giây = 1 ngày.",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "Số giây của cửa sổ",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "Nhập một số nguyên lớn hơn hoặc bằng 0.",
    "CHAT_DELETE_SAVE_BUTTON": "Lưu cửa sổ xóa",
    "GUEST_BANNER_CONTROL_TITLE": "Biểu ngữ khách",
    "GUEST_BANNER_CONTROL_LABEL": "Trò chuyện bằng mã QR của khách",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "Hiển thị biểu ngữ Khách cho tất cả người dùng",
    "GUEST_BANNER_CONTROL_HELPER": "Kiểm soát biểu ngữ Khách cố định và thời gian tồn tại của mã thông báo QR đang chờ xử lý.",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "Phương án dự phòng cục bộ đang hoạt động cho các điều khiển biểu ngữ Khách.",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "Đã lưu các điều khiển biểu ngữ Khách.",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "Không thể lưu các điều khiển biểu ngữ Khách.",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "Đã thu hồi {count} phiên của khách.",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "TTL của mã QR đang chờ xử lý (phút)",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "TTL hiện tại của mã QR đang chờ xử lý: {count} phút.",
    "GUEST_BANNER_PENDING_TTL_INVALID": "Nhập một số nguyên dương cho số phút.",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "Lưu biểu ngữ của khách",
    "GUEST_QR_LOADING": "Đang chuẩn bị mã QR của khách...",
    "GUEST_QR_READY": "Quét để mở cuộc trò chuyện Khách tạm thời.",
    "GUEST_QR_ALT": "Mã QR cuộc trò chuyện Khách",
    "GUEST_QR_LOAD_FAILED": "Không thể chuẩn bị mã QR Khách.",
    "GUEST_SESSION_ACTIVE": "Khách đã kết nối.",
    "GUEST_PUBLIC_TITLE": "Trò chuyện Khách",
    "GUEST_PUBLIC_CONNECTING": "Đang kết nối...",
    "GUEST_PUBLIC_CONNECTED": "Đã kết nối",
    "GUEST_PUBLIC_UNAVAILABLE": "Liên kết Khách này không khả dụng.",
    "GUEST_PUBLIC_SEND_FAILED": "Không thể gửi tin nhắn.",
    "UI_TEXTS_RUNTIME_TITLE": "Thời gian chạy ngôn ngữ giao diện người dùng",
    "UI_TEXTS_RUNTIME_BACKEND": "Thời gian chạy ngôn ngữ giao diện người dùng đang đọc từ dịch vụ backend được bảo vệ. Các thay đổi sẽ được áp dụng vào lần tải ứng dụng đầy đủ tiếp theo.",
    "UI_TEXTS_RUNTIME_CACHED": "Dịch vụ thời gian chạy ngôn ngữ giao diện người dùng backend hiện không khả dụng, vì vậy các giá trị mặc định được lưu trong bộ nhớ đệm hoặc cục bộ đang hoạt động.",
    "UI_TEXTS_RUNTIME_DEFAULTS": "Các mặc định thời gian chạy của ngôn ngữ giao diện người dùng đang hoạt động vì không thể tải trạng thái backend hoặc trạng thái đã lưu vào bộ nhớ đệm.",
    "UI_TEXTS_RUNTIME_SAVED": "Kiểm soát thời gian chạy ngôn ngữ giao diện người dùng đã được lưu. Người dùng cần làm mới hoàn toàn hoặc tải ứng dụng vào lần sau để nhận được cổng ngôn ngữ mới.",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "Dịch vụ backend được bảo vệ không thể lưu thay đổi thời gian chạy ngôn ngữ giao diện người dùng được yêu cầu.",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "Áp dụng ngôn ngữ thiết bị",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "Bật ngôn ngữ giao diện người dùng thời gian chạy",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "Người dùng có thể nhận các gói văn bản giao diện người dùng cho ngôn ngữ đã lưu hoặc ngôn ngữ của thiết bị.",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "Tất cả người dùng buộc phải sử dụng văn bản giao diện người dùng tiếng Anh và ngôn ngữ của thiết bị sẽ bị bỏ qua.",
    "PROFILE_VISIBILITY_TITLE": "Khả năng hiển thị hồ sơ",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "Bạn phải đăng nhập để quản lý khả năng hiển thị tài khoản.",
    "PROFILE_VISIBILITY_HELPER": "Công tắc này chỉ cập nhật trạng thái hiển thị tài khoản của bạn. Khả năng khám phá và hành vi danh sách banner vẫn không đổi trong giai đoạn này.",
    "PROFILE_VISIBILITY_LOAD_FAILED": "Hiện không thể tải khả năng hiển thị hồ sơ.",
    "PROFILE_VISIBILITY_SAVE_FAILED": "Hiện không thể cập nhật khả năng hiển thị hồ sơ.",
    "PROFILE_VISIBILITY_SAVED": "Khả năng hiển thị tài khoản của bạn hiện là {visibility}. Các cờ khả năng khám phá vẫn không đổi trong giai đoạn này.",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "Tài khoản công khai",
    "PROFILE_VISIBILITY_STORED": "Khả năng hiển thị đã lưu",
    "WF1_MODEL_CONTROL_TITLE": "Điều khiển model WF1",
    "WF1_ENABLE_TRANSLATION": "Bật dịch / pivot",
    "WF1_TRANSLATION_ACTIVE": "Dịch bằng AI đang hoạt động.",
    "WF1_TRANSLATION_INACTIVE": "WF1 vẫn chạy nhưng văn bản nguồn được sao chép và pivot được đánh dấu là không hoạt động.",
    "WF1_ACTIVE_RUNTIME_SLOT": "Slot runtime đang hoạt động",
    "WF1_ALLOW_SAME_LANGUAGE": "Cho phép AI cho các cặp cùng ngôn ngữ",
    "WF1_SAME_LANGUAGE_ACTIVE": "Các cặp cùng ngôn ngữ đi theo định tuyến WF1 bình thường.",
    "WF1_SAME_LANGUAGE_INACTIVE": "Các cặp cùng ngôn ngữ bỏ qua AI và lưu trạng thái không có ngôn ngữ pivot đang hoạt động.",
    "WF1_QWEN_ROUTING": "Định tuyến cặp Qwen",
    "WF1_QWEN_ROUTING_HELPER": "Các ngôn ngữ được chọn bên dưới sử dụng Qwen-Max khi cặp là cùng ngôn ngữ được chọn, một ngôn ngữ được chọn với tiếng Anh, hoặc hai ngôn ngữ không phải tiếng Anh được chọn. Nếu không, model chính đã chọn vẫn hoạt động.",
    "WF1_OPENROUTER_TEST_SLOT": "Slot thử nghiệm OpenRouter",
    "WF1_OPENROUTER_DEFAULT_LABEL": "Slot thử nghiệm OpenRouter - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "Chỉ kiểm thử chất lượng",
    "WF1_OPENROUTER_HELPER": "Slot này chỉ có thể chỉnh sửa cho các kiểm thử chất lượng OpenRouter tạm thời. Nó không thay đổi đường dẫn định tuyến cặp Qwen vận hành trừ khi chính slot này trở thành model đang hoạt động.",
    "WF1_LABEL": "Nhãn",
    "WF1_PRODUCT": "Sản phẩm",
    "WF1_MODEL": "Model",
    "WF1_PROVIDER_OPENROUTER": "Nhà cung cấp: OpenRouter",
    "WF1_SECRET_OPENROUTER": "Secret: OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "Slot thử nghiệm OpenRouter · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "Qwen-Max qua OpenRouter",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Giá niêm yết của Google",
    "WF1_PRICING_OPENAI_LIST_PRICE": "Giá niêm yết của OpenAI",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "Giá niêm yết của OpenRouter",
    "LANGUAGE_ENGLISH": "Tiếng Anh",
    "LANGUAGE_CHINESE_SIMPLIFIED": "Tiếng Trung (Giản thể)",
    "LANGUAGE_CHINESE_TRADITIONAL": "Tiếng Trung (Phồn thể)",
    "LANGUAGE_JAPANESE": "Tiếng Nhật",
    "LANGUAGE_KOREAN": "Tiếng Hàn",
    "LANGUAGE_PERSIAN": "Tiếng Ba Tư",
    "LANGUAGE_TURKISH_ISTANBUL": "Tiếng Thổ Nhĩ Kỳ (Istanbul)",
    "LANGUAGE_ARABIC": "Tiếng Ả Rập",
    "LANGUAGE_FRENCH": "Tiếng Pháp",
    "LANGUAGE_GERMAN": "Tiếng Đức",
    "LANGUAGE_SPANISH": "Tiếng Tây Ban Nha",
    "LANGUAGE_PORTUGUESE": "Tiếng Bồ Đào Nha",
    "LANGUAGE_ITALIAN": "Tiếng Ý",
    "LANGUAGE_RUSSIAN": "Tiếng Nga",
    "LANGUAGE_DUTCH": "Tiếng Hà Lan",
    "LANGUAGE_VIETNAMESE": "Tiếng Việt",
    "LANGUAGE_INDONESIAN": "Tiếng Indonesia",
    "LANGUAGE_THAI": "Tiếng Thái",
    "LANGUAGE_MALAY": "Tiếng Mã Lai",
    "WF1_PRICING_CUSTOM": "Định giá: model slot tùy chỉnh - kiểm tra giá OpenRouter hiện tại",
    "WF1_SAVE_OPENROUTER_SLOT": "Lưu slot OpenRouter",
    "WF1_PRICING_LINE": "Đầu vào {input} - Đầu ra {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "Secret: {secret}",
    "ZONE_VISIBILITY_TITLE": "Điều khiển hiển thị vùng",
    "ZONE_ENABLE": "Bật {zone}",
    "ZONE_ENABLED_NOTE": "{zone} có thể xuất hiện cho các vai trò được phép sau lần tải ứng dụng tiếp theo.",
    "ZONE_DISABLED_NOTE": "{zone} được coi là không tồn tại đối với người dùng không phải S_Admin sau lần tải ứng dụng tiếp theo.",
    "ZONE_S_ADMIN_BYPASS": "S_Admin bỏ qua danh sách vai trò này và luôn giữ quyền truy cập.",
    "ZONE_ROLE_LOCKED": "Các lựa chọn vai trò tạm thời bị khóa khi vùng này bị tắt và sẽ trở lại đúng như đã lưu khi vùng được bật lại.",
    "ZONE_LCAC_CONTROL": "Điều khiển LCAC",
    "ZONE_RCAC_CONTROL": "Điều khiển RCAC",
    "ZONE_LCAC_DESCRIPTION": "Kiểm soát sự tồn tại của vùng dành riêng bên trái và các vai trò có thể thấy vùng đó.",
    "ZONE_RCAC_DESCRIPTION": "Kiểm soát sự tồn tại của vùng dành riêng bên phải và các vai trò có thể thấy vùng đó.",
    "ZONE_VISIBILITY_BACKEND": "Bootstrap hiển thị vùng hiện đang đọc từ dịch vụ backend được bảo vệ. Các thay đổi áp dụng ở lần tải ứng dụng tiếp theo.",
    "ZONE_VISIBILITY_CACHED": "Dịch vụ hiển thị vùng backend hiện không khả dụng, nên các giá trị cache hoặc mặc định cục bộ đang hoạt động.",
    "ZONE_VISIBILITY_DEFAULTS": "Các giá trị mặc định hiển thị vùng đang hoạt động vì không tải được trạng thái backend hoặc cache nào.",
    "ZONE_VISIBILITY_SAVED": "Bootstrap hiển thị vùng đã được lưu. Cần tải lại cưỡng bức hoặc lần tải ứng dụng tiếp theo để áp dụng runtime.",
    "ZONE_VISIBILITY_SAVE_FAILED": "Dịch vụ backend được bảo vệ không thể lưu thay đổi hiển thị vùng được yêu cầu.",
    "ROLE_MEMBER": "Thành viên",
    "ROLE_STAFF": "Nhân viên",
    "ROLE_ADMIN": "Quản trị viên",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "Bật thông báo để nhận tin nhắn mới.",
    "MAIN_LOG_OUT": "Đăng xuất",
    "NOTIFICATION_NEW_MESSAGE": "Tin nhắn mới",
    "NOTIFICATION_UNREAD_MESSAGE": "Bạn có một tin nhắn chưa đọc.",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "Chế độ xem đầy đủ",
    "MEDIA_AUDIO_ATTACHMENT": "Tệp âm thanh đính kèm",
    "MEDIA_FILE_FALLBACK": "Tệp",
    "MEDIA_DOWNLOAD_READY": "Tệp đính kèm đã sẵn sàng để tải xuống",
    "MEDIA_TYPE_UNSUPPORTED": "Loại không được hỗ trợ cho chế độ xem đầy đủ",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "Ảnh trước",
    "MEDIA_NEXT_IMAGE_ARIA": "Ảnh tiếp theo",
    "MEDIA_OPEN_ORIGINAL": "Mở bản gốc",
    "MEDIA_DOWNLOAD": "Tải xuống",
    "MEDIA_CLOSE_ARIA": "Đóng",
    "MEDIA_PROFILE_PICTURE_ARIA": "Ảnh hồ sơ của {name}",
    "MEDIA_PROFILE_ALT": "Hồ sơ của {name}",
    "MEDIA_UPLOAD_FAILED": "Tải lên thất bại",
    "MEDIA_BACKEND_TOKEN_ERROR": "Lỗi token backend",
    "MEDIA_UPLOAD_URL_MISSING": "Nghiêm trọng: URL tải lên bị thiếu trong phản hồi backend.",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "Thiếu token xác thực cho tải lên trò chuyện",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "Yêu cầu token tải lên trò chuyện thất bại",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "Phản hồi tải lên trò chuyện không hợp lệ",
    "MEDIA_GCS_UPLOAD_FAILED": "Tải lên GCS thất bại",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "Thiếu tên tệp hoặc contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "Thiếu file_path",
    "BLOCK_NOTICE_TITLE": "Thông báo chặn vĩnh viễn",
    "BLOCK_NOTICE_MESSAGE": "Tài khoản của bạn đã bị tạm đình chỉ do vi phạm chính sách.",
    "BLOCK_NOTICE_CONTACT_PREFIX": "Nếu bạn cho rằng việc này cần theo dõi thêm, vui lòng liên hệ",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "qua email.",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "Người dùng không xác định",
    "GENERAL_GUEST": "Khách",
    "ADVISOR_FOR_CLIENT": "Cố vấn cho {client_display_name}",
    "GUEST_FOR_CLIENT": "Khách của {client_display_name}",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "Token và mật khẩu là bắt buộc",
    "AUTH_ERROR_REQUEST_BODY_JSON": "Nội dung yêu cầu phải là JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "Token lời mời không hợp lệ hoặc đã hết hạn",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "Đặt mật khẩu thất bại: thiếu phiên hoặc người dùng",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "Đặt mật khẩu thất bại trong khi đăng nhập",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "Tạo token quản trị thất bại",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "Đăng nhập thất bại: thiếu phiên hoặc người dùng",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "Đăng ký thành công. Vui lòng kiểm tra email để xác minh.",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "Đăng ký thất bại không xác định",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "Xử lý token không hợp lệ",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "Access token là bắt buộc",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "Xem trước token hash yêu cầu gợi ý email từ URL chuyển hướng",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "Không thể phân giải danh tính cho token này",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "Chỉ User Zero mới có thể truy cập dịch vụ selector LLM WF1.",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "Chỉ User Zero mới có thể truy cập dịch vụ điều khiển hiển thị vùng.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "Chỉ User Zero mới có thể truy cập dịch vụ điều khiển phiên bản frontend.",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "Chỉ User Zero mới có thể kiểm tra phiên bản frontend của người dùng khác.",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "Chỉ User Zero mới có thể truy cập dịch vụ điều khiển xóa trò chuyện.",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "Chỉ User Zero mới có thể truy cập dịch vụ kiểm soát thời gian chạy ngôn ngữ giao diện người dùng.",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "Chỉ User Zero mới có thể xóa vĩnh viễn tài khoản người dùng.",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "Payload yêu cầu không hợp lệ.",
    "API_ERROR_INTERNAL_SERVER": "Lỗi máy chủ nội bộ",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "Thiếu hàm trong backend (Yêu cầu tải lại)",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "Chỉ DB RPC được phép cho các chuyển đổi delivered/read.",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "Vui lòng chờ trước khi gửi tin nhắn khác.",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "Tin nhắn đã được gửi thành công.",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "Dịch vụ liên hệ không khả dụng.",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "Gửi tin nhắn thất bại.",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "Tên là bắt buộc.",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "Email không hợp lệ.",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "Tin nhắn là bắt buộc.",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "Payload selector là bắt buộc.",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "Payload hiển thị vùng là bắt buộc.",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "Payload phiên bản frontend là bắt buộc.",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "Payload điều khiển xóa trò chuyện là bắt buộc.",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "Cần có tải trọng kiểm soát thời gian chạy ngôn ngữ giao diện người dùng.",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "ID người dùng đã xác thực là bắt buộc.",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "ID người xem đã xác thực là bắt buộc.",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "ID tác nhân đã xác thực là bắt buộc.",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id là bắt buộc.",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id là bắt buộc.",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "Danh sách owner_user_ids là bắt buộc.",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email là bắt buộc.",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by là bắt buộc.",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "Runtime tìm kiếm bị tắt bởi phiên bản frontend toàn cục.",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "Bạn không được phép hủy lời mời đang chờ này.",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "Lời mời này không còn có thể hủy vì người dùng đã đăng ký.",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "Không tìm thấy lời mời đang chờ.",
    "INVITE_REPLY_ALREADY_MEMBER": "Xin chúc mừng, bạn của bạn ({invitee_email}) đã đăng ký trong ứng dụng này và là thành viên của không gian làm việc này.",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "Có một lời mời đang chờ cho {invitee_email}, nhưng không thể kích hoạt email gửi lại. Vui lòng kiểm tra nhật ký thư.",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "Bản ghi lời mời đã được tạo cho {invitee_email}, nhưng không thể xác nhận việc gửi email. Vui lòng thử lại sau hoặc kiểm tra nhật ký thư.",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "Không tạo được bản ghi lời mời. Vui lòng thử lại sau.",
    "INVITE_REPLY_SYSTEM_ERROR": "Lỗi hệ thống trong quá trình mời: {error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "Lỗi cấu hình backend: Thiếu thông tin xác thực Supabase",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "Lỗi cấu hình backend: URL Supabase không hợp lệ",
    "CHAT_ERROR_ACCESS_DENIED": "Truy cập bị từ chối",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "Nội dung không được để trống đối với tin nhắn văn bản",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "Không thể xác định ID cuộc trò chuyện",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "Thiếu ngữ cảnh xác thực RPC",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC trả về payload tin nhắn không hợp lệ",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "Chèn thất bại, không có dữ liệu được trả về",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations phải là một danh sách",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "Payload thao tác không hợp lệ",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "operation_type không được hỗ trợ",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id là bắt buộc",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "Không tìm thấy tin nhắn",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "Chỉ được phép xóa tin nhắn của chính bạn",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "Xóa cho mọi người không còn khả dụng cho tin nhắn này",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "Xóa cho mọi người thất bại",
    "API_ERROR_SERVER_CONFIGURATION": "Lỗi cấu hình máy chủ",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "Thiếu header secret webhook",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "Nguồn webhook không được ủy quyền",
    "API_ERROR_BACKEND_CONFIGURATION": "Lỗi cấu hình backend",
    "API_ERROR_MODULE_ATTRIBUTE": "Lỗi thuộc tính module: {error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "Thất bại trước khi xóa lời mời trong lúc gỡ người dùng xác thực đang chờ.",
    "CHAT_ERROR_DB": "Lỗi DB: {error}",

    # ==============================================
    # === Live Conversation (Request 69) ===
    # ==============================================
    "CHAT_LIVE_CONVERSATION": "",
    "CHAT_LIVE_CONVERSATION_ARIA": "",
    "LIVE_CONV_START": "",
    "LIVE_CONV_STOP": "",
    "LIVE_CONV_CLOSE": "",
    "LIVE_CONV_STATUS_READY": "",
    "LIVE_CONV_STATUS_CONNECTING": "",
    "LIVE_CONV_STATUS_LISTENING": "",
    "LIVE_CONV_STATUS_TRANSLATING": "",
    "LIVE_CONV_STATUS_FINISHING": "",
    "LIVE_CONV_STATUS_STOPPED": "",
    "LIVE_CONV_TURN_SENDING": "",
    "LIVE_CONV_TURN_SENT": "",
    "LIVE_CONV_TURN_FAILED": "",
    "LIVE_CONV_EMPTY_HINT": "",
    "LIVE_CONV_DISCLAIMER": "",
    "LIVE_CONV_ERROR_DISABLED": "",
    "LIVE_CONV_ERROR_DAILY_LIMIT": "",
    "LIVE_CONV_ERROR_MIC": "",
    "LIVE_CONV_ERROR_CONNECTION": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_AUDIO_REQUIRED": "",
    "LIVE_CONV_ERROR_TURN_MESSAGE_CONVERSATION_REQUIRED": "",
}
