# FILE: ~/otmega/otmega_app/backend/advisor/settings/ui_texts/zh.py
# ماموریت: نگهداری متن‌های اصلی انگلیسی رابط و پیام‌های سیستمی ادوایزر برای استفاده در i18n.

UI_TEXTS = {
    # ==============================================
    # === 1. General UI Elements (Shell & Headers) ===
    # ==============================================
    "MAIN_TITLE": "主界面",
    "APP_TITLE": "OTMEGA AI 平台",
    "APP_SUBTITLE": "AI 顾问",
    "CHAT_PLACEHOLDER": "输入您的消息...",
    "CHAT_SEND_BUTTON": "发送",
    "ADVISOR_DISCLAIMER_MESSAGE": "🙏 顾问可能会出错，请务必核对。",
    "STATUS_ONLINE": "在线",

    # --- Sidebar & Navigation Tooltips ---
    "ICON_MENU": "菜单",
    "ICON_NEW_CHAT": "新建聊天",
    "ICON_HISTORY": "历史记录",
    "ICON_TEMPLATES": "模板",
    "ICON_SETTINGS": "设置",
    "ICON_USER_PROFILE": "用户资料",
    "ICON_QUICK_ACTIONS": "快捷操作",
    "ICON_PINNED": "已置顶",
    "ICON_GALLERY": "图库",

    # ==============================================
    # === 2. PWA & Installation ===
    # ==============================================
    "PWA_INSTALL_TITLE": "安装应用",
    "PWA_ANDROID_MSG": "将此应用安装到您的设备上，以获得更好的体验和离线访问。",
    "PWA_IOS_MSG": "要在您的 iPhone/iPad 上安装此应用：\n1. 点击下方的分享按钮\n2. 选择“添加到主屏幕”",
    "PWA_BTN_INSTALL": "安装",
    "PWA_BTN_LATER": "稍后再说",

    # ==============================================
    # === 3. Authentication (Auth) ===
    # ==============================================

    # --- Window Titles ---
    "AUTH_HEADER_LOGIN": "登录顾问网络",
    "AUTH_HEADER_SIGNUP": "创建您的统一账户",
    "AUTH_HEADER_LOGIN_NETWORK": "登录顾问网络",
    "AUTH_HEADER_SIGNUP_UNIFIED": "创建您的统一账户",

    # --- Buttons ---
    "AUTH_BUTTON_LOGIN": "登录",
    "AUTH_BUTTON_SIGNUP": "创建账户",
    "AUTH_BUTTON_GOOGLE": "使用 Google 继续",
    "AUTH_BUTTON_FORGOT_PASSWORD": "忘记密码",
    "AUTH_BUTTON_SEND_RESET_LINK": "发送重置链接",

    # --- Helper Strings & Links ---
    "AUTH_PROMPT_SIGNUP": "还没有账户？注册",
    "AUTH_PROMPT_LOGIN": "已有账户？登录",
    "AUTH_HELPER_TEXT_SIGNUP": "您正在创建一个统一账户，可用于访问此平台上的所有顾问。",
    "AUTH_HELPER_TEXT_SIGNUP_UNIFIED": "您正在创建一个统一账户，可用于访问此平台上的所有顾问。",
    "AUTH_HELPER_TEXT_LOGIN": "请使用您在此网络中其他顾问处使用过的同一账户（邮箱/密码或 Google）。",
    "AUTH_HELPER_TEXT_LOGIN_NETWORK": "请使用您在此网络中其他顾问处使用过的同一账户（邮箱/密码或 Google）。",
    "AUTH_FORGOT_PASSWORD_LINK": "忘记密码？",
    "AUTH_FORGOT_PASSWORD_TITLE": "重置您的密码",
    "AUTH_FORGOT_PASSWORD_DESCRIPTION": "请输入您的邮箱地址，我们会向您发送重置密码的链接。",
    "AUTH_FORGOT_PASSWORD_EMAIL_LABEL": "邮箱",

    # --- Status & Error Messages ---
    "AUTH_STATUS_LOADING_LOGIN": "正在登录...",
    "AUTH_STATUS_LOADING_SIGNUP": "正在创建您的账户...",
    "AUTH_STATUS_LOADING_RESET": "正在发送重置链接...",
    "AUTH_STATUS_SUCCESS_LOGIN": "登录成功！正在重新加载...",
    "AUTH_STATUS_SUCCESS_RESET": "重置链接已成功发送。请检查您的邮箱。",
    "AUTH_FORGOT_PASSWORD_SUCCESS": "密码重置链接已成功发送。请检查您的邮箱。",

    "AUTH_ERROR_INVALID_CREDENTIALS": "邮箱或密码无效。",
    "AUTH_ERROR_EMAIL_EXISTS": "此邮箱已在顾问网络中存在账户。",
    "AUTH_ERROR_EMAIL_EXISTS_DETAILED": "此邮箱已存在账户。请登录。您目前是以下项的成员：",
    "AUTH_ERROR_EMAIL_EXISTS_NETWORK": "此邮箱已在顾问网络中存在账户。请关闭此窗口，并使用“登录”区域，输入相同邮箱和您之前的密码。",
    "AUTH_ERROR_EMAIL_EXISTS_ADVISORS_LIST": "您目前是以下项的成员：",
    "AUTH_ERROR_EMAIL_PASSWORD_REQUIRED": "邮箱和密码为必填项。",
    "AUTH_ERROR_FAILED_MEMBERSHIP": "账户已创建，但成员资格设置失败。请联系支持团队。",
    "AUTH_ERROR_DEFAULT": "发生错误。请重试。",
    "API_ERROR_GUEST_BANNER_PAYLOAD_REQUIRED": "",
    "API_ERROR_USER_ZERO_GUEST_BANNER_ONLY": "",
    "AUTH_FORGOT_PASSWORD_ERROR": "发送重置链接失败。请重试。",
    "INVITE_REPLY_EMAIL_SENT": "Collabra 邀请邮件已发送给您的朋友：{invitee_email}。",
    "INVITE_REPLY_EMAIL_RESENT": "Collabra 邀请邮件已重新发送给您的朋友：{invitee_email}。",
    
    # --- Password Toggle ---
    "AUTH_PASSWORD_TOGGLE_SHOW": "显示密码",
    "AUTH_PASSWORD_TOGGLE_HIDE": "隐藏密码",

    # ==============================================
    # === 4. Shared Runtime UI Copy ===
    # ==============================================
    "GENERAL_OK": "确定",
    "GENERAL_CANCEL": "取消",
    "GENERAL_CLOSE": "关闭",
    "GENERAL_SEND": "发送",
    "GENERAL_SEARCH": "搜索",
    "GENERAL_RESET": "重置",
    "GENERAL_ENABLE": "启用",
    "GENERAL_LOADING": "正在加载...",
    "GENERAL_DELETE": "删除",
    "GENERAL_DELETING": "正在删除...",
    "GENERAL_SAVE_PASSWORD": "保存密码",
    "AUTH_REMEMBER_EMAIL_LABEL": "记住邮箱",
    "GENERAL_SAVING": "正在保存...",
    "GENERAL_SENDING": "正在发送...",
    "GENERAL_REMOVING": "正在移除...",
    "GENERAL_CONFIRM_REMOVAL": "确认移除",
    "GENERAL_EMPTY": "空",
    "GENERAL_UNAVAILABLE": "不可用",
    "GENERAL_ENABLED": "已启用",
    "GENERAL_DISABLED": "已禁用",
    "GENERAL_GRANTED": "已授予",
    "GENERAL_DENIED": "已拒绝",
    "GENERAL_DEFAULT": "默认",
    "GENERAL_UNSUPPORTED": "不支持",
    "GENERAL_PUBLIC": "公开",
    "GENERAL_PRIVATE": "私密",
    "GENERAL_USERNAME": "用户名",
    "GENERAL_EMAIL": "邮箱",
    "GENERAL_YOU": "您",
    "GENERAL_USER": "用户",
    "GENERAL_UNKNOWN": "未知",
    "GENERAL_VISITOR": "访客",
    "GENERAL_PROFILE": "资料",
    "GENERAL_BANNER": "横幅",
    "GENERAL_UNKNOWN_BANNER": "未知横幅",
    "GENERAL_ADVISOR_BANNER": "顾问横幅",
    "GENERAL_NOT_AVAILABLE": "不可用",
    "GENERAL_NOT_SELECTED": "未选择",
    "GENERAL_NO_EMAIL_FOUND": "未找到邮箱",
    "GENERAL_USER_ZERO_ONLY": "仅限 User Zero",
    "GENERAL_CONNECTION_STATE": "连接状态",
    "GENERAL_DISPLAY_ONLY": "仅显示",
    "GENERAL_TEXTAREA": "文本区域",

    # ==============================================
    # === 5. Header, Status, and Navigation ===
    # ==============================================
    "HEADER_MENU_LCAC": "菜单 (LCAC)",
    "HEADER_CHAT_CCAC": "聊天 (CCAC)",
    "HEADER_QUICK_ACTIONS_RCAC": "快捷操作 (RCAC)",
    "HEADER_CHANGE_STATUS": "更改状态",
    "HEADER_OT_COIN_BALANCE": "OT Coin 余额",
    "HEADER_ALT_USER": "用户",
    "STATUS_BUSY": "忙碌",
    "STATUS_AWAY": "离开",
    "STATUS_OFFLINE": "离线",
    "STATUS_INVISIBLE": "隐身",
    "NETWORK_CHECKING_CONNECTION": "正在检查连接...",
    "NETWORK_ONLINE_LATENCY": "在线（延迟：{latency}毫秒）",
    "NETWORK_GOOD_TAP_TO_PING": "网络：良好（点击以 ping）",
    "CHAT_TARGET_ALT": "聊天目标",

    # ==============================================
    # === 6. Chat, Media, and Message UI ===
    # ==============================================
    "CHAT_SEARCH_PLACEHOLDER": "搜索...",
    "CHAT_OPEN_PROFILE_PICTURE_ARIA": "打开 {name} 的头像",
    "CHAT_MESSAGE_INPUT_ARIA": "消息输入框",
    "CHAT_TOGGLE_VIEW_ARIA": "切换视图",
    "CHAT_ADD_USER_ARIA": "添加用户",
    "CHAT_ATTACH_ARIA": "添加附件",
    "CHAT_MIC_ARIA": "麦克风",
    "CHAT_SEND_ARIA": "发送",
    "CHAT_SEARCH_ARIA": "搜索",
    "CHAT_OPEN_SEARCH_ARIA": "打开搜索",
    "CHAT_CLOSE_SEARCH_ARIA": "关闭搜索",
    "CHAT_ATTACHMENT_ALT": "附件",
    "CHAT_PREVIEW_ALT": "预览",
    "CHAT_REMOVE_ATTACHMENT_ARIA": "移除附件",
    "CHAT_REPLYING_TO": "正在回复",
    "CHAT_CANCEL_REPLY_ARIA": "取消回复",
    "CHAT_UPLOADING": "正在上传...",
    "CHAT_LOADING_CHATS": "正在加载聊天...",
    "CHAT_SEND_FAILED": "发送失败",
    "CHAT_SEND_FAILED_RETRY": "发送失败。请重试。",
    "CHAT_RETRY": "重试",
    "CHAT_EDITED": "已编辑",
    "CHAT_TYPING": "正在输入",
    "CHAT_LOADING": "正在加载",
    "CHAT_PENDING_INVITATION": "邀请待处理",
    "CHAT_PENDING_INVITATION_MIN": "{count} 分钟 邀请待处理",
    "CHAT_PENDING_INVITATION_HR": "{count} 小时 邀请待处理",
    "CHAT_PENDING_INVITATION_DAY": "{count} 天 邀请待处理",
    "CHAT_WAITING_FOR_YOU": "{label} - 正在等待您",
    "CHAT_PENDING_ACCEPTANCE": "{label} - 等待接受",
    "CHAT_MICROPHONE_ACCESS_DENIED": "麦克风访问被拒绝。",
    "CHAT_UPLOAD_FAILED": "上传失败：{error}",
    "CHAT_UPLOAD_REQUIRES_ONLINE": "上传需要互联网连接。请在线后重试。",
    "CHAT_ERROR_AUTH": "身份验证错误",
    "CHAT_ERROR_MISSING_FILENAME_CONTENT_TYPE": "缺少 filename 或 content_type",
    "CHAT_ERROR_MISSING_CONVERSATION_OR_TARGET": "缺少 conversation_id 或 target_id",
    "CHAT_ERROR_MISSING_CONVERSATION_FOR_UPLOAD": "非头像上传缺少 conversation_id",
    "CHAT_ERROR_INVALID_AVATAR_FILE_PATH": "无效的头像 file_path",
    "CHAT_ERROR_SUPABASE_SERVICE_CLIENT_UNAVAILABLE": "Supabase 服务客户端不可用",
    "CHAT_ERROR_AVATAR_READ_ACK_ADVISOR_ONLY": "头像已读确认仅在顾问聊天上下文中有效",
    "CHAT_ERROR_AVATAR_FLOW_NOT_FOUND": "未找到头像流程消息，或该消息不符合已读确认条件",
    "CHAT_ERROR_AVATAR_READ_FINALIZE_FAILED": "将头像消息最终标记为已读失败",
    "CHAT_ATTACHMENT_COUNT_ONE": "1 个附件",
    "CHAT_ATTACHMENT_COUNT_MANY": "{count} 个附件",
    "CHAT_VOICE_NOTE": "语音备注",
    "CHAT_UNAVAILABLE_TARGET_BLOCKED_VIEWER": "聊天不可用。此用户已屏蔽您。",
    "CHAT_UNAVAILABLE_VIEWER_BLOCKED_TARGET": "聊天不可用。您已屏蔽此用户。",
    "CHAT_UNAVAILABLE_ACCOUNT_POLICY": "账户访问已被策略阻止。",
    "CHAT_UNAVAILABLE_FINAL_BLOCKED_USER_ZERO": "聊天不可用。此账户已被 User Zero 最终屏蔽。",
    "CHAT_UNAVAILABLE_MUTUAL_BLOCK": "聊天不可用。双方屏蔽已生效。",
    "CHAT_UNAVAILABLE_BLOCK_POLICY": "由于屏蔽策略，聊天不可用。",
    "MESSAGE_PREVIEW_PHOTO": "照片",
    "MESSAGE_PREVIEW_VOICE": "语音消息",
    "MESSAGE_PREVIEW_VIDEO": "视频",
    "MESSAGE_PREVIEW_PDF": "PDF",
    "MESSAGE_PREVIEW_FILE": "文件",
    "MESSAGE_PREVIEW_MESSAGE": "消息",
    "MESSAGE_PREVIEW_SYSTEM": "系统消息",
    "MESSAGE_PREVIEW_NEW": "新消息",
    "MESSAGE_UNKNOWN_FILE": "未知文件",
    "MESSAGE_AUDIO_ATTACHMENT": "音频附件",
    "MESSAGE_FILE_ATTACHMENT": "附件",
    "BANNER_INVITED_BY": "由 {label} 邀请",

    # ==============================================
    # === 7. Search, Share, Forward, and Menus ===
    # ==============================================
    "SEARCH_RESULTS_TITLE": "搜索结果",
    "SEARCH_QUERY_LABEL": "查询：",
    "SEARCH_LOADING_VISIBILITY": "正在加载搜索可见性...",
    "SEARCH_NO_RESULTS": "当前搜索范围内未找到结果。",
    "SHARE_WITH_COLLABRA": "分享到 Collabra",
    "SHARE_SEND_TO": "发送给",
    "SHARE_SELECT_ONE_BANNER": "选择一个横幅",
    "SHARE_BANNER_LIST_ARIA": "横幅列表",
    "SHARE_NO_MATCHING_BANNER": "没有匹配的横幅",
    "SHARE_ADD_COMMENT_PLACEHOLDER": "添加评论...",
    "SHARE_RECENT_CHATS": "最近聊天",
    "SHARE_LEFT_LIST": "左侧列表",
    "SHARE_RIGHT_LIST": "右侧列表",
    "SHARE_UNTITLED_BANNER": "未命名横幅",
    "SHARE_SHARED_CONTENT": "共享内容",
    "SHARE_SHARED_CONTENT_OPEN_FAILED": "无法打开共享内容。",
    "SHARE_OPEN_BANNER_FAILED": "无法打开所选横幅。",
    "SHARE_ONE_PHOTO_SELECTED": "已选择 1 张照片",
    "SHARE_MANY_PHOTOS_SELECTED": "已选择 {count} 张照片",
    "SHARE_ONE_FILE_SELECTED": "已选择 1 个文件",
    "SHARE_MANY_FILES_SELECTED": "已选择 {count} 个文件",
    "FORWARD_MESSAGE_TITLE": "转发消息",
    "FORWARD_SELECT_RECIPIENTS": "选择收件人",
    "FORWARD_NO_OTHER_BANNER": "没有其他可用横幅。",
    "FORWARD_SEND_TO_COUNT": "发送给 {count}",
    "FORWARD_SELECT_AT_LEAST_ONE_BANNER": "请至少选择一个横幅。",
    "FORWARD_FAILED_DEFAULT": "转发失败。请重试。",
    "FORWARD_PARTIAL_SENT": "已发送 {count} 个。{error}",
    "FORWARD_SOURCE_NOT_FOUND": "未找到用于转发的源消息",
    "FORWARD_NO_FORWARDABLE_CONTENT": "此消息目前没有可转发内容",
    "FORWARD_DESTINATION_MISSING": "缺少转发目标",
    "FORWARD_MESSAGE_PREVIEW": "已转发消息",
    "MENU_PASTE": "粘贴",
    "MENU_COPY": "复制",
    "MENU_REPLY": "回复",
    "MENU_FORWARD": "转发",
    "MENU_REMOVE_INVITATION": "移除邀请",
    "MENU_REMOVE_FROM_LIST": "从列表中移除",
    "MENU_GOODBYE_GUEST": "",
    "MENU_ADD_TO_LIST": "添加到列表",
    "MENU_REJECT_INVITATION": "拒绝邀请",
    "MENU_FRONTEND_VERSION": "前端版本",
    "MENU_BANNER_HEADER": "横幅 - {zone}",
    "MENU_BANNER_INFO": "横幅信息：{title}",
    "MENU_MESSAGE_BUBBLE": "消息气泡",
    "MENU_CHAT_CANVAS_HEADER": "聊天画布 - {zone}",
    "MENU_CANVAS_INFO": "画布信息",
    "MENU_CHAT_CANVAS_SUBLABEL": "会话区域 / 当前聊天表面",
    "MENU_INPUT_AREA_HEADER": "输入区域 - {zone}",
    "MENU_INPUT_AREA_INFO": "输入区域信息：{title}",
    "MENU_INPUT_AREA_DESCRIPTION": "底部输入和操作工具区域",
    "MENU_HEADER": "页眉 - {zone}",
    "MENU_HEADER_INFO": "页眉信息：{title}",
    "MENU_HEADER_DESCRIPTION": "顶部导航和页面控制",
    "MENU_ZONE_HEADER": "区域 - {zone}",
    "MENU_ZONE_SPACE_INFO": "区域空间信息",
    "MENU_EMPTY_LIST_SURFACE": "空白/列表表面",
    "MENU_BLOCK": "屏蔽",
    "MENU_UNBLOCK": "取消屏蔽",
    "MENU_HIDE_IN_SEARCH": "在搜索中隐藏",
    "MENU_UNHIDE_IN_SEARCH": "在搜索中取消隐藏",
    "MENU_VISIBLE_IN_SEARCH": "在搜索中可见",
    "MENU_HIDDEN_IN_SEARCH": "在搜索中隐藏",
    "MENU_VISIBLE_IN_USER_LIST": "在用户列表中可见",
    "MENU_HIDDEN_IN_USER_LIST": "在用户列表中隐藏",
    "MENU_NOT_BLOCKED": "未屏蔽",
    "MENU_BLOCKED": "已屏蔽",
    "MENU_FRONTEND_VERSION_LOADING": "正在加载...",
    "MENU_FRONTEND_VERSION_LOADING_HELPER": "正在从后端加载每个横幅的值。在数据库响应到达前，不会将任何选项标记为活动。",
    "MENU_FRONTEND_VERSION_LOAD_FAILED": "无法加载后端值。未显示任何可信的活动选项。",
    "MENU_FRONTEND_VERSION_OVERRIDE_ACTIVE": "显式的每横幅数据库值为 {overrideVersion}。全局默认值为 {globalDefaultVersion}。目标用户必须完全刷新或重新打开应用，启动 bootstrap 才会应用它。",
    "MENU_FRONTEND_VERSION_DEFAULT_ACTIVE": "未存储显式的每横幅数据库值。FeV2.0.0 默认处于活动状态。全局默认值为 {globalDefaultVersion}。",
    "MENU_FRONTEND_VERSION_ACTIVE_OVERRIDE_NOTE": "显式的每横幅数据库值会在目标应用完全重新加载后生效",
    "MENU_FRONTEND_VERSION_ACTIVE_DEFAULT_NOTE": "未存储显式的每横幅值；这是默认的个人 FeV2.0.0 状态",
    "MENU_FRONTEND_VERSION_GLOBAL_DEFAULT_NOTE": "此选项也等于当前全局默认值",
    "MENU_DELETE_PERMANENT_CONFIRM": "要从数据库中永久删除 {target} 吗？这将移除账户、聊天历史、依赖项，并强制未来重新进入时走全新的邀请路径。",
    "MENU_DELETE_PERMANENTLY": "永久删除",
    "MENU_REFRESH_PAGE": "刷新页面",
    "MENU_LOG_OFF": "注销",
    "MENU_HARD_RELOAD": "强制重新加载",

    # ==============================================
    # === 8. Auth, Registration, and Invitations ===
    # ==============================================
    "APP_BRAND_TITLE": "OT Collabra AI",
    "AUTH_EMAIL_ADMIN_PLACEHOLDER": "邮箱（管理员用户）",
    "AUTH_PASSWORD_PLACEHOLDER": "密码",
    "AUTH_CONNECTING": "正在连接...",
    "AUTH_SIGNING_OUT": "正在退出...",
    "AUTH_BACK_TO_LOGIN": "返回登录",
    "AUTH_INVALID_SERVER_RESPONSE_NO_TOKEN": "服务器响应无效：未找到 token。",
    "AUTH_LOGIN_FAILED": "登录失败",
    "AUTH_PASSWORDS_DO_NOT_MATCH": "密码不匹配。",
    "AUTH_PASSWORDS_DO_NOT_MATCH_STRONG": "密码不匹配！",
    "AUTH_PASSWORDS_MUST_MATCH_EXACTLY": "密码必须完全一致。",
    "AUTH_NEW_PASSWORD_PLACEHOLDER": "新密码",
    "AUTH_CONFIRM_PASSWORD_PLACEHOLDER": "确认密码",
    "AUTH_CHANGE_PASSWORD": "更改密码",
    "AUTH_SAVING_PASSWORD": "正在保存...",
    "AUTH_PASSWORD_UPDATED_SUCCESS": "密码已成功更新。",
    "AUTH_CHANGE_PASSWORD_UNABLE": "目前无法更改密码。",
    "AUTH_MUST_BE_LOGGED_IN_CHANGE_PASSWORD": "您必须登录才能更改密码。",
    "AUTH_NEW_PASSWORD_VISIBILITY_ARIA": "切换新密码可见性",
    "AUTH_CONFIRM_PASSWORD_VISIBILITY_ARIA": "切换确认密码可见性",
    "REGISTER_TITLE": "完成注册",
    "REGISTER_SUBTITLE": "请手动设置您的密码。",
    "REGISTER_CREATING_ACCOUNT": "正在创建账户...",
    "REGISTER_FINISH_SETUP": "完成设置",
    "REGISTER_FAILED_SET_PASSWORD": "设置密码失败",
    "INVITE_EMAIL_INSTRUCTION": "请输入被邀请人的邮箱（格式：user@example.com）",
    "INVITE_EMAIL_PLACEHOLDER": "user@example.com",
    "INVITE_BUTTON": "邀请",
    "INVITE_EMAIL_REQUIRED": "请输入被邀请人的邮箱。",
    "INVITE_EMAIL_INVALID": "邮箱格式无效。请使用：user@example.com",
    "PENDING_INVITATION_TITLE": "待处理邀请",
    "PENDING_INVITATION_REMOVE_QUESTION": "要从数据库中移除此待处理邀请吗？",
    "PENDING_INVITATION_KEEP": "保留邀请",
    "PENDING_INVITATION_REMOVAL_FAILED": "移除失败。",
    "REMOVE_FROM_LIST_TITLE": "从列表中移除",
    "REMOVE_FROM_LIST_WARNING": "现在将此用户从两个列表中移除吗？聊天访问将立即中断。唯一的返回路径是新的邀请。",
    "REMOVE_FROM_LIST_KEEP": "将用户保留在列表中",
    "REMOVE_FROM_LIST_FAILED": "从列表中移除失败。",

    # ==============================================
    # === 9. Permission and User Zero Panels ===
    # ==============================================
    "PERMISSION_SETTING_LIVE_STATUS": "设置与实时状态",
    "PERMISSION_DIALOG_ARIA": "设置和实时状态",
    "PERMISSION_TRIGGER_ARIA": "设置弹窗触发器",
    "PERMISSION_CLOSE_ARIA": "关闭权限弹窗",
    "PERMISSION_LIVE_STATUS": "实时状态",
    "PERMISSION_SYSTEM_PERMISSION": "系统权限",
    "PERMISSION_APP_PUSH": "应用推送",
    "PERMISSION_LOCATION_PERMISSION": "位置权限",
    "PERMISSION_APP_LOCATION": "应用位置",
    "PERMISSION_CONTROLS": "权限控制",
    "PERMISSION_PUSH_NOTIFICATIONS": "推送通知",
    "PERMISSION_LOCATION_ACCESS": "位置访问",
    "PERMISSION_IN_APP_SETTINGS": "应用内设置",
    "PERMISSION_ALERT_SOUND": "提示音",
    "PERMISSION_APP_BADGE": "应用角标",
    "PERMISSION_PASSWORD_SETTINGS": "密码设置",
    "PERMISSION_NAVIGATION_STATUS": "导航状态",
    "PERMISSION_SELECTED_ZONE": "所选区域",
    "PERMISSION_STAGED_CHAT_BANNER": "暂存聊天横幅",
    "PERMISSION_CANVAS_CONTENT": "画布内容",
    "PERMISSION_YOUR_DEVICES": "您的设备（{count}）",
    "PERMISSION_REFRESH_DEVICE_LIST": "刷新设备列表",
    "PERMISSION_REFRESH_LIST": "刷新列表",
    "PERMISSION_NO_REGISTERED_DEVICES": "未找到已注册设备。",
    "PERMISSION_RESIZE_POPUP_ARIA": "调整设置弹窗大小",
    "PERMISSION_TOGGLE_PUSH_ARIA": "切换推送通知",
    "PERMISSION_TOGGLE_LOCATION_ARIA": "切换位置访问",
    "PERMISSION_TOGGLE_ALERT_SOUND_ARIA": "切换提示音",
    "PERMISSION_TOGGLE_APP_BADGE_ARIA": "切换应用角标",
    "PERMISSION_TOGGLE_PROFILE_VISIBILITY_ARIA": "切换资料可见性",
    "PERMISSION_OFF_IN_V1": "v1 中关闭",
    "PERMISSION_CHAT": "聊天",
    "PERMISSION_BANNER_LIST": "横幅列表",
    "PERMISSION_PUSH_DISABLED_V1": "v1 Google Play 版本已禁用推送通知。",
    "PERMISSION_PUSH_ON_TOOLTIP": "此设备的推送通知已开启。",
    "PERMISSION_PUSH_BLOCKED_TOOLTIP": "系统通知已被阻止。点击打开设置帮助。",
    "PERMISSION_PUSH_ENABLE_TOOLTIP": "开启以提高送达可靠性。",
    "PERMISSION_SYSTEM_DISABLE_HELP": "要禁用系统通知，请打开浏览器/站点通知设置，并将此站点设为阻止。",
    "PERMISSION_SYSTEM_ALLOW_HELP": "要更改系统通知权限，请打开浏览器/站点通知设置，并将此站点设为允许。",
    "PERMISSION_LOCATION_ON_TOOLTIP": "位置访问已开启，用于基于距离的 LCAC 排序和地图定位。",
    "PERMISSION_LOCATION_UNSUPPORTED_TOOLTIP": "此环境不支持位置 API。",
    "PERMISSION_LOCATION_BLOCKED_TOOLTIP": "位置访问已被阻止。点击打开设置帮助。",
    "PERMISSION_LOCATION_ENABLE_TOOLTIP": "开启以允许精准的基于距离 LCAC 排序和应用内地图定位。",
    "PERMISSION_LOCATION_UNSUPPORTED_ALERT": "此环境不支持位置访问。",
    "PERMISSION_LOCATION_DISABLE_HELP": "要禁用位置访问，请打开浏览器/站点位置设置，并将此站点设为阻止。",
    "PERMISSION_LOCATION_ALLOW_HELP": "要启用位置访问以用于距离排序和应用内地图定位，请打开浏览器/站点位置设置，并将此站点设为允许。",
    "PERMISSION_DEVICE_LOAD_FAILED": "目前无法加载已注册设备。",

    # ==============================================
    # === 10. Runtime Control Sections ===
    # ==============================================
    "RUNTIME_LOADING_UI_BRIDGE": "正在加载 UI 桥接...",
    "RUNTIME_LOADING_LOCAL_BRIDGE": "正在加载本地桥接...",
    "RUNTIME_LOADING_BACKEND": "正在加载后端...",
    "RUNTIME_LOADING": "正在加载...",
    "RUNTIME_LOADING_FROM_DATABASE": "正在从数据库加载...",
    "RUNTIME_BACKEND_CONNECTED": "后端已连接",
    "RUNTIME_CACHED_FALLBACK_ACTIVE": "缓存回退已启用",
    "RUNTIME_FALLBACK_DEFAULT_ACTIVE": "默认回退已启用",
    "RUNTIME_FALLBACK_DEFAULTS_ACTIVE": "回退默认值已启用",
    "RUNTIME_SAVING_THROUGH_BACKEND": "正在通过后端保存...",
    "RUNTIME_SAVED_IN_BACKEND_SERVICE": "已保存在后端服务中",
    "RUNTIME_SAVE_FAILED": "保存失败",
    "RUNTIME_LOAD_FAILED": "加载失败",
    "RUNTIME_CONNECTED": "已连接",
    "RUNTIME_LOGIN_REQUIRED": "需要登录",
    "RUNTIME_SAVED": "已保存",
    "RUNTIME_UI_READY_RUNTIME_PENDING": "UI 已就绪 - 运行时待处理",
    "RUNTIME_BACKEND_REJECTED_MODEL": "受保护的后端选择器服务拒绝或无法保存请求的模型选项。",
    "RUNTIME_BACKEND_REJECTED_ROUTING": "受保护的后端选择器服务拒绝或无法保存请求的 WF1 路由更改。",
    "RUNTIME_WF1_SELECTOR_BACKEND": "选择器现在正从受保护的后端服务读取活动配置、Qwen 路由和允许的选项。",
    "RUNTIME_WF1_SELECTOR_CACHED": "后端选择器服务当前不可用，因此正在使用最后缓存的选择器状态。",
    "RUNTIME_WF1_SELECTOR_DEFAULTS": "由于无法加载后端或缓存的选择器状态，选择器默认值已启用。",
    "RUNTIME_WF1_SELECTOR_SAVED": "受保护的后端选择器服务已更新活动 WF1 路由配置，并刷新运行时域缓存。",
    "FRONTEND_VERSION_TITLE": "前端版本",
    "FRONTEND_VERSION_HELPER_ACTIVE": "此选择器控制所有用户的活动前端版本。FeV2.0.0 处于活动状态。",
    "FRONTEND_VERSION_HELPER_RUNTIME": "此选择器从 config_domain_registry 读取活动前端版本。运行时解析为 FeV2.0.0。",
    "FRONTEND_VERSION_HELPER_FALLBACK": "无法加载后端前端版本配置，因此编码的 FeV2.0.0 默认值会保持活动，直到启动 bootstrap 能再次读取受保护服务。",
    "FRONTEND_VERSION_HELPER_SAVED": "活动前端版本已保存到 config_domain_registry。完整刷新或下次应用加载将应用运行时值。",
    "FRONTEND_VERSION_HELPER_SAVE_FAILED": "后端前端版本控制服务无法保存请求的全局版本。",
    "FRONTEND_VERSION_OPTION_ACTIVE_NOTE": "活动前端版本。",
    "CHAT_DELETE_WINDOW_TITLE": "聊天删除窗口",
    "CHAT_DELETE_HELPER": "此值控制“为所有人删除”的可用时间窗口，单位为秒。保存后后端守卫会立即更改。气泡可见性会在完整刷新或下次应用加载后更改。",
    "CHAT_DELETE_HELPER_FALLBACK": "无法加载后端聊天删除控制服务，因此编码的默认值会保持活动，直到启动 bootstrap 能再次读取受保护服务。",
    "CHAT_DELETE_HELPER_SAVED": "“为所有人删除”的可用时间窗口已保存到 config_domain_registry。后端守卫会立即更改。气泡可见性会在完整刷新或下次应用加载后更改。",
    "CHAT_DELETE_HELPER_SAVE_FAILED": "后端聊天删除控制服务无法保存请求的窗口值。",
    "CHAT_DELETE_WINDOW_LABEL": "为所有人删除窗口",
    "CHAT_DELETE_WINDOW_SECONDS": "{count} 秒",
    "CHAT_DELETE_WINDOW_SECONDS_HELP": "以整秒保存该值。当前生产值为 86400 秒 = 1 天。",
    "CHAT_DELETE_WINDOW_SECONDS_LABEL": "窗口秒数",
    "CHAT_DELETE_WINDOW_SECONDS_INVALID": "请输入大于或等于 0 的整数。",
    "CHAT_DELETE_SAVE_BUTTON": "保存删除窗口",
    "GUEST_BANNER_CONTROL_TITLE": "",
    "GUEST_BANNER_CONTROL_LABEL": "",
    "GUEST_BANNER_CONTROL_ENABLED_LABEL": "",
    "GUEST_BANNER_CONTROL_HELPER": "",
    "GUEST_BANNER_CONTROL_HELPER_FALLBACK": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVED": "",
    "GUEST_BANNER_CONTROL_HELPER_SAVE_FAILED": "",
    "GUEST_BANNER_CONTROL_REVOKED_COUNT": "",
    "GUEST_BANNER_PENDING_TTL_MINUTES_LABEL": "",
    "GUEST_BANNER_PENDING_TTL_CURRENT": "",
    "GUEST_BANNER_PENDING_TTL_INVALID": "",
    "GUEST_BANNER_CONTROL_SAVE_BUTTON": "",
    "GUEST_QR_LOADING": "",
    "GUEST_QR_READY": "",
    "GUEST_QR_ALT": "",
    "GUEST_QR_LOAD_FAILED": "",
    "GUEST_SESSION_ACTIVE": "",
    "GUEST_PUBLIC_TITLE": "",
    "GUEST_PUBLIC_CONNECTING": "",
    "GUEST_PUBLIC_CONNECTED": "",
    "GUEST_PUBLIC_UNAVAILABLE": "",
    "GUEST_PUBLIC_SEND_FAILED": "",
    "UI_TEXTS_RUNTIME_TITLE": "",
    "UI_TEXTS_RUNTIME_BACKEND": "",
    "UI_TEXTS_RUNTIME_CACHED": "",
    "UI_TEXTS_RUNTIME_DEFAULTS": "",
    "UI_TEXTS_RUNTIME_SAVED": "",
    "UI_TEXTS_RUNTIME_SAVE_FAILED": "",
    "UI_TEXTS_RUNTIME_DEVICE_LANGUAGE_LABEL": "",
    "UI_TEXTS_RUNTIME_ENABLE_DEVICE_LANGUAGE": "",
    "UI_TEXTS_RUNTIME_ENABLED_NOTE": "",
    "UI_TEXTS_RUNTIME_DISABLED_NOTE": "",
    "PROFILE_VISIBILITY_TITLE": "资料可见性",
    "PROFILE_VISIBILITY_LOGIN_REQUIRED": "您必须登录才能管理账户可见性。",
    "PROFILE_VISIBILITY_HELPER": "此开关仅更新您的账户可见性状态。可发现性和横幅列表行为在此阶段保持不变。",
    "PROFILE_VISIBILITY_LOAD_FAILED": "目前无法加载资料可见性。",
    "PROFILE_VISIBILITY_SAVE_FAILED": "目前无法更新资料可见性。",
    "PROFILE_VISIBILITY_SAVED": "您的账户可见性现在为 {visibility}。可发现性标志在此阶段保持不变。",
    "PROFILE_VISIBILITY_PUBLIC_ACCOUNT": "公开账户",
    "PROFILE_VISIBILITY_STORED": "已存储的可见性",
    "WF1_MODEL_CONTROL_TITLE": "WF1 模型控制",
    "WF1_ENABLE_TRANSLATION": "启用翻译 / 枢轴",
    "WF1_TRANSLATION_ACTIVE": "AI 翻译已启用。",
    "WF1_TRANSLATION_INACTIVE": "WF1 继续运行，但源文本会被复制，枢轴会标记为未启用。",
    "WF1_ACTIVE_RUNTIME_SLOT": "活动运行时槽位",
    "WF1_ALLOW_SAME_LANGUAGE": "允许同语言对使用 AI",
    "WF1_SAME_LANGUAGE_ACTIVE": "同语言对遵循正常 WF1 路由。",
    "WF1_SAME_LANGUAGE_INACTIVE": "同语言对绕过 AI，并存储为无活动枢轴语言。",
    "WF1_QWEN_ROUTING": "Qwen 语言对路由",
    "WF1_QWEN_ROUTING_HELPER": "下方勾选的语言会在以下情况使用 Qwen-Max：语言对为同一勾选语言、勾选语言与英语、或两个已勾选的非英语语言。否则，所选主模型保持活动。",
    "WF1_OPENROUTER_TEST_SLOT": "OpenRouter 测试槽位",
    "WF1_OPENROUTER_DEFAULT_LABEL": "OpenRouter 测试槽位 - Grok 4.20 Beta",
    "WF1_QUALITY_TEST_ONLY": "仅质量测试",
    "WF1_OPENROUTER_HELPER": "此槽位仅可用于临时 OpenRouter 质量测试编辑。除非此槽位本身成为活动模型，否则不会更改 Qwen 语言对路由的运行路径。",
    "WF1_LABEL": "标签",
    "WF1_PRODUCT": "产品",
    "WF1_MODEL": "模型",
    "WF1_PROVIDER_OPENROUTER": "提供商：OpenRouter",
    "WF1_SECRET_OPENROUTER": "密钥：OPENROUTER_API_KEY",
    "WF1_PROVIDER_GOOGLE": "Google",
    "WF1_PROVIDER_OPENAI": "OpenAI",
    "WF1_MODEL_GEMINI_25_FLASH_LITE": "Gemini 2.5 Flash Lite",
    "WF1_MODEL_GEMINI_25_PRO": "Gemini 2.5 Pro",
    "WF1_MODEL_GEMINI_31_PRO_PREVIEW": "Gemini 3.1 Pro Preview",
    "WF1_MODEL_GPT_4O": "GPT-4o",
    "WF1_MODEL_GPT_4O_MINI": "GPT-4o mini",
    "WF1_MODEL_GPT_54": "GPT-5.4",
    "WF1_MODEL_OPENROUTER_TEST_SLOT_GROK_420_BETA": "OpenRouter 测试槽位 · Grok 4.20 Beta",
    "WF1_QWEN_MAX_LABEL": "Qwen-Max",
    "WF1_QWEN_MAX_OPENROUTER_LABEL": "通过 OpenRouter 使用 Qwen-Max",
    "WF1_PRICING_GOOGLE_LIST_PRICE": "Google 标价",
    "WF1_PRICING_OPENAI_LIST_PRICE": "OpenAI 标价",
    "WF1_PRICING_OPENROUTER_LIST_PRICE": "OpenRouter 标价",
    "LANGUAGE_ENGLISH": "英语",
    "LANGUAGE_CHINESE_SIMPLIFIED": "中文（简体）",
    "LANGUAGE_CHINESE_TRADITIONAL": "中文（繁体）",
    "LANGUAGE_JAPANESE": "日语",
    "LANGUAGE_KOREAN": "韩语",
    "LANGUAGE_PERSIAN": "波斯语",
    "LANGUAGE_TURKISH_ISTANBUL": "土耳其语（伊斯坦布尔）",
    "LANGUAGE_ARABIC": "阿拉伯语",
    "LANGUAGE_FRENCH": "法语",
    "LANGUAGE_GERMAN": "德语",
    "LANGUAGE_SPANISH": "西班牙语",
    "LANGUAGE_PORTUGUESE": "葡萄牙语",
    "LANGUAGE_ITALIAN": "意大利语",
    "LANGUAGE_RUSSIAN": "俄语",
    "LANGUAGE_DUTCH": "荷兰语",
    "LANGUAGE_VIETNAMESE": "越南语",
    "LANGUAGE_INDONESIAN": "印度尼西亚语",
    "LANGUAGE_THAI": "泰语",
    "LANGUAGE_MALAY": "马来语",
    "WF1_PRICING_CUSTOM": "定价：自定义槽位模型 - 请查看当前 OpenRouter 定价",
    "WF1_SAVE_OPENROUTER_SLOT": "保存 OpenRouter 槽位",
    "WF1_PRICING_LINE": "输入 {input} - 输出 {output}",
    "WF1_PRICING_WITH_NOTE": "{pricing} - {note}",
    "WF1_PROVIDER_SECRET": "密钥：{secret}",
    "ZONE_VISIBILITY_TITLE": "区域可见性控制",
    "ZONE_ENABLE": "启用 {zone}",
    "ZONE_ENABLED_NOTE": "{zone} 可在下次应用加载后为允许的角色显示。",
    "ZONE_DISABLED_NOTE": "下次应用加载后，对于非 S_Admin 用户，{zone} 会被视为不存在。",
    "ZONE_S_ADMIN_BYPASS": "S_Admin 会绕过此角色列表，并始终保留访问权限。",
    "ZONE_ROLE_LOCKED": "当此区域被禁用时，角色选择会暂时锁定；当该区域再次启用时，会完全恢复为已保存状态。",
    "ZONE_LCAC_CONTROL": "LCAC 控制",
    "ZONE_RCAC_CONTROL": "RCAC 控制",
    "ZONE_LCAC_DESCRIPTION": "控制左侧保留区域的存在，以及哪些角色可以看到它。",
    "ZONE_RCAC_DESCRIPTION": "控制右侧保留区域的存在，以及哪些角色可以看到它。",
    "ZONE_VISIBILITY_BACKEND": "区域可见性 bootstrap 现在正从受保护的后端服务读取。更改会在下次应用加载时应用。",
    "ZONE_VISIBILITY_CACHED": "后端区域可见性服务当前不可用，因此缓存值或本地默认值处于活动状态。",
    "ZONE_VISIBILITY_DEFAULTS": "由于无法加载后端或缓存状态，区域可见性默认值已启用。",
    "ZONE_VISIBILITY_SAVED": "区域可见性 bootstrap 已保存。需要强制重新加载或下次应用加载，运行时才会应用。",
    "ZONE_VISIBILITY_SAVE_FAILED": "受保护的后端服务无法保存请求的区域可见性更改。",
    "ROLE_MEMBER": "成员",
    "ROLE_STAFF": "员工",
    "ROLE_ADMIN": "管理员",
    "ZONE_LCAC_V2": "LCAC (V2)",
    "ZONE_RCAC_V2": "RCAC (V2)",
    "MAIN_ENABLE_NOTIFICATIONS": "启用通知以接收新消息。",
    "MAIN_LOG_OUT": "退出登录",
    "NOTIFICATION_NEW_MESSAGE": "新消息",
    "NOTIFICATION_UNREAD_MESSAGE": "您有一条未读消息。",

    # ==============================================
    # === 11. Media Viewer and Account Blocks ===
    # ==============================================
    "MEDIA_FULL_VIEW_ALT": "完整视图",
    "MEDIA_AUDIO_ATTACHMENT": "音频附件",
    "MEDIA_FILE_FALLBACK": "文件",
    "MEDIA_DOWNLOAD_READY": "附件已准备好下载",
    "MEDIA_TYPE_UNSUPPORTED": "完整视图不支持此类型",
    "MEDIA_PREVIOUS_IMAGE_ARIA": "上一张图片",
    "MEDIA_NEXT_IMAGE_ARIA": "下一张图片",
    "MEDIA_OPEN_ORIGINAL": "打开原始文件",
    "MEDIA_DOWNLOAD": "下载",
    "MEDIA_CLOSE_ARIA": "关闭",
    "MEDIA_PROFILE_PICTURE_ARIA": "{name} 的头像",
    "MEDIA_PROFILE_ALT": "{name} 的资料",
    "MEDIA_UPLOAD_FAILED": "上传失败",
    "MEDIA_BACKEND_TOKEN_ERROR": "后端 Token 错误",
    "MEDIA_UPLOAD_URL_MISSING": "严重错误：后端响应中缺少上传 URL。",
    "MEDIA_CHAT_UPLOAD_AUTH_MISSING": "聊天上传缺少身份验证 token",
    "MEDIA_CHAT_UPLOAD_TOKEN_FAILED": "聊天上传 token 请求失败",
    "MEDIA_CHAT_UPLOAD_INVALID_RESPONSE": "聊天上传响应无效",
    "MEDIA_GCS_UPLOAD_FAILED": "GCS 上传失败",
    "MEDIA_ERROR_MISSING_FILENAME_CONTENT_TYPE": "缺少 filename 或 contentType",
    "WEBHOOK_ERROR_MISSING_FILE_PATH": "缺少 file_path",
    "BLOCK_NOTICE_TITLE": "永久屏蔽通知",
    "BLOCK_NOTICE_MESSAGE": "由于违反政策，您的账户已被暂时暂停。",
    "BLOCK_NOTICE_CONTACT_PREFIX": "如果您认为这需要后续处理，请联系",
    "BLOCK_NOTICE_CONTACT_EMAIL": "collabra@otmega.com",
    "BLOCK_NOTICE_CONTACT_SUFFIX": "通过电子邮件。",
    "USER_BANNER_SAMPLE_NAME": "Nosrat Abouhamzeh",
    "USER_BANNER_SAMPLE_ROLE": "S_Admin",
    "USER_BANNER_SAMPLE_COIN_BALANCE": "1000.00 Φ",
    "GENERAL_UNKNOWN_USER": "未知用户",
    "GENERAL_GUEST": "访客",
    "ADVISOR_FOR_CLIENT": "{client_display_name} 的顾问",
    "GUEST_FOR_CLIENT": "",
    "AUTH_ERROR_TOKEN_PASSWORD_REQUIRED": "token 和密码为必填项",
    "AUTH_ERROR_REQUEST_BODY_JSON": "请求正文必须是 JSON",
    "AUTH_ERROR_INVITATION_TOKEN_INVALID_EXPIRED": "邀请 token 无效或已过期",
    "AUTH_ERROR_PASSWORD_SET_MISSING_SESSION_USER": "设置密码失败：缺少会话或用户",
    "AUTH_ERROR_PASSWORD_SET_SIGNIN_FAILED": "登录过程中设置密码失败",
    "AUTH_ERROR_ADMIN_TOKEN_GENERATION_FAILED": "管理员 token 生成失败",
    "AUTH_ERROR_LOGIN_MISSING_SESSION_USER": "登录失败：缺少会话或用户",
    "AUTH_REGISTRATION_SUCCESS_CHECK_EMAIL": "注册成功。请检查邮箱以完成验证。",
    "AUTH_ERROR_SIGNUP_FAILED_UNKNOWN": "注册失败，原因未知",
    "AUTH_ERROR_INVALID_TOKEN_PROCESSING": "无效的 token 处理",
    "AUTH_ERROR_ACCESS_TOKEN_REQUIRED": "需要访问 token",
    "AUTH_ERROR_TOKEN_HASH_PREVIEW_EMAIL_REQUIRED": "token 哈希预览需要来自重定向 URL 的邮箱提示",
    "AUTH_ERROR_RESOLVE_IDENTITY_FAILED": "无法为此 token 解析身份",
    "API_ERROR_USER_ZERO_WF1_SELECTOR_ONLY": "只有 User Zero 可以访问 WF1 LLM 选择器服务。",
    "API_ERROR_USER_ZERO_ZONE_VISIBILITY_ONLY": "只有 User Zero 可以访问区域可见性控制服务。",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_ONLY": "只有 User Zero 可以访问前端版本控制服务。",
    "API_ERROR_USER_ZERO_FRONTEND_VERSION_INSPECT_ONLY": "只有 User Zero 可以检查其他用户的前端版本。",
    "API_ERROR_USER_ZERO_CHAT_DELETE_ONLY": "只有 User Zero 可以访问聊天删除控制服务。",
    "API_ERROR_USER_ZERO_UI_TEXTS_RUNTIME_ONLY": "",
    "API_ERROR_USER_ZERO_PERMANENT_DELETE_ONLY": "只有 User Zero 可以永久删除用户账户。",
    "API_ERROR_INVALID_REQUEST_PAYLOAD": "请求 payload 无效。",
    "API_ERROR_INTERNAL_SERVER": "内部服务器错误",
    "API_ERROR_FUNCTION_MISSING_RELOAD_REQUIRED": "后端缺少函数（需要重新加载）",
    "API_ERROR_ONLY_DB_RPC_STATUS_TRANSITIONS": "delivered/read 转换只允许使用数据库 RPC。",
    "API_ERROR_PUBLIC_CONTACT_RATE_LIMIT": "请稍候再发送另一条消息。",
    "API_MESSAGE_PUBLIC_CONTACT_SENT": "消息已成功发送。",
    "API_ERROR_PUBLIC_CONTACT_UNAVAILABLE": "联系服务不可用。",
    "API_ERROR_PUBLIC_CONTACT_SEND_FAILED": "消息发送失败。",
    "API_ERROR_PUBLIC_CONTACT_NAME_REQUIRED": "姓名为必填项。",
    "API_ERROR_PUBLIC_CONTACT_EMAIL_INVALID": "邮箱无效。",
    "API_ERROR_PUBLIC_CONTACT_MESSAGE_REQUIRED": "消息为必填项。",
    "API_ERROR_SELECTOR_PAYLOAD_REQUIRED": "选择器 payload 为必填项。",
    "API_ERROR_ZONE_VISIBILITY_PAYLOAD_REQUIRED": "区域可见性 payload 为必填项。",
    "API_ERROR_FRONTEND_VERSION_PAYLOAD_REQUIRED": "前端版本 payload 为必填项。",
    "API_ERROR_CHAT_DELETE_PAYLOAD_REQUIRED": "聊天删除控制 payload 为必填项。",
    "API_ERROR_UI_TEXTS_RUNTIME_PAYLOAD_REQUIRED": "",
    "API_ERROR_AUTH_USER_ID_REQUIRED": "需要已认证用户 id。",
    "API_ERROR_AUTH_VIEWER_USER_ID_REQUIRED": "需要已认证查看者用户 id。",
    "API_ERROR_AUTH_ACTOR_USER_ID_REQUIRED": "需要已认证操作者用户 id。",
    "API_ERROR_TARGET_USER_ID_REQUIRED": "target_user_id 为必填项。",
    "API_ERROR_OWNER_USER_ID_REQUIRED": "owner_user_id 为必填项。",
    "API_ERROR_OWNER_USER_IDS_LIST_REQUIRED": "owner_user_ids 列表为必填项。",
    "API_ERROR_INVITATION_EMAIL_REQUIRED": "invitation_email 为必填项。",
    "API_ERROR_INVITED_BY_REQUIRED": "invited_by 为必填项。",
    "API_ERROR_SEARCH_RUNTIME_DISABLED": "搜索运行时已被全局前端版本禁用。",
    "API_ERROR_INVITE_CANCEL_NOT_ALLOWED": "您无权取消此待处理邀请。",
    "API_ERROR_INVITE_CANCEL_ALREADY_REGISTERED": "此邀请无法再取消，因为用户已经注册。",
    "API_ERROR_PENDING_INVITATION_NOT_FOUND": "未找到待处理邀请。",
    "INVITE_REPLY_ALREADY_MEMBER": "恭喜，您的朋友（{invitee_email}）已在此应用注册，并且是此工作区的成员。",
    "INVITE_REPLY_PENDING_RETRY_FAILED": "{invitee_email} 有一个待处理邀请，但无法触发重试邮件。请检查邮件日志。",
    "INVITE_REPLY_RECORD_CREATED_EMAIL_UNCONFIRMED": "已为 {invitee_email} 创建邀请记录，但无法确认邮件送达。请稍后重试或检查邮件日志。",
    "INVITE_REPLY_CREATE_RECORD_FAILED": "创建邀请记录失败。请稍后重试。",
    "INVITE_REPLY_SYSTEM_ERROR": "邀请流程中发生系统错误：{error}",
    "CHAT_ERROR_BACKEND_CONFIG_MISSING_SUPABASE": "后端配置错误：缺少 Supabase 凭据",
    "CHAT_ERROR_BACKEND_CONFIG_INVALID_SUPABASE_URL": "后端配置错误：Supabase URL 无效",
    "CHAT_ERROR_ACCESS_DENIED": "访问被拒绝",
    "CHAT_ERROR_CONTENT_EMPTY_TEXT": "文本消息的内容不能为空",
    "CHAT_ERROR_CONVERSATION_ID_UNDETERMINED": "无法确定会话 ID",
    "CHAT_ERROR_RPC_AUTH_CONTEXT_MISSING": "缺少 RPC 身份验证上下文",
    "CHAT_ERROR_RPC_INVALID_MESSAGE_PAYLOAD": "RPC 返回了无效的消息 payload",
    "CHAT_ERROR_INSERT_FAILED_NO_DATA": "插入失败，未返回数据",
    "CHAT_ERROR_OPERATIONS_LIST_REQUIRED": "operations 必须是列表",
    "CHAT_ERROR_INVALID_OPERATION_PAYLOAD": "操作 payload 无效",
    "CHAT_ERROR_UNSUPPORTED_OPERATION_TYPE": "不支持的 operation_type",
    "CHAT_ERROR_MESSAGE_ID_REQUIRED": "message_id 为必填项",
    "CHAT_ERROR_MESSAGE_NOT_FOUND": "未找到消息",
    "CHAT_ERROR_DELETE_OWN_MESSAGE_ONLY": "只能删除您自己的消息",
    "CHAT_ERROR_DELETE_WINDOW_EXPIRED": "此消息已无法再为所有人删除",
    "CHAT_ERROR_DELETE_FOR_EVERYONE_FAILED": "为所有人删除失败",
    "API_ERROR_SERVER_CONFIGURATION": "服务器配置错误",
    "API_ERROR_MISSING_WEBHOOK_SECRET_HEADER": "缺少 webhook secret header",
    "API_ERROR_UNAUTHORIZED_WEBHOOK_SOURCE": "未授权的 webhook 来源",
    "API_ERROR_BACKEND_CONFIGURATION": "后端配置错误",
    "API_ERROR_MODULE_ATTRIBUTE": "模块属性错误：{error}",
    "API_ERROR_INVITE_DELETE_WAITING_AUTH_USER_FAILED": "移除等待中的认证用户时，在删除邀请之前失败。",
    "CHAT_ERROR_DB": "数据库错误：{error}",
}
